### ISSUE TITLE
Update supported php versions

### ISSUE THREAD

**Issue by soilSpoon** [laravel/valet#1002]
Currently, php 7.1 or lower is not supported. And PHPUnit is also not supported under 7.1 (currently only PHPUnit8 and PHPUnit9 are supported), and Laravel 6, the lowest supported Laravel, only supports php 7.2.5 or higher.

Using such a supported language or library may lead to security flaws and performance may be poor.

I think it is correct to discard the dead version by changing the major version.

## Reference
[PHP Supported Versions](https://www.php.net/supported-versions.php)
[PHPUnit Supported Versions](https://phpunit.de/supported-versions.html)
[Laravel Support Policy](https://laravel.com/docs/8.x/releases#support-policy)
[#987 comment](https://github.com/laravel/valet/issues/987#issuecomment-734712515)

**Comment by drbyte** [comment]
Your points are fully understood. And I agree it's much easier to support only the latest versions.

But people use Valet specifically to be able to use, and swap between, older PHP versions. Valet needs to still run when those are the active versions.
Hence the continued support of the older test suite.

I suppose we could have two sets of tests, which run accordingly when a compatible php version is selected in the test suite. (Newer syntax tests being default, older format being used on older php versions)

**Comment by soilSpoon** [comment]
But PHP 7.1or lower is not active version.
Upgrade is recommended.

![Screen Shot 2020-11-28 at 4 41 43 PM](https://user-images.githubusercontent.com/9105017/100496628-5aef5380-310a-11eb-86b9-0d445c5807c4.png)

**Comment by mattstauffer** [comment]
The reality is there are hundreds of thousands of PHP projects out there running on PHP 7 and 7.1 and I want those folks to be able to do their jobs. At my company alone we regularly take over older projects and migrate them, and not having access to our normal tooling would be a pain.  

I haven't checked, but are we at a point where 7.1 and 8.0 can't use the same version of PHPUnit?

**Comment by mattstauffer** [comment]
Never mind, I just read the link. I think we're gonna have to maintain two suites of tests but that is really frustrating that they have such narrow version constraints.￼

**Comment by mattstauffer** [comment]
https://twitter.com/Mark_Baker/status/1332704583395782656?s=20

**Comment by soilSpoon** [comment]
> https://twitter.com/Mark_Baker/status/1332704583395782656?s=20

@mattstauffer @drbyte Take a look at [PHPUnit Bridge](https://symfony.com/doc/current/components/phpunit_bridge.html), it's similar
I also implemented it #1009
