### ISSUE TITLE
Unable to Update Valet

### ISSUE THREAD

**Issue by alexbowers** [laravel/valet#102]
```
➜  vagrant-config git:(master) valet update
/Users/alexbowers/.composer/vendor/laravel/valet/cli/scripts/update.sh: line 4: /Users/alexbowers/.valet-cli/valet: No such file or directory
Downloading latest release of Valet...
/Users/alexbowers/.composer/vendor/laravel/valet/cli/scripts/update.sh: line 18: jq: command not found
(23) Failed writing body
Installing Valet's Composer dependencies...

Valet installed successfully!
/Users/alexbowers/.composer/vendor/laravel/valet/cli/scripts/update.sh: line 31: /Users/alexbowers/.valet-cli/valet: No such file or directory
```

```
➜  vagrant-config git:(master) valet --version
Laravel Valet version 1.1.12
```

**Comment by alexbowers** [comment]
Doing a `composer global update` to update valet doesn't work either. It just says I'm up to date.

**Comment by drbyte** [comment]
That's because the 1.1.13 release was tagged on a commit prior to the version-update commit.

A fresh install will give you the 1.1.13 code features but will still not display the right version number.

Additionally, you might have to the `brew install jq` dependency manually.

**Comment by alexbowers** [comment]
What is `jq`?

I'd like to not install random stuff if possible.

**Comment by drbyte** [comment]
It's `sed` for json files: https://stedolan.github.io/jq/

It's now installed by valet if not present, but only on fresh installs:
https://github.com/laravel/valet/blob/acc06387ae2daaf8116e7664b5cd72f0d941388e/cli/scripts/install.sh#L10

however, the upgrade expects it to be present, and fails if it's not:
https://github.com/laravel/valet/blob/fbe2fe6fac3f0d1e9a6cab35484b5f623e1bb001/cli/scripts/update.sh#L18

**Comment by alexbowers** [comment]
Ok cool, installing jq got rid of that error, but the rest of them are still there.

**Comment by adamwathan** [comment]
It sounds like it's looking for files in ~/.valet-cli that you might not have, in this case you can use `valet install` to run everything from scratch, but might lose some of your settings. Sorry about the trouble!

**Comment by alexbowers** [comment]
Unfortunately, `valet install` does not work.

```
➜  ~ valet install

Valet installed successfully!
➜  ~ valet update
/Users/alex/.composer/vendor/laravel/valet/cli/scripts/update.sh: line 4: /Users/alex/.valet-cli/valet: No such file or directory
Downloading latest release of Valet...
Installing Valet's Composer dependencies...

Valet installed successfully!
/Users/alex/.composer/vendor/laravel/valet/cli/scripts/update.sh: line 31: /Users/alex/.valet-cli/valet: No such file or directory
```

**Comment by alexbowers** [comment]
Doesn't work `uninstall` -> `install` -> `update` still has the same issues

**Comment by alexbowers** [comment]
Would it be possible to get another tag on this to see if it skips `1.1.13` and goes straight to `1.1.14` that may fix some of the issues.

**Comment by adamwathan** [comment]
Ok after looking into this a bit, the problem is that we recklessly published some undocumented stuff that you shouldn't really be using yet 👀

`valet update` only works if you installed Valet using an as-of-yet undocumented approach that we were playing with for keeping Valet out of your global composer dependencies, to avoid version conflicts and stuff.

Just rely on `composer global update` to manage Valet, and don't worry about ever running `valet update`.

I did tag 1.1.14 anyways, but will likely remove that command for now and tag 1.1.15 soon to avoid this mistake in the future.

**Comment by drbyte** [comment]
I just ran `valet update` and it worked fine for 1.1.14

... but (for reference with the not-yet-released `update` revert) it did overwrite the customizations I'd made to my `~/.valet/dnsmasq.conf` file.

**Comment by adamwathan** [comment]
@drbyte do you have a symlink at `~/.valet-cli/valet` that points to your Valet executable? It shouldn't work without that, and you shouldn't have that symlink unless you were using the work-in-progress install approach that no one should be using, haha...

**Comment by drbyte** [comment]
@adamwathan should I delete the entire `~/.valet-cli` folder?

**Comment by drbyte** [comment]
Running `composer global update` has it working fine for me now.

**Comment by alexbowers** [comment]
Right, im up to `1.1.16` now which is good. I didnt realise that update wasn't supposed to be used yet. My bad :P

**Comment by adamwathan** [comment]
Yeah no way you would have known, our fault! Hopefully all good now.
