### ISSUE TITLE
Error establishing a database connection

### ISSUE THREAD

**Issue by aryanrajcom** [laravel/valet#1020]
I recently upgraded to Big Sur and the valet (WordPress) websites start throwing the error "502 Bad Gateway nginx/1.19.6" so i made the necessary updates from here https://laravel.com/docs/8.x/valet#introduction

Also uninstalled and re-installed, switched to PHP 7.2 but now sites showing "Error establishing a database connection" and seems like DB file is missing as i am not able login on host 127.0.0.1 with root username.

<details>
<summary>sw_vers</summary>
<pre>ProductName:	macOS
ProductVersion:	11.1
BuildVersion:	20C69</pre>
</details>
<details>
<summary>valet --version</summary>
<pre>Laravel Valet 2.13.16</pre>
</details>
<details>
<summary>cat ~/.config/valet/config.json</summary>
<pre>{
    "domain": "test",
    "paths": [
        "/Users/aryanraj/.config/valet/Sites",
        "/Users/aryanraj/Sites",
        "/Users/aryanraj/Sites/Blog",
    ],
    "tld": "test"
}</pre>
</details>
<details>
<summary>cat ~/.composer/composer.json</summary>
<pre>{
    "require": {
        "laravel/valet": "^2.13",
        "squizlabs/php_codesniffer": "*"
    }
}</pre>
</details>
<details>
<summary>composer global diagnose</summary>
<pre>Changed current directory to /Users/aryanraj/.composer
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
require.squizlabs/php_codesniffer : unbound version constraints (*) should be avoided
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 2.0.8
PHP version: 7.2.34
PHP binary path: /usr/local/Cellar/php@7.2/7.2.34_1/bin/php
OpenSSL version: OpenSSL 1.1.1h  22 Sep 2020
cURL version: 7.74.0 libz 1.2.11 ssl (SecureTransport) OpenSSL/1.1.1i
zip: extension present, unzip present</pre>
</details>
<details>
<summary>composer global outdated</summary>
<pre>Changed current directory to /Users/aryanraj/.composer</pre>
</details>
<details>
<summary>ls -al /etc/sudoers.d/</summary>
<pre>total 16
drwxr-xr-x    4 root  wheel   128 Jan  7 20:21 .
drwxr-xr-x  120 root  wheel  3840 Jan  9 20:09 ..
-rw-r--r--    1 root  wheel    80 Sep 25 19:44 brew
-rw-r--r--    1 root  wheel    83 Sep 25 19:44 valet</pre>
</details>
<details>
<summary>brew config</summary>
<pre>HOMEBREW_VERSION: 2.7.2
ORIGIN: https://github.com/Homebrew/brew
HEAD: dad7dc6a1498b80770d98f2d7cd6fb927c300bbb
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: c01e0d67406094febb52a24f910044a755d8452c
Core tap last commit: 10 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.Kxl4RjcgKv/org.macosforge.xquartz:0
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: quad-core 64-bit skylake
Clang: 12.0 build 1200
Git: 2.21.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 1.8.0_161
macOS: 11.1-x86_64
CLT: 12.3.0.0.1.1607026830
Xcode: N/A
XQuartz: 2.7.11 => /opt/X11</pre>
</details>
<details>
<summary>brew services list</summary>
<pre>Name    Status  User           Plist
dnsmasq error   root           /Library/LaunchDaemons/homebrew.mxcl.dnsmasq.plist
mariadb started aryanraj /Users/aryanraj/Library/LaunchAgents/homebrew.mxcl.mariadb.plist
nginx   error   root           /Library/LaunchDaemons/homebrew.mxcl.nginx.plist
php     started aryanraj /Users/aryanraj/Library/LaunchAgents/homebrew.mxcl.php.plist
php@7.2 started root           /Library/LaunchDaemons/homebrew.mxcl.php@7.2.plist</pre>
</details>
<details>
<summary>brew list --formula --versions | grep -E "(php|nginx|dnsmasq|mariadb|mysql|mailhog|openssl)(@\d\..*)?\s"</summary>
<pre>dnsmasq 2.82
mariadb 10.2.14
nginx 1.19.6
openssl 1.0.2o_1
openssl@1.1 1.1.1i
php 8.0.1
php@7.2 7.2.34_1</pre>
</details>
<details>
<summary>brew outdated</summary>
<pre>composer
mariadb
wp-cli
copyq</pre>
</details>
<details>
<summary>brew tap</summary>
<pre>caskroom/cask
homebrew/core
homebrew/services
shivammathur/php</pre>
</details>
<details>
<summary>php -v</summary>
<pre>PHP 7.2.34 (cli) (built: Nov 30 2020 14:13:42) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.34, Copyright (c) 1999-2018, by Zend Technologies</pre>
</details>
<details>
<summary>which -a php</summary>
<pre>/usr/local/bin/php
/usr/bin/php</pre>
</details>
<details>
<summary>php --ini</summary>
<pre>Configuration File (php.ini) Path: /usr/local/etc/php/7.2
Loaded Configuration File:         /usr/local/etc/php/7.2/php.ini
Scan for additional .ini files in: /usr/local/etc/php/7.2/conf.d
Additional .ini files parsed:      /usr/local/etc/php/7.2/conf.d/error_log.ini,
/usr/local/etc/php/7.2/conf.d/ext-opcache.ini,
/usr/local/etc/php/7.2/conf.d/php-memory-limits.ini</pre>
</details>
<details>
<summary>nginx -v</summary>
<pre>nginx version: nginx/1.19.6</pre>
</details>
<details>
<summary>curl --version</summary>
<pre>curl 7.64.1 (x86_64-apple-darwin20.0) libcurl/7.64.1 (SecureTransport) LibreSSL/2.8.3 zlib/1.2.11 nghttp2/1.41.0
Release-Date: 2019-03-27
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS GSS-API HTTP2 HTTPS-proxy IPv6 Kerberos Largefile libz MultiSSL NTLM NTLM_WB SPNEGO SSL UnixSockets</pre>
</details>
<details>
<summary>php --ri curl</summary>
<pre>curl

cURL support => enabled
cURL Information => 7.74.0
Age => 7
Features
AsynchDNS => Yes
CharConv => No
Debug => No
GSS-Negotiate => No
IDN => Yes
IPv6 => Yes
krb4 => No
Largefile => Yes
libz => Yes
NTLM => Yes
NTLMWB => Yes
SPNEGO => Yes
SSL => Yes
SSPI => No
TLS-SRP => Yes
HTTP2 => Yes
GSSAPI => Yes
KERBEROS5 => Yes
UNIX_SOCKETS => Yes
PSL => No
Protocols => dict, file, ftp, ftps, gopher, http, https, imap, imaps, ldap, ldaps, mqtt, pop3, pop3s, rtmp, rtsp, scp, sftp, smb, smbs, smtp, smtps, telnet, tftp
Host => x86_64-apple-darwin20.2.0
SSL Version => (SecureTransport) OpenSSL/1.1.1i
ZLib Version => 1.2.11
libSSH Version => libssh2/1.9.0</pre>
</details>
<details>
<summary>~/.composer/vendor/laravel/valet/bin/ngrok version</summary>
<pre>ngrok version 2.3.35</pre>
</details>
<details>
<summary>ls -al ~/.ngrok2</summary>
<pre>ls: /Users/aryanraj/.ngrok2: No such file or directory</pre>
</details>
<details>
<summary>brew info nginx</summary>
<pre>nginx: stable 1.19.6 (bottled), HEAD
HTTP(S) server and reverse proxy, and IMAP/POP3 proxy server
https://nginx.org/
/usr/local/Cellar/nginx/1.19.6 (25 files, 2.2MB) *
  Poured from bottle on 2021-01-09 at 20:57:56
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/nginx.rb
License: BSD-2-Clause
==> Dependencies
Required: openssl@1.1, pcre
==> Options
--HEAD
	Install HEAD version
==> Caveats
Docroot is: /usr/local/var/www

The default port has been set in /usr/local/etc/nginx/nginx.conf to 8080 so that
nginx can run without sudo.

nginx will load all files in /usr/local/etc/nginx/servers/.

To have launchd start nginx now and restart at login:
  brew services start nginx
Or, if you don't want/need a background service you can just run:
  nginx
==> Analytics
install: 44,356 (30 days), 139,135 (90 days), 453,596 (365 days)
install-on-request: 44,265 (30 days), 137,754 (90 days), 443,574 (365 days)
build-error: 0 (30 days)</pre>
</details>
<details>
<summary>brew info php</summary>
<pre>php: stable 8.0.1 (bottled), HEAD
General-purpose scripting language
https://www.php.net/
/usr/local/Cellar/php/8.0.1 (499 files, 77.8MB)
  Poured from bottle on 2021-01-09 at 20:58:29
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/php.rb
License: PHP-3.01
==> Dependencies
Build: httpd, pkg-config
Required: apr, apr-util, argon2, aspell, autoconf, curl, freetds, gd, gettext, glib, gmp, icu4c, krb5, libffi, libpq, libsodium, libzip, oniguruma, openldap, openssl@1.1, pcre2, sqlite, tidy-html5, unixodbc
==> Options
--HEAD
	Install HEAD version
==> Caveats
To enable PHP in Apache add the following to httpd.conf and restart Apache:
    LoadModule php_module /usr/local/opt/php/lib/httpd/modules/libphp.so

    <FilesMatch \.php$>
        SetHandler application/x-httpd-php
    </FilesMatch>

Finally, check DirectoryIndex includes index.php
    DirectoryIndex index.php index.html

The php.ini and php-fpm.ini file can be found in:
    /usr/local/etc/php/8.0/

To have launchd start php now and restart at login:
  brew services start php
Or, if you don't want/need a background service you can just run:
  php-fpm
==> Analytics
install: 40,867 (30 days), 162,549 (90 days), 602,494 (365 days)
install-on-request: 40,131 (30 days), 159,439 (90 days), 578,550 (365 days)
build-error: 0 (30 days)</pre>
</details>
<details>
<summary>brew info openssl</summary>
<pre>openssl@1.1: stable 1.1.1i (bottled) [keg-only]
Cryptography and SSL/TLS Toolkit
https://openssl.org/
/usr/local/Cellar/openssl/1.0.2o_1 (1,791 files, 12.3MB)
  Poured from bottle on 2018-04-21 at 18:01:09
/usr/local/Cellar/openssl@1.1/1.1.1i (8,067 files, 18.5MB)
  Poured from bottle on 2021-01-09 at 16:57:55
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/openssl@1.1.rb
License: OpenSSL
==> Caveats
A CA file has been bootstrapped using certificates from the system
keychain. To add additional certificates, place .pem files in
  /usr/local/etc/openssl@1.1/certs

and run
  /usr/local/opt/openssl@1.1/bin/c_rehash

openssl@1.1 is keg-only, which means it was not symlinked into /usr/local,
because macOS provides LibreSSL.

If you need to have openssl@1.1 first in your PATH run:
  echo 'export PATH="/usr/local/opt/openssl@1.1/bin:$PATH"' >> /Users/aryanraj/.bash_profile

For compilers to find openssl@1.1 you may need to set:
  export LDFLAGS="-L/usr/local/opt/openssl@1.1/lib"
  export CPPFLAGS="-I/usr/local/opt/openssl@1.1/include"

==> Analytics
install: 868,823 (30 days), 2,442,138 (90 days), 7,928,373 (365 days)
install-on-request: 144,126 (30 days), 396,634 (90 days), 1,138,004 (365 days)
build-error: 0 (30 days)</pre>
</details>
<details>
<summary>openssl version -a</summary>
<pre>LibreSSL 2.8.3
built on: date not available
platform: information not available
options:  bn(64,64) rc4(16x,int) des(idx,cisc,16,int) blowfish(idx) 
compiler: information not available
OPENSSLDIR: "/private/etc/ssl"</pre>
</details>
<details>
<summary>openssl ciphers</summary>
<pre>ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-CHACHA20-POLY1305:GOST2012256-GOST89-GOST89:DHE-RSA-CAMELLIA256-SHA256:DHE-RSA-CAMELLIA256-SHA:GOST2001-GOST89-GOST89:AES256-GCM-SHA384:AES256-SHA256:AES256-SHA:CAMELLIA256-SHA256:CAMELLIA256-SHA:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-CAMELLIA128-SHA256:DHE-RSA-CAMELLIA128-SHA:AES128-GCM-SHA256:AES128-SHA256:AES128-SHA:CAMELLIA128-SHA256:CAMELLIA128-SHA:ECDHE-RSA-RC4-SHA:ECDHE-ECDSA-RC4-SHA:RC4-SHA:RC4-MD5:ECDHE-RSA-DES-CBC3-SHA:ECDHE-ECDSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:DES-CBC3-SHA</pre>
</details>
<details>
<summary>sudo nginx -t</summary>
<pre>nginx: the configuration file /usr/local/etc/nginx/nginx.conf syntax is ok
nginx: configuration file /usr/local/etc/nginx/nginx.conf test is successful</pre>
</details>
<details>
<summary>which -a php-fpm</summary>
<pre>/usr/sbin/php-fpm</pre>
</details>
<details>
<summary>/usr/local/opt/php/sbin/php-fpm -v</summary>
<pre>PHP 8.0.1 (fpm-fcgi) (built: Jan  7 2021 19:01:55)
Copyright (c) The PHP Group
Zend Engine v4.0.1, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.1, Copyright (c), by Zend Technologies</pre>
</details>
<details>
<summary>sudo /usr/local/opt/php/sbin/php-fpm -y /usr/local/etc/php/7.2/php-fpm.conf --test</summary>
<pre>[09-Jan-2021 22:29:46] NOTICE: configuration file /usr/local/etc/php/7.2/php-fpm.conf test is successful</pre>
</details>
<details>
<summary>ls -al ~/Library/LaunchAgents | grep homebrew</summary>
<pre>-rw-r--r--    1 aryanraj  staff   576 Jan  9 20:39 homebrew.mxcl.dnsmasq.plist
-rw-r--r--    1 aryanraj  staff   541 Jan  9 20:52 homebrew.mxcl.mariadb.plist
-rw-r--r--    1 aryanraj  staff   571 Jan  9 20:39 homebrew.mxcl.nginx.plist
-rw-r--r--    1 aryanraj  staff   628 Jan  9 20:39 homebrew.mxcl.php.plist</pre>
</details>
<details>
<summary>ls -al /Library/LaunchAgents | grep homebrew</summary>
<pre></pre>
</details>
<details>
<summary>ls -al /Library/LaunchDaemons | grep homebrew</summary>
<pre>-rw-r--r--   1 root  admin   657 Jan  9 22:25 homebrew.mxcl.dnsmasq.plist
-rw-r--r--   1 root  admin   571 Jan  9 22:25 homebrew.mxcl.nginx.plist
-rw-r--r--   1 root  admin   636 Jan  9 22:25 homebrew.mxcl.php@7.2.plist</pre>
</details>
<details>
<summary>ls -aln /etc/resolv.conf</summary>
<pre>lrwxr-xr-x  1 0  0  22 Jan  1  2020 /etc/resolv.conf -> ../var/run/resolv.conf</pre>
</details>
<details>
<summary>cat /etc/resolv.conf</summary>
<pre>#
# macOS Notice
#
# This file is not consulted for DNS hostname resolution, address
# resolution, or the DNS query routing mechanism used by most
# processes on this system.
#
# To view the DNS configuration used by this system, use:
#   scutil --dns
#
# SEE ALSO
#   dns-sd(1), scutil(8)
#
# This file is automatically generated.
#
nameserver 1.1.1.1
nameserver 1.0.0.1</pre>
</details>

**Comment by drbyte** [comment]
Valet has nothing to do with database services.

Nevertheless, there are other things you should address:

`brew services list` shows several services in "error" state. This is most likely because you have them set to run both as non-root and root upon startup. 
Valet normally runs dnsmasq, nginx, and php as root. Other services you choose to run probably shouldn't be run as root.

To clean up these specific services, I suggest the following:
`valet stop`
`brew services stop dnsmasq`
`brew services stop nginx`
`brew services stop php`

Then running `brew services list` will probably show that only your mariadb service is running.
You might then want to upgrade your mariadb, and other services using `brew upgrade`.

After that I suggest a reboot. 
Then `valet start`.

After that you can work on sorting out your database issues.

**Comment by aryanrajcom** [comment]
oh okay, laravel setup is working so i am closing this.

**Comment by iantearle** [comment]
@aryanrajcom did you set the host? 
Just in case anyone else comes across this, WordPress CLI automatically defaults to localhost, Valet world MySQL should be 127.0.0.1

In terms of CLI `wp config create --dbhost=127.0.0.1`

**Comment by ihorvorotnov** [comment]
Default connection method in MySQL and MariaDB have changed some time ago. If you have a standard Homebrew install, for WordPress your config should look like:
```
define( 'DB_NAME', 'your_database_name' );
define( 'DB_USER', 'your_macos_user_name' );
define( 'DB_PASSWORD', '' );
define( 'DB_HOST', 'localhost:/tmp/mysql.sock' );
```
