### ISSUE TITLE
Wording of the documentation re: Valet Daemon

### ISSUE THREAD

**Issue by mgussekloo** [laravel/valet#1021]
The documentation says "Finally, you may execute Valet's install command. This will configure and install Valet and DnsMasq. In addition, the Valet daemon will be configured to launch when your system starts."

It seems that there is no Valet Daemon, it's just that Valet configures separate "brew services" for DnsMasq, Nginx and PHP. Or am I missing something? I could make a PR to try and re-word.

**Comment by drbyte** [comment]
On a strictly technical level you are correct that Valet has no daemon of its own.

Valet tells Homebrew to configure each of the necessary services (which are essentially daemons in their own right) to start upon subsequent boots of the operating system. But that's a lot more wordy.

I suppose one could accurately change `the Valet daemon will` to `the services upon which Valet depends will`.

I dunno.
See what Matt and Taylor think.

**Comment by mattstauffer** [comment]
I think this is a great suggestion, yah:

> Finally, you may execute Valet's install command. This will configure and install Valet and DnsMasq. In addition, the daemons Valet depends on will be configured to launch when your system starts.

**Comment by drbyte** [comment]
Docs have been updated. @mgussekloo you can click "Close" below to close this issue.
