### ISSUE TITLE
Valet share works but shows Connection refused

### ISSUE THREAD

**Issue by markandrewkato** [laravel/valet#1022]
## Clear description of your problem
Whenever I start valet share, it works, however, it shows the error below:
```
In Request.php line 1060:

  Unable to connect to "http://127.0.0.1:4041/api/tunnels": 7 Failed to connect to 127.0.0.1 port 4041: Connection refused


fetch-share-url [<domain>]
```

## Expected behavior
It should not show the error in the description

## Current behavior
Shows the error in the description

## Steps to Reproduce
1. Open iTerm or Terminal
2. Run `valet share`

### Output of these steps
Shows the error in the description

## Diagnosis
<details>
<summary>sw_vers</summary>
<pre>ProductName:	macOS
ProductVersion:	11.1
BuildVersion:	20C69</pre>
</details>
<details>
<summary>valet --version</summary>
<pre>Laravel Valet 2.13.16</pre>
</details>
<details>
<summary>cat ~/.config/valet/config.json</summary>
<pre>{
    "tld": "test",
    "paths": [
        "/Users/markandrewkato/.config/valet/Sites"
    ]
}</pre>
</details>
<details>
<summary>cat ~/.composer/composer.json</summary>
<pre>{
    "require": {
        "phpunit/phpunit": "^8.0",
        "squizlabs/php_codesniffer": "*",
        "friendsofphp/php-cs-fixer": "^2.15",
        "beyondcode/expose": "^1.3",
        "laravel/installer": "^4.0",
        "laravel/valet": "^2.13"
    }
}</pre>
</details>
<details>
<summary>composer global diagnose</summary>
<pre>Changed current directory to /Users/markandrewkato/.composer
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
require.squizlabs/php_codesniffer : unbound version constraints (*) should be avoided
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: You are not running the latest stable version, run `composer self-update` to update (1.10.19 => 2.0.8)
Composer version: 1.10.19
PHP version: 7.3.26
PHP binary path: /usr/local/Cellar/php@7.3/7.3.26/bin/php
OpenSSL version: OpenSSL 1.1.1i  8 Dec 2020</pre>
</details>
<details>
<summary>composer global outdated</summary>
<pre>Changed current directory to /Users/markandrewkato/.composer
beyondcode/expose                  1.4.1   ! 1.5.0   Expose
composer/ca-bundle                 1.2.8   ! 1.2.9   Lets you find a path to the system CA bundle, and includes a fallback to the Mozilla CA bundle.
illuminate/container               v8.21.0 ! v8.22.1 The Illuminate Container package.
illuminate/contracts               v8.21.0 ! v8.22.1 The Illuminate Contracts package.
padraic/phar-updater               v1.0.6  = v1.0.6  A thing to make PHAR self-updating easy and secure.
Package padraic/phar-updater is abandoned, you should avoid using it. No replacement was suggested.
php-cs-fixer/diff                  v1.3.1  ~ v2.0.2  sebastian/diff v2 backport support for PHP5.6
phpunit/php-code-coverage          7.0.14  ~ 9.2.5   Library that provides collection, processing, and rendering functionality for PHP code coverage information.
phpunit/php-file-iterator          2.0.3   ~ 3.0.5   FilterIterator implementation that filters files based on a list of suffixes.
phpunit/php-text-template          1.2.1   ~ 2.0.4   Simple template engine.
phpunit/php-timer                  2.1.3   ~ 5.0.3   Utility class for timing
phpunit/php-token-stream           4.0.4   = 4.0.4   Wrapper around PHP's tokenizer extension.
Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.
phpunit/phpunit                    8.5.13  ~ 9.5.0   The PHP Unit Testing framework.
sebastian/code-unit-reverse-lookup 1.0.2   ~ 2.0.3   Looks up which function or method a line of code belongs to
sebastian/comparator               3.0.3   ~ 4.0.6   Provides the functionality to compare PHP values for equality
sebastian/diff                     3.0.3   ~ 4.0.4   Diff implementation
sebastian/environment              4.2.4   ~ 5.1.3   Provides functionality to handle HHVM/PHP environments
sebastian/exporter                 3.1.3   ~ 4.0.3   Provides the functionality to export PHP variables for visualization
sebastian/global-state             3.0.1   ~ 5.0.2   Snapshotting of global state
sebastian/object-enumerator        3.0.4   ~ 4.0.4   Traverses array structures and object graphs to enumerate all referenced objects
sebastian/object-reflector         1.1.2   ~ 2.0.4   Allows reflection of object attributes, including inherited and non-public ones
sebastian/recursion-context        3.0.1   ~ 4.0.4   Provides functionality to recursively process PHP variables
sebastian/resource-operations      2.0.2   ~ 3.0.3   Provides a list of PHP built-in functions that operate on resources
sebastian/type                     1.1.4   ~ 2.3.1   Collection of value objects that represent the types of the PHP type system
sebastian/version                  2.0.1   ~ 3.0.2   Library that helps with managing the version number of Git-hosted PHP projects</pre>
</details>
<details>
<summary>ls -al /etc/sudoers.d/</summary>
<pre>total 0
drwxr-xr-x    2 root  wheel    64 Jan  1  2020 .
drwxr-xr-x  123 root  wheel  3936 Jan 14 14:06 ..</pre>
</details>
<details>
<summary>brew config</summary>
<pre>HOMEBREW_VERSION: 2.7.4
ORIGIN: https://github.com/Homebrew/brew
HEAD: 663b972f449b679512a2c0e3303569a2e9bfba7c
Last commit: 15 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 0e82534aabee579c6c040137ca9cef17498e681b
Core tap last commit: 13 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.17sxlDWYji/org.macosforge.xquartz:0
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: quad-core 64-bit broadwell
Clang: 12.0 build 1200
Git: 2.30.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 1.8.0_121
macOS: 11.1-x86_64
CLT: 12.3.0.0.1.1607026830
Xcode: N/A
XQuartz: 2.7.11 => /opt/X11</pre>
</details>
<details>
<summary>brew services list</summary>
<pre>Name    Status  User           Plist
dnsmasq started root           /Library/LaunchDaemons/homebrew.mxcl.dnsmasq.plist
httpd   stopped                
nginx   started root           /Library/LaunchDaemons/homebrew.mxcl.nginx.plist
php     stopped                
php@7.3 started root           /Library/LaunchDaemons/homebrew.mxcl.php@7.3.plist
redis   started markandrewkato /Users/markandrewkato/Library/LaunchAgents/homebrew.mxcl.redis.plist
unbound stopped</pre>
</details>
<details>
<summary>brew list --formula --versions | grep -E "(php|nginx|dnsmasq|mariadb|mysql|mailhog|openssl)(@\d\..*)?\s"</summary>
<pre>dnsmasq 2.82
nginx 1.19.6
openssl@1.1 1.1.1i
php 8.0.1
php@7.3 7.3.26</pre>
</details>
<details>
<summary>brew outdated</summary>
<pre>apr
cmake
doxygen
ffmpeg
gnupg
htop
httpd
imagemagick
jasper
libffi
node
node@10
p7zip
php
php@7.3
python@3.9
rav1e
redis
stripe/stripe-cli/stripe</pre>
</details>
<details>
<summary>brew tap</summary>
<pre>exolnet/deprecated
homebrew/cask
homebrew/cask-versions
homebrew/core
homebrew/services
jdpedrie/php55
shivammathur/php
stripe/stripe-cli</pre>
</details>
<details>
<summary>php -v</summary>
<pre>PHP 7.3.26 (cli) (built: Jan  5 2021 14:23:37) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.26, Copyright (c) 1998-2018 Zend Technologies
    with Xdebug v2.9.8, Copyright (c) 2002-2020, by Derick Rethans
    with Zend OPcache v7.3.26, Copyright (c) 1999-2018, by Zend Technologies</pre>
</details>
<details>
<summary>which -a php</summary>
<pre>/usr/local/bin/php
/usr/bin/php</pre>
</details>
<details>
<summary>php --ini</summary>
<pre>Configuration File (php.ini) Path: /usr/local/etc/php/7.3
Loaded Configuration File:         /usr/local/etc/php/7.3/php.ini
Scan for additional .ini files in: /usr/local/etc/php/7.3/conf.d
Additional .ini files parsed:      /usr/local/etc/php/7.3/conf.d/error_log.ini,
/usr/local/etc/php/7.3/conf.d/ext-opcache.ini,
/usr/local/etc/php/7.3/conf.d/php-memory-limits.ini</pre>
</details>
<details>
<summary>nginx -v</summary>
<pre>nginx version: nginx/1.19.6</pre>
</details>
<details>
<summary>curl --version</summary>
<pre>curl 7.64.1 (x86_64-apple-darwin20.0) libcurl/7.64.1 (SecureTransport) LibreSSL/2.8.3 zlib/1.2.11 nghttp2/1.41.0
Release-Date: 2019-03-27
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS GSS-API HTTP2 HTTPS-proxy IPv6 Kerberos Largefile libz MultiSSL NTLM NTLM_WB SPNEGO SSL UnixSockets</pre>
</details>
<details>
<summary>php --ri curl</summary>
<pre>curl

cURL support => enabled
cURL Information => 7.74.0
Age => 7
Features
AsynchDNS => Yes
CharConv => No
Debug => No
GSS-Negotiate => No
IDN => Yes
IPv6 => Yes
krb4 => No
Largefile => Yes
libz => Yes
NTLM => Yes
NTLMWB => Yes
SPNEGO => Yes
SSL => Yes
SSPI => No
TLS-SRP => Yes
HTTP2 => Yes
GSSAPI => Yes
KERBEROS5 => Yes
UNIX_SOCKETS => Yes
PSL => No
HTTPS_PROXY => Yes
MULTI_SSL => Yes
BROTLI => Yes
Protocols => dict, file, ftp, ftps, gopher, http, https, imap, imaps, ldap, ldaps, mqtt, pop3, pop3s, rtmp, rtsp, scp, sftp, smb, smbs, smtp, smtps, telnet, tftp
Host => x86_64-apple-darwin20.2.0
SSL Version => (SecureTransport) OpenSSL/1.1.1i
ZLib Version => 1.2.11
libSSH Version => libssh2/1.9.0

Directive => Local Value => Master Value
curl.cainfo => no value => no value</pre>
</details>
<details>
<summary>~/.composer/vendor/laravel/valet/bin/ngrok version</summary>
<pre>ngrok version 2.3.35</pre>
</details>
<details>
<summary>ls -al ~/.ngrok2</summary>
<pre>ls: /Users/markandrewkato/.ngrok2: No such file or directory</pre>
</details>
<details>
<summary>brew info nginx</summary>
<pre>nginx: stable 1.19.6 (bottled), HEAD
HTTP(S) server and reverse proxy, and IMAP/POP3 proxy server
https://nginx.org/
/usr/local/Cellar/nginx/1.19.6 (25 files, 2.2MB) *
  Poured from bottle on 2021-01-08 at 21:26:53
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/nginx.rb
License: BSD-2-Clause
==> Dependencies
Required: openssl@1.1, pcre
==> Options
--HEAD
	Install HEAD version
==> Caveats
Docroot is: /usr/local/var/www

The default port has been set in /usr/local/etc/nginx/nginx.conf to 8080 so that
nginx can run without sudo.

nginx will load all files in /usr/local/etc/nginx/servers/.

To have launchd start nginx now and restart at login:
  brew services start nginx
Or, if you don't want/need a background service you can just run:
  nginx
==> Analytics
install: 43,540 (30 days), 136,346 (90 days), 454,794 (365 days)
install-on-request: 43,447 (30 days), 135,066 (90 days), 444,934 (365 days)
build-error: 0 (30 days)</pre>
</details>
<details>
<summary>brew info php</summary>
<pre>php: stable 8.0.1 (bottled), HEAD
General-purpose scripting language
https://www.php.net/
/usr/local/Cellar/php/8.0.1 (499 files, 77.8MB)
  Poured from bottle on 2021-01-08 at 21:23:34
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/php.rb
License: PHP-3.01
==> Dependencies
Build: httpd, pkg-config
Required: apr, apr-util, argon2, aspell, autoconf, curl, freetds, gd, gettext, glib, gmp, icu4c, krb5, libffi, libpq, libsodium, libzip, oniguruma, openldap, openssl@1.1, pcre2, sqlite, tidy-html5, unixodbc
==> Options
--HEAD
	Install HEAD version
==> Caveats
To enable PHP in Apache add the following to httpd.conf and restart Apache:
    LoadModule php_module /usr/local/opt/php/lib/httpd/modules/libphp.so

    <FilesMatch \.php$>
        SetHandler application/x-httpd-php
    </FilesMatch>

Finally, check DirectoryIndex includes index.php
    DirectoryIndex index.php index.html

The php.ini and php-fpm.ini file can be found in:
    /usr/local/etc/php/8.0/

To have launchd start php now and restart at login:
  brew services start php
Or, if you don't want/need a background service you can just run:
  php-fpm
==> Analytics
install: 45,149 (30 days), 165,526 (90 days), 609,628 (365 days)
install-on-request: 44,255 (30 days), 162,241 (90 days), 585,766 (365 days)
build-error: 0 (30 days)</pre>
</details>
<details>
<summary>brew info openssl</summary>
<pre>openssl@1.1: stable 1.1.1i (bottled) [keg-only]
Cryptography and SSL/TLS Toolkit
https://openssl.org/
/usr/local/Cellar/openssl@1.1/1.1.1i (8,067 files, 18.5MB)
  Poured from bottle on 2021-01-03 at 20:41:41
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/openssl@1.1.rb
License: OpenSSL
==> Caveats
A CA file has been bootstrapped using certificates from the system
keychain. To add additional certificates, place .pem files in
  /usr/local/etc/openssl@1.1/certs

and run
  /usr/local/opt/openssl@1.1/bin/c_rehash

openssl@1.1 is keg-only, which means it was not symlinked into /usr/local,
because macOS provides LibreSSL.

If you need to have openssl@1.1 first in your PATH run:
  echo 'export PATH="/usr/local/opt/openssl@1.1/bin:$PATH"' >> ~/.zshrc

For compilers to find openssl@1.1 you may need to set:
  export LDFLAGS="-L/usr/local/opt/openssl@1.1/lib"
  export CPPFLAGS="-I/usr/local/opt/openssl@1.1/include"

For pkg-config to find openssl@1.1 you may need to set:
  export PKG_CONFIG_PATH="/usr/local/opt/openssl@1.1/lib/pkgconfig"

==> Analytics
install: 752,415 (30 days), 2,348,331 (90 days), 7,976,498 (365 days)
install-on-request: 126,406 (30 days), 376,966 (90 days), 1,146,194 (365 days)
build-error: 0 (30 days)</pre>
</details>
<details>
<summary>openssl version -a</summary>
<pre>OpenSSL 1.0.2k  26 Jan 2017
built on: reproducible build, date unspecified
platform: darwin64-x86_64-cc
options:  bn(64,64) rc4(ptr,int) des(idx,cisc,16,int) idea(int) blowfish(idx) 
compiler: /usr/bin/clang -I. -I.. -I../include  -fPIC -fno-common -DOPENSSL_PIC -DZLIB -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -arch x86_64 -O3 -DL_ENDIAN -Wall -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM -DECP_NISTZ256_ASM
OPENSSLDIR: "/opt/local/etc/openssl"</pre>
</details>
<details>
<summary>openssl ciphers</summary>
<pre>ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:SRP-DSS-AES-256-CBC-SHA:SRP-RSA-AES-256-CBC-SHA:SRP-AES-256-CBC-SHA:DH-DSS-AES256-GCM-SHA384:DHE-DSS-AES256-GCM-SHA384:DH-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA256:DH-RSA-AES256-SHA256:DH-DSS-AES256-SHA256:DHE-RSA-AES256-SHA:DHE-DSS-AES256-SHA:DH-RSA-AES256-SHA:DH-DSS-AES256-SHA:DHE-RSA-CAMELLIA256-SHA:DHE-DSS-CAMELLIA256-SHA:DH-RSA-CAMELLIA256-SHA:DH-DSS-CAMELLIA256-SHA:ECDH-RSA-AES256-GCM-SHA384:ECDH-ECDSA-AES256-GCM-SHA384:ECDH-RSA-AES256-SHA384:ECDH-ECDSA-AES256-SHA384:ECDH-RSA-AES256-SHA:ECDH-ECDSA-AES256-SHA:AES256-GCM-SHA384:AES256-SHA256:AES256-SHA:CAMELLIA256-SHA:PSK-AES256-CBC-SHA:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:SRP-DSS-AES-128-CBC-SHA:SRP-RSA-AES-128-CBC-SHA:SRP-AES-128-CBC-SHA:DH-DSS-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:DH-RSA-AES128-GCM-SHA256:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES128-SHA256:DHE-DSS-AES128-SHA256:DH-RSA-AES128-SHA256:DH-DSS-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA:DH-RSA-AES128-SHA:DH-DSS-AES128-SHA:DHE-RSA-SEED-SHA:DHE-DSS-SEED-SHA:DH-RSA-SEED-SHA:DH-DSS-SEED-SHA:DHE-RSA-CAMELLIA128-SHA:DHE-DSS-CAMELLIA128-SHA:DH-RSA-CAMELLIA128-SHA:DH-DSS-CAMELLIA128-SHA:ECDH-RSA-AES128-GCM-SHA256:ECDH-ECDSA-AES128-GCM-SHA256:ECDH-RSA-AES128-SHA256:ECDH-ECDSA-AES128-SHA256:ECDH-RSA-AES128-SHA:ECDH-ECDSA-AES128-SHA:AES128-GCM-SHA256:AES128-SHA256:AES128-SHA:SEED-SHA:CAMELLIA128-SHA:IDEA-CBC-SHA:PSK-AES128-CBC-SHA:ECDHE-RSA-RC4-SHA:ECDHE-ECDSA-RC4-SHA:ECDH-RSA-RC4-SHA:ECDH-ECDSA-RC4-SHA:RC4-SHA:RC4-MD5:PSK-RC4-SHA:ECDHE-RSA-DES-CBC3-SHA:ECDHE-ECDSA-DES-CBC3-SHA:SRP-DSS-3DES-EDE-CBC-SHA:SRP-RSA-3DES-EDE-CBC-SHA:SRP-3DES-EDE-CBC-SHA:EDH-RSA-DES-CBC3-SHA:EDH-DSS-DES-CBC3-SHA:DH-RSA-DES-CBC3-SHA:DH-DSS-DES-CBC3-SHA:ECDH-RSA-DES-CBC3-SHA:ECDH-ECDSA-DES-CBC3-SHA:DES-CBC3-SHA:PSK-3DES-EDE-CBC-SHA</pre>
</details>
<details>
<summary>sudo nginx -t</summary>
<pre>nginx: the configuration file /usr/local/etc/nginx/nginx.conf syntax is ok
nginx: configuration file /usr/local/etc/nginx/nginx.conf test is successful</pre>
</details>
<details>
<summary>which -a php-fpm</summary>
<pre>/usr/sbin/php-fpm
/usr/local/sbin/php-fpm</pre>
</details>
<details>
<summary>/usr/local/opt/php/sbin/php-fpm -v</summary>
<pre>PHP 8.0.1 (fpm-fcgi) (built: Jan  7 2021 19:01:55)
Copyright (c) The PHP Group
Zend Engine v4.0.1, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.1, Copyright (c), by Zend Technologies</pre>
</details>
<details>
<summary>sudo /usr/local/opt/php/sbin/php-fpm -y /usr/local/etc/php/7.3/php-fpm.conf --test</summary>
<pre>[14-Jan-2021 22:45:33] NOTICE: configuration file /usr/local/etc/php/7.3/php-fpm.conf test is successful</pre>
</details>
<details>
<summary>ls -al ~/Library/LaunchAgents | grep homebrew</summary>
<pre>-rw-r--r--    1 markandrewkato  staff   823 Jan  5 02:57 homebrew.mxcl.redis.plist</pre>
</details>
<details>
<summary>ls -al /Library/LaunchAgents | grep homebrew</summary>
<pre></pre>
</details>
<details>
<summary>ls -al /Library/LaunchDaemons | grep homebrew</summary>
<pre>-rw-r--r--   1 root  admin   657 Jan  8 21:36 homebrew.mxcl.dnsmasq.plist
-rw-r--r--   1 root  admin   571 Jan 13 13:42 homebrew.mxcl.nginx.plist
-rw-r--r--   1 root  admin   636 Jan  8 21:36 homebrew.mxcl.php@7.3.plist</pre>
</details>
<details>
<summary>ls -aln /etc/resolv.conf</summary>
<pre>lrwxr-xr-x  1 0  0  22 Jan  1  2020 /etc/resolv.conf -> ../var/run/resolv.conf</pre>
</details>
<details>
<summary>cat /etc/resolv.conf</summary>
<pre>#
# macOS Notice
#
# This file is not consulted for DNS hostname resolution, address
# resolution, or the DNS query routing mechanism used by most
# processes on this system.
#
# To view the DNS configuration used by this system, use:
#   scutil --dns
#
# SEE ALSO
#   dns-sd(1), scutil(8)
#
# This file is automatically generated.
#
nameserver 8.8.8.8
nameserver 114.108.195.1
nameserver 114.108.193.201</pre>
</details>

**Comment by drbyte** [comment]
It's set to check port 4040 and give info about that. If it detects that you might have a second share going on it will also check port 4041.

**Comment by markandrewkato** [comment]
@drbyte Thanks for the reply. Do you mean that there is another instance of valet share running? I tried to do lsof to find if there is a process listening to port 4041 by doing the following:

`lsof -nP -iTCP -sTCP:LISTEN | grep 4041` and `netstat -anv | grep 4041`

However, it doesn't seem to return anything so I assume that there are none.

When I do `valet share`, it successfully creates the connection like the one below:

```
Session Status                online
Session Expires               1 hour, 59 minutes
Version                       2.3.35
Region                        United States (us)
Web Interface                 http://127.0.0.1:4040
Forwarding                    http://6f6baebd3ecc.ngrok.io -> http://justinme.test
Forwarding                    https://6f6baebd3ecc.ngrok.io -> http://justinme.test

Connections                   ttl     opn     rt1     rt5     p50     p90
                              0       0       0.00    0.00    0.00    0.00

In Request.php line 1060:

  Unable to connect to "http://127.0.0.1:4041/api/tunnels": 7 Failed to connect to 127.0.0.1 port 4041: Connection refused

fetch-share-url [<domain>]
```

Any ideas on how can I find and stop the other share? This happens even after starting the machine btw.

**Comment by drbyte** [comment]
You can see all the logic it is running here:
https://github.com/laravel/valet/blob/master/cli/Valet/Ngrok.php#L25-L39

It uses an API call to ask Ngrok what tunnels it has opened, then loops through the responses to get the http address (and matching it with the domain/link/dir you're sharing). 
If it fails to find a response (and matching http tunnel) on port 4040 it tries on 4041.
(Its whole purpose in doing this is just to get that http URL to copy it to your clipboard for convenience.)

The reason for your "connection refused" response is because there truly isn't anything running on 4041 because you only have one instance running (on 4040), which is totally normal.

Your challenge is figuring out why the api call to port 4040 isn't giving back a response that matches with the domain you're sharing from.

The only way I can replicate the symptom you describe is to set my firewall to block (or delay) outbound connections to ngrok.com

Maybe you need to increase the `sleep(1)` to a higher number if your computer is slower at starting things up?

**Comment by markandrewkato** [comment]
@drbyte Thanks. i updated the `~/.composer/vendor/laravel/valet/cli/Valet/Ngrok.php` file, increased the sleep time to 5 and the issue didn't show. 

One last. I assume the answer is none but is there's a way to update the sleep time without manually updating the source file?

**Comment by drbyte** [comment]
> increased the sleep time to 5 and the issue didn't show.

Good. That means the issue is that Ngrok is taking awhile to start up and make its connections to enable its sharing tunnel.

I'd suggest exploring how low you can make that sleep time and still have it work. Maybe `2` is enough to allow Ngrok to start up fully?
Does it happen only on certain internet slower connections? Or is it a slower-hardware issue? Or OS issue with too many background processes running vs available CPU and available RAM?

**Comment by drbyte** [comment]
>  I assume the answer is none but is there's a way to update the sleep time without manually updating the source file?

No. However, if you remove and re-install Valet using `--prefer-source` it will make the directory into a git repo that can stash and re-apply updates fairly intelligently whenever `composer global update` is run.

eg:
```
valet stop
composer global remove laravel/valet
composer global require laravel/valet --prefer-source
valet install
```
(The `valet stop` and `valet install` lines here are more precautionary than "required".)
(`valet install` should always be run after any `composer global update` that updates the Valet package version.)

**Comment by markandrewkato** [comment]
@drbyte Got it. Thanks for the help!

**Comment by markandrewkato** [comment]
> > increased the sleep time to 5 and the issue didn't show.
> 
> Good. That means the issue is that Ngrok is taking awhile to start up and make its connections to enable its sharing tunnel.
> 
> I'd suggest exploring how low you can make that sleep time and still have it work. Maybe `2` is enough to allow Ngrok to start up fully?
> Does it happen only on certain internet slower connections? Or is it a slower-hardware issue? Or OS issue with too many background processes running vs available CPU and available RAM?

Missed this. Not sure yet which causes the issue since this just happened after I reinstalled valet on my computer. Previously, it doesn't show me the error so it's weird this suddenly happened right after.

I'll try to check and diagnose more whenever I have free time and will update here. Thanks again!

**Comment by spark-jesus** [comment]
> > I assume the answer is none but is there's a way to update the sleep time without manually updating the source file?
> 
> No. However, if you remove and re-install Valet using `--prefer-source` it will make the directory into a git repo that can stash and re-apply updates fairly intelligently whenever `composer global update` is run.
> 
> eg:
> 
> ```
> valet stop
> composer global remove laravel/valet
> composer global require laravel/valet --prefer-source
> valet install
> ```
> 
> (The `valet stop` and `valet install` lines here are more precautionary than "required".) (`valet install` should always be run after any `composer global update` that updates the Valet package version.)
> 
> After installing that way you can make your source edits. Then on future `composer global update` calls, if the Ngrok.php file has been updated (which is rare), it should merge the changes by prompting you "would you like to stash and merge your customizations?", choose `s` and it should be fine.

---
I delete valet and reinstall with theses steps,
Now, it's work fine, thanks
