### ISSUE TITLE
Incorrect bin directory for M1 Macs

### ISSUE THREAD

**Issue by jasonvarga** [laravel/valet#1023]
## Clear description of your problem

Homebrew added support for M1 Macs. As part of that, they're now using `/opt/homebrew` rather than `/usr/local`.

Valet still uses the old path in its code.

This causes a couple of issues:
- The `valet` binary doesn't get symlinked into the user's `bin`
- Valet constantly asks for your password because the path in the sudoers file that `valet trust` generates points to the wrong place.

## Expected behavior

- The path to the correct `bin` directory should be used.
- The valet binary should get symlinked to the correct bin directory.
- The valet trust command should write the correct path and stop asking for passwords.

## Steps to Reproduce
1. Fresh install of MacOS on an M1 mac.
2. Install Homebrew
3. Install Valet
4. Run `valet trust` 
5. Open a new terminal so your sudo doesn't carry over from a second ago.
6. Run a valet command, see that it asks for your password.
7. Symlink `/opt/homebrew/bin/valet`
8. Edit `/etc/sudoers.d/valet` to point to `/opt/homebrew/bin/valet`
9. New terminal again.
10. Run a valet command, but this time it won't ask for a password.

## Possible solution

The path is hardcoded here:
https://github.com/laravel/valet/blob/35676120a707feacaed5bea5ce4311f73c2dcc85/cli/Valet/Valet.php#L11

This'll probably need to be injected.

I imagine it'll need to be a bit more than a "is this an M1, use /opt/homebrew, otherwise /usr/local" because of people that installed Homebrew before the native M1 support, which still would have used /usr/local.

Maybe you can check if the `/opt/homebrew` directory exists?

There's a few other references to `/usr/local`. https://github.com/laravel/valet/search?q=%2Fusr%2Flocal

I'm happy to take a stab at a PR when I get time, but I don't know when that'll be. Maybe this will be a simple thing for someone who knows Valet's internals better.

Hope that was helpful, thanks!

**Comment by drbyte** [comment]
@jasonvarga Awhile back we worked on this and merged #992 which updated things from `/usr/local` to use the `[BREW_PREFIX](https://github.com/laravel/valet/blob/35676120a707feacaed5bea5ce4311f73c2dcc85/cli/includes/helpers.php#L20)` directory for everything (er, well, "almost" everything 😊 ).

Do you think it would be sufficient to extend using that into these two main areas you're highlighting: symlinking the valet binary and setting the proper sudoers paths?

**Comment by jasonvarga** [comment]
Oh totally missed that PR, sorry. Yes, I think that'll absolutely work.
