### ISSUE TITLE
Is there an 'official' way to add a second TLD?

### ISSUE THREAD

**Issue by HCMF** [laravel/valet#1026]
I was wondering if there is an way to add more TLD's so that sites can be accesses at different domains (.site, .test etc)?

**Comment by drbyte** [comment]
It's quite complex.

Clarification: 
Are you wanting each site accessible on multiple TLDs?  eg: `foo.test` & `foo.site` are the same project?
Or just the freedom to specify one of multiple supported TLDs when `link`ing or `secure`ing a site, and always use it via that specified TLD? (eg: `valet link baz.site` and always use baz.site for it, never baz.test)
It'd be quite unruly to have a mixture of those approaches.

**Comment by HCMF** [comment]
The latter... baz.site and bif.test is all I require.

**Comment by ttomdewit** [comment]
Let's say you're building a marketing page on foo.nl (Dutch) and foo.de (German). It links to the same application, but based on the TLD (either `.nl` or `.de`) the preferred locale on the marketing site changes. Typically you'd see foo.com/nl for a Dutch version of foo.com whereas I prefer the official TLD path.

So in my use-case I'd need multiple TLDs to link to one and the same project. Is that feasible? Googling setting a (secondary) custom domain does provide _some_ results but all are quite hacky to say the least.

**Comment by drbyte** [comment]
@ttomdewit that workaround is fine. You'd have to edit/rename/clone the Nginx stub if you wanted to also use https. But if you're not using https then the mentioned workaround is fine.

Automating it in the cli would require a bunch of things, including keeping track of a list of configured tlds in the json config, setting them all into dnsmasq, and then keeping track of which site configs were linked to which tlds, and making all the certs honor all those as well, and then also make valet audit every configured tld to check for whether/which to serve upon any incoming request ... as well as then overriding it all even further if one wanted to use valet share, amongst other features.

For the one-off cases where you need to do it locally, the mentioned workaround is a whole lot simpler .... and by doing it yourself you also know what/where to troubleshoot if something goes wrong!
