### ISSUE TITLE
Valet using php 8 only. It's not changing.

### ISSUE THREAD

**Issue by vimalmistry** [laravel/valet#1027]
## Problem
After brew upgrade. It is updated with php 8.0. But some of my old project require php 7.4/7.3

When I using valet use php@7.4. Then version is changed on terminal but "myproject.test" is using php 8.

![Screenshot 2021-01-20 at 10 40 00 PM](https://user-images.githubusercontent.com/3993163/105209962-70b05080-5b70-11eb-81d7-d131bd70bdee.png)

On mysite.test
![Screenshot 2021-01-20 at 10 40 37 PM](https://user-images.githubusercontent.com/3993163/105210027-86257a80-5b70-11eb-9ac4-ddb642dbd836.png)

I am using Mac. catalina.

**Comment by mattstauffer** [comment]
Please try this:

https://github.com/laravel/valet/issues/1010

```bash
valet use php@7.4
rm ~/.config/valet/valet.sock
valet restart
```

If this works, please let us know in a comment here and close this issue; thanks!

**Comment by vimalmistry** [comment]
@mattstauffer Thank you. It is working now.

**Comment by hawkeyetwolf** [comment]
I experienced the same issue and this fixed it for me. Thank you! Would it make sense to add this documentation, under a "troubleshooting" section or something like that? @mattstauffer, if you agree, I'd be happy to make the PR. Thanks.

**Comment by drbyte** [comment]
> I experienced the same issue and this fixed it for me. Thank you! Would it make sense to add this to documentation, under a "troubleshooting" section or something like that? 

No, because that's now built-in to Valet since v2.13..18

**Comment by patrickomeara** [comment]
This morning I had the same issue, but going the other way `Valet is using php@8.0` but `phpinfo()` showed `7.4`

Removing `valet.sock` worked.

``valet use php@8.0 && rm ~/.config/valet/valet.sock && valet restart``

**Comment by drbyte** [comment]
> This morning I had the same issue, but going the other way `Valet is using php@8.0` but `phpinfo()` showed `7.4`
> 
> Removing `valet.sock` worked.
> 
> `valet use php@8.0 && rm ~/.config/valet/valet.sock && valet restart`

Again: using the latest Valet automatically removes the old/orphaned valet.sock file when calling `valet use` and a PHP version. NO NEED TO DELETE valet.sock MANUALLY. Just `composer global update`
