### ISSUE TITLE
Proxy a custom domain

### ISSUE THREAD

**Issue by tholu** [laravel/valet#1030]
Is there a way to proxy a custom domain, e.g. `dev.my-other-application.com` (with manually adding `127.0.0.1 dev.my-other-application` to `/etc/hosts`), when the tld is set to `test`? Then valet could easily be used as a full replacement of a local reverse proxy for other applications.

**Comment by mattstauffer** [comment]
I'm not actually the most knowledgeable person about these questions, sadly, but there's nothing I know of. Closing and if someone else has a solution they're welcome to share it!
