### ISSUE TITLE
Couldn't find any package by glob 'phpphp@7.4-fpm' when trying to execute valet use

### ISSUE THREAD

**Issue by crisalder2806** [laravel/valet#1034]
Hi, I'm currently facing this issue when trying to execute `valet use php@7.4` on my Linux machine.

> Changing php-fpm version...
This does not affect php -v.
Stopping php7.4-fpm...
Disabling php7.4-fpm...
Php7.4-fpm has been disabled
Php7.4-fpm was already disabled
[phpphp@7.4-fpm] is not installed, installing it now via Apt... 🍻
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package phpphp@7.4-fpm
E: Couldn't find any package by glob 'phpphp@7.4-fpm'
E: Couldn't find any package by regex 'phpphp@7.4-fpm'
Enabling php7.4-fpm...
Php7.4-fpm has been enabled
Changing version failed

> In Apt.php line 74:
                                               
> Apt was unable to install [phpphp@7.4-fpm].  
                                               

> use [<preferedversion>]

Although I tried to install phpphp@7.4-fpm throught apt did not work. Don't know if this package existst or should I add any repository for it? Please give me some sugestions. Thanks in advance.

**Comment by drbyte** [comment]
>  on my Linux machine.
> > In Apt.php line 74:
> 
> > Apt was unable to install [[phpphp@7.4-fpm](mailto:phpphp@7.4-fpm)].
> 

The `laravel/valet` package works on MacOS.

You appear to be using a different package, perhaps called `valet-linux`?, from a different repo.  Best to close this issue and open a new one in their repo.
