### ISSUE TITLE
Drupal driver not found (even when not in use)

### ISSUE THREAD

**Issue by drbyte** [laravel/valet#104]
1.1.14 to 1.1.16 give this error when valet is trying to select the right driver:

```
Warning: require_once(/Users/me/.composer/vendor/laravel/valet/cli/drivers/DrupalValetDriver.php):
 failed to open stream: No such file or directory in /Users/me/.composer/vendor/laravel/valet/cli/drivers/require.php on line 26
```

This is presumably because the Drupal driver added in #48 was put at `/valet/drivers/DrupalValetDriver.php` instead of `/valet/cli/drivers/DrupalValetDriver.php`

I've confirmed that relocating it to the `/valet/cli/drivers/` folder (where all the other drivers are found) gets rid of the error and lets previously-functioning sites work correctly again.

**Comment by aaemnnosttv** [comment]
I have this error now as well after upgrading

**Comment by adamwathan** [comment]
Fixed and published. What a fucking day 😩🔫
