### ISSUE TITLE
Any changes necessary for folks to be able to use/test Octane locally?

### ISSUE THREAD

**Issue by mattstauffer** [laravel/valet#1044]
We'll see by the end of his talk. :)

**Comment by ju5t** [comment]
I did not have enough time to test this yet, but I think Valet needs some work to support Octane.

**Comment by connor11528** [comment]
I added the above proxy. Currently getting 502 bad gateway trying to visit my valet site in the browser

**Comment by uchm4n** [comment]
**artisan serve** has to be executed in order to proxy config work properly. Maybe we can create OctanValetDriver to solve this issue ?

**Comment by jethromayuk** [comment]
Have there been any further developments on this? I'm quite eager to run Octane with Valet.. unless this is now possible?

**Comment by mattstauffer** [comment]
@jethromayuk are you not able to make it work with the instructions above?

**Comment by deevus** [comment]
If you google "laravel valet octane" this is the top result. The issue is marked as completed so it would be good to direct users to some documentation.

**Comment by amnah** [comment]
this was actually very easy to set up on laravel valet

here are the steps i did:

```cd ~/Sites/laravel
composer require laravel/octane
php artisan octane:install   # i chose frankenphp
valet unlink
valet proxy laravel.test http://127.0.0.1:8000 --secure
npm install --save-dev chokidar
php artisan octane:start --watch
# https://laravel.test should work now
```

unfortunately, i dont think xdebug is usable with this setup so ill be sticking with regular php-fpm
