### ISSUE TITLE
Change binding for Nginx to allow Docker containers to resolve services from host through DNSmasq

### ISSUE THREAD

**Issue by Keoghan** [laravel/valet#1046]
Hi, 

Would you be willing to consider altering the nginx.conf structure to stop binding directly to 127.0.0.1 (by binding to an alternative, or allow custom stubs stored in the valet config dir)?

In my use case, I am running docker containers for some sites and attempting to resolve other test sites through DNSmasq.  If the site resolves to 127.0.0.1, the container is unable to communicate as it tries to contact itself.

Instead, I am using an IP of 10.200.10.1 and would like to either bind nginx to that or just the relevant ports.

Happy to construct a PR if this is of interest. 

Thanks

**Comment by drbyte** [comment]
Do you mean like this ... https://github.com/laravel/valet/pull/1039 ?
Or some other approach?

**Comment by Keoghan** [comment]
@drbyte thanks, that approach will cover it and is pretty comprehensive. I'll pull it down and run it through for some testing - and close this issue.

**Comment by drbyte** [comment]
Great. If you have any feedback about it, please do post it to that discussion for consideration.
