### ISSUE TITLE
Why can't I valet use php@7.1 in 2021?

### ISSUE THREAD

**Issue by handhikadj** [laravel/valet#1047]
NOTE: If your issue is a feature request, please feel to delete this template and write your own.

------

## Clear description of your problem
Run `valet use php@7.1`

```
Installing php@7.1...
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
Updated 1 formula.

[php@7.1] is not installed, installing it now via Brew... 🍻
Note: older PHP versions may take 10+ minutes to compile from source. Please wait ...
Error: Formulae found in multiple taps:
       * shivammathur/php/php@7.1
       * exolnet/deprecated/php@7.1

Please use the fully-qualified name (e.g. shivammathur/php/php@7.1) to refer to the formula.


In Brew.php line 168:

  Brew was unable to install [php@7.1].


use [--force] [--] [<phpVersion>]
```

Then run `valet use shivammathur/php/php@7.1`

```
In PhpFpm.php line 235:

  Valet doesn't support PHP version: shivammathur/php/php@7.1 (try something like 'php@7.3' instead)


use [--force] [--] [<phpVersion>]
```

Valet is alternative to Laragon (on Windows), right?

## Expected behavior

Can use php7.1

## Current behavior

Cannot use php7.1

## Steps to Reproduce

1. valet use php@7.1
2. valet use shivammathur/php/php@7.1

### Output of these steps

You can see it on above

**Comment by drbyte** [comment]
`brew untap exolnet/deprecated`

**Comment by handhikadj** [comment]
jeez. thank you so much
