### ISSUE TITLE
Installing Valet on M1 Mac

### ISSUE THREAD

**Issue by adibhanna** [laravel/valet#1048]
I'm trying to install Laravel Valet on my M1 Mac, but I'm getting this error:

```
▶ valet install
Stopping nginx...
Installing nginx...
[nginx] is not installed, installing it now via Brew... 🍻
Updating Homebrew...
==> Auto-updated Homebrew!
Updated Homebrew from e79f315ee to 5361c04c4.
Updated 1 tap (homebrew/core).
==> Updated Formulae
Updated 2 formulae.

Error: Cannot install under Rosetta 2 in ARM default prefix (/opt/homebrew)!
To rerun under ARM use:
    arch -arm64 brew install ...
To install under x86_64, install Homebrew into /usr/local.
```

Any idea how to fix this? 

Thank you!

**Comment by drbyte** [comment]
According to https://github.com/Homebrew/brew/pull/10319 it seems your Terminal Emulator is running under Rosetta 2.

What terminal emulator application are you using and why?

**Comment by adibhanna** [comment]
@drbyte I'm using iTerm2, and i have it open in Rosetta (from the info)

**Comment by drbyte** [comment]
Does the problem go away if you use a non-Rosetta terminal emulator?

**Comment by adibhanna** [comment]
Nope!

**Comment by adibhanna** [comment]
Solved it! this helped me https://github.com/Homebrew/discussions/discussions/875#discussioncomment-388476 

my issue with with sqlite, i ran `brew reinstall sqlite` and it solved the problem!
