### ISSUE TITLE
Got Fatal error: Declaration of Illuminate\Container\Container::get($id) blabla after run valet

### ISSUE THREAD

**Issue by handhikadj** [laravel/valet#1049]
NOTE: If your issue is a feature request, please feel to delete this template and write your own.

------

## Clear description of your problem
got `Fatal error: Declaration of Illuminate\Container\Container::get($id) must be compatible with Psr\Container\ContainerInterface::get(string $id) in /Users/me/.composer/vendor/illuminate/container/Container.php on line 16` after run valet park

## Expected behavior

can run valet park

## Current behavior

an issue springs up

## Steps to Reproduce

1. Run `valet park` or just `valet`
2. That's it
3.  

## Diagnosis

`valet diagnose` output:

```
Fatal error: Declaration of Illuminate\Container\Container::get($id) must be compatible with Psr\Container\ContainerInterface::get(string $id) in /Users/me/.composer/vendor/illuminate/container/Container.php on line 16
```

**Comment by drbyte** [comment]
When you get errors happening in your `/Users/me/.composer/` directory it means you've got conflicting things registered in your global composer configuration. Probably several old things there that depend on older PHP or older dependencies that you currently have installed and haven't upgraded in a long time.

1. Edit your `~/.composer/composer.json` file and remove everything except `laravel/valet`.
2. Run `rm -rf ~/.composer/vendor ~/.composer/composer.lock`
3. Run `composer global install`

Then once Valet is working properly again, feel free to add back latest versions of things you actually still need by running `composer global require X/Y` to install them fresh (and NOT just pasting back in old outdated version numbers to the composer.json file).

**Comment by handhikadj** [comment]
thank you. that works
