### ISSUE TITLE
Unable to play video

### ISSUE THREAD

**Issue by jsengstrom** [laravel/valet#105]
I am finding that video files will not play in Valet as mp4, ogg, ogv or webm. I have tried adding Mime types within the .htaccess, but looking at ```cli/mimes.php``` thy should already be there?

Is there any way I can get around this?

**Comment by adamwathan** [comment]
They seem to play ok for me (using a `<video>` tag with a local mp4), can you provide more detail?

There are definitely improvements we need to make in terms of streaming the video content vs. loading it all into memory, is the video very large?

**Comment by jsengstrom** [comment]
That's how i'm loading them too:

```
<video loop preload autoplay>
  <source src="video-file.ogg" type="video/mp4">
  <source src="video-file.ogg" type="video/ogg">
  <source src="<video-file.ogg" type="video/webm">
</video>
```

In my frantic googling state I uncovered [this](https://github.com/wells/airflix/commit/fa0bae453015e1844113860382960378e2b169f8) commit that seems to show that somebody else at least is experiencing issues.

**Comment by adamwathan** [comment]
Think I've got this figured out by being able to push all static file handling to Caddy, which I originally thought would be impossible but apparently not (although it involved some weird hacky stuff 👀)

If you could, do you mind testing out this branch?

https://github.com/laravel/valet/tree/serve-static-via-caddy

You'll have to wipe your `~/.valet` folder and do a fresh `valet install` to pick up the changes to the Caddy server config.

Let me know if that fixes your issues or if you notice any other problems!

**Comment by adamwathan** [comment]
Actually just hop into your ~/.composer/composer.json file and tweak this line:

```diff
  {
      "require": {
-         "laravel/valet": "^1.1.14" // or whatever
+         "laravel/valet": "dev-serve-static-via-caddy"
      }
  }
```

Once you do that, you should be able to run `composer global update` and pull in that branch.

**Comment by jsengstrom** [comment]
Thanks for that - I've run the branch and reinstalled Valet and video is now playing perfectly!

Thanks again for all your help!

**Comment by GMCz** [comment]
I too ran into this issue, with a 3mb video file. (h.254, mp4 with no audio) and switching to this branch fixed the issue. So far, I've not noticed any unintended side effects. 👍🏼 Thanks!

**Comment by kjbrum** [comment]
I think I'm still having this issue. Is the fix included in the most recent release or is there another branch that I should be trying?

**Comment by adamwathan** [comment]
It's fixed on master but unfortunately master has some other issues. So far every time a new Caddy release comes out it fixes one of our problems and introduces a new one 😔

We're working on nginx support in another branch as a contingency plan at the moment 😕

**Comment by kjbrum** [comment]
Any suggestions for a workaround at the moment?

**Comment by adamwathan** [comment]
Switch to the master branch and run valet install again, it should work mostly fine. Taylor and I have had intermittent issues where Caddy was serving stale code and we'd need to refresh again, but it wasn't terrible, just not good enough to tag a release. Would actually be really curious to see if you also run into that issue.

**Comment by kjbrum** [comment]
I tried that early and my page was all messed up. Tried it again and everything is working now. I'll report back if I have an weird issues.

Thanks!

**Comment by adamwathan** [comment]
It's fixed on master but unfortunately master has some other issues. So far
every time a new Caddy release comes out it fixes one of our problems and
introduces a new one 😔

We're working on nginx support in another branch as a contingency plan at
the moment 😕
