### ISSUE TITLE
Laravel subdomain routes with ngrok not working as accepts

### ISSUE THREAD

**Issue by GMounir** [laravel/valet#1058]
I have a project with x-app.test and admin.x-app.test, I use ngrok with business plan to expose the project, my problem is admin.x-app.test not accessed by ngrok
The command I used is
valet share --subdomain=x-app
The result x-app.ngrok.io, it is worked but admin.x-app.ngrok.io not.
Please someone help me i spend a week try to found a solution
Thank you.

**Comment by mattstauffer** [comment]
Have you tried sharing in two different tabs? One sharing x-app and one sharing admin.x-app?

**Comment by mattstauffer** [comment]
Please re-open if you work on this and still need help.
