### ISSUE TITLE
Weird Crash

### ISSUE THREAD

**Issue by tillkruss** [laravel/valet#106]
I've been using Valet for 2 months without any issues.

Recently the valet or caddy seem to crash when I load certain `.js` files on a server rendered page. I tried narrowing down the issue further, without any luck. Once it crashes all valet sites and CLI commands become unresponsive.

I'm using Valet v1.1.16 and Laravel 5.2.

The same code is working fine using Homestead without errors or warnings.

Could someone help me out in debugging this issue?

**Comment by adamwathan** [comment]
Can you try using the branch from this thread and letting me know if it changes anything?

https://github.com/laravel/valet/issues/105#issuecomment-238677842

We are working on delegating all static file handling to Caddy instead of handling it ourselves, maybe this will make a difference in your case since all the JS would be entirely handled by the web server.

**Comment by tillkruss** [comment]
I ran `valet uninstall` and deleted `~/.valet`, then installed `dev-serve-static-via-caddy c214c51` and ran `valet install` and `valet park`. Still the same crash.

**Comment by adamwathan** [comment]
Can you create a minimum reproducible project that you could share on GitHub for me to pull down and troubleshoot?

**Comment by tillkruss** [comment]
I invited you to `jacobi2/timetrackpro`.

Add this to your `.env` file:

```bash
SEED_USER="Till Krüss"
SEED_EMAIL=till@kruss.io
SEED_PASSWORD=123456
```

Then run: `php artisan migrate --seed`. That should get you up and running right away. Then click on "Tasks".

**Comment by adamwathan** [comment]
Weird, I am able to click on "Tasks" and click around in there no problem, everything working as expected 😕 Do you have any information at all about the error?

**Comment by tillkruss** [comment]
All page assets under "Tasks" load without an issue in Chrome?

**Comment by adamwathan** [comment]
Yeah everything seems ok!

![image](https://cloud.githubusercontent.com/assets/4323180/17598295/ccddc06c-5fc7-11e6-8628-63c8cfa5a1d5.png)

(will delete this screenshot if it shouldn't be publicly available!)

**Comment by tillkruss** [comment]
I see all css/js files as "Pending..." in the Chrome Dev Tools. Is there anything else I could provide you with, or should I just use Homestead?

**Comment by adamwathan** [comment]
Is it just this project or any project that has CSS/JS assets? Trying to think how to find out more information but struggling :/

**Comment by tillkruss** [comment]
Only this one so far. I had some issues with a WordPress install a couple of months ago, but I just switched to HomeStead, because Valet was brand new.

**Comment by adamwathan** [comment]
How's this looking on recent versions of Valet?

**Comment by tillkruss** [comment]
Seems to be working with v1.1.22!
