### ISSUE TITLE
`brew services list` gives error when valet installed [solved]

### ISSUE THREAD

**Issue by hga77** [laravel/valet#1060]
## Clear description of your problem
`brew services list` gives error when valet installed

Hello, Can anyone give me possible reason(s) why `brew services list` is giving an error?

I just upgraded brew. (`brew upgrade`)

Brew 3.1.8
macOS 10.13 (no errors/warnings from `brew doctor` other that telling me macos 10.13 is old)
php@7.3
Valet 2.15.0
nginx 1.19.10

## Expected behavior
The command `brew services list` should list the services instead of giving an error.

## Current behavior
`brew services list` gives an error:
```shell
Error: Failure while executing; `/bin/launchctl\ list\ \'homebrew.mxcl.dnsmasq\'` exited with 113. Here's the output:
```

After installing php@7.3, it now shows the following error instead:
```shell
Error: Failure while executing; `/bin/launchctl\ list\ \'homebrew.mxcl.php@7.3\'` exited with 113. Here's the output:
```
Before php@7.3 was installed, it was complaining about `homebrew.mxcl.dnsmasq`, now it's saying `homebrew.mxcl.php@7.3`.

## Steps to Reproduce
I am using macOS 10.13 and two days ago did a `brew upgrade`. This broke several brew packages including valet. So I uninstalled brew and installed it again along with valet and php@7.3. `brew doctor` only has the warning about macos 10.13 being old. Nothing else.

**Comment by drbyte** [comment]
> brew services list gives an error:
> Error: Failure while executing; `/bin/launchctl\ list\ \'homebrew.mxcl.dnsmasq\'` exited with 113. Here's the output:

`brew` is calling the MacOS command `/bin/launchctl` with some parameters, and is returning a `113` response.

Running `/bin/launchctl error 113` reveals that error 113 means: `113: Could not find specified service`

Thus, it seems in your case either homebrew hasn't properly registered those services that launchctl is complaining about, or perhaps they simply haven't been started. Or maybe they're failing to start due to reasons unexplainable without exploring logs for those specific apps.

**Comment by hga77** [comment]
Thanks @drbyte. They are running because valet is working and running my local websites. So valet is doing it's job. It's just I don't get why this command gives this error.

Where do I start to try and detect the issue?

**Comment by drbyte** [comment]
Update: Looks like Homebrew may have had a bug yesterday.

I was able to trigger the same error, but now today after running `brew upgrade` the problem is gone. Now `brew services list` works fine without the `113` error.

**Comment by hga77** [comment]
Great. But `brew upgrade` was the reason I got into this mess in the first place because it upgraded Everything on my old laptop. Can I `brew upgrade` while suppressing the upgrade of some packages?

**Comment by hga77** [comment]
@drbyte
I just did a `brew upgrade` and the error is gone. But, I have pasted the outoput here. I noticed that some services has 'unknown'. 

Is this normal?

```console
$ brew services list
Name    Status  User  Plist
dnsmasq unknown root  /Library/LaunchDaemons/homebrew.mxcl.dnsmasq.plist
httpd   stopped
mariadb started Steve /Users/Steve/Library/LaunchAgents/homebrew.mxcl.mariadb.plist
nginx   unknown root  /Library/LaunchDaemons/homebrew.mxcl.nginx.plist
php@7.3 unknown root  /Library/LaunchDaemons/homebrew.mxcl.php@7.3.plist
```

**Comment by drbyte** [comment]
> I noticed that some services have 'unknown'.
> Is this normal?

Yes, in the last 6 months I've seen a lot of cases where it reports 'unknown'.
