### ISSUE TITLE
Add a driver for Moodle (https://moodle.org/) opensource learning management system 

### ISSUE THREAD

**Issue by ssmusoke** [laravel/valet#1061]
Sample code available at https://gist.github.com/sandeepgill/8aff4849bdbb4f7ac0aced72496f2183 - IMO all that may be needed is attribution in the driver code

**Comment by drbyte** [comment]
All you have to do is copy (or checkout) the file into your `~/.config/valet/Drivers` directory. You could optionally put it into its own subdirectory there.

That way you're entirely in control of which drivers you add to your own Mac.

**Comment by ssmusoke** [comment]
@drbyte @mattstauffer Sorry I was not clear, I meant as one of the default inbuilt drivers

**Comment by mattstauffer** [comment]
@ssmusoke No worries, that was clear! However, we're not adding new drivers right now.
