### ISSUE TITLE
Bintray is returning forbidden: can't install valet-php@7.2

### ISSUE THREAD

**Issue by alexandrosk** [laravel/valet#1064]
## Clear description of your problem
dl.bintray link for valet-php@7.2 returns forbidden :/ 
https://dl.bintray.com/henkrehorst/valet-php/valet-php@7.2-7.2

## Expected behavior
Should be able to download when running the command 
brew install valet-php@7.2

## Steps to Reproduce
Just try to run this 
brew install valet-php@7.2
you will get a 404 download.

## Possible solution
Is there any solution maybe to install this manually and link the folders? I can't run 7.3 since my application doesn't work with it yet. 

## Diagnosis
Brand new installation on intel macbook.

**Comment by drbyte** [comment]
This is the `laravel/valet` project repository.
You're not using `laravel/valet`. You're using someone else's fork of it. Please contact them for support, and close this issue.

**Comment by alexandrosk** [comment]
Right it's valet plus my mistake I thought I was in that repo. Thanks.
