### ISSUE TITLE
[Feature Request] Allow passing suffix to valet open command

### ISSUE THREAD

**Issue by vesper8** [laravel/valet#1067]
I would like to make myself an alias `nova` which will get the currently linked domain from the current working directory and then open the url + `/nova`

I could achieve this in two ways. If there was a valet command that simply printed out the current domain (the one that is called when running `valet open`, then I could add a little bash function that gets the value of that and then opens a browser with that url + `/nova`

OR

It would be even simpler if I could just pass it to `valet open`. So something likes `valet open -a '/nova'`

Just a small QoL improvements that I would find pretty useful

If there's already a way of retrieving the url linked to the CWD then please let me know.. I couldn't find one

Many thanks

**Comment by mattstauffer** [comment]
We've been talking about a `valet info` command or something similar that outputs *all* of the Valet information for all the sites, and I love the idea of that also potentially listing it out for the directory you're in.

**Comment by drbyte** [comment]
Quick implementation of first option: Add a personal `valet href` function to output the domain of the current site.

New file: `~/.config/valet/Extensions/href-command.php`
```php
<?php

use function Valet\output;

$app->command('href', function () {
    $url = Site::host(getcwd()).'.'.Configuration::read()['tld'];
    output($url);
})->descriptions('Print the URL that would be used for [valet open] for the current directory');
```

**Comment by drbyte** [comment]
> @drbyte ok, that's pretty freaking slick and a lot simpler than what I was thinking.

Ya, extensions can be cool quick personalized fixes that come in handy.

**Comment by drbyte** [comment]
Extensions like that can even re-define built-in Valet commands.
So, you could clone the "open" command code and change its logic by putting it in an extension. Just remember to check your own customized code before asking for support if it's not working as expected! 🤣

**Comment by drbyte** [comment]
> How feasible would it be to just override the `open` command, copy the existing command as-is and then add a new option to pass a string to append to the end?

Yes, you could just copy the `open` command section from the main valet.php file into a file in your  User's `Extensions` directory, like the example above, and adapt the command accordingly.
The `$app` is an instance of [`Silly/Application`](https://github.com/mnapoli/silly), which is a simplified wrapper for `Symfony/Console`.

Something like this should work:

```php
<?php

use function Valet\output;

$app->command('open [domain] [-a|--append=]', function ($domain = null, $append = null) {
    $url = "http://".($domain ?: Site::host(getcwd())).'.'.Configuration::read()['tld'];
    if (!empty($append)) $url .= $append;
    CommandLine::runAsUser("open ".escapeshellarg($url));
})->descriptions('Open the site for the current (or specified) directory in your browser', [
    'domain' => 'Domain to open',
    '--append' => 'Optional URI to [append]',
]);
```

... but I'd suggest changing the command name from `open` to something else, just to reduce ambiguity by preventing accidentally conflating the functionality with the built-in `open` command.

**Comment by vesper8** [comment]
@drbyte  thank you very much!

**Comment by mattstauffer** [comment]
@vesper8 If this has solved your problem, would you close the comment? If not, please let us know what else remains.

Thanks as always, @drbyte!

**Comment by vesper8** [comment]
@mattstauffer This approach no longer works in v4?

**Comment by drbyte** [comment]
> @mattstauffer This approach no longer works in v4?

Correct. When Valet was rebuilt for v4, support for Extensions was suspended, at least temporarily.

However, I'll post a workaround for you in your other thread # 1453.
