### ISSUE TITLE
Use valet with MariaDB and MySQL8 simultaneously?

### ISSUE THREAD

**Issue by shornuk** [laravel/valet#1077]
I'm not sure if this an appropriate place to post this, but looking for any that's had experience of running valet with both MariaDB and mysql8 simultaneously?

I've been dev'ing multiple sites locally with valet + MariaDB for years. Recently though, one of those sites updated to using mysql8 and I've struggled to get that installed in a way that allows me to continue to use my existing site.

In the meantime, I've switch to using a Nitro (built by CraftCMS as that's my main CMS) and this uses Docker. This is working, but it's incredibly slow, especially in comparison to valet. 

Just looking for any tips or suggestions. Thanks!

**Comment by drbyte** [comment]
Some options:
- continue using Docker. There are various tools for that, but your current one is probably fine.
- use Homebrew to install MySQL but configure it to listen on a different port than 3306 (maybe 3307), and configure your app accordingly.
- continue using MariaDB locally if exact 100% compatibility isn't crucial.

**Comment by shornuk** [comment]
Thank you for the response. I did find Takeout - https://github.com/tighten/takeout which could use docker for the databases but everything else with valet. Looks like you can run multiple versions of a database at once too.

With regards to installing mysql with Homebrew, I can't seem to find any docs that refer to installing on a different port?

**Comment by drbyte** [comment]
> I did find Takeout - https://github.com/tighten/takeout which could use docker for the databases but everything else with valet. Looks like you can run multiple versions of a database at once too.

Yes, Takeout would be my first recommendation if you weren't using Nitro which is part of the tooling ecosystem you're already using. 
If you don't need the rest of what Nitro offers, then Takeout is probably the best approach.

> With regards to installing mysql with Homebrew, I can't seem to find any docs that refer to installing on a different port?

My apologies: simply setting the port wouldn't be enough. I'd forgotten how much the mysql vs mariadb binary filenames clash, preventing safe co-installation of both apps without dockerizing one of them.
