### ISSUE TITLE
Valet link not working for volumes including a space

### ISSUE THREAD

**Issue by snapey** [laravel/valet#109]
I have some sites on a volume called `Macintosh HD`

`valet link foldername` says link has been created, and no error is reported

`valet links` shows no such symlink

The valet sites folder does not contain the link just requested.

Valet link to a folder in a different volume works fine.

The only thing unusual about the volume is the space in the name.  This has been an issue with some other scripts that do not quote the path.

**Comment by drbyte** [comment]
Does it still fail if you escape the space with a `\`?

ie: `Macintosh\ HD`

**Comment by adamwathan** [comment]
Are you sure you are using the command correctly? The `valet link` command takes the _domain_ you want to use as it's argument, not the folder name.

```
cd my-project
valet link awesome-project
```

...will make the project in `my-project` available at `awesome-project.dev`. You need to navigate to the root of the project directory, and then run `valet link {desired-url}` from inside there.

**Comment by snapey** [comment]
I don't specify the volume. (ignore drbyte comment).

my bad: `valet link foldername` is actually because I tend to have same name for folder as project.

I have a folder csdb. I want to create a site `csdb.dev` I use the command `valet link csdb`

If the csdb folder is on the path `/Volumes/Macintosh HD/websites/csdb` then the command appears to work but the symlink is not created

When I move the project to `/Volumes/SSD1/sites/csdb` the link command works fine.

**Comment by snapey** [comment]
The problem can be more easily replicated by trying to use `valet link` inside a folder that contains a space in its name.

**Comment by adamwathan** [comment]
I can't replicate this, I'm able to link to folders with spaces in the path:

![image](https://cloud.githubusercontent.com/assets/4323180/17608315/b2235976-5ff9-11e6-987e-67dbdc4c7c5e.png)

Are you able to symlink between volumes manually and have it work or is there some sort of error?

`ln -s '/Volumes/Macintosh HD/websites/csdb' '~/.valet/Sites/csdb'`

**Comment by snapey** [comment]
I did a google search and found this https://github.com/laravel/valet/pull/62/commits/4c09534b41fa9defdc58a949e85b9f5f37e43186

So, sorry, appears to have already been fixed.  I updated valet and it seems to be ok. (I was on 1.1.12)  

Just one oddity, updating said it was installing 1.1.17 but `valet -V` returns 1.1.16

**Comment by drbyte** [comment]
Ya, they missed stamping the version before it was tagged last time.

**Comment by JohnnyWalkerDesign** [comment]
So... Laravel doesn't bug out, but it creates an unreachable URL?
