### ISSUE TITLE
Valet-installed Formulae need manual intervention when upgrading

### ISSUE THREAD

**Issue by adriaanzon** [laravel/valet#1097]
## Clear description of your problem

The way Laravel valet installs its dependencies (using root permissions) causes `brew upgrade` invocations to be painfully tedious.

After every upgrade of any of the `php`, `dnsmasq` or `nginx` packages, the upgrade stops with the following output:

```
Error: Directory not empty @ dir_s_rmdir - /opt/homebrew/Cellar/php/8.0.8_1
```

Here, brew tries to clean up the old PHP directory, but it fails doing so because of the filesystem permissions. I have to manually clean it up by running `sudo rm -rf /opt/homebrew/Cellar/php/8.0.8_1`, and start `brew upgrade` again to update my other Formulae, and repeat this if there are updates for `dnsmasq` and `nginx`.

These error messages used to looked like this:

```
Error: Could not remove php@7.3 keg! Do so manually:
  sudo rm -rf /usr/local/Cellar/php@7.3/7.3.13
```

## Expected behavior

Run `brew upgrade` and have all my dependencies upgrade in one go.

## Current behavior

I need to run `brew upgrade` several times and clean up old kegs manually.

## Steps to Reproduce

1. Make sure Valet is installed with all its dependencies
2. Wait for updates to release for `php`, `dnsmasq` or `nginx`
3. Run `brew upgrade`

### Output of these steps

```
... (other brew upgrade output) ...
==> Upgrading php
  8.0.8_1 -> 8.0.11

==> Pouring php--8.0.11.arm64_big_sur.bottle.tar.gz
==> /opt/homebrew/Cellar/php/8.0.11/bin/pear config-set php_ini /opt/homebrew/etc/php/8.0/php.ini system
==> /opt/homebrew/Cellar/php/8.0.11/bin/pear config-set php_dir /opt/homebrew/share/pear system
==> /opt/homebrew/Cellar/php/8.0.11/bin/pear config-set doc_dir /opt/homebrew/share/pear/doc system
==> /opt/homebrew/Cellar/php/8.0.11/bin/pear config-set ext_dir /opt/homebrew/lib/php/pecl/20200930 system
==> /opt/homebrew/Cellar/php/8.0.11/bin/pear config-set bin_dir /opt/homebrew/opt/php/bin system
==> /opt/homebrew/Cellar/php/8.0.11/bin/pear config-set data_dir /opt/homebrew/share/pear/data system
==> /opt/homebrew/Cellar/php/8.0.11/bin/pear config-set cfg_dir /opt/homebrew/share/pear/cfg system
==> /opt/homebrew/Cellar/php/8.0.11/bin/pear config-set www_dir /opt/homebrew/share/pear/htdocs system
==> /opt/homebrew/Cellar/php/8.0.11/bin/pear config-set man_dir /opt/homebrew/share/man system
==> /opt/homebrew/Cellar/php/8.0.11/bin/pear config-set test_dir /opt/homebrew/share/pear/test system
==> /opt/homebrew/Cellar/php/8.0.11/bin/pear config-set php_bin /opt/homebrew/opt/php/bin/php system
==> /opt/homebrew/Cellar/php/8.0.11/bin/pear update-channels
==> Caveats
To enable PHP in Apache add the following to httpd.conf and restart Apache:
    LoadModule php_module /opt/homebrew/opt/php/lib/httpd/modules/libphp.so

    <FilesMatch \.php$>
        SetHandler application/x-httpd-php
    </FilesMatch>

Finally, check DirectoryIndex includes index.php
    DirectoryIndex index.php index.html

The php.ini and php-fpm.ini file can be found in:
    /opt/homebrew/etc/php/8.0/

To start php:
  brew services start php
Or, if you don't want/need a background service you can just run:
  /opt/homebrew/opt/php/sbin/php-fpm --nodaemonize
==> Summary
🍺  /opt/homebrew/Cellar/php/8.0.11: 500 files, 78.0MB
Removing: /opt/homebrew/Cellar/php/8.0.8_1... (500 files, 78.0MB)
Error: Directory not empty @ dir_s_rmdir - /opt/homebrew/Cellar/php/8.0.8_1
```

```
... (other brew upgrade output) ...
==> Upgrading dnsmasq
  2.85 -> 2.86

==> Pouring dnsmasq--2.86.arm64_big_sur.bottle.tar.gz
==> Caveats
To restart dnsmasq after an upgrade:
  sudo brew services restart dnsmasq
Or, if you don't want/need a background service you can just run:
  /opt/homebrew/opt/dnsmasq/sbin/dnsmasq --keep-in-foreground -C /opt/homebrew/etc/dnsmasq.conf -7 /opt/homebrew/etc/dnsmasq.d,*.conf
==> Summary
🍺  /opt/homebrew/Cellar/dnsmasq/2.86: 10 files, 614.9KB
Removing: /opt/homebrew/Cellar/dnsmasq/2.85... (10 files, 605.9KB)
Error: Directory not empty @ dir_s_rmdir - /opt/homebrew/Cellar/dnsmasq/2.85
```

```
... (other brew upgrade output) ...
==> Upgrading nginx
  1.21.1 -> 1.21.3

==> Pouring nginx--1.21.3.arm64_big_sur.bottle.tar.gz
==> Caveats
Docroot is: /opt/homebrew/var/www

The default port has been set in /opt/homebrew/etc/nginx/nginx.conf to 8080 so that
nginx can run without sudo.

nginx will load all files in /opt/homebrew/etc/nginx/servers/.

To start nginx:
  brew services start nginx
Or, if you don't want/need a background service you can just run:
  /opt/homebrew/opt/nginx/bin/nginx -g 'daemon off;'
==> Summary
🍺  /opt/homebrew/Cellar/nginx/1.21.3: 26 files, 2.2MB
Removing: /opt/homebrew/Cellar/nginx/1.21.1... (25 files, 2.2MB)
Error: Directory not empty @ dir_s_rmdir - /opt/homebrew/Cellar/nginx/1.21.1
```

## Possible solution

Maybe valet can install its dependencies the way a normal user would interact with Homebrew (without using root)?

## Diagnosis

n/a

**Comment by JoeCianflone** [comment]
I've been bit by this a couple of times too and it drives me crazy. I assume there must be a reason why it's running under `sudo` but it would be better if only the commands that needed it ran as root.

I have not had a chance to play with it, but if anyone has time to see what breaks if you change the `runAsUser()` function in `CommandLine.php`, I think that would be the starting point.

https://github.com/laravel/valet/blob/233539d890e7d69d87649fa3411acc5920e6af3c/cli/Valet/CommandLine.php#L61-L64

**Comment by jools-r** [comment]
Do you have any additional custom extensions installed? I get this error with the php directory on one computer (an M1/arm mac) where I also have the `imagick.so` extension installed per pecl. It's placed in the directory `/opt/homebrew/Cellar/php/{version}/lib/php/20200930/` and I have to do the same `sudo rm -rf …` command and continue with `brew upgrade` to complete upgrading. After upgrading php I have to reinstate `imagick.so` for the new php version for valet to run.

On another computer where I don't have imagick.so installed this doesn't happen. That computer is an intel Mac so the brew path's are different but otherwise the config is identical.

**Comment by JoeCianflone** [comment]
@jools-r oh that's interesting, I have xdebug installed via pecl and I got totally confused yesterday when I went to use xdebug and it wasn't installed. I thought I must have somehow deleted it or maybe I didn't install it, now I realize I nuked it with my `rm -rf`. I have no idea if it's the pecls causing this issue, but they seem to be a casualty for sure.

**Comment by adriaanzon** [comment]
I just checked. On one Mac I have Xdebug installed, and on the other Mac the Redis extension. I'm wondering how Pecl installations would also affect dnsmasq and Nginx, though.

I have uninstalled the Redis extension from that Mac, and reinstalled Laravel Valet. Now I'll wait until a new update for PHP, dnsmasq or Nginx releases, to see if the problem still persists.

**Comment by JoeCianflone** [comment]
Yeah, I don't know. I'm slightly skeptical on the pecl being the main reason because, like you, I also have this same problem with nginx and dnsmasq and I don't have any extensions for those. I feel like this has more to do with running the installs with `sudo`.  I mean, think about what it's trying to do, it's trying to remove a folder that homebrew doesn't have the rights to remove since it was put there by `user()` but with elevated privileges. Not that anyone should want to do this but I'd bet money that if you had installed brew with `sudo` you wouldn't have this problem. (Please for the love of god anyone reading this DON'T TRY IT)

**Comment by driesvints** [comment]
Closing this issue because it's inactive, already solved, old or not relevant anymore. Feel to open up a new issue if you're still experiencing this.
