### ISSUE TITLE
Root CA expires after 730 days without a convenient way to renew it

### ISSUE THREAD

**Issue by jaylinski** [laravel/valet#1103]
## Clear description of your problem
The generated root CA `LaravelValetCASelfSigned.pem` expires after 730 days, which will result in the error `cURL error 60: SSL certificate problem: unable to get local issuer certificate` when sending a PHP cURL request to a Valet secured domain.

### Option 1

Valet auto-rotates (renews) the root CA automatically and informs the user to recreate a CA bundle for cURL by running `brew reinstall ca-certificates`.

### Option 2

Valet provides a `valet renew` command that creates a new root CA and creates new certs for existing sites, adds them to the Keychain, then executes `brew reinstall ca-certificates` in order to regenerate a CA certificate bundle from the keychain.

## Current behavior
The root CA expires and things break with `cURL error 60: SSL certificate problem: unable to get local issuer certificate`.

There is no convenient way to create a new root CA and child-certificates for existing sites.

The current workaround is to delete the `valet/CA`-folder and re-secure existing sites.

## Steps to Reproduce

1. Install Valet
2. Wait 731 days and run `brew reinstall ca-certificates` (the CA bundle for cURL won't contain the expire Valet Root CA anymore)
3. Make a https request via PHP cURL to a site secured with Valet
4. Get the error `cURL error 60: SSL certificate problem: unable to get local issuer certificate`
5. Spend a lot of hours in order to figure out how certificate validation on macOS with cURL and PHP works 🙃 

### Output of these steps
/

## Possible solution

Valet either auto-rotates the root CA (by checking its age) or provides a command to manually renew the root CA.

I can provide a PR for one of these options, if desired.

## Diagnosis
<details>
    <summary>sw_vers</summary>
    <pre>ProductName:	macOS
ProductVersion:	11.6
BuildVersion:	20G165</pre>
</details>
<details>
    <summary>valet --version</summary>
    <pre>Laravel Valet 2.16.0</pre>
</details>

**Comment by driesvints** [comment]
Hey @jaylinski, I think "Valet either auto-rotates the root CA (by checking its age)" is would be a good pragmatic solution here. Are you willing to send in a PR for that? 

Also https://github.com/laravel/valet/pull/1154 got merged so the expiry date is half of what it was before.

**Comment by jaylinski** [comment]
> Are you willing to send in a PR for that?

@driesvints Yes, I'll send in a PR this week.
