### ISSUE TITLE
Nginx is not starting up

### ISSUE THREAD

**Issue by ahoiroman** [laravel/valet#1110]
`composer self-update` => You are already using the latest available Composer version 2.1.12 (stable channel).
`composer global update` =>  Nothing to install, update or remove
`brew upgrade` => Updated 1 tap (homebrew/core)

## Clear description of your problem

After running `valet install` Nginx is not coming up.

## Expected behavior
Nginx should boot up fine

## Current behavior
```
sudo brew services list                                
Password:
256
Name    Status  User File
dnsmasq started root 
nginx   error   root 
php     started root 
```

A less to `/opt/homebrew/var/log/nginx/error.log` shows:

> 2021/11/27 17:33:03 [emerg] 26386#0: unexpected end of parameter, expecting ";" in command line

## Steps to Reproduce
1. Install brew
2. `brew install php`
3. `brew install composer`
4. `composer global require laravel/valet`
5. `valet install`

### Output of these steps

```
valet install  
Stopping nginx...
Installing nginx...
[nginx] is not installed, installing it now via Brew... 🍻
Installing nginx configuration...
Installing nginx directory...
Updating PHP configuration...
Restarting php...
Updating Dnsmasq configuration...
Restarting dnsmasq...
Valet is configured to serve for TLD [.test]
Restarting nginx...

Valet installed successfully!
```

## Diagnosis
<details>
<summary>sw_vers</summary>
<pre>ProductName:	macOS
ProductVersion:	12.0.1
BuildVersion:	21A559</pre>
</details>
<details>
<summary>valet --version</summary>
<pre>Laravel Valet 2.16.1</pre>
</details>
<details>
<summary>cat ~/.config/valet/config.json</summary>
<pre>{
    "tld": "test",
    "loopback": "127.0.0.1",
    "paths": []
}</pre>
</details>
<details>
<summary>cat ~/.composer/composer.json</summary>
<pre>{
    "require": {
        "laravel/valet": "^2.16"
    }
}</pre>
</details>
<details>
<summary>composer global diagnose</summary>
<pre>Changed current directory to /Users/ahoi/.composer
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: FAIL
Missing pubkey for tags verification
Missing pubkey for dev verification
Run composer self-update --update-keys to set them up
Checking composer version: OK
Composer version: 2.1.12
PHP version: 8.0.13
PHP binary path: /opt/homebrew/Cellar/php/8.0.13_1/bin/php
OpenSSL version: OpenSSL 1.1.1l  24 Aug 2021
cURL version: 7.80.0 libz 1.2.11 ssl (SecureTransport) OpenSSL/1.1.1l
zip: extension present, unzip present, 7-Zip not available</pre>
</details>
<details>
<summary>composer global outdated</summary>
<pre>Changed current directory to /Users/ahoi/.composer
Legend:
! patch or minor release available - update recommended
~ major release available - update possible
psr/container                 1.1.2  ~ 2.0.2  Common Container Interface (PHP FIG PSR-11)
psr/simple-cache              1.0.1  ~ 3.0.0  Common interfaces for simple caching
symfony/deprecation-contracts v2.5.0 ~ v3.0.0 A generic function and convention to trigger deprecation notices
symfony/service-contracts     v2.5.0 ~ v3.0.0 Generic abstractions related to writing services</pre>
</details>
<details>
<summary>ls -al /etc/sudoers.d/</summary>
<pre>total 0
drwxr-xr-x   2 root  wheel    64 18 Okt 05:30 .
drwxr-xr-x  82 root  wheel  2624 27 Nov 17:08 ..</pre>
</details>
<details>
<summary>brew config</summary>
<pre>HOMEBREW_VERSION: 3.3.5
ORIGIN: https://github.com/Homebrew/brew
HEAD: 354718c40a4e7cc4e5d1d4b03fdce8b992e04e8a
Last commit: 5 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: fe633ddc44c3fdbdff9503779c98ca39b85fea8e
Core tap last commit: 8 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 13.0.0 build 1300
Git: 2.30.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.77.0 => /usr/bin/curl
macOS: 12.0.1-arm64
CLT: 13.1.0.0.1.1633545042
Xcode: N/A
Rosetta 2: false</pre>
</details>
<details>
<summary>brew services list</summary>
<pre>256
Name    Status  User    File
dnsmasq stopped         
nginx   error   ahoi 
php     started root</pre>
</details>
<details>
<summary>brew list --formula --versions | grep -E "(php|nginx|dnsmasq|mariadb|mysql|mailhog|openssl)(@\d\..*)?\s"</summary>
<pre>dnsmasq 2.86
nginx 1.21.4
openssl@1.1 1.1.1l_1
php 8.0.13_1</pre>
</details>
<details>
<summary>brew outdated</summary>
<pre></pre>
</details>
<details>
<summary>brew tap</summary>
<pre>homebrew/core
homebrew/services</pre>
</details>
<details>
<summary>php -v</summary>
<pre>PHP 8.0.13 (cli) (built: Nov 24 2021 11:02:19) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.13, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.13, Copyright (c), by Zend Technologies</pre>
</details>
<details>
<summary>which -a php</summary>
<pre>/opt/homebrew/bin/php</pre>
</details>
<details>
<summary>php --ini</summary>
<pre>Configuration File (php.ini) Path: /opt/homebrew/etc/php/8.0
Loaded Configuration File:         /opt/homebrew/etc/php/8.0/php.ini
Scan for additional .ini files in: /opt/homebrew/etc/php/8.0/conf.d
Additional .ini files parsed:      /opt/homebrew/etc/php/8.0/conf.d/error_log.ini,
/opt/homebrew/etc/php/8.0/conf.d/ext-opcache.ini,
/opt/homebrew/etc/php/8.0/conf.d/php-memory-limits.ini</pre>
</details>
<details>
<summary>nginx -v</summary>
<pre>nginx version: nginx/1.21.4</pre>
</details>
<details>
<summary>curl --version</summary>
<pre>curl 7.77.0 (x86_64-apple-darwin21.0) libcurl/7.77.0 (SecureTransport) LibreSSL/2.8.3 zlib/1.2.11 nghttp2/1.42.0
Release-Date: 2021-05-26
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: alt-svc AsynchDNS GSS-API HSTS HTTP2 HTTPS-proxy IPv6 Kerberos Largefile libz MultiSSL NTLM NTLM_WB SPNEGO SSL UnixSockets</pre>
</details>
<details>
<summary>php --ri curl</summary>
<pre>curl

cURL support => enabled
cURL Information => 7.80.0
Age => 9
Features
AsynchDNS => Yes
CharConv => No
Debug => No
GSS-Negotiate => No
IDN => Yes
IPv6 => Yes
krb4 => No
Largefile => Yes
libz => Yes
NTLM => Yes
NTLMWB => Yes
SPNEGO => Yes
SSL => Yes
SSPI => No
TLS-SRP => Yes
HTTP2 => Yes
GSSAPI => Yes
KERBEROS5 => Yes
UNIX_SOCKETS => Yes
PSL => No
HTTPS_PROXY => Yes
MULTI_SSL => Yes
BROTLI => Yes
Protocols => dict, file, ftp, ftps, gopher, gophers, http, https, imap, imaps, ldap, ldaps, mqtt, pop3, pop3s, rtmp, rtsp, scp, sftp, smb, smbs, smtp, smtps, telnet, tftp
Host => arm-apple-darwin21.1.0
SSL Version => (SecureTransport) OpenSSL/1.1.1l
ZLib Version => 1.2.11
libSSH Version => libssh2/1.10.0

Directive => Local Value => Master Value
curl.cainfo => no value => no value</pre>
</details>
<details>
<summary>~/.composer/vendor/laravel/valet/bin/ngrok version</summary>
<pre>ngrok version 2.3.40</pre>
</details>
<details>
<summary>ls -al ~/.ngrok2</summary>
<pre>ls: /Users/ahoi/.ngrok2: No such file or directory</pre>
</details>
<details>
<summary>brew info nginx</summary>
<pre>nginx: stable 1.21.4 (bottled), HEAD
HTTP(S) server and reverse proxy, and IMAP/POP3 proxy server
https://nginx.org/
/opt/homebrew/Cellar/nginx/1.21.4 (26 files, 2.2MB) *
  Poured from bottle on 2021-11-27 at 17:32:53
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/nginx.rb
License: BSD-2-Clause
==> Dependencies
Required: openssl@1.1, pcre
==> Options
--HEAD
	Install HEAD version
==> Caveats
Docroot is: /opt/homebrew/var/www

The default port has been set in /opt/homebrew/etc/nginx/nginx.conf to 8080 so that
nginx can run without sudo.

nginx will load all files in /opt/homebrew/etc/nginx/servers/.

To restart nginx after an upgrade:
  brew services restart nginx
Or, if you don't want/need a background service you can just run:
  /opt/homebrew/opt/nginx/bin/nginx -g 'daemon off;'
==> Analytics
install: 50,022 (30 days), 137,469 (90 days), 512,969 (365 days)
install-on-request: 49,922 (30 days), 137,147 (90 days), 511,686 (365 days)
build-error: 71 (30 days)</pre>
</details>
<details>
<summary>brew info php</summary>
<pre>php: stable 8.0.13 (bottled), HEAD
General-purpose scripting language
https://www.php.net/
/opt/homebrew/Cellar/php/8.0.13_1 (500 files, 77.7MB) *
  Poured from bottle on 2021-11-27 at 17:17:15
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/php.rb
License: PHP-3.01
==> Dependencies
Build: httpd, pkg-config
Required: apr, apr-util, argon2, aspell, autoconf, curl, freetds, gd, gettext, gmp, icu4c, krb5, libffi, libpq, libsodium, libzip, oniguruma, openldap, openssl@1.1, pcre2, sqlite, tidy-html5, unixodbc
==> Options
--HEAD
	Install HEAD version
==> Caveats
To enable PHP in Apache add the following to httpd.conf and restart Apache:
    LoadModule php_module /opt/homebrew/opt/php/lib/httpd/modules/libphp.so

    <FilesMatch \.php$>
        SetHandler application/x-httpd-php
    </FilesMatch>

Finally, check DirectoryIndex includes index.php
    DirectoryIndex index.php index.html

The php.ini and php-fpm.ini file can be found in:
    /opt/homebrew/etc/php/8.0/

To restart php after an upgrade:
  brew services restart php
Or, if you don't want/need a background service you can just run:
  /opt/homebrew/opt/php/sbin/php-fpm --nodaemonize
==> Analytics
install: 104,191 (30 days), 221,517 (90 days), 685,132 (365 days)
install-on-request: 81,207 (30 days), 196,348 (90 days), 651,204 (365 days)
build-error: 87 (30 days)</pre>
</details>
<details>
<summary>brew info openssl</summary>
<pre>openssl@3: stable 3.0.0 (bottled) [keg-only]
Cryptography and SSL/TLS Toolkit
https://openssl.org/
Not installed
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/openssl@3.rb
License: Apache-2.0
==> Dependencies
Required: ca-certificates
==> Caveats
A CA file has been bootstrapped using certificates from the system
keychain. To add additional certificates, place .pem files in
  /opt/homebrew/etc/openssl@3/certs

and run
  /opt/homebrew/opt/openssl@3/bin/c_rehash

openssl@3 is keg-only, which means it was not symlinked into /opt/homebrew,
because macOS provides LibreSSL.

==> Analytics
install: 84,630 (30 days), 192,361 (90 days), 192,362 (365 days)
install-on-request: 71,236 (30 days), 158,032 (90 days), 158,033 (365 days)
build-error: 4,430 (30 days)</pre>
</details>
<details>
<summary>openssl version -a</summary>
<pre>LibreSSL 2.8.3
built on: date not available
platform: information not available
options:  bn(64,64) rc4(ptr,int) des(idx,cisc,16,int) blowfish(idx) 
compiler: information not available
OPENSSLDIR: "/private/etc/ssl"</pre>
</details>
<details>
<summary>openssl ciphers</summary>
<pre>ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-CHACHA20-POLY1305:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:GOST2012256-GOST89-GOST89:DHE-RSA-CAMELLIA256-SHA256:DHE-RSA-CAMELLIA256-SHA:GOST2001-GOST89-GOST89:AES256-GCM-SHA384:AES256-SHA256:AES256-SHA:CAMELLIA256-SHA256:CAMELLIA256-SHA:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-CAMELLIA128-SHA256:DHE-RSA-CAMELLIA128-SHA:AES128-GCM-SHA256:AES128-SHA256:AES128-SHA:CAMELLIA128-SHA256:CAMELLIA128-SHA:ECDHE-RSA-RC4-SHA:ECDHE-ECDSA-RC4-SHA:RC4-SHA:RC4-MD5:ECDHE-RSA-DES-CBC3-SHA:ECDHE-ECDSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:DES-CBC3-SHA</pre>
</details>
<details>
<summary>sudo nginx -t</summary>
<pre>nginx: [emerg] open() "/opt/homebrew/etc/nginx/valet/valet.conf" failed (2: No such file or directory) in /opt/homebrew/etc/nginx/nginx.conf:46
nginx: configuration file /opt/homebrew/etc/nginx/nginx.conf test failed</pre>
</details>
<details>
<summary>which -a php-fpm</summary>
<pre>/opt/homebrew/sbin/php-fpm</pre>
</details>
<details>
<summary>/opt/homebrew/opt/php/sbin/php-fpm -v</summary>
<pre>PHP 8.0.13 (fpm-fcgi) (built: Nov 24 2021 11:02:21)
Copyright (c) The PHP Group
Zend Engine v4.0.13, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.13, Copyright (c), by Zend Technologies</pre>
</details>
<details>
<summary>sudo /opt/homebrew/opt/php/sbin/php-fpm -y /opt/homebrew/etc/php/8.0/php-fpm.conf --test</summary>
<pre>[27-Nov-2021 17:51:07] NOTICE: configuration file /opt/homebrew/etc/php/8.0/php-fpm.conf test is successful</pre>
</details>
<details>
<summary>ls -al ~/Library/LaunchAgents | grep homebrew</summary>
<pre>-rw-r--r--   1 ahoi  staff   550 27 Nov 13:54 homebrew.mxcl.mariadb.plist
-rw-r--r--   1 ahoi  staff   500 27 Nov 17:35 homebrew.mxcl.nginx.plist
-rw-r--r--   1 ahoi  staff   586 27 Nov 17:04 homebrew.mxcl.php.plist</pre>
</details>
<details>
<summary>ls -al /Library/LaunchAgents | grep homebrew</summary>
<pre></pre>
</details>
<details>
<summary>ls -al /Library/LaunchDaemons | grep homebrew</summary>
<pre>-rw-r--r--   1 root  admin   602 27 Nov 17:33 homebrew.mxcl.dnsmasq.plist
-rw-r--r--   1 root  admin   500 27 Nov 17:33 homebrew.mxcl.nginx.plist
-rw-r--r--   1 root  admin   586 27 Nov 17:32 homebrew.mxcl.php.plist</pre>
</details>
<details>
<summary>ls -al /Library/LaunchDaemons | grep "com.laravel.valet."</summary>
<pre></pre>
</details>
<details>
<summary>ls -aln /etc/resolv.conf</summary>
<pre>lrwxr-xr-x  1 0  0  22 18 Okt 05:30 /etc/resolv.conf -> ../var/run/resolv.conf</pre>
</details>
<details>
<summary>cat /etc/resolv.conf</summary>
<pre>#
# macOS Notice
#
# This file is not consulted for DNS hostname resolution, address
# resolution, or the DNS query routing mechanism used by most
# processes on this system.
#
# To view the DNS configuration used by this system, use:
#   scutil --dns
#
# SEE ALSO
#   dns-sd(1), scutil(8)
#
# This file is automatically generated.
#
search fritz.box
nameserver 192.168.178.1</pre>
</details>
<details>
<summary>ifconfig lo0</summary>
<pre>lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> mtu 16384
	options=1203<RXCSUM,TXCSUM,TXSTATUS,SW_TIMESTAMP>
	inet 127.0.0.1 netmask 0xff000000 
	inet6 ::1 prefixlen 128 
	inet6 fe80::1%lo0 prefixlen 64 scopeid 0x1 
	nd6 options=201<PERFORMNUD,DAD></pre>
</details>
<details>
<summary>sh -c 'echo "------\n/opt/homebrew/etc/nginx/valet/valet.conf\n---\n"; cat /opt/homebrew/etc/nginx/valet/valet.conf | grep -n "# valet loopback"; echo "\n------\n"'</summary>
<pre>------
/opt/homebrew/etc/nginx/valet/valet.conf
---

cat: /opt/homebrew/etc/nginx/valet/valet.conf: No such file or directory

------</pre>
</details>
<details>
<summary>sh -c 'for file in ~/.config/valet/dnsmasq.d/*; do echo "------\n~/.config/valet/dnsmasq.d/$(basename $file)\n---\n"; cat $file; echo "\n------\n"; done'</summary>
<pre>------
~/.config/valet/dnsmasq.d/tld-test.conf
---

address=/.test/127.0.0.1
listen-address=127.0.0.1

------</pre>
</details>
<details>
<summary>sh -c 'for file in ~/.config/valet/nginx/*; do echo "------\n~/.config/valet/nginx/$(basename $file)\n---\n"; cat $file | grep -n "# valet loopback"; echo "\n------\n"; done'</summary>
<pre>------
~/.config/valet/nginx/*
---

cat: /Users/ahoi/.config/valet/nginx/*: No such file or directory

------</pre>
</details>

**Comment by ahoiroman** [comment]
Based on 

```
------
/opt/homebrew/etc/nginx/valet/valet.conf
---
cat: /opt/homebrew/etc/nginx/valet/valet.conf: No such file or directory


------
```

I recreated that config based on https://github.com/laravel/valet/blob/master/cli/stubs/valet.conf - but without success.

**Comment by ahoiroman** [comment]
Hm, nginx is running fine, when not started as root. Did something change in brew?

I dumped brew and reinstalled it again - and I also reinstalled Nginx without valet:

```
==> Summary
🍺  /opt/homebrew/Cellar/nginx/1.21.4: 26 files, 2.2MB
==> Caveats
==> nginx
Docroot is: /opt/homebrew/var/www

The default port has been set in /opt/homebrew/etc/nginx/nginx.conf to 8080 so that
nginx can run without sudo.

nginx will load all files in /opt/homebrew/etc/nginx/servers/.

To restart nginx after an upgrade:
  brew services restart nginx
Or, if you don't want/need a background service you can just run:
  /opt/homebrew/opt/nginx/bin/nginx -g 'daemon off;'
➜  LaunchDaemons ll
total 48
-rw-r--r--  1 root  wheel   751B 27 Okt 18:04 com.adguard.mac.adguard.pac.plist
-rw-r--r--  1 root  wheel   779B 27 Okt 18:04 com.adguard.mac.adguard.tun-helper.plist
-rw-r--r--  1 root  wheel   727B 14 Nov 12:30 com.docker.vmnetd.plist
-rw-------  1 root  wheel   271B 18 Nov 08:43 com.microsoft.teams.TeamsUpdaterDaemon.plist
-rw-r--r--  1 root  wheel   548B 22 Jun 19:14 com.teamviewer.Helper.plist
-rw-r--r--  1 root  wheel   611B 22 Jun 19:14 com.teamviewer.teamviewer_service.plist
➜  LaunchDaemons brew install php composer
➜  LaunchDaemons sudo brew services list   
==> Tapping homebrew/services
Cloning into '/opt/homebrew/Library/Taps/homebrew/homebrew-services'...
remote: Enumerating objects: 1535, done.
remote: Counting objects: 100% (414/414), done.
remote: Compressing objects: 100% (303/303), done.
remote: Total 1535 (delta 171), reused 286 (delta 101), pack-reused 1121
Receiving objects: 100% (1535/1535), 448.89 KiB | 4.32 MiB/s, done.
Resolving deltas: 100% (647/647), done.
Tapped 1 command (38 files, 558.9KB).
Name  Status  User File
nginx stopped      
```

The Nginx logs are saying:

```
2021/11/27 20:56:22 [emerg] 16659#0: unexpected end of parameter, expecting ";" in command line
```

And that's because `/Library/LaunchDaemons/homebrew.mxcl.nginx.plist` contains this:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
        <key>Label</key>
        <string>homebrew.mxcl.nginx</string>
        <key>ProgramArguments</key>
        <array>
                <string>/opt/homebrew/opt/nginx/bin/nginx</string>
                <string>-g</string>
                <string>&#39;daemon off;&#39;</string>
        </array>
        <key>RunAtLoad</key>
        <true/>
        <key>WorkingDirectory</key>
        <string>/opt/homebrew</string>
</dict>
</plist>
```

As you can see, the `<string>&#39;daemon off;&#39;</string>` is faulty here. Even if I fix that and restart the service manually, this `&#...` appears again.

**Comment by pactode** [comment]
I have a similar issue and get the following, when I run `nginx -t`:
```
nginx: [warn] the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /opt/homebrew/etc/nginx/nginx.conf:1
nginx: the configuration file /opt/homebrew/etc/nginx/nginx.conf syntax is ok
nginx: [emerg] bind() to 127.0.0.1:80 failed (13: Permission denied)
nginx: configuration file /opt/homebrew/etc/nginx/nginx.conf test failed
```

If I run the same command with sudo in front, it looks OK, but nginx is still marked as error in the `sudo brew services list` and no valet sites are accessible.

**Comment by ahoiroman** [comment]
Could be related to https://github.com/Homebrew/homebrew-core/pull/90023

**Comment by ahoiroman** [comment]
Ugly hack that worked for me:

Edit `/opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/nginx.rb` and change it to `"daemon off;"`. Restart after that.

Disclaimer: That's NOT the way to go - it could damage the service I guess. I did this on my Mac and it worked, but there SHOULD be a better way to do this.

**Comment by ferrari308guy** [comment]
Seeing the exact same issue on my Mac as well.

**Comment by skeemer** [comment]
@ferrari308guy I ended up editing Cellar/nginx/1.21.4/homebrew.mxcl.nginx.plist to get it working.

**Comment by ahoiroman** [comment]
Issue is under investigation: https://github.com/Homebrew/homebrew-core/pull/90023#issuecomment-981059701

So I guess we will see an update within the next hours or days. :-)

**Comment by danielpastoor** [comment]
> Issue is under investigation: [Homebrew/homebrew-core#90023 (comment)](https://github.com/Homebrew/homebrew-core/pull/90023#issuecomment-981059701)
> 
> So I guess we will see an update within the next hours or days. :-)

The issue has been fixed.

To apply the fix, run the following commands:

`brew update && brew reinstall nginx`

**Comment by ahoiroman** [comment]
I can confirm: Works fine.

So I guess this issue can be closed.

For all of you who fixed things manually: Consider running `valet uninstall` and reinstall via `valet install`.
