### ISSUE TITLE
Deprecation notices with Valet in PHP 8.1 due to tightenco/collect dependency 

### ISSUE THREAD

**Issue by wturrell** [laravel/valet#1112]
In the last 24 hours, the PHP 8.1 package has been made available on macOS via homebrew. After upgrading, Valet spews out errors like this on every command:

> Deprecated: Return type of Tightenco\Collect\Support\Collection::offsetExists($key) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/wt/.composer/vendor/tightenco/collect/src/Collect/Support/Collection.php on line 1411

> Deprecated: Return type of Tightenco\Collect\Support\Collection::offsetGet($key) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/wt/.composer/vendor/tightenco/collect/src/Collect/Support/Collection.php on line 1422

> Deprecated: Return type of Tightenco\Collect\Support\Collection::offsetUnset($key) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/wt/.composer/vendor/tightenco/collect/src/Collect/Support/Collection.php on line 1449

etc.

[Tightenco\Collect is deprecated](https://github.com/tighten/collect) (apparently we can just use Illuminate/Collections now? (There is already [an issue](https://github.com/tighten/collect/issues/261) open about the errors, as the readme says they would maintain it for Laravel 8 and 9).  Valet still uses it, can this be fixed?

Thank you!

```
$ composer global why tightenco/collect
Changed current directory to /Users/wt/.composer
laravel/valet  v2.16.1  requires  tightenco/collect (^5.3|^6.0|^7.0|^8.0)
```

PHP 8.1.0  
Laravel Valet 2.16.1
macOS 10.14.6

## Diagnosis

Let me know if you actually need any of that output…

**Comment by driesvints** [comment]
Please report this to their repo. There nothing we can do here

**Comment by wturrell** [comment]
@driesvints can Valet not be changed to use Illuminate/Collect?

**Comment by driesvints** [comment]
There's an issue open for that iirc but involves a lot.

**Comment by mattstauffer** [comment]
@wturrell Just a note: This has been fixed on the Collect side and running `composer global update` should fix this problem for you!

**Comment by tomavic** [comment]
> @wturrell Just a note: This has been fixed on the Collect side and running `composer global update` should fix this problem for you!

that was quick win 🚀🚀
