### ISSUE TITLE
Incorrect version number

### ISSUE THREAD

**Issue by lesaff** [laravel/valet#113]
I just updated composer globally, saw valet 1.1.17 package update. I reinstall valet, and upon running `valet -V` it returns version 1.1.16 instead of 1.1.17.

![screen shot 2016-08-14 at 9 51 17 am](https://cloud.githubusercontent.com/assets/1151181/17649195/b0372d10-6204-11e6-8b33-2a7ee140dfaa.png)

**Comment by adamwathan** [comment]
Yep we know about this, unfortunately it's not fixable without tagging 1.1.18, so will have to remain incorrect until then.
