### ISSUE TITLE
Server not found, Can't find DNS (127.0.53.53)

### ISSUE THREAD

**Issue by NicolaeCasir** [laravel/valet#115]
HI. Please help me. Valet isn't working. No, it's working but not properly. I installed my osx and created user admin. I started to work on it, installed composer, laravel, valet. After i created new user and deleted the old.  After this I can't acces sites from Valet((  Please help me. Maybe i have to uninstall all what is everything's about valet, but how?
![captura de ecran din 2016 08 16 la 13 21 10](https://cloud.githubusercontent.com/assets/8903698/17696216/a605795c-63b5-11e6-8896-617aa14328c0.png)

**Comment by adamwathan** [comment]
Try reinstalling Valet as the new user.

**Comment by drbyte** [comment]
127.0.53.53 is the generic redirect for "the TLD you used has another master DNS", which is kinda cryptic, but basically it means you're looking for `*.dev` but your computer is hitting a public DNS server and not `dnsmasq` (or `dnsmasq` isn't responding to `*.dev`).

To fix this you'll need to get `dnsmasq` running properly again. Then valet should resume operation just fine.

(I ran into the same problem a month ago)

Sometimes it's helpful to tell dnsmasq to log its activities, and then in the logs you can discover things like "something else is already listening on that port" etc.

dnsmasq.conf:
```sh
address=/.dev/127.0.0.1

# Logging

# set filename:
log-facility=/Users/your_name/Documents/dnsmasq.log

# enable logging:
log-queries
```



Here's my `/.valet/dnsmasq.conf` file, in case any of these additional parameters are helpful to you.  Some of the things in here have been added because I also use dnscrypt-proxy, but should be harmless even if you don't.
```sh
address=/.dev/127.0.0.1

#ignore resolv.conf
no-resolv
no-poll

# listen only on localhost (for dnscrypt)
listen-address=127.0.0.1
# The bind-interfaces directive instructs dnsmasq to bind only to the network interface specified in the listen-address directive, which is important for dnscrypt use
bind-interfaces
# dnscrypt-proxy is on port 53:
server=127.0.0.1#53

# The following directives prevent dnsmasq from forwarding plain names (without any dots) or addresses in the non-routed address space to the parent nameservers.
domain-needed
bogus-priv

# default is 150, or 0 = off
cache-size=0


# Logging
log-facility=/Users/my_user_name/Downloads/dnsmasq.log
log-queries


# fallback servers to use if we can't resolve using our own rules
server=208.67.220.222
server=208.67.220.220
#server=4.4.4.4


#domain-needed This tells dnsmasq to never pass short names to the upstream DNS servers. If the name is not in the local /etc/hosts file then “not found” will be returned.
#bogus-priv All reverse IP (192.168.x.x) lookups that are not found in /etc/hosts will be returned as “no such domain” and not forwarded to the upstream servers.
#no-resolv Do not read resolv.conf to find the servers where to lookup dns.
#no-poll Do not poll resolv.conf for changes
#server=8.8.8.8 Set one or more DNS servers to use when addresses are not local. These are open DNS servers.
#local=/example.com/ Our local domain, queries in these domains are answered from /etc/hosts or the static-hosts files.
#address=/doubleclick.net/127.0.0.1 Use this force an address for the specified domains. e.g to block adverts force doubleclck.net to localhost
#no-hosts This options stops dnsmasq using the local /etc/hosts file as a source for lookups .
#addn-hosts=/etc/dnsmasq_static_hosts.conf Force dnsmasq to use this file for lookups. It is in the same format as /etc/hosts.
#expand_hosts So we can see our local hosts via our home domain without having to repeatedly specify the domain in our /etc/hosts file.
```

**Comment by mityukov** [comment]
Having the same issue on Yosemite install.. Only adding `log-facility` and `log-queries` to the `~/.valet/dnsmasq.conf` doesn't have any effect. No log file in the specified location.

**Comment by chucklin72** [comment]
I'm having the same problem mityukov posted. no logs, only resolve to 127.0.53.53
When i do brew services list

Name    Status  User Plist
dnsmasq started chuck /Users/chuck/Library/LaunchAgents/homebrew.mxcl.dnsmasq.plist

checking the Plist file and its empty. So I added the config as suggested by drbyte. Still no logs.

**Comment by chucklin72** [comment]
mityukov try to reinstall valet as root.
sudo valet install

**Comment by Spomsoree** [comment]
Resetting `valet domain test` made it work again for me.
