### ISSUE TITLE
valet bin only have x86 version of ngrok

### ISSUE THREAD

**Issue by xeon-zolt** [laravel/valet#1171]
- Valet Version: 2.18.3
- PHP Version: 7.4

### Description:
when running valet share on m1 mac with apple silicon it says 
`sudo: unable to execute /Users/xeon/.composer/vendor/laravel/valet/bin/ngrok: Bad CPU type in executable`

### Steps To Reproduce:
run valet share on non x86 cpu arch

**Comment by xeon-zolt** [comment]
I need to change the valet bash script with a if else and need to include binary of ngrok in bin for m1 mac

**Comment by driesvints** [comment]
I currently seem to be able to run ngrok with Valet fine expect I'm stumbling into a connection issue. I think this works fine with m1 Mac's right now. I'll need to figure out what's causing the connection issue before I can verify that.

In the meantime please try to update homebrew to the latest version and reinstall Valet completely.

**Comment by xeon-zolt** [comment]
let me try that

**Comment by xeon-zolt** [comment]
is ngrok shipped with Valet or downloaded via homebrew ?

**Comment by driesvints** [comment]
Shipped with Valet: https://github.com/laravel/valet/blob/master/bin/ngrok

I'm not really sure where I can find the latest ngrok binary but it indeed seems we should update it.

**Comment by mattstauffer** [comment]
https://github.com/laravel/valet/pull/1082

Here's what a PR looks like to update the binary, FWIW, in case we need to.

**Comment by driesvints** [comment]
Seems like v2.3.40 that currently ships is already the latest version so that can't be it.

**Comment by xeon-zolt** [comment]
for me, it worked after installing rosetta.
but ngrok ships two different binaries for mac
I think we can include both the versions in the valet and 
modify script like this around line 81 
```
    arch = $(uname -m)
    if [[ $arch == arm64 ]]; then
        sudo -u "$USER" "$DIR/bin/ngrok-arm" http "$HOST.$TLD:$PORT" -host-header=rewrite $PARAMS
    else 
        sudo -u "$USER" "$DIR/bin/ngrok" http "$HOST.$TLD:$PORT" -host-header=
rewrite $PARAMS"
    fi

**Comment by driesvints** [comment]
@xeon-zolt yeah that sounds like an idea maybe. Is there a repo with these on GitHub somewhere?

**Comment by xeon-zolt** [comment]
ngrok 2.0 is not opensource only binary file available on main website which can be fetched

**Comment by driesvints** [comment]
Do you have an url?

**Comment by xeon-zolt** [comment]
https://ngrok.com/download

**Comment by driesvints** [comment]
Thank you. I'll try to have a look soon.
