### ISSUE TITLE
[Proposition] Subdirectory as subdomain?

### ISSUE THREAD

**Issue by Siprah** [laravel/valet#120]
Hi!

I have looked at Valet, it's just awesome! Probably it will replace Docker and Vagrant for me to quick development in my machine. But, there's a little suggestion. 

For example: I'm working on some companies, and my naming of directories are: `~/Sites/[company-name]/[project]`. My domains are: `project-name.company.dev`.

I think it could be a great feature as root directory could be domain name, and subdirectory - subdomain. Of course, I think also it should be configurable (use naming in current one, or in my suggestion).

What are you think about it?

**Comment by adamwathan** [comment]
It's an interesting idea but subdomains are kind of tricky to get working properly in all cases with all drivers, so I think we will hold on it at the moment. Thanks!
