### ISSUE TITLE
Error establishing a database connection

### ISSUE THREAD

**Issue by ksr583** [laravel/valet#121]
Sorry of this is out of scope for this repo, but I've followed tutorials for installing Wordpress on Valet, and, despite being able to connect through Sequel Pro to the local database on localhost/127.0.0.1, Wordpress sites aren't able to connect to it. Anyone have any ideas on what could be causing this? I checked my `hosts` file, checked to make sure nothing else is listening on port 80, etc...

**Comment by georgeboot** [comment]
What are the connection parameters you are using?
