### ISSUE TITLE
WordPress 4.6 - Fatal Error: Uncaught phpmailerException

### ISSUE THREAD

**Issue by evansvince** [laravel/valet#123]
The latest version of Wordpress (4.6) and Valet causes a fatal error on step 2 of installing wordpress. The error is "**Fatal error: Uncaught phpmailerException: Invalid address: wordpress@....**".

This error occurs because WP expects the $_SERVER['SERVER_NAME'] to be set in order to create the $from_email variable. See wp-includes/pluggable.php ~line 326.

By default, Valet does not set the $_SERVER['SERVER_NAME']. Run phpinfo() and you will see no value.

To fix this issue: 

In ~/.composer/vendor/laravel/valet/clu/drivers/WordPressValetDriver.php, within the frontControllerPath, add the following:

`$_SERVER['SERVER_NAME'] = $siteName.'.dev'`

That's assuming you are using the `.dev` TLD. If not, change it to whatever you are using.

Run `valet restart`.

**Comment by jastuccio** [comment]
This fixed my problem.  Here is the function, including the new line.

` 
/**
     * Get the fully resolved path to the application's front controller.
     *
     * @param  string  $sitePath
     * @param  string  $siteName
     * @param  string  $uri
     * @return string
     */
    public function frontControllerPath($sitePath, $siteName, $uri)
    {
        $_SERVER['PHP_SELF']    = $uri;
        $_SERVER['SERVER_ADDR'] = '127.0.0.1';
        $_SERVER['SERVER_NAME'] = $siteName.'.dev';

        return parent::frontControllerPath(
            $sitePath, $siteName, $this->forceTrailingSlash($uri)
        );
    }
`

**Comment by victorhguillen** [comment]
Perfect it works. Thanks.

**Comment by robertbiswas** [comment]
Yeah. It works for me too! Thank you.

**Comment by adamwathan** [comment]
Fixed in https://github.com/laravel/valet/commit/353f24cea80808522c95fd4dc7189b5b4954dcad

**Comment by tmartin31** [comment]
Super helpful. Thanks for the fix.

**Comment by branigan** [comment]
MacOS Sierra
Related on CakePHP 3.4:
Add to frontControllerPath this: 

$_SERVER['PHP_SELF']    = $uri; 

on CakeValetDriver.php to work properly.
