### ISSUE TITLE
Valet isolate with alias/link

### ISSUE THREAD

**Issue by eossa** [laravel/valet#1231]
- Valet Version: 3.1.0
- PHP Version: 7.1.33

### Description:
The isolation does not work with alias/link. Only works without it.

### Steps To Reproduce:
valet link doe.localhost
valet isolate --site doe.localhost
Go to doe.localhost and print the phpinfo() (shows the default php version)
Go to doe.localhost.test and print the phpinfo() (shows the isolated version)

### Diagnosis

<details>
<summary>sw_vers</summary>
<pre>ProductName:	macOS
ProductVersion:	11.6.4
BuildVersion:	20G417</pre>
</details>
<details>
<summary>valet --version</summary>
<pre>Laravel Valet 3.1.0</pre>
</details>
<details>
<summary>cat ~/.config/valet/config.json</summary>
<pre>{
    "tld": "test",
    "loopback": "127.0.0.1",
    "paths": [
        "/Users/eOssa/.config/valet/Sites"
    ]
}</pre>
</details>
<details>
<summary>cat ~/.composer/composer.json</summary>
<pre>{
    "require": {
        "squizlabs/php_codesniffer": "^3.4",
        "laravel/valet": "^3.0"
    }
}</pre>
</details>
<details>
<summary>composer global diagnose</summary>
<pre>Changed current directory to /Users/eOssa/.composer
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: You are not running the latest stable version, run `composer self-update` to update (1.10.16 => 2.2.11)
Composer version: 1.10.16
PHP version: 7.0.33
PHP binary path: /usr/local/Cellar/php@7.0/7.0.33_5/bin/php
OpenSSL version: OpenSSL 1.1.1m  14 Dec 2021</pre>
</details>
<details>
<summary>composer global outdated</summary>
<pre>Changed current directory to /Users/eOssa/.composer
Warning from https://repo.packagist.org: Support for Composer 1 is deprecated and some packages will not be available. You should upgrade to Composer 2. See https://blog.packagist.com/deprecating-composer-1-support/
Info from https://repo.packagist.org: [37;44m#StandWith[30;43mUkraine[0m

The "http://repo.packagist.org/p/squizlabs/php_codesniffer%2446fe0a9736d761753726087f567d76702fbb4b184d5a9ae61c8e0f90bf0cd92a.json" file could not be downloaded: failed to open stream: Operation timed out
Retrying with degraded mode, check https://getcomposer.org/doc/articles/troubleshooting.md#degraded-mode for more info
The "http://repo.packagist.org/p/squizlabs/php_codesniffer%2446fe0a9736d761753726087f567d76702fbb4b184d5a9ae61c8e0f90bf0cd92a.json" file could not be downloaded: php_network_getaddresses: getaddrinfo failed: nodename nor servname provided, or not known
failed to open stream: php_network_getaddresses: getaddrinfo failed: nodename nor servname provided, or not known
http://repo.packagist.org could not be fully loaded, package information was loaded from the local cache and may be out of date
guzzlehttp/psr7 1.8.3 ! 1.8.5 PSR-7 message implementation that also provides common utility methods</pre>
</details>
<details>
<summary>ls -al /etc/sudoers.d/</summary>
<pre>total 0
drwxr-xr-x   2 root  wheel    64 Jan  1  2020 .
drwxr-xr-x  88 root  wheel  2816 Mar 28 00:48 ..</pre>
</details>
<details>
<summary>brew config</summary>
<pre>HOMEBREW_VERSION: 3.4.5-16-gf6ab300
ORIGIN: https://github.com/Homebrew/brew
HEAD: f6ab300fc169777705f025c67c4b7c35605f4a66
Last commit: 24 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: d2f9844971dbe96ea49abb23c71bb1c13acc074f
Core tap last commit: 54 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.8 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8/bin/ruby
CPU: octa-core 64-bit haswell
Clang: 13.0.0 build 1300
Git: 2.32.0 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.6.4-x86_64
CLT: 13.2.0.0.1.1638488800
Xcode: 13.2.1</pre>
</details>
<details>
<summary>brew services list</summary>
<pre>Name               Status User  File
beanstalkd         started         eOssa ~/Library/LaunchAgents/homebrew.mxcl.beanstalkd.plist
dnsmasq            none            root  
elasticsearch-full started         eOssa ~/Library/LaunchAgents/homebrew.mxcl.elasticsearch-full.plist
kibana-full        started         eOssa ~/Library/LaunchAgents/homebrew.mxcl.kibana-full.plist
mailhog            started         eOssa ~/Library/LaunchAgents/homebrew.mxcl.mailhog.plist
memcached          started         eOssa ~/Library/LaunchAgents/homebrew.mxcl.memcached.plist
mongodb-community  started         eOssa ~/Library/LaunchAgents/homebrew.mxcl.mongodb-community.plist
nginx              none            root  
php                none                  
php@7.0            none            root  
php@7.1            none            root  
php@7.4            none                  
php@8.0            none                  
supervisor         started         eOssa ~/Library/LaunchAgents/homebrew.mxcl.supervisor.plist
unbound            none</pre>
</details>
<details>
<summary>brew list --formula --versions | grep -E "(php|nginx|dnsmasq|mariadb|mysql|mailhog|openssl)(@\d\..*)?\s"</summary>
<pre>dnsmasq 2.86
mailhog 1.0.1
nginx 1.21.5
openssl@1.1 1.1.1m
php 8.1.3_1 8.1.1
php@7.0 7.0.33_5
php@7.1 7.1.33_4
php@7.4 7.4.28_1
php@8.0 8.0.16_1</pre>
</details>
<details>
<summary>brew outdated</summary>
<pre>boost
ca-certificates
elastic/tap/elasticsearch-full
elixir
erlang
ffmpeg
fnm
fontconfig
freetype
frei0r
glib
gnutls
gobject-introspection
harfbuzz
elastic/tap/kibana-full
krb5
libarchive
libbluray
libsndfile
libtool
libxml2
memcached
mongodb/brew/mongodb-community
mysql-client
nginx
openssl@1.1
php
php@8.0
python@3.8
python@3.9
sqlite
tesseract</pre>
</details>
<details>
<summary>brew tap</summary>
<pre>elastic/tap
homebrew/cask
homebrew/core
homebrew/services
kabel/php-ext
mongodb/brew
schniz/tap
shivammathur/extensions
shivammathur/php</pre>
</details>
<details>
<summary>php -v</summary>
<pre>PHP 7.0.33 (cli) (built: Mar  3 2022 07:28:37) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.33, Copyright (c) 1999-2017, by Zend Technologies</pre>
</details>
<details>
<summary>which -a php</summary>
<pre>/usr/local/bin/php
/usr/bin/php</pre>
</details>
<details>
<summary>php --ini</summary>
<pre>Configuration File (php.ini) Path: /usr/local/etc/php/7.0
Loaded Configuration File:         /usr/local/etc/php/7.0/php.ini
Scan for additional .ini files in: /usr/local/etc/php/7.0/conf.d
Additional .ini files parsed:      /usr/local/etc/php/7.0/conf.d/error_log.ini,
/usr/local/etc/php/7.0/conf.d/ext-opcache.ini,
/usr/local/etc/php/7.0/conf.d/php-memory-limits.ini</pre>
</details>
<details>
<summary>nginx -v</summary>
<pre>nginx version: nginx/1.21.5</pre>
</details>
<details>
<summary>curl --version</summary>
<pre>curl 7.64.1 (x86_64-apple-darwin20.0) libcurl/7.64.1 (SecureTransport) LibreSSL/2.8.3 zlib/1.2.11 nghttp2/1.41.0
Release-Date: 2019-03-27
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS GSS-API HTTP2 HTTPS-proxy IPv6 Kerberos Largefile libz MultiSSL NTLM NTLM_WB SPNEGO SSL UnixSockets</pre>
</details>
<details>
<summary>php --ri curl</summary>
<pre>curl

cURL support => enabled
cURL Information => 7.82.0
Age => 9
Features
AsynchDNS => Yes
CharConv => No
Debug => No
GSS-Negotiate => No
IDN => Yes
IPv6 => Yes
krb4 => No
Largefile => Yes
libz => Yes
NTLM => Yes
NTLMWB => Yes
SPNEGO => Yes
SSL => Yes
SSPI => No
TLS-SRP => Yes
HTTP2 => Yes
GSSAPI => Yes
KERBEROS5 => Yes
UNIX_SOCKETS => Yes
PSL => No
Protocols => dict, file, ftp, ftps, gopher, gophers, http, https, imap, imaps, ldap, ldaps, mqtt, pop3, pop3s, rtmp, rtsp, scp, sftp, smb, smbs, smtp, smtps, telnet, tftp
Host => x86_64-apple-darwin20.6.0
SSL Version => (SecureTransport) OpenSSL/1.1.1m
ZLib Version => 1.2.11
libSSH Version => libssh2/1.10.0</pre>
</details>
<details>
<summary>~/.composer/vendor/laravel/valet/bin/ngrok version</summary>
<pre>ngrok version 2.3.40</pre>
</details>
<details>
<summary>~/.composer/vendor/laravel/valet/bin/ngrok-arm version</summary>
<pre>sudo: unable to execute /Users/eOssa/.composer/vendor/laravel/valet/bin/ngrok-arm: Bad CPU type in executable</pre>
</details>
<details>
<summary>ls -al ~/.ngrok2</summary>
<pre>ls: /Users/eOssa/.ngrok2: No such file or directory</pre>
</details>
<details>
<summary>brew info nginx</summary>
<pre>nginx: stable 1.21.6 (bottled), HEAD
HTTP(S) server and reverse proxy, and IMAP/POP3 proxy server
https://nginx.org/
/usr/local/Cellar/nginx/1.21.5 (26 files, 2.2MB) *
  Poured from bottle on 2022-01-07 at 11:27:17
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/nginx.rb
License: BSD-2-Clause
==> Dependencies
Required: openssl@1.1, pcre2
==> Options
--HEAD
	Install HEAD version
==> Caveats
Docroot is: /usr/local/var/www

The default port has been set in /usr/local/etc/nginx/nginx.conf to 8080 so that
nginx can run without sudo.

nginx will load all files in /usr/local/etc/nginx/servers/.

To restart nginx after an upgrade:
  brew services restart nginx
Or, if you don't want/need a background service you can just run:
  /usr/local/opt/nginx/bin/nginx -g daemon off;
==> Analytics
install: 40,748 (30 days), 124,009 (90 days), 491,295 (365 days)
install-on-request: 40,669 (30 days), 123,805 (90 days), 490,272 (365 days)
build-error: 13 (30 days)</pre>
</details>
<details>
<summary>brew info php</summary>
<pre>php: stable 8.1.4 (bottled), HEAD
General-purpose scripting language
https://www.php.net/
/usr/local/Cellar/php/8.1.1 (509 files, 80.0MB)
  Built from source
/usr/local/Cellar/php/8.1.3_1 (513 files, 80MB)
  Poured from bottle on 2022-03-14 at 17:24:39
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/php.rb
License: PHP-3.01
==> Dependencies
Build: httpd, pkg-config
Required: apr, apr-util, argon2, aspell, autoconf, curl, freetds, gd, gettext, gmp, icu4c, krb5, libpq, libsodium, libzip, oniguruma, openldap, openssl@1.1, pcre2, sqlite, tidy-html5, unixodbc
==> Options
--HEAD
	Install HEAD version
==> Caveats
To enable PHP in Apache add the following to httpd.conf and restart Apache:
    LoadModule php_module /usr/local/opt/php/lib/httpd/modules/libphp.so

    <FilesMatch \.php$>
        SetHandler application/x-httpd-php
    </FilesMatch>

Finally, check DirectoryIndex includes index.php
    DirectoryIndex index.php index.html

The php.ini and php-fpm.ini file can be found in:
    /usr/local/etc/php/8.1/

To restart php after an upgrade:
  brew services restart php
Or, if you don't want/need a background service you can just run:
  /usr/local/opt/php/sbin/php-fpm --nodaemonize
==> Analytics
install: 139,735 (30 days), 377,272 (90 days), 976,591 (365 days)
install-on-request: 117,825 (30 days), 312,210 (90 days), 854,377 (365 days)
build-error: 56 (30 days)</pre>
</details>
<details>
<summary>brew info openssl</summary>
<pre>openssl@3: stable 3.0.2 (bottled) [keg-only]
Cryptography and SSL/TLS Toolkit
https://openssl.org/
Not installed
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/openssl@3.rb
License: Apache-2.0
==> Dependencies
Required: ca-certificates
==> Caveats
A CA file has been bootstrapped using certificates from the system
keychain. To add additional certificates, place .pem files in
  /usr/local/etc/openssl@3/certs

and run
  /usr/local/opt/openssl@3/bin/c_rehash

openssl@3 is keg-only, which means it was not symlinked into /usr/local,
because macOS provides LibreSSL.

==> Analytics
install: 157,747 (30 days), 367,278 (90 days), 683,523 (365 days)
install-on-request: 125,243 (30 days), 286,494 (90 days), 536,725 (365 days)
build-error: 5,575 (30 days)</pre>
</details>
<details>
<summary>openssl version -a</summary>
<pre>LibreSSL 2.8.3
built on: date not available
platform: information not available
options:  bn(64,64) rc4(16x,int) des(idx,cisc,16,int) blowfish(idx) 
compiler: information not available
OPENSSLDIR: "/private/etc/ssl"</pre>
</details>
<details>
<summary>openssl ciphers</summary>
<pre>ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-CHACHA20-POLY1305:GOST2012256-GOST89-GOST89:DHE-RSA-CAMELLIA256-SHA256:DHE-RSA-CAMELLIA256-SHA:GOST2001-GOST89-GOST89:AES256-GCM-SHA384:AES256-SHA256:AES256-SHA:CAMELLIA256-SHA256:CAMELLIA256-SHA:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-CAMELLIA128-SHA256:DHE-RSA-CAMELLIA128-SHA:AES128-GCM-SHA256:AES128-SHA256:AES128-SHA:CAMELLIA128-SHA256:CAMELLIA128-SHA:ECDHE-RSA-RC4-SHA:ECDHE-ECDSA-RC4-SHA:RC4-SHA:RC4-MD5:ECDHE-RSA-DES-CBC3-SHA:ECDHE-ECDSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:DES-CBC3-SHA</pre>
</details>
<details>
<summary>sudo nginx -t</summary>
<pre>nginx: the configuration file /usr/local/etc/nginx/nginx.conf syntax is ok
nginx: configuration file /usr/local/etc/nginx/nginx.conf test is successful</pre>
</details>
<details>
<summary>which -a php-fpm</summary>
<pre>/usr/sbin/php-fpm</pre>
</details>
<details>
<summary>/usr/local/opt/php/sbin/php-fpm -v</summary>
<pre>PHP 8.1.3 (fpm-fcgi) (built: Mar  1 2022 10:23:34)
Copyright (c) The PHP Group
Zend Engine v4.1.3, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.3, Copyright (c), by Zend Technologies</pre>
</details>
<details>
<summary>sudo /usr/local/opt/php/sbin/php-fpm -y /usr/local/etc/php/7.0/php-fpm.conf --test</summary>
<pre>[05-Apr-2022 14:00:45] NOTICE: configuration file /usr/local/etc/php/7.0/php-fpm.conf test is successful</pre>
</details>
<details>
<summary>ls -al ~/Library/LaunchAgents | grep homebrew</summary>
<pre>-rw-r--r--   1 eOssa  staff   733 Nov  2 14:56 homebrew.mxcl.beanstalkd.plist
-rw-r--r--   1 eOssa  staff   781 Jan 13 18:36 homebrew.mxcl.elasticsearch-full.plist
-rw-r--r--   1 eOssa  staff   388 Jan 14 05:05 homebrew.mxcl.kibana-full.plist
-rw-r--r--   1 eOssa  staff   581 Feb  9  2021 homebrew.mxcl.mailhog.plist
-rw-r--r--   1 eOssa  staff   542 Jan 11 15:33 homebrew.mxcl.memcached.plist
-rw-r--r--   1 eOssa  staff   969 Apr 13  2020 homebrew.mxcl.mongodb-community.plist
-rw-r--r--   1 eOssa  staff   523 Mar 27 19:24 homebrew.mxcl.supervisor.plist</pre>
</details>
<details>
<summary>ls -al /Library/LaunchAgents | grep homebrew</summary>
<pre></pre>
</details>
<details>
<summary>ls -al /Library/LaunchDaemons | grep homebrew</summary>
<pre>-rw-r--r--   1 root  admin   593 Apr  5 13:50 homebrew.mxcl.dnsmasq.plist
-rw-r--r--   1 root  admin   484 Apr  5 13:54 homebrew.mxcl.nginx.plist
-rw-r--r--   1 root  admin   585 Apr  5 13:52 homebrew.mxcl.php@7.0.plist
-rw-r--r--   1 root  admin   585 Apr  5 13:54 homebrew.mxcl.php@7.1.plist</pre>
</details>
<details>
<summary>ls -al /Library/LaunchDaemons | grep "com.laravel.valet."</summary>
<pre></pre>
</details>
<details>
<summary>ls -aln /etc/resolv.conf</summary>
<pre>lrwxr-xr-x  1 0  0  22 Jan  1  2020 /etc/resolv.conf -> ../var/run/resolv.conf</pre>
</details>
<details>
<summary>cat /etc/resolv.conf</summary>
<pre>#
# macOS Notice
#
# This file is not consulted for DNS hostname resolution, address
# resolution, or the DNS query routing mechanism used by most
# processes on this system.
#
# To view the DNS configuration used by this system, use:
#   scutil --dns
#
# SEE ALSO
#   dns-sd(1), scutil(8)
#
# This file is automatically generated.
#
nameserver 190.157.8.100
nameserver 190.157.8.108</pre>
</details>
<details>
<summary>ifconfig lo0</summary>
<pre>lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> mtu 16384
	options=1203<RXCSUM,TXCSUM,TXSTATUS,SW_TIMESTAMP>
	inet 127.0.0.1 netmask 0xff000000 
	inet6 ::1 prefixlen 128 
	inet6 fe80::1%lo0 prefixlen 64 scopeid 0x1 
	inet 127.94.0.1 netmask 0xff000000 
	nd6 options=201<PERFORMNUD,DAD></pre>
</details>
<details>
<summary>sh -c 'echo "------\n/usr/local/etc/nginx/valet/valet.conf\n---\n"; cat /usr/local/etc/nginx/valet/valet.conf | grep -n "# valet loopback"; echo "\n------\n"'</summary>
<pre>------
/usr/local/etc/nginx/valet/valet.conf
---

3:    #listen VALET_LOOPBACK:80; # valet loopback

------</pre>
</details>
<details>
<summary>sh -c 'for file in ~/.config/valet/dnsmasq.d/*; do echo "------\n~/.config/valet/dnsmasq.d/$(basename $file)\n---\n"; cat $file; echo "\n------\n"; done'</summary>
<pre>------
~/.config/valet/dnsmasq.d/tld-test.conf
---

address=/.test/127.0.0.1
listen-address=127.0.0.1

------</pre>
</details>
<details>
<summary>sh -c 'for file in ~/.config/valet/nginx/*; do echo "------\n~/.config/valet/nginx/$(basename $file)\n---\n"; cat $file | grep -n "# valet loopback"; echo "\n------\n"; done'</summary>
<pre>------
~/.config/valet/nginx/doe.localhost.test
---

5:    #listen VALET_LOOPBACK:80; # valet loopback

------

------
~/.config/valet/nginx/wasi.local.test
---

3:    #listen 127.0.0.1:80; # valet loopback
10:    #listen 127.0.0.1:443 ssl http2; # valet loopback
54:    #listen 127.0.0.1:60; # valet loopback

------

------
~/.config/valet/nginx/wasi.localhost.test
---

3:    #listen 127.0.0.1:80; # valet loopback
10:    #listen 127.0.0.1:443 ssl http2; # valet loopback
54:    #listen 127.0.0.1:60; # valet loopback

------</pre>
</details>

**Comment by driesvints** [comment]
Ping @NasirNobin

**Comment by NasirNobin** [comment]
If I'm not mistaken, this is common behavior across all valet commands. Like if you run this: 

```bash
valet secure doe.localhost
```

Valet won't secure `doe.localhost`, it would instead secure `doe.localhost.test` domain.

**Comment by NasirNobin** [comment]
@eossa do you know if there's any way to secure `doe.localhost` domain using Valet? 

Personally, I haven't used `.localhost` TLD for linking to Valet sites before. I'm a bit surprised it works in this way!

**Comment by NasirNobin** [comment]
![CleanShot 2022-04-06 at 22 44 22](https://user-images.githubusercontent.com/13833460/162025639-26384705-b720-4c88-a747-afdf8a004b9d.png)

For me, the HTTPS doesn't seem to work properly as expected. 


Either way, I think this https://github.com/laravel/valet/pull/1088 PR is addressing this problem for `valet secure` command. If that one gets merged, I'll try to open another PR to do the same for `valet isolate` command.

**Comment by mattstauffer** [comment]
@NasirNobin I'm a little bit scared to add a lot of code supporting the undocumented and Officially Unsupported feature of using `link` to point to domains that don't use the `.test` (or whatever else is defined) TLD.

However.. if we can modify the isolate command as simply as we modified `secure` in #1088, I'm up for it.

**Comment by driesvints** [comment]
We've recently decided to not support tld's other than the default anymore so I'm going to close this. We strongly recommend to stay on using `.test`.
