### ISSUE TITLE
Allow multiple subdomains

### ISSUE THREAD

**Issue by jdavidbakr** [laravel/valet#124]
I have a site that does routing based on the subdomain, so in order to serve this in valet I have to make the following change to server.php:

```
if (strpos($siteName, 'www.') === 0) {
    $siteName = substr($siteName, 4);
}
```

to

```
if (strstr($siteName, '.')) {
    $siteName = substr($siteName, strpos($siteName, '.') + 1);
}
```

It would be awesome if this were either the default or configurable.

**Comment by xt9** [comment]
This would save me some headache as well. We're also using subdomain groups.

**Comment by mattstauffer** [comment]
You can manually add a subdomain, if you'd like:

```bash
cd Sites/mergency
valet link burger.mergency
valet link coffee.mergency
valet link tea.mergency
```

Since I've run `valet park` on the `Sites` directory, this directory is now serving all of the following URLs:

- mergency.dev
- burger.mergency.dev
- coffee.mergency.dev
- tea.mergency.dev

**Comment by jdavidbakr** [comment]
@mattstauffer - yeah, but in my case, I am using the subdomains as a user-level identifier, so ideally I'd like to be able to add subdomains while playing with it that are not necessarily persistent and that I don't have to go in and create the link every time I need a new one.  The solution of changing the server.php setup is working great, but it would be nice to have this configurable somehow so it doesn't get overwritten if I pull an update to valet.

**Comment by mattstauffer** [comment]
@jdavidbakr :+1: Thought you might say that, but wanted to expose this option in here in case it solved your or others' problems.

**Comment by xt9** [comment]
@mattstauffer I've tried that before with little luck, but this time around it worked. Thanks :) I rarely use more than 2 subdomains, but adding some kind of wildcard support could be nice.

**Comment by neronmoon** [comment]
👍  to allow wildcards

**Comment by antonioribeiro** [comment]
Just sent a PR to allow dynamic subdomains: https://github.com/laravel/valet/pull/267.

**Comment by MehmetNuri** [comment]
How i can route subdomains dynamic?

**Comment by adamwathan** [comment]
@MehmetNuri, it should just work, don't need to configure anything. If you have a site available at `my-app.dev`, `foo.my-app.dev` will already route to that project automatically.

**Comment by MehmetNuri** [comment]
if you want support multi domain use this code 
```shell
ln -s ~/Projects/directory  ~/.valet/Sites/domain_name
```

And change route file
```php
Route::group(['domain' => 'laravel.app'], function()
{
    Route::get('/', function () {
        return "Main Domain";
    });

});


Route::group(['domain' => 'other.app'], function()
{
    Route::get('/', function () {
        return "Other Domain";
    });


});
```

In this project, project name is **laravel** , main domain is **laravel.app** and other domain is **other.app**
