### ISSUE TITLE
Command valet phplcomposerlwhich-php not working anymore globally

### ISSUE THREAD

**Issue by JacobDelcroix** [laravel/valet#1241]
### Discussed in https://github.com/laravel/valet/discussions/1240

<div type='discussions-op-text'>

<sup>Originally posted by **JacobDelcroix** April 16, 2022</sup>
Laravel Valet 3.1.3

Hello,

I think a new bug has been introduced recently (maybe 3.1.2) with these commands:
- valet php
- valet composer
- valet which-php

**valet php command log**
```
➜ ~ valet php -v
/Users/jacob/.composer/vendor/laravel/valet/valet: line 88: Deprecated:: command not found
```

**valet which-php command log**
```
➜ ~ valet which-php

Deprecated: preg_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /Users/jacob/.composer/vendor/laravel/valet/cli/Valet/PhpFpm.php on line 327

Deprecated: preg_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /Users/jacob/.composer/vendor/laravel/valet/cli/Valet/PhpFpm.php on line 327

Deprecated: preg_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /Users/jacob/.composer/vendor/laravel/valet/cli/Valet/PhpFpm.php on line 327
/opt/homebrew/bin/php
```

This bug appear when using these commands outside of a project (it should use default php version just like before).. all is working fine when you use these inside a project.
</div>

**Comment by NasirNobin** [comment]
I can reproduce this. Most probably introduced in this [release](https://github.com/laravel/valet/releases/tag/v3.1.2). I'll try to debug and submit a quick fix soon.
