### ISSUE TITLE
Valet isolate not worked

### ISSUE THREAD

**Issue by o2b3k** [laravel/valet#1243]
When I try command valet isolate php@7.4 returned  Command "isolate" is not defined.  

- Valet Version: Laravel Valet 2.18.10
- PHP Version: 8.1 and 7.4
- MacOs Monterey

**Comment by NasirNobin** [comment]
Valet Isolation requires Valet 3.0+ 

You can upgrade by running following command: 

```shell
composer global require laravel/valet:"^3.0"

valet install
```

**Comment by driesvints** [comment]
Thanks @NasirNobin
