### ISSUE TITLE
Laravel Valet hanging after upgrade

### ISSUE THREAD

**Issue by tillkruss** [laravel/valet#1245]
Just upgraded from 2.x to 3.x and when running `valet install` afterwards it just hangs:

```
> valet install
Stopping nginx...
Installing nginx configuration...
Installing nginx directory...

> valet install -vvv                                                                                                                                                                 
Stopping nginx...
Installing nginx configuration...
Installing nginx directory...
```

**Comment by NasirNobin** [comment]
Duplicate of https://github.com/laravel/valet/issues/1224. This usually gets fixed after a reboot. 

Please try rebooting the device and run `valet install` again.

**Comment by driesvints** [comment]
@tillkruss't please remember the issue template so we know which versions you're working with.

**Comment by driesvints** [comment]
We're btw still debugging that issue as it's not always solved after a reboot. I'm still experiencing it.

**Comment by driesvints** [comment]
Also see https://github.com/laravel/valet/issues/1226
