### ISSUE TITLE
Error after each reastart

### ISSUE THREAD

**Issue by Julian367** [laravel/valet#1249]
- Valet Version: 3.1.6
- PHP Version: 8.1.4
- MacOs Monterey 12.3.1

### Description:
After each laptop restart this error show on laravel projects.

Fatal error: Uncaught TypeError: Return value of Illuminate\Container\Container::offsetGet() must be an instance of Illuminate\Container\mixed, instance of Illuminate\Events\Dispatcher returned

### Steps To Reproduce:
If I run ```valet install``` the problem is fixed until next restart

**Comment by driesvints** [comment]
> Fatal error: Uncaught TypeError: Return value of Illuminate\Container\Container::offsetGet() must be an instance of Illuminate\Container\mixed

Most likely, you're running a PHP version that does not support the `mixed` return type.
