### ISSUE TITLE
Valet and large file uploads

### ISSUE THREAD

**Issue by tommytompkins** [laravel/valet#125]
Hey guys - 

Today I installed Valet with the hopes of replacing Homestead.  I'm running Laravel 5.2 with dropzone.js (dropzonejs.com) to upload files.  I don't have any issues in Homestead, but in Valet I start getting weird errors if I try to upload any file that's over 2.2 MB.  Sometimes the validation in my controller is triggered and complains that the named file is required:

```
{my-photo: ["The my-photo field is required."]}
```

And sometimes I'll get weird memory errors like this:

```
FatalErrorException: Allowed memory size of 134217728 bytes exhausted (tried to allocate 48000001 bytes)
```

Notice that in the above error, it's complaining that it's trying to allocate 48 MB but my memory limit is set to 128 MB so this shouldn't be an issue.  

Any ideas of how I can get around this?

Thanks!

Tommy

**Comment by tommytompkins** [comment]
Well this was an idiot thing on my part. I was only looking at the memory_limit in php.ini but I completely forgot to look at post_max_size and upload_max_filesize. After setting both of those to 20M, everything is working well again.

However, it still doesn't explain the memory issue that I was getting before.  I still don't understand why I was getting memory issues when my memory_limit is set to 128M and it was complaining that it tried to allocate LESS memory than what the limit is set at.  Hmm..

**Comment by drbyte** [comment]
> I still don't understand why I was getting memory issues when my memory_limit is set to 128M and it was complaining that it tried to allocate LESS memory than what the limit is set at. Hmm.

Pretty sure it means it was trying to allocate an additional 48M more than what was allowed.

**Comment by notflip** [comment]
Where did you change the post_max_size and upload_max_size?

**Comment by drbyte** [comment]
See https://github.com/laravel/valet/pull/277/files

**Comment by emilushi** [comment]
I have change `memory_limit` on both `/usr/local/etc/php/7.3/php.ini` and on `/usr/local/etc/php/7.3/conf.d/php-memory-limits.ini` at set it to 256M and I still see **128M** when I run `phpinfo()`

**Comment by drbyte** [comment]
> I have change `memory_limit` on both `/usr/local/etc/php/7.3/php.ini` and on `/usr/local/etc/php/7.3/conf.d/php-memory-limits.ini` at set it to 256M and I still see **128M** when I run `phpinfo()`

You have to restart nginx/phpfpm for it to take effect. `valet restart` or a reboot will do that for you.

**Comment by emilushi** [comment]
> > I have change `memory_limit` on both `/usr/local/etc/php/7.3/php.ini` and on `/usr/local/etc/php/7.3/conf.d/php-memory-limits.ini` at set it to 256M and I still see **128M** when I run `phpinfo()`
> 
> You have to restart nginx/phpfpm for it to take effect. `valet restart` or a reboot will do that for you.

:) of course I restarted valet

**Comment by drbyte** [comment]
@emilushi You've posted in a closed issue for a matter that has resolved things well for others. So let's not muddy it with your unique case, particularly since you haven't given any context and therefore it looks like lots of dialog is going to be necessary.
**Please open a separate issue for your specific situation.** In it, provide your problem statement, as well as the output from all of the following:

```sh
sw_vers
valet --version
cat ~/.config/valet/config.json
ls -al /etc/sudoers.d/
openssl version -a
openssl ciphers
php -v
which php
which -a php
nginx -v
brew config
brew doctor
brew info openssl
brew info nginx
brew info php
sudo nginx -t
php -i
```
And, since you specifically mentioned `phpinfo()` (which can differ from `php -i`), please post that output as well.
