### ISSUE TITLE
"Conn.Write wrote more than the declared Content-Length"

### ISSUE THREAD

**Issue by simplenotezy** [laravel/valet#129]
I am seeing the following in my valet error log constantly:

```
29/Aug/2016:19:55:54 +0200 [ERROR 502 /server.php] Conn.Write wrote more than the declared Content-Length
```

Am I to be worried?

**Comment by simplenotezy** [comment]
Bump

**Comment by adamwathan** [comment]
Not sure, haven't seen this myself. What versions of Valet and Caddy are you running? Future versions of Valet are likely going to switch to nginx so this problem will probably just vanish anyways.
