### ISSUE TITLE
test in site name fails

### ISSUE THREAD

**Issue by ErikDohmen** [laravel/valet#1295]
### Description:
In line with our regular site setup we have the same locally with valet:
portal.test-work.test
welcome.test-work.test
The moment it goes wrong is when I try to use the isolate option. Then I get the error that portal-work isn't found as site name. That is correct as it is indeed portal.test-work. The probleem seems to be that .test is removed not just at the end, but just as it is found in the site name.

### Steps To Reproduce:
1. add a link to your project with a specific site name in line with ours e.g. portal.test-work
2. try to isolate the site with any php version
3. you should get the error that the site name isn't found in the list of sites

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!

**Comment by driesvints** [comment]
Also next time please provide the info requested in the issue template.

**Comment by ErikDohmen** [comment]
Hi Dries,

Thanks for the input. I've actually searched for solutions to the issue but couldn't find one. 
In the mean time created one myself which I will add as a pull request if that is okay by you.

**Comment by ErikDohmen** [comment]
@driesvints I've added a pull request with a solution for the problem:
https://github.com/laravel/valet/pull/1297
