### ISSUE TITLE
test in site name fails with isolation

### ISSUE THREAD

**Issue by ErikDohmen** [laravel/valet#1298]
### Description:
In line with our regular site setup we have the same locally with valet:
portal.test-work.test
welcome.test-work.test
The moment it goes wrong is when I try to use the isolate option. Then I get the error that portal-work isn't found as site name. That is correct as it is indeed portal.test-work. The probleem seems to be that .test is removed not just at the end, but just as it is found in the site name.
searches on internet doesn't bring any solutions to the table

### Steps To Reproduce:
add a link to your project with a specific site name in line with ours e.g. portal.test-work
try to isolate the site with any php version
you should get the error that the site name isn't found in the list of sites

### Diagnosis

[valet-diagnose.txt](https://github.com/laravel/valet/files/9927983/valet-diagnose.txt)

**Comment by ErikDohmen** [comment]
I've added a pull request (https://github.com/laravel/valet/pull/1297) with a solution for the problem

**Comment by driesvints** [comment]
Thanks. Let's see how the PR goes 👍

**Comment by ErikDohmen** [comment]
@driesvints, any ideas when the PR is going to be tested and (dis)approved?

**Comment by driesvints** [comment]
Whenever @mattstauffer finds some time.
