### ISSUE TITLE
Strange encoding issues

### ISSUE THREAD

**Issue by simplenotezy** [laravel/valet#130]
After upgrading to Laravel Valet I now have strange encoding issues on my application. This didn't happen when running homestead.

Example:

![image](https://cloud.githubusercontent.com/assets/3786627/18061904/d8e78896-6e24-11e6-83d2-53e2ea2726eb.png)

**Comment by simplenotezy** [comment]
We have just installed it on a new El Capitan, and the encoding issues persists. What is going on? Hmmm

**Comment by rasmuswoelk** [comment]
I am also having this issue. Any suggestions?

**Comment by adamwathan** [comment]
Can you show me the text that's causing the problem so I can try and reproduce locally? Is it a problem if you include the text in a view by hand, or only if coming from the database?

**Comment by simplenotezy** [comment]
Hi @adamwathan 

This is indeed very strange. It only happens from the database. I think this has something to do with MariaDB since we just switched to that with Laravel Valet.

    exit('Wølk'); // ouputs "Wølk" (awesome name)
    exit(User::find(2)->lastname // outputs "W��lk"

In my database:

![image](https://cloud.githubusercontent.com/assets/3786627/18130241/83fbede8-6f8e-11e6-96bf-aa6d6bf621a5.png)

Create table syntax:

	CREATE TABLE `users` (
	  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
	  `firstname` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
	  `lastname` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
	  `email` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL
	)

**Comment by simplenotezy** [comment]
FYI: We use `doctrine/dbal` don't know if this could interfere in anyway.

This is from `database.php`:

	'charset'   => 'utf8',
	'collation' => 'utf8_unicode_ci',

**Comment by adamwathan** [comment]
What does the data look like in the database? Can you try switching to SQLite just to try and isolate the MariaDB issue? It's a real pain in the ass to install MySQL and MariaDB on the same machine, haha... I will try at some point today though.

**Comment by adamwathan** [comment]
Working for me with MariaDB the same as it did with MySQL 🤔

Is there any way you can create a sample project that demonstrates the issue, including maybe a seeder or something that when run is causing this problem?

**Comment by simplenotezy** [comment]
Interesting. Inside my table it looks perfect as well.

I'm afraid something else in my application could be causing this. it has been upgraded from laravel 4.2 all the way to l 5.1

**Comment by adamwathan** [comment]
Here's a demo project that works for me, just clone, create a database, migrate and seed, then hit `/` and `/json` to check output:

https://github.com/adamwathan/valet-encoding-test

**Comment by simplenotezy** [comment]
Downloading your project works. Using the same database on my old application does not.

Current ideas for why this could be happening:

1) Your project is `5.3.*`, mine is `5.2.*`. Could there be any issue in this?
2) My project initially started being 4.2, and has since then been upgraded to Laravel 5.2. Could this have anything to do with the issue?

I have narrowed this down to something in my application. If you have any suggestions where I could start debugging I'd be grateful. I am lost at the moment. I LOVE MY JOB! <3

**Comment by simplenotezy** [comment]
Here's the mother f*cker:



	/**
	 * Get the user's last name.
	 *
	 * @param  string  $value
	 * @return string
	 */

		public function getLastnameAttribute($value) {
			return UCWORDS(STRTOLOWER($value));
		}

**Comment by adamwathan** [comment]
Glad you found the issue!
