### ISSUE TITLE
Valet uses php version of isolated domain, while subdomain has to run on the default PHP version

### ISSUE THREAD

**Issue by nijholt** [laravel/valet#1308]
### Description:
Currently I'm facing a bug where a sub domain uses the php version of the top domain which is isolated.
The sub domain should run on the non isolated version of php

### Steps To Reproduce:
- `cd ~/Sites`
- Run `valet park` in the `Sites` folder
- Create a project called `domain` that is isolated in PHP 7.4
   - `composer create-project laravel/laravel domain`
   - `cd domain && valet isolate 7.4 && cd ..`
- Create a project called `subdomain` that is running PHP 8.1 (default)
   - `composer create-project laravel/laravel subdomain`
   - Make sure `subdomain.test` works
- Link "subdomain" as a sub domain:
  - `cd subdomain && valet link sub.domain && cd ..`
 - Open your browser and browse to `http://sub.domain.test`
 
 Now you'll see an error:
 ```
 Fatal error: Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.1.0". You are running 7.4.33. in /Users/user/Sites/subdomain/vendor/composer/platform_check.php on line 24
 ```

**Comment by driesvints** [comment]
You'll need to isolate each subdomain separately.

**Comment by nijholt** [comment]
@driesvints browsing to the subdomain and running `valet isolate php@8.1` doesn't do the job.

When going to `http://sub.domain.test` throws the same fatal error

**Comment by driesvints** [comment]
I linked a site through Valet, linked the subdomain, isolated to 8.0 and it all works fine for me. I indeed didn't need to isolate separately:

<img width="1644" alt="Screenshot 2022-11-30 at 14 11 44" src="https://user-images.githubusercontent.com/594614/204805235-bd6e04d7-a519-425e-945e-836e5d5c4e14.png">

Please use a support channel if you need further help:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

**Comment by nijholt** [comment]
Ok I fixed it with this command, but it's not clear in the documentation

```
valet isolate --site sub.domain -- php
```

**Comment by mattstauffer** [comment]
I read through this issue and made sure the current docs support it, and they seem to:

<img width="855" alt="image" src="https://user-images.githubusercontent.com/151829/209566378-5cdcf943-dc3b-4a07-be7a-dfd8f62ffe91.png">

So I feel good the documentation is clear now, even if it wasn't at the time of this issue. Thanks all!
