### ISSUE TITLE
When serving a site from`/public`, Valet will also serve matching files from the project root, and shouldn't

### ISSUE THREAD

**Issue by mattstauffer** [laravel/valet#1309]
In reviewing https://github.com/laravel/valet/pull/1303 I realized that Valet's `BasicValetDriver` has a behavior I'd like to end:

If your site structure looks like this:

```
├── public
│   ├── index.php
│   └── file-in-public.php
├── file-in-root.php
```

You can visit both `file-in-*` files publicly:

`mysite.test/public/file-in-public.php`
and
`mysite.test/file-in-root.php`

However, I would expect instead:

`mysite.test/file-in-public.php`

And that the `file-in-root.php` wouldn't serve at all.

I know this is a breaking change, but it feels like a helpful correction to a more reasonable behavior.

**Comment by driesvints** [comment]
@mattstauffer wait, isn't this normal? You're serving from the root so all files are accessible? Why isn't valet serving from public?

**Comment by mattstauffer** [comment]
@driesvints I'm not fully sure what you're asking. Let me state it different way, maybe?

What is *normal* for me would be:

If Valet is serving from `public/` then all files in the root should be totally un-serve-able; the *only* way Valet should ever serve files from the root is if that project doesn't have a `public/` directory.

But that's not the case right now.

**Comment by driesvints** [comment]
Agreed, was just assuming you said it served from the root.

**Comment by mattstauffer** [comment]
OK, sounds good! :)

**Comment by mattstauffer** [comment]
Closing since it's fixed in a to-be-released version.
