### ISSUE TITLE
Upgrade to 3.2.0 - missing UsesNullWriter.php

### ISSUE THREAD

**Issue by davideprevosto** [laravel/valet#1312]
I upgraded to 3.2.0 and I am getting the following warning running `valet start`:

`Warning: require(/Users/MY_USER/.composer/vendor/composer/../laravel/valet/tests/UsesNullWriter.php): Failed to open stream: No such file or directory in /Users/MY_USER/.composer/vendor/composer/autoload_real.php on line 55
`

I also run the following commands and restarted my iMac, without luck.

```
composer self-update
composer global update
brew upgrade
```

**Comment by worzy** [comment]
Thanks @mattstauffer, this stumped me today as well.  For anyone needing the command/version to bump down that works.

`composer global require laravel/valet:3.1.13`

**Comment by sprklinginfo** [comment]
OMG, thanks @worzy you saved me as I am stuck with this fatal error after the upgrade. will wait for the fix...

**Comment by kovspace** [comment]
composer.json autoload files:

"tests/UsesNullWriter.php",
"tests/BaseApplicationTestCase.php",
"tests/Drivers/BaseDriverTestCase.php"

it should be removed

**Comment by worzy** [comment]
> OMG, thanks @worzy you saved me as I am stuck with this fatal error after the upgrade. will wait for the fix...

You're welcome @sprklinginfo

**Comment by jools-r** [comment]
Yes, none of the following test files in the autoloader are present: 

```
"tests/UsesNullWriter.php",
"tests/BaseApplicationTestCase.php",
"tests/Drivers/BaseDriverTestCase.php"
```

Manually removing the following three lines from `/.composer/vendor/composer/autoload_files.php` and `/.composer/vendor/composer/autoload_static.php`:

```
    'baf4d662c353847c5ac6d87ab0f85328' => $vendorDir . '/laravel/valet/tests/UsesNullWriter.php',
    '132602d03dfc7ed2fb6aec8987432980' => $vendorDir . '/laravel/valet/tests/BaseApplicationTestCase.php',
    'fbc556b75f2e7365d66ad808000fa955' => $vendorDir . '/laravel/valet/tests/Drivers/BaseDriverTestCase.php',
```

allows you to run `valet install` and `valet --version` then returns v3.2.0.

**Comment by mattstauffer** [comment]
This should be fixed on `master`, I think; just needs @driesvints to tag a release whenever he's ready. :)

**Comment by mattstauffer** [comment]
Actually, this should be fixed in https://github.com/laravel/valet/releases/tag/v3.2.1.

Please test it out and close if fixed. Thanks!

**Comment by davideprevosto** [comment]
@mattstauffer it seems to me that you have solved the problem!
Thank you
