### ISSUE TITLE
Allow users to set PHP memory limit

### ISSUE THREAD

**Issue by michaellehmkuhl** [laravel/valet#1313]
### Description:

Commands like `valet use` and `valet install` cause `/*/local/etc/php/*/conf.d/php-memory-limits.ini` to be overwritten, even if it already exists. Since this config file is loaded after `php.ini`, the directives override what users may have set in their `php.ini` files. In particular, this is a problem when running an application that requires a large amount of memory (e.g., Magento), and can especially be an issue in a CLI environment, where longer running commands might be run.

As a workaround, I've taken to creating a file like `/*/local/etc/php/*/conf.d/zzz-final-config.ini` to ensure I can overwrite config settings as needed. This works for now, but it would be better if Valet didn't unexpectedly overwrite config settings that I've changed manually. At the very least, it would be good to see a warning if Valet is changing config files underneath me.

Additionally, it would be nice to have a way to configure separate settings for CLI and FPM. I realize this part may be more on the package managers for the Homebrew PHP packages, though.

### Steps To Reproduce:

1. Edit one of the `/*/local/etc/php/*/conf.d/php-memory-limits.ini` files.
2. Run `valet install` or `valet use`.
3. See that changes have been overwritten and the `php-memory-limits.ini` file is back to the default contents.

### Diagnosis
N/A

**Comment by driesvints** [comment]
Heya, thanks for submitting this.

This seems like a feature request or an improvement so I'm converting this to a discussion instead. It's best to post these in the discussions section in the future to get support for your idea. After that you may send a PR to the framework. Please only use the `laravel/framework` issue tracker to report bugs and issues with the framework.

Thanks!
