### ISSUE TITLE
Valet 3.2.0 breaks custom drivers that extend built-in drivers

### ISSUE THREAD

**Issue by markjaquith** [laravel/valet#1314]
In Valet 3.1.x, you could do this:

```php
class LocalValetDriver extends LaravelValetDriver {
```

or

```php
class LocalValetDriver extends WordPressValetDriver {
```

and this is what was recommended [in the documentation](https://laravel.com/docs/9.x/valet#local-drivers).

As of Valet 3.2.0 (and 3.2.1 does not fix this), this does not work.

> **Fatal error:** Uncaught Error: Class "WordPressValetDriver" not found in /Path/To/Site/LocalValetDriver.php

However, if you reference the full namespace `\Valet\Drivers\LaravelValetDriver` or `\Valet\Drivers\WordPressValetDriver`, it will work again.

I can update my custom drivers, but it really seems like this was an unintentional breaking change.

**Comment by markjaquith** [comment]
@mattstauffer made a PR (into the `mes/legacy-drivers` branch) that completes your fix: #1317

**Comment by markjaquith** [comment]
Once this is merged, should the documentation be updated to recommend that the fully-qualified class name be used, so that it's easier to remove this legacy layer in Valet 4.0? Or are there going to be so many other breaking changes that people will have to rewrite their custom drivers anyway?

**Comment by mattstauffer** [comment]
yes, I think we can update the docs now! I doubt there will be other big breaking changes. 🤞🏻

**Comment by mattstauffer** [comment]
This should be fixed here:
https://github.com/laravel/valet/releases/tag/v3.2.2

**Comment by dpslwk** [comment]
I think this may have broken my `valet which` command
as the SampleValetDriver.php stub that's copied during install was not namespaced with the other files in the refactor


```bash
 CryptoDash$ valet which                                                                                                                                                 

Fatal error: Uncaught Error: Class "ValetDriver" not found in /Users/matt/.config/valet/Drivers/SampleValetDriver.php:3
Stack trace:
#0 /Users/matt/.composer/vendor/laravel/valet/cli/Valet/Drivers/ValetDriver.php(134): require_once()
#1 /Users/matt/.composer/vendor/laravel/valet/cli/Valet/Drivers/ValetDriver.php(58): Valet\Drivers\ValetDriver::driversIn('/Users/matt/.co...')
#2 /Users/matt/.composer/vendor/laravel/valet/cli/app.php(280): Valet\Drivers\ValetDriver::assign('/Users/matt/Dro...', 'CryptoDash', '/')
#3 [internal function]: Silly\Application->{closure}(Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /Users/matt/.composer/vendor/php-di/invoker/src/Invoker.php(74): call_user_func_array(Object(Closure), Array)
#5 /Users/matt/.composer/vendor/mnapoli/silly/src/Application.php(96): Invoker\Invoker->call(Object(Closure), Array)
#6 /Users/matt/.composer/vendor/symfony/console/Command/Command.php(310): Silly\Application->Silly\{closure}(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /Users/matt/.composer/vendor/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /Users/matt/.composer/vendor/symfony/console/Application.php(314): Symfony\Component\Console\Application->doRunCommand(Object(Silly\Command\Command), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /Users/matt/.composer/vendor/symfony/console/Application.php(168): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /Users/matt/.composer/vendor/laravel/valet/cli/valet.php(9): Symfony\Component\Console\Application->run()
#11 {main}
  thrown in /Users/matt/.config/valet/Drivers/SampleValetDriver.php on line 3
  ```
  
  adding `namespace Valet\Drivers;` to `.config/valet/Drivers/SampleValetDriver.php` and things work again
