### ISSUE TITLE
Valet has broken after upgrade PHP to 8.2

### ISSUE THREAD

**Issue by xerenahmed** [laravel/valet#1322]
I ran `brew upgrade` and the PHP version became 8.2. After that I ran `valet restart` but it didn't work this time. 

Tried to re-link PHP and install valet again but this didn't work too.
```sh
$ brew unlink php && brew link php
Unlinking /opt/homebrew/Cellar/php/8.2.0... 24 symlinks removed.
Linking /opt/homebrew/Cellar/php/8.2.0... 24 symlinks created.

$ valet install
Stopping nginx...
Installing nginx configuration...
Installing nginx directory...
PHP Deprecated:  Using ${var} in strings is deprecated, use {$var} instead in /Users/eren/.composer/vendor/laravel/valet/cli/Valet/PhpFpm.php on line 153

Deprecated: Using ${var} in strings is deprecated, use {$var} instead in /Users/eren/.composer/vendor/laravel/valet/cli/Valet/PhpFpm.php on line 153
Updating PHP configuration...

In Brew.php line 299:

  Unable to determine linked PHP when parsing '8.2'


install
```

**Comment by driesvints** [comment]
I can run Valet on PHP 8.2 just fine:

<img width="708" alt="Screenshot 2022-12-22 at 09 30 27" src="https://user-images.githubusercontent.com/594614/209091528-f00988fe-aea4-4861-8620-8b47e90c8127.png">

Please try a support channel:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

**Comment by jjsanderson** [comment]
@xerenahmed I had the same problem on two machines, in both cases caused by inadvertently running an old version of Valet (2.18.10, in my case; check `valet --version`). If that's also your issue, try:

> composer global require "laravel/valet:^3.0"
> composer global update
> valet install

...which will bring you up to Valet 3.x. I'm not sure where I found this documented - it wasn't obvious to me that my Valet install was out-of-date.

**Comment by mattstauffer** [comment]
FYI, you can always run `valet on-latest-version` to get a "Yes" or "No" response of whether you're on the latest. You can run this manually or programatically if that helps you keep up to date.

**Comment by driesvints** [comment]
@MohannadNaj yeah that's a good idea. Can you send in a PR?

**Comment by svpernova09** [comment]
> @xerenahmed I had the same problem on two machines, in both cases caused by inadvertently running an old version of Valet (2.18.10, in my case; check `valet --version`). If that's also your issue, try:
> 
> > composer global require "laravel/valet:^3.0"
> > composer global update
> > valet install
> 
> ...which will bring you up to Valet 3.x. I'm not sure where I found this documented - it wasn't obvious to me that my Valet install was out-of-date.

Thanks for this
