### ISSUE TITLE
valet81.sock file not created when switching from php8.0 to php8.1 and running valet install

### ISSUE THREAD

**Issue by tanderson11** [laravel/valet#1333]
### Description:

After using `valet use` to switch my php version from 8.0 to 8.1, my valet server gives a 502 Bad Gateway error. Checking the logs, this is caused by the missing file `/Users/thayer/.config/valet/valet81.sock`. Note: I did run `composer global update` and `valet install`.

### Steps To Reproduce:

Starting from having a functioning website with php 8.0, here are the commands I ran and the error produced:
```
$  ls -al ~/.config/valet
lrwxr-xr-x   1 thayer  staff   40 Jan  3 16:47 valet.sock -> /Users/thayer/.config/valet/valet80.sock
srwxrwxrwx   1 thayer  staff    0 Jan  3 16:47 valet80.sock
srwxrwxrwx   1 thayer  staff    0 Jan  3 16:35 valet82.sock

$ valet use 8.1
...
Valet is now using php@8.1.

$ composer global update
...
Package operations: 0 installs, 8 updates, 0 removals

$ valet install
...
Valet installed successfully!

$ ls -al ~/.config/valet
lrwxr-xr-x   1 thayer  staff   40 Jan  3 16:41 valet.sock -> /Users/thayer/.config/valet/valet81.sock
srwxrwxrwx   1 thayer  staff    0 Jan  3 16:35 valet82.sock
```

And this produces a 502 Bad Gateway. In `nginx-error.log`:
`2023/01/03 16:38:55 [crit] 24544#0: *1 connect() to unix:/Users/thayer/.config/valet/valet.sock failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://unix:/Users/thayer/.config/valet/valet.sock:", host: "sitename.test", referrer: "http://sitename.test/wp-admin/"`

```
$ valet on-latest-version
Yes
```

**Comment by driesvints** [comment]
I can switch between php 8.0 and 8.1 fine. Please try a support channel:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

**Comment by sebastiansulinski** [comment]
I have the same issue with trying to use php 7.4 - perhaps there is the actual issue with isolating sites?
The relevant `*.sock` file for the php version isn't being created.

I uninstalled and then installed latest version of valet, updated composer's global dependencies etc. but keep getting 

```
connect() to unix:/Users/seb/.config/valet/valet74.sock failed (2: No such file or directory) while connecting to upstream ...
```

![01](https://user-images.githubusercontent.com/2211203/227926725-e98a7ab3-8eaf-4280-a397-f9b75ce01347.jpg)
![Screenshot 2023-03-27 at 12 16 17](https://user-images.githubusercontent.com/2211203/227926764-8f8b8726-9fd7-4f33-8267-7883cb3813da.png)

**Comment by edalzell** [comment]
@sebastiansulinski did you get this resolved? I just ran into the same thing on Valet 4.
