### ISSUE TITLE
`valet unlink` doesn't remove the outcome of `secure`

### ISSUE THREAD

**Issue by mattstauffer** [laravel/valet#1362]
Reproduce:

1. `valet link` a directory
2. `valet secure`
3. `valet unlink`

You'll still have all the files for that site in `~/.config/valet/Certificates`, and still have the certificate in your keychain.

**Comment by mattstauffer** [comment]
This seems like a bug to me, but is also sort of breaking change-y... for now I'm just going to fix it in v4.

**Comment by drbyte** [comment]
I'm away from dev machine right now so can't check.  But, question: Does `valet unsecure` do the cleanup properly?

**Comment by mattstauffer** [comment]
Yep!

<img width="505" alt="image" src="https://user-images.githubusercontent.com/151829/217938801-8c141e8a-fcd3-417d-bee8-04eecb8fb818.png">

I also checked and it removes the certificate.

I'm working on a branch to make sure `unlink` also calls `unsecure` internally.

**Comment by mattstauffer** [comment]
(this branch is very easy, but embarrassingly has made the test for the `unlink` command require a lot more complexity... I'll get it eventually)

**Comment by mattstauffer** [comment]
Closed in #1364.
