### ISSUE TITLE
Nginx SSI config apparently broken

### ISSUE THREAD

**Issue by wturrell** [laravel/valet#1368]
### Description:

This is while working on an almost entirely static HTML site, no framework or CMS, where I want to load a common SSI to avoid repeating navigation elements. 

I've been able to work around it by editing the site-specific Nginx config file, changing the root from ``/`` to the actual directory and removing the rewrite line that passes everything to .../vendor/laravel/valet/server.php

### Steps To Reproduce:

- Create a file called ``ssi-navigation.html`` or similar.
- Verify it loads fine when loaded directly in the browser.
- Insert it in the page with ``<!--# include virtual="/ssi-navigation.html"-->``
- When loading your main page, e.g. /index.html, rather than insert the SSI, Nginx will insert the entire index.html, and keep recursively loading it at the position of the SSI include. The page will never load and the Nginx error log will show warnings like:

>  *55 subrequests cycle while processing 

This happens regardless of whether you use `virtual` or `file` in the SSI directive - I thought perhaps the latter would work.

Is this something I can easily fix other than by disabling server.php entirely?  
Having SSI support is very useful, but obviously not necessary for most of the drivers.

(Thanks)

**Comment by mattstauffer** [comment]
I don't know enough about how SSI works to debug this with you, but I definitely remember this PR where we turned SSI on, so I presume it was working for them back then. Can you learn anything from the conversations there?

https://github.com/laravel/valet/pull/517

**Comment by driesvints** [comment]
Closing this issue because it's inactive, already solved, old or not relevant anymore. Feel to open up a new issue if you're still experiencing this.

**Comment by wturrell** [comment]
@mattstauffer Thanks. I _did_ see that, it didn't help, but I was able to comment out the relevant lines and get Nginx to handle it correctly.

If I have a feature request, I think it's maybe a Valet command for disabling the front controller on a per-site basis, and have the nginx root set to the actual path. Maybe from time to time others need to do the same, I don't know…
