### ISSUE TITLE
Ngrok gives "bad CPU type in executable" error on M2

### ISSUE THREAD

**Issue by hashemirafsan** [laravel/valet#1375]
### Description:
I was trying to add authtoken for ngrok. But each time i found this issue `bad CPU type in executable: /Users/<user>/.composer/vendor/laravel/valet/bin/ngrok`. Even if i give `valet share` command it's showing same error. 

### Steps To Reproduce:
1. Add authtoken for ngrok `~/.composer/vendor/laravel/valet/bin/ngrok authtoken <token>`
2. Run command `valet share`

### Result 
`bad CPU type in executable: /Users/<user>/.composer/vendor/laravel/valet/bin/ngrok`

### Diagnosis
Device: Apple M2 
Valet: 3.1.13
Laravel: 9.39
PHP: 8.1.14

**Comment by hashemirafsan** [comment]
> @hashemirafsan can you upgrade to the latest version of Valet and try again?

@mattstauffer i upgrade valet to version 3.3.2. But i'm getting same issue.

**Comment by jameswilddev** [comment]
There is a workaround, but it's hacky:

`brew install ngrok`
`cp /opt/homebrew/bin/ngrok ~/.composer/vendor/laravel/valet/bin`

**Comment by mattstauffer** [comment]
@hashemirafsan Thanks for the response! Could you try Valet 4.0.0? It uses Homebrew to install ngrok so hopefully will work around this issue.

**Comment by driesvints** [comment]
Closing this issue because it's inactive, already solved, old or not relevant anymore. Feel to open up a new issue if you're still experiencing this.
