### ISSUE TITLE
Error after executing `brew upgrade`

### ISSUE THREAD

**Issue by ltroya-as** [laravel/valet#1377]
### Description:
Hi guys, 

Today I updated all my global dependencies and execute `brew upgrade`. After doing that, I started to see this error in the console every time I run a `valet` command:

<img width="1279" alt="image" src="https://user-images.githubusercontent.com/84338290/224879060-64edee42-88ca-42a2-9e99-44f9063f66b5.png">

By any change, do you have any hint on how I can fix this issue?

Kind regards

**Comment by ltroya-as** [comment]
Looks like my `valet` command is broken after using the `valet use php@7.4`. I have reinstalled the PHP version 7.4 using `brew reinstall php@7.4`, but I got the same result.

The most recent PHP version I have installed on my system is `8.2.3`

**Comment by mattstauffer** [comment]
@ltroya-as I believe the issue template prompts you for some information that you did not provide. Please provide that information.

```
<!-- DID YOU KNOW? MOST PROBLEMS CAN BE RESOLVED BY RUNNING 3 COMMANDS:
`composer self-update`
`composer global update`
`brew upgrade`
... in fact it's good to run these commands at least once a month! 

Alternatively, try to reboot your machine first to see if it solves your current issue.-->

### Description:


### Steps To Reproduce:


### Diagnosis

<!-- Please upgrade to Valet 2.10 or greater, then run "valet diagnose", and then
     paste the output here. -->
```

**Comment by ltroya-as** [comment]
Hi @mattstauffer,

Are you referring to the `valet diagnose`? It's weird because I am not be able to execute any `valet` command once I change my PHP version to other than 8.2

Current PHP Version:
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/84338290/225135309-07b22921-3d45-4a09-a4ee-9b69e4c9b134.png">

Valet output: 
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/84338290/225135340-7dc0fc07-f794-4b83-975d-36088fa1289b.png">

I can't even change my PHP version using valet: 
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/84338290/225135498-ec768e01-8160-4bef-a887-6a5acf8fcebc.png">

I need to run `brew link php` to change the PHP version. After doing that, everything works as expected:
<img width="232" alt="image" src="https://user-images.githubusercontent.com/84338290/225135671-c22b3aea-1685-4e31-aa22-4a9e48bcd512.png">

PHP Version:
<img width="739" alt="image" src="https://user-images.githubusercontent.com/84338290/225135734-8c7b9c1a-5274-4d45-8104-59e28461fe40.png">

Do you have any hint on how I can fix this? I will really appreciate it.

**Comment by brunogaspar** [comment]
I have the same problem, after a `brew upgrade`.

Unsure what caused it (did not had time to check to be honest 😅), but so far i suppressed the warning by adding `imagick.skip_version_check=true` to `php.ini` and restarting the php service.

**Comment by ltroya-as** [comment]
@brunogaspar Oh, thank you so much! That works! 

For anyone else having the same issue, you can find the `php.ini` of your PHP version using `php --ini`. After that, adding the @brunogaspar recommendation worked for me
