### ISSUE TITLE
UPGRADE.md not found after updating to Valet v4

### ISSUE THREAD

**Issue by nickdavis** [laravel/valet#1379]
### Description:
Updated to valet v4 but the file I'm directed to  - https://github.com/laravel/valet/blob/master/UPGRADE.md - in the following message 404s 

```
Please make sure all custom drivers have been upgraded for Valet 4.
See the upgrade guide for more info:
https://github.com/laravel/valet/blob/master/UPGRADE.md
```

### Steps To Reproduce:
Try to visit this URL https://github.com/laravel/valet/blob/master/UPGRADE.md

### Diagnosis
Alternatively, if someone could let me how to update all custom drivers in the meantime. I've updated composer and brew. Thanks.

Unfortunately `valet diagnose` gives me the same message and no other output.

**Comment by mattstauffer** [comment]
WHOOPS. That's my bad!

@nickdavis https://github.com/laravel/valet/blob/8784458dfe9a4dfa11f204cc46f2b13386f620d3/upgrade.md

There's that file for now, and I'll bring it back shortly.

**Comment by mattstauffer** [comment]
From that doc:

---

- If you have any issues with your drivers, all custom drivers (including the `SampleValetDriver` published by previous versions of Valet) must have the following; see the [new SampleValetDriver](https://github.com/laravel/valet/blob/d7787c025e60abc24a5195dc7d4c5c6f2d984339/cli/stubs/SampleValetDriver.php) for an example:
    - Match the new type hints of the base ValetDriver
    - Extend the new namespaced drivers instead of the old globally-namespaced drivers
    - Have their own namespace

**Comment by nickdavis** [comment]
@mattstauffer thanks so much!
