### ISSUE TITLE
ngrok hostname when upgrading to v4

### ISSUE THREAD

**Issue by streamingsystems** [laravel/valet#1384]
### Description:

I have been using Valet for many years now along with ngrok. Prior to now it's been ngrok v2 and the latest version of Valet 3. 

This morning I upgraded to Valet 4 which also upgraded my ngrok to v3. I had to make a few syntax changes for the valet share (e.g use -domain instead of --subdomain, etc). 

I have a subdomain setup on ngrok:

foo.ngrok.io

In prior versions of Valet and ngrok the "host" that was coming into my Laravel system was:

foo.ngrok.io

So all of my URLs would resolve to, for example:

https://foo.ngrok.io/app.js
https://foo.ngrok.io/images/bar.jpg

As a result, my site would load perfectly. 

Now, for some reason my host is resolving to:

http://application.test

So, when I am visiting my site from https://foo.ngrok.io the page is not loading and when I look in the HTML source code I see: 

http://application.test/app.js
http://application.test/images/bar.jpg

I have tried to solve this myself all morning and can't seem to figure it out. I am not sure if it's a ngrok problem (e.g. it was upgraded to 3.0) or a Valet problem (e.g. it was upgraded to 4.0). 

Any assistance would be greatly appreciated. 

Thanks!

### Diagnosis

<details>
<summary>sw_vers</summary>
<pre>ProductName:		macOS
ProductVersion:		13.2.1
BuildVersion:		22D68</pre>
</details>
<details>
<summary>valet --version</summary>
<pre>Laravel Valet 4.0.0</pre>
</details>
<details>
<summary>cat ~/.config/valet/config.json</summary>
<pre>{
    "tld": "test",
    "loopback": "127.0.0.1",
    "paths": [
        "/Users/rob/code"
    ],
    "share-tool": "ngrok"
}</pre>
</details>
<details>
<summary>cat ~/.composer/composer.json</summary>
<pre>{
    "require": {
        "laravel/installer": "^4.2",
        "laravel/valet": "^4.0"
    }
}</pre>
</details>
<details>
<summary>composer global diagnose</summary>
<pre>Changed current directory to /Users/rob/.composer
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
Checking platform settings: OK
Checking git settings: OK git version 2.39.2
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: FAIL
Missing pubkey for tags verification
Missing pubkey for dev verification
Run composer self-update --update-keys to set them up
Checking composer version: OK
Composer version: 2.5.4
PHP version: 8.2.3
PHP binary path: /usr/local/Cellar/php/8.2.3/bin/php
OpenSSL version: OpenSSL 1.1.1t  7 Feb 2023
cURL version: 7.88.1 libz 1.2.11 ssl (SecureTransport) OpenSSL/1.1.1t
zip: extension present, unzip present, 7-Zip not available</pre>
</details>
<details>
<summary>composer global outdated</summary>
<pre>Changed current directory to /Users/rob/.composer
Info from https://repo.packagist.org: #StandWithUkraine

Direct dependencies required in composer.json:
Everything up to date

Transitive dependencies not required in composer.json:
Everything up to date</pre>
</details>
<details>
<summary>ls -al /etc/sudoers.d/</summary>
<pre>total 0
drwxr-xr-x   2 root  wheel    64 Feb  9 03:39 .
drwxr-xr-x  81 root  wheel  2592 Mar 15 22:10 ..</pre>
</details>
<details>
<summary>brew config</summary>
<pre>HOMEBREW_VERSION: 4.0.6
ORIGIN: https://github.com/Homebrew/brew
HEAD: 0c1031f2fd71016f0f5df699caaed384487bfb16
Last commit: 9 days ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 7e9c774bbaecf34bb618a70a3ba2f26a54f322f7
Core tap last commit: 4 weeks ago
Core tap branch: master
Core tap JSON: 19 Mar 18:48 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: nano
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: dodeca-core 64-bit kabylake
Clang: 14.0.0 build 1400
Git: 2.39.2 => /usr/local/bin/git
Curl: 7.86.0 => /usr/bin/curl
macOS: 13.2.1-x86_64
CLT: 14.2.0.0.1.1668646533
Xcode: 14.2</pre>
</details>
<details>
<summary>brew services list</summary>
<pre>Name    Status User File
dnsmasq none            root 
httpd   none                 
nginx   none            root 
php     none            root 
redis   none                 
unbound none</pre>
</details>
<details>
<summary>brew list --formula --versions | grep -E "(php|nginx|dnsmasq|mariadb|mysql|mailhog|openssl)(@\d\..*)?\s"</summary>
<pre>dnsmasq 2.89 2.88 2.86
nginx 1.23.2 1.23.3
openssl@1.1 1.1.1t
php 8.2.0 8.1.4.reinstall 8.2.3 8.1.10_1 8.1.4</pre>
</details>
<details>
<summary>brew outdated</summary>
<pre>ffmpeg
git
glib
gobject-introspection
harfbuzz
highway
httpd
imath
jpeg-xl
libvidstab
maven
node
openexr
php
sdl2
snappy
sqlite
ngrok
swiftformat-for-xcode</pre>
</details>
<details>
<summary>brew tap</summary>
<pre>homebrew/cask
homebrew/core
homebrew/services
ngrok/ngrok</pre>
</details>
<details>
<summary>php -v</summary>
<pre>PHP 8.2.3 (cli) (built: Feb 15 2023 00:34:20) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.3, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.3, Copyright (c), by Zend Technologies</pre>
</details>
<details>
<summary>which -a php</summary>
<pre>/usr/local/bin/php
/usr/local/bin/php</pre>
</details>
<details>
<summary>php --ini</summary>
<pre>Configuration File (php.ini) Path: /usr/local/etc/php/8.2
Loaded Configuration File:         /usr/local/etc/php/8.2/php.ini
Scan for additional .ini files in: /usr/local/etc/php/8.2/conf.d
Additional .ini files parsed:      /usr/local/etc/php/8.2/conf.d/error_log.ini,
/usr/local/etc/php/8.2/conf.d/ext-opcache.ini,
/usr/local/etc/php/8.2/conf.d/php-memory-limits.ini</pre>
</details>
<details>
<summary>nginx -v</summary>
<pre>nginx version: nginx/1.23.3</pre>
</details>
<details>
<summary>curl --version</summary>
<pre>curl 7.86.0 (x86_64-apple-darwin22.0) libcurl/7.86.0 (SecureTransport) LibreSSL/3.3.6 zlib/1.2.11 nghttp2/1.47.0
Release-Date: 2022-10-26
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: alt-svc AsynchDNS GSS-API HSTS HTTP2 HTTPS-proxy IPv6 Kerberos Largefile libz MultiSSL NTLM NTLM_WB SPNEGO SSL threadsafe UnixSockets</pre>
</details>
<details>
<summary>php --ri curl</summary>
<pre>curl

cURL support => enabled
cURL Information => 7.88.1
Age => 10
Features
AsynchDNS => Yes
CharConv => No
Debug => No
GSS-Negotiate => No
IDN => Yes
IPv6 => Yes
krb4 => No
Largefile => Yes
libz => Yes
NTLM => Yes
NTLMWB => Yes
SPNEGO => Yes
SSL => Yes
SSPI => No
TLS-SRP => Yes
HTTP2 => Yes
GSSAPI => Yes
KERBEROS5 => Yes
UNIX_SOCKETS => Yes
PSL => No
HTTPS_PROXY => Yes
MULTI_SSL => Yes
BROTLI => Yes
ALTSVC => Yes
HTTP3 => No
UNICODE => No
ZSTD => Yes
HSTS => Yes
GSASL => No
Protocols => dict, file, ftp, ftps, gopher, gophers, http, https, imap, imaps, ldap, ldaps, mqtt, pop3, pop3s, rtmp, rtmpe, rtmps, rtmpt, rtmpte, rtmpts, rtsp, scp, sftp, smb, smbs, smtp, smtps, telnet, tftp
Host => x86_64-apple-darwin22.3.0
SSL Version => (SecureTransport) OpenSSL/1.1.1t
ZLib Version => 1.2.11
libSSH Version => libssh2/1.10.0

Directive => Local Value => Master Value
curl.cainfo => no value => no value</pre>
</details>
<details>
<summary>/usr/local/bin/ngrok version</summary>
<pre>ngrok version 3.2.1</pre>
</details>
<details>
<summary>ls -al ~/.ngrok2</summary>
<pre>total 8
drwx------   3 rob  staff    96 Feb 24  2020 .
drwxr-xr-x+ 83 rob  staff  2656 Mar 19 13:47 ..
-rw-------@  1 rob  staff    74 Mar 19 09:09 ngrok.yml</pre>
</details>
<details>
<summary>brew info nginx</summary>
<pre>==> nginx: stable 1.23.3 (bottled), HEAD
HTTP(S) server and reverse proxy, and IMAP/POP3 proxy server
https://nginx.org/
/usr/local/Cellar/nginx/1.23.2 (23 files, 2.2MB)
  Built from source
/usr/local/Cellar/nginx/1.23.3 (26 files, 2.2MB) *
  Poured from bottle on 2023-01-09 at 14:15:18
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/nginx.rb
License: BSD-2-Clause
==> Dependencies
Required: openssl@1.1, pcre2
==> Options
--HEAD
	Install HEAD version
==> Caveats
Docroot is: /usr/local/var/www

The default port has been set in /usr/local/etc/nginx/nginx.conf to 8080 so that
nginx can run without sudo.

nginx will load all files in /usr/local/etc/nginx/servers/.

To start nginx now and restart at login:
  brew services start nginx
==> Analytics
install: 5,708 (30 days), 88,769 (90 days), 428,290 (365 days)
install-on-request: 5,695 (30 days), 88,637 (90 days), 427,561 (365 days)
build-error: 0 (30 days)</pre>
</details>
<details>
<summary>brew info php</summary>
<pre>==> php: stable 8.2.4 (bottled), HEAD
General-purpose scripting language
https://www.php.net/
/usr/local/Cellar/php/8.1.4 (510 files, 80.0MB)
  Built from source
/usr/local/Cellar/php/8.1.4.reinstall (193 files, 32.5MB)
  Built from source
/usr/local/Cellar/php/8.1.10_1 (510 files, 80.1MB)
  Built from source
/usr/local/Cellar/php/8.2.0 (516 files, 81.5MB)
  Built from source
/usr/local/Cellar/php/8.2.3 (519 files, 81.5MB) *
  Poured from bottle using the formulae.brew.sh API on 2023-02-28 at 07:46:04
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/php.rb
License: PHP-3.01
==> Dependencies
Build: httpd, pkg-config
Required: apr, apr-util, argon2, aspell, autoconf, curl, freetds, gd, gettext, gmp, icu4c, krb5, libpq, libsodium, libzip, oniguruma, openldap, openssl@1.1, pcre2, sqlite, tidy-html5, unixodbc
==> Options
--HEAD
	Install HEAD version
==> Caveats
To enable PHP in Apache add the following to httpd.conf and restart Apache:
    LoadModule php_module /usr/local/opt/php/lib/httpd/modules/libphp.so

    <FilesMatch \.php$>
        SetHandler application/x-httpd-php
    </FilesMatch>

Finally, check DirectoryIndex includes index.php
    DirectoryIndex index.php index.html

The php.ini and php-fpm.ini file can be found in:
    /usr/local/etc/php/8.2/

To start php now and restart at login:
  brew services start php
==> Analytics
install: 26,272 (30 days), 315,854 (90 days), 1,421,033 (365 days)
install-on-request: 23,188 (30 days), 280,134 (90 days), 1,236,245 (365 days)
build-error: 3 (30 days)</pre>
</details>
<details>
<summary>brew info openssl</summary>
<pre>==> openssl@3: stable 3.1.0 (bottled) [keg-only]
Cryptography and SSL/TLS Toolkit
https://openssl.org/
Not installed
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/openssl@3.rb
License: Apache-2.0
==> Dependencies
Required: ca-certificates
==> Caveats
A CA file has been bootstrapped using certificates from the system
keychain. To add additional certificates, place .pem files in
  /usr/local/etc/openssl@3/certs

and run
  /usr/local/opt/openssl@3/bin/c_rehash

openssl@3 is keg-only, which means it was not symlinked into /usr/local,
because macOS provides LibreSSL.

==> Analytics
install: 66,441 (30 days), 808,890 (90 days), 2,346,815 (365 days)
install-on-request: 16,751 (30 days), 211,212 (90 days), 1,274,508 (365 days)
build-error: 616 (30 days)</pre>
</details>
<details>
<summary>openssl version -a</summary>
<pre>LibreSSL 3.3.6
built on: date not available
platform: information not available
options:  bn(64,64) rc4(16x,int) des(idx,cisc,16,int) blowfish(idx) 
compiler: information not available
OPENSSLDIR: "/private/etc/ssl"</pre>
</details>
<details>
<summary>openssl ciphers</summary>
<pre>AEAD-AES256-GCM-SHA384:AEAD-CHACHA20-POLY1305-SHA256:AEAD-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-CHACHA20-POLY1305:GOST2012256-GOST89-GOST89:DHE-RSA-CAMELLIA256-SHA256:DHE-RSA-CAMELLIA256-SHA:GOST2001-GOST89-GOST89:AES256-GCM-SHA384:AES256-SHA256:AES256-SHA:CAMELLIA256-SHA256:CAMELLIA256-SHA:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-CAMELLIA128-SHA256:DHE-RSA-CAMELLIA128-SHA:AES128-GCM-SHA256:AES128-SHA256:AES128-SHA:CAMELLIA128-SHA256:CAMELLIA128-SHA:ECDHE-RSA-RC4-SHA:ECDHE-ECDSA-RC4-SHA:RC4-SHA:RC4-MD5:ECDHE-RSA-DES-CBC3-SHA:ECDHE-ECDSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:DES-CBC3-SHA</pre>
</details>
<details>
<summary>sudo nginx -t</summary>
<pre>nginx: the configuration file /usr/local/etc/nginx/nginx.conf syntax is ok
nginx: configuration file /usr/local/etc/nginx/nginx.conf test is successful</pre>
</details>
<details>
<summary>which -a php-fpm</summary>
<pre></pre>
</details>
<details>
<summary>/usr/local/opt/php/sbin/php-fpm -v</summary>
<pre>PHP 8.2.3 (fpm-fcgi) (built: Feb 15 2023 00:34:31)
Copyright (c) The PHP Group
Zend Engine v4.2.3, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.3, Copyright (c), by Zend Technologies</pre>
</details>
<details>
<summary>sudo /usr/local/opt/php/sbin/php-fpm -y /usr/local/etc/php/8.2/php-fpm.conf --test</summary>
<pre>[19-Mar-2023 13:48:35] NOTICE: configuration file /usr/local/etc/php/8.2/php-fpm.conf test is successful</pre>
</details>
<details>
<summary>ls -al ~/Library/LaunchAgents | grep homebrew</summary>
<pre></pre>
</details>
<details>
<summary>ls -al /Library/LaunchAgents | grep homebrew</summary>
<pre></pre>
</details>
<details>
<summary>ls -al /Library/LaunchDaemons | grep homebrew</summary>
<pre>-rw-r--r--@  1 root  admin   788 Mar 19 13:11 homebrew.mxcl.dnsmasq.plist
-rw-r--r--@  1 root  admin   679 Mar 19 13:11 homebrew.mxcl.nginx.plist
-rw-r--r--@  1 root  admin   772 Mar 19 13:11 homebrew.mxcl.php.plist
-rw-r--r--   1 root  admin   585 Dec 14  2021 homebrew.mxcl.php@8.0.plist</pre>
</details>
<details>
<summary>ls -al /Library/LaunchDaemons | grep "com.laravel.valet."</summary>
<pre></pre>
</details>
<details>
<summary>ls -aln /etc/resolv.conf</summary>
<pre>lrwxr-xr-x  1 0  0  22 Feb  9 03:39 /etc/resolv.conf -> ../var/run/resolv.conf</pre>
</details>
<details>
<summary>cat /etc/resolv.conf</summary>
<pre>#
# macOS Notice
#
# This file is not consulted for DNS hostname resolution, address
# resolution, or the DNS query routing mechanism used by most
# processes on this system.
#
# To view the DNS configuration used by this system, use:
#   scutil --dns
#
# SEE ALSO
#   dns-sd(1), scutil(8)
#
# This file is automatically generated.
#
search stl.streamingsystems.io
nameserver 10.1.0.1
nameserver 10.1.20.1
nameserver 10.1.21.1</pre>
</details>
<details>
<summary>ifconfig lo0</summary>
<pre>lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> mtu 16384
	options=1203<RXCSUM,TXCSUM,TXSTATUS,SW_TIMESTAMP>
	inet 127.0.0.1 netmask 0xff000000 
	inet6 ::1 prefixlen 128 
	inet6 fe80::1%lo0 prefixlen 64 scopeid 0x1 
	nd6 options=201<PERFORMNUD,DAD></pre>
</details>
<details>
<summary>sh -c 'echo "------\n/usr/local/etc/nginx/valet/valet.conf\n---\n"; cat /usr/local/etc/nginx/valet/valet.conf | grep -n "# valet loopback"; echo "\n------\n"'</summary>
<pre>------
/usr/local/etc/nginx/valet/valet.conf
---

3:    #listen VALET_LOOPBACK:80; # valet loopback

------</pre>
</details>
<details>
<summary>sh -c 'for file in ~/.config/valet/dnsmasq.d/*; do echo "------\n~/.config/valet/dnsmasq.d/$(basename $file)\n---\n"; cat $file; echo "\n------\n"; done'</summary>
<pre>------
~/.config/valet/dnsmasq.d/tld-test.conf
---

address=/.test/127.0.0.1
listen-address=127.0.0.1

------</pre>
</details>
<details>
<summary>sh -c 'for file in ~/.config/valet/nginx/*; do echo "------\n~/.config/valet/nginx/$(basename $file)\n---\n"; cat $file | grep -n "# valet loopback"; echo "\n------\n"; done'</summary>
<pre>------
~/.config/valet/nginx/*
---

cat: /Users/rob/.config/valet/nginx/*: No such file or directory

------</pre>
</details>

**Comment by streamingsystems** [comment]
A little more information, when I look at the SERVER php variables coming into Laravel (when hitting ngrok) I see: 

HTTP_X_FORWARDED_HOST => foo.ngrok.io
HTTP_HOST => application.test 

When I am testing and I force the $_SERVER['HTTP_HOST'] to be foo.ngrok.io in the Valet server.php file it all seems to work correctly. 

It's almost like the HTTP_HOST is not being set correctly in the Valet server.php.

Maybe this was missed in the rewrite to Valet 4 or ngrok changed something when moving to v3. 

I am sure it's an easy fix I just don't know enough about the Valet code to be useful except to report my findings, otherwise I would fix it and create a PR. 

Note: foo.ngrok.io is not the real subdomain as I did not want to put my subdomain public.

**Comment by streamingsystems** [comment]
Greetings. I was just checking to see when this might be fixed? I hacked my local copy to get it to work but when I upgraded to the latest valet (from a few days ago) it broke me hack (of course). 

I don't know enough about Valet to fix the bug myself otherwise I would and create a PR.

**Comment by drbyte** [comment]
Does the problem get fixed if you (temporarily, and manually) replace the ngrok binary with a v2 binary instead of the v3 binary?

**Comment by drbyte** [comment]
To manually (and temporarily) "downgrade" ngrok you could do something like this:
- download the ngrok binary from the v3 branch of Valet, here on github (change branch, browse to the bin directory, grab the ngrok binary)
- copy it (`cp` command) to `/usr/local/bin/ngrok`, replacing the symlink that homebrew created there
- test Valet

To revert back to homebrew's version, you can `rm /usr/local/bin/ngrok` to delete the old binary, and then you could tell homebrew to re-link ngrok. (I think this will do it: `brew link ngrok`)

**Comment by drbyte** [comment]
Perhaps skip any parameters that aren't needed? ie: the authtoken param. Since it's stored in your ngrok.yml file anyway.

I haven't studied the tech changes from ngrok v2 to v3, so all of my comments here today have been simply geared around trying to determine whether your problem is specific to an ngrok change, or if it's actually something Valet has changed incompletely/incorrectly/etc.

**Comment by streamingsystems** [comment]
Hi Chris,

I am still playing with this. I am not an expert on either Valet or ngrok.

Does is help you troubleshoot to see that the HTTP_HOST that is coming into Laravel is application.test? It seems like that is what’s breaking everything.

Have you ever setup a domain with ngrok and just tried to hit your web site? I can get you a test domain on mine and let you borrow my API key if you want to test.

From: Chris Brown ***@***.***>
Date: Thursday, March 30, 2023 at 4:45 PM
To: laravel/valet ***@***.***>
Cc: streamingsystems ***@***.***>, Author ***@***.***>
Subject: Re: [laravel/valet] ngrok hostname when upgrading to v4 (Issue #1384)

Perhaps skip any parameters that aren't needed? ie: the authtoken param. Since it's stored in your ngrok.yml file anyway.

I haven't studied the tech changes from ngrok v2 to v3, so all of my comments here today have been simply geared around trying to determine whether your problem is specific to an ngrok change, or if it's actually something Valet has changed incompletely/incorrectly/etc.

**Comment by webpatser** [comment]
I have the same issue. When I share (with our without a --domain flag) my secure (or unsecured) valet site would serve the homepage correctly. But links are pointing to the local domain with port 60 in the URL and thus failing. 

Strange thing is that other valet sites are not having this issue. I compared all settings between projects and they are the same (except for the hostname :-) )

**Comment by streamingsystems** [comment]
I was never able to solve it, for now I have to hardcode a variable in the valet server.php file ☹



From: Christoph Kempen ***@***.***>
Date: Friday, April 21, 2023 at 3:35 PM
To: laravel/valet ***@***.***>
Cc: streamingsystems ***@***.***>, Author ***@***.***>
Subject: Re: [laravel/valet] ngrok hostname when upgrading to v4 (Issue #1384)

I have the same issue. When I share (with our without a --domain flag) my secure (or unsecured) valet site would serve the homepage correctly. But links are pointing to the local domain with port 60 in the URL and thus failing.

Strange thing is that other valet sites are not having this issue. I compared all settings between projects and they are the same (except for the hostname :-) )

**Comment by drbyte** [comment]
@webpatser are you using a paid ngrok account?

**Comment by webpatser** [comment]
yes. But if the strange thing is, that for other valet sites on the same machine, sharing works just fine. Also what ngrok endpoint I use does't matter. All valet sites just works, except for one. 

When I type in the correct URL the page loads. But links in Laravel are not parsed correctly for some reason. All projects are on the same latest Laravel 10.8

**Comment by drbyte** [comment]
@webpatser Since in your case it's isolated to one valet site name, I wonder if perhaps your nginx config for it is damaged or has some quirk with it?

You can find the config file for each secured site as:
`~/.config/valet/Nginx/SITENAME.test`

I suggest copying that file someplace temporarily as a backup.
Then unsecure that site and re-secure it with valet.
Then test ngrok with it again.

**Comment by drbyte** [comment]
(as for port 60, that's intentional so that the ngrok ssl share can be targeted within the over all configuration. The nginx config file I mentioned is where port 60 is set as a listening port, and then the valet share command tells ngrok to start the site and link ssl to port 60 on your computer)

**Comment by webpatser** [comment]
I already did that, but I just did it again. Unlinked the project. Checked if the config was removed from all valet config directories. Linked and secured the project again. Same thing. 

I already checked if the nginx file was different from the others etc. No differences except for the hostname and paths

**Comment by drbyte** [comment]
You said:
- it's just a single project
- it generates links to port 60 (which it shouldn't need to do, the port 60 should be totally transparent)

Common causes of site-specific problems are:
- site-specific nginx config
- site-specific `.valet-php` and other valet-specific per-site config files
- something unique to the domain-name that's triggering an unexpected side-effect 
- wrong ValetDriver being triggered due to something in the driver's detection logic
- sometimes a configuration of sites in multiple subdirectories below/inside other sites can cause anomalies

**Comment by webpatser** [comment]
hmmm.. I was working down the list of possible things that go wrong. 

I unlinked the project and linked it again with a custom name and it worked. Strange thing is now, that in ngrok I see it now forwards it to port 80.

What seems to be the problem is that my projects are named as the domain name. And for the project that was not working it was an .io TLD. The domain valet made was project.io.test. That used to work fine, but since an upgrade of or valet, or ngrok the error appeared.

**Comment by webpatser** [comment]
I now see that @streamingsystems also had an .io domain as ngrok domain. So that seems to be the problem? Al my other domain I am currently working on have other TLDs and they work fine.

**Comment by drbyte** [comment]
Are all of the other TLDs .com ? Do you mind listing them? (I'm more interested in which ones other than .com)
It'll help with investigating ;)

**Comment by webpatser** [comment]
most of them are `.nl`. one is `.com`. But for some reason, it stopped working again. I now get the local domain again after I restarted valet. I'll investigate more.

**Comment by streamingsystems** [comment]
Hi All,

I think I might have found and fixed the issue (at least the one that is affecting me) which is hopefully the same issue affecting @webpatser 

Here are the $_SERVER variables currently coming down from ngrok when I load foo.ngrok.io (this is not my real subdomain): 

USER: rob
HOME: /Users/rob
HTTP_X_FORWARDED_PROTO: https
HTTP_X_FORWARDED_HOST: foo.ngrok.io
HTTP_X_FORWARDED_FOR: 72.182.13.89
HTTP_SEC_FETCH_SITE: none
HTTP_SEC_FETCH_MODE: navigate
HTTP_SEC_FETCH_DEST: document
HTTP_COOKIE: XSRF-TOKEN=eyJpdiI6InN4aGkwR2pCR3Q5MjFzUlhYU2tHNHc9PSIsInZhbHVlIjoiL0E4QTVTazl3Vnh5Y2hleXN1R3Q0U0MwU1hIWE8rdGNZVGE1OWY2T3IyU0tFbExmZndVbUxvNHBnczRVRXB3UWRZMjB1Q0c4eHdubWkyZk1sa3k1K0ZWRVVQYmptM283VUtRaGZnYW03dWJQSDd4Q2ppWWQ1c1c0UWIrVkNPZy8iLCJtYWMiOiJjMjNjNTBkOGIwYzI4NDc4ODIyM2IzZWM4MjZkMTE5YzhmMGMzZjMzNTgxOGU2ZDdmYTYwMjY1NDg2NDAyMmM2IiwidGFnIjoiIn0%3D; laravel_session=eyJpdiI6IlA5bTBad044OG9MTnlrajJSNnFUU1E9PSIsInZhbHVlIjoiZVBIT2Z4ZU8vcUorTFc1MHA3ek5FNnpubHhWcTZUMEtKMWxwczZFa1VqeGc0Zjh6U1oybDNuRTRrR2M1cHZyTGdlQkNXQnh3MWdHOXl6ODYxWFNFd3pxTEJySG51alRQVTR6NzR1UjYra2QzdHdHNFFMRDNndHh1RGF4SWdma2siLCJtYWMiOiJjNDE1YTgyZDM2NDgxNjk0NzJkYWEyNjg3YjY5OTk1ZjBlOWMxZDQ5MDZmNzZiZWI4NGIwNTY4ODM4OGRkM2ExIiwidGFnIjoiIn0%3D
HTTP_ACCEPT_LANGUAGE: en-US,en;q=0.9
HTTP_ACCEPT_ENCODING: gzip, deflate, br
HTTP_ACCEPT: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
HTTP_USER_AGENT: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.4 Safari/605.1.15
HTTP_HOST: application.test
PATH_INFO: 
REDIRECT_STATUS: 200
SERVER_NAME: 
SERVER_PORT: 80
SERVER_ADDR: 127.0.0.1
REMOTE_PORT: 52218
REMOTE_ADDR: 127.0.0.1
SERVER_SOFTWARE: nginx/1.23.4
GATEWAY_INTERFACE: CGI/1.1
SERVER_PROTOCOL: HTTP/1.1
DOCUMENT_ROOT: 
DOCUMENT_URI: /Users/rob/.composer/vendor/laravel/valet/server.php
REQUEST_URI: /
SCRIPT_NAME: /Users/rob/.composer/vendor/laravel/valet/server.php
SCRIPT_FILENAME: /Users/rob/.composer/vendor/laravel/valet/server.php
CONTENT_LENGTH: 
CONTENT_TYPE: 
REQUEST_METHOD: GET
QUERY_STRING: 
FCGI_ROLE: RESPONDER
PHP_SELF: /Users/rob/.composer/vendor/laravel/valet/server.php
REQUEST_TIME_FLOAT: 1682165741.5127
REQUEST_TIME: 1682165741

Note the HTTP_X_FORWARDED_HOST is present but the HTTP_X_ORIGINAL_HOST is not present. Based on looking at the Valet code it seems that maybe ngrok used to send HTTP_X_ORIGINAL_HOST in the old days (maybe this is on longer being sent with the new ngrok).

In valet Server.php line: 

`/**
 * ngrok uses the X-Original-Host to store the forwarded hostname.
 */
if (isset($_SERVER['HTTP_X_ORIGINAL_HOST']) && ! isset($_SERVER['HTTP_X_FORWARDED_HOST'])) {
    $_SERVER['HTTP_X_FORWARDED_HOST'] = $_SERVER['HTTP_X_ORIGINAL_HOST'];
}`

This code is not executed in my case because HTTP_X_ORIGINAL_HOST is present. But the purpose is to set $_SERVER['HTTP_X_FORWARDED_HOST'] equal to $_SERVER['HTTP_X_ORIGINAL_HOST'], if $_SERVER['HTTP_X_ORIGINAL_HOST'] is present. 

However, later on in the code it goes into the LaravelValetDriver and runs this: 

`public function beforeLoading(string $sitePath, string $siteName, string $uri): void
    {
        // Shortcut for getting the "local" hostname as the HTTP_HOST
        if (isset($_SERVER['HTTP_X_ORIGINAL_HOST'], $_SERVER['HTTP_X_FORWARDED_HOST'])) {
            $_SERVER['HTTP_HOST'] = $_SERVER['HTTP_X_FORWARDED_HOST'];
        }
    }`

I have only ever used isset with a single function parameter but based on what I am reading *all* variables must be true for isset to evaluate to true, so it's skipping this HTTP_HOST assignment. 

From the PHP docs: 

_The isset() returns a boolean value. It will return true if the parameter passed is declared and is not set NULL. In the case, where over one parameter is passed (they can be of different data types), the isset() will return true only if all the passed variables are not equal to NULL and their values exist. 

It will return false when a variable has not been declared or is equal to NULL. If there is more than one parameter passed, **and if any of them is unset, then the returned result will be false**, irrespective of the set/unset status of other variables._ 

Because HTTP_X_FORWARDED_HOST should already be set here (e.g the code that sets HTTP_X_FORWARDED_HOST from HTTP_X_ORIGINAL_HOST above) I think this function can be changed to: 

`public function beforeLoading(string $sitePath, string $siteName, string $uri): void
    {
        // Shortcut for getting the "local" hostname as the HTTP_HOST
        if (isset($_SERVER['HTTP_X_FORWARDED_HOST'])) {
            $_SERVER['HTTP_HOST'] = $_SERVER['HTTP_X_FORWARDED_HOST'];
        }
    }`

When I made this change my web page loaded perfectly. 

@webpatser 

Can you go into your ~/.composer/vendor/laravel/valet/cli/Valet/Drivers/LaravelValetDriver.php and change this function and see if your page loads fine like mine does.

**Comment by drbyte** [comment]
Here's some history on those variables.
https://github.com/laravel/valet/issues/342
https://github.com/laravel/valet/pull/389

Looks like I was the one who recommended the shortened `isset()` 😊  ... But it was semantically correct, an `&&` operation, in the original code.

As you say, ngrok may have changed ...

**Comment by streamingsystems** [comment]
I would say ngrok changed. The reason I say that is because it's not in the headers now (in the latest ngrok) and it must have been there before the upgrade as Valet was working great. That one morning in March I upgraded both Valet and Ngrok and it instantly stopped working. 

As such it seems that with my proposed change it would still be backwards compatible in that the first code snippet above will set HTTP_X_FORWARDED_HOST from HTTP_X_ORIGINAL_HOST (if present) and then the second code snippet (beforeLoading function) will test for HTTP_X_FORWARDED_HOST.

**Comment by webpatser** [comment]
yes. that if-replacement fixed it @streamingsystems

**Comment by streamingsystems** [comment]
Great @drbyte do you want me to create a PR. Although this is so simple it might just be easier for you to change the if statement and commit and release.

**Comment by streamingsystems** [comment]
mystery solved: 

Hi Rob,
 
Thank you for contacting ngrok Support. You are correct, the X-Original-Host was replaced with the more standard X-Forwarded-Host with the version 3.x + Agent to better align with web standards.
 
[More Info: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-Host](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-Host)

**Comment by drbyte** [comment]
@streamingsystems thanks for doing the research and testing on this.

I've submitted a PR #1404

Just waiting for @mattstauffer and @driesvints to review and tag a release.

**Comment by mattstauffer** [comment]
Merged, and @driesvints will tag a release shortly. Thank you all so much for your hard work here!

**Comment by webpatser** [comment]
You are welcome. Just upgraded and  all works like a charm again!

**Comment by drbyte** [comment]
@webpatser wrote:
> You are welcome. Just upgraded and all works like a charm again!

Great! Thanks for confirming it!

**Comment by webpatser** [comment]
@jeffgreco13 Yes. after upgrading valet it was fixed. I reinstalled valet a few times before the fix, so maybe that helped too...
