### ISSUE TITLE
Valet install (seems like not working)

### ISSUE THREAD

**Issue by shamsuljewel** [laravel/valet#1385]
I had valet 3 and working.

I tried to update into version 4.

So As the upgrade guide says

I did

`brew update`

then 
`composer global require laravel/valet`

which runs without any issue.

But once try to run 
`valet install`

I am getting this message
`Please make sure all custom drivers have been upgraded for Valet 4.
See the upgrade guide for more info:
https://github.com/laravel/valet/blob/master/UPGRADE.md`

I have already checked the guide and have php8.2 installed through Homebrew and liked as default. But still no luck.

**Comment by mattstauffer** [comment]
@shamsuljewel As you can see in the [upgrade guide](https://github.com/laravel/valet/blob/master/UPGRADE.md), this means you have a custom Valet driver in `~/.config/valet/Drivers` that needs to be upgraded to follow the new structure for custom Valet drivers.

If you don't have any custom drivers, there must be some error with the automated upgrade process; if that's the case, your `~/.config/valet/Drivers/SampleValetDriver.php` with the contents of this file: https://github.com/laravel/valet/blob/d7787c025e60abc24a5195dc7d4c5c6f2d984339/cli/stubs/SampleValetDriver.php

**Comment by shamsuljewel** [comment]
Hi @mattstauffer,
I found a custom driver at ~/.config/valet/Drivers/ directory. And after removing that `valet install` runs fine.
The directory only have SampleValetDriver.php file.
