### ISSUE TITLE
ValetDriver.php syntax error when using fastcgi_pass   127.0.0.1:9056;

### ISSUE THREAD

**Issue by erralb** [laravel/valet#1387]
### Steps To Reproduce:
Some of my old projects are stuck with PHP5.6.

Before upgrading to Valet 4, I was using : 
`fastcgi_pass   127.0.0.1:9056;`
in these projects' nginx configuration instead of : 
 `fastcgi_pass "unix:/Users/username/.config/valet/valet.sock";`

But after upgrading, I now get : `
Parse error: syntax error in /Users/username/.composer/vendor/laravel/valet/cli/Valet/Drivers/ValetDriver.php on line 15`

**Comment by driesvints** [comment]
We no longer support PHP 5.6 in Valet v4 sorry. Please continue to use Valet v3 if you need support for anything below PHP 7.1

**Comment by erralb** [comment]
In this case, isn't it more a matter of nginx connecting to a TCP port rather than something to do with PHP 5.6 ?
