### ISSUE TITLE
Ngrok arguments supported?

### ISSUE THREAD

**Issue by lezhnev74** [laravel/valet#139]
Hi!

I bought a paid Ngrok account and would like to do `valet share` with arguments like `--region ap --subdomain custom_domain`. 

Is it possible to set such arguments for every site I share or globally for Valet?

**Comment by lezhnev74** [comment]
Ok, I think I resolved that by setting up the config file:
`~/.ngrok2/ngrok.yml`

The config structure explained here: 
https://ngrok.com/docs#config

**Comment by campaignzee** [comment]
Hi @lezhnev74,

I'm also trying to setup a permanent subdomain for local dev (easier to test webhooks this way). Were you able to get subdomains working with valet share? If so, I would greatly appreciate if you could tell me a bit more.

I created a custom tunnel in my ngrok.yml file, but can't seem to get valet share to load a specific tunnel. Any tips?

**Comment by lezhnev74** [comment]
Well, this is not the clean solution but you can do this:

![example](https://ftp.azureedge.net/files/2016-09-29_6xa2o.jpg)

Basically you create a tunnel and use it without Valet, directly calling Ngrok.

**Comment by adamwathan** [comment]
If you switch to `dev-master`, we've added support for this as outlined here:

https://github.com/laravel/valet/pull/112

**Comment by campaignzee** [comment]
@adamwathan Awesome! Thanks for letting me know.

@lezhnev74 Thanks for letting me know how you accomplished it. It looks like the latest version has this built in 👍
