### ISSUE TITLE
Restarting MySQL / MariaDB after reboot

### ISSUE THREAD

**Issue by tommytompkins** [laravel/valet#140]
I just spent some time pulling out my hair because it wasn't clear that I had to restart MariaDB after rebooting my computer.  I had Valet up and running using MariaDB and all was working great, but after rebooting my machine I couldn't get my site to load.  It was giving me the following error:

```
SQLSTATE[HY000] [2002] Connection refused
```

After a little digging, I round out that I needed to run the following command to bring MariaDB back up:

```
brew services start mariadb
```

The following command also works:

```
mysql.server start
```

It would be nice if these details could be added to the Valet docs to help others that are trying to get started with Valet.

**Comment by drbyte** [comment]
The last time I did a fresh install of Valet on a new Mac, it installed mariadb and I'm pretty sure it ran `brew services start mariadb` for me. Perhaps that's changed in the last 3 months.

NOTE: You only have to run `brew services start mariadb` once, as that also tells it to auto-start on each reboot.
(NOTE: `mysql.server start` only starts it in the current boot, and doesn't survive a reboot. The `brew services start mariadb` command survives a reboot.)

**Comment by tommytompkins** [comment]
Hmm...interesting.  I'm curious why it didn't auto restart for me.

**Comment by drbyte** [comment]
Hmmm ... my memory was wrong:  I just checked and I had installed mariadb before installing Valet. Found these entries (amongst others), in this order in my bash history:

```sh
brew install mariadb
brew services start mariadb
composer global require laravel/valet
valet install
```

So, yes, 👍 I agree, adding `brew services start mariadb` to the docs might be a good idea; granted, brew does tell you to do that at the end of installing mariadb.

**Comment by drbyte** [comment]
This is now mentioned in the docs.
https://laravel.com/docs/5.3/valet#installation
