### ISSUE TITLE
Valet doesn't create tdl and loopback configurations when they don't exist

### ISSUE THREAD

**Issue by ftpman** [laravel/valet#1403]
### Description

https://github.com/laravel/valet/blob/fcfbb9829e0fb83baa741796e1c95891f4c670fe/cli/app.php#L100-L105

**The block above is never executed because the block below doesn't let it.**

https://github.com/laravel/valet/blob/fcfbb9829e0fb83baa741796e1c95891f4c670fe/cli/Valet/Configuration.php#L89-L94

**When I delete the config.json file then an exception is thrown**

```
PHP Warning:  file_get_contents(/Users/ftpman/.config/valet/config.json): Failed to open stream: No such file or directory in /Users/ftpman/.composer/vendor/laravel/valet/cli/Valet/Filesystem.php on line 84

Warning: file_get_contents(/Users/ftpman/.config/valet/config.json): Failed to open stream: No such file or directory in /Users/ftpman/.composer/vendor/laravel/valet/cli/Valet/Filesystem.php on line 84
PHP Fatal error:  Uncaught JsonException: Syntax error in /Users/ftpman/.composer/vendor/laravel/valet/cli/Valet/Configuration.php:155
Stack trace:
#0 /Users/ftpman/.composer/vendor/laravel/valet/cli/Valet/Configuration.php(155): json_decode('', true, 512, 4194304)
#1 /Users/ftpman/.composer/vendor/laravel/valet/cli/includes/facades.php(22): Valet\Configuration->read()
#2 /Users/ftpman/.composer/vendor/laravel/valet/cli/app.php(103): Facade::__callStatic('read', Array)
#3 /Users/ftpman/.composer/vendor/laravel/valet/cli/valet.php(4): require_once('/Volumes/Dados/...')
#4 {main}
  thrown in /Users/ftpman/.composer/vendor/laravel/valet/cli/Valet/Configuration.php on line 155

Fatal error: Uncaught JsonException: Syntax error in /Users/ftpman/.composer/vendor/laravel/valet/cli/Valet/Configuration.php:155
Stack trace:
#0 /Users/ftpman/.composer/vendor/laravel/valet/cli/Valet/Configuration.php(155): json_decode('', true, 512, 4194304)
#1 /Users/ftpman/.composer/vendor/laravel/valet/cli/includes/facades.php(22): Valet\Configuration->read()
#2 /Users/ftpman/.composer/vendor/laravel/valet/cli/app.php(103): Facade::__callStatic('read', Array)
#3 /Users/ftpman/.composer/vendor/laravel/valet/cli/valet.php(4): require_once('/Volumes/Dados/...')
#4 {main}
  thrown in /Users/ftpman/.composer/vendor/laravel/valet/cli/Valet/Configuration.php on line 155
```

### Steps To Reproduce

I found this out after I upgraded valet from version 2.x to version 4.x, and for some reason, the `loopback` setting in the config.json file didn't exist (or never did, I don't know).

So after the upgrade, the `valet install` command threw an exception:
```
Warning: Undefined array key "loopback" in /Users/ftpman/.composer/vendor/laravel/valet/cli/Valet/Nginx.php on line 105
PHP Fatal error:  Uncaught TypeError: Valet\Site::aliasLoopback(): Argument #2 ($loopback) must be of type string, null given, called in /Users/ftpman/.composer/vendor/laravel/valet/cli/Valet/Nginx.php on line 108 and defined in /Users/ftpman/.composer/vendor/laravel/valet/cli/Valet/Site.php:831
Stack trace:
#0 /Users/ftpman/.composer/vendor/laravel/valet/cli/Valet/Nginx.php(108): Valet\Site->aliasLoopback('127.0.0.1', NULL)
#1 /Users/ftpman/.composer/vendor/laravel/valet/cli/Valet/Nginx.php(83): Valet\Nginx->rewriteSecureNginxFiles()
#2 /Users/ftpman/.composer/vendor/laravel/valet/cli/Valet/Nginx.php(28): Valet\Nginx->installNginxDirectory()
#3 /Users/ftpman/.composer/vendor/laravel/valet/cli/includes/facades.php(22): Valet\Nginx->install()
#4 /Users/ftpman/.composer/vendor/laravel/valet/cli/app.php(57): Facade::__callStatic('install', Array)
#5 [internal function]: Silly\Application->{closure}(Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /Users/ftpman/.composer/vendor/php-di/invoker/src/Invoker.php(74): call_user_func_array(Object(Closure), Array)
#7 /Users/ftpman/.composer/vendor/mnapoli/silly/src/Application.php(96): Invoker\Invoker->call(Object(Closure), Array)
#8 /Users/ftpman/.composer/vendor/symfony/console/Command/Command.php(310): Silly\Application->Silly\{closure}(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /Users/ftpman/.composer/vendor/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /Users/ftpman/.composer/vendor/symfony/console/Application.php(314): Symfony\Component\Console\Application->doRunCommand(Object(Silly\Command\Command), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /Users/ftpman/.composer/vendor/symfony/console/Application.php(168): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /Users/ftpman/.composer/vendor/laravel/valet/cli/valet.php(9): Symfony\Component\Console\Application->run()
#13 {main}
  thrown in /Users/ftpman/.composer/vendor/laravel/valet/cli/Valet/Site.php on line 831
```

**Analyzing the source code, I discovered that when there is no `loopback` or `tdl` config it would only be created if the file does not exist, however, when the file does not exist the valet cannot create it.**

### Diagnosis

<details>
<summary>sw_vers</summary>
<pre>ProductName:	Mac OS X
ProductVersion:	10.15.6
BuildVersion:	19G73</pre>
</details>
<details>
<summary>valet --version</summary>
<pre>Laravel Valet 4.0.1</pre>
</details>
<details>
<summary>cat ~/.config/valet/config.json</summary>
<pre>{
    "paths": []
}</pre>
</details>
<details>
<summary>cat ~/.composer/composer.json</summary>
<pre>{
    "require": {
        "laravel/valet": "^4.0"
    }
}</pre>
</details>
<details>
<summary>composer global diagnose</summary>
<pre>Changed current directory to /Users/ftpman/.composer
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
Checking platform settings: OK
Checking git settings: OK git version 2.24.3
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: You are not running the latest stable version, run `composer self-update` to update (2.5.4 => 2.5.5)
Composer version: 2.5.4
PHP version: 8.1.16
PHP binary path: /usr/local/Cellar/php@8.1/8.1.16/bin/php
OpenSSL version: OpenSSL 1.1.1t  7 Feb 2023
cURL version: 7.88.1 libz 1.2.11 ssl (SecureTransport) OpenSSL/1.1.1t
zip: extension present, unzip present, 7-Zip not available</pre>
</details>
<details>
<summary>composer global outdated</summary>
<pre>Changed current directory to /Users/ftpman/.composer
Info from https://repo.packagist.org: #StandWithUkraine

Direct dependencies required in composer.json:
Everything up to date

Transitive dependencies not required in composer.json:
Everything up to date</pre>
</details>
<details>
<summary>ls -al /etc/sudoers.d/</summary>
<pre>total 0
drwxr-xr-x   2 root  wheel    64  5 Jul  2020 .
drwxr-xr-x  97 root  wheel  3104 20 Abr 02:50 ..</pre>
</details>
<details>
<summary>brew config</summary>
<pre>HOMEBREW_VERSION: 4.0.14-80-g72bdefb
ORIGIN: https://github.com/Homebrew/brew
HEAD: 72bdefb814083854830ceb2d8adad2c4983f49c8
Last commit: 8 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 0adf50e0816080e5261f165e49660f5c540a0639
Core tap last commit: 24 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 4
HOMEBREW_NO_INSTALL_FROM_API: set
Homebrew Ruby: 2.6.10 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.10_1/bin/ruby
CPU: quad-core 64-bit kabylake
Clang: 12.0.0 build 1200
Git: 2.24.3 => /Users/ftpman/Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.6-x86_64
CLT: 12.2.0.0.1.1604628099
Xcode: 12.4 => /Users/ftpman/Applications/Xcode.app/Contents/Developer</pre>
</details>
<details>
<summary>brew services list</summary>
<pre>Name          Status User           File
dnsmasq       none            root           
httpd         none                           
mariadb       started         ftpman ~/Library/LaunchAgents/homebrew.mxcl.mariadb.plist
nginx         none                           
php@7.2       none                           
php@7.4       none                           
php@8.0       none                           
php@8.1       none            root           
postgresql@14 none</pre>
</details>
<details>
<summary>brew list --formula --versions | grep -E "(php|nginx|dnsmasq|mariadb|mysql|mailhog|openssl)(@\d\..*)?\s"</summary>
<pre>dnsmasq 2.82 2.85
mariadb 10.5.5
nginx 1.19.4
openssl@1.1 1.1.1t 1.1.1q
php 8.2.3
php@7.2 7.2.34_4
php@7.2-imap 7.2.33
php@7.4 7.4.33
php@8.0 8.0.28
php@8.1 8.1.16</pre>
</details>
<details>
<summary>brew outdated</summary>
<pre>ansible
ansible@2.9
apr
boost
c-ares
cmake
cocoapods
composer
curl
deployer
dnsmasq
double-conversion
fmt
folly
freetds
ghostscript
glib
glog
gnu-getopt
groonga
highway
htop
httpd
ilmbase
imagemagick
jansson
jemalloc
jpeg-xl
libde265
libffi
libheif
libidn
libomp
libuv
mariadb
meson
msgpack
ncurses
nghttp2
nginx
npm
ntfs-3g
openexr
openjpeg
openssl
php
kabel/php-ext/php-imap
php@8.1
pipx
postgresql@14
putty
pygments
python@3.10
python@3.11
python@3.8
python@3.9
shared-mime-info
six
snappy
sshfs
teleport
telnet
watchman
x265
zstd
adoptopenjdk11
keepassxc</pre>
</details>
<details>
<summary>brew tap</summary>
<pre>adoptopenjdk/openjdk
homebrew/cask
homebrew/core
homebrew/services
kabel/php-ext</pre>
</details>
<details>
<summary>php -v</summary>
<pre>PHP 8.1.16 (cli) (built: Mar 15 2023 06:02:37) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.16, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.16, Copyright (c), by Zend Technologies</pre>
</details>
<details>
<summary>which -a php</summary>
<pre>/usr/local/bin/php
/usr/bin/php</pre>
</details>
<details>
<summary>php --ini</summary>
<pre>Configuration File (php.ini) Path: /usr/local/etc/php/8.1
Loaded Configuration File:         /usr/local/etc/php/8.1/php.ini
Scan for additional .ini files in: /usr/local/etc/php/8.1/conf.d
Additional .ini files parsed:      /usr/local/etc/php/8.1/conf.d/ext-opcache.ini</pre>
</details>
<details>
<summary>nginx -v</summary>
<pre>nginx version: nginx/1.19.4</pre>
</details>
<details>
<summary>curl --version</summary>
<pre>curl 7.64.1 (x86_64-apple-darwin19.0) libcurl/7.64.1 (SecureTransport) LibreSSL/2.8.3 zlib/1.2.11 nghttp2/1.39.2
Release-Date: 2019-03-27
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS GSS-API HTTP2 HTTPS-proxy IPv6 Kerberos Largefile libz MultiSSL NTLM NTLM_WB SPNEGO SSL UnixSockets</pre>
</details>
<details>
<summary>php --ri curl</summary>
<pre>curl

cURL support => enabled
cURL Information => 7.88.1
Age => 10
Features
AsynchDNS => Yes
CharConv => No
Debug => No
GSS-Negotiate => No
IDN => Yes
IPv6 => Yes
krb4 => No
Largefile => Yes
libz => Yes
NTLM => Yes
NTLMWB => Yes
SPNEGO => Yes
SSL => Yes
SSPI => No
TLS-SRP => Yes
HTTP2 => Yes
GSSAPI => Yes
KERBEROS5 => Yes
UNIX_SOCKETS => Yes
PSL => No
HTTPS_PROXY => Yes
MULTI_SSL => Yes
BROTLI => Yes
Protocols => dict, file, ftp, ftps, gopher, gophers, http, https, imap, imaps, ldap, ldaps, mqtt, pop3, pop3s, rtmp, rtmpe, rtmps, rtmpt, rtmpte, rtmpts, rtsp, scp, sftp, smb, smbs, smtp, smtps, telnet, tftp
Host => x86_64-apple-darwin19.6.0
SSL Version => (SecureTransport) OpenSSL/1.1.1t
ZLib Version => 1.2.11
libSSH Version => libssh2/1.10.0

Directive => Local Value => Master Value
curl.cainfo => no value => no value</pre>
</details>
<details>
<summary>/usr/local/bin/ngrok version</summary>
<pre>sudo: /usr/local/bin/ngrok: command not found</pre>
</details>
<details>
<summary>ls -al ~/.ngrok2</summary>
<pre>ls: /Users/ftpman/.ngrok2: No such file or directory</pre>
</details>
<details>
<summary>brew info nginx</summary>
<pre>==> nginx: stable 1.23.4, HEAD
HTTP(S) server and reverse proxy, and IMAP/POP3 proxy server
https://nginx.org/
/usr/local/Cellar/nginx/1.19.4 (25 files, 2.2MB) *
  Poured from bottle on 2020-11-17 at 14:27:23
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/nginx.rb
License: BSD-2-Clause
==> Dependencies
Required: openssl@1.1, pcre2
==> Options
--HEAD
	Install HEAD version
==> Caveats
Docroot is: /usr/local/var/www

The default port has been set in /usr/local/etc/nginx/nginx.conf to 8080 so that
nginx can run without sudo.

nginx will load all files in /usr/local/etc/nginx/servers/.

To restart nginx after an upgrade:
  brew services restart nginx
Or, if you don't want/need a background service you can just run:
  /usr/local/opt/nginx/bin/nginx -g daemon off;
==> Analytics
install: 1,537 (30 days), 44,848 (90 days), 390,534 (365 days)
install-on-request: 1,533 (30 days), 44,788 (90 days), 389,893 (365 days)
build-error: 2 (30 days)</pre>
</details>
<details>
<summary>brew info php</summary>
<pre>==> php: stable 8.2.5, HEAD
General-purpose scripting language
https://www.php.net/
/usr/local/Cellar/php/8.2.3 (511 files, 81.7MB)
  Built from source on 2023-03-15 at 03:16:30
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/php.rb
License: PHP-3.01
==> Dependencies
Build: httpd, pkg-config
Required: apr, apr-util, argon2, aspell, autoconf, curl, freetds, gd, gettext, gmp, icu4c, krb5, libpq, libsodium, libzip, oniguruma, openldap, openssl@1.1, pcre2, sqlite, tidy-html5, unixodbc
==> Options
--HEAD
	Install HEAD version
==> Caveats
To enable PHP in Apache add the following to httpd.conf and restart Apache:
    LoadModule php_module /usr/local/opt/php/lib/httpd/modules/libphp.so

    <FilesMatch \.php$>
        SetHandler application/x-httpd-php
    </FilesMatch>

Finally, check DirectoryIndex includes index.php
    DirectoryIndex index.php index.html

The php.ini and php-fpm.ini file can be found in:
    /usr/local/etc/php/8.2/

To restart php after an upgrade:
  brew services restart php
Or, if you don't want/need a background service you can just run:
  /usr/local/opt/php/sbin/php-fpm --nodaemonize
==> Analytics
install: 2,099 (30 days), 169,992 (90 days), 1,282,019 (365 days)
install-on-request: 1,928 (30 days), 151,033 (90 days), 1,118,915 (365 days)
build-error: 0 (30 days)</pre>
</details>
<details>
<summary>brew info openssl</summary>
<pre>==> openssl@3: stable 3.1.0 [keg-only]
Cryptography and SSL/TLS Toolkit
https://openssl.org/
/usr/local/Cellar/openssl@3/3.0.1 (6,420 files, 28.2MB)
  Poured from bottle on 2022-03-12 at 00:27:44
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/openssl@3.rb
License: Apache-2.0
==> Dependencies
Required: ca-certificates
==> Caveats
A CA file has been bootstrapped using certificates from the system
keychain. To add additional certificates, place .pem files in
  /usr/local/etc/openssl@3/certs

and run
  /usr/local/opt/openssl@3/bin/c_rehash

openssl@3 is keg-only, which means it was not symlinked into /usr/local,
because macOS provides LibreSSL.
==> Analytics
install: 5,977 (30 days), 580,933 (90 days), 2,188,147 (365 days)
install-on-request: 2,707 (30 days), 129,174 (90 days), 1,141,355 (365 days)
build-error: 598 (30 days)</pre>
</details>
<details>
<summary>openssl version -a</summary>
<pre>LibreSSL 2.8.3
built on: date not available
platform: information not available
options:  bn(64,64) rc4(16x,int) des(idx,cisc,16,int) blowfish(idx) 
compiler: information not available
OPENSSLDIR: "/private/etc/ssl"</pre>
</details>
<details>
<summary>openssl ciphers</summary>
<pre>ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-CHACHA20-POLY1305:GOST2012256-GOST89-GOST89:DHE-RSA-CAMELLIA256-SHA256:DHE-RSA-CAMELLIA256-SHA:GOST2001-GOST89-GOST89:AES256-GCM-SHA384:AES256-SHA256:AES256-SHA:CAMELLIA256-SHA256:CAMELLIA256-SHA:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-CAMELLIA128-SHA256:DHE-RSA-CAMELLIA128-SHA:AES128-GCM-SHA256:AES128-SHA256:AES128-SHA:CAMELLIA128-SHA256:CAMELLIA128-SHA:ECDHE-RSA-RC4-SHA:ECDHE-ECDSA-RC4-SHA:RC4-SHA:RC4-MD5:ECDHE-RSA-DES-CBC3-SHA:ECDHE-ECDSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:DES-CBC3-SHA</pre>
</details>
<details>
<summary>sudo nginx -t</summary>
<pre>nginx: [emerg] no host in ":80" of the "listen" directive in /usr/local/etc/nginx/valet/valet.conf:3
nginx: configuration file /usr/local/etc/nginx/nginx.conf test failed</pre>
</details>
<details>
<summary>which -a php-fpm</summary>
<pre>/usr/local/sbin/php-fpm
/usr/sbin/php-fpm</pre>
</details>
<details>
<summary>/usr/local/opt/php/sbin/php-fpm -v</summary>
<pre>PHP 8.2.3 (fpm-fcgi) (built: Mar 15 2023 06:15:09)
Copyright (c) The PHP Group
Zend Engine v4.2.3, Copyright (c) Zend Technologies</pre>
</details>
<details>
<summary>sudo /usr/local/opt/php/sbin/php-fpm -y /usr/local/etc/php/8.1/php-fpm.conf --test</summary>
<pre>[20-Apr-2023 14:55:03] NOTICE: configuration file /usr/local/etc/php/8.1/php-fpm.conf test is successful</pre>
</details>
<details>
<summary>ls -al ~/Library/LaunchAgents | grep homebrew</summary>
<pre>-rw-r--r--   1 ftpman  staff   541 15 Nov  2021 homebrew.mxcl.mariadb.plist</pre>
</details>
<details>
<summary>ls -al /Library/LaunchAgents | grep homebrew</summary>
<pre></pre>
</details>
<details>
<summary>ls -al /Library/LaunchDaemons | grep homebrew</summary>
<pre>-rw-r--r--   1 root  admin   593 20 Abr 11:34 homebrew.mxcl.dnsmasq.plist
-rw-r--r--   1 root  admin   780 20 Abr 11:34 homebrew.mxcl.php@8.1.plist</pre>
</details>
<details>
<summary>ls -al /Library/LaunchDaemons | grep "com.laravel.valet."</summary>
<pre></pre>
</details>
<details>
<summary>ls -aln /etc/resolv.conf</summary>
<pre>lrwxr-xr-x  1 0  0  22  2 Ago  2020 /etc/resolv.conf -> ../var/run/resolv.conf</pre>
</details>
<details>
<summary>cat /etc/resolv.conf</summary>
<pre>#
# macOS Notice
#
# This file is not consulted for DNS hostname resolution, address
# resolution, or the DNS query routing mechanism used by most
# processes on this system.
#
# To view the DNS configuration used by this system, use:
#   scutil --dns
#
# SEE ALSO
#   dns-sd(1), scutil(8)
#
# This file is automatically generated.
#
nameserver 8.8.8.8
nameserver 8.8.4.4</pre>
</details>
<details>
<summary>ifconfig lo0</summary>
<pre>lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> mtu 16384
	options=1203<RXCSUM,TXCSUM,TXSTATUS,SW_TIMESTAMP>
	inet 127.0.0.1 netmask 0xff000000 
	inet6 ::1 prefixlen 128 
	inet6 fe80::1%lo0 prefixlen 64 scopeid 0x1 
	nd6 options=201<PERFORMNUD,DAD></pre>
</details>
<details>
<summary>sh -c 'echo "------\n/usr/local/etc/nginx/valet/valet.conf\n---\n"; cat /usr/local/etc/nginx/valet/valet.conf | grep -n "# valet loopback"; echo "\n------\n"'</summary>
<pre>------
/usr/local/etc/nginx/valet/valet.conf
---

3:    listen :80; # valet loopback

------</pre>
</details>
<details>
<summary>sh -c 'for file in ~/.config/valet/dnsmasq.d/*; do echo "------\n~/.config/valet/dnsmasq.d/$(basename $file)\n---\n"; cat $file; echo "\n------\n"; done'</summary>
<pre>------
~/.config/valet/dnsmasq.d/tld-test.conf
---

address=/.test/127.0.0.1
listen-address=127.0.0.1

------</pre>
</details>
<details>
<summary>sh -c 'for file in ~/.config/valet/nginx/*; do echo "------\n~/.config/valet/nginx/$(basename $file)\n---\n"; cat $file | grep -n "# valet loopback"; echo "\n------\n"; done'</summary>
<pre>------
~/.config/valet/nginx/*
---

cat: /Users/ftpman/.config/valet/nginx/*: No such file or directory

------</pre>
</details>

**Comment by mattstauffer** [comment]
Thanks for the report! I think I've fixed it here: https://github.com/laravel/valet/pull/1415
