### ISSUE TITLE
Valet response too long

### ISSUE THREAD

**Issue by ahmedash95** [laravel/valet#141]
Hi , i'm using valet for about one month but sometimes it takes about more than 1 minute to respond event if i'm just returning "Hello World!" , i'm trying to figure out the problem but nothing until now , any idea ? 

* updates :  when i use file_get_contents() it take so long

**Comment by adamwathan** [comment]
Still running into this issue? It sounds like maybe an issue with the application more than Valet. Going to close as not-valet related but happy to help if I can.
