### ISSUE TITLE
Platform check brakes valet on older PHP versions (<8.1)

### ISSUE THREAD

**Issue by mischabraam** [laravel/valet#1417]
### Description

I did a clean install of valet (first removed everything, including composer, caches, aka everything) following the instructions on https://laravel.com/docs/10.x/valet#installation 
In Brew the default php version is 8.2. So `brew install php` installs php 8.2. When installing valet with `composer global require laravel/valet` it install valet including dependencies. The dependencies are installed using php 8.2.
I can successfully switch to php 8.0 using `valet use 8.0`. But from that point valet is broken. The installed dependencies for php 8.2 and platform check makes it impossible to use any `valet` command. Doing so will give the following fatal error.
```
Fatal error: Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.1.0". You are running 8.0.28. in /Users/piet/.composer/vendor/composer/platform_check.php on line 24
```

### Steps To Reproduce

Follow installation 
- `brew install composer`
- make sure the `~/.composer/vendor/bin` directory is in your system's "PATH"
- `brew update`
- `brew install php` (install 8.2)
- `composer global require laravel/valet`
- `valet install`
- `valet use 8.0`
- `valet` < broken with fatal error

### Diagnosis

`valet diagnose` can't be run at this point.

### Github actions

I see that Github actions are in place to test php 8.2, 8.1 and 8.0. These tests though are not in line with the install instructions. The 8.0 test first installs php 8.0, then installs valet. Doing it in this order will install dependencies compatible with php 8.0 instead of 8.2. 
However, if you do this (install php 8.0 and then install valet) I can successfully switch between all php versions. 

See screenshot

![Screenshot_2023-05-22_at_14_04_17](https://github.com/laravel/valet/assets/19824986/c070c2ef-c705-4f62-b9e2-5a2df17253b5)

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!

**Comment by bjuppa** [comment]
I ended up in same state, couldn't run `valet` command at all after `valet use 8.0`.

However, it seems I got my setup back after doing `brew upgrade`, that reinstalled php 8.2 🤷
