### ISSUE TITLE
Repeated rapid POST requests kill Valet on macOS Sierra

### ISSUE THREAD

**Issue by eklundkristoffer** [laravel/valet#142]
Hello. So, I install a new laravel app with the ```laravel new``` command. After that I run ```php artisan make:auth``` & then ```php artisan migrate``` after editing the .env with my connection details. 

So, I navigate to /login route and enter a email, and a random password, submit and do that like 1-15 times, until valet just freezing and I have to stop it or valet just dies itself and I have to start it again. There is no actual error, the only "error" I get is in the access.log, and it looks like:

```
127.0.0.1 - [10/Sep/2016:00:58:38 +0200] "GET /login HTTP/1.1" 200 4755
127.0.0.1 - [10/Sep/2016:00:58:38 +0200] "GET /css/app.css HTTP/1.1" 200 116158
127.0.0.1 - [10/Sep/2016:00:58:38 +0200] "GET /js/app.js HTTP/1.1" 200 294259
127.0.0.1 - [10/Sep/2016:00:58:38 +0200] "GET /favicon.ico HTTP/1.1" 200 0
127.0.0.1 - [10/Sep/2016:00:58:39 +0200] "POST /login HTTP/1.1" 302 328
-------1-------2-------7-------.-------0-------.-------0-------.-------1------- --------------- -------[-------1-------0-------/-------S-------e-------p-------/-------2-------0-------1-------6-------:-------0-------0-------:-------5-------8-------:-------3-------9------- -------+-------0-------2-------0-------0-------]------- -------"-------G-------E-------T------- -------/-------l-------o-------g-------i-------n------- -------H-------T-------T-------P-------/-------1-------.-------1-------"------- -------2-------0-------0------- -------{-------s-------i-------z-------e-------}-------
```
Worth to mention, I have tried with both mariadb setup & sqlite, also uninstalled & installed valet. Still the same. Do anyone have any idea what can possibly cause this? Thanks! 

EDIT: And sometimes it adds the text "Internal Server Error" to the bottom of the page, it stays there even if i reload the page. https://drops.blogster.se/QkSypk3lo6.png

EDIT2: Forgot to mention, I am running macOS Sierra version 10.12 beta (16A313a).

**Comment by drbyte** [comment]
> I navigate to /login route and enter a email, and a random password, submit and do that like 1-15 times

1. Why are you doing that? 

2. I can't make Valet crash when trying that.
Then again, I'm not usually in the habit of repeatedly intentionally entering random invalid credentials on my local PC.

**Comment by eklundkristoffer** [comment]
@drbyte , Thanks for you answer and taking the time to test if you could reproduce it.

1: I was testing the ThrottlesLogin, had a problem with the lock time resetting to fast when I noticed the problem.

2: A friend of mine were testing on his machine and could not either reproduce it.

**Comment by eklundchristopher** [comment]
I can confirm this issue after setting it up on my MacBook Pro Early 2011, using macOS 10.12 Sierra Beta (16A293a). However it is worth noting that Homebrew doesn't officially support the beta version of Sierra and I will therefore upgrade to the latest RC and see if the issue persists. I'll report back once I've verified.

_PS. I know me and @eklundkristoffer share VERY similar names, but I can assure you we are two different people. ;-)_

**Comment by adamwathan** [comment]
Which version of Caddy are you using? I know the version we currently ship has issues under Sierra, but we can't update Valet's version of Caddy until other bugs in the latest Caddy are fixed.

**Comment by eklundchristopher** [comment]
```bash
$ brew info caddy
caddy: stable 0.9.1 (bottled), HEAD
```

Works fine on my El Capitan installation, but not on Sierra. I personally don't use Sierra as part of my development setup, but @eklundkristoffer asked me to try it out on my Sierra installation simply to confirm.

**Comment by eklundkristoffer** [comment]
```
$ brew info caddy
caddy: stable 0.9.1, HEAD
```

**Comment by adamwathan** [comment]
What does:

`~/.composer/vendor/laravel/valet/bin/caddy -version`

...report? That's the binary Valet is using, so unless it's been overridden with the version installed via brew, the version installed via brew could be different.

We ship Valet with Caddy 0.8.3.

**Comment by eklundkristoffer** [comment]
It gives:
```
$ ~/.composer/vendor/laravel/valet/bin/caddy -version
Caddy 0.8.3
```

**Comment by adamwathan** [comment]
So that version of Caddy is known to not properly support macOS Sierra, but 0.9.x doesn't support the latest Valet features. We haven't tagged a release that includes features that don't work with 0.9.x yet, so if you want to, you can replace Caddy binary in `~/.composer/vender/laravel/valet/bin` with the one from Homebrew, and you might have better luck.

That will break whenever you update Valet and will need to be manually maintained until we actually have an official version of Valet tagged that is compatible with Sierra.

Can follow the instructions here:

https://murze.be/2016/08/fixing-laravel-valet-macos-sierra/

**Comment by eklundchristopher** [comment]
Yeah, the latest version of Sierra made no difference. Which in itself makes perfect sense after what you've mentioned around Caddy already. Thought I'd share though.

**Comment by eklundkristoffer** [comment]
Thanks @adamwathan , it did fix it!

**Comment by adamwathan** [comment]
Cool! Gonna close this then, hopefully Caddy 0.9.x will fix what we need fixed by the time Sierra is officially released and we can roll out an official Sierra-ready version of Valet then.
