### ISSUE TITLE
Ngrok not finding authtoken

### ISSUE THREAD

**Issue by whoacowboy** [laravel/valet#1432]
### Description

When I set the auth token ngrok does not recognize it.

```
valet set-ngrok-token SUPERSECRTETAUTHTOKEN
Authtoken saved to configuration file: /Users/james/.ngrok2/ngrok.yml
```

When I run 
```
valet share -hostname=sub.example.com -region=us;
```
I get the error

```
Please sign up for a free ngrok account and then run valet set-ngrok-token {yourTokenHere}.
```

### Steps To Reproduce

I did a fresh update, install and restart of valet. Restarted my computer a couple of times and the issue persisted.

I install of ngrok from the ngrok.com and not brew but the ngrok install and the brew install land them in the same directory which is the same as `brew --prefix`

I set the authtoken with the ngrok command as well as the valet command.
```
ngrok config add-authtoken SUPERSECRTETAUTHTOKEN
```

So it could be my bad.

### Diagnosis

The only thing that makes me think it might be an issue with valet and not my setup is this. When I comment out the [token check](https://github.com/laravel/valet/blob/c7ace590baeb7130e3664b8e56dd1f68dbf9cc2d/valet#L57C1-L60C11) in `~/.composer/vendor/laravel/valet/valet` works fine.

```
        BREW_PREFIX=$(brew --prefix)
        $($BREW_PREFIX/bin/ngrok config check >/dev/null 2>&1)

#        if [[ $? -ne 0 ]]; then
#            echo "Please sign up for a free ngrok account and then run valet set-ngrok-token {yourTokenHere}."
#            exit
#        fi
```

**Comment by drbyte** [comment]
Do you get any errors when running `ngrok config check` directly?

If it gives you an error like the following, then run `ngrok config upgrade`:
```sh
ERROR:  Error reading configuration file '/Users/username/.ngrok2/ngrok.yml': `version` property is required.
ERROR:
ERROR:  If you're upgrading from an older version of ngrok, you can run:
ERROR:
ERROR:      ngrok config upgrade
ERROR:
ERROR:  to upgrade to the new format and add the version number.
```

If it also gives you the following message about relocating, then you could optionally consider also running `ngrok config upgrade --relocate`:
```sh
Run this command with the --relocate flag to move your config file to the default location
```

After that, does the authtoken error persist?

**Comment by whoacowboy** [comment]
I ended up uninstalling and reinstalling most everything, Ngrok, valet and the problem resolved.
