### ISSUE TITLE
"Domain" should maybe be "TLD"?

### ISSUE THREAD

**Issue by mattstauffer** [laravel/valet#144]
Every time I read the command `domain` I think it has to do with the domain (e.g. `burgermergency`) of the folder I'm in. When I think of the "ending" (.com, .net, etc.) I think of that as the `TLD`.

I want to ask before I PR, because I don't know if everyone else thinks of this different from me. But I'd propose changing `domain` to `tld` so it's clearer that it's not talking about the domain of the current folder you're in, but instead your global `tld` for Valet.

Thoughts?

**Comment by drbyte** [comment]
Makes sense to me. I wouldn't be bothered by the change.

Would probably be smart to keep `domain` as a valid alias to `tld` since lots of older documentation (blog articles etc) for valet exists around the web already.

**Comment by michaeljhopkins** [comment]
I agree with the pr, but disagree with drbyte's response. If it was my choice, I'd prefer

  * `valet tld` - Get or set the domain used for Valet sites
  * `valet domain` - Get or set the domain used for the previously linked current working directory

**Comment by taylorotwell** [comment]
Would be open to this if someone wants to PR.
