### ISSUE TITLE
Any error in the system gives a 502 Gateway error and php-fpm.log file size in increased by ~1.1gb

### ISSUE THREAD

**Issue by sarik-k** [laravel/valet#1442]
### Description

I have been having this issue for the past couple of days

Whenever I get an error in my application, instead of getting an Ignition page, it just keeps loading and I eventually get a 502 Bad Gateway. At first I thought it was an issue with nginx, I checked the log file, nothing. 

I uninstalled valet completely and reinstalled it again, I ran `brew doctor` followed by `brew cleanup`, nothing fixed it. 

After a while, my mac started complaining that it was running out of space. 

I installed a disk analyzer, and the `~/.config/valet/Logs/php-fpm.log` was a whopping 188gb!

I didn't even try to open it, fearing my laptop would just crash. Deleted it. 

Now I have this route in my application: 
`Route::get('error', fn() => abort(500, 'Custom Server Error'));`

If I delete the php-fpm.log file and visit this route, I get 502 Bad Gateway error and a new 1.1gb php-fpm.log file is created. 
I opened it with `less php-fpm.log` and this is the first few lines of the error: 

```
[07-Sep-2023 07:30:59 UTC] PHP Warning:  Uncaught Symfony\Component\HttpKernel\Exception\HttpException: Custom Server Error in /Users/.../vendor/laravel/framework/src/Illuminate/Foundation/Application.php:1147
Stack trace:
#0 /Users/.../vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(45): Illuminate\Foundation\Application->abort(500, 'Custom Server E...', Array)
#1 /Users/.../routes/web.php(33): abort(500, 'Custom Server E...')
#2 /Users/.../vendor/laravel/framework/src/Illuminate/Routing/CallableDispatcher.php(40): Illuminate\Routing\RouteFileRegistrar->{closure}()
#3 /Users/.../vendor/laravel/framework/src/Illuminate/Routing/Route.php(237): Illuminate\Routing\CallableDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Closure))
#4 /Users/.../vendor/laravel/framework/src/Illuminate/Routing/Route.php(208): Illuminate\Routing\Route->runCallable()
#5 /Users/.../vendor/laravel/framework/src/Illuminate/Routing/Router.php(798): Illuminate\Routing\Route->run()
#6 /Users/.../vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#7 /Users/.../vendor/laravel/framework/src/Illuminate/Http/Middleware/AddLinkHeadersForPreloadedAssets.php(19): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
```
What can I do to solve this? I have tried everything I can find on the internet

I checked the same repo on my colleague's computer, its working fine

### Steps To Reproduce

Mentioned above

### Diagnosis

<details>
<summary>sw_vers</summary>
<pre>ProductName:		macOS
ProductVersion:		13.5.1
BuildVersion:		22G90</pre>
</details>
<details>
<summary>valet --version</summary>
<pre>Laravel Valet 4.3.0</pre>
</details>
<details>
<summary>cat ~/.config/valet/config.json</summary>
<pre>{
    "tld": "test",
    "loopback": "127.0.0.1",
    "paths": [
        "/Users/matat/code"
    ]
}</pre>
</details>
<details>
<summary>cat ~/.composer/composer.json</summary>
<pre>{
    "require": {
        "beyondcode/expose": "^2.6",
        "laravel/installer": "^4.5",
        "laravel/valet": "^4.3"
    },
    "require-dev": {
        "squizlabs/php_codesniffer": "^3.7"
    }
}</pre>
</details>
<details>
<summary>composer global diagnose</summary>
<pre>Changed current directory to /Users/matat/.composer
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
Checking platform settings: OK
Checking git settings: OK git version 2.41.0
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: You are not running the latest stable version, run `composer self-update` to update (2.5.5 => 2.6.2)
Composer version: 2.5.5
PHP version: 8.2.10
PHP binary path: /Users/matat/Library/Application Support/Herd/bin/php82
OpenSSL version: OpenSSL 3.1.2 1 Aug 2023
cURL version: 8.2.1 libz 1.3 ssl OpenSSL/3.1.2
zip: extension present, unzip present, 7-Zip not available</pre>
</details>
<details>
<summary>composer global outdated</summary>
<pre>Changed current directory to /Users/matat/.composer
Info from https://repo.packagist.org: #StandWithUkraine
Legend:
! patch or minor release available - update recommended
~ major release available - update possible

Direct dependencies required in composer.json:
laravel/installer                v4.5.0  ~ v5.1.0  Laravel application insta...

Transitive dependencies not required in composer.json:
laravel-zero/phar-updater        v1.3.0  ! v1.4.0  A thing to make PHAR self...
psr/container                    1.1.2   ~ 2.0.2   Common Container Interfac...
symfony/console                  v5.4.24 ~ v6.3.4  Eases the creation of bea...
symfony/deprecation-contracts    v2.5.2  ~ v3.3.0  A generic function and co...
symfony/polyfill-ctype           v1.27.0 ! v1.28.0 Symfony polyfill for ctyp...
symfony/polyfill-intl-grapheme   v1.27.0 ! v1.28.0 Symfony polyfill for intl...
symfony/polyfill-intl-normalizer v1.27.0 ! v1.28.0 Symfony polyfill for intl...
symfony/polyfill-mbstring        v1.27.0 ! v1.28.0 Symfony polyfill for the ...
symfony/polyfill-php73           v1.27.0 ! v1.28.0 Symfony polyfill backport...
symfony/polyfill-php80           v1.27.0 ! v1.28.0 Symfony polyfill backport...
symfony/process                  v5.4.24 ~ v6.3.4  Executes commands in sub-...
symfony/service-contracts        v2.5.2  ~ v3.3.0  Generic abstractions rela...
symfony/string                   v5.4.22 ~ v6.3.2  Provides an object-orient...</pre>
</details>
<details>
<summary>ls -al /etc/sudoers.d/</summary>
<pre>total 8
drwxr-xr-x   3 root  wheel    96 Sep  7 12:09 .
drwxr-xr-x  81 root  wheel  2592 Sep  7 12:16 ..
-rw-r--r--   1 root  wheel   110 Sep  7 12:09 herd</pre>
</details>
<details>
<summary>brew config</summary>
<pre>HOMEBREW_VERSION: 4.1.9
ORIGIN: https://github.com/Homebrew/brew
HEAD: b0985dabec8517ab5afda7cfee7d59f1da4ed6ce
Last commit: 2 days ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 5df27fbb71a5d61a497cc40e55ec2f8cf80b0fcd
Core tap last commit: 15 minutes ago
Core tap branch: master
Core tap JSON: 07 Sep 07:35 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit kabylake
Clang: 14.0.3 build 1403
Git: 2.41.0 => /usr/local/bin/git
Curl: 8.1.2 => /usr/bin/curl
macOS: 13.5.1-x86_64
CLT: 14.3.1.0.1.1683849156
Xcode: N/A</pre>
</details>
<details>
<summary>brew services list</summary>
<pre>Name    Status User  File
dnsmasq none            root  
mariadb started         matat ~/Library/LaunchAgents/homebrew.mxcl.mariadb.plist
nginx   none            root  
php     none            root</pre>
</details>
<details>
<summary>brew list --formula --versions | grep -E "(php|nginx|dnsmasq|mariadb|mysql|mailhog|openssl)(@\d\..*)?\s"</summary>
<pre>dnsmasq 2.89
mariadb 11.1.2
nginx 1.25.2
openssl@1.1 1.1.1v
php 8.2.10</pre>
</details>
<details>
<summary>brew outdated</summary>
<pre>git
groonga
rtmpdump
sqlite
ngrok
sequel-ace</pre>
</details>
<details>
<summary>brew tap</summary>
<pre>cloudflare/cloudflare
homebrew/cask-versions
homebrew/core
homebrew/services
kabel/php-ext
shivammathur/php</pre>
</details>
<details>
<summary>php -v</summary>
<pre>PHP 8.2.10 (cli) (built: Sep  1 2023 00:29:22) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.10, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.10, Copyright (c), by Zend Technologies</pre>
</details>
<details>
<summary>which -a php</summary>
<pre>/Users/matat/Library/Application Support/Herd/bin//php
/usr/local/bin/php
/usr/local/bin/php
/usr/local/bin/php</pre>
</details>
<details>
<summary>php --ini</summary>
<pre>Configuration File (php.ini) Path: /lib
Loaded Configuration File:         (none)
Scan for additional .ini files in: (none)
Additional .ini files parsed:      (none)</pre>
</details>
<details>
<summary>nginx -v</summary>
<pre>nginx version: nginx/1.25.2</pre>
</details>
<details>
<summary>curl --version</summary>
<pre>curl 8.1.2 (x86_64-apple-darwin22.0) libcurl/8.1.2 (SecureTransport) LibreSSL/3.3.6 zlib/1.2.11 nghttp2/1.51.0
Release-Date: 2023-05-30
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS GSS-API HSTS HTTP2 HTTPS-proxy IPv6 Kerberos Largefile libz MultiSSL NTLM NTLM_WB SPNEGO SSL threadsafe UnixSockets</pre>
</details>
<details>
<summary>php --ri curl</summary>
<pre>curl

cURL support => enabled
cURL Information => 8.2.1
Age => 10
Features
AsynchDNS => Yes
CharConv => No
Debug => No
GSS-Negotiate => No
IDN => No
IPv6 => Yes
krb4 => No
Largefile => Yes
libz => Yes
NTLM => Yes
NTLMWB => No
SPNEGO => No
SSL => Yes
SSPI => No
TLS-SRP => No
HTTP2 => No
GSSAPI => No
KERBEROS5 => No
UNIX_SOCKETS => Yes
PSL => No
HTTPS_PROXY => Yes
MULTI_SSL => No
BROTLI => No
ALTSVC => Yes
HTTP3 => No
UNICODE => No
ZSTD => No
HSTS => Yes
GSASL => No
Protocols => dict, file, ftp, ftps, gopher, gophers, http, https, imap, imaps, mqtt, pop3, pop3s, rtsp, smb, smbs, smtp, smtps, telnet, tftp
Host => Darwin
SSL Version => OpenSSL/3.1.2
ZLib Version => 1.3

Directive => Local Value => Master Value
curl.cainfo => no value => no value</pre>
</details>
<details>
<summary>/usr/local/bin/ngrok version</summary>
<pre>ngrok version 3.3.1</pre>
</details>
<details>
<summary>ls -al ~/.ngrok2</summary>
<pre>ls: /Users/matat/.ngrok2: No such file or directory</pre>
</details>
<details>
<summary>brew info nginx</summary>
<pre>==> nginx: stable 1.25.2 (bottled), HEAD
HTTP(S) server and reverse proxy, and IMAP/POP3 proxy server
https://nginx.org/
/usr/local/Cellar/nginx/1.25.2 (26 files, 2.4MB) *
  Poured from bottle using the formulae.brew.sh API on 2023-09-07 at 12:23:07
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/n/nginx.rb
License: BSD-2-Clause
==> Dependencies
Required: openssl@3, pcre2
==> Options
--HEAD
	Install HEAD version
==> Caveats
Docroot is: /usr/local/var/www

The default port has been set in /usr/local/etc/nginx/nginx.conf to 8080 so that
nginx can run without sudo.

nginx will load all files in /usr/local/etc/nginx/servers/.

To start nginx now and restart at login:
  brew services start nginx
Or, if you don't want/need a background service you can just run:
  /usr/local/opt/nginx/bin/nginx -g daemon\ off\;
==> Analytics
install: 19,320 (30 days), 55,642 (90 days), 103,061 (365 days)
install-on-request: 19,293 (30 days), 55,555 (90 days), 102,910 (365 days)
build-error: 4 (30 days)</pre>
</details>
<details>
<summary>brew info php</summary>
<pre>==> php: stable 8.2.10 (bottled), HEAD
General-purpose scripting language
https://www.php.net/
/usr/local/Cellar/php/8.2.10 (520 files, 81.6MB) *
  Poured from bottle using the formulae.brew.sh API on 2023-09-07 at 13:01:50
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/p/php.rb
License: PHP-3.01
==> Dependencies
Build: httpd, pkg-config
Required: apr, apr-util, argon2, aspell, autoconf, curl, freetds, gd, gettext, gmp, icu4c, krb5, libpq, libsodium, libzip, oniguruma, openldap, openssl@3, pcre2, sqlite, tidy-html5, unixodbc
==> Options
--HEAD
	Install HEAD version
==> Caveats
To enable PHP in Apache add the following to httpd.conf and restart Apache:
    LoadModule php_module /usr/local/opt/php/lib/httpd/modules/libphp.so

    <FilesMatch \.php$>
        SetHandler application/x-httpd-php
    </FilesMatch>

Finally, check DirectoryIndex includes index.php
    DirectoryIndex index.php index.html

The php.ini and php-fpm.ini file can be found in:
    /usr/local/etc/php/8.2/

To start php now and restart at login:
  brew services start php
Or, if you don't want/need a background service you can just run:
  /usr/local/opt/php/sbin/php-fpm --nodaemonize
==> Analytics
install: 58,137 (30 days), 161,470 (90 days), 295,094 (365 days)
install-on-request: 53,923 (30 days), 149,909 (90 days), 273,550 (365 days)
build-error: 49 (30 days)</pre>
</details>
<details>
<summary>brew info openssl</summary>
<pre>==> openssl@3: stable 3.1.2 (bottled)
Cryptography and SSL/TLS Toolkit
https://openssl.org/
/usr/local/Cellar/openssl@3/3.1.2 (6,495 files, 30.0MB) *
  Poured from bottle using the formulae.brew.sh API on 2023-08-30 at 15:18:53
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/o/openssl@3.rb
License: Apache-2.0
==> Dependencies
Required: ca-certificates
==> Caveats
A CA file has been bootstrapped using certificates from the system
keychain. To add additional certificates, place .pem files in
  /usr/local/etc/openssl@3/certs

and run
  /usr/local/opt/openssl@3/bin/c_rehash
==> Analytics
install: 391,696 (30 days), 1,060,827 (90 days), 1,482,839 (365 days)
install-on-request: 36,770 (30 days), 151,503 (90 days), 289,378 (365 days)
build-error: 1,597 (30 days)</pre>
</details>
<details>
<summary>openssl version -a</summary>
<pre>OpenSSL 3.1.2 1 Aug 2023 (Library: OpenSSL 3.1.2 1 Aug 2023)
built on: Tue Aug  1 13:36:55 2023 UTC
platform: darwin64-x86_64-cc
options:  bn(64,64)
compiler: clang -fPIC -arch x86_64 -O3 -Wall -DL_ENDIAN -DOPENSSL_PIC -D_REENTRANT -DOPENSSL_BUILDING_OPENSSL -DNDEBUG
OPENSSLDIR: "/usr/local/etc/openssl@3"
ENGINESDIR: "/usr/local/Cellar/openssl@3/3.1.2/lib/engines-3"
MODULESDIR: "/usr/local/Cellar/openssl@3/3.1.2/lib/ossl-modules"
Seeding source: os-specific
CPUINFO: OPENSSL_ia32cap=0x7ffaf3bfffebffff:0x29c67af</pre>
</details>
<details>
<summary>openssl ciphers</summary>
<pre>TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:DHE-RSA-AES256-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES256-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES128-SHA:DHE-RSA-AES128-SHA:RSA-PSK-AES256-GCM-SHA384:DHE-PSK-AES256-GCM-SHA384:RSA-PSK-CHACHA20-POLY1305:DHE-PSK-CHACHA20-POLY1305:ECDHE-PSK-CHACHA20-POLY1305:AES256-GCM-SHA384:PSK-AES256-GCM-SHA384:PSK-CHACHA20-POLY1305:RSA-PSK-AES128-GCM-SHA256:DHE-PSK-AES128-GCM-SHA256:AES128-GCM-SHA256:PSK-AES128-GCM-SHA256:AES256-SHA256:AES128-SHA256:ECDHE-PSK-AES256-CBC-SHA384:ECDHE-PSK-AES256-CBC-SHA:SRP-RSA-AES-256-CBC-SHA:SRP-AES-256-CBC-SHA:RSA-PSK-AES256-CBC-SHA384:DHE-PSK-AES256-CBC-SHA384:RSA-PSK-AES256-CBC-SHA:DHE-PSK-AES256-CBC-SHA:AES256-SHA:PSK-AES256-CBC-SHA384:PSK-AES256-CBC-SHA:ECDHE-PSK-AES128-CBC-SHA256:ECDHE-PSK-AES128-CBC-SHA:SRP-RSA-AES-128-CBC-SHA:SRP-AES-128-CBC-SHA:RSA-PSK-AES128-CBC-SHA256:DHE-PSK-AES128-CBC-SHA256:RSA-PSK-AES128-CBC-SHA:DHE-PSK-AES128-CBC-SHA:AES128-SHA:PSK-AES128-CBC-SHA256:PSK-AES128-CBC-SHA</pre>
</details>
<details>
<summary>sudo nginx -t</summary>
<pre>nginx: [warn] the "listen ... http2" directive is deprecated, use the "http2" directive instead in /Users/matat/.config/valet/Nginx/shipos.test:9
nginx: [warn] the "http2_push_preload" directive is obsolete, ignored in /Users/matat/.config/valet/Nginx/shipos.test:15
nginx: the configuration file /usr/local/etc/nginx/nginx.conf syntax is ok
nginx: configuration file /usr/local/etc/nginx/nginx.conf test is successful</pre>
</details>
<details>
<summary>which -a php-fpm</summary>
<pre>/usr/local/sbin/php-fpm</pre>
</details>
<details>
<summary>/usr/local/opt/php/sbin/php-fpm -v</summary>
<pre>PHP 8.2.10 (fpm-fcgi) (built: Aug 31 2023 19:16:18)
Copyright (c) The PHP Group
Zend Engine v4.2.10, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.10, Copyright (c), by Zend Technologies
    with Xdebug v3.2.1, Copyright (c) 2002-2023, by Derick Rethans
<br />
<b>Warning</b>:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php-imap/lib/php/20220829/imap.so' (tried: /usr/local/opt/php-imap/lib/php/20220829/imap.so (dlopen(/usr/local/opt/php-imap/lib/php/20220829/imap.so, 0x0009): tried: '/usr/local/opt/php-imap/lib/php/20220829/imap.so' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/php-imap/lib/php/20220829/imap.so' (no such file), '/usr/local/opt/php-imap/lib/php/20220829/imap.so' (no such file)), /usr/local/lib/php/pecl/20220829//usr/local/opt/php-imap/lib/php/20220829/imap.so.so (dlopen(/usr/local/lib/php/pecl/20220829//usr/local/opt/php-imap/lib/php/20220829/imap.so.so, 0x0009): tried: '/usr/local/lib/php/pecl/20220829//usr/local/opt/php-imap/lib/php/20220829/imap.so.so' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/lib/php/pecl/20220829//usr/local/opt/php-imap/lib/php/20220829/imap.so.so' (no such file), '/usr/local/lib/php/pecl/20220829//usr/local/opt/php-imap/lib/php/20220829/imap.so.so' (no such file))) in <b>Unknown</b> on line <b>0</b><br /></pre>
</details>
<details>
<summary>sudo /usr/local/opt/php/sbin/php-fpm -y /etc/php-fpm.conf --test</summary>
<pre>[07-Sep-2023 13:20:51] ERROR: failed to open configuration file '/etc/php-fpm.conf': No such file or directory (2)
[07-Sep-2023 13:20:51] ERROR: failed to load configuration file '/etc/php-fpm.conf'
[07-Sep-2023 13:20:51] ERROR: FPM initialization failed</pre>
</details>
<details>
<summary>ls -al ~/Library/LaunchAgents | grep homebrew</summary>
<pre>-rw-r--r--   1 matat  staff   721 Jun 13 18:53 homebrew.mxcl.mariadb.plist</pre>
</details>
<details>
<summary>ls -al /Library/LaunchAgents | grep homebrew</summary>
<pre></pre>
</details>
<details>
<summary>ls -al /Library/LaunchDaemons | grep homebrew</summary>
<pre>-rw-r--r--@  1 root  admin   788 Sep  7 12:23 homebrew.mxcl.dnsmasq.plist
-rw-r--r--@  1 root  admin   679 Sep  7 13:02 homebrew.mxcl.nginx.plist
-rw-r--r--@  1 root  admin   772 Sep  7 13:02 homebrew.mxcl.php.plist</pre>
</details>
<details>
<summary>ls -al /Library/LaunchDaemons | grep "com.laravel.valet."</summary>
<pre></pre>
</details>
<details>
<summary>ls -aln /etc/resolv.conf</summary>
<pre>lrwxr-xr-x  1 0  0  22 Aug  2 15:29 /etc/resolv.conf -> ../var/run/resolv.conf</pre>
</details>
<details>
<summary>cat /etc/resolv.conf</summary>
<pre>#
# macOS Notice
#
# This file is not consulted for DNS hostname resolution, address
# resolution, or the DNS query routing mechanism used by most
# processes on this system.
#
# To view the DNS configuration used by this system, use:
#   scutil --dns
#
# SEE ALSO
#   dns-sd(1), scutil(8)
#
# This file is automatically generated.
#
nameserver 192.168.1.254</pre>
</details>
<details>
<summary>ifconfig lo0</summary>
<pre>lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> mtu 16384
	options=1203<RXCSUM,TXCSUM,TXSTATUS,SW_TIMESTAMP>
	inet 127.0.0.1 netmask 0xff000000 
	inet6 ::1 prefixlen 128 
	inet6 fe80::1%lo0 prefixlen 64 scopeid 0x1 
	nd6 options=201<PERFORMNUD,DAD></pre>
</details>
<details>
<summary>sh -c 'echo "------\n/usr/local/etc/nginx/valet/valet.conf\n---\n"; cat /usr/local/etc/nginx/valet/valet.conf | grep -n "# valet loopback"; echo "\n------\n"'</summary>
<pre>------
/usr/local/etc/nginx/valet/valet.conf
---

3:    #listen VALET_LOOPBACK:80; # valet loopback

------</pre>
</details>
<details>
<summary>sh -c 'for file in ~/.config/valet/dnsmasq.d/*; do echo "------\n~/.config/valet/dnsmasq.d/$(basename $file)\n---\n"; cat $file; echo "\n------\n"; done'</summary>
<pre>------
~/.config/valet/dnsmasq.d/tld-test.conf
---

address=/.test/127.0.0.1
listen-address=127.0.0.1

------</pre>
</details>
<details>
<summary>sh -c 'for file in ~/.config/valet/nginx/*; do echo "------\n~/.config/valet/nginx/$(basename $file)\n---\n"; cat $file | grep -n "# valet loopback"; echo "\n------\n"; done'</summary>
<pre>------
~/.config/valet/nginx/shipos.test
---

3:    #listen 127.0.0.1:80; # valet loopback
10:    #listen 127.0.0.1:443 ssl http2; # valet loopback
54:    #listen 127.0.0.1:60; # valet loopback

------</pre>
</details>

**Comment by drbyte** [comment]
> I checked the same repo on my colleague's computer, its working fine

What's different between those two computers? 
Is your colleague also using Herd? 

> Whenever I get an error in my application...

Is the problem happening with ALL applications? 
Is it only with Laravel applications? Which Laravel versions?

> I have been having this issue for the past couple of days

What "changed" on your computer just before this started? What sort of software updates? Crashes? Forced power-off? New software installed?

**Comment by sarik-k** [comment]
> What's different between those two computers?
Is your colleague also using Herd?

Our computers are completely different, he's on Windows and I'm on Mac. Just wanted to make sure it wasn't software issue on the project.
I installed Herd after I started getting problems with Valet, but Herd had its own issues so now I have completely removed it. 

> Is the problem happening with ALL applications?
Is it only with Laravel applications? Which Laravel versions?

I have only tested it on Laravel applications, Laravel 9 and 10. 

> What "changed" on your computer just before this started? What sort of software updates? Crashes? Forced power-off? New software installed?

I had updated my system to macOS Ventura 13.5.1, nothing else was changed. 

After testing, I found that the problem occurs with php@8.2. I downgraded to 8.1 and it's working fine now.

**Comment by drbyte** [comment]
> downgraded to 8.1

Might be wise to use brew to uninstall 8.2 fully. 
And also delete the /opt/home brew/etc/php/8.2 directory too. 
When you need it again later you can reinstall it. Hopefully if it's anything wrong with that version or the config it'll be fine with the next version.

**Comment by driesvints** [comment]
Closing this issue because it's inactive, already solved, old or not relevant anymore. Feel to open up a new issue if you're still experiencing this.
