### ISSUE TITLE
Valet Share does not copy or show the latest ngrok url, but only the first one

### ISSUE THREAD

**Issue by vitr** [laravel/valet#145]
If you use it more than once, it'll open up multiple ngrok instances (which is fine), but it will keep displaying and copying to the clipboard only the first one.

**Comment by lancepioch** [comment]
Referencing https://github.com/vitr/valet4windows/issues/7

**Comment by KorvinSzanto** [comment]
The issue here looks to be at least partly in ngrok. If you look at http://127.0.0.1:4040/api/tunnels you will see that ngrok returns the same tunnel twice instead of each tunnel.

**Comment by vitr** [comment]
@KorvinSzanto I don't think so, ngrok returns http and https and if have 2 tunnels, it returns 4 and everything works OK, it's just the valet, which is hard-coded to the very first tunnel.
