### ISSUE TITLE
PHP 8.3

### ISSUE THREAD

**Issue by itrack** [laravel/valet#1462]
### Description

Hi,
When I try to use PHP 8.3 it doesn't seem to work:

Valet doesn't support PHP version: php@8.3 (try something like 'php@8.1' in  stead)  

Do you plan to add compatibility?

Thank you,
Alex

### Steps To Reproduce

valet use php@8.3

### Diagnosis

-

**Comment by driesvints** [comment]
We’d appreciate a pr for this.

**Comment by adrum** [comment]
@itrack What version of Valet are you running? Try running `valet -V` to grab that. Running `brew update` and `composer global update laravel/valet` would be good things to try next before running `valet use php@8.3` again.

**Comment by itrack** [comment]
You right.... Laravel Valet 3.3.2
<img width="404" alt="Screenshot 2023-12-22 at 19 53 57" src="https://github.com/laravel/valet/assets/2368391/694f7f03-86db-45c3-aa01-4371d995fbc3">

Now I realized that "composer global upgrade" does not upgrade to the major version :)

Thank you!

**Comment by itrack** [comment]
I see that there is complicity now. I will close this issue. Thank you again!
