### ISSUE TITLE
error 502 when i use mongodb atlas connection mongodb+srv://connection-link

### ISSUE THREAD

**Issue by nationdata-it** [laravel/valet#1474]
### Description

Logs when using php 7.4:
[08-Mar-2024 15:18:44] WARNING: [pool valet] child 48680 exited on signal 6 (SIGABRT) after 240186.833239 seconds from start

==> /Users/myuser/.config/valet/Log/nginx-error.log <==
2024/03/08 15:18:44 [error] 568#0: *1169 upstream prematurely closed connection while reading response header from upstream, client: 127.0.0.1, server: mysite.test, request: "GET / HTTP/2.0", upstream: "fastcgi://unix:/Users/myuser/.config/valet/valet74.sock:", host: "mysite.test"

==> /opt/homebrew/var/log/php-fpm.log <==
[08-Mar-2024 15:18:44] NOTICE: [pool valet] child 52224 started

Logs when using php 8.2:
==> /Users/myuser/.config/valet/Log/nginx-error.log <==
2024/03/08 15:25:57 [error] 568#0: *1177 upstream prematurely closed connection while reading response header from upstream, client: 127.0.0.1, server: mysite2.test, request: "GET /test1 HTTP/2.0", upstream: "fastcgi://unix:/Users/myuser/.config/valet/valet82.sock:", host: "mysite2.test"

==> /opt/homebrew/var/log/php-fpm.log <==
[08-Mar-2024 15:25:57] WARNING: [pool valet] child 833 exited on signal 6 (SIGABRT) after 367025.662150 seconds from start
[08-Mar-2024 15:25:57] NOTICE: [pool valet] child 53153 started

### Steps To Reproduce

.env:
`
DB_CONNECTION=mongodb
DB_DSN="mongodb+srv://connection"
DB_PORT=27017
DB_DATABASE=dbname

rest env configs

web.php
`
Route::get('/test1', function () {
    $user = User::first();
    dd($user->toArray());
});
`

### Diagnosis

<details>
<summary>sw_vers</summary>
<pre>ProductName:		macOS
ProductVersion:		13.2.1
BuildVersion:		22D68</pre>
</details>
<details>
<summary>valet --version</summary>
<pre>Laravel Valet 4.6.1</pre>
</details>
<details>
<summary>cat ~/.config/valet/config.json</summary>
<pre>{
    "tld": "test",
    "loopback": "127.0.0.1",
    "paths": [
        "/Users/myuser/.config/valet/Sites"
    ],
    "share-tool": "ngrok"
}</pre>
</details>
<details>
<summary>cat ~/.composer/composer.json</summary>
<pre>{
    "require": {
        "laravel/valet": "^4.6"
    }
}</pre>
</details>
<details>
<summary>composer global diagnose</summary>
<pre>Changed current directory to /Users/myuser/.composer
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
Checking platform settings: OK
Checking git settings: OK git version 2.37.1
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: You are not running the latest stable version, run `composer self-update` to update (2.6.5 => 2.7.1)
Composer version: 2.6.5
PHP version: 8.3.1
PHP binary path: /opt/homebrew/Cellar/php/8.3.1/bin/php
OpenSSL version: OpenSSL 3.2.0 23 Nov 2023
cURL version: 8.5.0 libz 1.2.11 ssl (SecureTransport) OpenSSL/3.2.1
zip: extension present, unzip present, 7-Zip not available</pre>
</details>
<details>
<summary>composer global outdated</summary>
<pre>Changed current directory to /Users/myuser/.composer
Legend:
! patch or minor release available - update recommended
~ major release available - update possible

Direct dependencies required in composer.json:
Everything up to date

Transitive dependencies not required in composer.json:
guzzlehttp/guzzle                  7.8.0    ! 7.8.1    Guzzle is a PHP HTTP ...
guzzlehttp/promises                2.0.1    ! 2.0.2    Guzzle promises library
guzzlehttp/psr7                    2.6.1    ! 2.6.2    PSR-7 message impleme...
illuminate/collections             v8.83.27 ~ v10.47.0 The Illuminate Collec...
illuminate/container               v8.83.27 ~ v10.47.0 The Illuminate Contai...
illuminate/contracts               v8.83.27 ~ v10.47.0 The Illuminate Contra...
illuminate/macroable               v8.83.27 ~ v10.47.0 The Illuminate Macroa...
mnapoli/silly                      1.8.3    ! 1.9.0    Silly CLI micro-frame...
psr/container                      1.1.2    ~ 2.0.2    Common Container Inte...
psr/simple-cache                   1.0.1    ~ 3.0.0    Common interfaces for...
symfony/console                    v5.4.32  ~ v7.0.4   Eases the creation of...
symfony/deprecation-contracts      v2.5.2   ~ v3.4.0   A generic function an...
symfony/event-dispatcher           v5.4.26  ~ v7.0.3   Provides tools that a...
symfony/event-dispatcher-contracts v2.5.2   ~ v3.4.0   Generic abstractions ...
symfony/polyfill-ctype             v1.28.0  ! v1.29.0  Symfony polyfill for ...
symfony/polyfill-intl-grapheme     v1.28.0  ! v1.29.0  Symfony polyfill for ...
symfony/polyfill-intl-normalizer   v1.28.0  ! v1.29.0  Symfony polyfill for ...
symfony/polyfill-mbstring          v1.28.0  ! v1.29.0  Symfony polyfill for ...
symfony/polyfill-php73             v1.28.0  ! v1.29.0  Symfony polyfill back...
symfony/polyfill-php80             v1.28.0  ! v1.29.0  Symfony polyfill back...
symfony/process                    v5.4.28  ~ v7.0.4   Executes commands in ...
symfony/service-contracts          v2.5.2   ~ v3.4.1   Generic abstractions ...
symfony/string                     v5.4.32  ~ v7.0.4   Provides an object-or...</pre>
</details>
<details>
<summary>ls -al /etc/sudoers.d/</summary>
<pre>total 16
drwxr-xr-x   4 root  wheel   128 Jan 29 11:49 .
drwxr-xr-x  83 root  wheel  2656 Mar  8 15:06 ..
-rw-r--r--@  1 root  wheel    83 Jan 29 11:49 brew
-rw-r--r--@  1 root  wheel    86 Jan 29 11:49 valet</pre>
</details>
<details>
<summary>brew config</summary>
<pre>HOMEBREW_VERSION: 4.2.11
ORIGIN: https://github.com/Homebrew/brew
HEAD: d7d4c8266210c024b93a450a7d357cec0b46a1bb
Last commit: 4 days ago
Core tap JSON: 08 Mar 05:30 UTC
Core cask tap JSON: 08 Mar 05:30 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 3.1.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: dodeca-core 64-bit arm_blizzard_avalanche
Clang: 14.0.0 build 1400
Git: 2.37.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.86.0 => /usr/bin/curl
macOS: 13.2.1-arm64
CLT: 14.2.0.0.1.1668646533
Xcode: 14.2
Rosetta 2: false</pre>
</details>
<details>
<summary>brew services list</summary>
<pre>Warning: running through sudo, using user/* instead of gui/* domain!
Hide this warning by setting HOMEBREW_SERVICES_NO_DOMAIN_WARNING.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
Name    Status User          File
dnsmasq none            root          
nginx   none            root          
php     none            root          
php@7.2 started         myuser ~/Library/LaunchAgents/homebrew.mxcl.php@7.2.plist
php@7.4 none            root          
php@8.0 none                          
php@8.2 none            root          
unbound none</pre>
</details>
<details>
<summary>brew list --formula --versions | grep -E "(php|nginx|dnsmasq|mariadb|mysql|mailhog|openssl)(@\d\..*)?\s"</summary>
<pre>dnsmasq 2.89
nginx 1.25.3
openssl@1.1 1.1.1v
php 8.3.0 8.3.1
php@7.2 7.2.34_10
php@7.4 7.4.33_5
php@8.0 8.0.30_1
php@8.2 8.2.13 8.2.14</pre>
</details>
<details>
<summary>brew outdated</summary>
<pre>aom
apache-arrow
apktool
autoconf
aws-sdk-cpp
awscli
c-ares
cfitsio
cocoapods
composer
curl
dart-lang/dart/dart
dav1d
dnsmasq
expat
ffmpeg
flatbuffers
gdal
gettext
glib
gnupg
gnutls
gradle@7
grpc
harfbuzz
highway
icu4c
imath
jpeg
jpeg-turbo
jpeg-xl
lcov
libass
libassuan
libavif
libffi
libgpg-error
libidn2
libksba
libmicrohttpd
libnghttp2
libpng
libpq
libunibreak
libunistring
libusb
libxcb
libxdmcp
libxext
libxml2
llvm
mbedtls
minizip
mpdecimal
mpg123
nginx
npth
nss
numpy
nvm
openblas
openexr
openjdk
openjdk@11
openjdk@17
openjpeg
openldap
openssl@1.1
opus
pango
pcre2
php
shivammathur/php/php@7.2
shivammathur/php/php@7.4
shivammathur/php/php@8.0
php@8.2
poppler
proj
protobuf
python-setuptools
python@3.11
python@3.12
rav1e
re2
readline
ruby
scrcpy
sdl2
getsentry/tools/sentry-cli
sqlite
telnet
tesseract
unbound
xz
z3
zlib
android-platform-tools
ngrok</pre>
</details>
<details>
<summary>brew tap</summary>
<pre>dart-lang/dart
getsentry/tools
homebrew/services
microsoft/git
mongodb/brew
ngrok/ngrok
shivammathur/extensions
shivammathur/php</pre>
</details>
<details>
<summary>php -v</summary>
<pre>PHP 8.3.1 (cli) (built: Dec 20 2023 12:44:38) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.3.1, Copyright (c) Zend Technologies
    with Zend OPcache v8.3.1, Copyright (c), by Zend Technologies
    with Xdebug v3.3.1, Copyright (c) 2002-2023, by Derick Rethans</pre>
</details>
<details>
<summary>which -a php</summary>
<pre>/opt/homebrew/bin/php
/opt/homebrew/bin/php</pre>
</details>
<details>
<summary>php --ini</summary>
<pre>Configuration File (php.ini) Path: /opt/homebrew/etc/php/8.3
Loaded Configuration File:         /opt/homebrew/etc/php/8.3/php.ini
Scan for additional .ini files in: /opt/homebrew/etc/php/8.3/conf.d
Additional .ini files parsed:      /opt/homebrew/etc/php/8.3/conf.d/error_log.ini,
/opt/homebrew/etc/php/8.3/conf.d/ext-opcache.ini,
/opt/homebrew/etc/php/8.3/conf.d/ext-redis.ini,
/opt/homebrew/etc/php/8.3/conf.d/ext-xdebug.ini,
/opt/homebrew/etc/php/8.3/conf.d/php-memory-limits.ini</pre>
</details>
<details>
<summary>nginx -v</summary>
<pre>nginx version: nginx/1.25.3</pre>
</details>
<details>
<summary>curl --version</summary>
<pre>curl 7.86.0 (x86_64-apple-darwin22.0) libcurl/7.86.0 (SecureTransport) LibreSSL/3.3.6 zlib/1.2.11 nghttp2/1.47.0
Release-Date: 2022-10-26
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: alt-svc AsynchDNS GSS-API HSTS HTTP2 HTTPS-proxy IPv6 Kerberos Largefile libz MultiSSL NTLM NTLM_WB SPNEGO SSL threadsafe UnixSockets</pre>
</details>
<details>
<summary>php --ri curl</summary>
<pre>curl

cURL support => enabled
cURL Information => 8.5.0
Age => 10
Features
AsynchDNS => Yes
CharConv => No
Debug => No
GSS-Negotiate => No
IDN => Yes
IPv6 => Yes
krb4 => No
Largefile => Yes
libz => Yes
NTLM => Yes
NTLMWB => No
SPNEGO => Yes
SSL => Yes
SSPI => No
TLS-SRP => Yes
HTTP2 => Yes
GSSAPI => Yes
KERBEROS5 => Yes
UNIX_SOCKETS => Yes
PSL => No
HTTPS_PROXY => Yes
MULTI_SSL => Yes
BROTLI => Yes
ALTSVC => Yes
HTTP3 => No
UNICODE => No
ZSTD => Yes
HSTS => Yes
GSASL => No
Protocols => dict, file, ftp, ftps, gopher, gophers, http, https, imap, imaps, ldap, ldaps, mqtt, pop3, pop3s, rtmp, rtmpe, rtmps, rtmpt, rtmpte, rtmpts, rtsp, scp, sftp, smb, smbs, smtp, smtps, telnet, tftp
Host => aarch64-apple-darwin22.6.0
SSL Version => (SecureTransport) OpenSSL/3.2.1
ZLib Version => 1.2.11
libSSH Version => libssh2/1.11.0

Directive => Local Value => Master Value
curl.cainfo => no value => no value</pre>
</details>
<details>
<summary>/opt/homebrew/bin/ngrok version</summary>
<pre>ngrok version 3.5.0</pre>
</details>
<details>
<summary>ls -al ~/.ngrok2</summary>
<pre>ls: /Users/myuser/.ngrok2: No such file or directory</pre>
</details>
<details>
<summary>brew info nginx</summary>
<pre>==> nginx: stable 1.25.4 (bottled), HEAD
HTTP(S) server and reverse proxy, and IMAP/POP3 proxy server
https://nginx.org/
/opt/homebrew/Cellar/nginx/1.25.3 (26 files, 2.4MB) *
  Poured from bottle using the formulae.brew.sh API on 2023-12-01 at 01:03:00
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/n/nginx.rb
License: BSD-2-Clause
==> Dependencies
Required: openssl@3, pcre2
==> Options
--HEAD
	Install HEAD version
==> Caveats
Docroot is: /opt/homebrew/var/www

The default port has been set in /opt/homebrew/etc/nginx/nginx.conf to 8080 so that
nginx can run without sudo.

nginx will load all files in /opt/homebrew/etc/nginx/servers/.

To start nginx now and restart at login:
  brew services start nginx
Or, if you don't want/need a background service you can just run:
  /opt/homebrew/opt/nginx/bin/nginx -g daemon\ off\;
==> Analytics
install: 14,190 (30 days), 33,935 (90 days), 175,277 (365 days)
install-on-request: 14,150 (30 days), 33,826 (90 days), 174,904 (365 days)
build-error: 10 (30 days)</pre>
</details>
<details>
<summary>brew info php</summary>
<pre>==> php: stable 8.3.3 (bottled), HEAD
General-purpose scripting language
https://www.php.net/
/opt/homebrew/Cellar/php/8.3.0 (523 files, 88.7MB)
  Poured from bottle using the formulae.brew.sh API on 2023-12-01 at 01:01:27
/opt/homebrew/Cellar/php/8.3.1 (525 files, 89.8MB) *
  Poured from bottle using the formulae.brew.sh API on 2024-01-08 at 22:08:40
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/p/php.rb
License: PHP-3.01
==> Dependencies
Build: httpd, pkg-config
Required: apr, apr-util, argon2, aspell, autoconf, curl, freetds, gd, gettext, gmp, icu4c, krb5, libpq, libsodium, libzip, oniguruma, openldap, openssl@3, pcre2, sqlite, tidy-html5, unixodbc
==> Options
--HEAD
	Install HEAD version
==> Caveats
To enable PHP in Apache add the following to httpd.conf and restart Apache:
    LoadModule php_module /opt/homebrew/opt/php/lib/httpd/modules/libphp.so

    <FilesMatch \.php$>
        SetHandler application/x-httpd-php
    </FilesMatch>

Finally, check DirectoryIndex includes index.php
    DirectoryIndex index.php index.html

The php.ini and php-fpm.ini file can be found in:
    /opt/homebrew/etc/php/8.3/

To start php now and restart at login:
  brew services start php
Or, if you don't want/need a background service you can just run:
  /opt/homebrew/opt/php/sbin/php-fpm --nodaemonize
==> Analytics
install: 64,292 (30 days), 175,813 (90 days), 661,025 (365 days)
install-on-request: 60,169 (30 days), 164,556 (90 days), 616,280 (365 days)
build-error: 66 (30 days)</pre>
</details>
<details>
<summary>brew info openssl</summary>
<pre>==> openssl@3: stable 3.2.1 (bottled)
Cryptography and SSL/TLS Toolkit
https://openssl.org/
/opt/homebrew/Cellar/openssl@3/3.2.1 (6,874 files, 32MB) *
  Poured from bottle using the formulae.brew.sh API on 2024-02-22 at 11:11:07
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/o/openssl@3.rb
License: Apache-2.0
==> Dependencies
Required: ca-certificates
==> Caveats
A CA file has been bootstrapped using certificates from the system
keychain. To add additional certificates, place .pem files in
  /opt/homebrew/etc/openssl@3/certs

and run
  /opt/homebrew/opt/openssl@3/bin/c_rehash
==> Analytics
install: 377,414 (30 days), 1,141,220 (90 days), 3,992,410 (365 days)
install-on-request: 49,357 (30 days), 150,887 (90 days), 628,450 (365 days)
build-error: 4,444 (30 days)</pre>
</details>
<details>
<summary>openssl version -a</summary>
<pre>OpenSSL 3.2.1 30 Jan 2024 (Library: OpenSSL 3.2.1 30 Jan 2024)
built on: Tue Jan 30 13:14:56 2024 UTC
platform: darwin64-arm64-cc
options:  bn(64,64)
compiler: clang -fPIC -arch arm64 -O3 -Wall -DL_ENDIAN -DOPENSSL_PIC -D_REENTRANT -DOPENSSL_BUILDING_OPENSSL -DNDEBUG
OPENSSLDIR: "/opt/homebrew/etc/openssl@3"
ENGINESDIR: "/opt/homebrew/Cellar/openssl@3/3.2.1/lib/engines-3"
MODULESDIR: "/opt/homebrew/Cellar/openssl@3/3.2.1/lib/ossl-modules"
Seeding source: os-specific
CPUINFO: OPENSSL_armcap=0x987d</pre>
</details>
<details>
<summary>openssl ciphers</summary>
<pre>TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:DHE-RSA-AES256-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES256-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES128-SHA:DHE-RSA-AES128-SHA:RSA-PSK-AES256-GCM-SHA384:DHE-PSK-AES256-GCM-SHA384:RSA-PSK-CHACHA20-POLY1305:DHE-PSK-CHACHA20-POLY1305:ECDHE-PSK-CHACHA20-POLY1305:AES256-GCM-SHA384:PSK-AES256-GCM-SHA384:PSK-CHACHA20-POLY1305:RSA-PSK-AES128-GCM-SHA256:DHE-PSK-AES128-GCM-SHA256:AES128-GCM-SHA256:PSK-AES128-GCM-SHA256:AES256-SHA256:AES128-SHA256:ECDHE-PSK-AES256-CBC-SHA384:ECDHE-PSK-AES256-CBC-SHA:SRP-RSA-AES-256-CBC-SHA:SRP-AES-256-CBC-SHA:RSA-PSK-AES256-CBC-SHA384:DHE-PSK-AES256-CBC-SHA384:RSA-PSK-AES256-CBC-SHA:DHE-PSK-AES256-CBC-SHA:AES256-SHA:PSK-AES256-CBC-SHA384:PSK-AES256-CBC-SHA:ECDHE-PSK-AES128-CBC-SHA256:ECDHE-PSK-AES128-CBC-SHA:SRP-RSA-AES-128-CBC-SHA:SRP-AES-128-CBC-SHA:RSA-PSK-AES128-CBC-SHA256:DHE-PSK-AES128-CBC-SHA256:RSA-PSK-AES128-CBC-SHA:DHE-PSK-AES128-CBC-SHA:AES128-SHA:PSK-AES128-CBC-SHA256:PSK-AES128-CBC-SHA</pre>
</details>
<details>
<summary>sudo nginx -t</summary>
<pre>nginx: the configuration file /opt/homebrew/etc/nginx/nginx.conf syntax is ok
nginx: configuration file /opt/homebrew/etc/nginx/nginx.conf test is successful</pre>
</details>
<details>
<summary>which -a php-fpm</summary>
<pre>/opt/homebrew/sbin/php-fpm
/opt/homebrew/sbin/php-fpm</pre>
</details>
<details>
<summary>/opt/homebrew/opt/php/sbin/php-fpm -v</summary>
<pre>PHP 8.3.1 (fpm-fcgi) (built: Dec 20 2023 12:44:38)
Copyright (c) The PHP Group
Zend Engine v4.3.1, Copyright (c) Zend Technologies
    with Zend OPcache v8.3.1, Copyright (c), by Zend Technologies
    with Xdebug v3.3.1, Copyright (c) 2002-2023, by Derick Rethans</pre>
</details>
<details>
<summary>sudo /opt/homebrew/opt/php/sbin/php-fpm -y /opt/homebrew/etc/php/8.3/php-fpm.conf --test</summary>
<pre>[08-Mar-2024 15:31:03] NOTICE: configuration file /opt/homebrew/etc/php/8.3/php-fpm.conf test is successful</pre>
</details>
<details>
<summary>ls -al ~/Library/LaunchAgents | grep homebrew</summary>
<pre>-rw-r--r--@  1 myuser  staff   789 Oct 17 22:17 homebrew.mxcl.php@7.2.plist</pre>
</details>
<details>
<summary>ls -al /Library/LaunchAgents | grep homebrew</summary>
<pre></pre>
</details>
<details>
<summary>ls -al /Library/LaunchDaemons | grep homebrew</summary>
<pre>-rw-r--r--@  1 root  admin   797 Mar  1 21:27 homebrew.mxcl.dnsmasq.plist
-rw-r--r--@  1 root  admin   685 Mar  1 21:28 homebrew.mxcl.nginx.plist
-rw-r--r--@  1 root  admin   781 Mar  1 21:28 homebrew.mxcl.php.plist
-rw-r--r--@  1 root  admin   789 Mar  1 21:27 homebrew.mxcl.php@7.4.plist
-rw-r--r--@  1 root  admin   789 Mar  1 21:27 homebrew.mxcl.php@8.2.plist</pre>
</details>
<details>
<summary>ls -al /Library/LaunchDaemons | grep "com.laravel.valet."</summary>
<pre></pre>
</details>
<details>
<summary>ls -aln /etc/resolv.conf</summary>
<pre>lrwxr-xr-x  1 0  0  22 Feb  9  2023 /etc/resolv.conf -> ../var/run/resolv.conf</pre>
</details>
<details>
<summary>cat /etc/resolv.conf</summary>
<pre>#
# macOS Notice
#
# This file is not consulted for DNS hostname resolution, address
# resolution, or the DNS query routing mechanism used by most
# processes on this system.
#
# To view the DNS configuration used by this system, use:
#   scutil --dns
#
# SEE ALSO
#   dns-sd(1), scutil(8)
#
# This file is automatically generated.
#
nameserver 192.168.0.1</pre>
</details>
<details>
<summary>ifconfig lo0</summary>
<pre>lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> mtu 16384
	options=1203<RXCSUM,TXCSUM,TXSTATUS,SW_TIMESTAMP>
	inet 127.0.0.1 netmask 0xff000000 
	inet6 ::1 prefixlen 128 
	inet6 fe80::1%lo0 prefixlen 64 scopeid 0x1 
	nd6 options=201<PERFORMNUD,DAD></pre>
</details>
<details>
<summary>sh -c 'echo "------\n/opt/homebrew/etc/nginx/valet/valet.conf\n---\n"; cat /opt/homebrew/etc/nginx/valet/valet.conf | grep -n "# valet loopback"; echo "\n------\n"'</summary>
<pre>------
/opt/homebrew/etc/nginx/valet/valet.conf
---

3:    #listen VALET_LOOPBACK:80; # valet loopback

------</pre>
</details>
<details>
<summary>sh -c 'for file in ~/.config/valet/dnsmasq.d/*; do echo "------\n~/.config/valet/dnsmasq.d/$(basename $file)\n---\n"; cat $file; echo "\n------\n"; done'</summary>
<pre>------
~/.config/valet/dnsmasq.d/tld-test.conf
---

address=/.test/127.0.0.1
listen-address=127.0.0.1

------</pre>
</details>
<details>
<summary>sh -c 'for file in ~/.config/valet/nginx/*; do echo "------\n~/.config/valet/nginx/$(basename $file)\n---\n"; cat $file | grep -n "# valet loopback"; echo "\n------\n"; done'</summary>
<pre>------
~/.config/valet/nginx/abc.test
---

5:    #listen VALET_LOOPBACK:80; # valet loopback

------

------
~/.config/valet/nginx/advance-jms-app.test
---

4:    #listen 127.0.0.1:80; # valet loopback
11:    #listen VALET_LOOPBACK:443 ssl; # valet loopback
55:    #listen 127.0.0.1:60; # valet loopback

------

------
~/.config/valet/nginx/agl.test
---

4:    #listen 127.0.0.1:80; # valet loopback
11:    #listen VALET_LOOPBACK:443 ssl; # valet loopback
55:    #listen 127.0.0.1:60; # valet loopback

------

------
~/.config/valet/nginx/anglo.test
---

4:    #listen 127.0.0.1:80; # valet loopback
11:    #listen VALET_LOOPBACK:443 ssl; # valet loopback
55:    #listen 127.0.0.1:60; # valet loopback

------

------
~/.config/valet/nginx/app.mail.test
---

5:    #listen 127.0.0.1:80; # valet loopback
12:    #listen VALET_LOOPBACK:443 ssl; # valet loopback

------

------
~/.config/valet/nginx/app.minio.test
---

5:    #listen 127.0.0.1:80; # valet loopback
12:    #listen VALET_LOOPBACK:443 ssl; # valet loopback

------

------
~/.config/valet/nginx/assets.agl.test
---

3:    #listen 127.0.0.1:80; # valet loopback
10:    #listen VALET_LOOPBACK:443 ssl; # valet loopback
54:    #listen 127.0.0.1:60; # valet loopback

------

------
~/.config/valet/nginx/assets.anglo.test
---

3:    #listen 127.0.0.1:80; # valet loopback
10:    #listen VALET_LOOPBACK:443 ssl; # valet loopback
54:    #listen 127.0.0.1:60; # valet loopback

------

------
~/.config/valet/nginx/assets.fly2work.test
---

4:    #listen 127.0.0.1:80; # valet loopback
11:    #listen VALET_LOOPBACK:443 ssl; # valet loopback
55:    #listen 127.0.0.1:60; # valet loopback

------

------
~/.config/valet/nginx/assets.igo.test
---

3:    #listen 127.0.0.1:80; # valet loopback
10:    #listen VALET_LOOPBACK:443 ssl; # valet loopback
54:    #listen 127.0.0.1:60; # valet loopback

------

------
~/.config/valet/nginx/assets.iluka.test
---

3:    #listen 127.0.0.1:80; # valet loopback
10:    #listen VALET_LOOPBACK:443 ssl; # valet loopback
54:    #listen 127.0.0.1:60; # valet loopback

------

------
~/.config/valet/nginx/assets.ionyx.test
---

4:    #listen 127.0.0.1:80; # valet loopback
11:    #listen VALET_LOOPBACK:443 ssl; # valet loopback
55:    #listen 127.0.0.1:60; # valet loopback

------

------
~/.config/valet/nginx/assets.journey.test
---

3:    #listen 127.0.0.1:80; # valet loopback
10:    #listen VALET_LOOPBACK:443 ssl; # valet loopback
54:    #listen 127.0.0.1:60; # valet loopback

------

------
~/.config/valet/nginx/assets.ozm.test
---

3:    #listen 127.0.0.1:80; # valet loopback
10:    #listen VALET_LOOPBACK:443 ssl; # valet loopback
54:    #listen 127.0.0.1:60; # valet loopback

------

------
~/.config/valet/nginx/cors.conf
---

------

------
~/.config/valet/nginx/fly2work-application.test
---

3:    #listen 127.0.0.1:80; # valet loopback
10:    #listen VALET_LOOPBACK:443 ssl; # valet loopback
54:    #listen 127.0.0.1:60; # valet loopback

------

------
~/.config/valet/nginx/fly2work.test
---

4:    #listen 127.0.0.1:80; # valet loopback
11:    #listen VALET_LOOPBACK:443 ssl; # valet loopback
55:    #listen 127.0.0.1:60; # valet loopback

------

------
~/.config/valet/nginx/igo.test
---

4:    #listen 127.0.0.1:80; # valet loopback
11:    #listen VALET_LOOPBACK:443 ssl; # valet loopback
55:    #listen 127.0.0.1:60; # valet loopback

------

------
~/.config/valet/nginx/iluka.test
---

3:    #listen 127.0.0.1:80; # valet loopback
10:    #listen VALET_LOOPBACK:443 ssl; # valet loopback
54:    #listen 127.0.0.1:60; # valet loopback

------

------
~/.config/valet/nginx/ionyx.test
---

4:    #listen 127.0.0.1:80; # valet loopback
11:    #listen VALET_LOOPBACK:443 ssl; # valet loopback
55:    #listen 127.0.0.1:60; # valet loopback

------

------
~/.config/valet/nginx/journey.test
---

4:    #listen 127.0.0.1:80; # valet loopback
11:    #listen VALET_LOOPBACK:443 ssl; # valet loopback
55:    #listen 127.0.0.1:60; # valet loopback

------

------
~/.config/valet/nginx/mailpit.test
---

5:    #listen 127.0.0.1:80; # valet loopback
12:    #listen VALET_LOOPBACK:443 ssl; # valet loopback

------

------
~/.config/valet/nginx/minio.test
---

5:    #listen 127.0.0.1:80; # valet loopback
12:    #listen VALET_LOOPBACK:443 ssl; # valet loopback

------

------
~/.config/valet/nginx/mongodb.test
---

5:    #listen 127.0.0.1:80; # valet loopback
12:    #listen VALET_LOOPBACK:443 ssl; # valet loopback

------

------
~/.config/valet/nginx/my-application.test
---

4:    #listen 127.0.0.1:80; # valet loopback
11:    #listen VALET_LOOPBACK:443 ssl; # valet loopback
55:    #listen 127.0.0.1:60; # valet loopback

------

------
~/.config/valet/nginx/ozm.test
---

4:    #listen 127.0.0.1:80; # valet loopback
11:    #listen VALET_LOOPBACK:443 ssl; # valet loopback
55:    #listen 127.0.0.1:60; # valet loopback

------

------
~/.config/valet/nginx/public.test
---

3:    #listen 127.0.0.1:80; # valet loopback
10:    #listen VALET_LOOPBACK:443 ssl; # valet loopback
54:    #listen 127.0.0.1:60; # valet loopback

------</pre>
</details>

**Comment by driesvints** [comment]
Laravel doesn’t supports this database type sorry

**Comment by nationdata-it** [comment]
Laravel itself doesn't come with built-in support for MongoDB out of the box. However, there are community-developed packages like mongodb/laravel-mongodb that extend Laravel's capabilities to work with MongoDB databases. It's not uncommon for these packages to function seamlessly with local MongoDB instances but encounter issues when connecting to MongoDB Atlas, which is a cloud-based MongoDB service.
thanks for your response.
