### ISSUE TITLE
Couldn't Install Laravel Valet

### ISSUE THREAD

**Issue by ayzerobug** [laravel/valet#1480]
### Description

I couldn't install valet on Mac OS Sonoma 14.4.1

### Steps To Reproduce

composer global require laravel/valet

Gives this response

Changed current directory to /Users/mac/.composer
./composer.json has been updated
Running composer update laravel/valet
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - laravel/valet[v0.1.0, ..., v0.1.2] require symfony/process ^3.0 -> found symfony/process[v3.0.0, ..., v3.4.47] but it conflicts with your root composer.json require (^7.0).
    - laravel/valet[v0.1.3, ..., v0.1.8, v1.0.0, ..., v1.1.22, v2.0.0, ..., v2.0.6] require symfony/process ~2.7|~3.0 -> found symfony/process[v2.7.0, ..., v2.8.52, v3.0.0, ..., v3.4.47] but it conflicts with your root composer.json require (^7.0).
    - laravel/valet[v2.0.7, ..., v2.5.3] require symfony/process ~2.7|~3.0|~4.0 -> found symfony/process[v2.7.0, ..., v2.8.52, v3.0.0, ..., v3.4.47, v4.0.0, ..., v4.4.44] but it conflicts with your root composer.json require (^7.0).
    - laravel/valet v2.5.4 requires symfony/process ~2.7|~3.0|~4.0|~5.0 -> found symfony/process[v2.7.0, ..., v2.8.52, v3.0.0, ..., v3.4.47, v4.0.0, ..., v4.4.44, v5.0.0, ..., v5.4.36] but it conflicts with your root composer.json require (^7.0).
    - laravel/valet[v2.6.0, ..., v2.16.1] require symfony/process ~3.0|~4.0|~5.0 -> found symfony/process[v3.0.0, ..., v3.4.47, v4.0.0, ..., v4.4.44, v5.0.0, ..., v5.4.36] but it conflicts with your root composer.json require (^7.0).
    - laravel/valet[v2.16.2, ..., v2.18.7] require symfony/process ^3.0|^4.0|^5.0 -> found symfony/process[v3.0.0, ..., v3.4.47, v4.0.0, ..., v4.4.44, v5.0.0, ..., v5.4.36] but it conflicts with your root composer.json require (^7.0).
    - laravel/valet[v2.18.8, ..., v2.18.10, v3.0.0, ..., v3.3.2, v4.0.0, ..., v4.6.1] require symfony/process ^3.0|^4.0|^5.0|^6.0 -> found symfony/process[v3.0.0, ..., v3.4.47, v4.0.0, ..., v4.4.44, v5.0.0, ..., v5.4.36, v6.0.0, ..., v6.4.4] but it conflicts with your root composer.json require (^7.0).
    - Root composer.json requires laravel/valet * -> satisfiable by laravel/valet[v0.1.0, ..., v0.1.8, v1.0.0, ..., v1.1.22, v2.0.0, ..., v2.18.10, v3.0.0, ..., v3.3.2, v4.0.0, ..., v4.6.1].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require laravel/valet:*" to figure out if any version is installable, or "composer require laravel/valet:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

### Diagnosis
Cound't install it at all

**Comment by drbyte** [comment]
It sounds like your `~/.composer/composer.json` file has `symfony/process: 7.0` hardcoded into it.
Valet's latest release is only tested up to symfony/process v6.x.

So, until Valet is updated, try changing your global composer config to use `"symfony/process": "^6.0|^7.0",` instead of just 7.0

**Comment by driesvints** [comment]
Gonna close this since there's a PR open. Thanks.
