### ISSUE TITLE
Valet does not serve files with no extension well.

### ISSUE THREAD

**Issue by shaljam** [laravel/valet#149]
I had `jpeg` files with **no extension** and Valet served them with different size and checksum.
See [http://stackoverflow.com/questions/39545406/laravel-valet-not-serving-jpeg-files-with-no-extension](url).
I don't know if it's an issue or a feature request.

**Comment by adamwathan** [comment]
I think this will be improved in `master` when we tag a release down the road, we've delegated all static file handling to Caddy which will hopefully be smarter about this out of the box. Will leave this open until we tag though!
