### ISSUE TITLE
Passing arguments to Ngrok broken in v.4.8.0

### ISSUE THREAD

**Issue by kiritokatklian** [laravel/valet#1494]
### Description

v4.8.0 breaks passing arguments like `--domain` with the `valet share` command. Only tested with Ngrok.
For now I've downgraded back to v4.7.1, since it works in this version

### Steps To Reproduce

```bash
$ valet share-tool ngrok
$ valet share --domain=custom.domain
```

### Diagnosis

N/A

**Comment by drbyte** [comment]
Could be related to #1467 
/cc @rcknr

**Comment by rcknr** [comment]
It seems like [this line](https://github.com/laravel/valet/blob/5da6033253dddece62ffaef4621b97ae5d333ff9/valet#L55) has to have `!=` instead of `==`.
