### ISSUE TITLE
Valet webserver permissions

### ISSUE THREAD

**Issue by Quezler** [laravel/valet#150]
On mac, the valet webserver runs under the user **_www**.

**Laravel new** however sets it up under the current user.

Without rights valet cannot cache blade, make log files, etc.

So I'm wondering why it works out of the box in [examples like this](https://laracasts.com/series/whats-new-in-laravel-5-3/episodes/13).

**Comment by adamwathan** [comment]
Valet runs as the current user, you can see where that gets configured
during installation here:

https://github.com/laravel/valet/blob/master/cli/Valet/PhpFpm.php#L62

Did you do anything out of the ordinary when installing Valet that would
have bypassed the configuration process?

**Comment by Quezler** [comment]
Hmm,

Well during/before the install there was a It works! apache page on port 80, i killed that process when i found out.

Its the only think i can think of right now.

**Comment by Quezler** [comment]
Update: editing said config file to the username of my account fixed the problem.

**Comment by Quezler** [comment]
Now that i think about it, there was an error during the initial valet setup (an error about libz not being installed)

I ran `xcode-select --install` afterwards followed by `brew install homebrew/php/php70`

Perhaps the initial install failed before it could set the config?

**Comment by hissy** [comment]
This is a nice thread. I had the same issue. I didn't know valet changed php-fpm config file during install, but I had changed php version. If users change php version, they have to change config file also.

**Comment by KorvinSzanto** [comment]
@hissy see #180 for information on how to cleanly swap out the underlying php you're using.

**Comment by hissy** [comment]
Thanks @KorvinSzanto 🍺
