### ISSUE TITLE
Valet Incorrectly Handles Root index.php in Native PHP Projects

### ISSUE THREAD

**Issue by belguinan** [laravel/valet#1508]
### Description
When serving a native PHP project that contains both a root `index.php` and a `/public/` folder or `public/index.php` file, Valet always serves the file from the `public` directory instead of the project root. This behavior is problematic for native PHP projects that follow a different directory structure than Laravel.

### Current Behavior
Given this structure:
```
project/
├── index.php          # Should be served by default
└── public/
    └── index.php      # Currently being served instead
```
Valet automatically serves `public/index.php` regardless of project type.

### Expected Behavior
- For native PHP projects: Serve `index.php` from the project root

### Environment
- macOS
- Laravel Valet Version: 4.8.0
- PHP Version: [7.4 & 8.3]

### Steps to Reproduce
1. Create a new directory `project`
2. Add an `index.php` in the root with sample content
3. Create a `public` directory
4. Add another `index.php` in the `public` directory
5. Link the project with Valet
6. Access the project through the browser

### Diagnosis

<details>
<summary>sw_vers</summary>
<pre>ProductName:       macOS
ProductVersion:     15.1.1
BuildVersion:       24B91</pre>
</details>
<details>
<summary>valet --version</summary>
<pre>Laravel Valet 4.8.0</pre>
</details>
<details>
<summary>cat ~/.config/valet/config.json</summary>
<pre>{
    "tld": "test",
    "loopback": "127.0.0.1",
    "paths": [
        "/Users/belguinan/.config/valet/Sites",
        "/Users/belguinan/Code"
    ]
}</pre>
</details>
<details>
<summary>cat ~/.composer/composer.json</summary>
<pre>{
    "require": {
        "laravel/installer": "^4.2",
        "laravel/valet": "^4.8"
    }
}</pre>
</details>
<details>
<summary>composer global diagnose</summary>
<pre>Changed current directory to /Users/belguinan/.composer
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
Checking composer.lock: OK
Checking platform settings: OK
Checking git settings: OK git version 2.39.5
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK does not expire
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking Composer version: OK
Checking Composer and its dependencies for vulnerabilities: OK
Composer version: 2.8.4
PHP version: 8.3.14
PHP binary path: /opt/homebrew/Cellar/php@8.3/8.3.14/bin/php
OpenSSL version: OpenSSL 3.4.0 22 Oct 2024
curl version: 8.11.0 libz 1.2.12 ssl OpenSSL/3.4.0 (SecureTransport)
zip: extension present, unzip present, 7-Zip not available</pre>
</details>
<details>
<summary>composer global outdated</summary>
<pre>Changed current directory to /Users/belguinan/.composer
Legend:
! patch or minor release available - update recommended
~ major release available - update possible

Direct dependencies required in composer.json:
laravel/installer 4.5.1  ~ 5.11.0 Laravel application installer.

Transitive dependencies not required in composer.json:
symfony/console   6.4.15 ~ 7.2.1  Eases the creation of beautiful and testab...
symfony/process   6.4.15 ~ 7.2.0  Executes commands in sub-processes</pre>
</details>
<details>
<summary>ls -al /etc/sudoers.d/</summary>
<pre>total 24
drwxr-xr-x   5 root  wheel   160 Dec  4 18:51 .
drwxr-xr-x  79 root  wheel  2528 Dec 11 13:39 ..
-r--r-----   1 root  wheel   897 Sep 22  2023 battery
-rw-r--r--   1 root  wheel    83 Dec  4 18:51 brew
-rw-r--r--   1 root  wheel    86 Dec  4 18:51 valet</pre>
</details>
<details>
<summary>brew config</summary>
<pre>HOMEBREW_VERSION: 4.4.11
ORIGIN: https://github.com/Homebrew/brew
HEAD: ad356d365837a691a52dfec32b3fb5f282f3aefc
Last commit: 3 days ago
Branch: stable
Core tap JSON: 12 Dec 15:22 UTC
Core cask tap JSON: 12 Dec 15:22 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_REPOSITORY: /opt/homebrew
HOMEBREW_CELLAR: /opt/homebrew/Cellar
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 3.3.6 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.6/bin/ruby
CPU: octa-core 64-bit westmere
Clang: 16.0.0 build 1600
Git: 2.39.5 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 8.7.1 => /usr/bin/curl
macOS: 15.1.1-x86_64
CLT: 16.1.0.0.1.1729049160
Xcode: N/A
Rosetta 2: true</pre>
</details>
<details>
<summary>brew services list</summary>
<pre>Warning: running through sudo, using user/* instead of gui/* domain!
Hide this warning by setting HOMEBREW_SERVICES_NO_DOMAIN_WARNING.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
Name       Status User      File
dnsmasq    error  512      root      ~/Library/LaunchAgents/homebrew.mxcl.dnsmasq.plist
memcached  none                      
mysql@8.4  started         belguinan ~/Library/LaunchAgents/homebrew.mxcl.mysql@8.4.plist
nginx      none            root      
php        none                      
php@7.4    none            root      
php@8.3    none            root      
unbound    none                      
wildfly-as none</pre>
</details>
<details>
<summary>brew list --formula --versions | grep -E "(php|nginx|dnsmasq|mariadb|mysql|mailhog|openssl)(@\d\..*)?\s"</summary>
<pre>dnsmasq 2.90
mysql@8.4 8.4.3_3
nginx 1.27.3
openssl@1.1 1.1.1u
php 8.4.1_1
php@7.4 7.4.33_8
php@8.3 8.3.14</pre>
</details>
<details>
<summary>brew outdated</summary>
<pre>cocoapods
composer
curl
docker
docker-completion
freetds
gettext
glib
icu4c@75
jpeg-xl
librist
memcached
shivammathur/extensions/msgpack@8.1
mysql-client@8.4
mysql@8.4
node
openjpeg
openssl@1.1
pandoc
pango
pixman
protobuf
pyenv
python@3.10
python@3.11
python@3.12
python@3.13
python@3.9
ruby
sdl2
sqlite
srt
twilio/brew/twilio
wget
rar</pre>
</details>
<details>
<summary>brew tap</summary>
<pre>homebrew/services
mrkai77/cask
ngrok/ngrok
redis-stack/redis-stack
shivammathur/extensions
shivammathur/php
twilio/brew
wpscanteam/tap</pre>
</details>
<details>
<summary>php -v</summary>
<pre>PHP 8.3.14 (cli) (built: Nov 19 2024 15:14:23) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.3.14, Copyright (c) Zend Technologies
    with Zend OPcache v8.3.14, Copyright (c), by Zend Technologies</pre>
</details>
<details>
<summary>which -a php</summary>
<pre>/opt/homebrew/bin/php
/opt/homebrew/opt/php@7.4/bin/php
/opt/homebrew/bin/php</pre>
</details>
<details>
<summary>php --ini</summary>
<pre>Configuration File (php.ini) Path: /opt/homebrew/etc/php/8.3
Loaded Configuration File:         /opt/homebrew/etc/php/8.3/php.ini
Scan for additional .ini files in: /opt/homebrew/etc/php/8.3/conf.d
Additional .ini files parsed:      /opt/homebrew/etc/php/8.3/conf.d/error_log.ini,
/opt/homebrew/etc/php/8.3/conf.d/ext-opcache.ini,
/opt/homebrew/etc/php/8.3/conf.d/php-memory-limits.ini</pre>
</details>
<details>
<summary>nginx -v</summary>
<pre>nginx version: nginx/1.27.3</pre>
</details>
<details>
<summary>curl --version</summary>
<pre>curl 8.7.1 (x86_64-apple-darwin24.0) libcurl/8.7.1 (SecureTransport) LibreSSL/3.3.6 zlib/1.2.12 nghttp2/1.62.0
Release-Date: 2024-03-27
Protocols: dict file ftp ftps gopher gophers http https imap imaps ipfs ipns ldap ldaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS GSS-API HSTS HTTP2 HTTPS-proxy IPv6 Kerberos Largefile libz MultiSSL NTLM SPNEGO SSL threadsafe UnixSockets</pre>
</details>
<details>
<summary>php --ri curl</summary>
<pre>curl

cURL support => enabled
cURL Information => 8.11.0
Age => 11
Features
AsynchDNS => Yes
CharConv => No
Debug => No
GSS-Negotiate => No
IDN => Yes
IPv6 => Yes
krb4 => No
Largefile => Yes
libz => Yes
NTLM => Yes
NTLMWB => No
SPNEGO => Yes
SSL => Yes
SSPI => No
TLS-SRP => Yes
HTTP2 => Yes
GSSAPI => Yes
KERBEROS5 => Yes
UNIX_SOCKETS => Yes
PSL => No
HTTPS_PROXY => Yes
MULTI_SSL => Yes
BROTLI => Yes
ALTSVC => Yes
HTTP3 => No
UNICODE => No
ZSTD => Yes
HSTS => Yes
GSASL => No
Protocols => dict, file, ftp, ftps, gopher, gophers, http, https, imap, imaps, ldap, ldaps, mqtt, pop3, pop3s, rtmp, rtmpe, rtmps, rtmpt, rtmpte, rtmpts, rtsp, scp, sftp, smb, smbs, smtp, smtps, telnet, tftp, ws, wss
Host => aarch64-apple-darwin24.1.0
SSL Version => OpenSSL/3.4.0 (SecureTransport)
ZLib Version => 1.2.12
libSSH Version => libssh2/1.11.1

Directive => Local Value => Master Value
curl.cainfo => no value => no value</pre>
</details>
<details>
<summary>/opt/homebrew/bin/ngrok version</summary>
<pre>ngrok version 3.18.4</pre>
</details>
<details>
<summary>ls -al ~/.ngrok2</summary>
<pre>ls: /Users/belguinan/.ngrok2: No such file or directory</pre>
</details>
<details>
<summary>brew info nginx</summary>
<pre>==> nginx: stable 1.27.3, HEAD
HTTP(S) server and reverse proxy, and IMAP/POP3 proxy server
https://nginx.org/
Installed
/opt/homebrew/Cellar/nginx/1.27.3 (27 files, 2.5MB) *
  Poured from bottle using the formulae.brew.sh API on 2024-12-04 at 19:48:04
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/n/nginx.rb
License: BSD-2-Clause
==> Dependencies
Required: openssl@3, pcre2
==> Options
--HEAD
    Install HEAD version
==> Caveats
Docroot is: /opt/homebrew/var/www

The default port has been set in /opt/homebrew/etc/nginx/nginx.conf to 8080 so that
nginx can run without sudo.

nginx will load all files in /opt/homebrew/etc/nginx/servers/.

To start nginx now and restart at login:
  brew services start nginx
Or, if you don't want/need a background service you can just run:
  /opt/homebrew/opt/nginx/bin/nginx -g daemon\ off\;
==> Analytics
install: 15,827 (30 days), 41,729 (90 days), 163,978 (365 days)
install-on-request: 15,799 (30 days), 41,672 (90 days), 163,550 (365 days)
build-error: 18 (30 days)</pre>
</details>
<details>
<summary>brew info php</summary>
<pre>==> php: stable 8.4.1, HEAD
General-purpose scripting language
https://www.php.net/
Installed
/opt/homebrew/Cellar/php/8.4.1_1 (530 files, 107.9MB)
  Poured from bottle using the formulae.brew.sh API on 2024-12-04 at 18:19:44
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/p/php.rb
License: PHP-3.01
==> Dependencies
Build: httpd, pkgconf
Required: apr, apr-util, argon2, autoconf, curl, freetds, gd, gettext, gmp, icu4c@76, krb5, libpq, libsodium, libzip, net-snmp, oniguruma, openldap, openssl@3, pcre2, sqlite, tidy-html5, unixodbc
==> Options
--HEAD
    Install HEAD version
==> Caveats
To enable PHP in Apache add the following to httpd.conf and restart Apache:
    LoadModule php_module /opt/homebrew/opt/php/lib/httpd/modules/libphp.so

    <FilesMatch \.php$>
        SetHandler application/x-httpd-php
    </FilesMatch>

Finally, check DirectoryIndex includes index.php
    DirectoryIndex index.php index.html

The php.ini and php-fpm.ini file can be found in:
    /opt/homebrew/etc/php/8.4/

To start php now and restart at login:
  brew services start php
Or, if you don't want/need a background service you can just run:
  /opt/homebrew/opt/php/sbin/php-fpm --nodaemonize
==> Analytics
install: 60,900 (30 days), 174,465 (90 days), 679,645 (365 days)
install-on-request: 56,367 (30 days), 162,630 (90 days), 633,530 (365 days)
build-error: 66 (30 days)</pre>
</details>
<details>
<summary>brew info openssl</summary>
<pre>==> openssl@3: stable 3.4.0
Cryptography and SSL/TLS Toolkit
https://openssl-library.org
Installed
/opt/homebrew/Cellar/openssl@3/3.4.0 (7,236 files, 33.4MB) *
  Poured from bottle using the formulae.brew.sh API on 2024-10-28 at 14:29:43
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/o/openssl@3.rb
License: Apache-2.0
==> Dependencies
Required: ca-certificates
==> Caveats
A CA file has been bootstrapped using certificates from the system
keychain. To add additional certificates, place .pem files in
  /opt/homebrew/etc/openssl@3/certs

and run
  /opt/homebrew/opt/openssl@3/bin/c_rehash
==> Analytics
install: 419,290 (30 days), 1,314,169 (90 days), 4,947,835 (365 days)
install-on-request: 55,271 (30 days), 188,271 (90 days), 642,053 (365 days)
build-error: 10,880 (30 days)</pre>
</details>
<details>
<summary>openssl version -a</summary>
<pre>OpenSSL 3.4.0 22 Oct 2024 (Library: OpenSSL 3.4.0 22 Oct 2024)
built on: Tue Oct 22 12:26:59 2024 UTC
platform: darwin64-arm64-cc
options:  bn(64,64)
compiler: clang -fPIC -arch arm64 -O3 -Wall -DL_ENDIAN -DOPENSSL_PIC -D_REENTRANT -DOPENSSL_BUILDING_OPENSSL -DNDEBUG
OPENSSLDIR: "/opt/homebrew/etc/openssl@3"
ENGINESDIR: "/opt/homebrew/Cellar/openssl@3/3.4.0/lib/engines-3"
MODULESDIR: "/opt/homebrew/Cellar/openssl@3/3.4.0/lib/ossl-modules"
Seeding source: os-specific
CPUINFO: OPENSSL_armcap=0x987d</pre>
</details>
<details>
<summary>openssl ciphers</summary>
<pre>TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:DHE-RSA-AES256-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES256-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES128-SHA:DHE-RSA-AES128-SHA:RSA-PSK-AES256-GCM-SHA384:DHE-PSK-AES256-GCM-SHA384:RSA-PSK-CHACHA20-POLY1305:DHE-PSK-CHACHA20-POLY1305:ECDHE-PSK-CHACHA20-POLY1305:AES256-GCM-SHA384:PSK-AES256-GCM-SHA384:PSK-CHACHA20-POLY1305:RSA-PSK-AES128-GCM-SHA256:DHE-PSK-AES128-GCM-SHA256:AES128-GCM-SHA256:PSK-AES128-GCM-SHA256:AES256-SHA256:AES128-SHA256:ECDHE-PSK-AES256-CBC-SHA384:ECDHE-PSK-AES256-CBC-SHA:SRP-RSA-AES-256-CBC-SHA:SRP-AES-256-CBC-SHA:RSA-PSK-AES256-CBC-SHA384:DHE-PSK-AES256-CBC-SHA384:RSA-PSK-AES256-CBC-SHA:DHE-PSK-AES256-CBC-SHA:AES256-SHA:PSK-AES256-CBC-SHA384:PSK-AES256-CBC-SHA:ECDHE-PSK-AES128-CBC-SHA256:ECDHE-PSK-AES128-CBC-SHA:SRP-RSA-AES-128-CBC-SHA:SRP-AES-128-CBC-SHA:RSA-PSK-AES128-CBC-SHA256:DHE-PSK-AES128-CBC-SHA256:RSA-PSK-AES128-CBC-SHA:DHE-PSK-AES128-CBC-SHA:AES128-SHA:PSK-AES128-CBC-SHA256:PSK-AES128-CBC-SHA</pre>
</details>
<details>
<summary>sudo nginx -t</summary>
<pre>nginx: the configuration file /opt/homebrew/etc/nginx/nginx.conf syntax is ok
nginx: configuration file /opt/homebrew/etc/nginx/nginx.conf test is successful</pre>
</details>
<details>
<summary>which -a php-fpm</summary>
<pre>/opt/homebrew/opt/php@7.4/sbin/php-fpm
/opt/homebrew/sbin/php-fpm</pre>
</details>
<details>
<summary>/opt/homebrew/opt/php/sbin/php-fpm -v</summary>
<pre>PHP 8.4.1 (fpm-fcgi) (built: Nov 20 2024 09:48:35) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.4.1, Copyright (c) Zend Technologies
    with Zend OPcache v8.4.1, Copyright (c), by Zend Technologies</pre>
</details>
<details>
<summary>sudo /opt/homebrew/opt/php/sbin/php-fpm -y /opt/homebrew/etc/php/8.3/php-fpm.conf --test</summary>
<pre>[12-Dec-2024 16:22:58] NOTICE: configuration file /opt/homebrew/etc/php/8.3/php-fpm.conf test is successful</pre>
</details>
<details>
<summary>ls -al ~/Library/LaunchAgents | grep homebrew</summary>
<pre>-rw-r--r--    1 belguinan  staff   797 Dec  4 19:40 homebrew.mxcl.dnsmasq.plist
-rw-r--r--    1 belguinan  staff   740 Dec  4 18:58 homebrew.mxcl.mysql@8.4.plist
-rw-r--r--@   1 belguinan  staff   880 Aug  2  2023 homebrew.mxcl.redis.plist</pre>
</details>
<details>
<summary>ls -al /Library/LaunchAgents | grep homebrew</summary>
<pre></pre>
</details>
<details>
<summary>ls -al /Library/LaunchDaemons | grep homebrew</summary>
<pre>-rw-r--r--   1 root  admin   797 Dec  4 21:29 homebrew.mxcl.dnsmasq.plist
-rw-r--r--   1 root  admin   685 Dec 12 16:22 homebrew.mxcl.nginx.plist
-rw-r--r--   1 root  admin   789 Dec 12 16:21 homebrew.mxcl.php@7.4.plist
-rw-r--r--   1 root  admin   789 Dec 12 16:21 homebrew.mxcl.php@8.3.plist</pre>
</details>
<details>
<summary>ls -al /Library/LaunchDaemons | grep "com.laravel.valet."</summary>
<pre></pre>
</details>
<details>
<summary>ls -aln /etc/resolv.conf</summary>
<pre>-rw-r--r--  1 0  0  25 Dec  4 19:40 /etc/resolv.conf</pre>
</details>
<details>
<summary>cat /etc/resolv.conf</summary>
<pre>nameserver 192.168.100.1</pre>
</details>
<details>
<summary>ifconfig lo0</summary>
<pre>lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> mtu 16384
    options=1203<RXCSUM,TXCSUM,TXSTATUS,SW_TIMESTAMP>
    inet 127.0.0.1 netmask 0xff000000
    inet6 ::1 prefixlen 128 
    inet6 fe80::1%lo0 prefixlen 64 scopeid 0x1 
    nd6 options=201<PERFORMNUD,DAD></pre>
</details>
<details>
<summary>sh -c 'echo "------\n/opt/homebrew/etc/nginx/valet/valet.conf\n---\n"; cat /opt/homebrew/etc/nginx/valet/valet.conf | grep -n "# valet loopback"; echo "\n------\n"'</summary>
<pre>------
/opt/homebrew/etc/nginx/valet/valet.conf
---

3:    #listen VALET_LOOPBACK:80; # valet loopback

------</pre>
</details>
<details>
<summary>sh -c 'for file in ~/.config/valet/dnsmasq.d/*; do echo "------\n~/.config/valet/dnsmasq.d/$(basename $file)\n---\n"; cat $file; echo "\n------\n"; done'</summary>
<pre>------
~/.config/valet/dnsmasq.d/tld-test.conf
---

address=/.test/127.0.0.1
listen-address=127.0.0.1

------</pre>
</details>
<details>
<summary>sh -c 'for file in ~/.config/valet/nginx/*; do echo "------\n~/.config/valet/nginx/$(basename $file)\n---\n"; cat $file | grep -n "# valet loopback"; echo "\n------\n"; done'</summary>
<pre>------
~/.config/valet/nginx/hotel-booking.test
---

3:    #listen 127.0.0.1:80; # valet loopback
10:    #listen VALET_LOOPBACK:443 ssl; # valet loopback
54:    #listen 127.0.0.1:60; # valet loopback

------

------
~/.config/valet/nginx/hotel-booking-backend.test
---

4:    #listen 127.0.0.1:80; # valet loopback
11:    #listen VALET_LOOPBACK:443 ssl; # valet loopback
56:    #listen 127.0.0.1:60; # valet loopback

------</pre>
</details>

**Comment by drbyte** [comment]
The best solution is probably a custom Valet driver.

**Comment by belguinan** [comment]
@drbyte or just fallback to the main project directory when public folder didn't respond with http success status code, because now, even when public folder exist and empty, valet will stop serving the default index files from the root dir.

**Comment by drbyte** [comment]
> Valet automatically serves public/index.php regardless of project type.

That's not an accurate statement. 

Valet serves `public/index.php` when it exists and when no other driver has responded with indicators that suggest it should behave otherwise. 
The driver which handles that, which is `BasicWithPublicValetDriver`, is the second-last in the sequence of over 2 dozen possible workflows it supports already using the provided drivers. And won't be used if a custom driver already handles the site.

That's why Valet has support for custom drivers, both per-project (which you can commit to your project repository) and per Application-Type (Laravel, Statamic, Wordpress, NativePHP if you create one) which you install onto your own Valet PC.

And your custom driver can very easily replace the detection of the "public" directory by simply never checking that directory. 

> fallback to the main project directory when public folder didn't respond with http success status code

Checking for an http status code isn't part of Valet's offerings. It checks based on filesystem.

> When serving a native PHP project that contains both `a root index.php` and `a /public/ folder` or `public/index.php file` ...

QUESTION: Why does your project have "both"? 
QUESTION 2: Under what conditions would you have a `public/index.php` that wouldn't "respond" with an http status anyway?
QUESTION 3: Why would these conditions be unique to NativePHP vs any other project? (This is key to identifying NativePHP vs anything else, in order for Valet to behave as desired.)
QUESTION 4: Building on Q3: What other system-detectable indicators would reveal that this specific project (vs any others on this Valet-powered PC) is operating under NativePHP vs a traditional PHP setup?

Answers to these questions will help with constructing an appropriate solution that won't also break existing implementations not using NativePHP.

**Comment by belguinan** [comment]
@drbyte Upon reviewing your response and the Valet documentation, I understand now that my initial approach of modifying Nginx configurations was not aligned with Valet's architecture.
I've implemented a custom Valet driver as per the documentation:

```php
<?php

namespace Valet\Drivers\Custom;

use Valet\Drivers\ValetDriver;

class LocalValetDriver extends ValetDriver
{
    public function serves(string $sitePath, string $siteName, string $uri): bool
    {
        return true;
    }

    public function isStaticFile($sitePath, $siteName, $uri)
    {
        $staticFilePath = $sitePath . $uri;
        
        if (str_ends_with($uri, '.php')) {
            return false;
        }

        if (file_exists($staticFilePath) && is_readable($staticFilePath)) {
            return $staticFilePath;
        }

        return false;
    }

    public function frontControllerPath(string $sitePath, string $siteName, string $uri): ?string
    {
        $indexPath = $sitePath . '/index.php';
        
        if (file_exists($indexPath)) {
            return $indexPath;
        }

        return null;
    }
}
```

This implementation resolves the serving priority issue while maintaining compatibility with Valet's design patterns.

**Comment by drbyte** [comment]
@belguinan Yes, that looks good!
