### ISSUE TITLE
Add CSS MIME type/subtype

### ISSUE THREAD

**Issue by CharlesWiltgen** [laravel/valet#152]
I'm just starting to use Valet, and one issue I noticed is that it doesn't seem to serve CSS files with the correct MIME type/subtype by default. Specifically, the error I received in Chrome's console was:

```
Resource interpreted as Stylesheet but transferred with MIME type text/html: "http://xxx.dev/css/theme.css".
```

CSS should be served with a MIME type/subtype of `text/css`. Thank you!

**Comment by adamwathan** [comment]
Hey! Which version of Valet are you using? This might be a problem on master right now while we wait for Caddy to fix a known bug that's causing this issue, but things should be ok on a tagged release.

**Comment by CharlesWiltgen** [comment]
I'm using 1.1.19, installed using the instructions on laravel.com.

**Comment by adamwathan** [comment]
Can you create a small project on GitHub that recreates the issue to help
me figure out what is causing it? CSS files are returned with the correct
mime type on my system.

Is there weird casing in the file extension or anything by any chance?

**Comment by CharlesWiltgen** [comment]
> Can you create a small project on GitHub that recreates the issue to help
me figure out what is causing it?

Absolutely, when I can. It won't be today, so feel free to close this if it's in your way.
