### ISSUE TITLE
Running Valet causes sudoer error

### ISSUE THREAD

**Issue by uruloke** [laravel/valet#153]
When I run valet, I get an error in valet & brew's sudoer.
```
>>> /etc/sudoers.d/brew: Alias `BREW' already defined near line 1 <<<
>>> /etc/sudoers.d/valet: Alias `VALET' already defined near line 1 <<<
sudo: parse error in /etc/sudoers.d/brew near line 1
sudo: no valid sudoers sources found, quitting
```

**Comment by uruloke** [comment]
Sorry, this issue might not be valet related.

**Comment by arandilopez** [comment]
@uruloke how did you solve it?? i got the same...

**Comment by uruloke** [comment]
@arandilopez You may notice that all your sudo commands are giving this error now.
I removed the two sudoers files and that solved it for me, altough I know that it was a bad solution. 

Here is the thread on [StackOverflow](http://stackoverflow.com/questions/39586801/sudo-giving-error-after-installing-homebrew-and-laravel-valet).
