### ISSUE TITLE
First Valet needed Brew, now it has Brew but still returns an error

### ISSUE THREAD

**Issue by LourensThalen** [laravel/valet#154]
Hi there,

Love Valet. Great job.
Had some problems with my $PATH on OSX, so I removed most of it. 

Valet stopped working and I can't get it to work again. It throws an error and still says it works, but in the browser it shows a Valet - Not found 404 error.

This is the message I get when using the valet start command: 
```
Warning: array_filter() expects at most 2 parameters, 3 given in /Users/lourens/.composer/vendor/tightenco/collect/src/Illuminate/Support/Arr.php on line 504

Warning: array_filter() expects at most 2 parameters, 3 given in /Users/lourens/.composer/vendor/tightenco/collect/src/Illuminate/Support/Arr.php on line 504

Warning: array_filter() expects at most 2 parameters, 3 given in /Users/lourens/.composer/vendor/tightenco/collect/src/Illuminate/Support/Arr.php on line 504

Warning: array_filter() expects at most 2 parameters, 3 given in /Users/lourens/.composer/vendor/tightenco/collect/src/Illuminate/Support/Arr.php on line 504

Warning: array_filter() expects at most 2 parameters, 3 given in /Users/lourens/.composer/vendor/tightenco/collect/src/Illuminate/Support/Arr.php on line 504
```

I do have ~/.composer/vendor/bin in my $PATH. 

At first Valet stated I needed Brew installed (which I had) but I fixed that. Think Valet was looking for Brew in a different location. 

which valet: /usr/local/bin/valet
which composer: /usr/local/bin/composer

No log files were found (valet logs), it has the latest version.

I can't view any of the websites through Valet and this is really frustrating. I hope you can show me the way.

Cheers

**Comment by adamwathan** [comment]
It sounds like you have an old version of PHP installed. Try updating to PHP 5.6 or 7.0, that will fix that array_filter error.

**Comment by morloderex** [comment]
@adamwathan Or an old version of PHP in the path atleast.
