### ISSUE TITLE
Change valet port

### ISSUE THREAD

**Issue by KorvinSzanto** [laravel/valet#157]
Right now [we use port 9000](https://github.com/laravel/valet/blob/8d999e180cb54f0ee6f11129fb3650ee957553a4/cli/stubs/Caddyfile#L9), this can be a pain since xdebug uses 9000 by default too. Switching to a different port here will remove the extra pain of having to customize your xdebug environment for step through debugging.

If there's a better way to do step through debugging these days that I don't know about, I'd love to know :)

**Comment by adamwathan** [comment]
Been meaning to update the default FPM configuration to use a unix socket since it's faster anyways, will see about switching this over soon.

**Comment by drbyte** [comment]
This is probably closed by #159
