### ISSUE TITLE
Valet didn't respect domain (other than DEV) after upgrade

### ISSUE THREAD

**Issue by kurucu** [laravel/valet#161]
Having upgraded to Sierra, I also did a global composer update and valet install to sweep through any changes made by you guys.

I then had issues accessing my projects. The IP address returned as 172.0.53.53.

Having first checked `valet domain` to ensure it was still set, I did some troubleshooting. DNSMasq was still configured to use .dev, so I had to re-run `valet domain app` (app being my preferred domain extension) and then restart dnsmasq. It seems that while valet was publishing my customised domain using `valet domain`, it had reset the actual settings to the default during the upgrade.

I followed the instructions here: https://laravel.com/docs/5.3/valet#upgrading

**Comment by adamwathan** [comment]
Just a heads up, Valet doesn't work properly with Sierra yet. We are
waiting on Caddy to fix a bug in their Sierra-ready release that breaks
Valet before we can support Sierra.

**Comment by drbyte** [comment]
I don't think this is a Sierra issue specifically.

It might be a general upgrade glitch.

> DNSMasq was still configured to use .dev, so I had to re-run "valet domain app" (app being my preferred domain extension) and then restart dnsmasq. It seems that while valet was publishing my customised domain using "valet domain", it had reset the actual settings to the default during the upgrade.

I'm guessing that when you ran `valet install` it replaced your `dnsmasq.conf` which therefore wiped out your previous `app` entry.  Restoring that file after running valet install is probably all you needed to do.

**Comment by kurucu** [comment]
I think you're probably right, but if that's the case I think there is still a bug with Valet. It should either reset what's shown when you type `valet domain`, or re-instate the settings specified by the user having completed the install.

**Comment by KorvinSzanto** [comment]
I think #162 will help with this in-so-far as it will allow you to easily roll-back and upgrade and get your custom changes back. I don't think it would really help with the fact that we overwrite the file completely and I don't really see a great way to get around that.

**Comment by drbyte** [comment]
>  I don't think it would really help with the fact that we overwrite the file completely and I don't really see a great way to get around that.

... I'm thinking the solution could be that if the file exists already (ie: in the .valet folder) then just leave it.

**Comment by edalzell** [comment]
@adamwathan which bug in Caddy?

**Comment by drbyte** [comment]
@edalzell https://github.com/laravel/valet/pull/135

**Comment by adamwathan** [comment]
@edalzell Here's the direct link: https://github.com/mholt/caddy/issues/1086
