### ISSUE TITLE
Upgrade path

### ISSUE THREAD

**Issue by KorvinSzanto** [laravel/valet#162]
A valet upgrade command would be neat. With #159 as an example, we could set up migration classes that modify the environment up or down like this:

```php
<?php
namespace Valet\Migration;

use Valet\Brew;
use Valet\CommandLine;
use Valet\Filesystem;
use Valet\PhpFpm;

class Migration159
{

    public function up(Brew $brew, CommandLine $cli, Filesystem $files, $backupPath)
    {
        // Update fpm
        $fpm = new PhpFpm($brew, $cli, $files);
        $fpmConfig = $fpm->fpmConfigPath();
        $files->copy($fpmConfig, $backupPath . '/fpm.conf');
        $fpm->updateConfiguration();

        // Update caddy files
        ...
    }
    
    public function down(Brew $brew, CommandLine $cli, Filesystem $files, $backupPath)
    {
        // Revert fpm file
        $fpm = new PhpFpm($brew, $cli, $files);
        $fpmConfig = $fpm->fpmConfigPath();
        $files->copy($backupPath . '/fpm.conf', $fpmConfig);
        
        // Revert caddy files
        ...
    }

}

```

This gives us a simple upgrade path and allows us to downgrade in the event that something breaks. Thoughts?

**Comment by drbyte** [comment]
I like the idea.

**Comment by KorvinSzanto** [comment]
@adamwathan is this something you think would be worth prototyping in a pull request?

**Comment by adamwathan** [comment]
Right now I'm okay with the current upgrade process which is just `composer global update && valet install`. Did some work not that long ago to make that smoother. Don't want to introduce a ton of complexity around managing backups of files and stuff.

**Comment by KorvinSzanto** [comment]
:+1:
