### ISSUE TITLE
Valet crashes unexpected

### ISSUE THREAD

**Issue by ekandreas** [laravel/valet#164]
When using Valet the service crashes and no response is given to .dev addresses.
The Console says:
Sep 22 12:19:08 aekmbp com.apple.xpc.launchd[1] (com.laravel.valetServer[45142]): Service exited with abnormal code: 2

**Comment by ekandreas** [comment]
macSierra, Valet 1.1.19

**Comment by ekandreas** [comment]
The workaround is to restart the service with `valet restart` but the issue reocc after a couple of minutes.

**Comment by adamwathan** [comment]
Use the Sierra branch, 1.1.19 does not support Sierra.

**Comment by ekandreas** [comment]
It's even worse with the Sierra-branch. Getting "502 Bad Gateway" after a couple of seconds.

**Comment by rslanzi** [comment]
Hi Adam, I have a similar problem also with dev-sierra. Randomly it return 502 error or malformed response...

**Comment by adamwathan** [comment]
Which version of PHP? Have you run `brew upgrade php70` since moving to Sierra to make sure you get a build compiled for Sierra?

**Comment by ekandreas** [comment]
PHP v7.0.11

**Comment by adamwathan** [comment]
502 usually means an FPM problem. Can you share the contents of this log file?

`/usr/local/opt/php70/var/log/php-fpm.log`

**Comment by rslanzi** [comment]
My php-fpm.log file is empty.
With brew upgrade php70 I've got this error: homebrew/php/php70 7.0.11_2 already installed.
I tried also brew reinstall php70 --without-apache but the 502 error is still there.

**Comment by ekandreas** [comment]
ERROR: unable to bind listening socket for address '127.0.0.1:9000': Address already in use (48)
