### ISSUE TITLE
Valet randomly cycling through sites and page elements

### ISSUE THREAD

**Issue by timgavin** [laravel/valet#165]
Having a really weird issue where - when visiting a local site - Valet will cycle through elements of the page (CSS files, images, jQuery, etc.) and display them, as if I'd opened the file directly in my browser. Each time I refresh, I see a new element.

If that's not weird enough, I'll open another site, and Valet will continue displaying the first site, then, as I refresh, Valet will show elements between both sites, drop Bootstrap padding, regain the padding, show a `502 Bad Gateway` error... just random craziness.

When hitting a new `.dev` site in my browser I'd -on average - have to refresh about 5 times before seeing the new site.

`~/.valet/Log/access.log` is basically lots of this

```
127.0.0.1 - [21/Sep/2016:21:23:01 -0400] "GET /server.php HTTP/1.1" 200 42
127.0.0.1 - [21/Sep/2016:21:23:09 -0400] "GET /server.php HTTP/1.1" 200 42
127.0.0.1 - [21/Sep/2016:21:23:11 -0400] "GET /server.php HTTP/1.1" 200 2321
```

**Comment by jeroennoten** [comment]
I can confirm this issue. Let me know if I can help.

**Comment by jeroennoten** [comment]
Hmm I removed and reinstalled everything (even including php). And now everything works fine. Maybe removing `~/.valet` did the trick. But I am not sure what it was actually.

**Comment by timgavin** [comment]
@jeroennoten it's actually the version of Caddy.

https://twitter.com/adamwathan/status/778965973135085569

**Comment by jeroennoten** [comment]
Aah thanks. Makes sense ;) I guess you could close this issue now, right?

**Comment by timgavin** [comment]
Yeah. I wasn't sure if Adam wanted to add anything, but I guess he can re-open. :)
