### ISSUE TITLE
Welcome page of Apache instead content of the project

### ISSUE THREAD

**Issue by freearhey** [laravel/valet#166]
When I open the `example.dev` I see not the content of the project and the welcome page of Apache. Do you have any ideas how fix it?

**Comment by adamwathan** [comment]
Just quit Apache: https://gist.github.com/adamwathan/6ea40e90a804ea2b3f9f24146d86ad7f#problem-i-just-see-it-works

**Comment by freearhey** [comment]
Thanks, it helped!
