### ISSUE TITLE
Missing Share command from the list of commands

### ISSUE THREAD

**Issue by akoury** [laravel/valet#168]
Hello, I am very new to this stuff so sorry if my proposal is bad or wrong.

I just noticed that when you run valet in terminal, the share command doesn't get listed (and it is one of valet's main benefits), I tried adding the command to the valet/cli/valet.php document but I dont know what the closure should do, so the boilerplate would be something like

`$app->command('share', function () {
//function here
})->descriptions('Generate a publicly accessible URL for your project');`

Thanks for all the great work! Hope this helps in some way

**Comment by adamwathan** [comment]
@akoury Good question! I think it should just be an empty function, or perhaps just something like:

```php
$app->command('share', function () {
    warning("It looks like you are running `cli/valet.php` directly, please use the `valet` script in the project root instead.");
})->descriptions('Generate a publicly accessible URL for your project');
```

Feel free to PR!
