### ISSUE TITLE
Automate process of swapping underlying PHP using brew

### ISSUE THREAD

**Issue by KorvinSzanto** [laravel/valet#180]
Coming from #178, I switch my php versions out when I need to really easily by doing this:

```sh
$ brew unlink php70
$ brew link php56
$ valet install
$ valet restart
```

We already have a brew class, is it possible to do this kind of thing as part of valet? Something like `valet use php70` would be great.

**Comment by KorvinSzanto** [comment]
Here's a mostly working prototype: https://github.com/KorvinSzanto/valet/tree/feature/chphp

For some reason it chokes when going from php56 to php70, but all other forms seem to work for me:

![](https://i.imgur.com/zy2SnDr.png)

**Comment by KorvinSzanto** [comment]
Is this something anyone else is interested in?

**Comment by adamwathan** [comment]
Hey @KorvinSzanto I think we are going to hold on this right now, thanks.
