### ISSUE TITLE
Cannot redeclare global function 'info()'

### ISSUE THREAD

**Issue by trevoristall** [laravel/valet#182]
OS: MacOS Sierra
php version: PHP 7.0.11

When running a fresh valet install I got the following error:
<img width="942" alt="screen shot 2016-10-01 at 2 00 33 pm" src="https://cloud.githubusercontent.com/assets/5009188/19016125/76c4de14-87df-11e6-9310-b36362dfd9a1.png">
---

_laravel/framework/src/Illuminate/Foundation/helpers.php_
<img width="370" alt="screen shot 2016-10-01 at 2 01 54 pm" src="https://cloud.githubusercontent.com/assets/5009188/19016132/b9a6b4fa-87df-11e6-92f1-d8011b2ac12a.png">

_laravel/valet/cli/includes/helpers.php_
<img width="296" alt="screen shot 2016-10-01 at 2 03 18 pm" src="https://cloud.githubusercontent.com/assets/5009188/19016137/e3739104-87df-11e6-942e-9a83f59ee009.png">

**Comment by trevoristall** [comment]
What is the preferred solution here? My instinct is to rename the generic 'info()' function to something less likely to collide.

**Comment by adamwathan** [comment]
Any reason you have `laravel/framework` installed globally? I would just
uninstall that.
