### ISSUE TITLE
Valet Share site.localhost’s server DNS address could not be found.

### ISSUE THREAD

**Issue by jasperf** [laravel/valet#183]
Wrote about it [here](http://stackoverflow.com/questions/39825383/laravel-valet-share-url-leads-to-connection-refused). Have local WordPress site running. But `valet share` created link cannot be accessed from outside of the network:

```
This site can’t be reached
site.localhost’s server DNS address could not be found.
Try:
Checking the connection
ERR_NAME_NOT_RESOLVED
```

**NB** had .dev before but decided to try .localhost as I thought there might be a TLD conflict or something..

I have the standard generated Caddyfile, and locally the WordPress site runs just fine. Ngrok also registers that I try to access it externally and it indicates a 301 redirect takes place. But that is as far as it goes. So why am I getting these connection refused or DNS not resolved issues? I would think there is an issue going from Ngrok to Caddy. Any ideas how I can solve this and share the site properly?

**Comment by adamwathan** [comment]
Is the site locally secured using `valet secure`? If so, we currently don't support using `valet share` to share sites that are locally secured.

**Comment by jasperf** [comment]
It wasn't running secure as all was served on http as far as I saw. But did a 
```
valet unsecure
The [valet.localhost] site will now serve traffic over HTTP.
```
and then tested http://c1fb56e2.ngrok.io . Still same issue.

**Comment by jasperf** [comment]
Also when I do a curl I get the same redirect. 
```

curl -v http://50d4780b.ngrok.io
* Rebuilt URL to: http://50d4780b.ngrok.io/
*   Trying 45.79.5.162...
* Connected to 50d4780b.ngrok.io (45.79.5.162) port 80 (#0)
> GET / HTTP/1.1
> Host: 50d4780b.ngrok.io
> User-Agent: curl/7.49.1
> Accept: */*
> 
< HTTP/1.1 301 Moved Permanently
< Content-Type: text/html; charset=UTF-8
< Location: http://rocketpure.localhost/
< Server: Caddy
< Status: 301 Moved Permanently
< X-Powered-By: PHP/7.0.11
< X-Ua-Compatible: IE=edge
< Date: Tue, 04 Oct 2016 04:48:09 GMT
< Content-Length: 0
< 
* Connection #0 to host 50d4780b.ngrok.io left intact
```So Ngrok seems to be asking for site.localhost and that is how Valet adds it to the Ngrok header:

```
ps aux | grep ngrok
jasper          15153   0.2  0.2 556735428  26052 s001  S+    7:35AM   0:05.41 /Users/jasper/.composer/vendor/laravel/valet/bin/ngrok http -host-header=rewrite rocketpure.localhost:80
root            15147   0.0  0.1  2454916   8956 s001  S+    7:35AM   0:00.01 sudo -u jasper /Users/jasper/.composer/vendor/laravel/valet/bin/ngrok http -host-header=rewrite rocketpure.localhost:80
jasper          15324   0.0  0.0  2432804   2096 s000  S+    7:50AM   0:00.00 grep ngrok
```
So there is a difference there in what Ngrok is looking for or gets sent to and where the site resides it seems.

**Comment by jasperf** [comment]
Well, I can access valet WP sites when running one plain WP one my laptop using LTE and accessing it from my Mac Mini. I cannot however access any sites remotely when they run on my Mac Mini on my local network plugged into the Batelco (local) ADSL grid. Basically I am on my own network, inside a building network inside the Batelco ADSL network on a dynamic ip (89.148.xx.xx) Traceroute partly shown here: 

```
traceroute to http://2aaca5b2.ngrok.io (45.79.5.162), 64 hops max, 52 byte packets
 1  tp-link.home (192.168.1.1)  1.765 ms  1.523 ms  2.141 ms
 2  * * *
 3  static.ip.88.201.64.242.batelco.com.bh (88.201.64.242)  8.743 ms
    static.ip.88.201.64.58.batelco.com.bh (88.201.64.58)  5.781 ms
    static.ip.88.201.64.242.batelco.com.bh (88.201.64.242)  4.698 ms
 4  static.ip.88.201.64.241.batelco.com.bh (88.201.64.241)  4.372 ms  6.493 ms  3.872 ms
 5  172.17.9.25 (172.17.9.25)  4.367 ms  5.093 ms  4.584 ms
 6  195.229.29.145 (195.229.29.145)  11.716 ms  12.081 ms  11.646 ms
 7  195.229.31.69 (195.229.31.69)  16.998 ms
    195.229.31.101 (195.229.31.101)  19.530 ms
    195.229.31.69 (195.229.31.69)  18.345 ms
 8  195.229.3.171 (195.229.3.171)  275.214 ms
    195.229.1.106 (195.229.1.106)  239.532 ms
    nyc-r1-atm64-0-0-0.emix.net.ae (195.229.0.82)  203.486 ms
```

All requests fail due to that redirect showing up in the Caddy records. I tried two sites so far. So what I wonder is whether Ngrok cannot handle this setup or whether there is an issue with my current Valet setup on my Mac Mini running OSX Sierra. The MBP is still running El Capitan.

**Comment by KorvinSzanto** [comment]
It sounds like a 301 redirect is your issue here and not anything in the stream of ngrok / valet. If you put something like `die('test')` on the first line of your index.php do you still get a 301 response?

**Comment by jasperf** [comment]
That does get the site loaded @KorvinSzanto . Thanks. It doesn't load / display the .site.localhost domain either. It just shows the text in the die statement under the Ngrok url now. So the url no longer gets converted either this way. Now I need to find out how a WordPress App with WooCommerce I have been using for 3 years does some type of redirect without the .htaccess involved that causes this. There is of course a redirect in one of the core files:  wp-includes/template-loader.php do_action( 'template_redirect' ); This is there to redirect / decide what template file to load. Will dig further.

**Comment by KorvinSzanto** [comment]
I honestly don't know anything about wordpress but you shouldn't be redirecting away from this ngrok url. Wherever you're 301ing to the development url needs to be updated to allow the ngrok url too.

**Comment by jasperf** [comment]
Yeah, thanks @KorvinSzanto . Appreciate your feedback a lot. Using local URL on other MBP after loading ngrok URL first works fine. Not a redirect though. Seems more like it just runs the rewrite set up by Valet using Ngrok and DNSMasq. Will need to check the Valet WordPress Driver some more when I have time as well as my setup. Thanks again.

**Comment by EvanHerman** [comment]
@jasperf Any updates on this issue? I have been encountering this issue lately as well, and have been unable to test on other machines other than my development one.

**Comment by jasperf** [comment]
@EvanHerman No, no news. Still the same issue. Moved the site client needed to see to a test domain online. When I have time to debug more I will.

**Comment by EvanHerman** [comment]
It would be nice if we can figure this one out. Testing on multiple devices would really come in handy.

**Comment by jasperf** [comment]
Found the solution. It was not the redirect in the `WordPressValetDriver.php` as it was not related to regular urls. Even modified it (commented out the only redirect there getting all paranoid - to check:
```

 /**
     * Get the fully resolved path to the application's front controller.
     *
     * @param  string  $sitePath
     * @param  string  $siteName
     * @param  string  $uri
     * @return string
     */
    public function frontControllerPath($sitePath, $siteName, $uri)
    {
        $_SERVER['PHP_SELF']    = $uri;
        $_SERVER['SERVER_ADDR'] = '127.0.0.1';

        return parent::frontControllerPath(
            $sitePath, $siteName, $this->forceTrailingSlash($uri)
        );
    }

    /**
     * Redirect to uri with trailing slash.
     *
     * @param  string $uri
     * @return string
     */
    private function forceTrailingSlash($uri)
    {
        if (substr($uri, -1 * strlen('/wp-admin')) == '/wp-admin') {
            header('Location: '.$uri.'/'); die;
        }

        return $uri;
    }
}
```

The issue for me was that I was using pretty urls or permalinks. This forced an extra redirect Caddy and Ngrok could not work out together. As soon as I turned off pretty link and started using plain I could load the WordPress site from my iPhone on a separate LTE network:
```

Session Status                online                                             
Version                       2.1.14                                             
Region                        United States (us)                                 
Web Interface                 http://127.0.0.1:4040                              
Forwarding                    http://1111111111.ngrok.io -> site.localhost:80
Forwarding                    https://111111111.ngrok.io -> site.localhost:8
                                                                                 
Connections                   ttl     opn     rt1     rt5     p50     p90        
                              16      0       0.11    0.03    12.71   88.06      
                                                                                 
HTTP Requests                                                                    
-------------                                                                    
                                                                                 
GET /wp-content/themes/Total/css/fonts/fontawesome-webfont.woff2           200 OK
GET /wp-content/themes/Total/images/full-screen-overlay-nav-close-black.pn 200 OK
GET /wp-content/themes/Total/css/fonts/fontawesome-webfont.woff2           200 OK
GET /wp-includes/js/wp-embed.min.js                                        200 OK
GET /wp-content/themes/Total/js/total-min.js                               200 OK
GET /wp-content/plugins/contact-form-7/includes/js/scripts.js              200 OK
GET /wp-content/plugins/contact-form-7/includes/js/jquery.form.min.js      200 OK
GET /wp-content/plugins/js_composer/assets/js/vendors/woocommerce-add-to-c 200 OK
GET /wp-content/plugins/flow-flow/js/require-utils.js                      200 OK
GET /wp-content/plugins/revslider/public/assets/js/jquery.themepunch.revol 200 OK
```

 Still checking the broken url issue mentioned by Ngrok [here](https://ngrok.com/faq#wordpress) . But this is awesome!
