### ISSUE TITLE
Invalid certificate if accessing https site using a custom port

### ISSUE THREAD

**Issue by bcreeves** [laravel/valet#184]
I'm using Browsersync with Valet on a Laravel site. When I try to access https://project.dev:3000 the certificate shows as invalid. Should I be setting the browsersync port to something other than 3000 or will it just not work having a port in the url?

**Comment by ruchern** [comment]
I believe this is because the certificate generated by `Laravel Valet` is for the `*.dev` domain (using default here; your TLDs may vary) and not for `localhost:3000` when ran under `BrowserSync`
