### ISSUE TITLE
Moodle - Caddy not supported

### ISSUE THREAD

**Issue by rogervila** [laravel/valet#191]
Hello,

Since moodle has an `index.php` file on the route, it does not need a specific valet driver, but when I try to setup a new moodle project, I get this message.

![moodle](https://cloud.githubusercontent.com/assets/6053012/19436924/42fc67a0-9473-11e6-90f7-59af3a6af414.png)

**I know that this is a Moodle problem, not a Valet's one**, but I would like to know if its possible to find a solution from valet.

Thank you.

**Comment by adamwathan** [comment]
You might be able to write a Moodle driver that rewrites whatever header
Moodle is seeing that string in and pretending to be Apache or Nginx
instead.

**Comment by rogervila** [comment]
Thanks Adam, I will try it. 
If I solve it, I will make a pull request.

**Comment by rogervila** [comment]
I solved the Caddy problem by changing the `SERVER_SOFTWARE` value, but there are 2 new problems:

1. The routes that do not end with `.php` download a DMS file that contains an error that says that the extension is undefined. 

2. Moodle reads the assets from a `javascript.php` file with get parameters through the url. Then, the static files method does not work here. 

I will add the driver on my fork, so you can see the results.

**Comment by scara** [comment]
Hello Everyone,
for the record, this is the issue to track when (and if) Moodle will support Caddy: [MDL-57646](https://tracker.moodle.org/browse/MDL-57646).

HTH,
Matteo
