### ISSUE TITLE
Can't install WordPress in a subdirectory

### ISSUE THREAD

**Issue by JoshMoreno** [laravel/valet#192]
When I do, I get the following error and basically leaves WP unusable.

> Notice:  Undefined offset: 1 in /Path/To/Valet-Parked-Dir/example/wp/wp-includes/vars.php  on line 31

When I try to access the edit posts admin page, I get the same error as above and WP spits out

>  Invalid post type.

When I try to add a new page, The page settings metabox (where it says publish and all that stuff) on the side is missing.

I'm sure there are other things broken as well, but I didn't bother looking for every thing that's broken as it's probably all related to the same bug.

Any ideas on how to fix this?

**Comment by danielbachhuber** [comment]
I don't believe Valet supports WordPress in a subdirectory natively.

I had to write my own custom driver to get this to work: https://github.com/danielbachhuber/quickstart-minus-quickstart/blob/master/config/VipValetDriver.php
