### ISSUE TITLE
Couldn't connect to site if no internet

### ISSUE THREAD

**Issue by edalzell** [laravel/valet#194]
I tried to work on my local site w/o a network connection and it didn't work. Safari reported no network connection.

I got it working by adding local site to `/etc/hosts`, but that doesn't seem right to me.

**Comment by drbyte** [comment]
Ya, that suggests your `dnsmasq` service isn't running/properly.

**Comment by edalzell** [comment]
Hokey dokey...not a Valet issue then. Closing.
