### ISSUE TITLE
Valet fails if Homebrew isn't installed at /usr/local/bin/brew

### ISSUE THREAD

**Issue by briankc** [laravel/valet#197]
Valet currently fails with the message `Valet requires Brew to be installed on your Mac` even if Homebrew is in fact installed but isn't at `/usr/local/bin/brew`. This is addressed by pull request #66. Any chance this request will be accepted?

**Comment by adamwathan** [comment]
I can't promise we will actually put in effort to always support this if any other problems come up as a result of having Homebrew installed in a non-standard location, especially since the Homebrew team really recommends against it.
