### ISSUE TITLE
Proxy commands through sudo not working correctly/not necessary on sierra

### ISSUE THREAD

**Issue by willvincent** [laravel/valet#198]
I upgraded to osx sierra this morning. After doing so, valet began behaving oddly, requiring the sudo password to link/unlink a site, or even just to open a site.

While this is mostly an inconvenience, it is somewhat problematic for the open command as that command will be proxied through sudo, so run as root -- which then does not respect the default browser choice.

I've done some experimenting and it appears this section of the bash script is entirely unnecessary on osx sierra:

```
# If the command is one of the commands that requires "sudo" privileges
# then we'll proxy the incoming CLI request using sudo, which allows
# us to never require the end users to manually specify each sudo.
if [[ "$EUID" -ne 0 ]]
then
    sudo $SOURCE "$@"
    exit
fi
```

Commenting that out allows behavior as expected.

Perhaps the correct fix here is to add another condition that the osx version is NOT 10.12?

**Comment by adamwathan** [comment]
Hmm install, start, restart, and secure should all require sudo. Not at computer, but are those commands still working for you without that?

**Comment by willvincent** [comment]
yep, commenting out the $EUID check, it still prompts for password for all of those.

**Comment by willvincent** [comment]
I've submit a PR #206 that should address this issue. My earlier attempt of just commenting out that segment stopped working after reboot.  This solution, however, checks the command being run to first, then checks whether the UID is 0 for commands that require sudo.

I've tested it for a half hour or so and it is working for me.
