### ISSUE TITLE
Uninstall Valet

### ISSUE THREAD

**Issue by sina-aria** [laravel/valet#200]
I just installed the valet for the first time and i had some issues with accessing the non laravel projects which valet seems to have problems with it and it just sends a 404 or something. So i decided to uninstall it.

I ran `$ valet uninstall` and then `$ valet` and it was all there?

**Comment by sina-aria** [comment]
I just find the solution. Valet uninstall command does not work and to uninstall it properly you should use composer and homebrew to uninstall the dependencies it ships with. Here is my [answer](http://stackoverflow.com/questions/40276967/uninstall-laravel-valet/40279538#40279538) to do so.

**Comment by sina-aria** [comment]
Nope things get worth! it does not work!
I don't know what valet does when installed. but my server stopped working after uninstalling!
All I get is:
The localhost page isn’t working

localhost didn’t send any data.
ERR_EMPTY_RESPONSE

**Comment by sina-aria** [comment]
Not funny! after restarting two times and deleting ~/.valet directory my browsers title is 'Valet - Not Found'

**Comment by sina-aria** [comment]
Does anybody even come to valet issues page?

**Comment by adamwathan** [comment]
If you've removed Valet via composer and deleted ~/.valet then you've removed all traces of any code that actually has the word "Valet" in it from your system.

When are you seeing that in your browser title? When visiting a certain URL? Always? Like does visiting Facebook say "Valet - Not found"?

If you run `sudo lsof -i :80` on the command line, does it still list Caddy as running? If so kill that process and manually verify that ~/.composer/vendor/laravel/valet does not exist.

I noticed you deleted your other entitled comment but keep in mind we do this for free and it's 6am here, and you only reopened this issue 15 minutes ago.

**Comment by sina-aria** [comment]
Thanks for answering. I was just a little bit nervous because it messed up my system so deeply i am working on it even a couple of hours before opening this issue!

Anyway i solved the problem but honestly i don't know how!! Because just like you said i removed all traces but it was again there!

**Comment by sina-aria** [comment]
And by the way i don't think my entitled comment did mean something to anyone!

Im doing this free too.

**Comment by adamwathan** [comment]
We don't get paid to work on open source projects. I will help you when I
have time. It's 5 in the fucking morning.
