### ISSUE TITLE
Yii2 driver needed

### ISSUE THREAD

**Issue by sagarrabadiya** [laravel/valet#201]
its a kind of feature request, but it would be good if yii 2 supported driver is added valet.

**Comment by wxs77577** [comment]
why closed?

**Comment by diaforetikus** [comment]
<?php

class YiiValetDriver extends ValetDriver
{
    /**
     * Determine if the driver serves the request.
     *
     * @param  string  $sitePath
     * @param  string  $siteName
     * @param  string  $uri
     * @return bool
     */
    public function serves($sitePath, $siteName, $uri)
    {
        if (file_exists($sitePath.'/yii')) {
            return true;
        }

        return false;
    }

    /**
     * Determine if the incoming request is for a static file.
     *
     * @param  string  $sitePath
     * @param  string  $siteName
     * @param  string  $uri
     * @return string|false
     */
    public function isStaticFile($sitePath, $siteName, $uri)
    {
        if ($uri != '/backend/' && (file_exists($staticFilePath = $sitePath.'/frontend/web'.$uri) || file_exists($staticFilePath = $sitePath.str_replace('/backend/', '/backend/web/', $uri)))) {

            return $staticFilePath;
        }

        return false;
    }

    /**
     * Get the fully resolved path to the application's front controller.
     *
     * @param  string  $sitePath
     * @param  string  $siteName
     * @param  string  $uri
     * @return string
     */
    public function frontControllerPath($sitePath, $siteName, $uri)
    {
        $frontControllerPath = '/frontend/web/index.php';
        
        $_SERVER['PHP_SELF'] = '/index.php';

        if (strstr($uri, '/backend/'))
        {
            $frontControllerPath = '/backend/web/index.php';
            $_SERVER['PHP_SELF'] = '/backend/index.php';
        }

        $_SERVER['SCRIPT_FILENAME'] = $sitePath.$frontControllerPath;
        
        return $sitePath.$frontControllerPath;
    }
}

**Comment by diaforetikus** [comment]
`class YiiValetDriver extends ValetDriver
{
    /**
     * Determine if the driver serves the request.
     *
     * @param  string  $sitePath
     * @param  string  $siteName
     * @param  string  $uri
     * @return bool
     */
    public function serves($sitePath, $siteName, $uri)
    {
        if (file_exists($sitePath.'/yii')) {
            return true;
        }

        return false;
    }

    /**
     * Determine if the incoming request is for a static file.
     *
     * @param  string  $sitePath
     * @param  string  $siteName
     * @param  string  $uri
     * @return string|false
     */
    public function isStaticFile($sitePath, $siteName, $uri)
    {
        if ($uri != '/backend/' && (file_exists($staticFilePath = $sitePath.'/frontend/web'.$uri) || file_exists($staticFilePath = $sitePath.str_replace('/backend/', '/backend/web/', $uri)))) {

            return $staticFilePath;
        }

        return false;
    }

    /**
     * Get the fully resolved path to the application's front controller.
     *
     * @param  string  $sitePath
     * @param  string  $siteName
     * @param  string  $uri
     * @return string
     */
    public function frontControllerPath($sitePath, $siteName, $uri)
    {
        $frontControllerPath = '/frontend/web/index.php';
        
        //Устанавливается для Yii
        $_SERVER['PHP_SELF'] = '/index.php';

        if (strstr($uri, '/backend/'))
        {
            $frontControllerPath = '/backend/web/index.php';
            $_SERVER['PHP_SELF'] = '/backend/index.php';
        }

        $_SERVER['SCRIPT_FILENAME'] = $sitePath.$frontControllerPath;
        
        return $sitePath.$frontControllerPath;
    }
}`
