### ISSUE TITLE
DNS Collision with the .dev suffix is reserved now by Icann

### ISSUE THREAD

**Issue by thinkstylestudio** [laravel/valet#204]
I was unable to use the `.dev` domain suffix due to it colliding with icann's reserved DNS list. 

https://iyware.com/dont-use-dev-for-development/

Before changing the suffix I did a dig and received.

```
 dig test.dev

; <<>> DiG 9.8.3-P1 <<>> test.dev
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 54200
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;test.dev.			IN	A

;; ANSWER SECTION:
test.dev.		3600	IN	A	127.0.53.53

;; Query time: 148 msec
;; SERVER: 192.168.1.254#53(192.168.1.254)
;; WHEN: Mon Oct 31 12:37:23 2016
;; MSG SIZE  rcvd: 42
```

The ip of `127.0.53.53` was actully fed by icann 
https://www.icann.org/news/announcement-2-2014-08-01-en

and when I ran a `ping` on `test.dev` would return `unresolved`. 

I was wondering if having .dev as the default domain is the best one to use? 

I changed the domain suffix to `.localhost` or `.app` and everything works as it should

**Comment by drbyte** [comment]
Evidently your `dnsmasq` service (installed and used by Valet) is not operating correctly.

See the troubleshooting tips I posted in #115
