### ISSUE TITLE
Valet Share disregarding subdomain

### ISSUE THREAD

**Issue by campaignzee** [laravel/valet#205]
I am running the latest Valet (1.1.22) and Ngrok (2.1.18) on macOS 10.12.1. Even though Ngrok recognizes my account it disregards the custom subdomain I am passing and generates a random one. I am using this command:

`valet share -subdomain webhooks.campaignzee`

This command generates the correct subdomain on my Mac running 10.11.6 (running latest Valet and Ngrok as well).

Any ideas why this isn't working on macOS 10.12.1?

**Comment by willvincent** [comment]
1.1.22 does not pass through extra params to ngrok.  Try installing valet dev-master

Alternately, just to test that it works correctly, you could edit the ~/.composer/vendor/bin/valet file and change the relevant line (line 49 I believe) from this: `sudo -u $(logname) "$DIR/bin/ngrok" http -host-header=rewrite "$HOST.$DOMAIN:80"` to this: `sudo -u $(logname) "$DIR/bin/ngrok" http "$HOST.$DOMAIN:80" -host-header=rewrite ${*:2}`

Then execute thusly:
`valet share -subdomain=webhooks.campaignzee` (pretty sure that equal sign is required)

**Comment by campaignzee** [comment]
I am having all kinds of trouble now. Can't even get valet to work on Sierra without seeing "Valet requires Homebrew to be installed on your Mac."

I will close this for now and investigate the bigger issue. Thanks for your assistance.

**Comment by llaski** [comment]
Just in case anyone comes across this recently like I did, you need to have a paid ngrok plan in order to use custom subdomains :/
