### ISSUE TITLE
Valet secure does not work

### ISSUE THREAD

**Issue by matthijs110** [laravel/valet#208]
```
OS: macOS Sierra 10.12.1
Valet version: 1.1.22
```

Hello,

When I execute the command `valet secure`, a message says that the site has been secured with a fresh TLS certificate (as it should). 

If I try to access (http and https) the website, it gives me a browser 404 (so Valet does not seem to run). If I unsecure the site however, it works fine.

What could be the problem? I tried to completely remove Valet (including `~/.valet`). Still no luck :/

**Comment by willvincent** [comment]
I _briefly_ experienced a similar issue going the other direction.. from secure to unsecure.. restarted valet and it was fine. Might be a caching issue with caddy perhaps?

**Comment by matthijs110** [comment]
Restarting Valet does not work unfortunately. Only `valet unsecure`.

**Comment by erikwestlund** [comment]
also having this issue

**Comment by sa7bi** [comment]
I'm also having the same problem :(

**Comment by ahmedash95** [comment]
+1 for this issue , can't figure it out.

**Comment by skybluesofa** [comment]
I found a gist by Adam Wathan about [Troubleshooting Valet on Sierra](https://gist.github.com/adamwathan/6ea40e90a804ea2b3f9f24146d86ad7f#where-to-look-for-errors) that helped me with this issue:

1. Connection refused to `https://mysite.dev`
2. Checked the Caddy start log at /tmp/com.laravel.valetServer.err
3. Found this error: open /Users/myusername/.valet/Log/access.log: no such file or directory
4. Discovered that the /Users/myusername/.valet/Log directory did not exist.
5. Created the directory
6. Ran CLI: `touch /Users/myusername/.valet/Log/access.log`
7. Ran CLI: `valet restart`
8. Re-checked the site at `https://mysite.dev`. Success!

**Comment by ahmedash95** [comment]
@skybluesofa thanks but It didn't work with me .. also valet crashed  after run secure command and it won't start until I run valet unsecure then valet start again

**Comment by adamwathan** [comment]
@ahmedash95 did you have Nginx already installed before installing Valet?

Try `valet stop && brew uninstall --forge nginx`, then re-run `valet install` to make sure nginx is installed with the correct flags.

**Comment by ahmedash95** [comment]
@adamwathan It works .. thanks man

**Comment by mitoop** [comment]
When use valet secure,nginx needs `ngx_http_v2_module`.
In mac,`valet stop && brew uninstall --forge nginx` and `brew install nginx --with-http2` now it works. the option `--with-http2` activate the `ngx_http_v2_module`.

**Comment by hassanazimi** [comment]
still not working

**Comment by joshmanders** [comment]
@hassanazimi can you show us your version, what error message you get, etc.?

**Comment by hassanazimi** [comment]
@joshmanders Unfortunately there isn't any error. Everything runs well but when I wanna secure a domain like `valet secure domain` everything stops working. All webpages "cannot resolve the address". I have to the remove `rm -rf ~./valet` and then `valet install` then `valet park` and everything works again. Summary: I can't secure a domain.

**Comment by joshmanders** [comment]
Try going into the project directory and running `valet secure` without the domain and see if that works.

**Comment by hassanazimi** [comment]
@joshmanders Still the same.

**Comment by blyleven** [comment]
Had the same problem and it turned out I needed to update to the latest version of Laravel Valet.
I was using 2.0.3 and now updated to 2.0.4 which resolved my problems.

- valet stop
- valet uninstall
- composer global require laravel/valet
- valet install
- valet restart

Hope this helps!

**Comment by hassanazimi** [comment]
@blyleven well i'm using `2.0.4`

**Comment by bohraji** [comment]
@blyleven this worked for me. Thnx!

**Comment by daddydanielt** [comment]
@adamwathan It works .. thanks

**Comment by hassanazimi** [comment]
Still `valet secure` stops everything from working and I can't figure out why. I'm sure it adds a certificate to `~/.valet` directory but everything stops from working.
I have to remove `~/.valet` directory and install valet again. this issue is about `valet secure`not the valet itself.

**Comment by KickDu** [comment]
I confirm, hassanazimi: I get the same issue without any of the above solution

**Comment by adamwathan** [comment]
Can't replicate this, working as expected here.

Can you guys provide any more info about *what* isn't working? Is PHP running? Is nginx running? Is dnsmasq running? What do the log files say in PHP and nginx?

**Comment by hassanazimi** [comment]
@adamwathan Like I said when I install valet it works, which means php Nginx work as well but when I want to add or secure a domain, I can't access to the laravel dev domains whatsoever, even the ones I didn't want to be secured. Php and nginx do work though. The only thing I have to do is to remove ~/.valet directory and install valet again. Can't secure any domains locally.

**Comment by adamwathan** [comment]
Are PHP and nginx running *after* you run `valet secure` though? And what do the log files for nginx and PHP say after running that command?

Does `ps aux | grep php` list several `php-fpm` instances as running, like below?

![image](https://user-images.githubusercontent.com/4323180/27958455-18451424-62f1-11e7-8dff-af31a3a2f262.png)

Depending on if you are running 7.0 or 7.1, you'll find the FPM log in one of these locations:

```
/usr/local/opt/php70/var/log/php-fpm.log
/usr/local/opt/php71/var/log/php-fpm.log
```

...and the nginx log will be here:

```
~/.valet/Log/nginx-error.log
```

After running valet secure, what happens when you run:

```
sudo nginx -t
```

Does `nginx -V` list that it was compiled `--with-http_v2_module` or does that not show up?

**Comment by KickDu** [comment]
php is running
and
sudo nginx -t
provides
nginx: the configuration file /usr/local/etc/nginx/nginx.conf syntax is ok
nginx: configuration file /usr/local/etc/nginx/nginx.conf test is successful
sorry I am quite new on this: can't find logs but on my side the path was probably not installed correctly for composer

**Comment by KickDu** [comment]
so strange, for:
/usr/local/opt/php70/var/log/php-fpm.log
/usr/local/opt/php71/var/log/php-fpm.log
there is not directory for php70 and php71 gives an empty log - normal ?!?

**Comment by KickDu** [comment]
~/.valet/Log/nginx-error.log
is empty too => ?!?

**Comment by hassanazimi** [comment]
@adamwathan 

1. These files are empty (no issues there)

```
/usr/local/opt/php71/var/log/php-fpm.log
~/.valet/Log/nginx-error.log
```

![screen shot 2017-07-28 at 15 01 30](https://user-images.githubusercontent.com/4809004/28720768-0ffe680e-73a6-11e7-954a-3ef67aa13561.png)

2. `ps aux | grep php` returns as follows: (no issues there)

![screen shot 2017-07-28 at 15 01 08](https://user-images.githubusercontent.com/4809004/28720871-42d78f4e-73a6-11e7-8672-3448944feca5.png)

3. BUT when I run `sudo nginx -t` this is what it returns: 

```
nginx: [emerg] BIO_new_file("/Users/hasan_azimi0/.valet/Certificates/persianwoo.dev.crt") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/Users/hasan_azimi0/.valet/Certificates/persianwoo.dev.crt','r') error:2006D080:BIO routines:BIO_new_file:no such file)
nginx: configuration file /usr/local/etc/nginx/nginx.conf test failed
```
![screen shot 2017-07-28 at 15 02 01](https://user-images.githubusercontent.com/4809004/28720874-4826b786-73a6-11e7-8496-279e18783b70.png)

Any clue Adam?

**Comment by adamwathan** [comment]
Sounds like a certificate file didn't get generated or somehow got deleted.

Try running the following which will force Valet to regenerate all certs:

```
valet domain blah
valet domain dev
```

**Comment by hassanazimi** [comment]
Thanks Adam but still no luck.

**Comment by adamwathan** [comment]
Try deleting the contents of ~/.valet/Certificates and ~/.valet/Nginx and then restarting valet.

**Comment by hassanazimi** [comment]
When I try delete the content of both folders the site runs again but its not secure.

**Comment by adamwathan** [comment]
Ok so now what happens if you try to secure it again from scratch, now that things are working...?

**Comment by adamwathan** [comment]
Ok so now what happens if you try to secure it again from scratch, now that things are working...?

**Comment by hassanazimi** [comment]
I can see the it generates certificates in `Certificates` directory and one file in `Nginx` directory and when i open the browser `This site can’t be reached` and when i delete the files and `valet restart` it comes back again.

**Comment by adamwathan** [comment]
So when nginx is complaining about the file that doesn't exist, does it exist? Is there a difference in the file name nginx is looking for vs. the one you actually see in the certificates folder?

**Comment by hassanazimi** [comment]
It's the same, have a look:

![screen shot 2017-07-28 at 19 38 47](https://user-images.githubusercontent.com/4809004/28731615-84c4cfcc-73cc-11e7-9a57-410c543ffd3f.png)

I think it tries to read but somehow can't.

**Comment by adamwathan** [comment]
Can you screenshot running `ls -la` inside of the Nginx folder?

**Comment by hassanazimi** [comment]
Sure:

![screen shot 2017-07-28 at 19 42 27](https://user-images.githubusercontent.com/4809004/28731724-ee9ffbec-73cc-11e7-9fd7-4552b8a4c8d0.png)

**Comment by adamwathan** [comment]
So actually the .crt file doesn't exist in the certificates directory which must be causing the issue. Probably something is failing during the secure stuff when trying to create the certificate.

The best I can recommend to help debug is trying to run all the steps you see in the code here manually in your terminal, and seeing if you get any errors:

https://github.com/laravel/valet/blob/master/cli/Valet/Site.php#L200-L267

**Comment by uicosp** [comment]
https://github.com/laravel/valet/blob/master/cli/Valet/Site.php#L239

just change `/C=/ST=/O=/localityName=/commonName=*.%s/organizationalUnitName=/emailAddress=/` to
`/commonName=*.%s/` solved the problem

**Comment by hassanazimi** [comment]
@uicosp I actually favorited your response because it DID fix it.

Thanks

**Comment by agraynel** [comment]
I have tried everything including delete .~/valet folder and reinstall everything, but I cannot start the website.
 I used to start it successfully. But after I updated homebrew, I can't open the website anymore. Any help?

**Comment by joshmanders** [comment]
probably getting php errors, you'll have to `brew list` and see if you still have `php71` packages installed. If so uninstall them and reinstall `php@7.1` as they renamed the formula

**Comment by SaifurRahmanMohsin** [comment]
I tried @mitoop solution to remove nginx and re-install with the --with-http2 flag. That didn't work as it gave me an unknown flag warning during the install (in the console logs) and continued to install nginx which failed to fix the bug.

I then checked the available flags using `brew options nginx` to see there was no —with-http2 flag. So I did a `brew uninstall nginx` and then did a `brew install nginx-full --with-http2` (this had the necessary flag and you can check using `brew options nginx-full`). Once installed, I did a `valet install`, cd’ed into the project folder and did a `valet secure` and `valet open`. It worked fine in https.

**Comment by hassanazimi** [comment]
@SaifurRahmanMohsin thats great to know. thanks for taking the time to update this.

**Comment by josegus** [comment]
not working, tried everything

**Comment by drbyte** [comment]
> not working, tried everything

Please open a new issue, and include the output from `valet diagnose`

**Comment by xeisu** [comment]
The only command that worked for me was `sudo nginx -s stop && sudo nginx`
