### ISSUE TITLE
[Help Wanted] 404 - Not Found

### ISSUE THREAD

**Issue by marktopper** [laravel/valet#210]
I had Valet working quite normal until I did this.

Removed PHP 7.0 and added PHP 5.6, found out that it didn't worked and tried to undo it
```
brew unlink php70
brew install php56
brew link php56

// undoing
brew unlink php56
brew uninstall php56
brew link php70
```

However after this I can not get it to work, any ideas?

**Comment by KorvinSzanto** [comment]
You'll need to reinstall valet, just run valet install and valet restart

**Comment by marktopper** [comment]
@KorvinSzanto That's what I though too. However, still `404 - Not found`.

Any other ideas?

Log: https://gist.github.com/marktopper/2cb626653169fdacef61a28b42e45dd5

**Comment by marktopper** [comment]
I noticed something, it always seems to **not** install `php70` and `dnsmasq`, cause I can run `valet install` twice and it still tells that its not installed and that it will install.

```Marks-MacBook-Pro.local ~/.composer/vendor/laravel/valet/bin $ valet install
[php70] is not installed, installing it now via Brew... 🍻
[dnsmasq] is not installed, installing it now via Brew... 🍻

Valet installed successfully!
Marks-MacBook-Pro.local ~/.composer/vendor/laravel/valet/bin $ valet install
[php70] is not installed, installing it now via Brew... 🍻
[dnsmasq] is not installed, installing it now via Brew... 🍻

Valet installed successfully!```

**Comment by marktopper** [comment]
I managed to remove every bit of Valet, and then complete

**Comment by chrisjohnstone** [comment]
@marktopper Hi Mark, could you describe what you did to remove every bit of Valet? I'm experiencing the same problem  - especially when trying to run Elixir and `gulp watch` to activate browsersync.

**Comment by Rozkalns** [comment]
@chrisjohnstone can't wait for next update of your investigation!

**Comment by chrisjohnstone** [comment]
I thought my previous answer solved the issue but whenever I try and access a local site after a reboot, I have to run `valet install` and it tells me php70 and dnsmasq are not installed. It installs them then everything works fine... until next reboot.

**Comment by tmartin31** [comment]
I'm experiencing a similar issue. Valet always tried to install dnsmasq and/or php70 when running `valet install` or `valet domain`.

```
➜  ~ valet install
[php70] is not installed, installing it now via Brew... 🍻
[dnsmasq] is not installed, installing it now via Brew... 🍻
Valet installed successfully!

➜  ~ valet domain io
[dnsmasq] is not installed, installing it now via Brew... 🍻
valet domain dev
Your Valet domain has been updated to [io].

➜  ~ valet domain dev
[dnsmasq] is not installed, installing it now via Brew... 🍻
Your Valet domain has been updated to [dev].

➜  ~ valet install
[php70] is not installed, installing it now via Brew... 🍻
[dnsmasq] is not installed, installing it now via Brew... 🍻
Valet installed successfully!
```

**Comment by tmartin31** [comment]
> Hold that! I did a bit more digging, uninstalled php56 via homebrew. Uninstalled Valet and deleted the .valet folder and reinstalled again. Again, it told me php70 and dnsmasq weren't installed, although I they were but not it seems to be working.

Same. Tried uninstalling php70 and dnsmasq via Homebrew and reinstalling Valet from scratch, but I'm still getting the errors/output when trying to use Valet.

**Comment by tmartin31** [comment]
Updating to Valet 2.0 solved the problem, but I'm now getting a 502 when trying to view any parked domains.

**Comment by chrisjohnstone** [comment]
Updated to 2.0.3 but I'm still totally stumped. I've completed removed all versions of php from my machine as well as homebrew and valet but after installing everything afresh, I still get a `404 - Not Found` error.

`brew services list` looks like:

```dnsmasq started root  /Library/LaunchDaemons/homebrew.mxcl.dnsmasq.plist
mysql   started chris /Users/chris/Library/LaunchAgents/homebrew.mxcl.mysql.plist
nginx   started root  /Library/LaunchDaemons/homebrew.mxcl.nginx.plist
php71   started root  /Library/LaunchDaemons/homebrew.mxcl.php71.plist
```
Not sure where to go from here.

**Comment by adamwathan** [comment]
@chrisjohnstone Have you linked some sites or parked a folder? It sounds like Valet is working (that 404 screen is coming from Valet), but it can't find the particular site you are looking for.

Where is your project located on your hard drive, and what is the output of `valet paths` and `valet links`?

**Comment by chrisjohnstone** [comment]
@adamwathan thank you for taking the time to comment.

Here's the output of `valet paths`

```
[
    "/Users/chris/.valet/Sites",
    "/Users/chris/Sites"
]
```
and `valet links`

```
total 16
drwxr-xr-x   3 chris  staff   102  2 Mar 14:57 .
drwxr-xr-x  11 chris  staff   374  2 Mar 14:54 ..
-rw-r--r--@  1 chris  staff  6148  2 Mar 14:57 .DS_Store
```

Valet is asking me for a password i.e. sudo for these commands. Is that expected?

An example of my site path is `/Users/chris/Sites/l54` and then the document root is in a `www` folder within each project.

**Comment by adamwathan** [comment]
Got it, what types of projects are they? Are they something standard that Valet supports out of the box, like a Laravel or Symfony app?

If it's a Laravel app (guessing from the `l54` name), did you rename `public` to `www`, or is the whole app nested inside `www`?

**Comment by chrisjohnstone** [comment]
So far all laravel apps. The `public` directory sits within a `www` parent. The laravel file structure is maintained therein.

**Comment by adamwathan** [comment]
Got it, so Valet is confused by that top level `www` folder. It's expecting each subfolder in `/Users/chris/Sites` to be a site, not a site nested in an extra folder that Valet doesn't understand.

Try this:

```
cd /Users/chris/Sites/l54/www
valet link my-app.dev
```

...then visit `my-app.dev` in the browser and see if you see your site.

**Comment by chrisjohnstone** [comment]
Ok, tried that but I'm still returning the same 404.

`A [my-app.dev] symbolic link has been created in [/Users/chris/.valet/Sites/my-app.dev].`

I restarted Valet and tried again with the same outcome. Again, it asked for my root password when restarting.

**Comment by KorvinSzanto** [comment]
Use 'valet link my-app'. Including .dev when linking will make your URL
"my-app.dev.dev"

**Comment by adamwathan** [comment]
Yeah @KorvinSzanto is right, typo on my part :)

**Comment by chrisjohnstone** [comment]
That nailed it!

Thanks @adamwathan, @KorvinSzanto.
