### ISSUE TITLE
Partial response with streaming does not work properly

### ISSUE THREAD

**Issue by FrodeMMeling** [laravel/valet#212]
Hello
For some reason, my mp4 HTML5 streaming controller does not work on IOS devices when running in valet. It works in php artisan serv, but not using valet.

It works on Mac with Safari and Chrome, but not on IOS devices.
Any Ideas why this is happening?

I can share some code if needed

**Comment by adamwathan** [comment]
This is unfortunately a known issue with how static files are served in Valet currently; we are working towards pushing that responsibility to the webserver itself (Caddy in our case) but a bug in the current version of Caddy has prevented us from doing so.

We are likely going to switch over to nginx soon and have experimental support in another branch.

If you're brave, you can try updating to `dev-nginx` in composer.json and re-run `valet install` to switch to the nginx-based version we are working on. No known issues so far but we want to run through the upgrade process a few more times, smooth out any issues, and update the documentation before tagging a release.

**Comment by FrodeMMeling** [comment]
Ok, I will try nginx.
thanks

**Comment by FrodeMMeling** [comment]
Switched to dev-nginx.. Working now.. Thanks

**Comment by FrodeMMeling** [comment]
Hello
I installed this on 2 macs. First mac its working fine, second mac, static files are not delivered.. I get a response, but its empty, no errors. branch is: nginx

How can I debug this?
Suggestions?

**Comment by FrodeMMeling** [comment]
I resolved this. Its a bug I will create new issue for it.
