### ISSUE TITLE
branch-nginx: Always reinstalls brew packages

### ISSUE THREAD

**Issue by FrodeMMeling** [laravel/valet#214]
I am testing the nginx branch, and every time I run valet install, it claims nginx, php70 and dnsmasq is not installed and tries to re-install.

Note! On OSX Sierra

**Comment by campaignzee** [comment]
I'm seeing the same issue on master as well on macOS Sierra.

**Comment by edalzell** [comment]
Yes after upgrading (I'm not using nginx) I ran `valet install` like recommended and the first time it tried to update homebrew:
```
[php70] is not installed, installing it now via Brew... 🍻
==> Installing php70 from homebrew/php
Error: php70-7.0.12_5 already installed
To install this version, first `brew unlink php70`
```

Then I manually upgraded everything on homebrew and tried again:
```
emdMB:Sites erin$ valet stop
Valet services have been stopped.
emdMB:Sites erin$ valet start
Valet services have been started.
emdMB:Sites erin$ valet install
[php70] is not installed, installing it now via Brew... 🍻
[dnsmasq] is not installed, installing it now via Brew... 🍻

Valet installed successfully!
emdMB:Sites erin$ valet restart
Valet services have been restarted.
emdMB:Sites erin$ valet --version
Laravel Valet version 1.1.22
```

Weird.

**Comment by taylorotwell** [comment]
I believe this should be fixed now that brew list is run as the user and not sudo.
