### ISSUE TITLE
How to link online domain name to a valet?

### ISSUE THREAD

**Issue by latrell** [laravel/valet#215]
During development of Wechat app test domain name must be online, so I don't need to be mapped. Dev domain name suffix, how to do?

```
cd ~/Code/weichatapp
valet link www.online-domain.com
sudo echo '127.0.0.1 www.online-domain.com' >> /etc/hosts
```

> http://www.online-domain.com
> 404 - Not Found

**Comment by danielbachhuber** [comment]
After a ton of debugging, I figured out that this was much easier than I expected.

```
$ cd ~/projects/
$ valet park
This directory has been added to Valet's paths.
$ mkdir my-project
# my-project.dev is now served by Valet
$ ln -s my-project my-project.com
# my-project.com is now served by Valet
```

**Comment by michaeldyrynda** [comment]
Why not just use ngrok to do this? `valet share` and point Wechat to that?

**Comment by straube** [comment]
@danielbachhuber is this supposed to work on recent Valet versions? I'm trying to use your hack but it's not working.
