### ISSUE TITLE
Bug - Going from Caddy to nginx

### ISSUE THREAD

**Issue by FrodeMMeling** [laravel/valet#216]
Switched to branch nginx and symptoms were that no static files was served. This was not the problem. The issue is that nginx branch, needs to check if old config with Caddy is running and stop (uninstall) it, before starting nginx.

there are no error starting valet services, but I think nginx Service has not been able to start. So caddy was running instead of nginx..

Workaround:
- Kill Caddy process
- run valet start

**Comment by taylorotwell** [comment]
Yeah key to run `valet stop` and `valet uninstall` I think before switching to Nginx.

**Comment by shahbaaz** [comment]
Even if you stop and uninstall valet. Caddy server still runs in the background. To get rid of Caddy server, follow these instructions:

`valet stop`
`valet uninstall`

Delete these executable files 
`sudo rm /usr/local/bin/valet `
and
`sudo rm /Users/{home-directory}/.composer/vendor/bin/valet`
(replace {home-directory} with your home directory name)

Make sure Caddy server and valet is removed from your computer completely.

when you type `valet` in terminal. You should see: `command not found: valet`

when you type `curl -I foo.dev`. You should see: `curl: (6) Could not resolve host: foo.dev`

Now install valet following the instructions in documentation: https://laravel.com/docs/5.4/valet#installation

Still if it doesn’t work. Type these command in your terminal:
`brew services restart nginx && brew services restart php71`

`valet start` or `valet restart`
