### ISSUE TITLE
Seeing "Valet requires Homebrew to be installed on your Mac." on macOS 12.10.1 on Valet 1.1.22 and dev-master

### ISSUE THREAD

**Issue by campaignzee** [laravel/valet#217]
I'm able to serve a static HTML site with Valet without issues, but as soon as I load a Laravel app I get the message "Valet requires Homebrew to be installed on your Mac." Brew is installed in the normal location:

`$ which brew
/usr/local/bin/brew`

The only place in the code I see the message is "cli/includes/compatibility.php":

`if (exec('which brew') !== '/usr/local/bin/brew' && ! $inTestingEnvironment) {
    echo 'Valet requires Brew to be installed on your Mac.';
    exit(1);
}`

So it does appear to be in the right location, so not sure why I am getting the message.

I tried dev-master as well and am seeing the same error.

I'm running dev-master on macOS 10.11.6 and it works as expected. Any ideas why it's failing on Sierra?

**Comment by campaignzee** [comment]
I discovered the cause. I had accidentally required Valet locally in a project, so the Laravel app was running that version, rather than the global Valet. Removing it seems to have fixed the issue.

**Comment by arjunbanker** [comment]
i'm running into this issue , what does it mean to require valet locally?

**Comment by adamwathan** [comment]
It means you ran `composer require laravel/valet` somewhere instead of `composer global require laravel/valet`

**Comment by arjunbanker** [comment]
I ran `composer global require laravel/valet` and when I run "which brew"
from the cmd line, i see "/usr/local/bin/brew"

but I still get "Valet requires Homebrew to be installed on your Mac.", interestingly the line has changed in compatability.php to "if (exec('which brew') == '' && ! $inTestingEnvironment) .."

**Comment by arjunbanker** [comment]
I removed ./vendor and re-ran composer install and it seemed to take me past this error!

**Comment by dylanhegarty** [comment]
What do you mean removed ./vendor? from where? did this cause any future problems?

**Comment by AlemAblat** [comment]
The main is your after install Home brew then run install valet
brew.sh or 
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

**Comment by agalvislopez** [comment]
install homebrew:
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
