### ISSUE TITLE
Maximum upload size

### ISSUE THREAD

**Issue by nathobson** [laravel/valet#224]
I've been facing an issue with maximum upload sizes out of the box with Valet with WordPress. It seems very low, around 8MB.

Steps I've tried:

- Editing `/usr/local/etc/php/7.0/php.ini`
- Editing the WordPress `function.php` file
- Last ditch attempt was using various plugins but as expected, they get ignored

Any ideas?

**Comment by taylorotwell** [comment]
This will be easier resolved when we switch to Nginx soon.
