### ISSUE TITLE
Nginx sends a 404 when navigating to index.php? url even if the file exists

### ISSUE THREAD

**Issue by KorvinSzanto** [laravel/valet#232]
My project has an index.php and tries to serve a request like `/index.php?foo=bar`. With 2.0.0 it seems that this is no longer possible for some reason. Looking at my error log, I see this:

```
2016/12/08 16:55:29 [error] 28461#0: *552 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 127.0.0.1, server: , request: "GET /index.php?foo=bar HTTP/1.1", upstream: "fastcgi://unix:/Users/Korvin/.valet/valet.sock:", host: "site.dev"
```

I've been trying to tweak my `/usr/local/etc/nginx/valet/valet.conf` to get it to work properly but I can't seem to find a working combination of settings. Any idea what might be wrong?

**Comment by shiroamada** [comment]
Mine also having the same issue, I trace to the config file. I found that
/Users/shiroamada/.valet/valet.sock the **valet.sock** is missing.

**Comment by Kimleang** [comment]
mine also having the same issue, I got File not found for all my basic site that ending with` .php` files.

**Comment by playwellsteve** [comment]
I'm having the same issue with Craft cms sites. The homepage works, but all links fail. The nginx error log shows the same error as KorvinSzanto reports.

**Comment by adamwathan** [comment]
Hey folks! We just tagged 2.0.1 which we think will fix this, give it a spin.

**Comment by shiroamada** [comment]
how to update? run valet update?

**Comment by adamwathan** [comment]
`composer global require laravel/valet:^2.0.1 && valet install`

**Comment by playwellsteve** [comment]
2.0.1 helps. For Craft CMS, links work, but attempting to access the admin panel fails with:

Can’t run Craft CMS :(

Your server doesn’t meet the following requirements to run Craft CMS:

Unable to determine URL path info. Please make sure $_SERVER["PATH_INFO"] (or $_SERVER["PHP_SELF"] and $_SERVER["SCRIPT_NAME"]) contains proper value.
Please talk to your host/IT department about upgrading your server.

**Comment by shiroamada** [comment]
Bravo! Positive from my side .Mine is working!
Just need to make sure your nginx process is totally killed. and run the valet install and start.
Thanks @adamwathan

**Comment by KorvinSzanto** [comment]
This is definitely fixed by a501ebcd5b15121068875d5e19019d8881afa29f, but unfortunately only for HTTP and not for HTTPS. See my comments on that commit.

**Comment by adamwathan** [comment]
Closing this one, can start a new issue for the HTTPS stuff.

**Comment by RyanRoberts** [comment]
@playwellsteve Hey Steve, did you ever fix that Craft admin panel problem? I'm facing it just now and struggling to find a fix.

**Comment by Harry-Harrison** [comment]
@RyanRoberts going through `/index.php?p=admin` works for me instead. Really strange and quite annoying.
