### ISSUE TITLE
Valet 2.0 ngrock redirect

### ISSUE THREAD

**Issue by marianvlad** [laravel/valet#233]
redirected you too many times when I use ngrock.

**Comment by hasusuf** [comment]
Same to me here, specially with Wordpress.

**Comment by marianvlad** [comment]
For me in Laravel

**Comment by rogervila** [comment]
with 2.0.1 too?

**Comment by marianvlad** [comment]
On 2.0.1 I have "404 - Not Found"

**Comment by alexblunck** [comment]
This might be related to #148. I was having the same redirect problem. Using `valet unsecure` & then `valet share` seems to work.
