### ISSUE TITLE
WordPress admin URLs return 404

### ISSUE THREAD

**Issue by A5hleyRich** [laravel/valet#236]
After upgrading to Valet 2.0, WordPress admin URLs no longer work.

The front-end works as expected, as does `http://wordpress.dev/wp-admin/`

But attempting to access specific admin areas such as `http://wordpress.dev/wp-admin/edit.php` returns `File not found`.

Nginx log entry:

`[error] 204#0: *122 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 127.0.0.1, server: , request: "GET /wp-admin/edit.php HTTP/1.1", upstream: "fastcgi://unix:/Users/ashley/.valet/valet.sock:", host: "wordpress.dev", referrer: "http://wordpress.dev/wp-admin/"`

**Comment by sidneywidmer** [comment]
I have exactly the same issue, it looks like since the 2.0 update requests to .php files don't work anymore. It seems like it tries to load the file directly from /foo.php (e.g the root of your drive) where it obviously can't find it. What is the desired behaviour here? Should these direct calls also be routed through server.php?

**Comment by victorhguillen** [comment]
I can access to the admin, but I can't access to the plugins, post, pages etc..

**Comment by tmartin31** [comment]
Same. I can't load any PHP files directly since updating to Valet 2.0 – for example`test.dev` loads index.php, but `test.dev/index.php` returns a `File not found` error.

**Comment by adamwathan** [comment]
Try Valet 2.0.1! :) Thanks.

**Comment by tjFogarty** [comment]
Legend. That works, thanks @adamwathan !

**Comment by tmartin31** [comment]
@adamwathan Back in the game. Thanks!

**Comment by victorhguillen** [comment]
I update it and I still have problems, I have to do anything else? @adamwathan

**Comment by aaemnnosttv** [comment]
This only seems to fix the problem for sites that are loaded via http.

After trying the update several times, I tried on an http site and it worked.  As soon as I run `valet secure` I get the same `File not found.` error.

This is probably related to #232.

**Comment by victorhguillen** [comment]
nvm @adamwathan  I just restart the OS and is working, but I tried restarting brew services and it doesn't work I had to do a full restart.

**Comment by aaemnnosttv** [comment]
@adamwathan this is still a problem for me on https. Tried reboot as well, to no avail.

![image](https://cloud.githubusercontent.com/assets/1621608/21060987/ff4caefc-be52-11e6-82e1-01b1ffc18124.png)
Any thoughts?

**Comment by adamwathan** [comment]
It's related to this, looking into it now. 

https://github.com/laravel/valet/commit/a501ebcd5b15121068875d5e19019d8881afa29f

**Comment by boogah** [comment]
@adamwathan Since this issue appears to be closed now, is there a new issue tracking this?

I only ask because I'm seeing the same issues on HTTPS as @aaemnnosttv and want to stay on top of the situation.

**Comment by adamwathan** [comment]
This has been fixed, just not tagged: https://github.com/laravel/valet/commit/6376bfca82ed34acf33b188a13723a04b14150c7

**Comment by jackmcdade** [comment]
Getting the same issue with Statamic's `/installer.php`. I opened #255 but maybe it's a dupe. I'm running on `dev-master` with no success and lost a whole night to trying to debug it. :(

**Comment by aaemnnosttv** [comment]
Thanks @adamwathan, that fixed it!

Regarding the versioning, I think it's still important if only for having known states to revert to when necessary. Anyone still having trouble with 2.0 should be able to revert back to 1.x just as fast and be back in business, no?
