### ISSUE TITLE
Valet 2 uses wrong PHP version

### ISSUE THREAD

**Issue by christophrumpel** [laravel/valet#237]
Hey,

I just upgraded valet to version 2 and suddenly it is using a wrong version oh PHP. (5.6 instead of 7.0) I then installed PHP71 (with Homebrew) but Valet is still using PHP 5.6.

Any idea how I can fix that?

**Comment by tmartin31** [comment]
What's it say when you run these commands?

```
which php
php -v
```

**Comment by hasusuf** [comment]
You might need to unlink PHP 5.6 and link PHP 7.0 or 7.1 using brew CLI,

```
 brew unlink php56
 brew link php70
```

**Comment by burakerdem** [comment]
I have the same issue. Valet uses previously installed v7.0.9. I already unlinked v7.0.9 and linked v7.1. `which php` and `php -v` displays the following info.

    /usr/local/opt/php71/bin/php

    PHP 7.1.0 (cli) (built: Dec  2 2016 11:32:42) ( NTS )

**Comment by christophrumpel** [comment]
I did remove all old PHP versions on now it seems to work again. But I can't connect to MariaDB now, guess this is another problem.

**Comment by KorvinSzanto** [comment]
Make sure you restart valet if you're switching php versions. FPM needs to
be stopped then started again with the new PHP version.

Testing this locally I cannot replicate.

**Comment by chaoszcat** [comment]
I'm facing the same issue and I couldn't change it. I upgraded my php71 to php72 using brew, restarted valet, but it's still showing wrong version when I do `phpinfo();`

    $ brew list | grep php
    php72
    php72-imagick
    php72-opcache
    php72-xdebug
    phpunit

    $ which php
    /usr/local/bin/php

    $ php -v
    PHP 7.2.1 (cli) (built: Jan  5 2018 17:34:14) ( NTS )
    Copyright (c) 1997-2017 The PHP Group
    Zend Engine v3.2.0, Copyright (c) 1998-2017 Zend Technologies
        with Zend OPcache v7.2.1, Copyright (c) 1999-2017, by Zend Technologies
        with Xdebug v2.6.0beta1, Copyright (c) 2002-2017, by Derick Rethans


    $ valet restart
    Restarting php72...
    Restarting nginx...
    Valet services have been started.

But phpinfo() still telling me it's running on PHP 7.1.8, with php.ini pulling from `/usr/local/etc/php/7.1`.

**Comment by RobertCordes** [comment]
@chaoszcat You, sir, are my hero.

**Comment by jpwitkowski11** [comment]
This resolved my issues after the 3/31/2018 brew upgrade (move of php into homebrew core) and the ensuing issues. Thanks @chaoszcat!!!

**Comment by mikerogne** [comment]
Resolved my issue as well, thanks @chaoszcat!

**Comment by therealchiko** [comment]
Worked! thanks @chaoszcat

**Comment by bronze** [comment]
Jesus rollerblading christ thank you @chaoszcat !

**Comment by mijewe** [comment]
For me brew didn't report having any services running, but doing a `ps -ef | grep php` showed an old php71 service still running.

In fact, if I stopped the brew php service, Valet would still be working with php71.

To solve this I had to stop the process using `launchctl unload <path to plist>`, where for me the path was `/Library/LaunchDaemons/homebrew.mxcl.php71.plist`.

Then I run `valet restart` and it grabbed the correct PHP version.

I hope that helps somebody and saves them half a day of hair pulling.

Sources:
https://stitcher.io/blog/php-73-upgrade-mac
https://superuser.com/questions/159486/how-to-kill-process-in-mac-os-x-and-not-have-it-restart-on-its-own

**Comment by nathobson** [comment]
@mijewe That just worked for me PHP 7.2 -> 7.4. THANKS!

**Comment by r-martins** [comment]
I'm having the same problem here.. Tried to do `valet use 7.2` and although its using 7.2 in the console, when opening any site was using PHP 5.6.
I started to do `brew services stop valet-php@5.6`.. then it started using php 7.3... did the same again (brew services stop valet-php@7.3`).. and then it got the right version.

**Comment by drbyte** [comment]
@r-martins  wrote:
> I started to do `brew services stop valet-php@5.6`.. then it started using php 7.3... did the same again (`brew services stop valet-php@7.3`).. and then it got the right version.

Something's odd here. Note:

> **valet-php**@7.3

Where did the `valet-` prefix come from? 

The `laravel/valet` package does NOT name the services with a `valet-` prefix. Never has. It's always used Homebrew's default naming of `php`, not `valet-php`.

Evidently you're using some other unofficial spinoff of Valet [eg](https://github.com/weprovide/valet-plus/blob/d74a6823539af71d924344e3f4a4adfd0c92798c/cli/Valet/PhpFpm.php#L9)
You're certainly free to do that, but then you should also take your support questions to them.

**Comment by r-martins** [comment]
Hi @drbyte . Thanks for the reply and for your concern about this.
I started using mamp (which I used for several years), then I migrated to Valet (for 1 hour) and then I met valet+ where I am now. 
This is my current brew services list:

<img width="391" alt="magento1943____www_magento1943__-__var_www_magento1943_app_code_core_Mage_Install_Model_Installer_Config_php" src="https://user-images.githubusercontent.com/191149/74704565-f642c680-5264-11ea-962c-023bf57d6302.png">

I guess it was pulled as a dependency from henkrehorst/homebrew-php, which is used by valet/valet+, as per brew info below:

<img width="405" alt="magento1943____www_magento1943__-__var_www_magento1943_app_code_core_Mage_Install_Model_Installer_Config_php" src="https://user-images.githubusercontent.com/191149/74704735-9698eb00-5265-11ea-8912-e45babd4f5bf.png">

Currently I'm using valet on a detached branch [fa1205e](https://github.com/weprovide/valet-plus/commit/fa1205e). It was the latest version when I was installing and fighting against the acpu issue.

<img width="254" alt="magento1943____www_magento1943__-__var_www_magento1943_app_code_core_Mage_Install_Model_Installer_Config_php" src="https://user-images.githubusercontent.com/191149/74704871-fb544580-5265-11ea-98cc-f114f657ecca.png">

**Comment by webong** [comment]
It worked! thanks @chaoszcat

**Comment by grafxflow** [comment]
Thanks @chaoszcat

**Comment by antoninmasek** [comment]
Can't thank you enough @chaoszcat . I lost too much time on it already and `brew services stop php@7.4` finally worked!

**Comment by mertasan** [comment]
Usually it works.

`composer global update`

**Comment by SOSTheBlack** [comment]
Para mim resolveu somente desta forma

which php

rm -rf no caminho que aparecer

php -v

**Comment by eightyfive** [comment]
A mix of @chaoszcat and `brew cleanup` did it for me.

**Comment by gausam** [comment]
Use `brew services stop php@8.0.1` if you need to get PHP 8 out of the way after running `valet use php@7.4`.

**Comment by SOSTheBlack** [comment]
Run

```shell
valet use php@8.0 --force && sudo rm ~/.config/valet/valet.sock && valet restart && brew unlink php@7.2 && brew link --overwrite --force php@8.0 && sudo brew services restart --all && sudo rm ~/.config/valet/valet.sock && valet install && composer global update
```

**Comment by drbyte** [comment]
> Run
> 
> ```shell
> valet use php@8.0 --force && sudo rm ~/.config/valet/valet.sock && valet restart && brew unlink php@7.2 && brew link --overwrite --force php@8.0 && sudo brew services restart --all && sudo rm ~/.config/valet/valet.sock && valet install && composer global update
> ```

While that covers a lot of stuff, the latest Valet does most of it automatically nowadays.
