### ISSUE TITLE
SSL certificate problem: Invalid certificate chain

### ISSUE THREAD

**Issue by gaillafr** [laravel/valet#239]
After having upgraded to Valet v2.0.0 I'm facing errors with the SSL certificate.
I also tried to unsecure/secure again but didn't change anything…

**Comment by marcaube** [comment]
@gaillafr I don't know if my problem is the same as yours, but after executing the "secure" command I started having errors with SSL certificates. It affected brew, my iCloud syncing, the App Store and a bunch of other programs.

What fixed it for me is the instructions in the "Invalid or incorrect Certificates" section on https://support.apple.com/en-ca/HT203811.

1. go to /var/db/crls/
2. delete crlcache.db and ocspcache.db
3. restart the system
4. profit!
