### ISSUE TITLE
[Valet 2.0.1] NGINX sends 404 along with the response

### ISSUE THREAD

**Issue by DCzajkowski** [laravel/valet#242]
If I reach any asset I get a 404 response code, but the correct file is being served. Tested on a custom Valet Driver.

As a result, no asset is being loaded (as browser thinks it is non-existent).

![](http://i.imgur.com/HfV7sGf.png)

**Comment by KorvinSzanto** [comment]
I'm guessing this is related to #232, 2.0.1 fixed this issue with non-secured links but the issue still remains for secure links.

**Comment by DCzajkowski** [comment]
I thought so too, but I have 2.0.1 (as the title states) and am using a custom driver. The non-secure version of the site is being used.

**Comment by adamwathan** [comment]
Any chance you can share the custom driver?

**Comment by DCzajkowski** [comment]
Sure. That's the one: https://github.com/DCzajkowski/DistValetDriver/blob/master/DistValetDriver.php
Previously (on Valet 1.*) I used this one: https://github.com/DCzajkowski/DistValetDriver/commit/cd2bf724e4462bed539fd4b23ec924dc54acf178#diff-a9d515ca4fe8857358f29671a5d0b948, although that was just a misuse (but worked ><). 

I have already uninstalled Valet, updated it and reloaded NGINX.

**Comment by adamwathan** [comment]
This should be resolved in `dev-master` 👍
