### ISSUE TITLE
All Requests Fail After 2.0 install

### ISSUE THREAD

**Issue by mpash** [laravel/valet#245]
It appears that Valet, after a fresh installation and reboot, does not handle the urls I'm throwing at it. Might be an issue with PHP 7.1 or in general.

**Comment by mpash** [comment]
Did some digging and found out that valet does not update your hosts file to point to the Nginx instance.

**Comment by adamwathan** [comment]
Hosts file changes are not necessary, Valet uses dnsmasq to intercept all requests to your configured TLD.

Can you provide details of the actual issues you are seeing?

**Comment by UltraSimplified** [comment]
It might be something to do with `dnsmasq` - I had a problem with this,  it appeared I had two versions of it installed and it was unable to listen on port 80. If you run `dnsmasq` in the command line it will alert you to any problems.

Running these commands fixed this for me:

```
brew uninstall --force dnsmasq
composer global remove laravel/valet
composer global install laravel/valet
```

this gave me a clean working build of Valet 2

**Comment by mpash** [comment]
Thanks! I'll give it a try and close the issue if this works :)

**Comment by mikemand** [comment]
That last command should be `composer global require laravel/valet`.

Another thing to note: if you changed your domain with `valet domain` in Valet 1, you **must** do so again after installing Valet 2. It reverts the domain back to `dev`.
