### ISSUE TITLE
valet 2.0 ,brew check nginx but not nginx-full,etc

### ISSUE THREAD

**Issue by nickfan** [laravel/valet#250]
i installed nginx-full instead of nginx via brew,but valet 2.0 only check if `nginx` have installed

**Comment by Fuitad** [comment]
+1

I'm having issues because I have nginx installed via nginx-full :(

**Comment by Fuitad** [comment]
Pull request #286 created. I tested it and it worked fine :).

**Comment by Fuitad** [comment]
Here we go. Pull request #287. Very sorry about that.
