### ISSUE TITLE
Primary script unknown / File not found

### ISSUE THREAD

**Issue by jackmcdade** [laravel/valet#255]
When trying to hit the Statamic `installer.php` file, which is accounted for the in the StatamicDriver, I get a "File not found" error in my browser and the following nginx log:

```
2016/12/13 01:30:31 [error] 51517#0: *1 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 127.0.0.1, server: , request: "GET /installer.php HTTP/1.1", upstream: "fastcgi://unix:/Users/jack/.valet/valet.sock:", host: "example.dev"
```

I've tried everything I can think of, but can't get it to run any `.php` file that's not `index.php` no matter the driver settings.

**Comment by adamwathan** [comment]
Are you not able to get this far?

![image](https://cloud.githubusercontent.com/assets/4323180/21141285/51c31090-c10a-11e6-8f32-be8fe6cc701c.png)

**Comment by adamwathan** [comment]
If you are running `dev-master`, make sure you run `valet install` again to update your local nginx config.

Your `/usr/local/etc/nginx/valet/valet.conf` file should look mostly like this:

```
server {
    listen 80 default_server;
    root /;
    charset utf-8;

    location /41c270e4-5535-4daa-b23e-c269744c2f45/ {
        internal;
        alias /;
        try_files $uri $uri/;
    }

    location / {
        rewrite ^ /Users/adamwathan/.composer/vendor/laravel/valet/server.php?$query_string last;
    }

    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }

    access_log off;
    error_log /Users/adamwathan/.valet/Log/nginx-error.log;

    error_page 404 /Users/adamwathan/.composer/vendor/laravel/valet/server.php;

    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass unix:/Users/adamwathan/.valet/valet.sock;
        fastcgi_index /Users/adamwathan/.composer/vendor/laravel/valet/server.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /Users/adamwathan/.composer/vendor/laravel/valet/server.php;
    }

    location ~ /\.ht {
        deny all;
    }
}
```

The most important bit is the:

`fastcgi_param SCRIPT_FILENAME /Users/adamwathan/.composer/vendor/laravel/valet/server.php;`

**Comment by jackmcdade** [comment]
Yep I had done all those things multiple times, but that wasn't what my `valet.conf` showed. I had been updating my global composer with `dev-master`. But then I remembered to update the valet repo i had checked out, which brought my .conf up to date.

I don't get a File Not Found error anymore, but rather a 404 routed through my index.php instead of actually running the `installer.php` file. My log now shows this error:

```
2016/12/13 09:24:33 [error] 4023#0: *16 rewrite or internal redirection cycle while processing "/Users/jack/Projects/valet/server.php", client: 127.0.0.1, server: , request: "GET /site/themes/redwood/js/redwood.js HTTP/1.1", upstream: "fastcgi://unix:/Users/jack/.valet/valet.sock", host: "example.dev", referrer: "http://saratogachimneysweep.dev/installer.php"
```

**Comment by adamwathan** [comment]
@jackmcdade Super weird, if you have time I can hop on ScreenHero with you and see if it's something we can figure out.

**Comment by jackmcdade** [comment]
Yeah def, I'm free. I'm `jack@statamic.com` on there.

**Comment by jackmcdade** [comment]
Resolved. I had been configuring my Statamic sites like `/Sites(valet parked here)/domain/public/*` which was actually just using the basic driver. If I move the site up a level, the Statamic Driver kicks and I'm good to go. Thanks for the help @adamwathan!
