### ISSUE TITLE
POSTMAN not able to resolve valet secure website.

### ISSUE THREAD

**Issue by shiroamada** [laravel/valet#257]
I run valet secure one of my laravel project.
When I use POSTMAN do POST https://myproject.dev/ajaxrequest
Below is the response from POSTMAN

> Could not get any response
> There was an error connecting to https://myproject.dev/ajaxrequest.
> Why this might have happened:
> The server couldn't send a response:
> Ensure that the backend is working properly
> Self-signed SSL certificates are being blocked:
> Fix this by turning off 'SSL certificate verification' in Settings > General
> Client certificates are required for this server:
> Fix this by adding client certificates in Settings > Certificates
> Request timeout:
> Change request timeout in Settings > General

When I switch back to valet unsecure myproject, it back to normal.

**Comment by drbyte** [comment]
valet secure does use self signed certificates. 
Did you follow the instructions it gave to allow use of self signed certificates?

**Comment by shiroamada** [comment]
OK, thanks for the tips to off the setting.
