### ISSUE TITLE
Serves Contao application with SymfonyDriver

### ISSUE THREAD

**Issue by thoresuenert** [laravel/valet#258]
Every Contao instance is served by SymfonyValetDriver.
Which is caused by the following change in [SymfonyValetDriver L15](https://github.com/laravel/valet/blob/master/cli/drivers/SymfonyValetDriver.php#L15) to support versions < 3.0
This should appear for all Symfony based frameworks which rely on the base folder structure.

Solution:
Move up all Symfony based frameworks in  [ValetDriver](https://github.com/laravel/valet/blob/v2.0.1/cli/drivers/ValetDriver.php)
From now on the order of drivers list is important.

e.g. move ContaoValetDriver above SymfonyValetDriver

**Comment by mattstauffer** [comment]
If this is still of value, I suggest someone PR it and test it out.
