### ISSUE TITLE
[2.0.3] Static sites error with 500 on assets links

### ISSUE THREAD

**Issue by faustbrian** [laravel/valet#260]
I have a few static sites locally that just looks like this.

```
~/Sites/project_name/public/index.html
~/Sites/project_name/public/css/app.css
~/Sites/project_name/public/js/app.js
```

I did `composer global update` to get the latest valet and thought maybe some permissions got screwed up but all is fine. Installed valet on a fresh system and still none of the static sites are working anymore, any assets I link result in 500 errors.

Any clue what is causing this?

**Comment by stayallive** [comment]
This also happens in my Laravel application, all 500 errors (from nginx) in the static resources :(

**Comment by faustbrian** [comment]
Thanks, that fixed it.
