### ISSUE TITLE
413 Request Entity Too Large - NGINX

### ISSUE THREAD

**Issue by maxvaser** [laravel/valet#264]
The new Valet 2.x with NGINX throws a 413 Request Entity Too Large request error for file uploads over 1MB. 

The NGINX default:    client_max_body_size  1m;

Is it possible to increase that in a future release to 10m or greater. 

Thanks!

P.S. Valet is so great! So incredibly easy to setup and configure. Took all the pain out of setting up a dev environment on a Mac.

**Comment by adamwathan** [comment]
This was fixed here: https://github.com/laravel/valet/pull/253

...and should be there in 2.0.3 which was tagged yesterday 😊 

Re-run `valet install` and it'll update your nginx configurations 👍

**Comment by maxvaser** [comment]
Thank you very much Adam!

**Comment by drbyte** [comment]
I was running into issues with this on all `secure` sites, and ran into PHP being configured with too-small values as well. 

So I submitted #277

**Comment by agusdwimilniadi** [comment]
if u change lient_max_body_size in nginx/nginx.conf. Lets try change client_max_body_size on nginx/valet/valet.conf
