### ISSUE TITLE
Laravel assets are not loading after Valet after 2.0.3

### ISSUE THREAD

**Issue by msonowal** [laravel/valet#265]
The page is loading but all the assets like css,js,images are not loading it's giving a 500 response in the inspect tab 
<img width="897" alt="screen shot 2016-12-16 at 1 43 46 am" src="https://cloud.githubusercontent.com/assets/6334484/21240513/a9e7a460-c331-11e6-9efb-3c9563ba9d0c.png">

**Comment by jerguslejko** [comment]
same here

**Comment by adibhanna** [comment]
same here

**Comment by jerguslejko** [comment]
probably related to #259 ?

**Comment by adamwathan** [comment]
Can anyone share a small example project that we can try out that exhibits this problem? All of mine and Taylor's projects are working without any issues so this is a tricky one for us to debug.

**Comment by adibhanna** [comment]
I fixed it. I ran `valet uninstall` then `valet install`

**Comment by jerguslejko** [comment]
@adibhanna omg. I now feel stupid for not trying that. that fixed it...

**Comment by adibhanna** [comment]
@jerguslejko nah, we never do that when updating a composer package. easy to miss.

**Comment by msonowal** [comment]
after running `valet uninstall then valet install`
it worked fine, never knew what was the issues,
I will report if I get any in the future thanks @adamwathan @adibhanna

**Comment by bbashy** [comment]
`valet uninstall && valet install` worked for me too. Had 500 errors.

This is also weird though (GIF) https://d.pr/i/MfQv/2UMcevfk.gif

![](https://d.pr/i/MfQv/2UMcevfk.gif)
