### ISSUE TITLE
Craft page loads are slow

### ISSUE THREAD

**Issue by imploding** [laravel/valet#266]
All static, non-framework php, Kirby and WP sites work just fine, however any Craft installation I have is excruciatingly with pages requests and /admin is inaccessible. Wondering if anyone else had encountered this?

Just did a clean install of 2.0.3 to make sure.
With nginx 1.10.2 and php 7.1.0.

**Comment by sjelfull** [comment]
@imploding Craft is usually not a problem. An idea: Have you tried disabling Xdebug?

**Comment by imploding** [comment]
@sjelfull yep, Xdebug not running.

Seems to be running just fine with Craft 3 Alpha installation, will have to investigate further.
Will close as no one else seems to be experiencing and most likely an environment issue.

**Comment by andocobo** [comment]
For anyone who might be wondering about how to fix this this, for me what worked was creating a local valet driver (https://laravel.com/docs/5.4/valet#custom-valet-drivers) containing the code below:

Also note that my setup had the front controller index.php file in the site root, not in the public folder.

`class LocalValetDriver extends ValetDriver
{
    /**
     * Determine if the driver serves the request.
     *
     * @param  string  $sitePath
     * @param  string  $siteName
     * @param  string  $uri
     * @return bool
     */
    public function serves($sitePath, $siteName, $uri)
    {
       return true;
    }

    /**
     * Determine if the incoming request is for a static file.
     *
     * @param  string  $sitePath
     * @param  string  $siteName
     * @param  string  $uri
     * @return string|false
     */
    public function isStaticFile($sitePath, $siteName, $uri)
    {
        if ($this->isActualFile($staticFilePath = $sitePath.'/'.$uri)) {
            return $staticFilePath;
        }

        return false;
    }

    /**
     * Get the fully resolved path to the application's front controller.
     *
     * @param  string  $sitePath
     * @param  string  $siteName
     * @param  string  $uri
     * @return string
     */
    public function frontControllerPath($sitePath, $siteName, $uri)
    {
        // Default index path
        $indexPath = $sitePath.'/index.php';
        $scriptName = '/index.php';


        $_SERVER['SCRIPT_FILENAME'] = $indexPath;
        $_SERVER['SERVER_NAME'] = $_SERVER['HTTP_HOST'];
        $_SERVER['SCRIPT_NAME'] = $scriptName;
        $_SERVER['PHP_SELF'] = $scriptName;

        return $indexPath;
    }
}`

I also had to make sure I was using multi-environment config for Craft, my local config was setup as below:

`return array(
    '*' => array(
        'omitScriptNameInUrls' => true,
        'cooldownDuration' => 0    
    ),

    'quillcraft.dev' => array(
        'devMode' => false,
        'usePathInfo' => false,
        'siteUrl' => 'http://quillcraft.dev',
        'cooldownDuration' => 0,

        'environmentVariables' => array(
            'basePath' => '/Users/Andrew/Code/quillcraft/',
            'baseUrl'  => 'http://quillcraft.dev'
        )
   )
);`
