### ISSUE TITLE
502 Bad Gateway - nginx/1.10.2

### ISSUE THREAD

**Issue by rsm23** [laravel/valet#269]
I'm using Laravel Valet 2.0.3 on MacOS Sierra
And I'm getting this error everytime I restart my laptop

![screen shot 2016-12-17 at 10 41 41 am](https://cloud.githubusercontent.com/assets/2084708/21285893/8326b55e-c445-11e6-889c-ac72d29859ec.png)

**Comment by adamwathan** [comment]
Did you run `valet install` after upgrading?

**Comment by rsm23** [comment]
Yes of course

**Comment by ekandreas** [comment]
Same here...

**Comment by rsm23** [comment]
Isn't there any solution for that?

**Comment by mpociot** [comment]
Same for me - I encountered this issue only after updating to Sierra 10.12.2 (16C67).

**Comment by ekandreas** [comment]
So, I did work around this by two actions:
1. Reinstall with the http2 parameter.
2. Adjust fastcgi buffer settings in valet.conf.

**Comment by ekandreas** [comment]
```
valet stop
brew uninstall nginx
brew install nginx --with-http2
valet install
```

And `/usr/local/etc/nginx/valet/valet.conf` updated with:
```
location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass unix:/Users/aek/.valet/valet.sock;
        fastcgi_index /Users/aek/.composer/vendor/laravel/valet/server.php;
	# added params:
        fastcgi_buffers 16 16k;
	fastcgi_buffer_size 32k;
        # /added params
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /Users/{username}/.composer/vendor/laravel/valet/server.php;
    }
```

**Comment by mpociot** [comment]
That's not working for me.
I don't always get a 502 Bad Gateway, I get it 2-3 requests on my .dev sites if I keep refreshing.

So it also happens for static files.

**Comment by RafaelPlantard** [comment]
Any news? Same error for me.

**Comment by RafaelPlantard** [comment]
Anyone know how can I install php71-memcached with Homebrew???

**Comment by hsleewis** [comment]
Also still an issue here,.. anyone has a working solution?

**Comment by adamwathan** [comment]
I haven't been able to reproduce this at all but some things online point to it maybe having something to do with large responses and big files. Is anyone able to create some sort of repository or something that demonstrates this in a reproducible way?

**Comment by hsleewis** [comment]
I have a couple of pages where I do a number of external requests, it looks like I get the error on those pages. Unfortunately nothing I can make available publicly. I even reinstalled my new MacBook Pro on a new partition and tested it, but I get exactly the same issues.

**Comment by simonpeters** [comment]
Having the same issue since updating to 2.0.3

**Comment by drbyte** [comment]
What's recorded in your `~/.valet/Log/nginx-error.log` ?

**Comment by simonpeters** [comment]
It's an empty file

**Comment by drbyte** [comment]
Ya, that was gonna be my next comment: Bad Gateway often means the call to php-fpm (usually it's on port 9000) is failing. Glad you got it working.

**Comment by tlaverdure** [comment]
@adamwathan I was getting this error just now when trying to perform a `POST`. In my ngnix-error.log I'm seeing this error:

```
 upstream sent too big header while reading response header from upstream
```

I was able to fix by adding these two lines to my valet.conf file in the `location ~ \.php$` block:
```
fastcgi_buffers 16 16k;
fastcgi_buffer_size 32k;
```

I also tested this `POST` request with less form fields and it seems to be consistent with the amount of data being submitted.

[Reference](http://stackoverflow.com/questions/23844761/upstream-sent-too-big-header-while-reading-response-header-from-upstream/23845727#23845727)

**Comment by GiampaoloFalqui** [comment]
I keep having the same issues.

fastcgi buffer settings did not fix the issue.
rebooting did not fix the issue.

**Comment by hsleewis** [comment]
With my computer it always happens when doing a POST request.

**Comment by jesusamezag** [comment]
I've the same issue...

Here is my log:

<img width="574" alt="captura de pantalla 2017-01-20 a la s 17 52 39" src="https://cloud.githubusercontent.com/assets/14480445/22170309/654dbd02-df39-11e6-8d53-5d61bc67eebd.png">

**Comment by jpmurray** [comment]
I'm having the same log output as @jesusamezag here, but it all started to happen after I did `valet unsecure` on one of my site/folder...

**Comment by jpmurray** [comment]
I made a couple uninstall/install cycle and I wouldn't get valet started anymore. What got me back on track was stopping valet, uninstalling nginx and reinstalling it with `brew install nginx --with-http2`. Now all seems ok.

I don't think it could help for everyone, but in case it did... !

**Comment by railto** [comment]
Having same issues and have tried all the solutions in this thread.  content from the error log is 

```
2017/01/27 10:39:15 [crit] 41134#0: *7 connect() to unix:/Users/mark/.valet/valet.sock failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/Users/mark/.valet/valet.sock:", host: "personalsite.dev
```

Hoping someone else has a solution for this as currently means I'm back to using vagrant for local dev and would really rather use valet

**Comment by thinkstylestudio** [comment]
I know when I was snooping I was unable to find /Users/mark/.valet/valet.sock
It did not exist. I couldn't test if that was the issue either as I don't
know what should in theory be in the file.

**Comment by drbyte** [comment]
The `valet.sock` file has no content. In some ways it's not really even a "file". It's a socket. But it shows up as a file on the filesystem.

The valet.sock file is created upon nginx startup, and removed on normal shutdown.

If it doesn't exist then nginx didn't/couldn't start properly. Look at the `~/.valet/Log/nginx-error.log` for messages.

Common causes of nginx not starting are documented all over the web.  Typically it's a port clash with other services already running on ports 80/443, or a nginx.conf file content problem.

**Comment by xboston** [comment]
Hi @rsm23! 

Check please:
```
$ ls -lm $HOME/.valet
Certificates, Drivers, Extensions, Log, Nginx, Sites, config.json, dnsmasq.conf

$ brew services start php71
==> Successfully started `php71` (label: homebrew.mxcl.php71)

$ ls -lm $HOME/.valet
Certificates, Drivers, Extensions, Log, Nginx, Sites, config.json, dnsmasq.conf, valet.sock
```

Done.

**Comment by drbyte** [comment]
@xboston is right ... I was looking at too much nginx stuff earlier when I said it was about nginx. The valet.sock is created when PHP-FPM is started (not nginx).

Look in `/usr/local/var/log/php-fpm.log` for error messages if it's not starting.

**Comment by thomas-oo** [comment]
@xboston 

I'm not seeing valet.sock after I run brew services start php71. For some reason, after I start php71 and I check brew services list, it is still stopped... Does anyone know what might be happening

**Comment by drbyte** [comment]
Have you tried `sudo` instead?

**Comment by thomas-oo** [comment]
yes now I see valet.sock and my issue is no long a 502 error but now I have a 404 error, valet - not found...

**Comment by tatocaster** [comment]
after upgrading to 2.XX i have the same problem. 
`usr/local/var/log/php-fpm.log` is empty, 
`nginx-error.log` says `.valet/valet.sock failed (2: No such file or directory) `

**Comment by tatocaster** [comment]
`sudo brew services restart nginx && sudo brew services restart php71` 
if it writes that permissions are messed up , use this link below. 
[](http://stackoverflow.com/questions/28063598/error-while-executing-plist-file-path-had-bad-ownership-permissions ) 

everything is up and running.

**Comment by ZeoKnight** [comment]
@tatocaster thanks - that has put it right for me seems the nginx/1.10.3/homebrew.mxcl.nginx.plist had permission issues - that SO post helped

**Comment by Davidsr** [comment]
Hi, I have a 404 error. What you think about this?:

```
sudo chown root /Library/LaunchDaemons/myfile.plist
sudo chgrp wheel /Library/LaunchDaemons/myfile.plist
```
Done

`nginx -t`

```
nginx: [warn] the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /usr/local/etc/nginx/nginx.conf:1
nginx: the configuration file /usr/local/etc/nginx/nginx.conf syntax is ok
nginx: [emerg] open() "/usr/local/var/run/nginx.pid" failed (13: Permission denied)
nginx: configuration file /usr/local/etc/nginx/nginx.conf test failed
```

**Comment by pryley** [comment]
I was having the same problem. In my case it happened after brewing a new PHP version and trying to switch to it:

1. `brew install php71`
2. `valet install`

At this point everything works.

3. `brew install php70`
4. `sudo brew services stop php71`
5. `brew unlink php71`
6. `brew link php70`
7. `sudo brew services start php70`

Now I get the following 502 Bad Gateway error when loading a site:

```
2017/02/07 21:13:23 [crit] 78452#0: *1 connect() to unix:/Users/me/.valet/valet.sock failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/Users/me/.valet/valet.sock:", host: "laravel.dev"
```

To fix this, you have to run `valet install` after brewing a new PHP version.

8. `valet install`

Now running steps 4-7 to swap between PHP versions works correctly. 👍

**Comment by Davidsr** [comment]
Ok, the solution for my problem 404 error was.

`valet link
valet start`

I don´t know why valet park is not working.

**Comment by swiftliuziyang** [comment]
when i input $ sudo brew services start php70 in my mac's command line, it works! thank for pryley

**Comment by rchoffardet** [comment]
`sudo brew services start php70` also fixed my issue. But, i think it only fixes the symptom and not the real problem... i would love to have a real fix.

I continue my researches :smile:

**Comment by cerw** [comment]
Try to run /usr/local/opt/php70/sbin/php70-fpm configtest and see if php-fpm it self is OK in my case it was bad permission, like sudo brew .. will mark it as root :( 

After i fixed it, it work now!

**Comment by rchoffardet** [comment]
Seems like it worked ! But I said just above, the only difference in the two commands was `start` or `restart` which is kinda weird..

**Comment by joelpierre** [comment]
So for me I have brew linked php71 however when I started php70 valet worked again..... Very confusing.

**Comment by shahbaaz** [comment]
Even if you stop and uninstall valet. Caddy server still runs in the background. To get rid of Caddy server, follow these instructions:

`valet stop`
`valet uninstall`

Delete these executable files 
`sudo rm /usr/local/bin/valet `
and
`sudo rm /Users/{home-directory}/.composer/vendor/bin/valet`
(replace {home-directory} with your home directory name)

Make sure Caddy server and valet is removed from your computer completely.

when you type `valet` in terminal. You should see: `command not found: valet`

when you type `curl -I foo.dev`. You should see: `curl: (6) Could not resolve host: foo.dev`

Now install valet following the instructions in documentation: https://laravel.com/docs/5.4/valet#installation

Still if it doesn’t work. Type these command in your terminal:
`brew services restart nginx && brew services restart php71`

`valet start` or `valet restart`

**Comment by ahmedchijai** [comment]
sudo brew services start php71 it works! thank

**Comment by jasperf** [comment]
Another `valet install` on top of an existing older one did the trick to get back valet.sock . Here:
```
ls -lm $HOME/.valet
Caddy, Caddyfile, Certificates, Drivers, Extensions, Log, Nginx, Sites, config.json, dnsmasq.conf
Jaspers-MBP-2016:Log jasperfrumau$ valet install
Valet installed successfully!
Jaspers-MBP-2016:Log jasperfrumau$ ls -lm $HOME/.valet
Caddy, Caddyfile, Certificates, Drivers, Extensions, Log, Nginx, Sites, config.json, dnsmasq.conf, valet.sock
```

**Comment by benleivian** [comment]
Was having a similar issue, then I realized I had a vpn firewall active 😑

**Comment by BobbyBorisov** [comment]
I was having the same issue and installing php71 helped me

**Comment by jartaud** [comment]
@tatocaster thanks. Your solution works for me so i don't have to issue ``valet install`` command.

Ubuntu 16.04.2 LTS

**Comment by llaski** [comment]
For php56 I had to manually change the listen value in the php-fpm.conf file (Something like `listen = '.VALET_HOME_PATH.'/valet.sock`). Normally it gets replaced by valet but didn't in my case. Hope this helps someone.

**Comment by clarkeash** [comment]
Ive had this issue today on High Sierra and ultimately fixed it (after lots of googling)

```bash
brew uninstall php71
brew prune
rm -rf /usr/local/opt/php71
brew install php71 php71-xdebug
sudo valet install
```

**Comment by ctf0** [comment]
@tlaverdure where to add the config  ? i cant find `valet.conf` anywhere except in `cli/stubs`

**Comment by MikeZange** [comment]
@clarkeash Fixed issue for me, thanks!

`brew uninstall php71
brew prune
rm -rf /usr/local/opt/php71
brew install php71 php71-xdebug
sudo valet install`

**Comment by Adamnator92** [comment]
solved my permissions problem by `valet install`

**Comment by llbbl** [comment]
Hey everyone. The solution this is to that nginx can't pass requests to php-fpm. This is normally because php-fpm listener is not configured correctly. PHP can be configured to respond to request via unix socket or via TCP socket. 

Check where your www.conf file is configured to listen:
```
listen = /run/php/php7.0-fpm.sock
or
listen = 127.0.0.1:9000
or what valet wants... 
listen = /Users/YourUserName/.valet/valet.sock
```

Hope this helps someone else. Just finished double clawing myself outta that hole.

**Comment by drbyte** [comment]
True. 
If I recall correctly, an older version of Valet formerly listened on 127.0.0.1:9000. 
I ran into this when I had an older version of PHP installed, then installed a newer version, then ran valet install, and it only updated the PHP config for the newer PHP. 
Then when attempted to switch back to older PHP version it was looking on localhost instead of the socket. 
Updating the www.conf (or equiv) for the various PHP versions I have available solved all the conflicts.

**Comment by cheerego** [comment]
I changed my php version from 7.2 to 7.1 ,found this error.
I solve it via ‘valet install’

**Comment by same07** [comment]
@tlaverdure thx bro.. u save my day...

adding 

```
fastcgi_buffers 16 16k;
fastcgi_buffer_size 32k;
```

works well..

**Comment by raveenasurani** [comment]
Hello guys,

I was having the same issue after knocking my head around i came upto this solution and its working perfectly .. Here you go 👍

so Firstly, i install Brew : /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

Then i installed php71 which is now php@7.1 : brew install php71

-> after installation export : echo 'export PATH="/usr/local/opt/php@7.1/bin:$PATH"' >> ~/.bash_profile
echo 'export PATH="/usr/local/opt/php@7.1/sbin:$PATH"' >> ~/.bash_profile

-> brew link php@7.1 --force --overwrite

->ln -s $(which php) /usr/local/bin/php

Then i installed composer using :

php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
php -r "if (hash_file('SHA384', 'composer-setup.php') === '544e09ee996cdf60ece3804abc52599c22b1f40f4323403c44d44fdfdd586475ca9813a858088ffbc1f233e9b180f061') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
php composer-setup.php
php -r "unlink('composer-setup.php');"

and mv composer.phar /usr/local/bin/composer

and then installed valet : composer global require laravel/valet

And then comes the tricky part :

-> open -e /Users/USERNAME-Directory/.composer/vendor/laravel/valet/cli/Valet/Brew.php

and alter

function supportedPhpVersions()
{
return collect(['php', 'php72', 'php71', 'php70', 'php56','php@7.1']);
}

-> open -e /Users/USERNAME-Directory/.composer/vendor/laravel/valet/cli/Valet/PhpFpm.php

and alter

function fpmConfigPath()
{
$confLookup = [
'php' => '/usr/local/etc/php/7.2/php-fpm.d/www.conf',
'php72' => '/usr/local/etc/php/7.2/php-fpm.d/www.conf',
'php71' => '/usr/local/etc/php/7.1/php-fpm.d/www.conf',
'php70' => '/usr/local/etc/php/7.0/php-fpm.d/www.conf',
'php56' => '/usr/local/etc/php/5.6/php-fpm.conf',
'php@7.1' => '/usr/local/etc/php/7.1/php-fpm.d/www.conf'
];

    return $confLookup[$this->brew->linkedPhp()];
}
and then final step : sudo brew services restart nginx && sudo brew services restart php@7.1

And DONE!!!!

Cheers!!

**Comment by hsleewis** [comment]
@tlaverdure do you know if there is a way to automatically add the fastcgi settings to all valet hosts?

**Comment by drbyte** [comment]
@hsleewis wrote:
> do you know if there is a way to automatically add the fastcgi settings to all valet hosts?

Running `valet domain test` will do this. First it will set the TLD for Valet to `.test`, and then it will rebuild every nginx config so that it uses that TLD. It uses the `valet.conf` and `secure.valet.conf` stubs in your `~/.composer/vendor/laravel/valet/cli/stubs` directory as the templates for rebuilding those configs. 
So if you want to change all your hosts configs, simply update the stubs and run `valet domain test`. 

Then restart nginx with `valet restart` or with `brew services nginx restart`

**Comment by ilterocal** [comment]
brew commands should be run with "sudo" otherwise it fails to create the valet.sock in valet folder.

**Comment by acymru** [comment]
Trying to run brew commands as "sudo":
**Error:** Running Homebrew as root is extremely dangerous and no longer supported.
As Homebrew does not drop privileges on installation you would be giving all
build scripts full access to your system.

**Comment by Sauruz** [comment]
I've tried everything above and none seemed to work. Until I noticed I had 2 php versions in /usr/local/etc/php. Deleting both and doing all the steps at https://laravel.com/docs/5.6/valet solved my problem. It took me quite some hours of pulling my hair out.

**Comment by gindra** [comment]
I have same problem php-fpm not loaded, because of new brew sudo requirements,  brew reinstall php71 --build-from-source did not have permissions to create necessary folders for fpm, so I gave 777 permission to the PHP folder and run reinstall php71 --build-from-source, restart pc and, run vallet install and everything works great.

**Comment by bradycharron** [comment]
I have come up against this issue when trying to configure my database with SSL, and connect to it with the MySql driver.  Per a few different resources, I found the following configuration for the MySql driver to add support for SSL connections, but with this driver configuration, I get the Bad Gateway error.

Driver:
-----
```
'mysql' => [
            'driver' => 'mysql',
            'host' => env('DB_HOST', '127.0.0.1'),
            'port' => env('DB_PORT', '3306'),
            'database' => env('DB_DATABASE', 'forge'),
            'username' => env('DB_USERNAME', 'forge'),
            'password' => env('DB_PASSWORD', ''),
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'sslmode' => env('DB_SSLMODE', 'prefer'),
            'options'   => array(
                PDO::MYSQL_ATTR_SSL_CA    => '/path/to/file/ca.pem',
                PDO::MYSQL_ATTR_SSL_CERT    => ''/path/to/file/client-cert.pem',
                PDO::MYSQL_ATTR_SSL_KEY    => ''/path/to/file/cleint-key.pem'
            ),
            'strict' => true,
            'engine' => null,
        ],
```

I am using Laravel Valet as the development environment for this.  I get the following error in the Valet NGINX error log: `2018/06/14 07:51:50 [error] 6495#0: *15 upstream prematurely closed connection while reading response header from upstream, client: 127.0.0.1, server: ccc.dev, request: "POST /oauth/token HTTP/1.1"`

Does anyone know how to resolve this issue with a SSL enabled DB connection?

**Comment by trungtnm** [comment]
@drbyte You saved my day!
PHP-FPM complains about some missing images when I have looked at `/usr/local/var/log/php-fpm.log` . So i run `brew update && brew upgrade php@7.1` , then everything works fine.

**Comment by kundaneyug** [comment]
This worked for me
`composer global update
valet install
valet restart`

**Comment by jorshhh** [comment]
> This worked for me
> `composer global update`
> `valet install`
> `valet restart`

This worked for me too

**Comment by tammai** [comment]
> This worked for me
> `composer global update`
> `valet install`
> `valet restart`

Me too

**Comment by hezll** [comment]
valet install after switch PHP version

**Comment by AbsohAbsoh** [comment]
Make sure PHP is running. 

`brew services start php`

**Comment by akilsagitarius** [comment]
> This worked for me
> `composer global update`
> `valet install`
> `valet restart`

This worked too me

**Comment by CptMeatball** [comment]
Also running into this problem after updating brew, php and valet. I was still running on `php71` and after deleting all php versions and installed php 7.3 with the `php@7.3` command.  

All seemed fine, updated MacOS and running into the 502 now. 

Will try and report what worked for me.

**Comment by AbsohAbsoh** [comment]
@CptMeatball make sure you're actually running PHP with...

    brew services start php

If that doesn't work then make sure you're actually running the brew php not one that comes installed on the Mac by default.

    which php

**Comment by HPWebdeveloper** [comment]
I had such experience and solved it finally. The solution is [here](https://medium.com/@panjeh/laravel-502-bad-gateway-when-starting-laravel-valet-simple-solution-d168bfedfb7)

**Comment by whoacowboy** [comment]
I tried everything on this chain and then some to no avail. 

It turns out that this file `/usr/local/etc/php/7.3/php-fpm.d/www.conf` was empty.

I copied `www.conf.default` to `www.conf` and restarted valet and everything is now working.

```
cd /usr/local/etc/php/7.3/php-fpm.d/
cp www.conf.default www.conf
valet restart
```

**Comment by ihsanberahim** [comment]
> after upgrading to 2.XX i have the same problem.
> `usr/local/var/log/php-fpm.log` is empty,
> `nginx-error.log` says `.valet/valet.sock failed (2: No such file or directory) `

i did `sudo touch /usr/local/var/log/nginx/access.log` then it works.

**Comment by eComEvo** [comment]
Manually removing valet by doing `sudo rm -rf /Users/myuser/.config/valet/` and then `valet install` fixed the issue for me.

**Comment by classiebit** [comment]
@adamwathan perfect. Needed to run `valet install` after upgrading brew and PHP version.

**Comment by vanrijs** [comment]
Had this same issue. Don't know the cause of it. 
For me a brew upgrade php@7.4 was the fix. After upgrade run valet install again and link your PHP version with valet use php@7.4

**Comment by yratof** [comment]
Writing this here incase it helps anyone in 2021 - I had to copy /usr/local/etc/php/8.0/php-fpm.d/valet-fpm.conf to /usr/local/etc/php/8.0/php-fpm.conf. This solved my issue of the 502 error. Looking at the php-fpm logs revealed that the conf file wasn't being loaded - because it didn't exist. I'm guessing there's a reason for this, but working with only valet, it was easier to clone the file and rename it, than to spend my life figuring out why the server gods reject me so

**Comment by mostafasoufi** [comment]
Neither the `valet restart` nor `valet install worked but changing the PHP version fixed the issue.

```
valet use php@7.4
```
Or
```
valet isolate php@7.4
```

**Comment by vanrezky** [comment]
> Neither the `valet restart` nor `valet install` worked but changing the PHP version fixed the issue.
> 
> ```
> valet use php@7.4
> ```
> 
> Or
> 
> ```
> valet isolate php@7.4
> ```

im using valet isolate php@7.4 or php what i want
and it solve my problem
