### ISSUE TITLE
[Valet 2.0.3] 500 Bad Gateway on every static file

### ISSUE THREAD

**Issue by DCzajkowski** [laravel/valet#270]
Hello. In the newest Laravel Valet any time I access any site assets are not being loaded e.g.
```
laravel new test
cd test
php artisan make:auth
```
Navigate to `test.dev` site is working. When I click on `Login` on `/login` no assets are being loaded and every one of them gets 500 error. 

---

![](http://i.imgur.com/Y44esJQ.png)

---

In #242 it was sending 404 along with the response. Now it is not sending anything, just an nginx error.

---

##### In the mean time
At the same time `valet secure` did not work at all (every site served over https resulted in "This site can’t be reached" or something like that).

![](http://i.imgur.com/ZhJNxBX.png)

**Comment by adamwathan** [comment]
Few questions:

1. Did you run `valet install` after upgrading to 2.0.3?

2. Can you post the contents of the following files?

    ```
    /usr/local/etc/nginx/nginx.conf
    /usr/local/etc/nginx/valet/valet.conf
    ```

3. Did you have nginx already installed via homebrew before installing Valet? It needs to be installed with the `--with-http2` flag for HTTPS to work properly. Valet will install it using that flag for you if it's not already installed, but if it was already installed, try:

    ```
    valet stop
    brew uninstall nginx
    brew install nginx --with-http2
    valet install
    ```

**Comment by DCzajkowski** [comment]
1. yes
2.
```
user Darek staff;
worker_processes auto;

events {
    worker_connections  1024;
}

http {
    include mime.types;
    default_type  application/octet-stream;

    sendfile on;
    keepalive_timeout  65;

    gzip  on;
    gzip_comp_level 5;
    gzip_min_length 256;
    gzip_proxied any;
    gzip_vary on;

    gzip_types
    application/atom+xml
    application/javascript
    application/json
    application/rss+xml
    application/vnd.ms-fontobject
    application/x-font-ttf
    application/x-web-app-manifest+json
    application/xhtml+xml
    application/xml
    font/opentype
    image/svg+xml
    image/x-icon
    text/css
    text/plain
    text/x-component;

    include /Users/Darek/.valet/Nginx/*;
    include servers/*;
    include valet/valet.conf;
}
```

```
server {
    listen 80 default_server;
    root /;
    charset utf-8;
    client_max_body_size 128M;

    location /41c270e4-5535-4daa-b23e-c269744c2f45/ {
        internal;
        alias /;
        try_files $uri $uri/;
    }

    location / {
        rewrite ^ /Users/Darek/.composer/vendor/laravel/valet/server.php last;
    }

    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }

    access_log off;
    error_log /Users/Darek/.valet/Log/nginx-error.log;

    error_page 404 /Users/Darek/.composer/vendor/laravel/valet/server.php;

    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass unix:/Users/Darek/.valet/valet.sock;
        fastcgi_index /Users/Darek/.composer/vendor/laravel/valet/server.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /Users/Darek/.composer/vendor/laravel/valet/server.php;
    }

    location ~ /\.ht {
        deny all;
    }
}
```
3. No, but after rerunning with your command still doesn't work (same happens).

---

P.S. While you were replying I updated my original question/issue with screenshots.

**Comment by DCzajkowski** [comment]
I have also uninstalled Valet entirely, nginx, updated php to 7.1 etc.

**Comment by DCzajkowski** [comment]
Also tried with `dev-master`. Now on `dev-master`, not on 2.0.3

**Comment by adamwathan** [comment]
Anything in the nginx logs?

**Comment by DCzajkowski** [comment]
What's the best way to access that?

**Comment by DCzajkowski** [comment]
nvm Got it

**Comment by DCzajkowski** [comment]
This appears after accessing `/login`.

```
2016/12/18 18:55:26 [error] 38115#0: *1861 rewrite or internal redirection cycle while processing "/Users/Darek/.composer/vendor/laravel/valet/server.php", client: 127.0.0.1, server: , request: "GET /css/app.css HTTP/1.1", upstream: "fastcgi://unix:/Users/Darek/.valet/valet.sock", host: "laravel53.dev", referrer: "http://laravel53.dev/login"
2016/12/18 18:55:26 [error] 38115#0: *1862 rewrite or internal redirection cycle while processing "/Users/Darek/.composer/vendor/laravel/valet/server.php", client: 127.0.0.1, server: , request: "GET /js/app.js HTTP/1.1", upstream: "fastcgi://unix:/Users/Darek/.valet/valet.sock", host: "laravel53.dev", referrer: "http://laravel53.dev/login"
2016/12/18 18:55:27 [error] 38115#0: *1863 rewrite or internal redirection cycle while processing "/Users/Darek/.composer/vendor/laravel/valet/server.php", client: 127.0.0.1, server: , request: "GET /js/app.js HTTP/1.1", upstream: "fastcgi://unix:/Users/Darek/.valet/valet.sock", host: "laravel53.dev", referrer: "http://laravel53.dev/login"
2016/12/18 18:55:28 [error] 38115#0: *1864 rewrite or internal redirection cycle while processing "/Users/Darek/.composer/vendor/laravel/valet/server.php", client: 127.0.0.1, server: , request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://unix:/Users/Darek/.valet/valet.sock", host: "laravel53.dev", referrer: "http://laravel53.dev/login"
```

**Comment by DCzajkowski** [comment]
Here is the demo:

phpinfo() - http://4dff26f8.ngrok.io/
login page - http://4dff26f8.ngrok.io/login

**Comment by DCzajkowski** [comment]
Oh. I have forgotten to mention I am still using Yosemite. May that be an issue?

**Comment by dodyagung** [comment]
Have the same problem. Try `valet uninstall && valet install`. I don't have an idea about that but it works on my macOS. Good luck.

**Comment by DCzajkowski** [comment]
@dodyagung I have already tried a few times. No change.

**Comment by adamwathan** [comment]
@DCzajkowski I can't know for sure but I wouldn't be surprised if the issue was related to being on Yosemite. Unfortunately there's no reasonable way for me to try and reproduce that locally :/

If you like, I can make time for a screenshare at some point if you want to try and troubleshoot it together.

**Comment by DCzajkowski** [comment]
Sure. Whenever you can :)

**Comment by maxvaser** [comment]
I'm on macOS Sierra 10.12.2 and have the same problem. I don't think it's OS related. The problem with file size limit happened for me when valet 2.x moved to NGINX.

**Comment by maxvaser** [comment]
I even just re-ran a full update where I uninstalled PHP7.0 and upgraded to the version with 7.1 support and reinstalled everything and I still get the 413 error on files over 1MB. 

https://laravel-news.com/laravel-valet-php-7-1

valet stop
valet uninstall
composer global require laravel/valet
brew uninstall --force php70
valet install
valet restart

**Comment by DCzajkowski** [comment]
@maxvaser Your issue is a different from mine, as I get 500 and you get 413. Please create a new issue for that. Thanks.

**Comment by maxvaser** [comment]
Sorry, there is already one started. this issue was referenced to verify that the .conf files were indeed updated. I'll move those to the other issue.

**Comment by jkmassel** [comment]
FWIW I have the same issue in El Cap as well. Same log entires, too:

```
2016/12/19 11:38:17 [error] 15618#0: *1574 rewrite or internal redirection cycle while processing "/Users/jeremy/.composer/vendor/laravel/valet/server.php", client: 127.0.0.1, server: , request: "GET /wp-content/uploads/2016/12/17-300x200.png HTTP/1.1", upstream: "fastcgi://unix:/Users/jeremy/.valet/valet.sock", host: "gdi-wp.dev"
2016/12/19 11:38:21 [error] 15618#0: *1714 rewrite or internal redirection cycle while processing "/Users/jeremy/.composer/vendor/laravel/valet/server.php", client: 127.0.0.1, server: , request: "GET /wp-content/uploads/2016/12/17-300x200.png HTTP/1.1", upstream: "fastcgi://unix:/Users/jeremy/.valet/valet.sock", host: "gdi-wp.dev"
```

Tried uninstalling + reinstalling nginx per your suggestion, as well as uninstalling and reinstalling valet

**Comment by DCzajkowski** [comment]
Did you restart nginx or something after the change to `/usr/local/etc/nginx/valet/valet.conf`?

**Comment by ekandreas** [comment]
For me it helped with updated settings in `/usr/local/etc/nginx/valet/valet.conf`

```
    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass unix:/Users/aek/.valet/valet.sock;
        fastcgi_index /Users/aek/.composer/vendor/laravel/valet/server.php;
	**fastcgi_buffers 16 16k;
	fastcgi_buffer_size 32k;**
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /Users/aek/.composer/vendor/laravel/valet/server.php;
    }
```

And a `valet restart` after edit...

**Comment by DCzajkowski** [comment]
Thanks @ekandreas, but it still didn't work for me (changed `/Users/aek` to `/Users/Darek` accordingly) :/

**Comment by ekandreas** [comment]
Don't change other than just the two params...?

**Comment by DCzajkowski** [comment]
Oh, ok. Still same thing though.

**Comment by ekandreas** [comment]
Sorry, have you tested the other examples in the source?

**Comment by DCzajkowski** [comment]
Yes, I have. Although my problem (I think) is not with a file size or sth, but with a 500 error.

**Comment by DCzajkowski** [comment]
When I removed everything from the `app.css` file the problem still persists, so it can't be a file size, can it?

**Comment by adamwathan** [comment]
I definitely don't think it's related to file size but I'm not sure what the problem is yet :/

**Comment by DCzajkowski** [comment]
If you had some time for a screen-share just drop me a message. Thanks for your help BTW :)

**Comment by EHLOVader** [comment]
I too had the same problem. It may have been due to nginx being installed previously. 

Following the instructions to install with the `--with-http2` flag worked for me.

```
valet stop
brew uninstall nginx
brew install nginx --with-http2
valet install
```

**Comment by dexterliu1214** [comment]
I have the same problem. Any solution now?

**Comment by DCzajkowski** [comment]
All of the guys having the same problem please edit your posts to include a Mac version, and have you installed or updated Valet. Also feel free to include any additional information.

**Comment by dexterliu1214** [comment]
I have the problem when I upgrade to valet 2.0.3. And I tried completely remove valet, nginx and relative folders and .conf files.

**Comment by pedroborges** [comment]
I'm on El Capitan and following @EHLOVader recommendation solved the issue.

```
valet stop
brew uninstall nginx
brew install nginx --with-http2
valet install
```

I tried restarting my machine before running these command but that alone didn't work.

**Comment by tomschlick** [comment]
```
valet stop
brew uninstall nginx
brew install nginx --with-http2
valet install
```

This fixed mine on El Cap as well...

**Comment by antonioribeiro** [comment]
Make sure you have a valet.sock file:

    ls -la ~/.valet/valet.sock

And you should have 

![image](https://cloud.githubusercontent.com/assets/3182864/21579017/855abb82-cf7f-11e6-8a5c-ffd00ae11daa.png)

Make sure it's really a socket, that first "s" tells you that.

Make sure php-fpm is running:

    ps aux | grep php

Should give you something like:

![image](https://cloud.githubusercontent.com/assets/3182864/21578996/d1d655e4-cf7e-11e6-8a33-ee8617f890ee.png)

Make sure you have no errors on PHP no Nginx, by looking at your logs while running `valet restart`:

    sudo tail -f * /usr/local/var/log/* /usr/local/var/log/nginx/* ~/.valet/Log/* /usr/local/opt/php71/var/log/*

And you should get

![image](https://cloud.githubusercontent.com/assets/3182864/21579004/151c895e-cf7f-11e6-9961-5092cb2d6420.png)

In my case it was xdebug wrongly configured in php-fpm.conf. FPM was not starting at all.

A missing valet.sock file opened my eyes.

**Comment by DCzajkowski** [comment]
These are the outputs of commands you have suggested:
![](http://i.imgur.com/rC2vPE2.png)
![](http://i.imgur.com/yMJvwp7.png)
![](http://i.imgur.com/ZIKx5qn.png)
![](http://i.imgur.com/ckkGhXf.png)

Although there is nothing especially interesting about those outputs, this one is very interesting indeed:
![](http://i.imgur.com/FiyVSZj.png)

**Comment by antonioribeiro** [comment]
@DCzajkowski, looks like there's something listening on port 80, check using:

    lsof -i :80 | grep LISTEN

If it's NGINX, completely stop it:

running as root

     sudo brew services stop nginx

and also as your user

     brew services stop nginx

Then restart valet

    valet restart

And you have another error `[emerg] "http" directive is not allowed here …` for that one check if you don't have any nginx configuration files doing that, like a backup file. You can try to disable some of the includes in nginx.conf to see if it loads:

    include /Users/antoniocarlos/.valet/Nginx/*;
    include servers/*;
    include valet/valet.conf;

Check if you have any files in those dirs, they might be causing it too, becaus they are loaded before valet.conf.

**Comment by michelemarrionline** [comment]
hi guys! i've a similar problem... 
<img width="1276" alt="screen shot 2017-01-14 at 15 35 59" src="https://cloud.githubusercontent.com/assets/9830656/21955617/2f948b56-da6f-11e6-81f3-18c4f63526e2.png">

when i load my repo randomly give me 502 bad gateway or it drop some stylesheets or js

**Comment by olimorris** [comment]
I had a similar issue this morning but a `cd ~/.valet && valet install && valet restart` solved the problem. I think it would be helpful for Valet to flag when it requires an install. I don't even know it's updating as the alias I run updates Valet alongside a thousand other items.

**Comment by thecrypticace** [comment]
I've encounter this too. Don't know why but doing `valet install` just completely broke… well everything for valet. So I
1. removed and reinstalled PHP 7.1 and nginx
2. Fixed the permissions on ~/.valet/Log to make it and all files inside writable by my user
3. Ran this:
```
sudo chown root /usr/local/Cellar/nginx/1.10.2_1/homebrew.mxcl.nginx.plist
sudo chown root /usr/local/Cellar/php71/7.1.1_12/homebrew.mxcl.php71.plist
sudo chown root /usr/local/Cellar/dnsmasq/2.76/homebrew.mxcl.dnsmasq.plist

sudo chgrp wheel /usr/local/Cellar/nginx/1.10.2_1/homebrew.mxcl.nginx.plist
sudo chgrp wheel /usr/local/Cellar/php71/7.1.1_12/homebrew.mxcl.php71.plist
sudo chgrp wheel /usr/local/Cellar/dnsmasq/2.76/homebrew.mxcl.dnsmasq.plist
```
4. And this:
```
sudo brew services restart nginx
sudo brew services restart php71
sudo brew services restart dnsmasq
```
5. And this
```
sudo killall mDNSResponder
```

And everything started working correctly. (and `valet restart` works as expected) It appears that the permissions for newly installed launch daemon plists are either broken or I did something strange.

I realize these steps are close to nuclear (you'll have to setup your valet settings again, a la `valet domain` and `valet park`) but I figured that I'd put them here if it happens to help someone. I think I got all the steps down. Let me know if these don't seem to help. There was a large amount of intermediate debugging and "what the heck is going on" for the last hour or so.

**Comment by adamwathan** [comment]
I actually had a similar problem last night where `brew services restart` wasn't working properly, but `stop` then `start` always worked. Related to permissions for those same files you changed.

I pushed a "fix" for this on the master branch:

https://github.com/laravel/valet/commit/3027a0dbbac35e8ae1ca93475835bd611c4ea25e

If anyone wants to update to `dev-master` and see if that fixes anything for them I'd be interested in hearing about it.

**Comment by thecrypticace** [comment]
Yeah, that's something I tried too. Unfortunately the file permissions wouldn't actually _fix_ themselves which is why I had to go through those steps. I would think that `sudo brew …` would auto fix the files but it didn't for me.

**Comment by adamwathan** [comment]
Yeah I found I could keep the default file permissions if I just manually stopped and started my services vs. using restart.

**Comment by thecrypticace** [comment]
I was under the impression daemons plist files handled by launchctl had to be `root/wheel` if they're launched with `sudo` like they are w/ brew but I'm not a macOS developer so I could be wrong. But hey if that worked for you it might work for others. Worth a shot I guess.

**Comment by adamwathan** [comment]
Yeah literally just trial and error until something worked. It seemed really weird to me that root wouldn't be able to properly restart a service owned by a less-privileged user :/

**Comment by thecrypticace** [comment]
Yeah, I noticed that too. Seemed really strange. Got mine in a position where I had to manually kill some nginx processes because brew was _convinced_ that it wasn't running as me or root.

**Comment by DCzajkowski** [comment]
It is incredible and impossible at the same time. I haven't changed anything, I haven't updated anything. I don't even remember rebooting since. Yet, recently everything started working back as it should. Both static files and https. 

Now. It started working for me, but what about others? Feel free to **close** this issue if you feel like doing so. Cheers! :)

**Comment by michelemarrionline** [comment]
i'm in the same situation

**Comment by DCzajkowski** [comment]
Never mind. Still doesn't wok :/

**Comment by ptihiy** [comment]
I had the aforementioned problem 3-4 times already on even latest version.. It works okay, then one time 500 error on all static files enters. I reinstall valet and all works okay again... Until it breaks)))

**Comment by sweettimes** [comment]
Same issue :(

**Comment by vcgnetwork** [comment]
@DCzajkowski if it is still not working try running this command. 

sudo apachectl stop then reboot. see if it all starts to work. It sounds like apache and ngnix are fighting for port 80

**Comment by DCzajkowski** [comment]
This is from February 2017. I am now on 2.3.0 and running Mojave. Everything works as expected. I am not sure what was the issue, but I closed this on September 2017, so it must have worked back then. Thanks for the advice anyway
