### ISSUE TITLE
Broken on PHP 5.5

### ISSUE THREAD

**Issue by drbyte** [laravel/valet#279]
In Valet v1.0.13 the `composer.json` was updated to use `"tightenco/collect": "~5.2"` ... which allows "5.2 or greater", which includes 5.3.x.

The problem here is that Illuminate/Collect 5.3 requires PHP 5.6 minimum, because `Arr.php` uses the PHP constant `ARRAY_FILTER_USE_BOTH` which doesn't exist until PHP 5.6.

So, running tests on Valet 2 using PHP 5.5 breaks ... because Valet's `Configuration.php` and `FileSystem.php` both make calls to `collect()->reject()` and `collect()->filter()` which trigger the `where()` method in `Arr.php` which uses the `ARRAY_FILTER_USE_BOTH` constant.

Further, this hasn't become obvious because `.travis.yml` only lists PHP 5.6+ for tests.

There are 2 ways to address this. Just not sure which direction you wish to take.

1. Change minimum supported PHP version to 5.6 in `valet/composer.json`
```diff
    "require": {
-        "php": ">=5.5.9",
+        "php": ">=5.6.0",
```

2. a) Change required version of tightenco/collect to "5.2.*" instead of "~5.2"
```diff
    "require": {
        "php": ">=5.5.9",
        "illuminate/container": "~5.1",
        "mnapoli/silly": "~1.0",
        "symfony/process": "~2.7|~3.0",
        "nategood/httpful": "~0.2",
-        "tightenco/collect": "~5.2"
+        "tightenco/collect": "5.2.*"
    },
```

2. b) and add PHP 5.5 to `.travis.yml` to ensure ongoing compatibility when the test suite runs.

(I'm in favor of just upping the minimum PHP requirement, since I rarely ever touch 5.5.  I just ran into this while testing another app which requires 5.5, and valet was giving me grief, and I discovered even its tests are failing.)

**Comment by adamwathan** [comment]
Yeah upping to 5.6+ sounds like the right solution 👍
