### ISSUE TITLE
PrestaShop 1.7, 404 on images and few Symfony based pages

### ISSUE THREAD

**Issue by kpodemski** [laravel/valet#285]
Hello guys,

first of all - thank you for this tool, it is really helpful

there are some issues while working with PrestaShop and Valet:
1. images are not loaded correctly, 404 error
2. on /admin-dev/ page when you go to Catalog or Modules section there is 404 error, these pages based on Symfony, maybe that's an issue?

I'm not using any custom driver, everything works properly except these two things

**Comment by pagalba-com** [comment]
Hello,

I have exactly same issue, please look here
https://www.prestashop.com/forums/topic/569696-prestashop-17-backoffice-404-error/
and here
http://forge.prestashop.com/browse/BOOM-2128

Please add comment in Forge about your case and configuration.
