### ISSUE TITLE
javascript file doesn't update when refreshing the page

### ISSUE THREAD

**Issue by fajarnuha** [laravel/valet#288]
While doing my project, I was editing my javascript file to send ajax request, then I try to check my work by refreshing the page, but the javascript file doesn't update on what I'm doing. Probably the js file is from cache. How do I solve this?

**Comment by fajarnuha** [comment]
I don't know if this is valet-specific issue or not but I solve the problem by refreshing the page using cmd+shift+R which essentially reload all files including css and js

**Comment by adamwathan** [comment]
Yeah your browser is caching the files, I usually avoid that by versioning
my assets so the file name changes when the contents change. You can do
that with Elixir's `version` function 👍🏻
