### ISSUE TITLE
Valet 2.0.3: 500 Bad Gateway (upstream sent too big header)

### ISSUE THREAD

**Issue by jplhomer** [laravel/valet#290]
PHP stack traces are getting cut off by Nginx with the error `upstream sent too big header while reading response header from upstream`.

Would it be possible to change the way PHP stack traces are delivered, or to increase the limit for this issue?

Here's an example stack trace from `~/.valet/Log/nginx-error.log`:

```
2017/01/09 18:15:35 [error] 41481#0: *1 FastCGI sent in stderr: "PHP message: PHP Warning:  A non-numeric value encountered in /Users/jplhomer/Documents/Sites/site/content/plugins/advanced-custom-fields-pro/pro/fields/flexible-content.php on line 1470
PHP message: PHP Warning:  A non-numeric value encountered in /Users/jplhomer/Documents/Sites/site/content/plugins/advanced-custom-fields-pro/pro/fields/flexible-content.php on line 1470
PHP message: PHP Warning:  A non-numeric value encountered in /Users/jplhomer/Documents/Sites/site/content/plugins/advanced-custom-fields-pro/pro/fields/flexible-content.php on line 1470
PHP message: PHP Warning:  A non-numeric value encountered in /Users/jplhomer/Documents/Sites/site/content/plugins/advanced-custom-fields-pro/pro/fields/flexible-content.php on line 1470
PHP message: PHP Warning:  A non-numeric value encountered in /Users/jplhomer/Documents/Sites/site/content/plugins/advanced-custom-fields-pro/pro/fields/flexible-content.php on line 1470
PHP message: PHP Warning:  A non-numeric value encountered in /Users/jplhomer/Documents/Sites/site/content/plugins/advanced-custom-fields-pro/pro/fields/flexible-content.php on line 1470
PHP message: PHP Warning:  A non-numeric value encountered in /Users/jplhomer/Documents/Sites/site/content/plugins/advanced-custom-fields-pro/pro/fields/flexible-content.php on line 1470
PHP message: PHP Warning:  A non-numeric value encountered in /Users/jplhomer/Documents/Sites/site/content/plugins/advanced-custom-fields-pro/pro/fields/flexible-content.php on line 1470
PHP message: PHP Warning:  A non-numeric value encountered in /Users/jplhomer/Documents/Sites/site/content/plugins/advanced-custom-fields-pro/pro/fields/flexible-content.php on line 1470
PHP message: PHP Warning:  A non-numeric value encountered in /Users/jplhomer/Documents/Sites/site/content/plugins/advanced-custom-fields-pro/pro/fields/flexible-content.php on line 1470
PHP message: PHP Warning:  A non-numeric value encountered in /Users/jplhomer/Docu
2017/01/09 18:15:35 [error] 41481#0: *1 upstream sent too big header while reading response header from upstream, client: 127.0.0.1, server: site.dev, request: "GET /wordpress/wp-admin/post.php?post=5411&action=edit&message=1 HTTP/2.0", upstream: "fastcgi://unix:/Users/jplhomer/.valet/valet.sock:", host: "site.dev", referrer: "https://site.dev/wordpress/wp-admin/post.php?post=5411&action=edit"
```

**Comment by drbyte** [comment]
Since you're using `https://site.dev` that tells me you've run `valet secure` and therefore you have a `~/.valet/Nginx/site.dev` file for your Nginx config.

In that file you can edit the configuration details, so I might suggest trying the suggestions at http://stackoverflow.com/questions/13894386/upstream-too-big-nginx

And whenever you make changes to your nginx configs, you'll need to either `valet restart` or `sudo brew service restart nginx` to take effect.

That's where I'd start anyway ...

**Comment by jplhomer** [comment]
@drbyte Thanks - that helped me. Oddly enough, I'm still seeing a stream of errors in the Nginx now in error log, but no errors served in the browser. I'm able to finish what I needed to get done, though 👍 Don't know if this is something to address with the default Valet setup.

**Comment by elaman** [comment]
@drbyte is helpful, but it took me some time to make suggested StackOverflow link work with Valet. 

1. Create `~/.valet/Nginx/all.conf` with this:
```
proxy_buffer_size   4096k;
proxy_buffers   128 4096k;
proxy_busy_buffers_size   4096k;
```

2. Append this to `/usr/local/etc/nginx/fastcgi_params`
```
fastcgi_buffer_size 4096k;
fastcgi_buffers 128 4096k;
fastcgi_busy_buffers_size 4096k;
```

**Comment by karudonaldson** [comment]
@elaman thanks, your suggestion fixed the issue for me.  Why wouldn't this be a default I wonder?  Perhaps more default allowances should be set I guess

**Comment by darthsteven** [comment]
The solution in https://github.com/laravel/valet/issues/290#issuecomment-398686133 worked for me.
This was with a Drupal 8 site that outputs a lot of headers when developing, this wasn't even outputting a stack trace or similar :)

**Comment by ravenberg** [comment]
> @drbyte is helpful, but it took me some time to make suggested StackOverflow link work with Valet.
> 
> 1. Create `~/.valet/Nginx/all.conf` with this:
> 
> ```
> proxy_buffer_size   4096k;
> proxy_buffers   128 4096k;
> proxy_busy_buffers_size   4096k;
> ```
> 
> 1. Append this to `/usr/local/etc/nginx/fastcgi_params`
> 
> ```
> fastcgi_buffer_size 4096k;
> fastcgi_buffers 128 4096k;
> fastcgi_busy_buffers_size 4096k;
> ```
> 
> _Note: 4096k is something you need to figure out what best works for you._

This solved a similar issue I had today. 🙏

**Comment by BirenGrooveHere** [comment]
> @drbyte is helpful, but it took me some time to make suggested StackOverflow link work with Valet.
> 
> 1. Create `~/.valet/Nginx/all.conf` with this:
> 
> ```
> proxy_buffer_size   4096k;
> proxy_buffers   128 4096k;
> proxy_busy_buffers_size   4096k;
> ```
> 
> 1. Append this to `/usr/local/etc/nginx/fastcgi_params`
> 
> ```
> fastcgi_buffer_size 4096k;
> fastcgi_buffers 128 4096k;
> fastcgi_busy_buffers_size 4096k;
> ```
> 
> _Note: 4096k is something you need to figure out what best works for you._

Thanks buddy

**Comment by andrewdaluz** [comment]
For who did the fix applied on the comment above and it didn't work you might restart the Nginx by brew command:

    brew services restart nginx && valet restart

**Comment by drbyte** [comment]
> For who did the fix applied on the comment above and it didn't work you might restart the Nginx by brew command:
> 
> ```
> brew services restart nginx && valet restart
> ```

No, without using sudo you should just `stop` the services.
You don't want to restart nginx or php or dnsmasq as non-root.
So better to first stop them all as non-root (in case you started them as non-root):
```
brew services stop nginx
brew services stop dnsmasq
brew services stop php
```
and then let Valet start them up as root:
```
valet start
```
