### ISSUE TITLE
PHP 7.1 issue on macOS sierra

### ISSUE THREAD

**Issue by anishdcruz** [laravel/valet#291]
After upgrading valet, i got this wired "<?php" prefixed to every artisan command.

php version 

PHP 7.1.0 (cli) (built: Dec  2 2016 11:32:42) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.1.0-dev, Copyright (c) 1998-2016 Zend Technologies

<img width="398" alt="screen shot 2017-01-11 at 9 28 55 am" src="https://cloud.githubusercontent.com/assets/2182620/21837967/73c0dfa0-d7e0-11e6-8908-9ea89e04789a.png">

**Comment by drbyte** [comment]
I notice you're using an alias `art` to invoke artisan.
Does the same symptom occur if you run it directly, without the alias? ie: `php artisan cache:clear`

**Comment by anishdcruz** [comment]
@drbyte yes both commands produce the same issue.

The issue is produced by php 7.1, can confirm it on ubuntu 16.04 also.
After downgrading php to 7.0, the issue is gone, works as normal.

**Comment by drbyte** [comment]
Strange, because I'm using 7.1 and have never run into the problem you describe.
