### ISSUE TITLE
fastcgi path_info not configured by default

### ISSUE THREAD

**Issue by randycasburn** [laravel/valet#295]
New install Valet 2.0.3 running PHP 7.1.0 on MacOS Sierra 10.12

**To Reproduce:**
```
mkdir test
cd test
echo "<?php print_r(\$_SERVER); ?> > index.php
valet link test
curl http://test.dev/app.php/dog/cat/chicken   // This assumes default *.dev tld 
```
path_info will not be in the $_SERVER superglobal.

**To Fix**
_Change fastcgi_params:_
- [ ] Add: `fastcgi_param PATH_INFO  $fastcgi_path_info;`

_Change valet.conf:_
    - _Change PHP location regex:_
- [ ] From: `location ~ \.php$`
- [ ] To: `location ~ [^/]\.php(/|$)`

**This provided a proper path_info for my installation.**

Thanks for listening.

**Comment by drbyte** [comment]
Confirmed. This is still the case with v2.0.12

Your workaround should suffice.

**Comment by drbyte** [comment]
IMO this can be closed, as a workaround is posted, and doesn't appear to be a real need for it.
In #235 more info was requested with no response.
In #340 a workaround was given for a very specific case.
No other mentions.
