### ISSUE TITLE
php71 stops after valet secure

### ISSUE THREAD

**Issue by sheldonkotyk** [laravel/valet#301]
Sheldons-MacBook-Pro:Sites sheldon$ valet secure kotyk
The [kotyk.dev] site has been secured with a fresh TLS certificate.
Sheldons-MacBook-Pro:Sites sheldon$ brew services list
Name    Status  User Plist
dnsmasq started root /Library/LaunchDaemons/homebrew.mxcl.dnsmasq.plist
mariadb started root /Library/LaunchDaemons/homebrew.mxcl.mariadb.plist
nginx   started root /Library/LaunchDaemons/homebrew.mxcl.nginx.plist
php71   stopped
Sheldons-MacBook-Pro:Sites sheldon$ sudo brew services start php71
==> Successfully started `php71` (label: homebrew.mxcl.php71)
Sheldons-MacBook-Pro:Sites sheldon$ brew services list
Name    Status  User Plist
dnsmasq started root /Library/LaunchDaemons/homebrew.mxcl.dnsmasq.plist
mariadb started root /Library/LaunchDaemons/homebrew.mxcl.mariadb.plist
nginx   started root /Library/LaunchDaemons/homebrew.mxcl.nginx.plist
php71   started root /Library/LaunchDaemons/homebrew.mxcl.php71.plist
Sheldons-MacBook-Pro:Sites sheldon$ valet secure pghockey
The [pghockey.dev] site has been secured with a fresh TLS certificate.
Sheldons-MacBook-Pro:Sites sheldon$ brew services list
Name    Status  User Plist
dnsmasq started root /Library/LaunchDaemons/homebrew.mxcl.dnsmasq.plist
mariadb started root /Library/LaunchDaemons/homebrew.mxcl.mariadb.plist
nginx   started root /Library/LaunchDaemons/homebrew.mxcl.nginx.plist
php71   stopped

Had to follow these instructions to even get to this point.
https://github.com/laravel/valet/issues/282#issuecomment-269997175

**Comment by TheDeadCode** [comment]
Also got this error.

**Comment by mattstauffer** [comment]
Much has changed since this comment. If anyone gets this issue with a modern version of the codebase, please open a new issue. Thanks!
