### ISSUE TITLE
Query strings don't work with lumen after valet secure.

### ISSUE THREAD

**Issue by ladea** [laravel/valet#302]
Query strings don't work with lumen after valet secure.

Hitting any route with query string generates NotFoundHttpException.

Way to reproduce the problem:

1. Create new lumen project "blog".
2. Make it secure with "valet secure blog".
3. Try to load https://blog.dev/?page=1, you should see a NotFoundHttpException.

Software that I'm using:
MacOS Sierra 10.12.3
Valet 2.0.3
Lumen 5.3.3
Php 7.1.1
Nginx 1.10.2

The problem doesn't exist with valet secure and laravel.
The problem doesn't exist with HTTP protocol and lumen.

**Comment by ramdanisource** [comment]
same with me, i'm using laravel valet on ubuntu

**Comment by mattstauffer** [comment]
Can't reproduce. Please re-open if this is still an issue.
