### ISSUE TITLE
Not loading php extensions

### ISSUE THREAD

**Issue by nerijunior** [laravel/valet#303]
My valet installations was not loading the php extensions, if I use php artisan server works fine but using valet the `phpinfo();` doesn't show any extension.

What I can do?

**Comment by drbyte** [comment]
In order to replicate or test, it would be helpful if you were to provide a list of extensions you're expecting, as well as how and where you installed them.

**Comment by nerijunior** [comment]
The extensions:

`brew install php71-mcrypt php71-mongodb php71-redis`

Some commands to check if the extensions was installed:

```
$ php -v
PHP 7.1.1 (cli) (built: Jan 21 2017 13:36:56) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
```

```
$ php -i | grep mcrypt
Additional .ini files parsed => /usr/local/etc/php/7.1/conf.d/ext-mcrypt.ini,
Registered Stream Filters => zlib.*, bzip2.*, convert.iconv.*, string.rot13, string.toupper, string.tolower, string.strip_tags, convert.*, consumed, dechunk, mcrypt.*, mdecrypt.*
mcrypt
mcrypt support => enabled
mcrypt_filter support => enabled
mcrypt.algorithms_dir => no value => no value
mcrypt.modes_dir => no value => no value
```

```
$  php -i | grep mongo
/usr/local/etc/php/7.1/conf.d/ext-mongodb.ini,
mongodb
mongodb support => enabled
mongodb version => 1.2.2
mongodb stability => stable
libmongoc version => 1.5.0
mongodb.debug => no value => no value
```

```
$ php -i | grep redis
/usr/local/etc/php/7.1/conf.d/ext-redis.ini
redis
Registered save handlers => files user redis rediscluster redis rediscluster
This program is free software; you can redistribute it and/or modify
```

**Comment by drbyte** [comment]
Hmmm ... works for me ... :(

Before you posted I didn't have the `php71-redis` extension installed, so that's a good one to test with. 

(I don't use mcrypt because Laravel switched to more modern and more reliable encrypt tools, and nothing else I do needs the antiquated mcrypt anymore.)

I checked `php -i | grep redis` and saw only the "can redistribute it" line, as expected.
Also checked `phpinfo()` from a browser page served by `valet`, and redis wasn't mentioned.

Then I ran:
```
brew install php71-redis
sudo brew services restart php71
sudo brew services restart nginx
```
(note: `sudo` because nginx runs as root, and also uses ports 80/443 which are lower than 1024 so must use sudo)

now when I visit my browser page showing the `phpinfo()` output I see:

```
redis

Redis Support	enabled
Redis Version	3.0.0
```

and from CLI:

```
php -i | grep redis
/usr/local/etc/php/7.1/conf.d/ext-redis.ini,
redis
Registered save handlers => files user redis rediscluster redis rediscluster
```

**Comment by nerijunior** [comment]
I don't know why, but now it's working:

```
brew uninstall --force php71 php71-mongodb php71-mcrypt php71-redis
composer global remove laravel/valet
brew uninstall nginx
brew uninstall dnsmasq
brew cleanup
brew prune
```

```
brew install nginx --with-http2 php71
cd /usr/local/etc/php
rm -rf 7.1/conf.d/ext-*
rm -rf ~/.valet
composer global require laravel/valet
valet install
valet start
brew install php71-redis php71-mongodb
sudo brew services restart php71
valet restart
```

**Comment by rafaelcpalmeida** [comment]
I had the same issue and got it working using @drbyte solution:

```
sudo brew services restart php71
sudo brew services restart nginx
```

Before this I've only tested without `sudo` and kept failing.
