### ISSUE TITLE
504 Gateway Timeout

### ISSUE THREAD

**Issue by pryley** [laravel/valet#315]
I think laravel/valet should provide more relaxed defaults for a development environment. Importing a large(ish) database in phpmyadmin causes a `504 Gateway Time-out` error.

To fix the 504 error you need to change the default timeout to more than 30 seconds. Here's how to change it to 5min (300 seconds):

1. `/usr/local/etc/php/{version}/conf.d/php.ini`
```ini
max_execution_time = 300
```
2. https://github.com/laravel/valet/blob/master/cli/Valet/PhpFpm.php#L57
```php
function updateConfiguration()
{
    $contents = $this->files->get($this->fpmConfigPath());

    $contents = preg_replace('/^user = .+$/m', 'user = '.user(), $contents);
    $contents = preg_replace('/^group = .+$/m', 'group = staff', $contents);
    $contents = preg_replace('/^listen = .+$/m', 'listen = '.VALET_HOME_PATH.'/valet.sock', $contents);
    $contents = preg_replace('/^;?listen\.owner = .+$/m', 'listen.owner = '.user(), $contents);
    $contents = preg_replace('/^;?listen\.group = .+$/m', 'listen.group = staff', $contents);
    $contents = preg_replace('/^;?listen\.mode = .+$/m', 'listen.mode = 0777', $contents);
    // Enable the "request_terminate_timeout" parameter
    $contents = preg_replace('/^;?request_terminate_timeout = .+$/m', 'request_terminate_timeout = 300', $contents);

    $this->files->put($this->fpmConfigPath(), $contents);
}
```
3. https://github.com/laravel/valet/blob/master/cli/stubs/valet.conf#L25
```nginx
location ~ \.php$ {
    fastcgi_split_path_info ^(.+\.php)(/.+)$;
    fastcgi_pass unix:VALET_HOME_PATH/valet.sock;
    fastcgi_index VALET_SERVER_PATH;
    include fastcgi_params;
    fastcgi_param SCRIPT_FILENAME VALET_SERVER_PATH;
    # Set the "fastcgi_read_timeout" parameter
    fastcgi_read_timeout 300;
}
```
4. https://github.com/laravel/valet/blob/master/cli/stubs/secure.valet.conf#L34
```nginx
location ~ \.php$ {
    fastcgi_split_path_info ^(.+\.php)(/.+)$;
    fastcgi_pass unix:VALET_HOME_PATH/valet.sock;
    fastcgi_index VALET_SERVER_PATH;
    include fastcgi_params;
    fastcgi_param SCRIPT_FILENAME VALET_SERVER_PATH;
    # Set the "fastcgi_read_timeout" parameter
    fastcgi_read_timeout 300;
}
```

**Comment by 3alampro** [comment]
thanks this helped me with Ajax file uploading 
I no longer see 504 Gateway Timeout when uploading files with Ajax request

**Comment by mityukov** [comment]
Which files should be changed on an existing/working Valet installation? Something in ~/.valet ?
Is it possible to disable Timeout completely (I use Valet on my notebook, not on server, so I an stop any processes myself, if need to).

**Comment by lazyguru** [comment]
Valet just installs nginx via brew (unless it is already installed).  You can always modify the configs under `/usr/local/etc/nginx/`.  If you have used `valet secure` on the site then there is also a site specific nginx config created under `~/.valet/Nginx/`

**Comment by tiagomatosweb** [comment]
I've got the same issue, but much more frequent when I make multiple requests.
However, 
1. /usr/local/etc/php/{version}/conf.d/php.ini 
I don't have php.ini. I do have php-memory-limits.ini instead. Should I create php.ini or set in the php-memory-limits.ini?

2/3/4 - Couldn't find those files, any clue?

```
$ valet -V
Laravel Valet version 2.0.5
```

```
$ php -v
PHP 7.1.8 (cli) (built: Aug  7 2017 15:02:45) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
```

```
$ ls /usr/local/etc/php/7.1/conf.d/
php-memory-limits.ini 
```

**Comment by bkkrishna** [comment]
Any replies/solutions to @tiagomatosweb's problem? I am stuck with the same problem.

**Comment by sylouuu** [comment]
For those who are stuck with 5 concurrent max requests:

```
/usr/local/etc/php/7.1/php-fpm.d/www.conf
```

```
pm.max_children = 200
```

If you want to boost the perf:


```
pm.start_servers = 20
pm.min_spare_servers = 10
pm.max_spare_servers = 20
pm.process_idle_timeout = 10s
pm.max_requests = 500
```

```
sudo brew services restart php71
``

**Comment by navyhan** [comment]
非常感谢楼主,对于一直没有解决问题的小伙伴看好了. 直接修改 /usr/local/etc/nginx/valet/valet.conf 在差不多22行左右
`location ~ \.php$ {
        #下面这行是新加的,加好就好了 哈哈 
        fastcgi_read_timeout 300; 
        fastcgi_split_path_info ^(.+\.php)(/.+)$;`

**Comment by tiagomatosweb** [comment]
@bkkrishna I have solved my issue adding

```
client_header_timeout 3000;
client_body_timeout 3000;
fastcgi_read_timeout 3000;
fastcgi_buffers 8 128k;
fastcgi_buffer_size 128k;
```

to `~/usr/local/etc/nginx.confg` file under `http {} `object.

Then restart the services `valet restart`

**Comment by ctf0** [comment]
maybe instead of fiddling around to find the correct files to change, could valet instead make an alias to the files inside the `.valet` folder ?

**Comment by mattstauffer** [comment]
Closing this issue as it seems there are myriad solutions presented but no forward movement for their impact on Valet; @ctf0 if you'd like to continue that proposal, would you please open it as a separate (and more fleshed-out) issue?

**Comment by clarknelson** [comment]
This is still an issue! My valet installation is giving me a 504 and I do not know how to fix it

**Comment by drbyte** [comment]
> The /Users/clarknelson/.config/valet/valet.sock file exists, but nothing prints when I use cat on it. When I try to open it with a text editor it says Unknown system error -102.

That's normal. Socket files aren't intended to be read/used by other than the system service that created them. You can't `cat` its contents, nor can you view it in a text editor.

**Comment by clarknelson** [comment]
It looks like `website.test/admin` works while `website.test` seems to not respond and then eventually rest on a 504 error.

**Comment by clarknelson** [comment]
Thank you for your help.

It looks like maybe I spoke too soon, both the normal and `/admin` versions of the site return 504.

I get a few messages like this when running `valet install` implying that php 7.3 needs to be installed. I don't believe this is the culprit because other sites work. Also 7.3 isn't even available on homebrew yet.

`PHP Warning:  file_get_contents(/usr/local/etc/php/7.3/php-fpm.d/www.conf): failed to open stream: No such file or directory in /Users/clarknelson/.composer/vendor/laravel/valet/cli/Valet/Filesystem.php on line 112`

I've already uninstalled nginx, removed the nginx directory, and then reinstalled both nginx and valet.  I am getting the same error.

All of the websites work besides this one, which makes me think it is a problem with the project. Unfortunately I don't have any clue what this is. There is no .htaccess for nginx, I have tried to clean up any config files. Wow I am frustrated

**Comment by clarknelson** [comment]
Now all the websites are giving me 504. What a mess! Nothing is working anymore

**Comment by drbyte** [comment]
PHP 7.3 is available on homebrew. 

If everything is saying bad gateway then it's likely that your PHP is the problem.

A complete reset of valet (er, well, the nginx/php part anyway; I'm assuming dnsmasq is resolving the .test TLD properly) can be done via:
```sh
valet stop
brew services list  # (should show both nginx and php as stopped)
brew uninstall php nginx
rm -rf /usr/local/etc/nginx /usr/local/etc/php
rm -rf ~/.config/valet
composer global update
valet install
valet start
```

**Comment by clarknelson** [comment]
Seems to be working a bit better. I received the following error during install though:

    Installing php71...
    [php71] is not installed, installing it now via Brew... 🍻
    Updating PHP configuration...

    In Brew.php line 195:
    Unable to determine linked PHP.

**Comment by drbyte** [comment]
What's the output of `brew info php` and `brew services list` ?

**Comment by clarknelson** [comment]
`brew services list`

dnsmasq started root        /Library/LaunchDaemons/homebrew.mxcl.dnsmasq.plist
mysql   started root        /Library/LaunchDaemons/homebrew.mxcl.mysql.plist
nginx   started clarknelson /Users/clarknelson/Library/LaunchAgents/homebrew.mxcl.nginx.plist
php     started root        /Library/LaunchDaemons/homebrew.mxcl.php.plist
php@7.1 started clarknelson /Users/clarknelson/Library/LaunchAgents/homebrew.mxcl.php@7.1.plist

**Comment by clarknelson** [comment]
`brew info php`

php: stable 7.3.0 (bottled)
General-purpose scripting language
https://secure.php.net/
/usr/local/Cellar/php/7.3.0 (521 files, 76.5MB) *
  Poured from bottle on 2018-12-12 at 12:10:06
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/php.rb
==> Dependencies
Build: httpd ✘, pkg-config ✘
Required: apr ✔, apr-util ✔, argon2 ✔, aspell ✔, autoconf ✔, curl-openssl ✔, freetds ✔, freetype ✔, gettext ✔, glib ✔, gmp ✔, icu4c ✔, jpeg ✔, libpng ✔, libpq ✔, libsodium ✔, libzip ✔, openldap ✔, openssl ✔, pcre ✔, sqlite ✔, tidy-html5 ✔, unixodbc ✔, webp ✔
==> Caveats
To enable PHP in Apache add the following to httpd.conf and restart Apache:
    LoadModule php7_module /usr/local/opt/php/lib/httpd/modules/libphp7.so

    <FilesMatch \.php$>
        SetHandler application/x-httpd-php
    </FilesMatch>

Finally, check DirectoryIndex includes index.php
    DirectoryIndex index.php index.html

The php.ini and php-fpm.ini file can be found in:
    /usr/local/etc/php/7.3/

To have launchd start php now and restart at login:
  brew services start php
Or, if you don't want/need a background service you can just run:
  php-fpm
==> Analytics
install: 48,923 (30 days), 128,090 (90 days), 366,326 (365 days)
install_on_request: 44,452 (30 days), 116,312 (90 days), 330,600 (365 days)
build_error: 0 (30 days)

**Comment by drbyte** [comment]
I'm not understanding why your valet is assuming it needs php71. Especially when it shows php as running and is linked to 7.3.

Did you run `composer global update` and let it update valet?  
If you run `valet` it gives you a list of commands, but displays a version number at the top. What's that version number?
(An outdated version of valet (prior to 2.1.5) won't recognize PHP 7.3 as a version number.)

You might want to run `brew update` to ensure you've got the latest definitions for brew.

It might also be worth running `brew doctor` to expose any "issues" brew notes with your system.

**Comment by clarknelson** [comment]
Well i've disabled the php error using the line `pcre.jit=0` in php.ini and I managed to get several websites back up! The original "problem" website is still giving me a 504, but it is likely related to another issue :/ I am running an AJAX call on the homepage which may be throwing a 504, `website.text/admin` does work now for the problem website.

**Comment by drbyte** [comment]
I'm glad you've got it reset and working now.

(for the "problem" domain, perhaps renaming it or linking to it on a different domain with `valet link` may be useful to see if the problem "follows" or if it's specific to the domain name)

Good luck with resolving your app-specific issue!

**Comment by clarknelson** [comment]
Thanks again for your help, the same 504 error appears on the new domain unfortunately, and not much success on disabling the AJAX call.

**Comment by simonhamp** [comment]
I'm also seeing this in the Statamic CP when it's attempting to load images via AJAX. My only solution so far is `valet restart`. As soon as I hit a page in the CP that tries to process a bundle of images, it fails and times out for every request after that.

**Comment by clarknelson** [comment]
@simonhamp make sure all of the images exist !

**Comment by simonhamp** [comment]
They do. I think I’ve managed to solve it by increasing the number of workers nginx spins up

**Comment by AbhinavDobhal** [comment]
Solving this issue is easy: just open the file /usr/local/etc/nginx/valet/valet.conf and add the following lines to the block location ~ \.php$ { } :
proxy_connect_timeout       600;
proxy_send_timeout          600;
proxy_read_timeout          600;
send_timeout                600;
fastcgi_read_timeout        300;
fastcgi_buffers 8 128k;
fastcgi_buffer_size         256k;

Now all you have to do is to run on your valet restart terminal and everything should work fine.

**Comment by drbyte** [comment]
Thanks @AbhinavDobhal 

Putting them in `/usr/local/etc/nginx/fastcgi_params` works well too, since it's a central location and valet loads that file from the same block you mentioned. I recently started exploring using the following to test a suggestion made elsewhere for cookie payload size issues.

`/usr/local/etc/nginx/fastcgi_params`
```text
...

# Very large cookies/headers may throw errors without the following (extremely generous) settings:
fastcgi_buffer_size 4096k;
fastcgi_buffers 128 4096k;
fastcgi_busy_buffers_size 4096k;

# Long-running/slow services
fastcgi_read_timeout 600;
proxy_connect_timeout 600;
proxy_send_timeout 600;
proxy_read_timeout 600;
send_timeout 600;
```

**Comment by fbenas** [comment]
HI all,

I have been experiencing the same issue. I followed the same solution as @simonhamp.

Specifically editing `/usr/local/etc/php/7.3/php-fpm.d/www.conf`

With the following updates:

**Comment by Pab89** [comment]
I spent a lot of time trying to find ~/.valet/Nginx, turns out in newer versions of valet it is under ~/.config/Valet/Nginx. :)

**Comment by jasperf** [comment]
> # Very large cookies/headers may throw errors without the following (extremely generous) settings:
> fastcgi_buffer_size 4096k;
> fastcgi_buffers 128 4096k;
> fastcgi_busy_buffers_size 4096k;
> 
> # Long-running/slow services
> fastcgi_read_timeout 600;
> proxy_connect_timeout 600;
> proxy_send_timeout 600;
> proxy_read_timeout 600;
> send_timeout 600;

Added a new `fastcgi_params` inside `~/.config/Valet/Nginx` and did a `valet restart` and that worked

**Comment by torbentschechne** [comment]
I had this issue today as well with a WordPress Installation. In my case it was an incomplete database dump that caused this. I had no errors in any log that pointed in that direction, but luckily I solved it. Maybe it's useful for somebody else as well...

**Comment by aubreypwd** [comment]
https://dev.to/aubreypwd/how-i-configured-niginx-valet-to-stop-the-504-gateway-time-out-during-long-xdebug-sessions-174i

## How I solved this

Added:

```
    proxy_connect_timeout 1200;
    proxy_read_timeout 1200;
    proxy_send_timeout 1200;
    fastcgi_read_timeout 1200;
    fastcgi_send_timeout 1200;
```

in `/opt/homebrew/etc/nginx/nginx.conf`, right before:

```
    include "/Users/.../.config/valet/Nginx/*";
    include servers/*;
    include valet/valet.conf;
```
