### ISSUE TITLE
DrupalValetDriver rewriting non-clean urls to clean. redirect index.php

### ISSUE THREAD

**Issue by StefanPrintezis** [laravel/valet#316]
Some code in drupal in common/form.inc form_process_autocomplete() is forcing non-clean urls. Because the server normally rewrites index.php?q=[q] to /[q]. That doesn't seem to be working in the Valet drupal driver.

?q=entityreference/autocomplete/single/field_name/node/bundle/NULL/e
This redirects me to index.php and shows a 404.

**Comment by zanami** [comment]
entity reference autocomplete

accessing /entity_reference_autocomplete/user/default/C-KD665IxAezDCL3UhxOafVu0c9QkemJpHAtwH84JDY?q=01

this is q= using Valet

```
Symfony\Component\HttpFoundation\ParameterBag Object
(
    [parameters:protected] => Array
        (
            [q] => /entity_reference_autocomplete/user/default/C-KD665IxAezDCL3UhxOafVu0c9QkemJpHAtwH84JDY
        )

)
```
should be [q] => => 01 or whatever the text is

Is there a quick hack for this? This way all autocomplete fields are useless and those are everywhere in Drupal.

**Comment by romainlp** [comment]
Hi,

Just notice if i comment this line in my driver, in the frontControllerPath method:
```php
if (!empty($uri) && $uri !== '/') {
    // $_GET['q'] = $uri;
}
```
It's seems working.

**Comment by StefanPrintezis** [comment]
I've temporary fixed it by not forcing non-clean URL's in drupal
`diff --git a/includes/form.inc b/includes/form.inc
index cbbdef47..f3daf5b1 100644
--- a/includes/form.inc
+++ b/includes/form.inc
@@ -3982,15 +3982,15 @@ function form_process_autocomplete($element) {
     $element['#autocomplete_input']['#id'] = $element['#id'] .'-autocomplete';
     // Force autocomplete to use non-clean URLs since this protects against the
     // browser interpreting the path plus search string as an actual file.
-    $current_clean_url = isset($GLOBALS['conf']['clean_url']) ? $GLOBALS['conf']['clean_url'] : NULL;
-    $GLOBALS['conf']['clean_url'] = 0;
+    // $current_clean_url = isset($GLOBALS['conf']['clean_url']) ? $GLOBALS['conf']['clean_url'] : NULL;
+    // $GLOBALS['conf']['clean_url'] = 0;
     // Force the script path to 'index.php', in case the server is not
     // configured to find it automatically. Normally it is the responsibility
     // of the site to do this themselves using hook_url_outbound_alter() (see
     // url()) but since this code is forcing non-clean URLs on sites that don't
     // normally use them, it is done here instead.
     $element['#autocomplete_input']['#url_value'] = url($element['#autocomplete_path'], array('absolute' => TRUE, 'script' => 'index.php'));
-    $GLOBALS['conf']['clean_url'] = $current_clean_url;
+    // $GLOBALS['conf']['clean_url'] = $current_clean_url;
   }
   return $element;
 }`

**Comment by maxplus** [comment]
@StefanPrintezis
Thanks, your patch on drupal/core fixed this issue for me for my local Laravel/Valet dev enviroment on my MAC (was getting ajax errors for autocomplete fields)
