### ISSUE TITLE
Verbose option isn't that verbose.

### ISSUE THREAD

**Issue by cornedor** [laravel/valet#317]
The verbose option isn't really that verbose. Debugging a valet start which says everything works fine is quite hard when it doesn't log anything at all and requires edits in the script it self. See for example https://github.com/laravel/valet/issues/305.

Maybe don't show the option if it doesn't change anything.

**Comment by drbyte** [comment]
True.

Bypassing the `valet` command and directly running `brew services start php -v` will show more verbose details.
