### ISSUE TITLE
Valet and Pow

### ISSUE THREAD

**Issue by skylerkatz** [laravel/valet#327]
I have a couple of Ruby projects at work that are set up to use POW in development. I am trying to get Laravel Valet up and running on the same computer but POW seems to be taking precedent to Valet. By default both use .dev, but I have updated Valet to serve from .app instead.

I have attempted to just link valet to the laravel project, and that did not work. It also did not work when parking the whole "sites" folder.

Has anyone experienced this before/know of any workarounds to let both services play nicely with each other?

**Comment by plcosta** [comment]
+1

I'm using puma-dev (like POW) to Ruby development and Laravel Valet to PHP. Unfortunately the both services doesn't play nicely with each other.

@skylerkatz Did you solve this issue?

**Comment by skylerkatz** [comment]
I have not figured out a workaround for this.  Since I only have one laravel project at the moment and multiple ruby projects, I just use POW and Homestead.

**Comment by skylerkatz** [comment]
Since this is not that big of an issue, and I do not have the ability to attempt a fix, I am going to close this out.

Valet is still a great project!
