### ISSUE TITLE
[Idea] Custom Local Drivers

### ISSUE THREAD

**Issue by vinkla** [laravel/valet#330]
What about making it possible to add a custom local driver to your current project and make Valet automagically check the directory for you. If there is an `CustomDriver` class available in the `vendor` directory we could use that as a driver instead of the default ones. This would make it easy to add support for the non-supported frameworks.

@adamwathan what do you think? Would it be possible?

**Comment by adamwathan** [comment]
What if I told you this was already possible but undocumented? 👀

https://github.com/laravel/valet/pull/213

**Comment by vinkla** [comment]
Oh, cool. Didn't know about that!

Out of curiosity. How many stars and downloads does a framework need to have to get a driver merged into Valet?

**Comment by adamwathan** [comment]
No real metric for that, the drivers take a long time to get merged just because it's hard to make time to test them locally before merging :/

Going to close this since we actually support this feature already 👍
