### ISSUE TITLE
Chrome Devtools Remote Devices

### ISSUE THREAD

**Issue by james-brndwgn** [laravel/valet#331]
Is it possible to access .dev domains through the Remote Devices > Port Forwarding feature in Chrome Devtools? I've been able to make it access localhost, but so far no luck accessing something like "mysite.dev:8080"

My Port Forwarding settings are like this:

Device: 8080
Local address: mysite.dev:80

Devtools article for reference: https://developers.google.com/web/tools/chrome-devtools/remote-debugging/local-server

**Comment by ramon-villain** [comment]
Did you try `valet share`? https://laravel.com/docs/5.4/valet#sharing-sites

**Comment by james-brndwgn** [comment]
Yes and it works, as does xip.io, it was more of a curiosity
