### ISSUE TITLE
[Proposal] Valet Secure Check

### ISSUE THREAD

**Issue by brandonferens** [laravel/valet#332]
I just spent several hours trying to figure out why valet broke after I ran `valet secure`. Everything just stopped working. So I reversed it, but to no avail. I finally came across a thread telling me to try `brew install nginx --with-http2`, which finally fixed it.

My proposal is that within the `secure` command, a check should be run to see if `http2` exists on the nginx server. If it does not, then either issue an info message stating that it should get installed with the above mentioned brew command, or just run the command from within valet.

I looked through the code and in `Valet/Nginx.php` line 40, it is ensuring that nginx is installed and `--with-http2` is passed in as an option. However in `Valet/Brew.php` line 59, the if statement is only checking that nginx is installed, but not checking that the `--with-http2` option is also installed.

I'm not proficient at CLI, but doing something like `brew info nginx | grep -- "--with-http2"` works.

**Comment by drbyte** [comment]
I haven't had any issue with the --with-http2 being used automatically. 

Is this still a "current" issue? is it really something Valet should be concerned with?
I'm inclined to close it.

**Comment by mattstauffer** [comment]
Closing; can be re-opened if we get a response back.

**Comment by brandonferens** [comment]
Hey @drbyte and @mattstauffer. It has been a long time since I created this PR. I don't know if this continues to be an issue or not. I haven't seen the issue since. Is it a result of now having nginx installed with http2 or because something else in the valet code base changed? Not sure.

**Comment by mattstauffer** [comment]
OK, thanks @brandonferens! If you run into it again please open a new issue and we'll get to it faster :)
