### ISSUE TITLE
[HARD] Valet 404 Not Found

### ISSUE THREAD

**Issue by wesharehoodies** [laravel/valet#333]
Hello

After three attempts trying to get Valet to work I'm turning here for help. Here is my setup:

![img](http://i.imgur.com/zoY1kRk.png)

![img2](http://i.imgur.com/XMaEXw3.png)

I even tried using configurating  the .pow and it still does not work. Any clues? I killed my apache (free up port 80), reinstalled everything 3x times and yet not working. 

Anyone smart enough to figure out why this is happening?

**Comment by joshmanders** [comment]
Did you make sure to restart the services? `sudo brew services restart (nginx|php71)`?

**Comment by wesharehoodies** [comment]
@joshmanders yes I tried that, does not fix.

**Comment by drbyte** [comment]
I've usually seen that if anything else was running on port 80 prior to installing valet then even killing the previous process might not be enough ... but a reboot magically solves it all. Strange I know, but has been the solution for several.

**Comment by wesharehoodies** [comment]
@drbyte http://d.pr/i/WmPF/23IzKuLy Here's my port 80 stuff. No apache stuff..

**Comment by bravist** [comment]
I also encountered this problem, you can go to tracking problem as I thoughtEnter the user home directory /. Valet/Log

```bash
$ cd  /Users/chenghuiyong/.valet/Log

$ tail nginx-error.log
```

**Comment by wesharehoodies** [comment]
@bravist 

The `.log` file is empty =(

<img width="230" alt="tail" src="https://cloud.githubusercontent.com/assets/11220736/24837405/f301f088-1d3b-11e7-8183-e0ad50847bbb.png">

**Comment by bravist** [comment]
@wesharehoodies, try to reinstall the valet  or your project

**Comment by chamalC** [comment]
I have the same issue , I have even reinstall valet and stoped apache but still not working

**Comment by wesharehoodies** [comment]
Sorry, can't help, didn't get it to work properly. 😞

**Comment by Rahulsharma0810** [comment]
Try with

valet uninstall
valet install
valet link
brew services restart --all
valet restart
valet open

Best of Luck !

**Comment by archy-bold** [comment]
I'm having the same issues and none of the above works. There is another user on this machine who has Valet installed so could it be related to multiple users?

**Comment by Rahulsharma0810** [comment]
If Valet installed on Separate users /home directory then there should should be no issue

**Comment by archy-bold** [comment]
There _should_ be no issue, but there definitely is. I've now managed to get it working on my user account but it looks like the other user can only access my sites. Despite having their own `~/.valet` folder and configuration. I guess the 404 comes from the fact that it's using another valet installation and can't find the requested project.

I tried restarting valet, the homebrew services and reinstalling on the other account. Nothing worked.

**Comment by blu-towers** [comment]
archy-bold is right having two users on the same machine both with Valet causes an absolute nightmare. I ended up deleting one user, chown all /usr/local folders back to main user then reinstalling brew services and valet.

I still had problems ping test.dev not found. Turns out /user/local/etc/dnsmasq.conf had references to my old users dnsmasq.conf file deleting this now all working. I think this conf file may have contributed to the 404 issue to start with but i can't be sure.

Found this info on [https://stackoverflow.com/questions/37172691/valet-laravel-dns-address-can-not-be-found]([https://stackoverflow.com/questions/37172691/valet-laravel-dns-address-can-not-be-found])

**Comment by rickvdl** [comment]
Having the same issue with multiple users, can't seem to figure it out.

**Comment by jeffreyroberts** [comment]
I am having this issue for a CakePHP 3 application

I did valet park in the parent folder of the application and I am getting

![screen shot 2017-10-20 at 7 57 53 pm](https://user-images.githubusercontent.com/2320614/31845644-010af624-b5d1-11e7-977b-178f962466c0.png)

**Comment by dpatey** [comment]
@alexgiuvara Thank you.  The link issue was what causing my 404s.

**Comment by Ahmed3rab** [comment]
If anyone is still having an issue, I just had this issue with Craft3, what I did is I went to the web folder inside the root folder of the craft project, ran valet link <url>.<test/dev> and it worked. my entry was valet link craft, since my only domain was test, so valet automatically set the url to craft.test

**Comment by tom-tom-cp** [comment]
@alexgiuvara thanks mate your linking tip solved it for me.

**Comment by cdils** [comment]
@alexgiuvara Thank you! Solves my problem. I'll add this here to be explicit in case in helps someone else. If you've previously run: 
`cd parent && valet link my-project` then do 
`cd parent && valet unlink my-project`. That'll clean up previous, incorrect link and then run 
`cd parent/my-project && valet link my-project` per @alexgiuvaras's tip.

**Comment by Mayvis** [comment]
Try `valet links` to see your project path, and `valet link` again.

**Comment by manhlinhng** [comment]
Yep. I had issue on Mojave. 
You can unlink your project wrong link path project.
Example: Park path: `path_to/projects` and project path `path_to/projects/laravel`
Step by step
1. Unlink project (laravel) wrong path.
`cd projects`
`valet unlink laravel`
2. Go to your project (laravel) and create new link
`cd path_to/project/laravel`
`valet link laravel`
`valet restart`
DONE.

**Comment by ligne13** [comment]
I also found that if you prefix your site domain with "www." it may not work. For example : www.mysite.test does not work, but mysite.test does.

Anyway, I think valet automatically handles the www subdomain when creating a site.

**Comment by bedus-creation** [comment]
I got the same problem and solved by..
cd ~/.composer/

sudo chown -R $(whoami) vendor

**Comment by drbyte** [comment]
> I got the same problem and solved by..
> cd ~/.composer/
> 
> sudo chown -R $(whoami) vendor

Or even better: 
```sh
sudo rm -rf ~/.composer/vendor
composer global update
```

(I say "better" because if you've got a mishmash of permissions problems in that directory, then you've probably also got other problems, and clearing it all and reinstalling stuff is more thorough.)

**Comment by Ahmed-Aboud** [comment]
if you are trying to link normal php folders  ( no framework ) you must specify the file and the file ending example :` http://phpinfo.localhost/info.php`

**Comment by wakjoko** [comment]
please rename your project if it contains underscore.
i found it the hard way though.. hope this will help someone else.

example project name: my_project
rename it to: my-project

```
valet unlink my_project
valet link my-project
```

**Comment by musafir928** [comment]
-> cd path/to/your/project/folder
-> valet link

**Comment by RichardFisher8410** [comment]
cd into your project folder. In my case this was the folder that contained all my WordPress files and folders (root of my website) and run "valet link". I tried other ways, but this was the only one that worked for me.

**Comment by dima2306** [comment]
> please rename your project if it contains underscore.
> i found it the hard way though.. hope this will help someone else.
> 
> example project name: my_project
> rename it to: my-project
> 
> ```
> valet unlink my_project
> valet link my-project
> ```

Thanks for the notice. _ is really a problem.
I've just renamed project name in the Nginx configuration, certificates issued for it, symlink in .valet/Sites. So actually where project is located /var/www/project_name is with underscore, but elsewhere name is merged.
**valet:links** gives

```
+-------------+-----+--------------------------+-------------------------+
| Site        | SSL | URL                      | Path                    |
+-------------+-----+--------------------------+-------------------------+
| projectname |     | http://projectname.test  | /var/www/project_name   |
+-------------+-----+--------------------------+-------------------------+
```
And it's working!

**Comment by fjobeir** [comment]
use `valet links` to check the registered links
I had that issue, my mistake was so funny, I simply had the following folder structure:
sites -> project.
under project, I have the api folder and front folder.

I had to apply link on the api, but I was applying it on the project folder. `valet links` helped me discovering the problem

**Comment by solamichealolawale** [comment]
In my own case (Vanilla PHP project), `public` folder was the cause of my issue. 

Inside my project folder, I have a public folder that houses all my assets. 

Turns out the valet driver checks inside the public folder for `index.php` which makes sense because that's how Laravel is configured. 

> So I had to rename the `public` folder that house all my assets to `assets`.

You can rename it to whatever you want.

**Comment by uaibo** [comment]
> I got the same problem and solved by.. cd ~/.composer/
> 
> sudo chown -R $(whoami) vendor

this is the only solution from here that worked for me. I had tried park/unpark, link/unlink, secure/unsecure, reinstall, restart, everything else in the book. Only setting these proper permissions fixed it for me. I have a similar problem in another laptop so will try there too. 
Thanks a lot.

**Comment by chrisgrim** [comment]
For those of you who are having this issue because of multiple Users. This solution solved it for me: 

Create a Sites directory in the second user account at /Users/username/Sites and put my sites into that, then just head back to my main (admin) account where Valet is installed and run...

$ cd /Users/username/Sites
$ valet park
... and I can now access any websites I park in that folder.

**Comment by aimahdi** [comment]
> ```shell
> composer global update
> ```

Finally I have

> In my own case (Vanilla PHP project), `public` folder was the cause of my issue.
> 
> Inside my project folder, I have a public folder that houses all my assets.
> 
> Turns out the valet driver checks inside the public folder for `index.php` which makes sense because that's how Laravel is configured.
> 
> > So I had to rename the `public` folder that house all my assets to `assets`.
> 
> You can rename it to whatever you want.

Finally, I have resolved this. Thank you so much. My project was running and suddenly I went to share my project using valet share. I am assuming it creates a conflict with public folder available on my project.

**Comment by fln31** [comment]
> I also found that if you prefix your site domain with "www." it may not work. For example : [www.mysite.test](http://www.mysite.test) does not work, but mysite.test does.
> 
> Anyway, I think valet automatically handles the www subdomain when creating a site.

THX BUDDY !!! WWW give me crazy
