### ISSUE TITLE
DNS Lookup request time

### ISSUE THREAD

**Issue by rogervila** [laravel/valet#337]
Hello,

I'm not sure if its a bug, but some times valet needs some time to resolve the DNS.

This screenshots have been taken on the same valet link:

**First attempt:**
![captura de pantalla 2017-03-07 a las 15 46 10](https://cloud.githubusercontent.com/assets/6053012/23661529/4c28a4ee-034d-11e7-9a67-83cabd30c47f.png)

**Second attempt:**
![captura de pantalla 2017-03-07 a las 15 46 24](https://cloud.githubusercontent.com/assets/6053012/23661637/9b990c94-034d-11e7-92e5-395f9bfaabdd.png)

Is it normal? 

Thank you.

**Comment by drbyte** [comment]
Despite the many sites I'm using valet with locally, I don't recall ever encountering any DNS lookup delays, especially for local valet-driven sites.

Granted, delays would be a function of `dnsmasq` or your configuration of it.

You might want to look at my `dnsmasq` config as posted in https://github.com/laravel/valet/issues/115 and https://github.com/laravel/valet/issues/299#issuecomment-274177318

**Comment by ryanmortier** [comment]
I'm having sort of the same issue here: https://github.com/Adldap2/Adldap2/issues/408

**Comment by ryanmortier** [comment]
@rogervila Can you post your `/etc/hosts` file?
