### ISSUE TITLE
Custom Share Domains

### ISSUE THREAD

**Issue by AbbyJanke** [laravel/valet#338]
Current Ngrok supports utilizing custom domains using CNAME records. I am currently the only developer of a small non-profit project and generally go from a _dev.*_ to _staging.*_ to _www.*_  I recently made the switch to valet from homestead and loving it currently. But I want to make my dev environment available to my partner for feedback.

https://ngrok.com/docs#upgrade-cname

**Comment by jalenconner** [comment]
This would be awesome 👍

**Comment by PaoloFalomo** [comment]
Yep! i agree 👍

**Comment by michaeldyrynda** [comment]
You should be able to just pass `-hostname` to the valet command and it'll work.

I've been using `valet -region au -subdomain <subdomain>` for some time now
