### ISSUE TITLE
Valet doesn't work offline in Safari

### ISSUE THREAD

**Issue by edalzell** [laravel/valet#339]
I tried to do some work while on the bus the other day but I couldn't get to any of my valet served sites.

The symptom is that I get a "you are not connected to the internet" error in Safari.

Is this a Valet, DNSMasq thing or something completely else.

Apologies if this is not a Valet issue...

**Comment by edalzell** [comment]
If I do [this](http://stackoverflow.com/questions/26840768/yosemite-localhost-resolver-and-dnsmasq-fails-offline#33582801) it works in Chrome but not Safari.

Guess it's a Safari issue and not a Valet issue...closing.

**Comment by drbyte** [comment]
In https://github.com/laravel/valet/issues/115#issuecomment-241275816 I shared what I've done to optimize `dnsmasq`. With this config I've never had the symptom you reported with Safari.
