### ISSUE TITLE
Easy install, no uninstall

### ISSUE THREAD

**Issue by TimOgilvy** [laravel/valet#341]
Valet installs a whole bunch of stuff including nginx.

What it doesn't do is give me any clues about how many things I now need to uninstall.

A bit of a rough guide would be nice.  nginx is running as a service on my mac now and I don't want it to be.  I know I should probably google it like an uber-hacker until my amazing nerd skills overcome the obstacle, but I really don't have the time or energy right now.

Help please?

**Comment by adamwathan** [comment]
Sure, we should update the docs to include this but here you go:

```
valet uninstall
sudo brew services stop nginx
sudo brew services stop php70
sudo brew services stop dnsmasq
brew uninstall nginx
brew uninstall php70
brew uninstall dnsmasq
rm -rf ~/.valet
rm /usr/local/bin/valet
```

...should do the trick.

**Comment by TimOgilvy** [comment]
Thanks, this is really helpful!

**Comment by dwenaus** [comment]
no matter what I try, I cannot delete valet. i get this:

( ! ) Warning: Unknown: failed to open stream: No such file or directory in Unknown on line 0

( ! ) Fatal error: Unknown: Failed opening required '/Users/myusername/.composer/vendor/laravel/valet/server.php' (include_path='.:') in Unknown on line 0
