### ISSUE TITLE
Troubleshooting custom ValetDriver

### ISSUE THREAD

**Issue by mityukov** [laravel/valet#346]
Hi, I'm trying to make my own Valet driver, but I get "502 bad gateway" response all the time.

The trouble is: I don't know how to troubleshoot my driver at all. Adding `var_dump`s to the driver code changes nothing. There are no error messages in the `valet logs` output either.

Could you give me any hints?

Maybe, I should read the Caddy's logs? Where are they?

**Comment by adamwathan** [comment]
Hey @mityukov, it sounds like PHP FPM isn't actually running at all, hence the bad gateway error.

Try stopping and restarting the services powering Valet:

```
sudo brew services stop php70
sudo brew services start php70
sudo brew services stop nginx
sudo brew services start nginx
```

...and seeing if that helps.

You can verify PHP FPM is running by running:

`ps aux | grep php`

...and checking the output to make sure there's a few php-fpm instances running. If you only get one result (which would be the actual grep process), FPM still isn't starting, at which point you'll want to try and debug that by manually running:

```
/usr/local/opt/php70/sbin/php-fpm --fpm-config /usr/local/etc/php/7.0/php-fpm.conf
```

...and checking the output to see what's happening.

**Comment by mityukov** [comment]
Yes, the issue was not running (for some reason) php70. Now it's restored and lLaravel driver-based links work. But the site, based on my own driver, does not. Now I get "ERR_CONNECTION_REFUSED".

So, the question remains the same: how can I troubleshoot/debug my driver? There must be more verbose error message somewhere (well, I really hope so!)

**Comment by adamwathan** [comment]
Sounds like maybe dnsmasq is not running now, can you run:

```
sudo brew services stop dnsmasq
sudo brew services start dnsmasq
sudo brew services stop php70
sudo brew services start php70
sudo brew services stop nginx
sudo brew services start nginx
```

...and see if that helps? `valet restart` should do all of that but if you're not on `dev-master` there might be some issues; a recent macOS update caused some issues with Homebrew that took a while for them to fix.

**Comment by mityukov** [comment]
I have only `dnsmasq`, `php70` and `mysql`; no `nginx`. From what I understand, Valet comes with Caddy embedded?

The question is still the same, anyway: where to get more details (error messages, etc.) if something doesn't work on Valet my custom driver? Is there standard error logs location?

**Comment by ruchern** [comment]
@mityukov `nginx` seems to be a requirement to run Valet.

**Comment by drbyte** [comment]
Valet 2 uses nginx.   (Old version 1 used Caddy).

Nginx logs are in ~/.valet/Log/  (ref: https://github.com/laravel/valet/blob/master/cli/stubs/valet.conf#L20 )

**Comment by Daikazu** [comment]
@mityukov  simply placing a `die()` after your `var_dump()` will allow it output to the browser.
