### ISSUE TITLE
valet links error expecting Valet\string

### ISSUE THREAD

**Issue by gooddadmike** [laravel/valet#347]
Hello people. I came here seeking help with a valet bug. Not sure what I did but I get this when I run `valet links`
```
PHP Catchable fatal error:  Argument 1 passed to Valet\Site::getCertificates() must be an instance of Valet\string, string given, called in /Users/msearcy/.composer/vendor/laravel/valet/cli/Valet/Site.php on line 72 and defined in /Users/msearcy/.composer/vendor/laravel/valet/cli/Valet/Site.php on line 83
```

Nt sure what I did to get this.

**Comment by adamwathan** [comment]
Sounds like you are using PHP 5. I'm going to remove those type hints
anyways tomorrow though, I must've mistakenly let those slip by in a PR 😕

**Comment by adamwathan** [comment]
Fixed on `master` 👍🏻

**Comment by gooddadmike** [comment]
It worked. Thanks! I had to install with 
`composer global require laravel/valet dev-master#4743c118d68941cedd0d89b46039823ea5a76d99`
I had never done that before. Had to do some googl'in for it. I did find something else though. I'll open another ticket.

**Comment by mitoop** [comment]
`composer global require laravel/valet dev-master#4743c118d68941cedd0d89b46039823ea5a76d99` It works.  I use PHP5.6 in an old project and meet the same question.

**Comment by Rozkalns** [comment]
@mitoop Yes, it is not in
