### ISSUE TITLE
How to enable access logs for nginx

### ISSUE THREAD

**Issue by abishekrsrikaanth** [laravel/valet#351]
Is there a command or config file that needs to be updated to enable access logs on nginx?

**Comment by marconett** [comment]
On macOS, just add a path to the `access_log` directive in `/usr/local/etc/nginx/valet/valet.conf`.

**Comment by drbyte** [comment]
I think this can be closed.

If #548 is updated and merged then it will provide a mechanism for this. I'm not sure this needs to remain open for it though.

**Comment by Stetzon** [comment]
`/usr/local/etc/nginx` path does not exist for my default installation (valet 4.7.1, MacOS 14.5 Sonoma), I was able to find the configuration to enable access logs in `/opt/homebrew/etc/nginx/valet/valet.conf`
