### ISSUE TITLE
Bug/Undocumented requirement - Using valet without sudo

### ISSUE THREAD

**Issue by OwenMelbz** [laravel/valet#352]
Hey,

We've started to look at using Valet for our teams machine - however none of the machines have root/sudo access.

From looking through Valet it seems it runs many of the brew commands etc as sudo (and hides the brew warnings) - which is causing us the inability to use it.

Can you recommend (by not suggesting giving sudo) a way we could go about using Valet without it? Or would there be a potential patch in the future which will allow this?

Thanks

**Comment by adamwathan** [comment]
Dnsmasq and nginx both require being run as root to be able to listen on
port 80 sadly. Maybe we will support listening on other ports eventually
but it's not in the cards for the near future.

**Comment by OwenMelbz** [comment]
Is a shame, but food for thought, you could consider dropping the dnsmasq services inside `/Library/LaunchDaemons` to get it to run as root, then map nginx to port 8080 and 8443

Then can use use another launch daemon to run something like `rdr pass proto tcp from any to any port {80,8080} -> 127.0.0.1 port 8080`

This would map the 80 port to the nginx server listing on 8080 - that way you dont need sudo to run the nginx listener as the port is outside of the reserved range for sudo.

This means that you can then run php as the current users, which will allow them to swap between versions of php as well, would be helpful for large agencies, as we have to actively support websites running on 7.1, 7.0, 5.6 and 5.4

Heres a little run down of what I guess would be needed https://github.com/laravel/valet/compare/master...OwenMelbz:master

**Comment by Flimm** [comment]
Have a look at running `valet trust`
