### ISSUE TITLE
Is there a way to get rid of file extensions using Valet?

### ISSUE THREAD

**Issue by corysimmons** [laravel/valet#355]
Do I just tweak my php.ini to multiviews (or whatever it's called)? Sorry for the dumb question.

**Comment by morloderex** [comment]
Can you clarify your question?

**Comment by corysimmons** [comment]
Nevermind, it's a dumb question. I was asking about vanilla php files `.php` showing their extensions.

Valet just seems to do whatever php.ini is set to.
