### ISSUE TITLE
Browser-sync tries to force https connection regardless if secure is set

### ISSUE THREAD

**Issue by riskiii** [laravel/valet#356]
I have been using the dev version that is about a month to six weeks old, and decided to upgrade to production.  It may not be the fault of valet, but now I am not able to  get browser-sync to open http://localhost:3000 like it did before, it always tries to open https.  Could this be dnsmasq?

**Comment by adamwathan** [comment]
Hmm it might be the browser caching a redirect. If you type that URL manually does it try to redirect to HTTPS or no?

**Comment by ruchern** [comment]
Clear your browser cache and it should be back to non-secure urls.
