### ISSUE TITLE
Unable to use WordPress REST API with Valet

### ISSUE THREAD

**Issue by micheleivani** [laravel/valet#357]
I'm developing a plugin for Wordpress and I need to use WordPress REST api but they do not work. I have just tried the basic ones but the site returns the homepage. 
Any idea about that?

**Comment by aaemnnosttv** [comment]
I had this problem too, but the most common cause is that [permalinks are not set](https://github.com/WP-API/WP-API/issues/2561#issuecomment-228753532).

I tried looking for this in the documentation but it is somewhat hidden in the handbook under  [Discovery](https://developer.wordpress.org/rest-api/using-the-rest-api/discovery/#link-header)

> For sites without “pretty permalinks” enabled, /wp-json/ isn’t automatically handled by WordPress. This means that normal/default WordPress permalinks will be used instead. These headers look more like this:  
Link: <http://example.com/?rest_route=/>; rel="https://api.w.org/"

**Comment by micheleivani** [comment]
Thank you 👍
