### ISSUE TITLE
Slower response times in Valet compared to Homestead

### ISSUE THREAD

**Issue by davestewart** [laravel/valet#358]
Hey,

First of all, thanks for a really nice solution. It's amazing how easy Valet is to set up and how quickly you can have a site showing in the browser.

Unfortunately, I seem to be getting noticeably slower response times; over a second per request where under Homestead it might be 200ms or so.

I note that the docs state "blazing fast local development" so I presume this isn't normal?

I'm on OSX Yosemite, running (right now) PHP 5.6, which I note from other issues is supported. I have Apache stopped, Brew was recently updated, and I can't think offhand if I have anything special going on with my setup.

I've also restarted my machine, and run `valet restart`.

Any tips?

Thanks.

**Comment by adamwathan** [comment]
Try `brew install php56-opcache` and see how much of a difference that makes. I'm surprised it's over a second per request though, here's a fresh Laravel app on my machine running PHP 7:

![image](https://cloud.githubusercontent.com/assets/4323180/25253231/0941a090-25ee-11e7-84b2-1c324e2c99eb.png)

**Comment by davestewart** [comment]
Hey Adam,

Thanks for responding, and so quickly!

That's certainly improved things, thanks. I'm down to 500ms or so.

![image](https://cloud.githubusercontent.com/assets/132681/25253490/015f0f86-2619-11e7-9b00-f61e58a40abe.png)

Perhaps I'll jump back into Homestead for a bit (tomorrow, now) and will see if there's a difference.

I guess it's not a Valet issue per-se, so I appreciate you taking the time to help me out with it.

**Comment by davestewart** [comment]
There seems to be a pattern that the first hit for a while will be REALLY slow, like 1.5s. About a third of this seems to be DNS lookup.

It generally comes down to around 500-700ms with repeated hits to the same URL.

My machine is a 13" 2015 MBP.

I've searched for various things on google regarding slow DNS etc, but it starts to get quite technical (networking is a bit out of my experience TBH).

**Comment by davestewart** [comment]
OK, so I've managed to get Valet working as advertised, and very pleased about it too :)

Not sure what did it, could be a combination of any of the below:

- closing the 100+ or so tabs I had open in Chrome
- doing a full shut-down and restart and re-starting Valet
- uninstalling F-Secure, an anti-virus software
- resetting my router

A Laravel demo site is now down to 20-30ms loading, with the occasional 400-500ms spike, normally on a first-load.

I would have liked to have been able to do this more scientifically, but hopefully I'm just an edge case.

Cheers for now,

Dave
