### ISSUE TITLE
Rewrite url

### ISSUE THREAD

**Issue by addorange** [laravel/valet#359]
Hi,

is there any option I can achieve some kind of rewrite like in .htaccess through Valet/Nginx? My goal is to simulate some kind of multisite through one cms installation.

domain1.dev
and
domain2.dev

point to the same folder, but according to the used domain need to be mapped to one or the other, so the cms can serve the right contents.

Maybe I can get some hint how to achieve this, if possible.

Kind regards,

Chris

**Comment by adamwathan** [comment]
To accomplish this you need to link both domains to the same folder like so:

```
cd my-multisite-cms-installation
valet link domain1
valet link domain2
```

Now visiting either `domain1.dev` or `domain2.dev` will point to the same folder.

From there it's up to you to detect the current URL in your CMS code and do whatever you need to do.

**Comment by addorange** [comment]
Oh my,

it's so obvious and I didn't catch that, tried to mess around with the nginx files etc.

Thank you so much
