### ISSUE TITLE
WordPress Multisite Cron jobs

### ISSUE THREAD

**Issue by leaase** [laravel/valet#360]
Hello :)

I have an issue when I try to execute **wp-cron.php** on a site in my multisite. I get a 404 when I visit _https://domain.dev/sitename/wp-cron.php_. It works for _https://domain.dev/wp-cron.php_, but then the site spesific crons won't execute.

I use @clifgriffin custom driver for multisite: https://github.com/Objectivco/WordPressMultisiteSubdirectoryValetDriver

Anyone know how to fix this?

**Comment by clifgriffin** [comment]
@leaase This is definitely not a scenario I've tested. 

It shouldn't be too hard to debug. You can add `var_dump()` and `die()` to the driver to see exactly what's going on. 

If you wouldn't mind creating an issue on our repository, that will help us track this and find a solution (if you don't beat us to it with a PR).

**Comment by leaase** [comment]
Yes, I will create an issue on your repository 👍

**Comment by clifgriffin** [comment]
This is fixed. https://github.com/Objectivco/WordPressMultisiteSubdirectoryValetDriver/issues/2
