### ISSUE TITLE
Chrome 58 - Valet TLS certs no longer valid

### ISSUE THREAD

**Issue by bbashy** [laravel/valet#362]
*Google Chrome* 58.0.3029.81 (Official Build) (64-bit)

The Valet TLS certs are no longer working in the above version (58) since this;

> Since version 58, Chrome requires SSL certificates to use SAN (Subject Alternative Name) instead of the popular Common Name (CN), thus CN support has been removed.
If you're using self signed certificates (but not only!) having only CN defined, you get an error like this when calling a website using the self signed certificate:

Ref: https://alexanderzeitler.com/articles/Fixing-Chrome-missing_subjectAltName-selfsigned-cert-openssl/

![](https://d.pr/i/CGX6N/3M8pueZq.jpg)

**Comment by joshmanders** [comment]
What version of Valet are you using?

**Comment by joshmanders** [comment]
Make sure you're using latest Valet, then unsecure and resecure your site. My PR to add wildcard SSL support uses SAN and my site works fine in Chrome 58.

**Comment by adamwathan** [comment]
Probably want to be on dev-master not a tagged version.

**Comment by bbashy** [comment]
@joshmanders Appears it did need a restart and resecure. Thanks for the sanity check.

@adamwathan Seems to be working now after restarting valet and resecuring sites. Using 2.0.4

**Comment by SteveEdson** [comment]
Is it possible to backport this to Valet 1? I've been having issues using v2

**Comment by joshmanders** [comment]
What kind of issues, @SteveEdson
