### ISSUE TITLE
tap method conflict

### ISSUE THREAD

**Issue by Jmrich** [laravel/valet#363]
Ran into an issue with the `tap` function within valet and the `tap` function in laravel 5.4. 
5.4 added high order functions to `tap`. Running phpunit will cause this error to be thrown:
```
Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 2 passed to tap() must be callable, none given, called in /Projects/cms/app/Http/Controllers/Events/EventsController.php on line 76

/.composer/vendor/laravel/valet/cli/includes/helpers.php:143
```
since it is expecting `tap` to have a different signature.

**Comment by adamwathan** [comment]
Globally installed composer packages always conflict unfortunately, just the nature of how composer handles global dependencies.

I recommend using this tool to manage globally installed composer dependencies instead:

https://github.com/consolidation/cgr
