### ISSUE TITLE
Valet directory appears in URL (CakeValetDriver)

### ISSUE THREAD

**Issue by steffenbrand** [laravel/valet#368]
What my URLs are being rewritten to:
http://dmn-analyser.dev/Users/steffen/.composer/vendor/laravel/valet/users/login

What I expected:
http://dmn-analyser.dev/users/login

The problem also occurs on a fresh CakePHP (3.4) installation. F.e. with static resources:
... href="/Users/steffen/.composer/vendor/laravel/valet/webroot/css/base.css" ...

- I'm using the default CakeValetDriver without modifications.
- Other drivers are working correctly.
- I'm on the latest valet version.
- I'm using PHP 7.0
- I'm using a Mac.
- The applications seems to be configured correctly.

Anyone with the same problem and/or a solution or idea?

**Comment by Luceos** [comment]
Having the same issue. Static files also return a 404, but only arbitrarily. Tried debugging but no luck so far.

**Comment by steffenbrand** [comment]
Adding the following line to CakeValetDriver in method frontControllerPath works for me:
`$_SERVER['PHP_SELF'] = $_SERVER['HTTP_HOST'];`

@Luceos and @ergineker: If one of you could verify it works, I will provide a pull request.

**Comment by Luceos** [comment]
Yes that works!

**Comment by steffenbrand** [comment]
Okay, after reading the documentation and some debugging, I think I found every $_SERVER variable CakePHP 3 needs and came to this solution:

    public function frontControllerPath($sitePath, $siteName, $uri)
    {
        $_SERVER['DOCUMENT_ROOT'] = $sitePath.'/webroot';
        $_SERVER['SCRIPT_FILENAME'] = $sitePath.'/webroot/index.php';
        $_SERVER['SCRIPT_NAME'] = '/index.php';
        $_SERVER['PHP_SELF'] = '/index.php';

        return $sitePath.'/webroot/index.php';
    }

I will provide a PR.

**Comment by ruchern** [comment]
I don't understand this.

You are using CakePHP Framework but using **Laravel Valet**?

**Comment by steffenbrand** [comment]
@ruchern: Yes, I think that's the concept behind Valet and its various drivers.
When there is a driver for your framework/application, you can run it on Valet.
And you can add your own drivers.

From the Documentation:

> Out of the box, Valet support includes, but is not limited to:
> 
> - Laravel
> - Lumen
> - Symfony
> - Zend
> - CakePHP 3
> - WordPress
> - Bedrock
> - Craft
> - Statamic
> - Jigsaw
> - Static HTML
> 
> However, you may extend Valet with your own custom drivers.

https://laravel.com/docs/5.4/valet

**Comment by ruchern** [comment]
@steffenbrand  Oh I see. I actually never thought of that.

**Comment by Gynidark** [comment]
@steffenbrand Thank you ! 💯

**Comment by steffenbrand** [comment]
You're welcome. Unfortunately I don't think my PR is going to be merged.Even if the documentation lists CakePHP as supported and it's broken without it.

**Comment by steffenbrand** [comment]
Fixed with https://github.com/laravel/valet/releases/tag/v2.0.5
