### ISSUE TITLE
openssl issue since Chrome 58+

### ISSUE THREAD

**Issue by sebszocinski** [laravel/valet#369]
Just updated Chrome and found my valet secure sites were showing ssl errors (missing_subjectAltName), did some googling and found this: https://alexanderzeitler.com/articles/Fixing-Chrome-missing_subjectAltName-selfsigned-cert-openssl/

**Comment by rockethouse** [comment]
EDIT: Okay I just upgraded Valet and I think it's fixed it? but i'll wait for confirmation.

**Comment by ChrisReid** [comment]
Upgrading valet to v2.0.4 fixed it for me 👍

**Comment by joshmanders** [comment]
@rockethouse yes upgrade to latest and resecure your site. My PR for wildcard ssl certs uses san which fixes this issue.

**Comment by carlalexander** [comment]
Upgraded valet, unsecured then resecured my site and restarted valet. It fixed the old SSL error, but I get a `ERR_CERT_AUTHORITY_INVALID` error still.

**Comment by carlalexander** [comment]
This started working for me again a few weeks ago. I guess maybe a chrome update fixed it.
