### ISSUE TITLE
'valet links' is not working.

### ISSUE THREAD

**Issue by sdavara** [laravel/valet#373]
I'm on mac Yosemite(10.10). I've installed latest Valet 2.0.4
When I try to list all linked application folder, it gives me below error:

```
                                      
  [BadMethodCallException]            
  Method mapWithKeys does not exist.  
                                      

links


```
Let me know, if anyone is experiencing the same or any solution.

**Comment by adamwathan** [comment]
Sounds like your global dependencies are out of date in some way.

Try:

```
cd ~/.composer
rm -rf vendor
composer global update
```

**Comment by sdavara** [comment]
Yes. It worked.
Thanks @adamwathan
