### ISSUE TITLE
is there a way to disable automatic wildcard ssl and the www. that gets added everywhere?

### ISSUE THREAD

**Issue by vesper8** [laravel/valet#383]
I know that some people find this a convenience but I do not, in fact it just caused me a lot of grief as I tried to understand why redirects were still happening on my subdomain.domain.dev until I realize that I also had the domain.dev linked and secured which caused all my subdomain configs to be basically ignored as it was treating them as wildcards from the domain.dev

also whenever I link a new subdomain.domain it adds www.subdomain.domain.dev

it adds www. everywhere. Even if I add a www.domain and secure it, it will create www.www.domain.dev.. this one doesn't really affect anything but I find it annoying

Can we override this valet functionality somewhere? Where are the nginx configuration templates (when using valet secure) stored and is there a mechanism for overriding them without modifying the core composer files?

**Comment by vesper8** [comment]
ok so I found the stub file https://github.com/laravel/valet/blob/master/cli/stubs/secure.valet.conf

it would be very nice if there was a mechanism for looking for those stubs in the .valet folder first, and if they don't exist then load them from the usual location, thus allowing us to override them. I would be removing the wildcard directive as well as adding some CORS stuff

I guess for now I can add a symlink inside the composer folder so my stubs are safe from future valet updates

**Comment by drbyte** [comment]
@vesper8 is this still an issue with the last Valet release? 

I can't seem to duplicate it, or maybe I'm not understanding what you're saying.

**Comment by drbyte** [comment]
@mattstauffer I think this can be closed.

**Comment by ChristianGerdes** [comment]
Any progress on how to disable wildcard subdomains?
