### ISSUE TITLE
Unable to make Grav CMS works with Valet

### ISSUE THREAD

**Issue by blackyzero** [laravel/valet#384]
Dear everyone,

I tried to make Valet work with Grav, but still get problem with creation driver for Grav.
Anyone please share your idea.

Thanks a lot.

**Comment by adamwathan** [comment]
Closing this as it's not an issue with Valet itself. I don't personally have time to try and set up a Grav instance and work on a driver for it and we don't have plans to add one to core.

If you can provide more info about what you've tried and what the errors are, I can try my best to provide suggestions in this thread.

**Comment by heihachi88** [comment]
What errors it throws?
