### ISSUE TITLE
It it necessary to run all services as root?

### ISSUE THREAD

**Issue by skovmand** [laravel/valet#386]
Hi.

Thanks for your work on valet. I appreciate it a lot!

I see that all services (nginx, dnsmasq, php-fpm) are started as `sudo brew services start x`, which means that they will be launched with root privileges. The question is of course if they later will fork to another process, as e.g. `www-data` or something similar.

However, is it necessary to run the services as root? 
Could some of them have lower privileges?

Thanks.

**Comment by adamwathan** [comment]
nginx needs to run as root to access port 80 and dnsmasq needs to run as root as well.

The php-fpm might be able to run as another user, I can explore that. The actual fpm processes don't run as root though, just as your actual user account so any files your application writes while you are developing are written with the same permissions and ownership as the other files in your project 👍

**Comment by adamwathan** [comment]
Closing this for now, it seems like it might be possible to run the initial PHP FPM process as the current user but none of the actual FPM processes run as root anyways, and the other services do have to run as root. Can explore further if this actually has any real consequences.
