### ISSUE TITLE
Adding a Certificate Authority to the created certificates

### ISSUE THREAD

**Issue by lucadegasperi** [laravel/valet#390]
Hello, for iOS development the certificates generated by valet aren't valid. simply adding the certificate to the trusted ones doesn't work. It's required that the certificate is signed by a Certificate Authority whose root certificate is installed on your device.

Now, how would one proceed in Valet to sign the certificates with their own CA ?

Here's the apple technical note where I gathered this information from: https://developer.apple.com/library/content/qa/qa1948/_index.html

**Comment by adamwathan** [comment]
Not sure honestly, here's the relevant code though:

https://github.com/laravel/valet/blob/master/cli/Valet/Site.php#L181-L304

If you can figure out how those openssl and add-trusted-cert calls would need to be configurable to support it, we can definitely see about getting that supported.

**Comment by lucadegasperi** [comment]
@adamwathan I got at that point as well, but I have no knowledge on how openssl works and how a certificate should be signed by a CA instead of it being self-signed.

**Comment by joshmanders** [comment]
This is something I had been thinking about for a while along with dynamically generating certificates so all urls are secure by default, which [`puma-dev`](https://github.com/puma/puma-dev) but I don't know enough about Go yet to be able to reverse engineer and abstract it out into Valet.

**Comment by aaemnnosttv** [comment]
I just ran into this when trying to test with the iOS simulator. This article looks to have everything we need: https://deliciousbrains.com/ssl-certificate-authority-for-local-https-development/

It outlines how to create a root CA certificate, and how to create site certificates which are signed by that including all the necessary `openssl` commands. This should also solve the problems with other browsers that don't think Valet's trusted certs are good enough, like Firefox (#296).

I'd love to contribute a PR, but if someone gets to it before me, have at it!

**Comment by drbyte** [comment]
Done.
