### ISSUE TITLE
Valet forget isn't working properly for user relative paths

### ISSUE THREAD

**Issue by codeams** [laravel/valet#394]
If you're in your sites directory `~/Sites` and run `valet park` and `valet forget` the path isn't removed from Valet's paths. At least it didn't work for me in Mac OS Sierra.

Running `valet forget /Users/codeams/.valet/Sites` did the trick, but I think this isn't the desired behavior.

**Comment by adamwathan** [comment]
`~/.valet/Sites` does not need to be parked, it is meant to be permanently available. Whenever you run `valet link`, we link those to that `Sites` directory, so removing the sites directory effectively breaks that functionality.

If you parked it by mistake and were trying to undo that change, then forgetting it explicitly is probably the right solution. We might want to make it impossible to park that directory manually.
