### ISSUE TITLE
Adding datetime to HTTP requests log in valet serve

### ISSUE THREAD

**Issue by jeffreyvanhees** [laravel/valet#395]
Hi,

Is it possible to add date and time to the HTTP-request log in the terminal in the `valet share` command? This makes clearer distinction possible between different requests.

**Comment by drbyte** [comment]
I don't think so.

But if you use the other URL provided by ngrok (127.0.0.1:4040) to view all those requests in your browser, you can see timestamps and lots more.

**Comment by drbyte** [comment]
@mattstauffer IMO this can be closed. It's ngrok, not Valet.
