### ISSUE TITLE
When I set the app-name to "blog", I received ERR_EMPTY_RESPONSE

### ISSUE THREAD

**Issue by fangd123** [laravel/valet#398]
I just want to know why this happened, and if I set the app-name to others, I can access the website normally.

**Comment by fangd123** [comment]
I look up the log of `dnsmasq`, it didn't have the query of `blog.dev`, and the browser's cache has been cleared.

**Comment by heshiweij** [comment]
+1 ,me too ...

**Comment by heshiweij** [comment]
so am i

**Comment by mattstauffer** [comment]
@fangd123 @heshiweij Is this still a problem for either of you?

**Comment by drbyte** [comment]
@mattstauffer IMO this can be closed.
