### ISSUE TITLE
How to retrieve the valet url by command or script

### ISSUE THREAD

**Issue by jeystaats** [laravel/valet#404]
At the moment I would love to retrieve the $ valet share url when I run the command in the terminal without manually copying the ngrok.io url. 

Is there a way to retrieve this url by script or something?

**Comment by adamwathan** [comment]
When you run `valet share`, the URL is already automatically copied to your clipboard. Just need to `cmd+v` after sharing has finished booting up and you can paste it wherever you want.

**Comment by jeystaats** [comment]
Cheers, although I don't mean to use it manually with cmd+v or anything else. 
I would like to scrape or retrieve the ngrok url from a file so I can use it in a bash command.

Atm the valet share does make it go into your clipboard. But I'm trying to copy and paste it into my .env automatically with a bash script. Thats why I would like to retrieve to URL :)

**Comment by adamwathan** [comment]
We have a sort of internal command called `valet fetch-share-url` which will get the URL of the current site being shared through ngrok. It won't work as expected if you are sharing multiple sites at once, but if you are only sharing one at a time it should give you what you need.

**Comment by jeystaats** [comment]
Yes! Thats precisely what I need. Thanks @adamwathan . Issue closed.
