### ISSUE TITLE
wordpress redirect loop on /wp-admin/install.php when using custom folder structure

### ISSUE THREAD

**Issue by vesper8** [laravel/valet#406]
I always install Wordpress in a /public/ folder similar to Laravel.

I would get into a redirect loop when trying to run a fresh install. I looked at the Wordpress driver and it seems to me like the frontControllerPath only works when you're trying to hit the index.php but it has no logic to handle the install.php? Am I missing something or is this an oversight?

After reading other posts about this, I updated from 2.0.4 to dev-master, then created the custom driver below which is identical to the stock wordpress driver except this one takes the '/public' driver into account.

All is working fine now

```
<?php

class WordPressPublicValetDriver extends BasicValetDriver
{
    /**
     * Determine if the driver serves the request.
     *
     * @param  string  $sitePath
     * @param  string  $siteName
     * @param  string  $uri
     * @return bool
     */
    public function serves($sitePath, $siteName, $uri)
    {
        return file_exists($sitePath.'/public/wp-config.php') || file_exists($sitePath.'/public/wp-config-sample.php');
    }

    /**
     * Get the fully resolved path to the application's front controller.
     *
     * @param  string  $sitePath
     * @param  string  $siteName
     * @param  string  $uri
     * @return string
     */
    public function frontControllerPath($sitePath, $siteName, $uri)
    {
        $_SERVER['PHP_SELF']    = $uri;
        $_SERVER['SERVER_ADDR'] = '127.0.0.1';
        $_SERVER['SERVER_NAME'] = $_SERVER['HTTP_HOST'];

        return parent::frontControllerPath(
            $sitePath . '/public', $siteName, $this->forceTrailingSlash($uri)
        );
    }

    /**
     * Redirect to uri with trailing slash.
     *
     * @param  string $uri
     * @return string
     */
    private function forceTrailingSlash($uri)
    {
        if (substr($uri, -1 * strlen('/wp-admin')) == '/wp-admin') {
            header('Location: '.$uri.'/'); die;
        }

        return $uri;
    }
}
```

**Comment by adamwathan** [comment]
When I try to create a fresh Wordpress project with Valet, the first thing I see when I visit `wordpress.dev` is this install screen. Is that not happening for you?

![image](https://user-images.githubusercontent.com/4323180/28719653-baa9f292-7378-11e7-8f34-c8ab79177ca1.png)

**Comment by adamwathan** [comment]
Ah just saw now that you are using a `public` folder inside of the project folder. If you are customizing the folder structure, then it's best to use a custom driver for your project.

**Comment by mmeester** [comment]
I'm having a similar issue, all works with the driver above but wp-admin redirects to home and wp-admin only works when using the full path of the php file

**Comment by schellenbergk** [comment]
I faced the same redirect issue with `/wp-admin/install.php`.  The problem in my case was the `~/.config/valet/Drivers/SampleValetDriver.php` that was causing it.   I found the issue by running `valet which` command which revealed that it was using the `SampleValetDriver'.  To fix it I've deleted it and Valet automatically switched to built-in Wordpress Driver.  Boomshakalaka! :)
