### ISSUE TITLE
Questionmarks in response from valet

### ISSUE THREAD

**Issue by Kwickell** [laravel/valet#407]
Since some time ago valet has started "randomly" returning questionmarks (?) instead of the proper response from my sites.

The only source on the pages are like or similar to this.

`??????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????`

I have no clue as to what caused it to start behaving this way and once it has started it seems not to vary between different sites. 

Restarting valet with "valet restart" seems to fix it temporarily.

Has anyone seen something like this before?

**Comment by drbyte** [comment]
I don't believe this to be an issue with valet. Perhaps with some homebrew packages, but not valet itself.

I think this can be closed due to inactivity.
