### ISSUE TITLE
Valet Secure & Valet Share having issues

### ISSUE THREAD

**Issue by lokisource** [laravel/valet#409]
Hello,

For the development of an embedded Shopify app I have been using Valet with success for the past two weeks. As part of the on boarding process a new coworker needs to work on the same project, using the same repository, but publishing it to a separate ngrok url. Shopify requires all embedded apps to be on SSL.

We keep running into an 302: too many redirects response on his machine, both with a copy of the project and with a site consisting of just and index.php echoing phpinfo(). 

Both machines are running Sierra 10.12.6 and Valet dev-master, although we did run in the same issue when using the default.

Any help would be greatly appreciated. If I need to supply more info, please let me know.

**Comment by adamwathan** [comment]
Valet secure does not work with valet share, you need a paid ngrok account
to use SSL ngrok tunnels. Best to pay for an ngrok account and use ngrok
directly in that case.
