### ISSUE TITLE
$_SERVER['SERVER_NAME'] is empty in v2.0.5

### ISSUE THREAD

**Issue by mdurao** [laravel/valet#411]
Has the title says, $_SERVER['SERVER_NAME'] is empty is not set in valet 2.0.5.

**Comment by adamwathan** [comment]
Just compared v2.0.4 and v2.0.5 and nothing has changed regarding which drivers have `SERVER_NAME` set and which don't. What sort of project are you serving?

**Comment by mdurao** [comment]
Hi Adam, i'm trying to debug an old Code Ignitor project.
When I "die and dump" the $_SERVER, SERVER_NAME is empty.
I'm going to check the behaviour in a laravel project and report back.
Thank you.

**Comment by adamwathan** [comment]
Cool! What were you getting on Valet v2.0.4? Was it displaying it then and now it's not, or do you think this has been an issue forever?

**Comment by mdurao** [comment]
In a laravel project, editing `public/index.php` and inserting this after `<?php` tag:
```
echo "<pre>"; print_r($_SERVER); die();
```
It will dump:
```
    ...
    [HTTP_HOST] => test.dev
    [REDIRECT_STATUS] => 200
    [SERVER_NAME] => 
    [SERVER_PORT] => 80
    [SERVER_ADDR] => 127.0.0.1
    ...
```

I'm going to check the nginx configs in valet to see if there is something missing...
In apache, usually, this var is setted by ServerName (and probably ServerAlias).

I'll keep in touch

**Comment by adamwathan** [comment]
What should the value be set to?

**Comment by mdurao** [comment]
In a Forge deploy, for example, it will be set to the subdomain/domain of the project.

IE: `[SERVER_NAME] => test.mydomain.com`

**Comment by mdurao** [comment]
Ok, checking the differences, I'm not sure if it's possible to fix this in Valet.

Basically, in the **server** directive of **nginx** config, you need to have `server_name project.dev;`

Is there anyway of getting the `anything.dev`and set the **server_name** var in **nginx**?

**Comment by mdurao** [comment]
If the site is *secured* with `valet secure`, the `$_SERVER['SERVER_NAME']` is set OK!

**Comment by joshmanders** [comment]
It doesn't set it because the `server_name` directive was not set in the nginx config[[0]](https://github.com/laravel/valet/blob/master/cli/stubs/valet.conf) file because of how valet handles routing all requests. When you run `valet secure` it generates an actual config file for that domain, which has the `server_name` directive set[[1]](https://github.com/laravel/valet/blob/master/cli/stubs/secure.valet.conf).

**Comment by adamwathan** [comment]
Yeah this is typically done per driver:

https://github.com/laravel/valet/blob/master/cli/drivers/KirbyValetDriver.php#L46

...but it's probably not unreasonable to do this globally and allow a driver to override if needed.

**Comment by adamwathan** [comment]
@mdurao The reason it works for secure sites is because each secured site gets its own nginx config file to use the right certificate. We can't create per-site nginx configs for unsecured sites because things would get too static and rigid that way, we couldn't do the awesome dynamic stuff we do with directory parking if we always needed a static list of active projects.

**Comment by mdurao** [comment]
Thank you @adamwathan and @joshmanders.
The parking is the best feature indeed of Valet.
It's good enough for me, if I need to access that kind of Info, to secure a site and play around the config file.
Closing this issue!

**Comment by joshmanders** [comment]
I’d love to see Valet go to a secure by default setup. It’s always good to have dev be as close to prod as possible, and it’s best to have ssl on prod. :)

**Comment by nbyloff** [comment]
This is happening to me all of a sudden on v3.3.0. Been using this install for months and I thought upgrading to 3.3.0 from 3.2.2 would fix it. SERVER_NAME is empty. If I use a secure valet site, SERVER_NAME shows up but xdebug won't work.

**Comment by mattstauffer** [comment]
@nbyloff Could you create a new issue with a minimum reproducible case, including what driver the site is being served by? I can't reproduce and would rather move that conversation outside of this one.

**Comment by nbyloff** [comment]
@mattstauffer I will try with a fresh install but I am confused on how it started happening in the first place. If I can reproduce it, I'll open an issue.
