### ISSUE TITLE
valet stopped working: dial tcp: lookup blog_test.kasper on 62.58.48.10:53: no such host

### ISSUE THREAD

**Issue by kasperpeulen** [laravel/valet#413]
For some reason valet stopped working for me, I tried to reinstall everything and install everything from scratch.

I currently get this error:

![image](https://user-images.githubusercontent.com/1035299/28926398-f6532f2c-7867-11e7-9b14-92701d21010b.png)

Any ideas what is going on?

**Comment by drbyte** [comment]
`brew services list` will show what services are running.

Probably an issue with dnsmasq.
Perhaps updating it with brew might be a good first step:
`brew update && brew upgrade` will update all brew apps

I've also posted custom dnsmasq configs here in other issues, which you may find useful.

**Comment by kasperpeulen** [comment]
![image](https://user-images.githubusercontent.com/1035299/28927594-3d323d86-786b-11e7-8b0e-2f9d25052878.png)

I have tried brew update and brew upgrade, and reinstalling all the dependencies, but without success. Do you know how to completely remove valet? It seems like valet is still doing something even if I delete valet completely. For example, it will still respond to pings, even if I delete everything:

![image](https://user-images.githubusercontent.com/1035299/28927700-89e1b09e-786b-11e7-8109-cd45e1471ad0.png)

Any idea how to really uninstall valet, and start from fresh?

**Comment by drbyte** [comment]
Here are a couple issues that discuss aggressive uninstall actions, found by searching this repo for "uninstall":

https://github.com/laravel/valet/issues/329
https://github.com/laravel/valet/issues/341

**Comment by kasperpeulen** [comment]
Is it interesting that my nginx log dates from may?

```
==> /usr/local/var/log/nginx/access.log <==
127.0.0.1 - - [03/May/2017:23:05:42 +0200] "GET / HTTP/1.1" 301 185 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.81 Safari/537.36"
127.0.0.1 - - [03/May/2017:23:12:52 +0200] "GET / HTTP/1.1" 301 185 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3087.0 Safari/537.36"
127.0.0.1 - - [09/May/2017:11:43:29 +0200] "GET / HTTP/1.1" 301 185 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.96 Safari/537.36"
127.0.0.1 - - [09/May/2017:14:06:42 +0200] "GET / HTTP/1.1" 301 185 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/603.1.30 (KHTML, like Gecko) Version/10.1 Safari/603.1.30"
127.0.0.1 - - [11/May/2017:17:58:04 +0200] "GET / HTTP/1.1" 301 185 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36"
127.0.0.1 - - [11/May/2017:19:19:01 +0200] "GET / HTTP/1.1" 301 185 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3096.0 Safari/537.36"
127.0.0.1 - - [11/May/2017:19:52:03 +0200] "GET / HTTP/1.1" 301 185 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3096.0 Safari/537.36"
127.0.0.1 - - [11/May/2017:20:06:20 +0200] "GET / HTTP/1.1" 301 185 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36"
127.0.0.1 - - [12/May/2017:18:02:54 +0200] "GET / HTTP/1.1" 301 185 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36"
127.0.0.1 - - [19/May/2017:12:13:53 +0200] "GET / HTTP/1.1" 301 185 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3103.0 Safari/537.36"
```

**Comment by drbyte** [comment]
The launchDaemon should have been removed automatically when running `valet stop` and `valet uninstall`.

The composer cache is normal. safe to delete
The `etc` stuff is fine.  safe to delete

But ... when was your last reboot?

**Comment by kasperpeulen** [comment]
Okay, I deleted everything. And rebooted my pc. I found out that website.kasper actually gives Unknown: host after some time. But other webiste give Unknown: host immediately. I still have that website 127.0.53.53 responds to website.*dev*

![image](https://user-images.githubusercontent.com/1035299/28932474-dff0525c-7879-11e7-8384-d2806bc29e30.png)

So I guess there is still something of valet's installation that does this?

**Comment by drbyte** [comment]
Without dnsmasq, ALL *.dev will send to 127.0.53.53. That's a natural catch-all in the DNS world. 

So, that's normal.

**Comment by kasperpeulen** [comment]
Ah, I see. After this last update, and reinstalling everything from brew and composer, all works :D :D 💃 .

Thanks for the help. So what I did to get it to work, is deleting everyting per #341. Deleting all the other files that contained valet in the name as well. Rebooting. And installing everything from scratch again.

**Comment by drbyte** [comment]
My guess is that a reboot would have been enough.  But you've learned a lot from the investigation at least! :)

Ironically, all I had to do for the recent Valet update was simply 
`brew update && brew upgrade && brew cleanup`

Immediately the new valet was working, all sites active, all dns working normally.
