### ISSUE TITLE
Stripe says API request is made with TLS 1.0

### ISSUE THREAD

**Issue by manogi** [laravel/valet#418]
Hi there, running Valet on macOS 10.12.6: When I test my E-Shop and I am sending a credit card payment to the Stripe test API I get the error message "Stripe no longer supports API requests made with TLS 1.0... (see screenshot).
I secured the site with valet secure and it works fine under https in Chrome (only the Stripe call does not work). Funnily when I check the TLS Version in Firefox (don't know how to do that in Chrome) it says the version IS TLS 1.2... (seen screen2.png).

Can I update the script that makes the certificates somehow? Is this an issue of my OS or is it Valet?

Thanks for any hints!

![screen](https://user-images.githubusercontent.com/1419634/29271011-af06984e-80f9-11e7-83f5-92af1fa48272.png)

![screen2](https://user-images.githubusercontent.com/1419634/29271082-148e8e9c-80fa-11e7-89f9-a13533271800.png)

**Comment by clizaola** [comment]
I have the same problem, @manogi were you able to fix it?

**Comment by manogi** [comment]
@clizaola sorry no, I still have that problem locally.

**Comment by adamwathan** [comment]
What happens if you try to hit Stripe using cURL from the CLI on your
machine?

**Comment by clizaola** [comment]
@manogi @adamwathan In my case I was using the stripe/stripe-php library, and actually, I make it work, the only thing is I don't know exactly what change was the one that solved.

I update the OpenSSL with brew
I secure the website using valet secure
I update the stripe library from 3.1^ to 5.1^ (I am pretty sure this was the solution, apparently that has nothing to do with valet)

**Comment by adamwathan** [comment]
Yeah I really don't expect this is a Valet issue since Valet isn't really in control of how outgoing HTTP requests are made. Going to close this under that assumption for now.

**Comment by tommytompkins** [comment]
I'm having this same exact issue using Valet and Laravel 5.2 but everything works fine when deployed to Digital Ocean via Forge. @adamwathan Do you have any idea how I can get this to work with Valet?  All Stripe API calls result in the following error only when using Valet:

```
Authentication in ApiRequestor.php line 110:
Stripe no longer supports API requests made with TLS 1.0. Please initiate HTTPS connections with TLS 1.2 or later. You can learn more about this at https://stripe.com/blog/upgrading-tls.
```

**Comment by tommytompkins** [comment]
If anyone else is curious, the fix for this was to upgrade from OSX Sierra (10.12.6) to OSX High Sierra (10.13.3).  I was trying to avoid upgrading OSX since it affects my Parallels installation, but I think it's impossible to upgrade OpenSSL in Sierra without updating the OS.  After upgrading the OS, my Laravel 5.2 install talks to Stripe just fine.

**Comment by manogi** [comment]
Same for me - updated today, the problem was gone.

**Comment by R00118189** [comment]
I think it is cashier dependency (v6) issue with stripe-php on L5.2, when using valet on sierra I substituted vendor/stripe with the latest version to get this working
