### ISSUE TITLE
 Please help:  Valet 2.0 [DomainException] Unable to determine linked PHP. 

### ISSUE THREAD

**Issue by brusselsregular** [laravel/valet#419]
Hi Guys,

I'm trying to install valet 2.0 on mac OS Sierra v 10.12.6, keep getting this error: 

`Stopping nginx....
Installing nginx configuration...
Installing nginx directory...
Updating PHP configuration...

                                   
  **[DomainException]                
  Unable to determine linked PHP.**  
                                   

install`

When I link a site and try to visit it I get: "This site can’t be reached"

**Ping test.dev does respond**

What I tried: 

- reinstall brew 
- reinstall php71 + unlink and relink PHP
- restart brew services
- restart mac
- ~/.composer/vendor/bin  is in PATH

Kind of out of ideas at this point....Anything else I can try?

**Comment by adamwathan** [comment]
Sounds like PHP isn't linked properly! Few questions for you:

If you check `/usr/local/bin`, is there a symlink to a `php` binary in there?

What's the output of `stat -x /usr/local/bin/php`?

What's the output of `readlink /usr/local/bin/php`?

**Comment by brusselsregular** [comment]
Hi, 

Thanks for replying.

I just checked: there is a symlink to a php binary in /bin 

 output of stat -x /usr/local/bin/php: 

 File: "/usr/local/bin/php"
  Size: 32           FileType: Symbolic Link
  Mode: (0755/lrwxr-xr-x)         Uid: (  501/myname)  Gid: (   80/   admin)
Device: 1,4   Inode: 45255109    Links: 1
Access: Tue Aug 15 11:32:47 2017
Modify: Tue Aug 15 11:32:47 2017
Change: Tue Aug 15 11:47:03 2017

output of readlink /usr/local/bin/php: 

../Cellar/php71/7.1.8_20/bin/php

**Comment by adamwathan** [comment]
Hmm interesting. Can you try modifying your local copy of Valet to diagnose which of these two possible errors is being thrown?

https://github.com/laravel/valet/blob/master/cli/Valet/Brew.php#L176-L189

Just change the string in each one of the exceptions so they aren't the same, then let me know which section it's failing in.

One possibility that comes to mind is that another global Composer dependency is declaring the "collect" function, but it's an old version of the `Collection` class in that package and the parameter order to that `first` callback is reversed. I think I would actually bet money on that being the problem 😄

Try running:

```
rm -rf ~/.composer/vendor
rm ~/.composer/composer.lock
composer global update
```

Then rerun `valet install`.

If that still doesn't work, can you share the contents of `~/.composer/composer.json`?

**Comment by brusselsregular** [comment]
@adamwathan You're awesome, this worked: 

rm -rf ~/.composer/vendor
rm ~/.composer/composer.lock
composer global update
Then rerun valet install

Thank a lot for helping me out on this one!

**Comment by adamwathan** [comment]
Awesome! No problem.

**Comment by sebastiandedeyne** [comment]
Just a heads up, I did a `composer global update` today and this issue started popping up (have been using Valet for a while without any problems).

The suggested workaround did the trick though!
