### ISSUE TITLE
linkedPhp() throwing error Unable to determine linked PHP. after change to collections

### ISSUE THREAD

**Issue by tomeh** [laravel/valet#422]
Using tag 2.0.5 I get the following error "Unable to determine linked PHP.". 

If I dump the `$version` variable in the callback [here](https://github.com/laravel/valet/blob/master/cli/Valet/Brew.php#L185) I get:

```
0
1
2
```

I think the culprit is the minimum version in composer.json "tightenco/collect": "^5.2"

In the [tightenco/collect](https://github.com/tightenco/collect) package version - 5.2, the 'first()' method still passes `$key, $value` to the callback rather than the desired `$value, $key`. I suggest bumping the version constraint to ^5.3

#421

Kind regards

**Comment by adamwathan** [comment]
This seems to happen as well if you've got another global package installed like the Laravel installer and it happens to be an old version. Merged your PR though, thanks!

**Comment by tomeh** [comment]
Thanks!

Also, you are correct, I installed the Laravel installer a while back but usually just use composer create-project so it is probably an ancient version of the installer.
