### ISSUE TITLE
Laravel 5.5 not working

### ISSUE THREAD

**Issue by SantiMA10** [laravel/valet#427]
PHP: 7.1
Valet: 2.0.5
Laravel: 5.5.0

Today I installed Laravel 5.5 to made some test with the new version and if I try to access with valet I get this error:
> Parse error: syntax error, unexpected '?' in /Users/xxxx/laravel/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php on line 233

But if I use php artisan serve it works. Any idea? Or Valet is not compatible with Laravel 5.5 yet?

**Comment by adamwathan** [comment]
Whats the code on that line, what's the syntax error? Maybe you saved it by mistake? Has happened to me, heh 😄

It's definitely compatible with 5.5, been using it for a few months now prior to release.

**Comment by SantiMA10** [comment]
The problem is the PHP 7 new operator "??", I have two PHP versions installed and I don't why valet is using the older one(PHP 5.6) and php artisan serve the new one(PHP 7.1).

**Comment by SantiMA10** [comment]
Now working on Laravel 5.5.2
