### ISSUE TITLE
svgz files don't work

### ISSUE THREAD

**Issue by dannyuk1982** [laravel/valet#428]
Any svgz files don't seem to load but give the error 

```
This page contains the following errors:

error on line 1 at column 1: Encoding error
Below is a rendering of the page up to the first error.
```

**Comment by drbyte** [comment]
@dannyuk1982 is this still an issue? (I'm not up on svgz stuff)

If so, then per this article https://trac.nginx.org/nginx/ticket/372 I wonder if simply adding the following to your project's Nginx config (in `~/.config/valet/Nginx/`) may be enough?
`location ~ \.svgz$ { add_header Content-Encoding gzip; }`

**Comment by dannyuk1982** [comment]
Hi, yes it's still an issue and that doesn't work. It weirdly gives a 404 error for the svgz. Safari/Chrome think it is a html file oddly:

<img width="668" alt="Screenshot 2019-12-12 at 14 13 43" src="https://user-images.githubusercontent.com/7669885/70719300-a76b3480-1ce9-11ea-981e-62f5edd6b9a4.png">

<img width="748" alt="Screenshot 2019-12-12 at 14 14 36" src="https://user-images.githubusercontent.com/7669885/70719353-c1a51280-1ce9-11ea-8f60-47eab8221a33.png">


Here is a test html file:

```<html>
<body>
<img src="test.svgz">
<img src="test.svg">
</body>
</html>
```

And the files:
<img width="229" alt="Screenshot 2019-12-12 at 14 12 24" src="https://user-images.githubusercontent.com/7669885/70719202-6f63f180-1ce9-11ea-9dad-93df09d7aaf8.png">

The svg works fine, but not the svgz, here is the snippet of the config file:

```
server {
    listen 127.0.0.1:443 ssl http2;
    server_name testing.test www.testing.test *.testing.test;
    root /;
    charset utf-8;
    client_max_body_size 128M;
    http2_push_preload on;

    location ~ \.svgz$ { add_header Content-Encoding gzip; }

...
```
Also tried 
```location ~ [^/]\.svgz(/|$) {```

**Comment by drbyte** [comment]
Is this truly isolated to Valet? Or do you run into the same problem on other nginx-hosted servers?

Mind posting a link where I can download those test files?

**Comment by dannyuk1982** [comment]
I'm not sure, I only run nginx with valet, could well be an nginx problem though. I've attached the file below:
[testing.zip](https://github.com/laravel/valet/files/3961824/testing.zip)

**Comment by drbyte** [comment]
Curiously, Safari, Firefox, Chrome all show the same results, with both Nginx and Apache:
- both images are sent with content-type of image/svg+xml
- the svg image renders fine
- the svgz image doesn't render. On any of the browsers, regardless of nginx or apache.

I'm not convinced this has anything to do with Valet.

**Comment by dannyuk1982** [comment]
Yea, you're right in that example it doesn't work with Apache either. When I had a live site back in 2017 when I opened this issue, the svgzs I was having trouble with in Valet were working fine in Apache. I am not sure it's worth the energy trying to work out the problem as I don't think I have used svgz since and doesn't seem it's too popular a format anyway.

**Comment by drbyte** [comment]
I tend to agree.

Wanna click the "Close" button below?

**Comment by dannyuk1982** [comment]
Will do!

**Comment by Jylpah** [comment]
Hi, I know this is an old issue, but I think the problem here is the web server "double-compressing" `.svgz` images. Therefore the `Content-Type` HTTP  response header should be `gzip, gzip`. This, however, fails on iOS Safari...

It's a tricky issue since web servers are often configured to compress content based on MIME-type. 

[HOWTO serve SVGZ images on GitHub Pages](https://github.com/Jylpah/svgztest/issues/1)
