### ISSUE TITLE
Valet is displaying filesystem "path to valet" in the browser address bar

### ISSUE THREAD

**Issue by mattyglover** [laravel/valet#430]
This problem happens everytime with this site - I can't work out what is difference about it. However, although the php seems to be running, none of the the CSS or JS file are running due to invalid mime types.

The stragest thing is the address bar - it is showing a file system path to valet!

See https://matt-sparkeleven.tinytake.com/sf/MTkzMTA3NV82MTQ0MTM3

So, I can successfully log into (a Kanboard clone) the app, but the URLS are crazy - they look like this:

http://kanboard.dev/Users/mattyglover/.composer/vendor/laravel/valet/?controller=DashboardController&action=show

The console is filled with these errors: 

- Refused to execute script from '' because its MIME type ('text/html') is not executable, and strict MIME
- Resource interpreted as Stylesheet but transferred with MIME type text/html:

All my other sites are running fine locally (Laravel, Spark and WordPress) so I'm pulling my hair out - any insights???

**Comment by adamwathan** [comment]
What framework are you using for that site?

**Comment by mattyglover** [comment]
https://github.com/kanboard

Looks to be based on Zend/Symphony

Matt

**Comment by mattstauffer** [comment]
@mattyglover I'm going to close this for now because it's been dormant for a while. Sounds like it's specific to Kanboard and/or whatever frameworks it's built on, and it doesn't seem like anyone at Valet has a lot of ideas. Good luck!
