### ISSUE TITLE
Changing .dev TLD references

### ISSUE THREAD

**Issue by inverse** [laravel/valet#431]
Following on from the discussion in: https://github.com/laravel/docs/issues/3526

It might be worth adopting `.localhost` instead of `.dev` TLD since google has registered this.

**Comment by adamwathan** [comment]
Have discussed this in previous issues. It's trivial to change for your own installation and so far there are no real .dev domains, so not going to worry about it until it's actually an issue for people.

**Comment by rdrnnr87** [comment]
I'm getting the following Chrome error on all my Valet served projects using "Canary" Chrome 63.0.3223.0.  "Stable" Chrome 61.0.3163.100 still seems to load .dev TLD fine. I'm not sure how quick their release cycle is but it looks like the change is coming.

> my-domain.dev normally uses encryption to protect your information. When Google Chrome tried to connect to my-domain.dev this time, the website sent back unusual and incorrect credentials. This may happen when an attacker is trying to pretend to be my-domain.dev, or a Wi-Fi sign-in screen has interrupted the connection. Your information is still secure because Google Chrome stopped the connection before any data was exchanged.

> You cannot visit my-domain.dev right now because the website uses HSTS. Network errors and attacks are usually temporary, so this page will probably work later.

**Comment by drbyte** [comment]
Agreed: the change is coming quickly.
Fortunately PR #436 is ready for merge and will change the default for new installations. 

But you don't have to wait for the merge.

Simply run `valet domain test` and then your projects will be served as `*.test` instead of `*.dev`.

(If you don't like `*.test`, several other "safe" options are listed in the dialog in #436 and #434)

**Comment by rdrnnr87** [comment]
Thanks @drbyte!  Just found that in the command list a few minutes ago.  To @adamwathan's point it's super easy to change but could become a stumbling point for new comers with the default installation.

Thanks for ref to the other conversations.  Looks like bases are covered between potential merges on laravel/valet and laravel/docs.

**Comment by PaoloFalomo** [comment]
@adamwathan false. `.dev` is now available (see https://www.onlydomains.com/domains/new/.dev) we should provide a configuration purpose on `valet install` or maybe a default `.loc`

This is not fixed.

**Comment by adamwathan** [comment]
It *is* fixed, Valet uses `.test` by default now:

https://github.com/laravel/valet/pull/436

**Comment by OrbitalStudios** [comment]
There are situations where using the actual domain is imperative (multisite installs with sub-domains). There should be a way to run valet secure "ACTUAL DOMAIN" without this overhead.

**Comment by mattstauffer** [comment]
@OrbitalStudios Your comment isn't particularly clear. Could you create a new issue and try to go into more detail there? Thanks!

**Comment by jylinman** [comment]
Just to let you know, people are starting to use the `.dev` TLD so this is actually very helpful.  For example, when working with Tensorflow it asks you to download something from https://tfhub.dev/google/

**Comment by jacobkenji10** [comment]
https://kr8.opsarang1.com/
Nice page, Preserve the good work. Thank you so much.
