### ISSUE TITLE
built in php 7.1.7 High Sierra GM

### ISSUE THREAD

**Issue by hsleewis** [laravel/valet#442]
macOS High Sierra GM ships with PHP 7.1.7, php 7.1 can't be installed through homebrew.
Is there a way to let Valet use the systems default php version?

**Comment by arthurkirkosa** [comment]
There is PHP 7.1 and 7.2 in homebrew (`homebrew/php/php71`, `homebrew/php/php72`)

**Comment by hsleewis** [comment]
@arthurkirkosa yes, and both can't be installed on macOS High Sierra :)

**Comment by adamwathan** [comment]
Weird, macOS has always shipped with a default version of PHP and has never
been an issue to install the same version via brew as it gets installed in
a totally different place. What error are you seeing?

**Comment by hsleewis** [comment]
> ==> Installing php72 from homebrew/php
> ==> Downloading https://downloads.php.net/~remi/php-7.2.0beta3.tar.bz2
> ######################################################################## 100.0%
> ==> ./configure --prefix=/usr/local/Cellar/php72/7.2.0beta3_5 --localstatedir=/usr/local/var --sysconfdir=/usr/local/etc/php/7.2 --with-config-file-path=/usr/local/etc/php/7.2 --with-config-file-scan-dir=
> Last 15 lines from /Users/hsl/Library/Logs/Homebrew/php72/01.configure:
> checking for Kerberos support... /usr
> checking whether to use system default cipher list instead of hardcoded value... no
> checking for krb5-config... /usr/bin/krb5-config
> checking for RAND_egd... no
> checking for pkg-config... no
> checking for OpenSSL version... >= 1.0.1
> checking for CRYPTO_free in -lcrypto... yes
> checking for SSL_CTX_set_ssl_version in -lssl... yes
> checking for PCRE library to use... bundled
> checking whether to enable PCRE JIT functionality... yes
> checking whether to enable the SQLite3 extension... yes
> checking bundled sqlite3 library... yes
> checking for ZLIB support... yes
> checking if the location of ZLIB install directory is defined... no
> configure: error: Cannot find libz
> 
> Do not report this issue to Homebrew/brew or Homebrew/core!

And it ends with this:

> Error: You are using macOS 10.13.
> We do not provide support for this pre-release version.
> You may encounter build failures or other breakages.
> Please create pull-requests instead of filing issues.

So the most easy would be just using the built in PHP instead of one that was installed by brew.

**Comment by hsleewis** [comment]
Fixed it,.. somehow Xcode alone wasn't enough. I also needed to install the commandline tools to get it working.
