### ISSUE TITLE
Valet 'start' or 'restart' keeps crashing my machine

### ISSUE THREAD

**Issue by gavinhewitt** [laravel/valet#443]
So when I do a valet start or restart, the CLI says 'Restarting' and then my machine shows a spinner and reboots. I have tried Googling but that did not return any results so I'm guessing it's not a common problem. Anyone got an idea?

I'm on El Capitan.

**Comment by drbyte** [comment]
Not common.
Here's a bunch of questions that might help us help you:

When you go to CLI and type `brew services list` what does it report?

How long have you been using Valet?

When did this problem start?

How long have you been using Homebrew?

Do you have other webserver tools running on your machine? Pre-existing Apache or Nginx or Lightspeed or anything else?

Any other DNS tools installed that might conflict with dnsmasq?

**Comment by gavinhewitt** [comment]
Thanks for your reply, but after some more investigating it does not seem to be Valet related but (possibly) homebrew. Closing this issue.

Thanks
