### ISSUE TITLE
Move ~/.valet to ~/.config/valet

### ISSUE THREAD

**Issue by eberkund** [laravel/valet#447]
It would be really nice if Valet were to move the default installation path from `~/.valet` to `~/.config/valet` to conform to https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

A lot of software (fish shell is one of them for example) is going this way now because users get annoyed with the home directory becoming cluttered with endless configuration files. I think it would be a very basic change to this file here: https://github.com/laravel/valet/blob/a0dbae74bf2a8b63ae1ccb9d2cbfea2349e1fe59/server.php

The more software which transitions over to this standard the better!

**Comment by drbyte** [comment]
Note: Another location to change too: 
https://github.com/laravel/valet/blob/master/valet#L40

**Comment by joshmanders** [comment]
I agree with this. Lot of stuff is migrating over to the spec. Yarn recently did too.

**Comment by adamwathan** [comment]
Cool I like this idea. Would love a PR that also migrates the config from
the current location on install, making sure to preserve any secured sites
and stuff like that.

**Comment by eberkund** [comment]
Glad to see so much support for this issue, I will submit a PR shortly.
