### ISSUE TITLE
Updated to Valet 2. Magento 2 will no longer get shipping rates.

### ISSUE THREAD

**Issue by Jrb1x** [laravel/valet#448]
For some reason, upgrading to Valet 2 has broken all of my Magento installations. I can't access the checkout because the applications freeze when trying to get shipping rates. This occurs on multiple projects since updating.

**Comment by Jrb1x** [comment]
This seems to have something to do with the way HTML files are processed?

`ReferenceError: Unable to process binding "foreach: function (){return $parent.getRatesForGroup($data) }"
Message: Unable to process binding "css: function (){return {'field choice item':available,'message error':!available} }"
Message: Can't find variable: available`

This error happens on all of my projects now. Each project has different themes, different code, same version of Magento (2.1).

**Comment by adamwathan** [comment]
I've never used Magento 2 before but if you can provide the simplest possible steps to reproduce this (written for someone who has never even installed Magento) I can try and find time to take a look.

**Comment by Jrb1x** [comment]
@adamwathan Thanks the the quick reply. Here are my steps:

- Install Laravel (clean install on High Sierra), except install PHP5.6 instead of PHP7.0 with homebrew.
- Install MySQL with homebrew.
- Create a database called `magento`
- Create a Magento project directory
- Cd into new magento directory
- Create a Magento project from composer: `composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition=2.1.0 .`
- Install Magento
- Install magento: `sudo php bin/magento setup:install --admin-firstname=FIRSTNAME --admin-lastname=LASTNAME --admin-email=admin@email.com --admin-user=admin --admin-password='admin123' --base-url='http://magento.dev' --db-name="magento" --backend-frontname=admin --use-rewrites=1`
- 
- Add a product via the admin panel
- Go to the frontend, add the product to the cart (Make sure its in stock in the admin panel)
- Go to the cart page (http://magento/checkout/cart/)

This is where the problems start. You'll see the JS errors on this page. Continue to checkout and lots of empty shipping rates will show up.

**Comment by drbyte** [comment]
@Jrb1x you said you "upgraded". I think you may have some leftovers kicking around in your `~/.valet` directory or something. Including perhaps old/different Valet drivers?

Using `Valet 2.0.5`, I just created a fresh project using your steps above (granted, used `PHP 7.1` and `Magento 2.2` and skipped the `sudo` on the magento install) (and auth'ing to the repo after creating account+keys). Added a single product. Added to cart. Shipping methods work fine: both the default flat-rate, and also UPS (after enabling it). No JS errors. 

<img width="826" alt="screen shot 2017-09-30 at 4 05 15 pm" src="https://user-images.githubusercontent.com/404472/31049060-5e217d98-a5f9-11e7-8e1b-9c993d153fd8.png">

<img width="174" alt="screen shot 2017-09-30 at 4 05 59 pm" src="https://user-images.githubusercontent.com/404472/31049062-61d50824-a5f9-11e7-8e3d-d8944c78cff2.png">

**Comment by Jrb1x** [comment]
@drbyte I updated to Valet 2 by doing a clean install from High Sierra. I was previously using Valet 1 on Sierra. There shouldn’t be anything old in valet’s directory. It’s realy strange because I’ve just repeated the steps I listed on a web server (no Valet) and everything works great.

**Comment by Jrb1x** [comment]
This appears to be an issue with homebrew's PHP version. It was linked to php5.6.3, but Magento 2.1 requires 5.6.5. It's odd that homebrew doesn't offer 5.6.5.

**Comment by drbyte** [comment]
That's odd. 

The `php56` that Homebrew installed for me was `5.6.31`
