### ISSUE TITLE
Encoding not working as expected

### ISSUE THREAD

**Issue by Lloople** [laravel/valet#457]
I already know there's an old issue regarding encoding (#130), but I think my behaviour may be different.

I just installed Laravel Valet for the first time in a new machine. The project is working in another machine over Homestead and also in production server (Ubuntu 16).

The code that doesn't works as expected is:

```
echo iconv('UTF-8', 'ASCII//TRANSLIT', 'è'); // prints "`e". It should print "e"
```

I also followed the steps described here (except the first one since valet uses Nginx instead of Apache) https://stackoverflow.com/a/1610475

Maybe the problem is with nginx charset? I tried to edit the file `/etc/nginx/nginx.conf` but that folder does not exist.

I had this test on my app that passes in the Homestead machine

```
/** @test **/
public function slugify()
{
    $this->assertEquals('complex-string-to-be-sluged', slugify('Complex striñg to be slügèd'));
}
```

but now it's failling:

```
Failed asserting that two strings are equal.
Expected :'complex-string-to-be-sluged'
Actual   :'complex-stri-ng-to-be-sl-ug-ed'
```

The method to be tested:

```
function slugify(string $string, string $replace = '-'): string
{
    $removeasci = iconv('UTF-8', 'ASCII//TRANSLIT', $string);
    $removecomas = str_replace('\'', '', $removeasci);
    $output = preg_replace('/[^a-zA-Z0-9]/', $replace, $removecomas);

    return strtolower($output);
}
```

I also tested on `tinker` with the production server and Valet. This are the results

Production server
```
>>> $str = "àáâãäåæçèéêëìíîïðñòóôõöøùúûüý";
=> "àáâãäåæçèéêëìíîïðñòóôõöøùúûüý"
>>> strtoupper($str);
=> "àáâãäåæçèéêëìíîïðñòóôõöøùúûüý"
```

Local valet environment
```
>>> $str = "àáâãäåæçèéêëìíîïðñòóôõöøùúûüý";
=> "àáâãäåæçèéêëìíîïðñòóôõöøùúûüý</string>"
>>> strtoupper($str);
=> "ÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖØÙÚÛÜÝ</string>"
```

Any help will be much apppreciated 😄 

And of course, request as many information as you need, I'll try to provide it as soon as possible.

**Comment by timacdonald** [comment]
Having never used `iconv`, but after a quick read, perhaps this will suit...

```
\Illuminate\Support\Str::ascii('è');
```

**Comment by Lloople** [comment]
Thanks for your reply @timacdonald, but I'll prefer to continue using that code since I use it in a lot of projects and tested and worked in `5.6`, `7.0` and `7.1` and have tests for it.

Also, the problem is not just with `iconv` since `strtoupper` returns a different output too.

**Comment by timacdonald** [comment]
its because they are multibyte characters, so you need to use the PHP multibyte method. This is in Laravel Tinker...

<img width="650" alt="screen shot 2017-10-11 at 7 48 15 pm" src="https://user-images.githubusercontent.com/24803032/31430634-32b8ba28-aebd-11e7-857e-986f22b3cb8c.png">

I'd say your production server has tweaked PHP settings to alias all string methods automatically to the multi byte equivalent.

**Comment by Lloople** [comment]
The production server hasn't tweaked anything. That code works in 3 different productions servers and also in 2 different Homestead machines.

I don't know if Valet uses another version of `mbstring` or something like that.

The problem is not modifying the current code, since that code works in production. The problem is getting the current development environment to work with the production code 😄

**Comment by timacdonald** [comment]
Awesome, well hopefully someone smarter than I will jump on and get to the bottom of it for ya 👍

**Comment by adamwathan** [comment]
If it's an nginx charset issue, your nginx file is not located at `/etc/nginx/nginx.conf` on macOS, it's located at `/usr/local/etc/nginx`. Try making whatever changes you wanted to make there.

**Comment by Lloople** [comment]
@adamwathan thanks for the reply, I checked that file which calls `/usr/local/etc/nginx/valet/valet.conf`, but I saw that the charset is `utf-8` already.

    server {
        listen 80 default_server;
        root /;
        charset utf-8;
        client_max_body_size 128M;


Do you know what's going on? 

Thank you

**Comment by drbyte** [comment]
@Lloople is this still an issue? or have you found a workaround? 

I know you said "the production server hasn't tweaked anything". 
But I'll add that "Valet hasn't (hardly) tweaked anything" either, other than just doing a fresh install from Homebrew and tying things together. Granted, the Homebrew defaults might be missing/adding extensions (their PHP recipe is at https://github.com/Homebrew/homebrew-core/blob/master/Formula/php.rb and Nginx at https://github.com/Homebrew/homebrew-core/blob/master/Formula/nginx.rb)
... or something else in MacOS is setting defaults or dependencies different than your server OS is ... which definitely makes things harder to find a solution for.

**Comment by Lloople** [comment]
@drbyte nope, I switched the code to use the `mb_` version two years ago and never looked back. Also my machine is different now and I cannot reproduce the error again.
