### ISSUE TITLE
Blank page after valet secure High Sierra

### ISSUE THREAD

**Issue by kevinpijning** [laravel/valet#462]
I installed Valet, got it working, but after i tried to use
`valet secure foobar` valet stopped working.
Every domain i go to gives me a blank page. Even with only an index.html file in the domain root and public directory.

I've checked the log files in the .valet dir, nginx-error.log is the only file en it is empty.

Uninstalling and reinstalling valet has no result, tried is multiple times with reboots in between.
`valet stop`
`valet uninstall`
`rm -rf ~/.valet directory`
`brew unlink nginx && brew remove nginx`
`brew unlink php56 && brew remove php56 && brew uninstall --ignore-dependencies php56`
`brew unlink php71 && brew remove php71`
`brew unlink dnsmasq && brew remove dnsmasq`

Someone ideas? Thanks!

**Comment by pryley** [comment]
I have the same issue (also on High Sierra). The only way so far to fix it is to restart after running `valet secure`

**Comment by drbyte** [comment]
I think this can be closed due to inactivity, and the fact that CA Certificate logic has been updated.
