### ISSUE TITLE
mac sierra valet install error

### ISSUE THREAD

**Issue by hope-soft** [laravel/valet#463]
I am using mac Sierra. when I try to install valet I am getting this error.
PHP Parse error:  syntax error, unexpected '.11' (T_DNUMBER), expecting ',' or ')' in Command line code on line 2

**Comment by eaktadiur** [comment]
I have same problem

**Comment by Yashaswini** [comment]
Even I face the same issue. I get - syntax error, unexpected '.12' (T_DNUMBER), expecting ',' or ')' in Command line code on line 2/cli/valet.php

I cant trace the root cause. Any help appreciated

**Comment by drbyte** [comment]
Questions:
- OS version
- what command-shell are you running? bash? zsh? oh-my-zsh? other?
- what's the output of running:   `which php`
- what's the output of running:  `php -v`
- what's the output of running: `brew services list`

**Comment by ChadTaljaardt** [comment]
These are the same?
https://github.com/laravel/valet/issues/491

**Comment by drbyte** [comment]
Yes, same issue: Mac is actually using original old PHP version, not the Homebrew version, and therefore is incompatible with Valet.

Solution: fix the linking of Homebrew PHP version, as described in #491 


This issue can be closed.
