### ISSUE TITLE
Unable to use brew's nginx package after uninstalling Valet

### ISSUE THREAD

**Issue by ctrlaltdylan** [laravel/valet#465]
Steps to reproduce:

1. Install Valet
2. Uninstall Valet (`valet uninstall` + including removing `~/.valet` and `/usr/local/nginx/valet` and references in `nginx.confg`)
3. Uninstall dnsmasq (`brew uninstall dnsmasq`)
4. Uninstall nginx (`brew uninstall nginx && rm -rf /usr/local/etc/nginx`)
5. Reinstall nginx (`brew install nginx`)
6. Attempt to view the default `http://localhost:8080` page, get a "Connection Refused"

It appears that nginx is running, but `sudo lsof -i -P | grep -i "8080"` doesn't show nginx running at the expected port, double checked the `nginx.conf` to make sure the entry was correct. `brew services list` shows that nginx is indeed running but with a yellow status - whatever that means.

I think there might be a rogue valet setting or file somewhere that's effecting nginx or dns resolution to localhost.

**Comment by ctrlaltdylan** [comment]
Another fun tidbit that the valet installation leaves behind that it doesn't uninstall:

In your `/usr/local/etc/php70/php-fpm.d/www.conf` which controls your php-fpm settings. It changes the php-fpm socket to valet's own thing. Uninstalling valet doesn't remove this entry and you're kinda on your own to figure this out.

```
; The address on which to accept FastCGI requests.
; Valid syntaxes are:
;   'ip.add.re.ss:port'    - to listen on a TCP socket to a specific IPv4 address on
;                            a specific port;
;   '[ip:6:addr:ess]:port' - to listen on a TCP socket to a specific IPv6 address on
;                            a specific port;
;   'port'                 - to listen on a TCP socket to all addresses
;                            (IPv6 and IPv4-mapped) on a specific port;
;   '/path/to/unix/socket' - to listen on a unix socket.
; Note: This value is mandatory.
listen = /Users/dylanpierce/.valet/valet.sock
```

To get your regular behavior back, change `listen = /Users/YOUR_USERNAME/.valet/valet.sock` to `listen = localhost:9000`, or a different socket location if you prefer sockets.

**Comment by ptasker** [comment]
I'd check what `brew services list` shows for nginx. It may be running as root, in which case you'll need to `sudo` uninstall/install. I had a bunch of issues with nginx on High Sierra, and the sudo trick worked well. See also: https://github.com/laravel/valet/issues/298#issuecomment-274799696

**Comment by drbyte** [comment]
I think this can be closed due to inactivity.
