### ISSUE TITLE
Valet embedding localhost to addresss

### ISSUE THREAD

**Issue by remymumoh** [laravel/valet#469]
So i have created a local host directory on my MacBook. whenever i type valet open it loads the name of the project but it embeds http://loginregister.dev/dashboard/  in-front instead of loading http://loginregister.dev. How can you correct this?

**Comment by drbyte** [comment]
I don't think this is a valet issue.

**Comment by remymumoh** [comment]
i have tried everything Laravel Valet stil Showing all folders in the localhost

**Comment by adamwathan** [comment]
Agree don't know how this could be a Valet issue. Are you saying your URL bar is showing this?

```
http://loginregister.dev/dashboard/http://loginregister.dev
```

**Comment by remymumoh** [comment]
not this http://loginregister.dev/dashboard/http://loginregister.dev
but this http://loginregister.dev/dashboard/  instead of loading the website it is showing all files in localhost

**Comment by adamwathan** [comment]
What do you mean by "showing all the files in localhost"? Is it showing a directory listing? What directory? There's no "localhost" directory so not sure what you're seeing.

**Comment by remymumoh** [comment]
i have created a projects folder on my root folder, then mapped it on valet so after installing a new laravel installation, and trying to say valet open inside the folder it shows the directories instead of loading the public folder

**Comment by mattstauffer** [comment]
@remymumoh It's not entirely clear what you're saying here.

Can you write out A) the steps you're taking, one after another and B) how those steps are differing from what you expect?

**Comment by drbyte** [comment]
I think this can be closed due to inactivity.
