### ISSUE TITLE
no .valet folder / 502 Bad Gateway

### ISSUE THREAD

**Issue by ibdf** [laravel/valet#471]
I'm getting a 502 Bad Gateway error on any folder added to park. Unlike most people having this issue, I am not on Sierra, I'm on El Capitan. After trying to troubleshoot this issue I noticed that I don't even have .valet folder.

I get no errors during installation. I have removed everything and added everything again but no luck. I'm using php 7.1.

What else can I check?

**Comment by GielvdBerg** [comment]
I have exactly the same issue.

**Comment by adamwathan** [comment]
Sounds like something is going wrong in the installation process. I recommend adding some debug statements to your local copy of Valet's source to try and troubleshoot where things are going wrong; I don't have any ideas off the top of my head unfortunately.

**Comment by james2doyle** [comment]
I ran `valet install` again and mine came back from the dead.

**Comment by GielvdBerg** [comment]
Yay, it works!

After some research and some headache, it works.

1. Set the correct permissions on /var/root
2. Run valet install
3. Run sudo find / -type d -name '.valet'
4. mv the .valet folder to ~
