### ISSUE TITLE
Laravel Valet "directory.dev" return to localhost directory even I run "Valet park" in the folder my Os is High Sierra

### ISSUE THREAD

**Issue by moussaDoumbia9219** [laravel/valet#477]

**Comment by adamwathan** [comment]
Need a lot more info than a title and an empty issue to help solve this...

**Comment by moussaDoumbia9219** [comment]
Have a fresh installation of Sierra High who is running on php 7.7 when run valet park in my workspace directory and going to chrome to try if the command work the folder.dev turn me to my  127.0.0.1 installation

**Comment by d3z41k** [comment]
Apache may be running... try `sudo apachectl stop`

**Comment by moussaDoumbia9219** [comment]
thanks it's work

**Comment by drbyte** [comment]
@moussaDoumbia9219 if this is resolved, please close the issue.
