### ISSUE TITLE
Valet park with symlink in directory

### ISSUE THREAD

**Issue by Oscarteg** [laravel/valet#478]
I have a `~/Sites` folder and want to serve all valet sites from that directory. So I `valet park` that directory. I symlink a couple of Laravel projects to that directory from my Projects folders but valet doesn't work with the symlink. A fresh installation in the `~/Sites` folder does work but symlinks doesn't. 

Is there a way that makes symlinking a project in a parked directory work?

**Comment by drbyte** [comment]
@Oscarteg 
No, in my experience that is not possible. I've always ended up having to do it the other way: create it in my valet-served directory and symlink the other direction.

Unless someone comes up with and posts a way to do it, I don't imagine this will become a feature of valet.

**Comment by drbyte** [comment]
IMO this can be closed.
