### ISSUE TITLE
Chrome forcing .dev domains to HTTPS 

### ISSUE THREAD

**Issue by devinfd** [laravel/valet#480]
I suspect you are aware of this already but in case not.

Chrome to force .dev domains to HTTPS via preloaded HSTS
https://ma.ttias.be/chrome-force-dev-domains-https-via-preloaded-hsts/

This change/problem is begging to take affect.

**Comment by adamwathan** [comment]
Yep Valet was updated to account for this back in October:

https://github.com/laravel/valet/pull/436

**Comment by devinfd** [comment]
oh I missed that update. Thanks!

**Comment by devinfd** [comment]
fyi: it's a bit confusing because all the documentation in this repo and the laravel docs still refer to .dev

**Comment by adamwathan** [comment]
Yeah we haven't tagged a release or updated the docs yet, just spread a bit thin across too many projects to dedicate a lot of time to this right now.

**Comment by devinfd** [comment]
I understand. Maybe later today or tomorrow I’ll send a pr to update those. 

- Devin Dombrowski

**Comment by hsleewis** [comment]
Somehow this also happens in Safari 11.0.2 on macOS 10.13.2. Not only with .dev, but with all "fake" tld's.
