### ISSUE TITLE
Valet links gives no sites back.

### ISSUE THREAD

**Issue by hsleewis** [laravel/valet#484]
I've ran "valet park" in my ~/Projects folder and when I run "valet links" I get this:
```
+------+-----+-----+------+
| Site | SSL | URL | Path |
+------+-----+-----+------+
```
Without any sites under it.

I'm running 2.0.6 under macOS 10.13.2
(since the last macOS update I got a whole bunch of issues with valet in combination with Safari)

Already reinstalled homebrew, php, nginx and valet.
Anyone else having issues like this?

**Comment by adamwathan** [comment]
`valet links` lists sites that you explicitly linked with `valet link`; it's not meant to show sites that are available via a parked folder.

**Comment by adamhopkinson** [comment]
I was about to add a ticket requesting what @hsleewis was expecting, then found this.

It would be really useful (to me at least) if `valet links` also showed sites available via a parked folder:

- I often forget where stuff is or what it's called, and this would reduce the steps involved in re-discovering stuff
- in iTerm I can cmd+click a url to open it
- for sites in parked folders, there's no way to see which are secured without running `valet open` on each one

My suggestion would be to add a fifth column to the `valet links` output, called something like _Added via_:

`+------+-----+-----+------+-----------+
| Site | SSL | URL | Path | Added via |
+------+-----+-----+------+-----------+`
