### ISSUE TITLE
Valet 2.0.6 still points to .dev

### ISSUE THREAD

**Issue by itzikbenh** [laravel/valet#487]
I'm on macOS Sierra. I uninstalled and installed several times, but I can't get the test domain to work. I cleared cache and everything, but only the .dev works. 
And ideas?

**Comment by adamwathan** [comment]
Sounds like you probably didn’t *completely* uninstall (removing dnsmasq
config for example). It won’t update automatically for an existing install,
you just need to run “valet domain test” to change it.

**Comment by itzikbenh** [comment]
Thanks :)
