### ISSUE TITLE
Parse error: syntax error, unexpected '.12' (T_DNUMBER), expecting ',' or ')' in Command line code

### ISSUE THREAD

**Issue by Yashaswini** [laravel/valet#491]
I have been using valet for a month now & now it seems something has gone wrong. 
I am unable to use .*dev sites and it throws me 'The site cant be reached error' 
I have all the pre-requisites installed via brew to run valet successfully. However when I run valet restart / valet start command I see following error. 

`PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/Cellar/php71/7.1.12_23/lib/php/extensions/no-debug-non-zts-20160303/php_gmp.dll' - dlopen(/usr/local/Cellar/php71/7.1.12_23/lib/php/extensions/no-debug-non-zts-20160303/php_gmp.dll, 9): image not found in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/Cellar/php71/7.1.12_23/lib/php/extensions/no-debug-non-zts-20160303/php_intl.dll' - dlopen(/usr/local/Cellar/php71/7.1.12_23/lib/php/extensions/no-debug-non-zts-20160303/php_intl.dll, 9): image not found in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php71-pdo-pgsql/pdo_pgsql.so' - dlopen(/usr/local/opt/php71-pdo-pgsql/pdo_pgsql.so, 9): image not found in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/Cellar/php71/7.1.12_23/lib/php/extensions/no-debug-non-zts-20160303/php_gmp.dll' - dlopen(/usr/local/Cellar/php71/7.1.12_23/lib/php/extensions/no-debug-non-zts-20160303/php_gmp.dll, 9): image not found in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/Cellar/php71/7.1.12_23/lib/php/extensions/no-debug-non-zts-20160303/php_intl.dll' - dlopen(/usr/local/Cellar/php71/7.1.12_23/lib/php/extensions/no-debug-non-zts-20160303/php_intl.dll, 9): image not found in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php71-pdo-pgsql/pdo_pgsql.so' - dlopen(/usr/local/opt/php71-pdo-pgsql/pdo_pgsql.so, 9): image not found in Unknown on line 0
PHP Parse error:  syntax error, unexpected '.12' (T_DNUMBER), expecting ',' or ')' in Command line code on line 2
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/Cellar/php71/7.1.12_23/lib/php/extensions/no-debug-non-zts-20160303/php_gmp.dll' - dlopen(/usr/local/Cellar/php71/7.1.12_23/lib/php/extensions/no-debug-non-zts-20160303/php_gmp.dll, 9): image not found in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/Cellar/php71/7.1.12_23/lib/php/extensions/no-debug-non-zts-20160303/php_intl.dll' - dlopen(/usr/local/Cellar/php71/7.1.12_23/lib/php/extensions/no-debug-non-zts-20160303/php_intl.dll, 9): image not found in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php71-pdo-pgsql/pdo_pgsql.so' - dlopen(/usr/local/opt/php71-pdo-pgsql/pdo_pgsql.so, 9): image not found in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/Cellar/php71/7.1.12_23/lib/php/extensions/no-debug-non-zts-20160303/php_gmp.dll' - dlopen(/usr/local/Cellar/php71/7.1.12_23/lib/php/extensions/no-debug-non-zts-20160303/php_gmp.dll, 9): image not found in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/Cellar/php71/7.1.12_23/lib/php/extensions/no-debug-non-zts-20160303/php_intl.dll' - dlopen(/usr/local/Cellar/php71/7.1.12_23/lib/php/extensions/no-debug-non-zts-20160303/php_intl.dll, 9): image not found in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php71-pdo-pgsql/pdo_pgsql.so' - dlopen(/usr/local/opt/php71-pdo-pgsql/pdo_pgsql.so, 9): image not found in Unknown on line 0
PHP Parse error:  syntax error, unexpected '.12' (T_DNUMBER), expecting ',' or ')' in Command line code on line 2
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/Cellar/php71/7.1.12_23/lib/php/extensions/no-debug-non-zts-20160303/php_gmp.dll' - dlopen(/usr/local/Cellar/php71/7.1.12_23/lib/php/extensions/no-debug-non-zts-20160303/php_gmp.dll, 9): image not found in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/Cellar/php71/7.1.12_23/lib/php/extensions/no-debug-non-zts-20160303/php_gmp.dll' - dlopen(/usr/local/Cellar/php71/7.1.12_23/lib/php/extensions/no-debug-non-zts-20160303/php_gmp.dll, 9): image not found in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/Cellar/php71/7.1.12_23/lib/php/extensions/no-debug-non-zts-20160303/php_intl.dll' - dlopen(/usr/local/Cellar/php71/7.1.12_23/lib/php/extensions/no-debug-non-zts-20160303/php_intl.dll, 9): image not found in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/Cellar/php71/7.1.12_23/lib/php/extensions/no-debug-non-zts-20160303/php_intl.dll' - dlopen(/usr/local/Cellar/php71/7.1.12_23/lib/php/extensions/no-debug-non-zts-20160303/php_intl.dll, 9): image not found in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php71-pdo-pgsql/pdo_pgsql.so' - dlopen(/usr/local/opt/php71-pdo-pgsql/pdo_pgsql.so, 9): image not found in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/opt/php71-pdo-pgsql/pdo_pgsql.so' - dlopen(/usr/local/opt/php71-pdo-pgsql/pdo_pgsql.so, 9): image not found in Unknown on line 0
Could not open input file: 
Warning: PHP Startup: Unable to load dynamic library '/usr/local/Cellar/php71/7.1.12_23/lib/php/extensions/no-debug-non-zts-20160303/php_gmp.dll' - dlopen(/usr/local/Cellar/php71/7.1.12_23/lib/php/extensions/no-debug-non-zts-20160303/php_gmp.dll, 9): image not found in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/Cellar/php71/7.1.12_23/lib/php/extensions/no-debug-non-zts-20160303/php_intl.dll' - dlopen(/usr/local/Cellar/php71/7.1.12_23/lib/php/extensions/no-debug-non-zts-20160303/php_intl.dll, 9): image not found in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/opt/php71-pdo-pgsql/pdo_pgsql.so' - dlopen(/usr/local/opt/php71-pdo-pgsql/pdo_pgsql.so, 9): image not found in Unknown on line 0

Parse error: syntax error, unexpected '.12' (T_DNUMBER), expecting ',' or ')' in Command line code on line 2/cli/valet.php`

I am not able to understand the root cause for this. Any help is appreciated.

**Comment by drbyte** [comment]
Please post the output of the following commands:

`which php`
and
`php -v`
and
`brew services list`

**Comment by Yashaswini** [comment]
Hi @drbyte 

Version - PHP 7.1.12 
brew services list shows me

`dnsmasq    started user /Users/user/Library/LaunchAgents/homebrew.mxcl.dnsmasq.plist
memcached  started user /Users/user/Library/LaunchAgents/homebrew.mxcl.memcached.plist
nginx      started root /Library/LaunchDaemons/homebrew.mxcl.nginx.plist
php70      started user /Users/user/Library/LaunchAgents/homebrew.mxcl.php70.plist
php71      started root /Library/LaunchDaemons/homebrew.mxcl.php71.plist
postgresql started user /Users/user/Library/LaunchAgents/homebrew.mxcl.postgresql.plist`

**Comment by drbyte** [comment]
And what does running `which php` give you?  It should show you the path that it things PHP should be called from.

**Comment by Yashaswini** [comment]
Just throws me this warning 
`PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/Cellar/php71/7.1.12_23/lib/php/extensions/no-debug-non-zts-20160303/php_gmp.dll' - dlopen(/usr/local/Cellar/php71/7.1.12_23/lib/php/extensions/no-debug-non-zts-20160303/php_gmp.dll, 9): image not found in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/Cellar/php71/7.1.12_23/lib/php/extensions/no-debug-non-zts-20160303/php_gmp.dll' - dlopen(/usr/local/Cellar/php71/7.1.12_23/lib/php/extensions/no-debug-non-zts-20160303/php_gmp.dll, 9): image not found in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/Cellar/php71/7.1.12_23/lib/php/extensions/no-debug-non-zts-20160303/php_intl.dll' - dlopen(/usr/local/Cellar/php71/7.1.12_23/lib/php/extensions/no-debug-non-zts-20160303/php_intl.dll, 9): image not found in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/Cellar/php71/7.1.12_23/lib/php/extensions/no-debug-non-zts-20160303/php_intl.dll' - dlopen(/usr/local/Cellar/php71/7.1.12_23/lib/php/extensions/no-debug-non-zts-20160303/php_intl.dll, 9): image not found in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php71-intl/intl.so' - dlopen(/usr/local/opt/php71-intl/intl.so, 9): Library not loaded: /usr/local/opt/icu4c/lib/libicudata.60.1.dylib
  Referenced from: /usr/local/opt/php71-intl/intl.so
  Reason: image not found in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/opt/php71-intl/intl.so' - dlopen(/usr/local/opt/php71-intl/intl.so, 9): Library not loaded: /usr/local/opt/icu4c/lib/libicudata.60.1.dylib
  Referenced from: /usr/local/opt/php71-intl/intl.so
  Reason: image not found in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php71-pdo-pgsql/pdo_pgsql.so' - dlopen(/usr/local/opt/php71-pdo-pgsql/pdo_pgsql.so, 9): image not found in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/opt/php71-pdo-pgsql/pdo_pgsql.so' - dlopen(/usr/local/opt/php71-pdo-pgsql/pdo_pgsql.so, 9): image not found in Unknown on line 0`

**Comment by drbyte** [comment]
Strange.  The `which` command is a shell command asking the OS to tell you what binary it's trying to load.

So, running `which php` should give you: `/usr/local/opt/php71/php` if it is indeed running Homebrew's version of PHP.

I think you're just typing `php` instead of `which php`

**Comment by drbyte** [comment]
Also, what output do you get when you type:
`echo $PATH` at the command line?

**Comment by Yashaswini** [comment]
Sorry my bad :( 

/usr/local/bin/php - This is the output

**Comment by drbyte** [comment]
Okay, that's exactly the problem: You're using Mac's PHP, not Homebrew's.

Run:
`brew link php71`

**Comment by Yashaswini** [comment]
But that's not the case since I have already linked it. And running the above command gives me the warning below : 
Warning: Already linked: /usr/local/Cellar/php71/7.1.12_23

**Comment by drbyte** [comment]
Okay, then that tells me that your environment PATH may have `/usr/bin` listed before `/usr/local/bin`

What's the output from:
`echo $PATH` at the command line?

**Comment by Yashaswini** [comment]
`/Library/Frameworks/Python.framework/Versions/3.6/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/Users/user/anaconda/bin:/opt/local/bin:/opt/local/sbin:/Applications/XAMPP/xamppfiles/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Postgres.app/Contents/Versions/latest/bin:/Users/user/.composer/vendor/bin`

**Comment by drbyte** [comment]
Okay, another diagnostic:
What do you get from:
`/usr/bin/php -v`

**Comment by Yashaswini** [comment]
Ah, i get this one 
`PHP 5.6.30 (cli) (built: Feb  7 2017 16:18:37) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies`

But i do have all the references unlinked. I wonder how this is being referenced

**Comment by drbyte** [comment]
I wonder if your `/usr/local/bin/php` is a symlink to `/usr/bin/php`
I think homebrew normally makes its own symlink to `/usr/local/bin/php` pointing to whatever you've installed, when you run `brew link xxxxx`

You could try: `rm /usr/local/bin/php` and then `brew unlink php71 && brew link php71` to force a refreshing.

**Comment by drbyte** [comment]
You can check what the symlink is by:  `ln -al /usr/local/bin` and see what it says `php` is pointed to.

**Comment by drbyte** [comment]
Aside:  When you get a minute, can you please edit the title of this issue to be the actual main error message we've been investigating:

`Parse error: syntax error, unexpected '.12' (T_DNUMBER), expecting ',' or ')' in Command line code`

**Comment by mattstauffer** [comment]
Closing as it seems @drbyte's fix here is a solution. Please let me know if this ends up not being the case.

**Comment by lukepolo** [comment]
It doesn't seem to be working for me 

PATH
`
/Users/LukePOLO/.nvm/versions/node/v8.9.1/bin:/usr/local/opt/php72/bin:/usr/local/sbin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
`

php --version 
`PHP 7.2.2 (cli)`


which php
`/usr/local/opt/php72/bin/php`


Its like composer is refusing to use 7.2.1 , instead loads 5.6.30

**Comment by agraynel** [comment]
Sorry, I ran rm /usr/local/bin/php and then brew unlink php71 && brew link php71,
but still when I use valet command, it says,
PHP Warning:  Module 'intl' already loaded in Unknown on line 0
PHP Warning:  Module 'intl' already loaded in Unknown on line 0
PHP Parse error:  syntax error, unexpected 'intl' (T_STRING), expecting ',' or ')' in Command line code on line 2
PHP Warning:  Module 'intl' already loaded in Unknown on line 0
PHP Warning:  Module 'intl' already loaded in Unknown on line 0
PHP Parse error:  syntax error, unexpected 'intl' (T_STRING), expecting ',' or ')' in Command line code on line 2
PHP Warning:  Module 'intl' already loaded in Unknown on line 0

Warning: Module 'intl' already loaded in Unknown on line 0
Could not open input file: 
Warning: Module 'intl' already loaded in Unknown on line 0

Parse error: syntax error, unexpected 'intl' (T_STRING), expecting ',' or ')' in Command line code on line 2/cli/valet.php

**Comment by drbyte** [comment]
Your homebrew PHP is broken. It appears you've installed php-intl multiple times, perhaps once with the old homebrew versioning and then again after the new versioning, so it's trying to load the `intl` config multiple times, hence the error.

This is a homebrew issue.

This is not a Valet issue.

**Comment by simplenotezy** [comment]
@drbyte running `ln -al /usr/local/bin` gives error `ln: illegal option -- a`
