### ISSUE TITLE
Can't open Valet sites without www subdomain

### ISSUE THREAD

**Issue by ivanvermeyen** [laravel/valet#496]
Hi,

After running `valet domain local` to switch from .dev, I suddenly need to include the www subdomain in the url if I want to open a site in the browser... otherwise i get `ERR_NAME_NOT_RESOLVED`.

I've been digging through a lot of valet/nginx config files but couldn't find any reference that could explain this behaviour...

I  also uninstalled Valet, removed the `~/.valet` folder, uninstalled nginx and dnsmasq and then reinstalled Valet. But I still need to add the www subdomain.

Maybe the issue is not with Valet, but I have no idea what it could be...

**Comment by drbyte** [comment]
Browsers don't typically recognize unregistered TLDs like `.test`.

Typically just adding a `/` to the end of the domain name overcomes this browser issue.

ie: these will usually work fine:
`example.test/` 
`http://example.test`

**Comment by ivanvermeyen** [comment]
Yeah it used to work like that, but now `http://mysite.local/` fails and `http://www.mysite.local/` works... :(

**Comment by ivanvermeyen** [comment]
So I gave it another shot and tried a few more things:

- removed Valet, nginx, dnsmasq
- removed all of its config folders in `~/.valet` and under `/usr/local/etc`.
- installed Valet again (`composer require`, `valet install`, `valet park`).

At this point `http://site.test` is loading in the browser.

- then I ran `valet domain local`

Now `http://site.local` is not loading, but `http://www.site.local` is.

When I switch back to `.test`, (`valet domain test`) then `http://site.test` is working again.

When I switch to `.app` (`valet domain app`) it keeps redirecting me to `https`...

When I try `.labz` (`valet domain labz`) then `http://site.labz` is loading as expected...

So there seems to be something weird going on with .local and .app...

**Comment by adamwathan** [comment]
.app is owned by Google and Chrome forces it to HTTPS now just like .dev (as far as I understand.)

It sounds like .local behaves in some special way as well. I would recommend using a safe TLD that's designed for this sort of use-case, which is why we use `.test` by default now:

https://tools.ietf.org/html/rfc2606

**Comment by ivanvermeyen** [comment]
Ok, thanks 👍
