### ISSUE TITLE
Redirect to external URL

### ISSUE THREAD

**Issue by pascalporedda** [laravel/valet#497]
Hello there,

I've recently switched to using valet as my local development environment. Every things is awesome, except one thing.

What I'am trying to do is write a custom driver, that redirect images requests to an external server if they don't exist on my filesystem, as I don't want to download tons of gigabytes of images from my staging or live servers to my local env. 

In my previous setup with Apache I could simply do this with the following snippet:

```
RedirectMatch ^/media/(.*)\.(jpeg|jpg|gif|png)$ https://external-server.tld/static/media/$1.$2
RedirectMatch ^/static/uploads/(.*)\.(jpeg|jpg|gif|png)$ https://external-server.tld/static/uploads/$1.$2
```

The custom drivers can't handle "external" links, if I would return to "google.com" for example.

Here is an excerpt from what I have been trying to do:
```
    public function isStaticFile($sitePath, $siteName, $uri)
    {
        if ($this->isActualFile($staticFilePath = $sitePath.'/web/'.$uri)) {
            return $staticFilePath;
        }

        if (strpos($uri, 'media') || strpos($uri, 'uploads')) {
            return 'http://via.placeholder.com/350x150';
        }

        return false;
    }
```
This is causing an 500 status code from nginx. 

Is there any chance to get this to work? I've been browsing through the source code of valet, but have not found an entry point to this, to make a contribution.

**Comment by drbyte** [comment]
I imagine the problem is that it's looking for a `file` to serve or execute, and giving it a `URL` string isn't comprehendible by nginx at that stage. 

I think you're better off touching the nginx configuration, similar to what you did with your apache:
```diff
-    RedirectMatch ^/media/(.*)\.(jpeg|jpg|gif|png)$ https://external-server.tld/static/media/$1.$2
+    rewrite ^/media/(.*)\.(jpeg|jpg|gif|png)$ https://external-server.tld/static/media/$1.$2 redirect;
```
in `/Users/username/.valet/nginx/domainname.tld`
ie: `/Users/pascal/.valet/nginx/example.test`

**Comment by pascalporedda** [comment]
> I imagine the problem is that it's looking for a file to serve or execute, and giving it a URL string isn't comprehendible by nginx at that stage.

Yeah that's what I assumed as well. 

> I think you're better off touching the nginx configuration, similar to what you did with your apache

That seems to be working fine, thank you. Probably the easiest solution.
