### ISSUE TITLE
Provide support for Chrome 63+ and .dev domains

### ISSUE THREAD

**Issue by StarkNZ** [laravel/valet#499]
Afternoon/Evening everyone.

Hey, I found a way to use the .dev domain with HTTPS. Was wondering if a command such as ``secure-all`` could be added to secure all sites to make this work.

This command would be responsible for generating a SSL certificate for every site in your parked/linked directories.

How to get single projects working:

1. Paste this into your browser, and enable the experimental feature.
``chrome://flags/#allow-insecure-localhost``
2. In your project of choice(s), run the ``valet secure`` command
3. Visit your site in the browser as: ``https://your-domain.dev``

**notes:**

For Wordpress, update all options linking to your current URL and clear cache/cookies else you'll be redirected back to the old domain.

**Comment by drbyte** [comment]
So you've brought up 2 things here:

1. Asking for a `secure-all` command to pre-run `valet secure` against all potential sites in configured directories.
I don't think this is a good idea. One still needs to manually configure every project in those directories to use http or https, and whatever domain is relevant. Case in point your Wordpress footnote.
It's a one-time thing, and it's not uncommon to have other folders in the "parked" directory, which are never served by valet; so generating certificates and configs for those isn't helpful.
I don't this should be in valet.

2. Switching Chrome-specific flags.
While this is handy, it only works with certain browsers.  (Or works differently in other browsers.)
So while it's nice to have documented someplace as a tip (a Medium post, for example), we shouldn't be building anything into valet for it. 

Just my opinion.

**Comment by mattstauffer** [comment]
This is a great issue to have as a reference point, and as @drbyte said, this could also be a helpful blog post--but it's not something necessarily appropriate for formal inclusion in Valet. Thanks for the report/idea!
