### ISSUE TITLE
composer global require laravel/valet - command not found in macOS Heigh Sierra

### ISSUE THREAD

**Issue by Yosef7908** [laravel/valet#500]
I'm having issues installing larval valet on macOS Heigh Sierra I already did the following steps.

1 . /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" - this worked fine
2. brew update - this worked fine
3. brew install homebrew/php/php71 - this worked fine
4. composer global require laravel/valet - this gives me command not found

I know I'm supposed to add it to the path but this command composer global require laravel/valet should work before I add the path

**Comment by AlexVipond** [comment]
@YosefOberlander Did you find a solution to this problem?

**Comment by clarknelson** [comment]
I just fixed this by using `$PATH:$HOME/.composer/vendor/bin` instead of `$PATH:~/.composer/vendor/bin`

**Comment by melch-inno** [comment]
I was having the same error but I fixed it using `export PATH=$PATH:~/.composer/vendor/bin` Hope it will work for you.
