### ISSUE TITLE
[Feature] make an alias to the tools files inside the .valet folder

### ISSUE THREAD

**Issue by ctf0** [laravel/valet#503]
valet comes with lots of pre-configured settings for things like `nginx, phpfpm, etc..`, however you may need to change some of this settings to fix issues like https://github.com/laravel/valet/issues/269 or https://github.com/laravel/valet/issues/315

atm valet doesnt offer an easy way to edit those files and you simply have to search all over the place to find them, 
so maybe on installation valet would create alias/shortcuts to those files automatically so the user can have a one & central location where he can just goto and edit.

**Comment by regularlabs** [comment]
Or have a built in option to set the timeouts in valet.
Maybe have some default 'dev' mode that will set the timeouts to a high number.

**Comment by ctf0** [comment]
@adamwathan any updates ?

**Comment by jacobdo2** [comment]
I second timeouts option, although control of those would be handy.

**Comment by drbyte** [comment]
@mattstauffer @ctf0 now that the directories/files are documented in the Valet docs, I think we can close this issue.

Ref: https://laravel.com/docs/valet#valet-directories-and-files
