### ISSUE TITLE
[Feature] Give the option of forcing SSL when using valet secure

### ISSUE THREAD

**Issue by mcblum** [laravel/valet#504]
Based on another thread and trying to get ngrok to work, it would be awesome if when you secured a site you could do something like `--force` if you wanted to force port 80 to redirect to 443. Running `valet share` fails with a site that's secured locally because the default valet Nginx config doesn't respond on port 80 anymore after being secured.

**Comment by mattstauffer** [comment]
@mcblum I have read those threads but not 100% followed.

Would it be safe to say that "If we could force SSL after securing, we could run `valet share` after `valet secure` and it would work"? If so, that's awesome.

**Comment by mcblum** [comment]
@mattstauffer me neither, dude. So many terms to process.

Here's what we went through - let me know if it makes sense.

We secured our API which means that locally it's served at `https://app.dev`. All good so far. Then I needed to test some webhooks, so I fired up Ngrok with `valet share` and pointed Mailgun to `https://crazyurl.ngrox.com` where my tunnel was located. However, locally Ngrok maps both `http` and `https` to port 80. The issue arises then because running `valet secure` adds a server  block that listens on port 80 but only directs to port 443. Because of that, all requests made via Ngrox fail with a 301 returned.

The fix that I made was to manually edit the `/Users/mcblum/.valet/Nginx/app.conf` file to basically serve the app on both port 80 and port 443. That way when Ngrox sends the requests to `http` the app still responds.

Let me know if this makes sense. I think that's what you said above.

The way I see it, if you run `valet secure` either there could be an option to serve on both ports _or_ redirect to ssl, or running `valet share` could regenerate the Nginx config file to serve sites on both ports.

**Comment by mattstauffer** [comment]
Ahh--totally makes sense.

So if it would work, you could theoretically say "force redirect to ssl after running `valet share`" and it would fix the issue as well, right? Thanks for explaining!

**Comment by drbyte** [comment]
Two clarifications:

1. The free ngrok accounts don't support https, hence why both http and https are being directed to port 80. 

2. When one runs `valet secure` all the secured `site.conf` files are updated to redirect all port 80 traffic to port 443, basically forcing https. This is great, except when using the free ngrok which forces it all onto port 80.

So, as @mcblum pointed out, having valet build the `site.conf` to serve -normally- on port 80 (but of course as http, not https), in addition to serving on port 443 as https, solves this ngrok problem. 

Making that change to `valet secure` in a way that affects "all" sites may or may not be desirable.

I propose that adding an optional parameter to `valet secure` like `--not-redirected` would be useful. In such case its generation of the `.conf` file should build a normal port-80 section, and a normal port-443 section.

**Comment by mattstauffer** [comment]
Ahhhhh I get it with the free ngrok. I had it backward. Thanks @drbyte. And that makes sense why there's no global fix that would work.

**Comment by mcblum** [comment]
Thanks @drbyte for making my gibberish more clear.  @mattstauffer it's possible there just isn't a great way to fix it and that's just fine - it isn't that much work to make it function. I also didn't realize that free Ngrox didn't actually support https. The strange thing is `https` _seems_ to work but they must just be handling the request and then not actually using it rather than throwing an error when you try to interact with https.

Maybe there's nothing to be done here or maybe a short bit in the docs explaining that this is an edge case with `valet secure`, `valet share` and a free Ngrok account?

**Comment by drbyte** [comment]
Others have reported similar challenges with free ngrok, and thus far the "solution" was to `valet unsecure`.  But I've never liked that "solution".
I think the `valet secure [site] --not-redirected` is a good hybrid: it would do what @mcblum has done to make it work, which IMO is the best approach.

**Comment by mcblum** [comment]
@drbyte I think that's a solid choice. The reason `valet unsecure` doesn't work for us is that some of the third-party APIs and redirects that we needed to accommodate will not redirect to an `http` site, they require `https`. Because of that, we have everything set up to just use `https` all the time. If it weren't for that, we could skip this altogether. Maybe it's not an edge case. I think it's pretty much what happens when you have 1000 linked things working together.

**Comment by mattstauffer** [comment]
@mcblum @drbyte This totally makes sense.

**Comment by sjelfull** [comment]
At this point, I think this consists of two different problems:
- Make the redirect optional, so that you can use `valet share` with it. _It seems to me neither ngrok, localtunnel or any other solution is able to connect to a secure host with self-signed certificate_
- Add support for paid ngrok accounts, which allows you to use reserved subdomains and https.

_Some nitpicking: How do you feel about calling the parameter `valet secure --optional` instead of `valet secure --not-redirected`? Either works for me, I just think --optional is nicer to type, and I've never liked dash-separated parameters/ones prefixed with negative words like `not`._

**Comment by drbyte** [comment]
Since this was mostly geared around ngrok, #630 resolves this for me.

**Comment by drbyte** [comment]
@mcblum @mattstauffer I believe this can be closed.
