### ISSUE TITLE
Sites must use HTTPS in macOS High Sierra 10.13.2

### ISSUE THREAD

**Issue by eriktobben** [laravel/valet#508]
Hi,

After updating macOS to the latest version I now need to serve sites with https. Is there any way around this?

**Comment by lauhakari** [comment]
Are your sites using .dev as the top domain?

If so this is a Chrome problem, Google owns .dev and are forcing them to https. You read more #436 for example. I suggest changing your valet domains to .test, .localhost or some other reserved one. Valet comes with .test now as fas as I know. :)

**Comment by eriktobben** [comment]
I was under the impression that this was only in Chrome, but I am using Safari. Maybe they have done the same?

**Comment by ChadTaljaardt** [comment]
im assuming most browsers will start forcing https on the .dev domain.

**Comment by jrmd** [comment]
This happens in most browsers due to them all using the same HSTS list, basically a list of domains to force SSL on.

**Comment by eriktobben** [comment]
Okey. Thanks for clarifying :)
