### ISSUE TITLE
Valet secure not working

### ISSUE THREAD

**Issue by peterfigwall** [laravel/valet#509]
When I run valet secure, my URL and SSL column on valet links table stays with HTTP and not checked for SSL. I'm using .test on Sierra and I have the last version of valet installed with certificates valid so I don't know what is the problem. This is causing me serious problems in my development because when I do curl or file_get_contents, I always get _ssl3_get_server_certificate:certificate verify failed_ and I can't change all my php code to ignore this. Any idea?

**Comment by drbyte** [comment]
You might want to try out the proposed change in #495 for file: `~/.composer/vendor/laravel/valet/cli/Valet/Site.php`

https://github.com/laravel/valet/pull/495/files

**Comment by mattstauffer** [comment]
@peterfigwall Does this work now that #495 is merged?

**Comment by drbyte** [comment]
I believe this is resolved.
