### ISSUE TITLE
In High Sierra, on a new install, ping domain.test works but curl fails

### ISSUE THREAD

**Issue by jonathanstegall** [laravel/valet#511]
I'm running High Sierra (I previously had a local Apache install using dnsmasq, so this could be related). I've tried running valet with the default and with the dev-master. I've tried:

1. Removing /Library/LaunchDaemons/co.echo.httpdfwd (this was previously used to forward port 80 to port 8080.
2. Reinstalling valet
- valet uninstall
- rm -rf ~/.valet
- valet install
- valet park (in ~/Sites)

I ran laravel new blog to create an empty Laravel site inside ~/Sites. When I run `brew services list`, I get this:

```
postgresql started root /Library/LaunchDaemons/homebrew.mxcl.postgresql.plist
redis      started root /Library/LaunchDaemons/homebrew.mxcl.redis.plist
php56      started root /Library/LaunchDaemons/homebrew.mxcl.php56.plist
memcached  started root /Library/LaunchDaemons/homebrew.mxcl.memcached.plist
php71      started root /Library/LaunchDaemons/homebrew.mxcl.php71.plist
httpd      stopped      
php70      started root /Library/LaunchDaemons/homebrew.mxcl.php70.plist
nginx      started root /Library/LaunchDaemons/homebrew.mxcl.nginx.plist
mysql      started root /Library/LaunchDaemons/homebrew.mxcl.mysql.plist
php53      started root /Library/LaunchDaemons/homebrew.mxcl.php53.plist
dnsmasq    started root /Library/LaunchDaemons/homebrew.mxcl.dnsmasq.plist
```

In `~/.valet/dnsmasq.conf`, I can see:

```
address=/.test/127.0.0.1
listen-address=127.0.0.1
```

Running `dig blog.test @127.0.0.1` returns:

```
; <<>> DiG 9.9.7-P3 <<>> blog.test @127.0.0.1
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 46359
;; flags: qr aa rd ra ad; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;blog.test.			IN	A

;; ANSWER SECTION:
blog.test.		0	IN	A	127.0.0.1

;; Query time: 1 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Thu Jan 18 10:30:06 CST 2018
;; MSG SIZE  rcvd: 43
```

Inside `/etc/resolver` there is a `test` file that contains `nameserver 127.0.0.1`.

`Ping blog.test` returns:

```
PING blog.test (127.0.0.1): 56 data bytes
64 bytes from 127.0.0.1: icmp_seq=0 ttl=64 time=0.057 ms
64 bytes from 127.0.0.1: icmp_seq=1 ttl=64 time=0.074 ms
64 bytes from 127.0.0.1: icmp_seq=2 ttl=64 time=0.080 ms
64 bytes from 127.0.0.1: icmp_seq=3 ttl=64 time=0.126 ms
```

Opening in the browser is not working, so I ran `curl blog.test --verbose`:

```
* Rebuilt URL to: blog.test/
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connection failed
* connect to 127.0.0.1 port 80 failed: Connection refused
* Failed to connect to blog.test port 80: Connection refused
* Closing connection 0
curl: (7) Failed to connect to blog.test port 80: Connection refused
```

What else should I be investigating? I thought it must be a conflict with the previous Apache or its use of dnsmasq, but I'm not sure how to proceed.

**Comment by jonathanstegall** [comment]
Well, it seems like maybe I just had to restart my Mac, although I had previously tried this a couple of times. Maybe one of the subsequent steps did it. Here's what I did after posting the above:

- `brew uninstall dnsmasq`
- `brew uninstall nginx`
- `sudo rm -rf /usr/local/etc/nginx`
- `composer global remove laravel/valet`
- `brew install homebrew/php/php71`
- `composer global require laravel/valet`
- `valet install`
- `valet park`

I think here is where I restarted, since nothing else was working, but it's possible I was in the middle somewhere. After this, curl and ping worked successfully and I was able to open both http and https in the browser.

**Comment by drbyte** [comment]
It could be that `dnsmasq` was waiting for another process to release something it needed to bind to ... which sometimes only a reboot will allow.  You mentioned Apache having been in use before and that it might be conflicting: yes, it's possible. 

Glad you sorted it out!

If this issue is resolved, please click Close below.
