### ISSUE TITLE
Is there a way to increase line length in the ngnix log?

### ISSUE THREAD

**Issue by benlk** [laravel/valet#512]
When running `tail -f ~/.valet/Log/nginx-error.log`, long PHP error messages are frequently cut off before being bundled into a single ngnix error message. See the following log entry: 

```
2018/01/26 17:14:16 [error] 210#0: *15654 FastCGI sent in stderr: "PHP message: ''
PHP message: array (
  '^wp-json/?$' => 'index.php?rest_route=/',
  '^wp-json/(.*)?' => 'index.php?rest_route=/$matches[1]',
  '^index.php/wp-json/?$' => 'index.php?rest_route=/',
  '^index.php/wp-json/(.*)?' => 'index.php?rest_route=/$matches[1]',
  'roundup/?$' => 'index.php?post_type=roundup',
  'roundup/feed/(feed|rdf|rss|rss2|atom|fulltext|mailchimp)/?$' => 'index.php?post_type=roundup&feed=$matches[1]',
  'roundup/(feed|rdf|rss|rss2|atom|fulltext|mailchimp)/?$' => 'index.php?post_type=roundup&feed=$matches[1]',
  'roundup/page/([0-9]{1,})/?$' => 'index.php?post_type=roundup&paged=$matches[1]',
  'rounduplink/?$' => 'index.php?post_type=rounduplink',
  'rounduplink/feed/(feed|rdf|rss|rss2|atom|fulltext|mailchimp)/?$' => 'index.php?post_type=rounduplink&feed=$matches[1]',
  'rounduplink/(feed|rdf|rss|rss2|atom|fulltext|mailchimp)/?$' => 'index.php?post_type=rounduplink&feed=$matches[1]',
  'rounduplink/page/([0-9]{1,})/?$' => 'index.php?post_type=rounduplink&paged=$matches[1]',
  'category/(.+?)/feed/...
PHP message: 'continued to here'" while reading upstream, client: 127.0.0.1, server: usenergynews.test, request: "GET /wp-admin/post.php?post=1092764&action=edit&message=1 HTTP/2.0", upstream: "fastcgi://unix:/Users/blk/.valet/valet.sock:", host: "usenergynews.test", referrer: "https://usenergynews.test/wp-admin/post.php?post=1092764&action=edit"
```

There are three separate PHP messages in this log, but the third one, containing a large array, is truncated with an unceremonious `...`. Is there a way to get valet or its ngnix or its php to *not* do that?

Thanks,

**Comment by drbyte** [comment]
Aren't those `PHP message` segments coming from your application's error handling? 
I'm not convinced this is an nginx log issue.

**Comment by benlk** [comment]
The conclusion to this ticket, which I apparently didn't save as a comment, was that the php-fpm module that the ngnix server (that valet is using) is using has a max line length of 1024, as evidenced by the second "PHP message" chunk of this ngnix log being 1024 characters including the trailing newline and the truncating ellipsis. php-fpm ignores the line length set in that PHP version's `php.ini` and uses a line length that is for some reason set at compile time.

Were I willing to recompile php-fpm, I would be limited by the max line length of 2048 chars set in ngnix, which is likewise set at compile time.

And I am unwilling to recompile half my dev environment at this time.

**Comment by benlk** [comment]
For those of you wanting more details: https://forums.freebsd.org/threads/howto-stop-nginx-php-fpm-from-truncating-your-stack-trace-error-message.56543/
