### ISSUE TITLE
Cannot download the larval/valet

### ISSUE THREAD

**Issue by Tamasneedhelp** [laravel/valet#518]
Hey guys,

I recently installed php 7.1.12 on my mac (high sierra), composer 1.5.5, laravel/installer, and now I'm trying to install laravel/valet to no avail. Below is the output I'm getting. Any ideas?

`composer global require laravel/valet
Changed current directory to /Users/brad/.composer
Using version ^2.0 for laravel/valet
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

Problem 1
- Conclusion: don't install symfony/process v3.4.2
- Conclusion: don't install laravel/valet v2.0.6
- Conclusion: remove symfony/process v4.0.2
- Conclusion: don't install symfony/process v3.4.1
- Conclusion: don't install laravel/valet v2.0.5
- Conclusion: don't install laravel/valet v2.0.4
- Conclusion: don't install laravel/valet v2.0.5|don't install symfony/process v4.0.2|install symfony/process v2.7.0|install symfony/process v2.7.1|install symfony/process v2.7.10|install symfony/process v2.7.11|install symfony/process v2.7.12|install symfony/process v2.7.13|install symfony/process v2.7.14|install symfony/process v2.7.15|install symfony/process v2.7.16|install symfony/process v2.7.17|install symfony/process v2.7.18|install symfony/process v2.7.19|install symfony/process v2.7.2|install symfony/process v2.7.20|install symfony/process v2.7.21|install symfony/process v2.7.22|install symfony/process v2.7.23|install symfony/process v2.7.24|install symfony/process v2.7.25|install symfony/process v2.7.26|install symfony/process v2.7.27|install symfony/process v2.7.28|install symfony/process v2.7.29|install symfony/process v2.7.3|install symfony/process v2.7.30|install symfony/process v2.7.31|install symfony/process v2.7.32|install symfony/process v2.7.33|install symfony/process v2.7.34|install symfony/process v2.7.35|install symfony/process v2.7.36|install symfony/process v2.7.37|install symfony/process v2.7.38|install symfony/process v2.7.39|install symfony/process v2.7.4|install symfony/process v2.7.5|install symfony/process v2.7.6|install symfony/process v2.7.7|install symfony/process v2.7.8|install symfony/process v2.7.9|install symfony/process v2.8.0|install symfony/process v2.8.1|install symfony/process v2.8.10|install symfony/process v2.8.11|install symfony/process v2.8.12|install symfony/process v2.8.13|install symfony/process v2.8.14|install symfony/process v2.8.15|install symfony/process v2.8.16|install symfony/process v2.8.17|install symfony/process v2.8.18|install symfony/process v2.8.19|install symfony/process v2.8.2|install symfony/process v2.8.20|install symfony/process v2.8.21|install symfony/process v2.8.22|install symfony/process v2.8.23|install symfony/process v2.8.24|install symfony/process v2.8.25|install symfony/process v2.8.26|install symfony/process v2.8.27|install symfony/process v2.8.28|install symfony/process v2.8.29|install symfony/process v2.8.3|install symfony/process v2.8.30|install symfony/process v2.8.31|install symfony/process v2.8.32|install symfony/process v2.8.4|install symfony/process v2.8.5|install symfony/process v2.8.6|install symfony/process v2.8.7|install symfony/process v2.8.8|install symfony/process v2.8.9|install symfony/process v3.0.0|install symfony/process v3.0.1|install symfony/process v3.0.2|install symfony/process v3.0.3|install symfony/process v3.0.4|install symfony/process v3.0.5|install symfony/process v3.0.6|install symfony/process v3.0.7|install symfony/process v3.0.8|install symfony/process v3.0.9|install symfony/process v3.1.0|install symfony/process v3.1.1|install symfony/process v3.1.10|install symfony/process v3.1.2|install symfony/process v3.1.3|install symfony/process v3.1.4|install symfony/process v3.1.5|install symfony/process v3.1.6|install symfony/process v3.1.7|install symfony/process v3.1.8|install symfony/process v3.1.9|install symfony/process v3.2.0|install symfony/process v3.2.1|install symfony/process v3.2.10|install symfony/process v3.2.11|install symfony/process v3.2.12|install symfony/process v3.2.13|install symfony/process v3.2.14|install symfony/process v3.2.2|install symfony/process v3.2.3|install symfony/process v3.2.4|install symfony/process v3.2.5|install symfony/process v3.2.6|install symfony/process v3.2.7|install symfony/process v3.2.8|install symfony/process v3.2.9
- Installation request for symfony/console (locked at v4.0.2) -> satisfiable by symfony/console[v4.0.2].
- Conclusion: don't install symfony/process v4.0.2
- laravel/valet v2.0.3 requires symfony/process ~2.7|~3.0 -> satisfiable by symfony/process[v2.7.0, v2.7.1, v2.7.10, v2.7.11, v2.7.12, v2.7.13, v2.7.14, v2.7.15, v2.7.16, v2.7.17, v2.7.18, v2.7.19, v2.7.2, v2.7.20, v2.7.21, v2.7.22, v2.7.23, v2.7.24, v2.7.25, v2.7.26, v2.7.27, v2.7.28, v2.7.29, v2.7.3, v2.7.30, v2.7.31, v2.7.32, v2.7.33, v2.7.34, v2.7.35, v2.7.36, v2.7.37, v2.7.38, v2.7.39, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.8.0, v2.8.1, v2.8.10, v2.8.11, v2.8.12, v2.8.13, v2.8.14, v2.8.15, v2.8.16, v2.8.17, v2.8.18, v2.8.19, v2.8.2, v2.8.20, v2.8.21, v2.8.22, v2.8.23, v2.8.24, v2.8.25, v2.8.26, v2.8.27, v2.8.28, v2.8.29, v2.8.3, v2.8.30, v2.8.31, v2.8.32, v2.8.4, v2.8.5, v2.8.6, v2.8.7, v2.8.8, v2.8.9, v3.0.0, v3.0.1, v3.0.2, v3.0.3, v3.0.4, v3.0.5, v3.0.6, v3.0.7, v3.0.8, v3.0.9, v3.1.0, v3.1.1, v3.1.10, v3.1.2, v3.1.3, v3.1.4, v3.1.5, v3.1.6, v3.1.7, v3.1.8, v3.1.9, v3.2.0, v3.2.1, v3.2.10, v3.2.11, v3.2.12, v3.2.13, v3.2.14, v3.2.2, v3.2.3, v3.2.4, v3.2.5, v3.2.6, v3.2.7, v3.2.8, v3.2.9, v3.3.0, v3.3.1, v3.3.10, v3.3.11, v3.3.12, v3.3.13, v3.3.14, v3.3.2, v3.3.3, v3.3.4, v3.3.5, v3.3.6, v3.3.7, v3.3.8, v3.3.9, v3.4.0, v3.4.1, v3.4.2].
- laravel/valet v2.0.1 requires symfony/process ~2.7|~3.0 -> satisfiable by symfony/process[v2.7.0, v2.7.1, v2.7.10, v2.7.11, v2.7.12, v2.7.13, v2.7.14, v2.7.15, v2.7.16, v2.7.17, v2.7.18, v2.7.19, v2.7.2, v2.7.20, v2.7.21, v2.7.22, v2.7.23, v2.7.24, v2.7.25, v2.7.26, v2.7.27, v2.7.28, v2.7.29, v2.7.3, v2.7.30, v2.7.31, v2.7.32, v2.7.33, v2.7.34, v2.7.35, v2.7.36, v2.7.37, v2.7.38, v2.7.39, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.8.0, v2.8.1, v2.8.10, v2.8.11, v2.8.12, v2.8.13, v2.8.14, v2.8.15, v2.8.16, v2.8.17, v2.8.18, v2.8.19, v2.8.2, v2.8.20, v2.8.21, v2.8.22, v2.8.23, v2.8.24, v2.8.25, v2.8.26, v2.8.27, v2.8.28, v2.8.29, v2.8.3, v2.8.30, v2.8.31, v2.8.32, v2.8.4, v2.8.5, v2.8.6, v2.8.7, v2.8.8, v2.8.9, v3.0.0, v3.0.1, v3.0.2, v3.0.3, v3.0.4, v3.0.5, v3.0.6, v3.0.7, v3.0.8, v3.0.9, v3.1.0, v3.1.1, v3.1.10, v3.1.2, v3.1.3, v3.1.4, v3.1.5, v3.1.6, v3.1.7, v3.1.8, v3.1.9, v3.2.0, v3.2.1, v3.2.10, v3.2.11, v3.2.12, v3.2.13, v3.2.14, v3.2.2, v3.2.3, v3.2.4, v3.2.5, v3.2.6, v3.2.7, v3.2.8, v3.2.9, v3.3.0, v3.3.1, v3.3.10, v3.3.11, v3.3.12, v3.3.13, v3.3.14, v3.3.2, v3.3.3, v3.3.4, v3.3.5, v3.3.6, v3.3.7, v3.3.8, v3.3.9, v3.4.0, v3.4.1, v3.4.2].
- laravel/valet v2.0.0 requires symfony/process ~2.7|~3.0 -> satisfiable by symfony/process[v2.7.0, v2.7.1, v2.7.10, v2.7.11, v2.7.12, v2.7.13, v2.7.14, v2.7.15, v2.7.16, v2.7.17, v2.7.18, v2.7.19, v2.7.2, v2.7.20, v2.7.21, v2.7.22, v2.7.23, v2.7.24, v2.7.25, v2.7.26, v2.7.27, v2.7.28, v2.7.29, v2.7.3, v2.7.30, v2.7.31, v2.7.32, v2.7.33, v2.7.34, v2.7.35, v2.7.36, v2.7.37, v2.7.38, v2.7.39, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.8.0, v2.8.1, v2.8.10, v2.8.11, v2.8.12, v2.8.13, v2.8.14, v2.8.15, v2.8.16, v2.8.17, v2.8.18, v2.8.19, v2.8.2, v2.8.20, v2.8.21, v2.8.22, v2.8.23, v2.8.24, v2.8.25, v2.8.26, v2.8.27, v2.8.28, v2.8.29, v2.8.3, v2.8.30, v2.8.31, v2.8.32, v2.8.4, v2.8.5, v2.8.6, v2.8.7, v2.8.8, v2.8.9, v3.0.0, v3.0.1, v3.0.2, v3.0.3, v3.0.4, v3.0.5, v3.0.6, v3.0.7, v3.0.8, v3.0.9, v3.1.0, v3.1.1, v3.1.10, v3.1.2, v3.1.3, v3.1.4, v3.1.5, v3.1.6, v3.1.7, v3.1.8, v3.1.9, v3.2.0, v3.2.1, v3.2.10, v3.2.11, v3.2.12, v3.2.13, v3.2.14, v3.2.2, v3.2.3, v3.2.4, v3.2.5, v3.2.6, v3.2.7, v3.2.8, v3.2.9, v3.3.0, v3.3.1, v3.3.10, v3.3.11, v3.3.12, v3.3.13, v3.3.14, v3.3.2, v3.3.3, v3.3.4, v3.3.5, v3.3.6, v3.3.7, v3.3.8, v3.3.9, v3.4.0, v3.4.1, v3.4.2].
- Can only install one of: symfony/process[v3.0.0, v4.0.2].
- Can only install one of: symfony/process[v3.0.1, v4.0.2].
- Can only install one of: symfony/process[v3.0.2, v4.0.2].
- Can only install one of: symfony/process[v3.0.3, v4.0.2].
- Can only install one of: symfony/process[v3.0.4, v4.0.2].
- Can only install one of: symfony/process[v3.0.5, v4.0.2].
- Can only install one of: symfony/process[v3.0.6, v4.0.2].
- Can only install one of: symfony/process[v3.0.7, v4.0.2].
- Can only install one of: symfony/process[v3.0.8, v4.0.2].
- Can only install one of: symfony/process[v3.0.9, v4.0.2].
- Can only install one of: symfony/process[v3.1.0, v4.0.2].
- Can only install one of: symfony/process[v3.1.1, v4.0.2].
- Can only install one of: symfony/process[v3.1.10, v4.0.2].
- Can only install one of: symfony/process[v3.1.2, v4.0.2].
- Can only install one of: symfony/process[v3.1.3, v4.0.2].
- Can only install one of: symfony/process[v3.1.4, v4.0.2].
- Can only install one of: symfony/process[v3.1.5, v4.0.2].
- Can only install one of: symfony/process[v3.1.6, v4.0.2].
- Can only install one of: symfony/process[v3.1.7, v4.0.2].
- Can only install one of: symfony/process[v3.1.8, v4.0.2].
- Can only install one of: symfony/process[v3.1.9, v4.0.2].
- Can only install one of: symfony/process[v3.2.0, v4.0.2].
- Can only install one of: symfony/process[v3.2.1, v4.0.2].
- Can only install one of: symfony/process[v3.2.10, v4.0.2].
- Can only install one of: symfony/process[v3.2.11, v4.0.2].
- Can only install one of: symfony/process[v3.2.12, v4.0.2].
- Can only install one of: symfony/process[v3.2.13, v4.0.2].
- Can only install one of: symfony/process[v3.2.14, v4.0.2].
- Can only install one of: symfony/process[v3.2.2, v4.0.2].
- Can only install one of: symfony/process[v3.2.3, v4.0.2].
- Can only install one of: symfony/process[v3.2.4, v4.0.2].
- Can only install one of: symfony/process[v3.2.5, v4.0.2].
- Can only install one of: symfony/process[v3.2.6, v4.0.2].
- Can only install one of: symfony/process[v3.2.7, v4.0.2].
- Can only install one of: symfony/process[v3.2.8, v4.0.2].
- Can only install one of: symfony/process[v3.2.9, v4.0.2].
- Can only install one of: symfony/process[v3.3.0, v4.0.2].
- Can only install one of: symfony/process[v3.3.1, v4.0.2].
- Can only install one of: symfony/process[v3.3.10, v4.0.2].
- Can only install one of: symfony/process[v3.3.11, v4.0.2].
- Can only install one of: symfony/process[v3.3.12, v4.0.2].
- Can only install one of: symfony/process[v3.3.13, v4.0.2].
- Can only install one of: symfony/process[v3.3.14, v4.0.2].
- Can only install one of: symfony/process[v3.3.2, v4.0.2].
- Can only install one of: symfony/process[v3.3.3, v4.0.2].
- Can only install one of: symfony/process[v3.3.4, v4.0.2].
- Can only install one of: symfony/process[v3.3.5, v4.0.2].
- Can only install one of: symfony/process[v3.3.6, v4.0.2].
- Can only install one of: symfony/process[v3.3.7, v4.0.2].
- Can only install one of: symfony/process[v3.3.8, v4.0.2].
- Can only install one of: symfony/process[v3.3.9, v4.0.2].
- Can only install one of: symfony/process[v3.4.0, v4.0.2].
- Can only install one of: symfony/process[v2.7.0, v4.0.2].
- Can only install one of: symfony/process[v2.7.1, v4.0.2].
- Can only install one of: symfony/process[v2.7.10, v4.0.2].
- Can only install one of: symfony/process[v2.7.11, v4.0.2].
- Can only install one of: symfony/process[v2.7.12, v4.0.2].
- Can only install one of: symfony/process[v2.7.13, v4.0.2].
- Can only install one of: symfony/process[v2.7.14, v4.0.2].
- Can only install one of: symfony/process[v2.7.15, v4.0.2].
- Can only install one of: symfony/process[v2.7.16, v4.0.2].
- Can only install one of: symfony/process[v2.7.17, v4.0.2].
- Can only install one of: symfony/process[v2.7.18, v4.0.2].
- Can only install one of: symfony/process[v2.7.19, v4.0.2].
- Can only install one of: symfony/process[v2.7.2, v4.0.2].
- Can only install one of: symfony/process[v2.7.20, v4.0.2].
- Can only install one of: symfony/process[v2.7.21, v4.0.2].
- Can only install one of: symfony/process[v2.7.22, v4.0.2].
- Can only install one of: symfony/process[v2.7.23, v4.0.2].
- Can only install one of: symfony/process[v2.7.24, v4.0.2].
- Can only install one of: symfony/process[v2.7.25, v4.0.2].
- Can only install one of: symfony/process[v2.7.26, v4.0.2].
- Can only install one of: symfony/process[v2.7.27, v4.0.2].
- Can only install one of: symfony/process[v2.7.28, v4.0.2].
- Can only install one of: symfony/process[v2.7.29, v4.0.2].
- Can only install one of: symfony/process[v2.7.3, v4.0.2].
- Can only install one of: symfony/process[v2.7.30, v4.0.2].
- Can only install one of: symfony/process[v2.7.31, v4.0.2].
- Can only install one of: symfony/process[v2.7.32, v4.0.2].
- Can only install one of: symfony/process[v2.7.33, v4.0.2].
- Can only install one of: symfony/process[v2.7.34, v4.0.2].
- Can only install one of: symfony/process[v2.7.35, v4.0.2].
- Can only install one of: symfony/process[v2.7.36, v4.0.2].
- Can only install one of: symfony/process[v2.7.37, v4.0.2].
- Can only install one of: symfony/process[v2.7.38, v4.0.2].
- Can only install one of: symfony/process[v2.7.39, v4.0.2].
- Can only install one of: symfony/process[v2.7.4, v4.0.2].
- Can only install one of: symfony/process[v2.7.5, v4.0.2].
- Can only install one of: symfony/process[v2.7.6, v4.0.2].
- Can only install one of: symfony/process[v2.7.7, v4.0.2].
- Can only install one of: symfony/process[v2.7.8, v4.0.2].
- Can only install one of: symfony/process[v2.7.9, v4.0.2].
- Can only install one of: symfony/process[v2.8.0, v4.0.2].
- Can only install one of: symfony/process[v2.8.1, v4.0.2].
- Can only install one of: symfony/process[v2.8.10, v4.0.2].
- Can only install one of: symfony/process[v2.8.11, v4.0.2].
- Can only install one of: symfony/process[v2.8.12, v4.0.2].
- Can only install one of: symfony/process[v2.8.13, v4.0.2].
- Can only install one of: symfony/process[v2.8.14, v4.0.2].
- Can only install one of: symfony/process[v2.8.15, v4.0.2].
- Can only install one of: symfony/process[v2.8.16, v4.0.2].
- Can only install one of: symfony/process[v2.8.17, v4.0.2].
- Can only install one of: symfony/process[v2.8.18, v4.0.2].
- Can only install one of: symfony/process[v2.8.19, v4.0.2].
- Can only install one of: symfony/process[v2.8.2, v4.0.2].
- Can only install one of: symfony/process[v2.8.20, v4.0.2].
- Can only install one of: symfony/process[v2.8.21, v4.0.2].
- Can only install one of: symfony/process[v2.8.22, v4.0.2].
- Can only install one of: symfony/process[v2.8.23, v4.0.2].
- Can only install one of: symfony/process[v2.8.24, v4.0.2].
- Can only install one of: symfony/process[v2.8.25, v4.0.2].
- Can only install one of: symfony/process[v2.8.26, v4.0.2].
- Can only install one of: symfony/process[v2.8.27, v4.0.2].
- Can only install one of: symfony/process[v2.8.28, v4.0.2].
- Can only install one of: symfony/process[v2.8.29, v4.0.2].
- Can only install one of: symfony/process[v2.8.3, v4.0.2].
- Can only install one of: symfony/process[v2.8.30, v4.0.2].
- Can only install one of: symfony/process[v2.8.31, v4.0.2].
- Can only install one of: symfony/process[v2.8.32, v4.0.2].
- Can only install one of: symfony/process[v2.8.4, v4.0.2].
- Can only install one of: symfony/process[v2.8.5, v4.0.2].
- Can only install one of: symfony/process[v2.8.6, v4.0.2].
- Can only install one of: symfony/process[v2.8.7, v4.0.2].
- Can only install one of: symfony/process[v2.8.8, v4.0.2].
- Can only install one of: symfony/process[v2.8.9, v4.0.2].
- Installation request for symfony/process (locked at v4.0.2) -> satisfiable by symfony/process[v4.0.2].
- Installation request for laravel/valet ^2.0 -> satisfiable by laravel/valet[v2.0.0, v2.0.1, v2.0.3, v2.0.4, v2.0.5, v2.0.6].

Installation failed, reverting ./composer.json to its original content.`

**Comment by adamwathan** [comment]
Global Composer dependencies all share the same vendor directory, so it's extremely easy to run into conflicts that actually don't matter which is what you're seeing here.

I'd recommend using [cgr](https://github.com/consolidation/cgr/) to manage your global dependencies so they all get their own isolated vendor dependencies which will fix this for you.

**Comment by bloggervista** [comment]
I guess its fixed . you can close it :)

**Comment by sebsel** [comment]
I'm having this issue too... even with my global composer folder empty (on a second user account). Now I deleted it from my main account and I can't reinstall it. :(

Are you sure there's nothing to do to fix it in valet?

Note: my composer squawks at symfony/process v4.0.4, not v4.0.2. Seems like they are updating things?

**Comment by drbyte** [comment]
You have something in your global composer.json which is requiring/using a specific version of symfony/process that's not compatible with other dependencies. 

Using `cgr` as mentioned above typically removes these version clashes.

Investigation steps:
1. What's in your `~/.composer/composer.json` file?  Anything there you don't really need? 
2. Delete your `~/.composer/cache` and `~/.composer/vendor` folders, and run `composer global update`

**Comment by sebsel** [comment]
Ah, of course it's a cache. I would close it again if it wasn't closed already. Thanks!
