### ISSUE TITLE
Having issues with SSL

### ISSUE THREAD

**Issue by lstables** [laravel/valet#519]
My valet install is messed up for some reason, every time I add new sites to my code directory and go to add a new SSL cert it doesn't work.

Having done such commands like:

````
valet stop
brew services stop nginx
brew services stop dnsmasq
composer remove laravel/valet
brew reinstall dnsmasq
brew reinstall nginx
composer global require laravel/valet
valet install
valet domain test
````

But still sites don't work in any browser

**Comment by drbyte** [comment]
> sites don't work in any browser

Can you be more specific?
Do you mean the sites "don't respond"?
or "get an invalid certificate error"?

What's the exact error?

What Operating System?

**Comment by lstables** [comment]
````
This site can’t be reached
quill.test refused to connect.
Try:

Checking the connection
Checking the proxy and the firewall
ERR_CONNECTION_REFUSED
````

MacOS

**Comment by drbyte** [comment]
Which version of MacOS? 

What do you get from running `dig quill.test` ?

What's the result of running the following?
`sudo /usr/local/opt/nginx/bin/nginx -t`
(this will ask nginx to report on any errors in your nginx configs)

What errors are recorded in `/usr/local/var/log/nginx/error.log` ?

**Comment by lstables** [comment]
For some reason, I have uninstalled everything (or so I thought) reinstalled everything and the restarted my macbook and it worked. Seems a bit crappy that every time I add a new site and do `valet secure newsite` I have to restart though.

**Comment by drbyte** [comment]
Agreed: that's not normally necessary. Sounds like nginx isn't restarting properly (without errors).

It would be revealing to know the output of `sudo /usr/local/opt/nginx/bin/nginx -t` when those symptoms occur again.

**Comment by mattstauffer** [comment]
Please feel free to re-open if this comes up again. Thanks!
