### ISSUE TITLE
WSL/Bash on Windows?

### ISSUE THREAD

**Issue by strarsis** [laravel/valet#520]
It would be awesome if this works officially out of the box on WSL (Bash on Windows).

There are some forks existing already like 
https://github.com/valeryan/valet-wsl
https://github.com/huncrys/valet-wsl

**Comment by cretueusebiu** [comment]
I have a port for Windows [valet-windows](https://github.com/cretueusebiu/valet-windows). But only works if you install it directly on Windows, not through the Ubuntu subsystem.

**Comment by mattstauffer** [comment]
I don't believe that's in the intentions of the authors. Thanks!
