### ISSUE TITLE
Accessing Laravel Sites from Windows

### ISSUE THREAD

**Issue by rlated1337** [laravel/valet#524]
Hi!
For some reason I can't reach my Laravel Sites. I run Laravel on my Linux VM. Tried to edit my host file but still cant reach my sites. 
Any ideas what I could do?

Thanks.,

**Comment by drbyte** [comment]
@rlated1337 wrote:
>  I can't reach my Laravel Sites

Please explain in more detail. Do you get a `404` response? or a `500` response? or a `blue screen of death`? or something else?

Why did you post this as a Valet issue? What part does Valet play in this equation?

**Comment by rlated1337** [comment]
I'm trying to access it from my Windows PC. Valet runs on my VM.

**Comment by drbyte** [comment]
From the README:
> Valet is a Laravel development environment for **Mac**

@rlated1337 wrote:
>  I run Laravel on my Linux VM

I don't think this is a `laravel/valet` issue.

**Comment by drbyte** [comment]
I think this can be closed due to inactivity.

**Comment by drbyte** [comment]
Can be closed.
