### ISSUE TITLE
Is the v2.0.7 release considered stable?

### ISSUE THREAD

**Issue by nlenkowski** [laravel/valet#525]
The latest release is still v2.0.5 from July 28, 2017, while v2.0.7 was tagged on Feb 9, 2018 with 88 commits since master.

Is v2.0.7 considered stable or is v2.0.5 still the recommended release?

Also, huge thanks for building and maintaining Valet. It is by far the best PHP development environment for macOS 👍

**Comment by mattstauffer** [comment]
Yep, it's stable. :) (I can't take credit for your second half but can answer your first)

**Comment by nlenkowski** [comment]
Excellent, glad to hear! I'm going to give it a whirl on a fresh install of High Sierra.
