### ISSUE TITLE
PHP_SELF set to wrong value

### ISSUE THREAD

**Issue by DarrenTheDev** [laravel/valet#526]
I was chasing down a WordPress issue with missing images redirecting to the homepage, rather than returning a 404. During this I noticed that the PHP_SELF value that valet sets is different to the one returned by Apache. The PHP Docs define the variable as "The filename of the currently executing script, relative to the document root.", whereas the driver sets it to the incoming request URI. I believe that the correct way to set it in the driver would be:

`str_replace( $sitePath, '', $frontControllerPath );`

This could be done in Wordpress driver, but I think that it should actually be changed in the basic driver.

**Comment by r-martins** [comment]
Also check if you are really using the wordpress driver.
In my case, my blog was inside a magento project's directory, so it was using Magento's driver instead. Once I configured it properly, it worked.
