### ISSUE TITLE
Cannot view any Valet sites since upgrading to 2.0.8

### ISSUE THREAD

**Issue by Muzical84** [laravel/valet#531]
I asked for help with this in [Slack](https://larachat.slack.com/archives/C039F76DN/p1520299016000283), but all I got out of that was that I'd actually tried everything.  Since that page requires a login, I'll re-iterate:

- I've restarted the laptop.
- I've done `brew services restart` for the relevant services.
- I've done `valet restart`
- I've checked `valet links` and everything looks fine.
- `valet on-latest-version` returns YES
- I manually changed `valet domain` to use `.test` instead of `.dev`
- My output from `brew services list --all` is as follows:

```bash
Name       Status  User  Plist
postgresql started muzical /Users/muzical/Library/LaunchAgents/homebrew.mxcl.postgresql.plist
dbus       started muzical /Users/muzical/Library/LaunchAgents/homebrew.mxcl.dbus.plist
emacs      stopped       
memcached  started muzical /Users/muzical/Library/LaunchAgents/homebrew.mxcl.memcached.plist
php71      started root  /Library/LaunchDaemons/homebrew.mxcl.php71.plist
httpd      stopped       
tor        stopped       
nginx      started root  /Library/LaunchDaemons/homebrew.mxcl.nginx.plist
dnsmasq    started root  /Library/LaunchDaemons/homebrew.mxcl.dnsmasq.plist
```

FWIW, postgres and memcached print "started" as green; the other "started" services are yellow.

Since I had no luck viewing a newly parked domain, (I either get the same error that I get when I enter an invalid domain or Chrome sends the URL to my search engine...) I checked that one domain I had used (parked) before was still valid and tried to visit it.  Nothing.

I've also tried doing `valet uninstall`, removing it from my global `composer.json` file, running `composer update`, doing a new `global require` for Valet, etc., running `valet install` and so on _again_, and still nothing.

I'm running macOS High Sierra and have had this issue in Chrome, Firefox, etc.  I also cannot ping my `.test` domains.

If you read through all of this, thanks!  (Bonus if you can actually help... 😅 )

**Comment by drbyte** [comment]
Thanks for posting all those details. 

Which version of Valet did you upgrade from?  
Not sure exactly what you meant by "manually changed" when changing to .test TLD. Details would help.

If you're getting "invalid domain" or cannot ping your `.test` domains, then that means dnsmasq isn't doing the resolving of DNS lookups. 
Perhaps using a custom dnsmasq config will help; I posted one here: https://github.com/laravel/valet/issues/115#issuecomment-241275816
And, if you use that then you can also get debug logs from dnsmasq to help diagnose why it's not working on your machine.

**Comment by Muzical84** [comment]
I believe I upgraded from the previous version, so 2.0.7, but I installed Valet for the first time a few months ago at most.  The current architecture was already there.

When I said "manually changed," I meant that I typed `valet domain test` since I saw the documentation was using .test and I didn't know if the new version was automatically making the switch or if that was the problem.  I knew Google had bought up a lot of the TLDs people had been using, so `.dev` wasn't going to work anymore.

I'll give this config a try and see what happens!  ty!

**Comment by drbyte** [comment]
> When I said "manually changed," I meant that I typed `valet domain test` 

Oh, good. The undesired alternative is manually editing the valet json config file .. but that doesn't take care of all the related steps that running `valet domain` will do. So you did that part correctly.

**Comment by Muzical84** [comment]
OK in good news, I'm just getting a 404 error when I load the site, and when I ping, I'm getting a request timeout, so I _think_ that's progress?  Also, thanks, @drbyte for that config; it even included workarounds for DNSCrypt, which I actually use and usually just disable when coding.

**Comment by josermorales** [comment]
@Muzical84 Did you managed to fix it? happened the same thing to me... I think it has something to do with the `homebrew/dupes` taps being empty (migrated).

I am trying to reinstall valet, but now it keeps trying to install `homebrew/dupes/php71` even tho there's nothing there and I have php72 on my system.

**Comment by drbyte** [comment]
I think this can be closed.
