### ISSUE TITLE
Clean install of Laravel 5.6 throws unknown line 0 error, http 500.

### ISSUE THREAD

**Issue by xron89** [laravel/valet#540]
I'm able to download my clean install of Laravel 5.6 successfully and run migration/artisan commands fine. However, trying to load the site in the browser simply throws a 500 error. 

From the NGIX error log I found this;
```2018/03/22 17:39:59 [error] 48661#0: *32 FastCGI sent in stderr: "PHP message: PHP Parse error:  syntax error, unexpected '?', expecting variable (T_VARIABLE) in /Users/sam/Laravel/blog/vendor/symfony/finder/Comparator/NumberComparator.php on line 42
PHP message: PHP Fatal error:  Exception thrown without a stack frame in Unknown on line 0
PHP message: PHP Parse error:  syntax error, unexpected '?', expecting variable (T_VARIABLE) in /Users/sam/Laravel/blog/vendor/symfony/finder/Comparator/NumberComparator.php on line 42
PHP message: PHP Fatal error:  Exception thrown without a stack frame in Unknown on line 0" while reading response header from upstream, client: 127.0.0.1, server: , request: "GET /register HTTP/1.1", upstream: "fastcgi://unix:/Users/sam/.valet/valet.sock:",$```

Using PHP version 7.1.7

Thanks

**Comment by drbyte** [comment]
Line 42 in that symfony file is:
```php
    public function __construct(?string $test)
```
Notice the `?string $test` parameter. That's the ["nullable type" feature introduced in PHP 7.1](http://php.net/manual/en/migration71.new-features.php)

Thus your error message is telling you that your Nginx is ACTUALLY using a PHP version older than PHP 7.1, regardless what your command-line PHP version is. 

Use:
`valet stop`
`brew services list`
For any PHP versions "still running", stop them with `brew services phpXX stop` (where `phpXX` is the service name in homebrew
`brew link php71`
`valet start`

Valet is dependent on you using the components it manages for you. If you do fancy things with your PHP/Nginx config other than what Valet does itself, then you need to take responsibility for fixing your configuration to be compatible with Valet.  There are dozens of very similar (now closed) issues here where you can learn from others.

**Comment by vusani** [comment]
For me, I had to do a `valet install` again

`valet install`

_Stopping nginx...
Installing nginx configuration...
Installing nginx directory...
Updating PHP configuration...
Restarting php...
Restarting dnsmasq...
Restarting nginx..._

Valet installed successfully!

**Comment by juanvillegas** [comment]
just a note on @drbyte comment, the correct command to stop a brew services would be `brew services <service_name> stop`. (_stop_ at the end)

**Comment by drbyte** [comment]
I think this can be closed due to inactivity.

As for resolution, to force PHP 5.6 with Valet, set your composer global config, as mentioned in https://github.com/laravel/valet/pull/535#issuecomment-401382906
