### ISSUE TITLE
Securing long domain names crash nginx

### ISSUE THREAD

**Issue by 0x6368** [laravel/valet#543]
When I create a long domain name (e.g. `valet link 12345678901234567890123456789012345678901234567890`) and then `valet secure 12345678901234567890123456789012345678901234567890`, I cannot reach any of my valet links any more, because nginx will not start any more.

To fix this, I have to `valet unsecure 12345678901234567890123456789012345678901234567890`.

I think valet should prevent securing such links.

**Comment by drbyte** [comment]
Confirmed. 
37 characters is the max that appears to work when running `valet secure`. Longer than that stops nginx from reloading properly. (Not a problem with `valet link` though.)

**Comment by drbyte** [comment]
Update: Workaround posted at: https://github.com/laravel/valet/issues/808#issuecomment-521651937

**Comment by drbyte** [comment]
This can be closed.
