### ISSUE TITLE
Homebrew changed how php is installed

### ISSUE THREAD

**Issue by clakeb** [laravel/valet#544]
I did a `brew update && brew upgrade` this morning and my valet environment broke. I am mostly using php71 and valet is now complaining that it is `Unable to determine linked PHP.`

I will try to fix it myself but I don't know if I have time this morning.

see [#4721](https://github.com/Homebrew/homebrew-php/issues/4721)

**Comment by appinteractive** [comment]
I have the same problem!

**Comment by tpharaoh** [comment]
brew list | grep php
brew unlink php7.1
brew link php7.2
sudo brew services restart php72
sudo brew services restart nginx

At least that worked for me.

**Comment by clakeb** [comment]
So I temporarily fixed this by modifying valet. In `$HOME/.composer/vendor/laravel/valet/cli/Valet/Brew.php` I added `php@7.1` to the array in the function `supportedPhpVersions()`, like so:
```php
    function supportedPhpVersions()
    {
        return collect(['php', 'php72', 'php71', 'php70', 'php56', 'php@7.1']);
    }
```
Then I modified `$HOME/.composer/vendor/laravel/valet/cli/Valet/PhpFpm.php`, function `fpmConfigPath()`, like so:
```php
function fpmConfigPath()
    {
        $confLookup = [
            'php' => '/usr/local/etc/php/7.2/php-fpm.d/www.conf',
            'php72' => '/usr/local/etc/php/7.2/php-fpm.d/www.conf',
            'php71' => '/usr/local/etc/php/7.1/php-fpm.d/www.conf',
            'php70' => '/usr/local/etc/php/7.0/php-fpm.d/www.conf',
            'php56' => '/usr/local/etc/php/5.6/php-fpm.conf',
            'php@7.1' => '/usr/local/etc/php/7.1/php-fpm.d/www.conf'
        ];

        return $confLookup[$this->brew->linkedPhp()];
    }
```
Then I symlinked the new `php@7.1`, `$ ln -s $(which php) /usr/local/bin/php`. I did a `valet install` after and this worked.

I know this is just a temporary workaround for me and I'll try to come up with a better solution. I hope this helps people get back to work today though.

**Comment by james2doyle** [comment]
Since `php71` and `php@7.1` are identical in terms of paths and all that, maybe sanitizing the version with something like `preg_replace('/php[@|\.]/', 'php', $this->brew->linkedPhp());` will fix this?

**Comment by epreston** [comment]
I'd recommend holding off on updating your php via brew.  It just downgraded me from php 7.1.14 or so to 7.1.7 in this whole package rename process.

**Comment by lakinmohapatra** [comment]
How to install imagick php 56

**Comment by epreston** [comment]
I submitted a pull request to address this issue. #549

**Comment by OwenMelbz** [comment]
Anybody having the issue with php 7.2 though? the fact its just now named php?

**Comment by epreston** [comment]
Adam addressed php version 7.2 (or above) being referenced as just "php" in commit 740d716cdd5ba7a55f8567f38b8d59185cd06e48

Only issue I've found is on test devices that are pinned to 7.2.

**Comment by epreston** [comment]
Expanding on the php-fpm modifications above, you'd also need to modify the taps and name of the default package installed for the install command to work when a brew version of php is not found.

The services list in the `stop` method should include the new service names as well.

I've added this to #564 

The instructions above should include a `valet install` to ensure the configuration is written / updated, and the required services are installed.

**Comment by afolabiabass** [comment]
@raveenasurani thank you so much, this solved the issue I was having

**Comment by drbyte** [comment]
Since homebrew has stabilized, this can probably be closed.
