### ISSUE TITLE
can't change domain .test to another

### ISSUE THREAD

**Issue by abdhannan** [laravel/valet#547]
The default domain for valet is .test
however, when I try to change it to another ex: valet domain app, it's not working on the browser, work again when reverting to.test

Can anyone help?

**Comment by kakajansh** [comment]
Google Chrome automatically redirects `.app`, `.dev` domains to secure `https`. So actually it is not issue with valet, but with Chrome. If you would run on Firefox it will work as expected. 

As a solution you should either use something like `.test`, `.site` or secure your apps with running `valet secure` in your project folder.

**Comment by adamwathan** [comment]
Yep like @kakajansh mentioned, we changed this to `test` specifically to skirt the issues with Chrome when using `dev` or `app`.
