### ISSUE TITLE
[DomainException] Unable to determine linked PHP.

### ISSUE THREAD

**Issue by physcocode** [laravel/valet#550]
There was a problem while using PHP71 despite all being fine valet could not detect it as valid version.
Then i noticed PHP71 is now php@7.1 adding php@7.1 to supported list solved my problem

**Comment by osindex** [comment]
same problem. 
btw, how to swich php version [ lastest valet(2.0.8) with current brew]?

**Comment by martisj** [comment]
Related to #544

**Comment by raveenasurani** [comment]
Hello guys,

I was having the same issue after knocking my head around i came upto this solution and its working perfectly .. Here you go 👍 

so Firstly, i install Brew  : **/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"**

Then i installed php71 which is now php@7.1 : **brew install php71**

-> after installation export :   **echo 'export PATH="/usr/local/opt/php@7.1/bin:$PATH"' >> ~/.bash_profile
  echo 'export PATH="/usr/local/opt/php@7.1/sbin:$PATH"' >> ~/.bash_profile**

-> **brew link php@7.1 --force --overwrite**

->**ln -s $(which php) /usr/local/bin/php**

Then i installed composer using :

 **php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
php -r "if (hash_file('SHA384', 'composer-setup.php') === '544e09ee996cdf60ece3804abc52599c22b1f40f4323403c44d44fdfdd586475ca9813a858088ffbc1f233e9b180f061') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
php composer-setup.php
php -r "unlink('composer-setup.php');"**

and **mv composer.phar /usr/local/bin/composer**

and then installed valet : **composer global require laravel/vale**t

And then comes the tricky part : 

-> **open -e /Users/USERNAME-Directory/.composer/vendor/laravel/valet/cli/Valet/Brew.php**

and alter

 function supportedPhpVersions()
    {
        return collect(['php', 'php72', 'php71', 'php70', 'php56',**'php@7.1'**]);
    }

-> **open -e /Users/USERNAME-Directory/.composer/vendor/laravel/valet/cli/Valet/PhpFpm.php** 

and alter

 function fpmConfigPath()
    {
        $confLookup = [
            'php' => '/usr/local/etc/php/7.2/php-fpm.d/www.conf',
            'php72' => '/usr/local/etc/php/7.2/php-fpm.d/www.conf',
            'php71' => '/usr/local/etc/php/7.1/php-fpm.d/www.conf',
            'php70' => '/usr/local/etc/php/7.0/php-fpm.d/www.conf',
            'php56' => '/usr/local/etc/php/5.6/php-fpm.conf',
 	    **'php@7.1' => '/usr/local/etc/php/7.1/php-fpm.d/www.conf'**
        ];

        return $confLookup[$this->brew->linkedPhp()];
    }

and then final step : **sudo brew services restart nginx && sudo brew services restart php@7.1**

And DONE!!!!

Cheers!!

**Comment by Oscarteg** [comment]
Structured it a little bit better:

so Firstly, i install Brew : 

`/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"`

Then i installed php71 which is now php@7.1 : 

`brew install php71`

-> after installation export : 
`echo 'export PATH="/usr/local/opt/php@7.1/bin:$PATH"' >> ~/.bash_profile`
`echo 'export PATH="/usr/local/opt/php@7.1/sbin:$PATH"' >> ~/.bash_profile`

`brew link php@7.1 --force --overwrite`

`ln -s $(which php) /usr/local/bin/php`

Then i installed composer using :
`brew install composer`

and then installed valet : 
`composer global require laravel/valet`

And then comes the tricky part:
`open -e /Users/USERNAME-Directory/.composer/vendor/laravel/valet/cli/Valet/Brew.php`

and alter
```
function supportedPhpVersions()
{
return collect(['php', 'php72', 'php71', 'php70', 'php56','php@7.1']);
}
```
`open -e /Users/USERNAME-Directory/.composer/vendor/laravel/valet/cli/Valet/PhpFpm.php`

and alter
```
function fpmConfigPath()
{
$confLookup = [
'php' => '/usr/local/etc/php/7.2/php-fpm.d/www.conf',
'php72' => '/usr/local/etc/php/7.2/php-fpm.d/www.conf',
'php71' => '/usr/local/etc/php/7.1/php-fpm.d/www.conf',
'php70' => '/usr/local/etc/php/7.0/php-fpm.d/www.conf',
'php56' => '/usr/local/etc/php/5.6/php-fpm.conf',
'php@7.1' => '/usr/local/etc/php/7.1/php-fpm.d/www.conf'
];

    return $confLookup[$this->brew->linkedPhp()];
}
```
and then final step : 
`sudo brew services restart nginx && sudo brew services restart php@7.1`

**Comment by drbyte** [comment]
Or upgrade to valet 2.0.12 which already has the necessary code changes to support the April changes made to Homebrew's PHP numbering.
https://github.com/laravel/valet/releases

This issue should be closed.

**Comment by SimonWang2014** [comment]
please update Valet to the latest version:

```
composer global update
```

**Comment by AK-PapaSoft** [comment]
My way to fix this was ti rewrite current php version: `brew link php@7.1 --force --overwrite`
That worked for me in similar case. If you have questions in the whole process - ping me as well. Probably, I can help ;)
