### ISSUE TITLE
Enable directory listing (autoindex on;) if there's no index file

### ISSUE THREAD

**Issue by vtimbuc** [laravel/valet#554]
Is it possible to enable directory listing if the project doesn't have an index file?

I've tried to add `autoindex on;` to the `nginx/valet/valet.conf` file http://bit.ly/2uLzgvL but it doesn't work, still get a 404 page http://bit.ly/2GE4w16.

Any help would be much appreciated, thanks.

**Comment by drbyte** [comment]
See the discussion on #610 for a workaround you can use for this.
