### ISSUE TITLE
Fresh install, PHP warnings when running any valet command, also Nginx 502 error

### ISSUE THREAD

**Issue by richpav** [laravel/valet#556]
Brand new Mac running 10.13.4.

Running any command, it's the same warnings:

```
$ valet secure
Warning: preg_replace() expects parameter 4 to be integer, string given in /Users/richpav/.composer/vendor/laravel/valet/cli/Valet/Brew.php on line 185
Warning: strpos() expects at least 2 parameters, 1 given in /Users/richpav/.composer/vendor/laravel/valet/cli/Valet/Brew.php on line 185
```

I completely uninstalled and deleted everything Composer and Valet related, reinstalled composer with Brew, ran the valet install but still getting the same errors.

And nginx/1.13.10 is throwing a 502 error. I see why, but I don't know how to fix it.

`2018/04/05 11:21:00 [crit] 217#0: *1 connect() to unix:/Users/richpav/.valet/valet.sock failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: test.dev, request: "GET /favicon.ico HTTP/2.0", upstream: "fastcgi://unix:/Users/richpav/.valet/valet.sock:", host: "test.dev", referrer: "https://test.dev/"`

which php says
```
$ which php
/usr/bin/php
```

**Comment by richpav** [comment]
I seemed to have fixed the 502 errors, probably by doing this. (I tried a lot of stuff and wasn't keeping track.)

$ brew install php
$ brew install php71
$ ln -s /usr/local/Cellar/php@7.1/7.1.16 /usr/local/Cellar/php/7.1.16
$ ln -s /usr/local/Cellar/php/7.1.16/bin/php /usr/local/bin/php
$ composer global update
$ valet install

I'm still getting the PHP warnings:

```
$ valet restart
PHP Warning:  preg_replace() expects parameter 4 to be integer, string given in /Users/richpav/.composer/vendor/laravel/valet/cli/Valet/Brew.php on line 185

Warning: preg_replace() expects parameter 4 to be integer, string given in /Users/richpav/.composer/vendor/laravel/valet/cli/Valet/Brew.php on line 185
PHP Warning:  strpos() expects at least 2 parameters, 1 given in /Users/richpav/.composer/vendor/laravel/valet/cli/Valet/Brew.php on line 185

Warning: strpos() expects at least 2 parameters, 1 given in /Users/richpav/.composer/vendor/laravel/valet/cli/Valet/Brew.php on line 185
Restarting php...
Restarting nginx...
Valet services have been restarted.

```

**Comment by nasrulhazim** [comment]
I receive the same warning message as you did [above](https://github.com/laravel/valet/issues/556#issuecomment-378812233).

**Comment by drbyte** [comment]
Now that the changes with Homebrew's rename of their PHP implementation is completed, this issue is probably resolved.

If one needs to force their CLI to use PHP 5.6 for some reason, they can set their global config to do that as described in 
https://github.com/laravel/valet/pull/535#issuecomment-401382906

**Comment by mattstauffer** [comment]
Closing unless it comes back up for anyone. Thanks @drbyte!
