### ISSUE TITLE
Ngrok share configs per directory

### ISSUE THREAD

**Issue by JacobBennett** [laravel/valet#557]
https://github.com/laravel/valet/blob/74e203e37b9549b364feda1920e91e3156f38ad9/valet#L32

Would be nice to be able to call `valet share` from any directory, and have valet check to see if there was a `.valet` file in that directory that would store some configs you could use to handle `valet share`.

If using a paid version of ngrok, you can set custom subdomains using a command similar to

```
valet share -suddomain=mysubdomain -region=us
```

if you could store the `subdomain` and the `region` in a `.valet` file per project and check for that when doing a valet share, would be able to drop the extra pieces after `valet share` and have it handled automatically.

sudo code:
```
if [ -f $PWD/.valet ]; then
    CUSTOM_SHARE=$(php "$DIR/cli/valet.php" ngrok_share)
fi
```

**Comment by drbyte** [comment]
I like this idea. 
Undecided what the right name for the config file should be. I think it should be more specific than just `.valet`.  `.valet-ngrok` perhaps?

**Comment by Harry-Harrison** [comment]
I think `.valet` is fine, personally.

**Comment by drbyte** [comment]
@JacobBennett did you ever do something with this?

**Comment by JacobBennett** [comment]
Never did no. Have at it! :)

**Comment by drbyte** [comment]
@sjelfull how are you handling these parameters today?

**Comment by sjelfull** [comment]
I'm just passing it manually. But some day! :D

**Comment by comes** [comment]
Have a look at https://github.com/laravel/valet/pull/881

**Comment by driesvints** [comment]
Hi there, we're cleaning up the Valet issue tracker and are moving all feature requests/support questions to the Discussions tab. We'll be using the issue tracker solely for bugs with Valet from now on. You're welcome to continue the discussion on in the Discussions tab. Thanks!
