### ISSUE TITLE
PHP Warning:  Module 'mcrypt' already loaded in Unknown on line 0

### ISSUE THREAD

**Issue by futurewebsites** [laravel/valet#560]
Every time I try to install I get the following errors:

PHP Warning:  Module 'mcrypt' already loaded in Unknown on line 0
PHP Warning:  Module 'mcrypt' already loaded in Unknown on line 0
PHP Parse error:  syntax error, unexpected 'mcrypt' (T_STRING), expecting ',' or ')' in Command line code on line 2
PHP Warning:  Module 'mcrypt' already loaded in Unknown on line 0
PHP Warning:  Module 'mcrypt' already loaded in Unknown on line 0
PHP Parse error:  syntax error, unexpected 'mcrypt' (T_STRING), expecting ',' or ')' in Command line code on line 2
PHP Warning:  Module 'mcrypt' already loaded in Unknown on line 0

Warning: Module 'mcrypt' already loaded in Unknown on line 0
Could not open input file: 
Warning: Module 'mcrypt' already loaded in Unknown on line 0

Parse error: syntax error, unexpected 'mcrypt' (T_STRING), expecting ',' or ')' in Command line code on line 2/cli/valet.php

**Comment by javian** [comment]
The new PHP formulas embed mcrypt whereas the old one loaded a seperate module. Are you sure the module isn't loaded a second time from your etc/conf.d directory ?

**Comment by futurewebsites** [comment]
@javian Hi I can't find a etc/conf.d directory?

**Comment by futurewebsites** [comment]
OK I have deleted mcrypt ext from all php dirs and valet now installs without error however the command line shows (php -v) I am on 7.1 but php info under valet shows 5.6

**Comment by futurewebsites** [comment]
Solved by deleting mcrypt extensions from all php versions and then https://github.com/laravel/valet/issues/237 chaoszcat last comment

**Comment by drbyte** [comment]
@futurewebsites If this is resolved, please close the issue.

**Comment by drbyte** [comment]
This isn't a valet issue. Can be closed.

If you need to force a PHP version in composer you can do that with the global config parameters as mentioned in #535
