### ISSUE TITLE
Default TLD name proposal

### ISSUE THREAD

**Issue by eightyfive** [laravel/valet#563]
Hi,

Just a quick shout to propose a new neat default TLD name for Valet.

Currently it is `*.test`, which does not feel (to me) adequate. `*.dev` feels better but since it [cannot be used with Chrome anymore](https://www.theregister.co.uk/2017/11/29/google_dev_network/) it is out of the question. `*.app`.. Meh...

So my new and shiny proposal is: `*.val`.

**PROs**

- Short (3 letters long)
- Strong link with Valet tool (very clear what website URLs are handled by Valet)
- Future proof (very specific/branded TLD name)
- No existing `.val` WWW TLD name (to my knowledge)
- Neat (?!)

**CONs**

- No semantic meaning!
- ... (I'm biased 😄)

Feel free to disregard that issue (and close it) as fast as I opened it! No hard feelings!

**Comment by adamwathan** [comment]
It would be cool but `.test` is actually a [reserved TLD](https://tools.ietf.org/html/rfc2606#section-2) which means we can safely rely on it being available forever, whereas `.val` could become a real TLD any time. You're free to change yours locally though to whatever you want 👍
