### ISSUE TITLE
Can't change domain name to local

### ISSUE THREAD

**Issue by CBox** [laravel/valet#566]
Hey,

Everything working well but when I change the valet domain to local is not working.

```
valet domain local
Restarting dnsmasq...
Restarting php...
Restarting nginx...
Your Valet domain has been updated to [local].
```

dnsmasq.conf content:
address=/.local/127.0.0.1
listen-address=127.0.0.1

How can I debug it? I got to use the "local" domain.

Thanks,
Rafael

**Comment by adamwathan** [comment]
The `local` TLD doesn't work properly on macOS in my experience; the operating system hijacks it or something and treats it differently. Try a different TLD.

**Comment by iAn-Pinto** [comment]
To set local as domain name using valet do the following setting. 
On Mac add 'local' to Search Domains in advanced settings in Network settings.
![screen shot 2018-09-04 at 3 00 04 pm](https://user-images.githubusercontent.com/7788571/45023132-7b2b2780-b053-11e8-9a30-5ed2f68d72b2.png)

**Comment by bhuvidya** [comment]
@iAn-Pinto that worked for me! Thanks heaps!
