### ISSUE TITLE
Imagick is missing

### ISSUE THREAD

**Issue by CBox** [laravel/valet#567]
Hey,

I can't install php 7.1 with imagick and Valet can't start.

which php returns:
/usr/local/opt/php@7.1/bin/php

php -v returns:
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/Cellar/php@7.1/7.1.16_1/lib/php/20160303/imagick.so' - dlopen(/usr/local/Cellar/php@7.1/7.1.16_1/lib/php/20160303/imagick.so, 9): image not found in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/Cellar/php@7.1/7.1.16_1/lib/php/20160303/imagick.so' - dlopen(/usr/local/Cellar/php@7.1/7.1.16_1/lib/php/20160303/imagick.so, 9): image not found in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php71-imagick/imagick.so' - dlopen(/usr/local/opt/php71-imagick/imagick.so, 9): image not found in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/opt/php71-imagick/imagick.so' - dlopen(/usr/local/opt/php71-imagick/imagick.so, 9): image not found in Unknown on line 0
PHP 7.1.16 (cli) (built: Apr 12 2018 03:28:19) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.1.16, Copyright (c) 1999-2018, by Zend Technologies

brew list | grep php returns:
php
php@7.1

When I try to get imagick:

brew install php71-imagick:
Error: No available formula with the name "php71-imagick"

How I can solve this?

**Comment by drbyte** [comment]
Homebrew seems to be missing that formula: https://github.com/Homebrew/homebrew-core/issues/26524

This really isn't a Valet issue. It's a Homebrew problem. This valet issue should be closed.

**Comment by aj-adl** [comment]
@drbyte All communications with the homebrew team have resulted in this being a 'WONT FIX' issue from them. They do not care about supporting everyone's use cases.

Valet should, at the very least, update the documentation on the website to notify people that there is a lot of issues / instability as a result of homebrew making these changes. Simply closing the issues is doing a disservice to potential users and probably also the repo maintainers as another 10 like it will be opened again in the future. 

Another alternative would be to list known issues, warning people that they will need to switch to PECL for extensions and listing known issues such as the OpenSSL issues, for which the only current 
 solution is altering homebrew core's PHP config and recompiling from source (which I'm currently doing as I write this comment).

Seems like the 'free ride' for easy PHP installation on the Mac is over, so the relevance of a project like valet may diminish over time and people will switch back to utilising more isolated environments such as homestead (which is still great, but a bit heavy) or utilising docker containers.

**Comment by skylerfenn** [comment]
If you're running into homebrew php issues. You can clean everything up with this guide: https://getgrav.org/blog/macos-sierra-apache-upgrade-homebrew.

I cleaned up homebrew (removing some old php versions) and then following the installation worked great.

**Comment by drbyte** [comment]
I think this can be closed -- it's a homebrew issue, not valet.
