### ISSUE TITLE
xdebug stops working after valet secure

### ISSUE THREAD

**Issue by danieldevsquad** [laravel/valet#570]
The xdebug was installed using homebrew and works fine with unsecured sites. After running

```bash
valet secure
```

The xdebug stops working (it still works for php artisan commands though).

My xdebug configuration:

```
[xdebug]
zend_extension="/usr/local/opt/php71-xdebug/xdebug.so"

xdebug.remote_enable=1
xdebug.remote_host=localhost
xdebug.remote_port=9000
xdebug.remote_autostart=1
xdebug.max_nesting_level=512

``` 

Tested with PHPStorm and Visual Studio Code

Any ideas?

**Comment by pascalporedda** [comment]
Having the same trouble.. It was working a few versions ago though..

**Comment by drbyte** [comment]
@danieldevsquad @pascalporedda is this still an issue?

**Comment by pascalporedda** [comment]
@drbyte Nope works for me now.

**Comment by drbyte** [comment]
@mattstauffer I think this can be closed

**Comment by adriaanzon** [comment]
I just ran into this problem. After unsecuring the site, debugging started working again.

I am running Valet 2.9.0.

**Comment by premnathmali007** [comment]
The solution is you have to do the following
1. Go to Settings>PHP>Servers
2. Uncheck "Use path mappings"
3. Check Shared checkbox

**Comment by iboved** [comment]
@danieldevsquad can you help me? How did you solve this problem? Thanks.
