### ISSUE TITLE
Valet could not install nginx [Brew was unable to install nginx]

### ISSUE THREAD

**Issue by toeyanuntachai** [laravel/valet#572]
i ran valet install then it's  show error like this below
<img width="846" alt="screen shot 2018-04-18 at 6 14 06 pm" src="https://user-images.githubusercontent.com/7608232/38928867-b6259dd4-4334-11e8-8259-71cb0435ed0b.png">

**Comment by benyou1969** [comment]
Lots of people would simply copy paste that command @florianbouvot and may not notice the typo moving to something else
`brew postinstall nginx`

**Comment by drbyte** [comment]
I think this can be closed due to inactivity.

Also, installing valet via sudo as the screenshot shows ... isn't particularly appropriate.
