### ISSUE TITLE
Change User on Mac, Re-Install of Valet not works

### ISSUE THREAD

**Issue by Stefan39** [laravel/valet#574]
Hi

on an old user i have installed valet with homebrew successfully. Yesterday i have change the mac user and today delete the old user. All valet links are not working anymore.

So i have found [this comment](https://github.com/laravel/valet/issues/341#issuecomment-287048987) and try it with that. 

But if i am type valet install in the terminal now i got the follow error:
`-bash: /usr/local/bin/valet: No such file or directory`

I have re-install valet with follow commands:
`MaBook-Pro: stefan$ composer global require laravel/valet`
`Changed current directory to /Users/olicci-stefan/.composer`
`Using version ^2.0 for laravel/valet`
`./composer.json has been updated`
`Loading composer repositories with package information`
`Updating dependencies (including require-dev)`
`Nothing to install or update`
`Generating autoload files`
`MacBook-Pro: stefan$ valet install`
`-bash: /usr/local/bin/valet: No such file or directory`

Of course like describes in the comment i have delete the folder /usr/local/bin/valet, but should the valet install not added again?

What can i do now for repair it?

Thanks,
Stefan

**Comment by Stefan39** [comment]
ok, after uninstalling all (include brew), reboot and re-installing all works fine.

**Comment by turanzamanli** [comment]
export PATH=$PATH:~/.composer/vendor/bin

**Comment by turanzamanli** [comment]
`export PATH=$PATH:~/.composer/vendor/bin`
