### ISSUE TITLE
serve projects with different php versions

### ISSUE THREAD

**Issue by NikolaySav** [laravel/valet#576]
Greetings!
I'm wondering how can i serve projects with different php versions at the same time?
For example: one project with php5.6 and another one with php7.1.

Thanks in advance.

**Comment by drbyte** [comment]
I wrote a summary of how to do that in a PR comment here: https://github.com/laravel/valet/pull/378#issuecomment-372088267

**Comment by NikolaySav** [comment]
Thank you for answer. 
But i don't have this file:
/Users/USERNAME/.valet/valet56.sock
How can i create one?

**Comment by drbyte** [comment]
If you follow all the instructions I posted there, then PHP will automatically create the .sock file when it starts.

**Comment by NikolaySav** [comment]
followed all your instructions one again but still getting an error
connect() to unix:/Users/nsavinov/.valet/valet56.sock failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1....

Could you tell me which step should create the valet56.sock file?

**Comment by drbyte** [comment]
> Could you tell me which step should create the valet56.sock file?

This from https://github.com/laravel/valet/pull/378#issuecomment-372088267 :
> edit the PHP 5.6 config file /usr/local/etc/php/5.6/php-fpm.conf and find the line containing valet.sock...
> `listen = /Users/USERNAME/.valet/valet56.sock`

After making that edit and restarting PHP, the valet56.sock socket file should be created.

I suppose maybe the Homebrew changes to PHP version numbering may have changed which exact path the php-fpm.conf file is located in. Adjust accordingly.

**Comment by drbyte** [comment]
> I also noticed that no php@5.6 fpm processes are running.
brew services restart php@5.6 was successful but nothing changed.

If the associated service isn't running, then it's no surprise that there's no socket file.

I'd start by looking for errors in the PHP logs, to see if something else got broken when you were editing the .conf file, or for other problems it may be encountering when starting.

Sorry, I'm only using PHP 7.2 nowadays, and don't have older PHP versions installed anymore, so don't have a 5.6 setup to test more exact details.

**Comment by NikolaySav** [comment]
After doing
`sudo brew services restart php56`
the valet56.sock file appeared.

That was kinda strange because with 7.1 i didn't have to do it as su...

**Comment by drbyte** [comment]
Glad you sorted it out!
If this is resolved, please close this Issue.

**Comment by NikolaySav** [comment]
Thanks for help. 
Closed.
