### ISSUE TITLE
How to use xip.io in projects with sub-domains

### ISSUE THREAD

**Issue by simioluwatomi** [laravel/valet#579]
I have a project with 3 sub-domains ```admin.example.test```, ```app.example.test```, ```api.example.test```. To share the project with xip.io, I have followed the steps mentioned in #450. I also modified my ```APP_URL = http://my_local_ip_address.xip.io``` because my route groups are structured like so
```
Route::group(['namespace' => 'Web', 'domain' => env('APP_URL')], function () {
    // more code here
});

Route::group(['namespace' => 'Web\Auth', 'domain' => 'app.' . env('APP_URL')], function () {
    // more code here
});
```
Then I ran ```valet link my_local_ip_address.xip.io``` and ```valet link {subdomain}.my_local_ip_address.xip.io``` for all sub-domains. The result is that all subdomain routes throw a ```Valet 404 - Not Found error``` but ```my_local_ip_address.xip.io``` routes work just fine.

How do I make this work for all sub-domains in the project? Thanks

**Comment by drbyte** [comment]
@simioluwatomi is this still an issue?

**Comment by simioluwatomi** [comment]
When I couldn't get this to work, I stopped using Valet altogether. I now use Laragon
