### ISSUE TITLE
Valet Joomla driver too many redirects

### ISSUE THREAD

**Issue by thinkerytim** [laravel/valet#580]
I'm trying to use the Laravel Valet driver for Joomla-- when I navigate to my newly extracted Joomla files (direct from the Joomla 3.8 archive) I can't view the page, I get a "too many redirects" error at the following URL: `https://joomla38.test/installation/installation/installation/installation/installation/installation/installation/installation/installation/installation/installation/installation/installation/installation/installation/installation/installation/installation/installation/installation/index.php`

Has anyone encountered this?

**Comment by drbyte** [comment]
@thinkerytim is this still an issue?

**Comment by thinkerytim** [comment]
It doesn't seem to be anymore. I suspect an upgrade may have resolved it. Closing.
