### ISSUE TITLE
Can we have url rewriting option support?

### ISSUE THREAD

**Issue by gogachinchaladze** [laravel/valet#581]
I'm using Valet for my Angular application local server + sharing. 

The problem I came across, is that it doesn't support url rewriting (and web.config/.htaccess) are not working.

I researched google and found out that there are no options to do it. Then I solved the problem using the driver:

```
public function isStaticFile($sitePath, $siteName, $uri)
    {
        if (file_exists($staticFilePath = $sitePath.'/public'.$uri)) {
            return $staticFilePath;
        } elseif ($this->isActualFile($staticFilePath = $sitePath.$uri)) {
            return $staticFilePath;
        } else{ //always return index.html or index.php to ensure 
            if($this->isActualFile($staticFilePath = "$sitePath/index.html")){
                return "$sitePath/index.html";
            }
            else if($this->isActualFile($staticFilePath = "$sitePath/index.php")){
                return "$sitePath/index.php";
            }
            else if($this->isActualFile($staticFilePath = "$sitePath/public/index.php")){
                return "$sitePath/public/index.php";
            }
        }
        // return false;
    }
```

But I know that's not a very good thing to do :)

I would love to have url rewriting option when I'm starting valet.

**Comment by drbyte** [comment]
I think this can be closed.

You have the right solution: a custom driver.
Alternatively you can customize your Nginx/Apache configs to provide features as needed.
