### ISSUE TITLE
Resource interpreted as Stylesheet but transferred with MIME type text/html

### ISSUE THREAD

**Issue by rockingaryan** [laravel/valet#582]
Valet Version: latest
PHP Version: 7.2.4
macOS Version: Sierra 10.12.6

`ls -la /Library/LaunchDaemons`
not found this in the list `com.laravel.valetServer.plist`

how to solve this?
![image](https://user-images.githubusercontent.com/34836534/39695090-04e633e4-5207-11e8-8e31-5f9f29754bfe.png)

**Comment by ryanjohnsonnc** [comment]
I am having the same problem.

**Comment by comes** [comment]
How to reproduce this issue? please describe step-by-step how to reproduce this issue

**Comment by drbyte** [comment]
@mattstauffer I think it can be closed. If someone else actually has the problem and can recreate it, they can add to it.
