### ISSUE TITLE
Shell script does not use the same environment as the terminal shell 

### ISSUE THREAD

**Issue by ssmusoke** [laravel/valet#585]
I am running a Symfony 4 project with the latest , what executes shell scripts based on input from form data using the Process component reference Ticket https://github.com/symfony/symfony/issues/18847

I keep getting command not found for mysql in my output, yet shell_exec executes the scripts properly... and they also run well on the command line

My Environment:

- MacOS 10.13.4 - all installations done via Homebrew
- PHP 7.2.5 (cli) (built: Apr 26 2018 12:07:32) ( NTS )
- Symfony 4.0.8 + Process 4.0.8

When I run the code below:
   `$env = new Process("env");

     $env->run();

     print_r($env->getOutput());
    `
I find my path as PATH=/usr/bin:/bin:/usr/sbin:/sbin which is different from what I get on a shell command. On further reading these seem to be the default MacOS paths ...

**Comment by ssmusoke** [comment]
This does not occur when running the inbuilt PHP server using the Symfony Web Server Bundle and these lines seem to do the trick https://github.com/symfony/web-server-bundle/blob/0dd380dda69a180151de75f3734c418917652f3a/Command/ServerRunCommand.php#L102-L112

**Comment by ssmusoke** [comment]
The fix that I ended up having to do was to add the output of the `echo $PATH` command on my computer as  fastcgi_param PATH within the configuration for my project. 

Is there anyway this can be done automatically?

**Comment by drbyte** [comment]
@ssmusoke PR https://github.com/laravel/valet/pull/474, which is in `dev-master` currently, allows you to set ENV values at the per-project level, in a `.valet-env.php` file.

Does that give you a suitable hook to control what you were looking for?

**Comment by drbyte** [comment]
IMO this can be closed.

**Comment by ssmusoke** [comment]
Sorry I had missed the comment, is it possible to also use the environment variables from the shell being used - this was my challenge

**Comment by drbyte** [comment]
When accessing valet via a web request, PHP-FPM is controlling what passes through for environment variables.

The ServerRunCommand link you posted above refers to passing `$env` as `prod` or `local` etc, not as passing a shell's environment. Perhaps in those cases you have some config file for your defined prod/local setup that is passing through specialized values that override the defaults from PHP-FPM?

At any rate, if you want to inject a custom PATH (you mentioned `echo $PATH`), you can do that in either fastcgi_param configs in individual site definitions (as you said you've done), or more generally in `/usr/local/etc/nginx/fastcgi_params` (which valet updates on install).  If you need even more control you could tweak your fpm configs, although I'd suggest that's too extreme.

**Comment by ssmusoke** [comment]
So when I run a bash shell script through PHP-FPM, what environment does it use? 

It is definitely not the one on the host which has the necessary paths set yet the same setup runs in a docker nginx container without issues

**Comment by drbyte** [comment]
If you're invoking Valet, then you're invoking the FPM SAPI, which uses this default configuration: (I've highlighted PHP's explanation of what it deems as "default")

https://github.com/php/php-src/blob/be7e819068985859f92e4af21e49b4f647dd0467/sapi/fpm/www.conf.in#L398-L405

**Comment by ssmusoke** [comment]
@drbyte now that totally makes sense - you can go ahead and close the ticket as this is the default behavior. Thank you for taking the time to make this clear
