### ISSUE TITLE
Add Uninstall Steps to Laravel Valet Documentation

### ISSUE THREAD

**Issue by ryanjbonnell** [laravel/valet#589]
The Valet docs comprehensively cover installation, but don't offer any advice to uninstall Valet (and its dependencies).

This topic was mentioned in #341 along with documenting the necessary steps.

However, the documentation has never been updated to share the uninstall procedures:

```
valet uninstall
sudo brew services stop nginx
sudo brew services stop php70
sudo brew services stop dnsmasq
brew uninstall nginx
brew uninstall php70
brew uninstall dnsmasq
rm -rf ~/.valet
rm /usr/local/bin/valet
```

Can we get the uninstall steps added as a new section to the [official documentation][0]?

[0]:  https://laravel.com/docs/5.6/valet

**Comment by drbyte** [comment]
Keep in mind that PHP versions are changing regularly, so the specific version number will vary based on whatever the user has installed.

That said, the docs are maintained on a public github repo, which is open for PRs:
https://github.com/laravel/docs/blob/5.6/valet.md

**Comment by bbashy** [comment]
Yeah homebrew use php@7.2 now.

**Comment by drbyte** [comment]
As of Valet 2.6.0 there's a built-in complete uninstall command: `valet uninstall --force` and if you want to do the uninstall manually, `valet uninstall` will explain the steps you need to take.

**Comment by drbyte** [comment]
@mattstauffer This can be closed.
