### ISSUE TITLE
Nginx not serving updated files

### ISSUE THREAD

**Issue by alystair** [laravel/valet#595]
Was directed here by @cretueusebiu - maintainer of the Windows port of Valet. Copy of the issue I submitted to his repo @ https://github.com/cretueusebiu/valet-windows/issues/88

Sometimes Nginx does not recognize files have been modified, as such browsers reload from disk cache - since Valet is a development environment wouldn't it make sense to specifically disable caching mechanisms?

Nginx is specifically returning cache tags in response headers
```
Date: Sat, 02 Jun 2018 19:29:15 GMT
ETag: W/"5b1126c5-4a3"
Last-Modified: Fri, 01 Jun 2018 10:58:13 GMT
```

**Comment by drbyte** [comment]
I believe this can be closed.
