### ISSUE TITLE
NET::ERR_CERT_COMMON_NAME_INVALID

### ISSUE THREAD

**Issue by rupertraphael** [laravel/valet#603]
Hi, what could be the possible reasons why I am getting this NET::ERR_CERT_COMMON_NAME_INVALID on chrome?
<img width="679" alt="screen shot 2018-06-24 at 9 54 55 pm" src="https://user-images.githubusercontent.com/19609578/41829659-46759314-77f9-11e8-8a15-a3acabb73106.png">

**Comment by rupertraphael** [comment]
So, i changed the valet domain to .test and it all works now. What was weird before was that I used the .app domain and all but one of my projects received that certificate error. I would like to know why, though.

**Comment by linuxjuggler** [comment]
Sadly `.app` domains are not for local development anymore, they are now owned and operated by Google.

By default those domains need to have a *valid* certificate, not self-signed one, you can read more about them [here](https://www.blog.google/technology/developers/introducing-app-more-secure-home-apps-web/) and [here](https://security.googleblog.com/2017/09/broadening-hsts-to-secure-more-of-web.html)

**Comment by rupertraphael** [comment]
@linuxjuggler Oh, I see. Searching this error on the web only made me find out that `.dev` wouldn't work any more. Seems like I've didn't do much research. Thanks!

**Comment by linuxjuggler** [comment]
@rupertraphael true especially that both domains `.app` and `.dev` are owned by Google :'( 
https://icannwiki.org/.dev

**Comment by LockedMind** [comment]
i have a doubt, i can't connect to passbolt web but my co-workers can.
the error is the same, invalid certificate
