### ISSUE TITLE
Google chrome complains about phishing stuff

### ISSUE THREAD

**Issue by heihachi88** [laravel/valet#604]
Laravel 5.6
Valet 2.0.12
High Sierra 10.13.5

When i do `valet share` google chrome complains about /css/app.css, tough i've removed this file at all, it still complains about it. Is that valet or laravel mix bug?

**Comment by designbyjr** [comment]
Its most likely a cross-origin error, please search for cross-origin metas

**Comment by drbyte** [comment]
This can be closed.
