### ISSUE TITLE
ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by pmochine** [laravel/valet#605]
After 4 hours of trying, I don't know what to do.

So everything worked fine and I coded for weeks without problems. Now when I wanted to show my friend how to use valet share, everything went wrong.

My page was secured with https://instafood.test. For "valet share" I needed to use "valet unsecure". My mistake was that I forgot to write "valet unsecure instafood". 

I did not notice my mistake and called the command valet share afterward. I took the shared URL and opened it on safari on an iPhone. I saw the dreaded "it works". So I stopped valet share and secured it again, but the page https://instafood.test stopped working and I even didn't get "it works". Just "ERR_CONNECTION_REFUSED".

With "valet paths" I saw the wrong paths and deleted them, but nonetheless, it's still not working.

In #326 I found that I should uninstall everything again. I did everything and restarted the services:

![image](https://user-images.githubusercontent.com/25006691/42245811-74c7c2e6-7f1a-11e8-96bd-f27fbadafa55.png)

Brew is telling me that it is successfully restarted, but I get errors in: /usr/local/var/log 

In redis I get the errors:

![image](https://user-images.githubusercontent.com/25006691/42245917-ef8f3d60-7f1a-11e8-9dcc-78103cfd3de2.png)

And in nginx

![image](https://user-images.githubusercontent.com/25006691/42245928-fcd33ce2-7f1a-11e8-9c1b-96a179ba68bb.png)

Like for the others. The weird part is that I can ping my address and it works. If I go to http://localhost:8080/ I get the "Welcome to nginx!"-page.

So I tryed to find out what is on port: 80

![image](https://user-images.githubusercontent.com/25006691/42246049-74a5f2dc-7f1b-11e8-86b9-40c1b03af7cc.png)

How should I block these? And with sudo lsof -i:80  I see these

![image](https://user-images.githubusercontent.com/25006691/42246087-94252bdc-7f1b-11e8-817f-17c56b8f099d.png)

So in another forum I found out you should stop apache. I tried with sudo apachectl stop and then sudo brew services restart --all. But still no luck.

I don't really know what to do anymore. It's super weird and I don't want to reinstall my os...

**Comment by drbyte** [comment]
Usually when ports are being reserved unexpectedly, especially after installing and starting/stopping/removing/reinstalling/starting/etc a reboot works wonders.

**Comment by pmochine** [comment]
So I just are going to post some Updates:

I uninstalled everything. From [Node](https://stackoverflow.com/questions/9044788/how-do-i-uninstall-nodejs-installed-from-pkg-mac-os-x) to all brew services and I even uninstalled [apache](https://stackoverflow.com/questions/46268082/how-to-uninstall-apache-from-the-command-line-on-mac).

Now I installed everything back beside apache and every brew services are running without errors.

Fortunately, I get a 404 - Not Found on valet. I think that is because apache is not running. But I'm curious why do I need nginx and apache at the same time? Does anyone know it?

**Comment by pmochine** [comment]
Well, that is weird. I've never needed to write: cd parent/my-project && valet link my-project

But that was it. I DID IT 🎉

**Comment by drbyte** [comment]
You said you had edited the `valet paths` settings. Perhaps your parent directory is no longer in that list? That would explain the need to do manual linking.

Nevertheless, glad you got it sorted out!  Please close this Issue if your matter requires no further discussion.

**Comment by tdwesten** [comment]
Check next time if the nginx config; ```nginx -t``` this was for me the problem.

**Comment by HPWebdeveloper** [comment]
https://medium.com/@panjeh/valet-this-site-cant-be-reached-err-connection-refused-ad424ea1e343
