### ISSUE TITLE
IDEA: Serve up a listing of available sites when visiting localhost

### ISSUE THREAD

**Issue by JamiesonRoberts** [laravel/valet#610]
Preface: I work at an agency and have lots of projects installed in my code folder.

The idea is that when you visit http://localhost, maybe the 404 page, or being able to define a "home" route that would then server up a list of clickable links to all of the valid valet paths and links. This would make it convenient and not have to remember what exactly the folder name is etc.

Thoughts? I've tried to dig around and can't see how it might be possible outside of the the core codebase. Also, would be happy to tackle this myself with some guidance or insight on how it might be accomplished.

Cheers!

**Comment by aaemnnosttv** [comment]
This is a cool idea but I don't think Valet "core" is the right place for it.

Nothing is preventing this from being done as a standalone project since all the necessary paths are readily available. Parked sites can be found by following the `paths` key in `~/.valet/config.json` and linked sites are in `~/.valet/Sites/`. Because of this, there's any number of ways you could create your own "sites dashboard" of sorts 😎

**Comment by aaemnnosttv** [comment]
Ok, I couldn't help whipping something up real quick, so I here ya go:

https://github.com/aaemnnosttv/valet-dashboard

The implementation is super basic, so you could fork it and do all kinds of fancy stuff with it if you wanted to. Let me know what you think!

**Comment by jackfruhecolab** [comment]
aaemnnosttv, 

i just did this, then found yours! Your's is mostly better.
Could you consider opening issues on that repo so we can comment there?

I have a few thoughts...
If you create a folder in your parked folder, and call that folder "Localhost", then you can bring up localhost on your browser, and it will run your index.php script.
Note for me I expected to have to use http://localhost.test, but in my testing it looks like it works with plain old http://localhost.

**Comment by aaemnnosttv** [comment]
@jackfruhecolab Issues opened. Let's move the convo there.

**Comment by drbyte** [comment]
@mattstauffer I think this can be closed

**Comment by daslicht** [comment]
any news on this ? /.valet/Sites/. is no nolnger available
