### ISSUE TITLE
PHP file returns the body of index.html

### ISSUE THREAD

**Issue by JoshuaPerk** [laravel/valet#617]
I'm working with a fresh install of Valet and have noticed AJAX requests (that were previously successfully deployed to my production server) are now catching errors. Upon further investigation, I noticed that by navigating directly to a PHP file, rather than the expected output, the body of the index file would be returned.

### Example:
```
.index.html
├── php
└──── test.php          # only function within is to echo "Hello World"
```
### Actions to reproduce:
Navigate directly to test.php

### Expected behavior:
Browser returns and prints "Hello World" on screen.

### Actual behavior:
The contents of index.html are returned.
When fetching the PHP file via AJAX, the console logs: `SyntaxError: Unexpected token < in JSON at position 0”` which makes sense since the return is an HTML page.

I haven't the faintest idea how to resolve but am speculating that either PHP or my Valet config are askew.

**Comment by drbyte** [comment]
That sounds like your php-fpm service isn't running, or your valet config for that particular site is no longer pointing to a valid php-fpm instance. 
Did you recently update php versions?  

Running `valet domain test` (assuming ".test" is your normal valet TLD) will rebuild all your host configs to point to the current php-fpm instance.

**Comment by JoshuaPerk** [comment]
Hi, @drbyte. I didn't recently update, but I did noticed I had two versions of PHP installed so there was some cleanup recently. Maybe that has something to do with it? I ran the `valet domain test` and it rebuilt successfully but the problem appears to persist.

Running `brew services list` shows:
```
Name      Status  User       Plist
dnsmasq   started root       /Library/LaunchDaemons/homebrew.mxcl.dnsmasq.plist
mysql@5.7 started joshuaperk /Users/joshuaperk/Library/LaunchAgents/homebrew.mxcl.mysql@5.7.plist
nginx     started root       /Library/LaunchDaemons/homebrew.mxcl.nginx.plist
php       started root       /Library/LaunchDaemons/homebrew.mxcl.php.plist
```

**Comment by drbyte** [comment]
What's `brew info php` say?

**Comment by JoshuaPerk** [comment]
```
php: stable 7.2.9 (bottled), devel 7.3.0beta2
General-purpose scripting language
https://secure.php.net/
/usr/local/Cellar/php/7.2.9_1 (515 files, 79.1MB) *
  Poured from bottle on 2018-08-22 at 11:23:50
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/php.rb
==> Dependencies
Build: httpd ✘, pkg-config ✘
Required: apr ✔, apr-util ✔, argon2 ✔, aspell ✔, autoconf ✔, freetds ✔, freetype ✔, gettext ✔, glib ✔, gmp ✔, icu4c ✔, jpeg ✔, libpng ✔, libpq ✔, libsodium ✔, libxml2 ✔, libzip ✔, openssl ✔, pcre ✔, unixodbc ✔, webp ✔
==> Options
--devel
	Install development version 7.3.0beta2
==> Caveats
To enable PHP in Apache add the following to httpd.conf and restart Apache:
    LoadModule php7_module /usr/local/opt/php/lib/httpd/modules/libphp7.so

    <FilesMatch \.php$>
        SetHandler application/x-httpd-php
    </FilesMatch>

Finally, check DirectoryIndex includes index.php
    DirectoryIndex index.php index.html

The php.ini and php-fpm.ini file can be found in:
    /usr/local/etc/php/7.2/

To have launchd start php now and restart at login:
  brew services start php
Or, if you don't want/need a background service you can just run:
  php-fpm
```

**Comment by JoshuaPerk** [comment]
Interesting: when I run `php-fpm`

```
[22-Aug-2018 11:57:31] ERROR: failed to open configuration file '/private/etc/php-fpm.conf': No such file or directory (2)
[22-Aug-2018 11:57:31] ERROR: failed to load configuration file '/private/etc/php-fpm.conf'
[22-Aug-2018 11:57:31] ERROR: FPM initialization failed
```

**Comment by drbyte** [comment]
Okay, let's switch gears. 

> Upon further investigation, I noticed that by navigating directly to a PHP file, rather than the expected output, the body of the index file would be returned.

This seems more like a domain misconfiguration, or the wrong valet driver is being activated.
Or, you're trying to access a PHP file that matches the name of a directory, or somehow doing something that's triggering a "display the default file" (can happen with file-not-found fallbacks etc).

I tried doing a fresh install of valet and a fresh laravel project, and can't trigger anything like you're describing.

**Comment by JoshuaPerk** [comment]
@drbyte You're right. Thank you, tremendously.

For future folks experiencing similar problems, take a look at how your existing application is structured. I didn't spend a lot of time understanding the Laravel framework before using Valet and ended up needing a driver focused on more static-like apps (at least until I refactor my app using Laravel).
