### ISSUE TITLE
Domain command no longer outputs bare TLD 

### ISSUE THREAD

**Issue by aaemnnosttv** [laravel/valet#620]
As of #241 `valet domain` no longer outputs the plain TLD used for the domain, but a more informational message.

This breaks a package that I maintain that uses this command as part of a scripted install. See aaemnnosttv/wp-cli-valet-command#39

With the addition of the `tld` command, can we keep `domain` outputting the bare TLD for backwards compatibility?

If this is the wrong way to get configuration values from Valet, what's the best/safest future-proof way to do so?

**Comment by aaemnnosttv** [comment]
Thank you for the PR, that's much appreciated.

I'm still interested to know what the maintainers have to say in regard to the questions above though as it goes beyond just the issue with my package.

**Comment by mattstauffer** [comment]
@aaemnnosttv From my understanding, the maintainers are open to PRs that offer functionality that makes sense, doesn't overly complicate the codebase, is easy to grok and test and implement and maintain, and isn't more drivers. So if you want to build a feature that exposes data for consumption by a third-party tool, I can't guarantee they'll say yes, but I can say that's probably going to be your best option. That, or just merge @drbyte's PR.

FWIW, while he doesn't have commit rights, @drbyte is by far the most active helper on this repo, so him offering help in this way is one of the best things we have going for us.

**Comment by aaemnnosttv** [comment]
Thanks Matt. I wasn't thinking that building something for getting configuration values is really necessary.

I took a look at if it might be possible to keep the `domain` command the way it was without listing it as a normal command but it doesn't look like a simple change. Preserving BC would require changing the `tld` command as well and I'm not suggesting that since it has already been accepted as-is.

Everything I need is in `~/.valet/config.json`. As long as I can rely on that not moving, then I think reaching for it there is probably the way to go going forward (this is what [Lambo](https://github.com/tightenco/lambo) does).

Thanks to @drbyte and everyone else who helps maintain this!

**Comment by mattstauffer** [comment]
@aaemnnosttv :) ❤️

**Comment by drbyte** [comment]
@aaemnnosttv wrote:
> Everything I need is in ~/.valet/config.json. As long as I can rely on that not moving, then I think reaching for it there is probably the way to go going forward (this is what Lambo does).

Just FYI - There's an open PR proposing to move that file to the standard Mac `~/.config/` directory as `~/.config/valet/config.json`.  I've personally been using that implementation since the PR was submitted, and quite prefer it. I think it's stable, and the last time I tested it on a fresh install it properly moved things around for easy upgrading too. No idea if Matt will merge it, but since you raised the possibility of relying on it, thought you might want to consider it if you're adapting your package to rely on it.

**Comment by mattstauffer** [comment]
Let's make that easier: I merged it. I'll be pushing up a tag soon with all the stuff I've merged over the last few weeks. 

https://github.com/laravel/valet/pull/449

**Comment by aaemnnosttv** [comment]
Thanks for the heads up! :)

**Comment by aaemnnosttv** [comment]
@mattstauffer you should test the latest after merging #449 before tagging as I had problems before and after running `install` which required me to manually move over to the new config directory.

**Comment by mattstauffer** [comment]
@aaemnnosttv OK, sounds good. Thanks!
