### ISSUE TITLE
Wordpress - woocommerce - wc vendors, not show menu products

### ISSUE THREAD

**Issue by ssheduardo** [laravel/valet#621]
Hi,
When create a new project of wordpress is fine.
When install woocommerce and wc vendors is fine.

But if create a user with role vendor and after login, not show menu: products, store, etc.
So if install wodpress, woocommerce and wc vendors with Homestead, this show menu: productos, store, etc.

WITH VALET
-------------
![imagen](https://user-images.githubusercontent.com/1160138/44807894-06776980-abcb-11e8-8a95-31fc2c63a68f.png)

WITH HOMESTEAD
--------------------
![imagen](https://user-images.githubusercontent.com/1160138/44807914-0ecfa480-abcb-11e8-8a1b-a163d5055f14.png)

Where is the error, is permission or configuration?
Someone try this please.

**Comment by ssheduardo** [comment]
**More info**
Mac os high sierra 
Laravel Valet 2.0.12
WooCommerce 3.4.4
WC Vendors Marketplace 2.0.10

**Comment by aaemnnosttv** [comment]
Sounds and looks like the `vendor` role doesn't have the proper capabilities to manage the store.

I don't see how Valet could be responsible for the issue you're having.

**Comment by ssheduardo** [comment]
@aaemnnosttv the installation is same at valet and homestead.

**Comment by ssheduardo** [comment]
I created a new website wordpress in Homestead with the basic configuration of woocommerce and wc vendors and this is result.

![imagen](https://user-images.githubusercontent.com/1160138/44819188-3daa4280-abec-11e8-8ddd-67905c52c43c.png)

In admin wordpress see the role user.

HOMESTEAD
==========
![imagen](https://user-images.githubusercontent.com/1160138/44819278-911c9080-abec-11e8-819c-4e537b3e7416.png)

**Comment by ssheduardo** [comment]
I believe a idea, I try at afternoon.

**Comment by ssheduardo** [comment]
I am sorry, the problem is a permissions :(

Close the issues
