### ISSUE TITLE
Able to ping, see remotely, not able to see locally

### ISSUE THREAD

**Issue by e-baker** [laravel/valet#627]
I just installed Valet version 2.0.12 on my MacBook Pro. I have nginx, php7.2, dnsmasq all up and running via homebrew. I've verified this with `ps aux | grep nginx`, `ps aux | grep dnsmasq`, and `ps aux | grep php`. 

When I try to go to `*.tld` (tld means whatever I've set for the domain at that point), I'm able to ping it successfully, I can use `valet share` to access via ngrok.io, but cannot access it via my browser. 

I've verified everything I can think to verify. For now, I'm just using `valet share` to develop but would love to not need that.

**Comment by drbyte** [comment]
Maybe it's just your browser giving you grief?

I just did the following, using Valet 2.0.12 and PHP 7.2 : 
(Valet is already configured to serve from my ~/Sites directory.)

```sh
cd ~/Sites
valet domain test
laravel new demo2
valet open demo2
```
This opened http://demo2.test in my browser, and displayed a fresh Laravel install:

<img width="728" alt="screen shot 2018-09-12 at 3 18 21 pm" src="https://user-images.githubusercontent.com/404472/45447945-1d27c100-b69f-11e8-808d-45d256076f27.png">

Then run:
```sh
cd demo2
valet share
```
ngrok opens as expected:

<img width="651" alt="screen shot 2018-09-12 at 3 22 05 pm" src="https://user-images.githubusercontent.com/404472/45448198-c1116c80-b69f-11e8-80a5-51a531ee24a2.png">

Then visiting the http ngrok link opens as expected:
<img width="738" alt="screen shot 2018-09-12 at 3 22 32 pm" src="https://user-images.githubusercontent.com/404472/45448261-da1a1d80-b69f-11e8-9b24-f1c2e4926424.png">

And visiting the `demo2.test` domain still works as well:
<img width="733" alt="screen shot 2018-09-12 at 3 24 18 pm" src="https://user-images.githubusercontent.com/404472/45448303-ff0e9080-b69f-11e8-82bd-10262dc7bf73.png">

**Comment by e-baker** [comment]
So since you said that, I just tried refreshing cache, etc in Opera, Chrome, and Safari (all three of which I've already tried) and Safari shows the site.  However, both Opera and Chrome still don't. This obviously isn't an issue with Valet anymore though so I'll close the issue and can look for help on stack exchange.
