### ISSUE TITLE
Bad Gateway: http://example.test/ 

### ISSUE THREAD

**Issue by andira47** [laravel/valet#634]
I've successfully installed valet plus.
But on every parked or linked domain i created display this error :
Bad Gateway: http://example.test/

![2018-09-19_23-22-54](https://user-images.githubusercontent.com/1632865/45763526-33b3b680-bc63-11e8-9ce4-347add331c06.png)

**Comment by andira47** [comment]
i'm sorry, it seem that i have this justproxy extension on my google chrome enabled.
it's working fine now. thanks.

**Comment by drbyte** [comment]
Since your issue is resolve, please click Close below.
