### ISSUE TITLE
The tap function should be the same as the Laravel tap function

### ISSUE THREAD

**Issue by RicardoRamirezR** [laravel/valet#638]
Hi there, 

I'm using Laravel 5.7.4, this the stock ExampleTest, I just added the tap function.
```php
    public function testBasicTest()
    {
        $response = $this->get('/');

        tap($response);

        $response->assertStatus(200);
    }
```
I got:
```
1) Tests\Feature\ExampleTest::testBasicTest
ArgumentCountError: Too few arguments to function tap(), 1 passed in L5.7/tests/Feature/ExampleTest.php on line 19 and exactly 2 expected
```
I dig it to here: https://github.com/laravel/valet/blob/10c5239ddc08213d59765976fb4615e804e99c05/cli/includes/helpers.php#L147

Perhaps it should be equal to Laravel's one?

**Comment by mattstauffer** [comment]
@RicardoRamirezR Two things here. First, tap in Laravel has two parameters:

https://github.com/laravel/framework/blob/5.7/src/Illuminate/Support/helpers.php#L1017

Second, if you're working in a Laravel app, you shouldn't be getting the Valet version of this helper anyway. Are you sure of what's happening here?

**Comment by drbyte** [comment]
Observations:
1. Laravel 5.3 had `tap` with `$callback` being a required parameter, like Valet does.
https://github.com/laravel/valet/blob/master/cli/includes/helpers.php#L147
https://github.com/laravel/framework/blob/5.3/src/Illuminate/Support/helpers.php#L816

2. Since Laravel 5.4 the `$callback` is optional:
https://github.com/laravel/framework/blob/5.4/src/Illuminate/Support/helpers.php#L958

3. But ... if you have Valet installed as a `global` composer dependency, and NOT as an app-specific dependency, then you shouldn't run into any clash.
**Remove** `laravel/valet` from your app's `composer.json`, 
and **instead run** `composer global require laravel/valet`

**Comment by RicardoRamirezR** [comment]
I installed Valet according to [Valet Installation docs](https://laravel.com/docs/5.7/valet#installation), so it is installed globally, also I've checked the stock Laravel `composer.json` and I did not find any valet references.

I did the following:

1. Create a new Laravel installation `laravel new L5.7`

2. Modify the function `testBasicTest` in `tests\Feature\ExampleTest.php` adding the `tap` call

```php
public function testBasicTest()
{
    $response = $this->get('/');

    tap($response);

    $response->assertStatus(200);
}
```

3. Got an error:
```
There was 1 error:

1) Tests\Feature\ExampleTest::testBasicTest
ArgumentCountError: Too few arguments to function tap(), 1 passed in /Users/ricardo/Projects/L5.7/tests/Feature/ExampleTest.php on line 19 and exactly 2 expected

/Users/ricardo/.composer/vendor/laravel/valet/cli/includes/helpers.php:143
/Users/ricardo/Projects/L5.7/tests/Feature/ExampleTest.php:19
/Users/ricardo/.composer/vendor/phpunit/phpunit/src/TextUI/Command.php:203
/Users/ricardo/.composer/vendor/phpunit/phpunit/src/TextUI/Command.php:159
```

This is not a problem for me, I just changed the Valet helper `tap` to match Laravel's one.

**Comment by mattstauffer** [comment]
@RicardoRamirezR Your userland code should not be getting the `tap()` helper from Valet, because those are namespaced to `Valet/tap`. What version of Valet are you running?

**Comment by RicardoRamirezR** [comment]
@mattstauffer `Laravel Valet 2.0.12`

**Comment by RicardoRamirezR** [comment]
@mattstauffer updated to 2.1.1 solve the issue, sorry for the noise.
