### ISSUE TITLE
iOS simulator can't access Valet endpoint when my Macbook goes offline

### ISSUE THREAD

**Issue by let-aurn** [laravel/valet#639]
Hi,
I'm using Valet to serve my local Laravel API project (someapi.dev), to be consumed by a React Native code on iOS simulator.

2 problems:

1. My app in iOS simulator can't access the API when my Macbook goes offline (working in a train or in a plane). Safari of iOS simulator says "Your iPhone is not connected to Internet". However, when I hit it from my mac's browser, everything is fine, even offline.
2. Pull Request #515 seems to not solve #390. Still have the warning message in Safari, and my React native app cannot make request..

**Comment by drbyte** [comment]
@let-aurn is this still an issue?

**Comment by drbyte** [comment]
I suggest closing due to no response

**Comment by Gnative** [comment]
In case anyone else comes to this issue looksing for a solution.. 
The iOS simulator will look to use the `/etc/hosts` file from your mac but the Valet settings are not used form some reason when a Mac is offline. 

The solution is to manually add the domains you what access to your /etc/hosts file. For example

```
127.0.0.1 [yourdomain].test
127.0.0.1 api.[yourdomain].text
```
