### ISSUE TITLE
Upgraded to MacOS Mojave and Valet sites no longer working

### ISSUE THREAD

**Issue by LucidNinja** [laravel/valet#642]
Chrome: This site can't be reached, ERR_CONNECTION_REFUSED
Safari: Safari can't connect to the server

I've tried everything mentioned here: https://gist.github.com/adamwathan/6ea40e90a804ea2b3f9f24146d86ad7f#gistcomment-1880793

But with no success. Are there compatibility issues or am I doing something wrong?

**Comment by LucidNinja** [comment]
Ok. I managed to get this working by doing the following:

```
valet uninstall
sudo brew services stop nginx
sudo brew services stop php72
sudo brew services stop dnsmasq
brew uninstall nginx
brew uninstall php72
brew uninstall dnsmasq
rm -rf ~/.config/valet
rm /usr/local/bin/valet
```

Then I followed the standard installation docs, but had to restart my Mac to be able to perform `valet install`, otherwise the installer was not found.

After all of this, it still wasn't working, but I noticed that Chrome and Safari were still trying to access the https:// version, despite having cleared the cache numerous times. As a last ditch effort, I decided to run `valet unsecure` and then `valet secure` again, and voila! Fixed. 

I don't really know what happened here, but we're all good now!

**Comment by zaknesler** [comment]
Good to hear that you got it to work! For me, I was able to do the following:

```
sudo brew services stop nginx
sudo brew services stop php72
sudo brew services stop dnsmasq

valet install
```

**Comment by unr** [comment]
@zaknesler's solution worked for me after upgrading.

However, if you have custom Nginx configs, make sure you back them up first. 🤦‍♂️

**Comment by codeInBit** [comment]
@LucidNinja thank you, your solution work for me.
