### ISSUE TITLE
Why is valet-linux is slow than php artisan serve

### ISSUE THREAD

**Issue by muneebarif11** [laravel/valet#644]
I know its not a laravel question but i want to ask why is valet slow than php artisan serve? 

I open project in browser side by side, one with PHP ARTISAN SERVE and one with VALlET V-Host. Ofcourse valet need to translate it via server config and artisan don't but still it's huge difference. 

I'm running nginx/1.14.0 (Ubuntu) with Php 7.1.* and cpriego/valet-linux package. 

Just to add here, my system is of good specs, 8GB ram, Qurad core, SSD with good transfer rate. and both projects where running with bunch of applications and browser tabs.

Hopefully someone can update here on this.

**Comment by mattstauffer** [comment]
You may want to leave this question on the valet-linux repo instead of the Valet repo. They're not the same project.

https://github.com/cpriego/valet-linux

Thanks!
