### ISSUE TITLE
CLI Error: /usr/local/bin/valet: No such file or directory

### ISSUE THREAD

**Issue by innoscience** [laravel/valet#649]
Ran into this issue when doing:

1. `valet uninstall`
2. `composer global remove laravel/valet`
3. `composer global require laravel/valet`
4. `valet install`

Then it throws the error `/usr/local/bin/valet: No such file or directory`

Was able to resolve the problem by running:

 `source ~/.bashrc`

(Might be  `source ~/.bashrc_profile` for others)

After that, I was able to run valet commands without issue. (Rebooting would also resolve the issue.) Just wanted to note this issue in case anyone else runs into it.

**Comment by drbyte** [comment]
Strange. I did those same 4 steps on the weekend and didn't run into that.

However, thanks for posting - it could be helpful diagnostic for someone in the future.

That said, this issue can also be closed.

**Comment by drbyte** [comment]
This can be closed.
