### ISSUE TITLE
React Native & port 8081

### ISSUE THREAD

**Issue by eightyfive** [laravel/valet#652]
It seems like Valet is using the port 8081 for something but I am not sure what (I suspect the dnsmasq setup).

Regardless of what it is used for, would it be possible to make that port configurable?

The reason why I am asking is because React Native default dev port is also 8081 and it is a pain in the ass to change in RN.

Wondering if that would be easier on Valet side.

**Comment by drbyte** [comment]
Pretty sure Valet doesn't do anything with 8081.  I know it doesn't on my machine.

Try this command to see what processes are using that port:
```sh
sudo lsof -i tcp:8081
```

**Comment by eightyfive** [comment]
Hey @drbyte, thanks for taking the time.

As soon as I `valet start` on my mac, a bunch on nginx processes are launched on port `8081`:

![sudo lsof -i :8081](https://image.ibb.co/mWVPUU/Screen-Shot-2018-10-12-at-14-28-30.png)

**Comment by hainuo** [comment]
changing the conf of nginx which is `/user/local/etc/nginx/nginx.conf` 
nginx.conf or other `server/*.conf` has definded the port 8081

**Comment by eightyfive** [comment]
Quick update on that matter. As it turns out @hainuo pointed me in the right direction and indeed I had some (very old) Nginx configuration using port `8081` in `servers/*.conf`.

Bottom line is @drbyte is right, Valet does not make use of port `8081`.
