### ISSUE TITLE
Cron

### ISSUE THREAD

**Issue by clarkeash** [laravel/valet#657]
Hey, 

What are your thoughts on adding a command to update the crontab file. 
So we could run something like `valet cron:enable` and on laravel it would add `* * * * * php /path-to-your-project/artisan schedule:run >> /dev/null 2>&1` etc.

**Comment by mattstauffer** [comment]
How reliable is the Mac crontab? I remember trying to use it in the past and finding it unusable.

**Comment by clarkeash** [comment]
@mattstauffer Yea, its not been great. Ill just use a docker 😄
