### ISSUE TITLE
Documentation needed for error logs

### ISSUE THREAD

**Issue by Flimm** [laravel/valet#660]
Once you have set up Valet to serve a website, where can you find the access logs and the error logs for that website?

I can see the file `~/.config/valet/Log/nginx-error.log`, but it doesn't seem to contain the access log or the output of the `error_log` function in PHP.

**Comment by josecanhelp** [comment]
Do we need more documentation beyond providing the `valet log` command as an option? 

[Valet Documentation referencing Log Command](https://laravel.com/docs/6.x/valet#other-valet-commands)

The command output is very detailed:
<img width="593" alt="image" src="https://user-images.githubusercontent.com/2329654/70326632-053be000-1803-11ea-873e-18cefbfb2fae.png">

**Comment by drbyte** [comment]
@josecanhelp I tend to agree. I'm not sure much more is needed for documenting this command.

@Flimm or @mattstauffer can close this issue IMO

**Comment by Flimm** [comment]
Thank you for your time!
