### ISSUE TITLE
Feature request: a command to generate hosts file configs for all Valet sites.

### ISSUE THREAD

**Issue by benlk** [laravel/valet#661]
Yes, Valet sets DNSmasq up on the host. But VMs like the [Internet Explorer development VMs](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/) are not configured to use the host OS's DNS. As a result, users of VMs need to be able to easily configure the VM to point to the host's IP address for development sites.

Here's my proposal: A command that, given an IP address as an argument, outputs text compatible with [a `hosts` file](https://en.wikipedia.org/wiki/Hosts_(file)) for all Valet-recognized sites.

Example operation:
```
user:~/valet-dir/$ valet hostsfile 10.0.2.2
10.0.2.2	wordpress.test
10.0.2.2	wordpress-dev.test
10.0.2.2	my-site.test
10.0.2.2	project.test
10.0.2.2	example.test
```
Note that the spacing between the IP address and the domain name should be a tab, not spaces.

This would ideally be paired with a command to list all sites currently served by valet, as `valet links` only shows `valet link`ed sites and `valet path` shows the *parent* directory containing sites, not the sites themselves.

**Comment by drbyte** [comment]
@benlk Valet now includes a `valet parked` command which shows all sites that Valet "could" serve.

You could leverage that to output your list.

**Comment by benlk** [comment]
Yep, that works!

```
$ valet parked | cut -d"|" -f4 | sed -E -e 's/h/127.0.0.1   h/'
+-------------------------+-----+-------------------------------------+------------------------------------------+
 URL                                 
+-------------------------+-----+-------------------------------------+------------------------------------------+
 127.0.0.1	http://thing.test  
+-------------------------+-----+-------------------------------------+------------------------------------------+
```
