### ISSUE TITLE
Allow using http://127.0.0.1 for one of the sites

### ISSUE THREAD

**Issue by Flimm** [laravel/valet#662]
It would be useful if I could tell Valet to let http://127.0.0.1 be used for one of the sites. For example, `valet default-site SITENAME`.

Sometimes, using the custom domain is not helpful. For instance, I am running Android in an emulator. It can access my host machine on the IP address http://10.0.2.2 , but all I get is this HTML document:

```html
<html>
    <head>
        <title>Valet - Not Found</title>

        <style>
            body {
                font-family: monospace;
            }
        </style>
    </head>
    <body>
        404 - Not Found
    </body>
</html>
```

Setting up the emulator to allow for a custom `hosts` file within the emulated Android system is proving to be a hassle. It would be much nicer if I could just tell Valet which site is the default site when only an IP address is provided, rather than a domain for the host name.

**Comment by drbyte** [comment]
You can use xip.io or nip.io for this.

With valet, hitting `http://example.127.0.0.1.xip.io` would hit your `example` project (ie: `example.test`)

**Comment by drbyte** [comment]
No, I understand. And it doesn't in its current state.
I was just offering an alternative.  Since your posts indicate you have control over the URL your emulator hits (ie: setting a 10.x IP or changing the port on 127.0.0.1, etc), I gave you a URL that would hit your valet project.

**Comment by drbyte** [comment]
Valet now lets you specify a `default` parameter in your `~/.config/valet/config.json` file. It will serve this directory if no matching URL is found.

This can be closed.

**Comment by Flimm** [comment]
Thank you so much! Like @drbyte said, modifying the `default` parameter works. For anyone else trying to get this working, know that you need to include the full path, so that the configuration file `~/.config/valet/config.json` looks like this:

```json
{
    "domain": "test",
    "paths": [
        "/home/example/.config/valet/Sites"
    ],
    "tld": "test",
    "default": "/home/example/examplesite"
}
```
