### ISSUE TITLE
Not works with Forticlient VPN?

### ISSUE THREAD

**Issue by endigo** [laravel/valet#664]
Forticlient breaks DNS settings or conflicts.

Any solutions with Forticleint VPN?

**Comment by drbyte** [comment]
Perhaps your VPN client has an option to specify using only its own DNS when active?
See this solution for ExpressVPN: https://github.com/laravel/valet/issues/527#issuecomment-427967761

**Comment by drbyte** [comment]
Additionally, you could specifically insert `127.0.0.1` in your Mac's list of DNS servers to use, preferably as the first entry. And then you could also add `1.1.1.1` for CloudFlare and `8.8.8.8` for Google as additional alternates. 

I imagine Forticlient probably adds its own when in use, but I'm not sure if they also override your own settings.

System Preferences->Networking->Advanced->DNS

**Comment by arwinvdv** [comment]
Same problem here, when I install the FortiClient ZTNA version, laravel valet is not working anymore. Also setting manually the DNS in System Preferences is not working. When I uninstall the FortiClient it is working again.

For now I change manually my host file (/ets/hosts) to fix the issue. But if someone has a solution, let me know!

**Comment by ninety3** [comment]
@arwinvdv what you have changed in your hosts file?

**Comment by arwinvdv** [comment]
@ninety3 I added the local domainname to the 127.0.0.1 line.
Example:
`127.0.0.1 localhost dirname1.test dirname2.test`

**Comment by keizah7** [comment]
Removed custom DNS servers and valet started working again

**Comment by keizah7** [comment]
> 127.0.0.1 localhost dirname1.test dirname2.test

You manually declaring all valet projects?

**Comment by TobiasFeld** [comment]
> @ninety3 I added the local domainname to the 127.0.0.1 line. Example: `127.0.0.1 localhost dirname1.test dirname2.test`

Sorry but this could not be the solution. There must exist a better solution :/

**Comment by fahu** [comment]
We are experiencing the same issue :( Until now, the only workaround is declaring pages manually in `/etc/hosts`.

**Comment by duikb00t** [comment]
This problem is today (almost 2023) still active. 

Anyone found a good fix for this instead of adding domains manually to the hosts file?

**Comment by jonatanolsson** [comment]
I don't use the forticlient so much, so i removed the LaunchDeamons and rebooted. Success

Those who are using it on a daily basis should wait

`
cd /Library/LaunchDaemons
sudo rm -rf com.fortinet.forticlient.*
`

This is a part of their uninstall process
https://community.fortinet.com/t5/FortiGate/Technical-Tip-How-to-uninstall-FortiClient-on-macOS/ta-p/229617

**Comment by elburro1887** [comment]
@jonatanolsson Your solution worked for me, but I also had to remove the

`com.fortinet.forticlient.* `

files from

`/Library/LaunchAgents`
