### ISSUE TITLE
"valet install" does not create ~/.valet

### ISSUE THREAD

**Issue by Danny-G-Smith** [laravel/valet#666]
I am having a terrible time installing valet, which is strange, because it is normally painless.  When I run 
valet install, I get all of the correct messages, but there is not ~/.valet when it is finished.
https://cl.ly/708f67a01bef

**Comment by drbyte** [comment]
Yes. In v2.1.0 it was relocated to the ~/.config/valet directory, to match the location of many other app "configs".
https://github.com/laravel/valet/releases/tag/v2.1.0

**Comment by Danny-G-Smith** [comment]
Ok, I was having an issue, and saw that, and just assumed it was the issue.  Sorry, I will dig deeper.

**Comment by joshlewis** [comment]
I just wasted half an hour trying to figure out where my files went. ☹️ This change was not well handled.
