### ISSUE TITLE
Valet suddenly  stop working 

### ISSUE THREAD

**Issue by guytzhak** [laravel/valet#673]
Hi,
Laravel valet suddenly stop working and don't display any folder.

I tried to park again, and do many things but nothing happened.

I tried to unistall and re-install valet but no-matter that I does, my terminal say "zsh: command not found: valet"

What I can do?

My compter is Mac book pro. macOS Mojave

**Comment by drbyte** [comment]
First thing I'd suggest is run `composer global require laravel/valet` to re-run the installation of the actual valet code.

If that fails then you might also have issues with your shell PATH. But I'd start with the above.
It really sounds like you've messed up your shell environment -- which is way beyond the Valet project.

**Comment by guytzhak** [comment]
I restart the computer. than remove composer, brew and everything that connected to larave valet. and than install all of them ...
and it's work.

I think you right and the problem from the begining is this PATH.

thanks
