### ISSUE TITLE
Adding PHP Server Environment Variable (from computer paths)

### ISSUE THREAD

**Issue by ahinkle** [laravel/valet#682]
Hi, I've been working on this issue for a little over a week and finally decided to open up an issue to hopefully find a resolution.

I need to add `ORACLE_HOME` to my PHP Server Path. I've added it to my local paths but it won't appear even after I do a Valet restart, etc.

Local Paths (➜  ~ env):
```
USER=andy
ORACLE_HOME=/Applications/oracle/product/instantclient_64/11.2.0.4.0

... + more irrelevant paths
```

PHP Info:
<img width="984" alt="screen shot 2018-12-07 at 1 33 07 pm" src="https://user-images.githubusercontent.com/17038330/49668726-a93e5000-fa24-11e8-80fc-b5d907c7096a.png">

Is there somewhere I can edit a configuration file to add the server variables? Should they pick up automatically?

I tried using this method:
https://github.com/laravel/valet/issues/220#issuecomment-263464950

but the files no longer exist for a site specific within Valet. The files in that specified location are no longer there. Have they been moved?

Thanks!

**Comment by drbyte** [comment]
That #220 issue was for Valet v1 which used Caddy, which stored configs in a different spot.

The config files are now located in `~/.config/valet` and for your case, in the `Nginx` subdirectory.

So, find your site config there, and inside the file find both of the `fastcgi_param SCRIPT_FILENAME .....` lines and add your own ORACLE_HOME param on the line below, ie:

`fastcgi_param ORACLE_HOME /Applications/oracle/product/instantclient_64/11.2.0.4.0`

**Comment by ahinkle** [comment]
Thanks for the quick response @drbyte! Unfortunately, I don't see any config files within the Nginx subdirectory. Am I in the right place?
<img width="934" alt="screen shot 2018-12-08 at 10 28 53 am" src="https://user-images.githubusercontent.com/17038330/49688206-2d034580-fad4-11e8-8157-eb3b05059e5d.png">

**Comment by ahinkle** [comment]
Figured it out -- it was actually something completely unrelated.

For anyone trying to connect to a Oracle Database:
We previously were working on windows when 
`APP_DB_TNS=CONNECTIONNAME`
worked fine, I changed it to `APP_DB_TNS=CONNECTIONNAME.DOMAIN.COM`

You can debug the connection within `sqlplus`.

**Comment by drbyte** [comment]
Glad you got it sorted out.

> I don't see any config files within the Nginx (~/.config/valet/nginx)subdirectory. Am I in the right place?

Apologies for the confusion, I meant to also mention that you would need to `valet link [domain]` in order to generate the specific Nginx config. (It doesn't generate configs for things served from the generic `valet paths` dir, unless you specifically link them.)
