### ISSUE TITLE
Secured valet project not sending emails

### ISSUE THREAD

**Issue by chadmazilly** [laravel/valet#684]
I'm successfully using a secured domain in valet. I copied mail configuration over from a working Homestead setup that was using Mailtrap and emails do not appear to be sent in Valet. I've tried combinations of different ports (25, 465, 2525) and mail authentication config values (null, tls) but nothing, though sometimes Swift complains about not being able to connect with certain combinations.

I then installed Mailhog locally, reconfigured the Laravel project's mail settings, and tested. I cannot get email to render in Mailhog either.

I do know that the email is being fired as I've switched the mail driver to `log` and can see the HTML there.

Any help would be much appreciated, thanks!

**Comment by drbyte** [comment]
I suspect you've got some other config that's interfering.

Creating fresh Laravel apps in Valet and setting them to send via Mailtrap.io works fine for me. (I just did two of those this morning.)

Possible culprits:
- firewall apps blocking PHP from sending
- mail set to be queued, but no queue workers running or no queue providers configured

**Comment by chadmazilly** [comment]
Thanks for the quick response @drbyte. The mail is in fact set to be queued but the queue driver is `sync` so I'm assuming this shouldn't be the issue, no? I'll have to take a look at the firewall stuff, but this is a fresh macbook and fresh install of homebrew, valet, etc. so I have not voluntarily set up any firewall apps.

**Comment by drbyte** [comment]
I installed on a fresh macbook and had no issues. Hmmm ....

**Comment by chadmazilly** [comment]
All good. I am embarrassed to admit that it was because I was not calling the "->to()" method on the mailable. Doh! But thanks for your feedback though.

**Comment by drbyte** [comment]
Ha! No worries! Been there, done that! ... more times than I care to admit!
