### ISSUE TITLE
Issues with PHP 7.3 and Xdebug 2.7.0beta1

### ISSUE THREAD

**Issue by ihorvorotnov** [laravel/valet#685]
- macOS Mojave
- Valet 2.1.5
- PHP 7.3.0 via Homebrew
- Xdebug 2.7.0beta1 via PECL

The Xdebug extension was built and installed without any issues, it is loaded and works. However, there's quite some issues:

1. Any `valet` command fails:
```
/usr/local/bin/valet: line 63: 17031 Segmentation fault: 11  php "$DIR/cli/valet.php" "$@"
```
2. Running `sudo brew services restart php` instead of `valet restart` works fine.
3. WordPress sites don't work, 502 error is returned with log entry:
```
2018/12/14 14:47:45 [error] 15719#0: *8 upstream prematurely closed connection while reading response header from upstream, client: 127.0.0.1, server: vidico.test, request: "GET / HTTP/2.0", upstream: "fastcgi://unix:/Users/Ihor/.config/valet/valet.sock:", host: "vidico.test"
```
No additional PHP-related error info.
4. However, a vanilla Laravel project that simply dumps `phpinfo()` works fine, shows Xdebug loaded, `var_dump()` is overloaded by Xdebug (so it kinda works).

I understand that 7.3 support in Xdebug is still in beta, and issues are expected. Will be happy to dive deeper and investigate that cli segfault and 502 error if someone points where to look for additional debug info.

**Comment by stefanos82** [comment]
Since the introduction of PHP 7.3.0-rc4-1, at least under Debian, it segfaults like crazy. I have tested it with 7.3.0-1 as well, but still behaves the same.

As soon as I switch back to 7.2.9-1, everything works as expected.

**Comment by ihorvorotnov** [comment]
@stefanos82 PHP 7.2.13 with Xdebug 2.6.1 (stable) works perfectly fine for me. PHP 7.3.0 - nope.

**Comment by stefanos82** [comment]
@ihorvorotnov Yep, it must be a bug with 7.3.0.

Another person reported the same behavior https://laracasts.com/discuss/channels/code-review/homestead-502-bad-gateway-for-php-73-web-app-works-with-72

**Comment by MartijnDevNull** [comment]
Disabling opcache seems to work: https://externals.io/message/103609

At least it wont segfault, can't get it to connect

**Comment by ihorvorotnov** [comment]
@MartijnDevNull thanks for your input. I personally rolled back to 7.2 for now, hope it'll be fixed soon.

**Comment by MartijnDevNull** [comment]
It will be fixed in the next version:
https://github.com/xdebug/xdebug/pull/438

**Comment by drbyte** [comment]
IMO This can be closed, as it's not in Valet's control.

**Comment by fjarrett** [comment]
Looks like it's fixed as of RC1, here's what just worked for me:

```
pecl install xdebug-2.7.0RC2
valet restart
```
