### ISSUE TITLE
Home directory containing spaces breaks some commands.

### ISSUE THREAD

**Issue by sahibalejandro** [laravel/valet#691]
Hi, I sent a PR to fix a problem with the installation when the home directory contains spaces.
This is the original issue: https://github.com/laravel/valet/issues/678

But today I found that usernames containing spaces also breaks more commands like `valet share`, for example, if your username is `john doe` and you run `valet share` it will throw this error:

````
grep: /Users/john: No such file or directory
grep: doe/.config/valet/Nginx/valet*: No such file or directory
````
Caused by not surrounding username on this line: https://github.com/laravel/valet/blob/master/valet#L55

This extends to other commands and files where username is not surrounded with quotes, like those:
https://github.com/laravel/valet/blob/master/cli/stubs/nginx.conf#L1
https://github.com/laravel/valet/blob/master/cli/stubs/nginx.conf#L40

I'm working on a PR to fix this completely.

**Comment by sahibalejandro** [comment]
I found that also `valet secure` won't work with usernames containing blank spaces.
The PR I just sent fix that too.

**Comment by drbyte** [comment]
This can be closed, since the PR has been merged and released.
