### ISSUE TITLE
Cannot access subpages in my project

### ISSUE THREAD

**Issue by Mehz0rs** [laravel/valet#694]
Hi!

I'm rather new to Valet, and wouldn't know where to look for an answer to this:
I've been working on a website using localhost. The homepage loads just fine on my localhost, but when I start adding subpages and using links to them I get a 404 page.

Do I have to do something in Valet before I can add and start viewing a subpage?

To be clear, my index.html loads just fine (it shows my localhost custom url), but my agenda.html gives a 404 page with thesamelocalhostcustomurl/agenda. (for example)

I've been Googling a lot to find an answer to this, but don't know what to look for so I hope someone here can help me. I'm sorry if this isn't the right place to ask, but I really have no clue where to find an answer to this.

**Comment by mattstauffer** [comment]
If you want `mywebsite.com/agenda` to work, you need to create a file that would be `mywebsite.com/agenda/index.html`. `index.html` is a special privileged filename that most web servers look for by default. So, basically, you can always drop `index.html` off the end of your URL and it should still serve correctly; when you try to access a folder (in your case, the `agenda` folder), you'll get the `index.html` in that folder.
