### ISSUE TITLE
Trailing slashes in valet

### ISSUE THREAD

**Issue by bronze** [laravel/valet#696]
Hello

I have a simple html file (trying to start my way with valet) and in it i have a 
`<link rel="stylesheet" href="./css/main.css">`
 
Thing is, `home.test/app` doesnt show my styled html, while in `home.test/app/` it is styled.
Ive been googling a cause/fix for some time and i cant wrap my head around it. should i do a nginx.conf in the folder? change valet's home.conf?

Id like it to always add a trailing slash at the end of a url if possible.

edit: words are hard

**Comment by bronze** [comment]
Screenshot showing the chrome inspector. This is under home.test/app. It doesnt recognize the subfolder of the url unless theres a trailing slash...
![screen shot 2019-01-06 at 08 32 23](https://user-images.githubusercontent.com/170220/50734926-ceda8880-118d-11e9-9acb-e311b1631701.png)

**Comment by ryanmortier** [comment]
What happens if you remove the `./` at the beginning in the `href` attribute?

**Comment by drbyte** [comment]
I have indeed run into this same issue.

Never found a permanent solution for it. Have settled with the workaround of adding the trailing `/`.

**Comment by egyptik** [comment]
Same issue here. Is this a problem with the NGINX config?

**Comment by driesvints** [comment]
Closing this issue because it's inactive, already solved, old or not relevant anymore. Feel to open up a new issue if you're still experiencing this.

**Comment by iantearle** [comment]
Is there a solution to this? Seems a simple thing to achieve but I can find now solution. @bronze did you achieve a trailing slash?
