### ISSUE TITLE
Driver does not fully work with Kirby 3

### ISSUE THREAD

**Issue by HashandSalt** [laravel/valet#704]
Kirby 3 got released today, and now includes an upgrade script [described here](https://getkirby.com/docs/cookbook/migration/sites#folder-and-file-structure) that doesn't seem to be handled by the built in Valet driver for Kirby. It seems to prevent access to `upgrade.php`.

**Comment by lekkerduidelijk** [comment]
Running into the same issues. I'm investigating how to update the driver to make it work. 
This is also needed for `/panel` access.

**Comment by HashandSalt** [comment]
> Running into the same issues. I'm investigating how to update the driver to make it work.
> This is also needed for `/panel` access.

The panel should be working fine. I discovered how to get the upgrade to work by amending the driver. Theres a [gist here](https://gist.github.com/HashandSalt/ae3f34132bc11429dead4dc2f24887e3).

**Comment by lekkerduidelijk** [comment]
Accessing the panel with `domain/panel` returned:

`Warning: chdir(): No such file or directory (errno 2) in /Users/xx/.composer/vendor/laravel/valet/server.php on line 145`

`Warning: require(/Users/xx/www/domain/panel/index.php): failed to open stream: No such file or directory in /Users/xx/.composer/vendor/laravel/valet/server.php on line 147`

`Fatal error: require(): Failed opening required '/Users/xx/domain/panel/index.php' (include_path='.:/usr/local/Cellar/php/7.2.12_2/share/php/pear') in /Users/xx/.composer/vendor/laravel/valet/server.php on line 147`

👉 **Updated**
Seems I was running an older Valet version (2.0.12). After upgrading to the latest (2.1.5) and applying the [PHP 7.3 fix](https://github.com/laravel/valet/issues/695#issuecomment-451200459) it's running smoothly 👍

**Comment by drbyte** [comment]
@HashandSalt if this is resolved, would you mind closing it?
