### ISSUE TITLE
 Call to undefined function collect() 

### ISSUE THREAD

**Issue by okaufmann** [laravel/valet#706]
I'm getting this error after a clean new install on a Mojave (10.14.2 (18C54)) MacBook Pro.

Other Laravel helper-functions like `dd` do work.

Any Ideas?

## Steps to reproduce

    composer global require laravel/valet
    valet install

```
PHP Fatal error:  Uncaught Error: Call to undefined function collect() in /Users/okaufmann/.composer/vendor/laravel/valet/cli/Valet/Configuration.php:192
Stack trace:
#0 /Users/okaufmann/.composer/vendor/laravel/valet/cli/includes/helpers.php(149): Valet\Configuration->Valet\{closure}(Array)
#1 /Users/okaufmann/.composer/vendor/laravel/valet/cli/Valet/Configuration.php(195): Valet\tap(Array, Object(Closure))
#2 /Users/okaufmann/.composer/vendor/laravel/valet/cli/includes/facades.php(28): Valet\Configuration->prune()
#3 /Users/okaufmann/.composer/vendor/laravel/valet/cli/valet.php(40): Facade::__callStatic('prune', Array)
#4 {main}
  thrown in /Users/okaufmann/.composer/vendor/laravel/valet/cli/Valet/Configuration.php on line 192

Fatal error: Uncaught Error: Call to undefined function collect() in /Users/okaufmann/.composer/vendor/laravel/valet/cli/Valet/Configuration.php on line 192

Error: Call to undefined function collect() in /Users/okaufmann/.composer/vendor/laravel/valet/cli/Valet/Configuration.php on line 192

Call Stack:
    0.0006     451368   1. {main}() /Users/okaufmann/.composer/vendor/laravel/valet/cli/valet.php:0
    0.2403    1870352   2. Facade::prune() /Users/okaufmann/.composer/vendor/laravel/valet/cli/valet.php:40
    0.2403    1870352   3. Facade::__callStatic() /Users/okaufmann/.composer/vendor/laravel/valet/cli/valet.php:40
    0.2409    1943824   4. Valet\Configuration->prune() /Users/okaufmann/.composer/vendor/laravel/valet/cli/includes/facades.php:28
    0.2413    1944784   5. Valet\tap() /Users/okaufmann/.composer/vendor/laravel/valet/cli/Valet/Configuration.php:195
    0.2413    1944808   6. Valet\Configuration->Valet\{closure}() /Users/okaufmann/.composer/vendor/laravel/valet/cli/includes/helpers.php:149
```

**Comment by okaufmann** [comment]
Laravel Support 4.2 was installed globally for whatever reason.

**Comment by okaufmann** [comment]
Finally, a global composer package based on old packages was installed. I uninstalled all global composer packages and reinstalled them with https://github.com/consolidation/cgr, then valet worked again.

**Comment by bjuppa** [comment]
`composer global remove laravel/installer` made `valet install` work again for me!

**Comment by drbyte** [comment]
> `composer global remove laravel/installer` made `valet install` work again for me!
> 
> I think this is a hint why:
> 
> ```
> ...
> - Removing illuminate/support (v4.2.17)
> - Installing illuminate/support (v6.18.1)
> ...
> ``
> ```

Yes, that's most likely because of the dependencies required by that older version of `laravel/installer` that you had.  It's good to occasionally go through and update the versions of all those things you have in your global composer config, to be sure you're using modern versions of them.

You can most likely add it back again now without issue. Just a `composer global require` will grab the latest version.

**Comment by njoguamos** [comment]
U resolved by removing `laravel/installer` globally

**Comment by njoguamos** [comment]
> Yes, that's most likely because of the dependencies required by that older version of `laravel/installer` that you had. It's good to occasionally go through and update the versions of all those things you have in your global composer config, to be sure you're using modern versions of them.
> 
> You can most likely add it back again now without issue. Just a `composer global require` will grab the latest version.

Removing global packages with `illuminate/support` dependencies helped.
