### ISSUE TITLE
When running valet stop it runs stop on all installed php versions, this can be slow

### ISSUE THREAD

**Issue by jrbarnard** [laravel/valet#708]
E.g if you have php@5.6, php@7.0, php@7.1, php@7.2 all installed it will call stop on all even though say on php@7.2 is running. 

We could instead look at the currently running services before deciding what to pass to Brew::stopService().

As part of the work for #378 I've got code that would allow us to do this quite easily, so we could potentially swap the PhpFpm::stop() with PhpFpm::stopRunning();

PR for this new functionality: #710 

I'm happy to link this with the PR #378 and then update the PhpFpm::stop calls to stopRunning in a new PR if the other one gets approved.

**Comment by drbyte** [comment]
#710 has been merged.

**Comment by jrbarnard** [comment]
@drbyte  @mattstauffer  The underlying issue still exists, the PR that was merged included code that can be used to fix the issue but didn't fix the issue.

Here's a screen shot showing the issue:
<img width="545" alt="Screen Shot 2019-09-27 at 08 30 27" src="https://user-images.githubusercontent.com/6758366/65750958-770bf500-e101-11e9-82c7-f5585cbd3fe0.png">

I'll put a PR together to update this to look for the currently running version of PHP before stopping?
