### ISSUE TITLE
Always got "www" in front of domain. 

### ISSUE THREAD

**Issue by ThunderBirdsX3** [laravel/valet#714]
With default of domain `.test`. It fine.

![screen shot 2562-01-24 at 10 52 43](https://user-images.githubusercontent.com/6513358/51653744-67af3780-1fc7-11e9-8011-ba940333b37a.png)

But when I change domain to `.local` (May be other too). It would get `www` appear in front of domain name.

![screen shot 2562-01-24 at 10 57 02](https://user-images.githubusercontent.com/6513358/51653792-93cab880-1fc7-11e9-8340-9eca19d88322.png)

![screen shot 2562-01-24 at 10 59 13](https://user-images.githubusercontent.com/6513358/51653794-96c5a900-1fc7-11e9-92eb-6188fe9d1a66.png)

And it can't remove unless you put `sac.local` to `/etc/hosts`

**Comment by drbyte** [comment]
@ThunderBirdsX3 I've never been able to trigger this. (Although if it's an issue I'd be suspecting the nginx config file for that domain as not having the proper redirects set up.)

Is it still an issue in a current version of Valet? If not, would you mind closing this issue?
