### ISSUE TITLE
Load build/ directory in project as root

### ISSUE THREAD

**Issue by Sulcalibur** [laravel/valet#715]
I have numerous website in a development directory on my computer but I use a load of stylus, pug etc and the actual website is in a build directory inside the project. How would I load that content in Valet as the project valet url?

Example:

Development `valet park`
- projectname
    - build
        - index.html

So I load the contents of `build` but have the valet url of `projectname.dev`

**Comment by drbyte** [comment]
You could create a custom driver that specifies `/build` as the location of your files. 
There are numerous examples already in Valet: https://github.com/laravel/valet/tree/master/cli/drivers and the docs have a section on custom drivers.

**Comment by drbyte** [comment]
IMO this can be closed, as a solution has been provided.
