### ISSUE TITLE
Out-of-the-box Access to Individual Site Error/Access Logs and Server Blocks

### ISSUE THREAD

**Issue by kerns** [laravel/valet#718]
Sorry. I'm new to Valet and have not been able to find a community or support area elsewhere to discuss it. So I'm posting here. More of a feature request really. Maybe I'll find out it already exists and I just haven't succeeded in finding it.

1) Easier Way to Generate/Expose Specific Access and Error Logs
I understand this used to be an option with Valet but was removed in the change to nginx? Would be great if there was a single command to expose or tail these site specific logs a little more easily. Digging into .config/Valet/... for the server block, setting up logs to output at the desired path, making sure the server has permission to write at that path....this is exactly the sort of routine hustle I'd like Valet to try and smooth over.

2) Easier Way to Expose Site Specific .conf file.
There are very few content management systems I know of that don't want or expect some server tweaking via the vhost or server block. And while we all know the real work needs to be done in a stage environment closer to production, it would still be handy to have this site block (read vhost) quickly exposed with an additional valet command. I can hack this together myself, I'm just not sure why it's not baked in.

---

Is there a supported way to add custom commands to Valet?

**Comment by drbyte** [comment]
> Is there a supported way to add custom commands to Valet?

Yes. You can put your own custom commands in your `~/.config/valet/Extensions` folder.

**Comment by drbyte** [comment]
The `valet log` command allows tailing of related log files.

The `./config/valet/Nginx` folder stores your site-specific nginx configs.

**Comment by drbyte** [comment]
@mattstauffer I believe this can be closed.
