### ISSUE TITLE
New features need documentation

### ISSUE THREAD

**Issue by mattstauffer** [laravel/valet#719]
- [x] `valet use php@X.x` (https://github.com/laravel/valet/pull/710)
- [x] env vars (https://github.com/laravel/valet/pull/474)
- [x] `valet tld`, in case we didn't document the change
- [x] Other things??

**Comment by mattstauffer** [comment]
@jalendport sweet! I think this is it:
https://github.com/laravel/docs/blob/5.7/valet.md

**Comment by jalendport** [comment]
@mattstauffer ah cool... Thanks!

**Comment by ahinkle** [comment]
Valet Use: https://github.com/laravel/docs/pull/4953

I'll have to play around more with env vars before submitting some official documentation. The entire `.env.valet` vs `.valet-env.php` threw me off.

Got a PR link for Valet TLD? I searched through the recent PRs but no luck.

**Comment by mattstauffer** [comment]
@ahinkle great! the change is just that we deprecated `valet domain` and replaced it with `valet tld`.

**Comment by ahinkle** [comment]
> * `valet tld`, in case we didn't document the change

https://github.com/laravel/docs/pull/4966

**Comment by mattstauffer** [comment]
@ahinkle 🙌

**Comment by ahinkle** [comment]
> - env vars (#474)

https://github.com/laravel/docs/pull/5038

Should be all set. 👍

**Comment by mattstauffer** [comment]
Thank you @ahinkle !!
