### ISSUE TITLE
Homebrew fails to install nginx because of removal of with http2 option

### ISSUE THREAD

**Issue by zchrykng** [laravel/valet#725]
Homebrew has recently been working to strip options from formulas. Thus Valet fails to install nginx because it specifies `--with-http2`, which is no longer an option.

See homebrew/homebrew-core#31510 😢

**Comment by drbyte** [comment]
@zchrykng Thanks for posting this.

Would you please update the title of this to add something like ..."with http2 option" or something that adds specificity to the issue's meaning?

The good news is that it looks like the nginx formula has been updated to include the http2 option: https://github.com/Homebrew/homebrew-core/blob/175af0f78ca84574424ee12d940dfb16e0543652/Formula/nginx.rb#L64

This means we should be able to drop that flag from Valet's logic for new installs. 
Existing nginx installs are unaffected. 

Until Valet is updated, one could `brew install nginx` manually before running `valet install`.

**Comment by erikgyepes** [comment]
Same issue here, on clean Mac OS Mojave install.

^^^ `brew install nginx` looks like fixed the issue.

**Comment by zchrykng** [comment]
@drbyte Just created a pull request that I think will fix the issue. Since it seemed simple I just took a shot at it. #726
