### ISSUE TITLE
After switching to php@5.6,, cannot come back to 7.2

### ISSUE THREAD

**Issue by filipac** [laravel/valet#727]
Hello, I tried switching to php@5.6 that I have installed with brew. Until now, I manually edited the site file in ~/.config/valet/Nginx/*.conf but now I wanted to try the new feature. Now I cannot come back to 7.2 with the same command.

One thing to mention is that you should not support versions older than Valet supports.
Or maybe some warning in the docs/repo to mention that you can come back to newer `php using brew link php --overwrite`

```➜ in App valet use php@5.6
Stopping php...
Unlinking current version: php
Linking new version: php@5.6
Updating PHP configuration...
Restarting php@5.6...
Restarting nginx...
Valet is now using php@5.6.

➜ in App php -v
PHP 5.6.38 (cli) (built: Nov 27 2018 06:16:39)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies

➜ in App valet use php@7.2
PHP Parse error:  syntax error, unexpected '->' (T_OBJECT_OPERATOR) in /Users/filipac/.composer/vendor/illuminate/support/Collection.php on line 181

Parse error: syntax error, unexpected '->' (T_OBJECT_OPERATOR) in /Users/filipac/.composer/vendor/illuminate/support/Collection.php on line 181
```

**Comment by mattstauffer** [comment]
Huh. I honestly thought we still supported 5.6, honestly. Will try to look at it later today—sorry about that! But that’s a good point. We can’t let you switch to a version that will make valet stop working.

**Comment by filipac** [comment]
Yeah, I did now how to link it back though, maybe someone else does not know that.

**Comment by drbyte** [comment]
The best solution is to drop PHP 5.6 support from Valet altogether, especially considering you can't install it from homebrew anymore (without using 3rd party kegs).

A bridge in the meantime is to force your global composer config to only support PHP 5.6:
```
composer global config platform.php 5.6.36
composer global update
```

Quoting from ref: https://github.com/laravel/valet/pull/535#issuecomment-401382906

**Comment by drbyte** [comment]
IMO this can be closed.
