### ISSUE TITLE
Valet secure issue after upgrading ERR_CONNECTION_REFUSED BIO_new_file

### ISSUE THREAD

**Issue by bmakowski** [laravel/valet#731]
All sites are returning ERR_CONNECTION_REFUSED in Chrome.
`2019/02/13 15:54:39 [emerg] 30103#0: BIO_new_file("/Users/user/.valet/Certificates/site.dev.conf.crt") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/Users/user/.valet/Certificates/site.dev.conf.crt','r') error:2006D080:BIO routines:BIO_new_file:no such file)`

PHP 7.3.2
Valet 2.2.1

Ping works fine, so it looks like a cert problem.

**Comment by drbyte** [comment]
The valet configs were relocated to /users/user/.config/valet several versions ago.
Things inside Valet's control should have been updated automatically.
But if this error is coming from some other source (ie: you said it's Chrome, so does Chrome have the cert paths stored somewhere?), then you'll have to update those manually.

**Comment by bmakowski** [comment]
@drbyte thanks. I removed old config from the site that was causing the issue and it works fine.
