### ISSUE TITLE
Could not establish a secure connection to wordpress.org

### ISSUE THREAD

**Issue by markushasselryd** [laravel/valet#733]
Hi,
I've got a problem with connecting to wordpress.org. Also got this "RSS-error: WP HTTP Error: cURL error 28: Resolving timed out after 10031 milliseconds". Valet was working fine until I downloaded yarn with all its dependencies. Can't update or download plugins. I've reinstalled Valet several times and reinstalled php, dnsmasq, nginx and curl in the process. Right now I'm stuck... can someone point me in the right direction and give me a hand?

**Comment by ihorvorotnov** [comment]
Re WordPress.org connection error - that's 99.999% not related to Valet, it happens from time to time with wordpress.org API. Usually goes away quickly.

**Comment by markushasselryd** [comment]
Ok, I thought it could be related to curl or openssl... it happens to all of my local sites.

**Comment by ihorvorotnov** [comment]
Well, technically, openssl isn't related to Valet as well.

**Comment by markushasselryd** [comment]
Hmm... ok. Tried to download Wordpress using wp cli, same issue there. If its not related to Valet, any suggestions how I move on?

**Comment by ihorvorotnov** [comment]
You can start here:

https://docs.presscustomizr.com/article/326-how-to-fix-a-curl-error-28-connection-timed-out-in-wordpress
https://www.samuelaguilera.com/post/curl-error-28-wordpress
https://github.com/docksal/docksal/issues/312

**Comment by markushasselryd** [comment]
Ok, thanks for your help.

**Comment by ryanscherler** [comment]
I know this issue is closed, but @markushasselryd did you ever solve your issue? I am running into the same problem and it hasn't seemed to resolve.

**Comment by markushasselryd** [comment]
Hi @ryanscherler, I managed to solve it. The problem was my local DNS-server, I changed it to Googles 8.8.8.8 and everything worked fine after that.

**Comment by ryanscherler** [comment]
Gotcha - I ended up updating both my router and my local dns with openDNS servers and that seemed to solve it. This stuff baffles me.

**Comment by JPry** [comment]
I was running into a similar problem, and it seems that DNS settings were to blame for me as well. I changed mine to use [1.1.1.1 by Cloudflare](https://one.one.one.one/dns/) (for those who might want to avoid using Google). This fixed the curl errors.

**Comment by angelozehr** [comment]
I could not fetch theme or plugin information from wordpress.org on my local valet wordpress intallation. Switching the DNS helped 👍 thank you!
I followed the steps on <https://one.one.one.one/dns/> for Mac OS:
1. Open System Preferences.
2. Search for DNS Servers and select it from the dropdown.
3. Click the + button to add a DNS Server and enter 1.1.1.1
4. Click + again and enter 1.0.0.1 (This is for redundancy.)
7. Click Ok, then click Apply.
⚡️

**Comment by drbyte** [comment]
> I could not fetch theme or plugin information from wordpress.org on my local valet wordpress intallation. Switching the DNS helped 👍 thank you!
> I followed the steps on https://one.one.one.one/dns/ for Mac OS:
> 
> 1. Open System Preferences.
> 2. Search for DNS Servers and select it from the dropdown.
> 3. Click the + button to add a DNS Server and enter 1.1.1.1
> 4. Click + again and enter 1.0.0.1 (This is for redundancy.)
> 5. Click Ok, then click Apply.

NOTE:
If you have no 127.0.0.1 entry, or if you've put either of those "above" the 127.0.0.1 entry, then Valet won't be able to serve you the `.test` domains from your Mac.

**Comment by kevinmamaqi** [comment]
I'm having the same problem but the public DNS doesn't work. I've tried Google, Cloudflare and I also added 127.0.0.1 at the beginning from my Mac. Does any one knows what other problem might it be?

**Comment by elanclarkson** [comment]
> > I could not fetch theme or plugin information from wordpress.org on my local valet wordpress intallation. Switching the DNS helped 👍 thank you!
> > I followed the steps on https://one.one.one.one/dns/ for Mac OS:
> > 
> > 1. Open System Preferences.
> > 2. Search for DNS Servers and select it from the dropdown.
> > 3. Click the + button to add a DNS Server and enter 1.1.1.1
> > 4. Click + again and enter 1.0.0.1 (This is for redundancy.)
> > 5. Click Ok, then click Apply.
> 
> NOTE:
> If you have no 127.0.0.1 entry, or if you've put either of those "above" the 127.0.0.1 entry, then Valet won't be able to serve you the `.test` domains from your Mac.

Adding this entry fixed my problem right away - thank you @drbyte!

In my case the .test domains were still working but the admin updates screen was loading painfully slowly and it wasn't detecting the latest WP update when it did eventually load. I guess this was coming from DNS cache or something...
