### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by KickSchutte67** [laravel/valet#735]
Hello I've been trying to get valet working on Mac but I get "File not found" when opening my project with app.test.

Any solutions?

**Comment by drbyte** [comment]
Is it `File not found`?  or is it actually `404 - Not Found`?

Lots of context missing here. How did you "get" the "File not found" message? browser? command line? 
What would I need to do on my computer to test/recreate the same symptom that you're encountering?

**Comment by KickSchutte67** [comment]
Thanks for your quick reply!

I am currently not at work, so I can't access the files. Sorry for that, I was too frustrated.

It is "File not found" error, I get it in the browser. I use Chrome. I parked my folder via iTerm, folder: Users/****/sites. 

When I check the paths it will not recognize any other folders inside the path folder. I am also 100% sure I am creating new projects inside this "sites" folder.

**Comment by drbyte** [comment]
@KickSchutte67 is this still an issue?

**Comment by drbyte** [comment]
Should close due to inactivity.
