### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by sirjonathan** [laravel/valet#737]
I've been attempting to install Valet off an on for the past week. I've carefully performed and uninstall using these instructions: https://tommcfarlin.com/when-valet-stops-working/

Then, I've worked carefully through each of the steps here: https://laravel.com/docs/5.7/valet

I make it all the way up to "valet install" and I get this:

```
MacBook-Air:~ jonathanwold$ valet install
Password:
Stopping nginx...
Installing nginx...
[nginx] is not installed, installing it now via Brew... 🍻
==> Downloading https://homebrew.bintray.com/bottles/nginx-1.15.9.mojave.bottle.tar.gz
==> Pouring nginx-1.15.9.mojave.bottle.tar.gz
Warning: The post-install step did not complete successfully
You can try again using `brew postinstall nginx`
==> Caveats
Docroot is: /usr/local/var/www

The default port has been set in /usr/local/etc/nginx/nginx.conf to 8080 so that
nginx can run without sudo.

nginx will load all files in /usr/local/etc/nginx/servers/.

To have launchd start nginx now and restart at login:
  brew services start nginx
Or, if you don't want/need a background service you can just run:
  nginx
==> Summary
🍺  /usr/local/Cellar/nginx/1.15.9: 27 files, 2MB
Removing: /Users/jonathanwold/Library/Caches/Homebrew/nginx--1.15.8.mojave.bottle.3.tar.gz... (1.2MB)


In Brew.php line 130:

  Brew was unable to install [nginx].


install
```

Any ideas what's going on?

**Comment by drbyte** [comment]
The blog article you linked to is mostly complete, but it's outdated, so has a couple errors. It references old paths that are no longer a match for what Valet does currently. For example, the `~/.valet` directory has been `~/.config/valet` for awhile now.

Your issue is something amuck with the way Nginx is currently installed vs what Homebrew wants to do. Specifically it's saying that the post-install step is failing.
Running `brew info nginx` reveals that the recipe for how Homebrew installs it can be found on github, and gives the URL. In that script is the post-install section:
https://github.com/Homebrew/homebrew-core/blob/0e07c0afbe86d22323018bef76b8800bdd07cf5e/Formula/nginx.rb#L95
Perhaps it's worth inspecting that list to see what files/paths might already exist on your machine, and/or whether permissions might be blocking the script from doing what it's expecting to have the freedom to do.

**Comment by sirjonathan** [comment]
Thank you for the feedback! For reference, here's the current output when I run `brew info nginx`:

```
MacBook-Air:~ jonathanwold$ brew info nginx
nginx: stable 1.15.9 (bottled), HEAD
HTTP(S) server and reverse proxy, and IMAP/POP3 proxy server
https://nginx.org/
/usr/local/Cellar/nginx/1.15.9 (27 files, 2MB) *
  Poured from bottle on 2019-02-27 at 22:17:41
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/nginx.rb
==> Dependencies
Required: openssl ✔, pcre ✔
==> Options
--HEAD
	Install HEAD version
==> Caveats
Docroot is: /usr/local/var/www

The default port has been set in /usr/local/etc/nginx/nginx.conf to 8080 so that
nginx can run without sudo.

nginx will load all files in /usr/local/etc/nginx/servers/.

To have launchd start nginx now and restart at login:
  brew services start nginx
Or, if you don't want/need a background service you can just run:
  nginx
==> Analytics
install: 27,674 (30 days), 92,696 (90 days), 435,822 (365 days)
install_on_request: 26,266 (30 days), 86,986 (90 days), 393,799 (365 days)
build_error: 0 (30 days)
```

Does anything stand out as problematic there that you can tell?

I'll go ahead and attempt the uninstall / reinstall again.

**Comment by sirjonathan** [comment]
I attempted it again, this type using `~/.config` in the removal instructions and manually navigating to and removing `valet` from `bin`.

I ran the process again, same effect. Here's the output, included the attempted postinstall:

```
MacBook-Air:~ jonathanwold$ valet install
Password:
Stopping nginx...
Installing nginx...
[nginx] is not installed, installing it now via Brew... 🍻
==> Downloading https://homebrew.bintray.com/bottles/nginx-1.15.9.mojave.bottle.tar.gz
Already downloaded: /Users/jonathanwold/Library/Caches/Homebrew/downloads/0f137dce9f6bc8965466766de46da51616aa8c21bf01331eed18fcf1ce4a760a--nginx-1.15.9.mojave.bottle.tar.gz
==> Pouring nginx-1.15.9.mojave.bottle.tar.gz
Warning: The post-install step did not complete successfully
You can try again using `brew postinstall nginx`
==> Caveats
Docroot is: /usr/local/var/www

The default port has been set in /usr/local/etc/nginx/nginx.conf to 8080 so that
nginx can run without sudo.

nginx will load all files in /usr/local/etc/nginx/servers/.

To have launchd start nginx now and restart at login:
  brew services start nginx
Or, if you don't want/need a background service you can just run:
  nginx
==> Summary
🍺  /usr/local/Cellar/nginx/1.15.9: 27 files, 2MB


In Brew.php line 130:

  Brew was unable to install [nginx].


install

MacBook-Air:~ jonathanwold$ brew postinstall nginx
==> Postinstalling nginx
Warning: The post-install step did not complete successfully
You can try again using `brew postinstall nginx`
```

Any other ideas? Is something wrong with my homebrew install?

**Comment by drbyte** [comment]
@sirjonathan is valet still failing to install?
There have been a lot of updates to Valet since you first posted this.

**Comment by drbyte** [comment]
@mattstauffer I think this can be closed.
