### ISSUE TITLE
PHP setlocale problem

### ISSUE THREAD

**Issue by MarekGogol** [laravel/valet#739]
Hello,

I have used Homestead for few years, now I want switch to Valet. I have installed valet without any problems, but when I open my applications, I experience problems of weird behaviour of PHP after setting locales. I can't reproduce this problem on any other server, homestead or other device, just in my fresh Valut configuration.

Valet version: 2.2.1
PHP version: 7.2.15 + 7.3.2

```php
setlocale(LC_ALL, 'en_US.UTF-8'); // (without setlocale works properly)
$s = 'test Ščď hello';

echo preg_replace("/\s+/", ' ', $s);
```

Result in browser (with Valet): test � čď hello
Result in browser (with Homestead or other server, this is expected behavior): test Ščď hello

Do you have any ideas how to fix this, without change in application code?

(EDIT) I found something in this case:
https://stackoverflow.com/questions/35887031/why-does-w-match-non-english-characters-in-mac-os-x-php-environment

**Comment by drbyte** [comment]
Adding the `/u` modifier to the regex pattern seems to resolve the problem.

**Comment by MarekGogol** [comment]
Yes, I used /u operator. But It was weird that problem appears just in mac environment.
