### ISSUE TITLE
How do I secure and alias?

### ISSUE THREAD

**Issue by rosshulford** [laravel/valet#741]
I create an alias

`    ln -s bikeshop home.bikeshop.localhost`

I try and secure it

`    valet secure home.bikeshop.localhost`

But it appends test to the url

`    The [home.bikeshop.localhost.test] site has been secured with a fresh TLS certificate.`

How can  get an alias to work over https?

**Comment by drbyte** [comment]
Use `valet link`:
```sh
cd home.bikeshop.localhost
valet link bikeshop
valet secure bikeshop
```
