### ISSUE TITLE
[PSA] Ngrok 2.3.23 for macOS breaks Valet.

### ISSUE THREAD

**Issue by ellisio** [laravel/valet#749]
This is not an issue, but more of a PSA until this is resolved. The latest stable version (2.3.23) causes Laravel Valet domains to be inaccessible from public URLs.

If you run into this issue, [downgrade to 2.3.18](https://bin.equinox.io/a/6xmUfV9cWa7/ngrok-2.3.18-darwin-amd64.zip).

I'll close this issue once I hear back from support with a workaround, or if they plan to fix this issue.

**Comment by drbyte** [comment]
@ellisio thanks for posting.

I just ran `valet share` on a project where I haven't used it before, and ngrok told me that it had upgraded, and to restart to use the new version. So I stopped the share, and ran `valet share` again, which shows that I'm using 2.3.23. Using the ngrok.io share link works fine. I'm able to click around the shared site normally, both in https and non-https, and can login/logout fine.
Just posting in case it exposes a different problem on your end.

**Comment by ellisio** [comment]
From the maintainer:

> short version: we changed the environment we were using to build ngrok and just changing the environment caused the build to change which type of resolver it was using and the new resolver it's using is not as accurate

There will be a fix available soon. Going to go ahead and close this out.

CC: @billmn @drbyte

**Comment by ellisio** [comment]
Confirmed resolved with Ngrok 2.3.25.
