### ISSUE TITLE
valet trying to load xdebug and failing

### ISSUE THREAD

**Issue by brothman01** [laravel/valet#752]
whenever I run any valet command I get errors:
```
$ valet links
Failed loading /usr/local/opt/php71-xdebug/xdebug.so:  dlopen(/usr/local/opt/php71-xdebug/xdebug.so, 9): image not found
Failed loading /usr/local/opt/php71-xdebug/xdebug.so:  dlopen(/usr/local/opt/php71-xdebug/xdebug.so, 9): image not found
Failed loading /usr/local/opt/php71-xdebug/xdebug.so:  dlopen(/usr/local/opt/php71-xdebug/xdebug.so, 9): image not found
```
these errors point to the fact that valet is trying to load xdebug but is failing.  I had xdebug installed a long time ago, but I don't even use it anymore.  How can I remove/ uninstall xdebug and the command(s) telling valet to load it?

**Comment by drbyte** [comment]
@brothman01 the xdebug pecl installer typically adds some lines directly to the top of your `/usr/local/etc/php/7.1/php.ini` file. 
You can get to that file by opening a Finder window, pressing CMD+Shift+G and typing the path.
Then remove those lines to have it stop trying to load the module.

**Comment by brothman01** [comment]
hmm that is a long file, which lines are you referring to?  The top of the file starts [PHP] and has no 'extra' looking lines before that.  I also grepped that file and found no instances of xdebug.  Which lines am I looking for specifically?

**Comment by drbyte** [comment]
It added (something like) the following to the top of mine (I believe I edited it to put the full path) when I did it recently for PHP 7.3:

```ini
[xdebug]
zend_extension='/usr/local/Cellar/php/7.3.3/pecl/20180731/xdebug.so'
```

**Comment by brothman01** [comment]
hmm, I don't see that line.  I grepped the file:

```
$ grep zend /usr/local/etc/php/7.1/php.ini
; http://php.net/zend.enable-gc
zend.enable_gc = On
;zend.multibyte = Off
; Only affects if zend.multibyte is set.
;zend.script_encoding =
;report_zend_debug = 0
; Changing from or to a negative value is only possible in php.ini! (For turning assertions on and off at run-time, see assert.active, when zend.assertions = 1)
; http://php.net/zend.assertions
zend.assertions = 1
```
is "zend.enable_gc = On" the offending line? or "zend.assertions = 1"? Or maybe this is the wrong file?

**Comment by brothman01** [comment]
I fixed it, it was in another file but the header was different and not [xdebug].  Honestly, thanks, I would not have found the solution if you hadnt have said that.
