### ISSUE TITLE
valet share, ngrok giving 404, CORS errors in Craft CMS project

### ISSUE THREAD

**Issue by BBaysinger** [laravel/valet#753]
I have a Craft instance running via Valet, per the instructions [here][1].

Running the project via `valet link` works great, and `valet share` works, except when I try to access the admin side. I'm using `valet share` to try to access the site over a local network for a demo.

In Chrome from `http://ad3f5068.ngrok.io/admin/login` when I try to log in, I get:

    OPTIONS http://craftycoffee.test:60/index.php?p=admin/actions/users/login 404 (Not Found)
    Access to XMLHttpRequest at 'http://craftycoffee.test:60/index.php?p=admin/actions/users/login' from origin 'http://ad3f5068.ngrok.io' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

If I use HTTPS, I get net::ERR_SSL_PROTOCOL_ERROR across a bunch of requests.

What am I missing to get this to share over a local host?

Jalen Davenport suggested unsecuring the site via `'enableCsrfProtection' => false`, bit this did not resolve my issue.

  [1]: https://medium.com/@jalendport/running-craft-cms-3-on-laravel-valet-6df61e5193fd

Stack Exchange issue: https://craftcms.stackexchange.com/questions/30001/valet-share-ngrok-giving-404-cors-errors

**Comment by itguy614** [comment]
See the solution I posted in #836 .

**Comment by drbyte** [comment]
@BBaysinger if this works for you, can you close this Issue?

**Comment by BBaysinger** [comment]
I haven't actually had time to confirm. Should I just close it for now?

**Comment by drbyte** [comment]
It seemed to work fine for me. I'm pretty sure it's an adequate solution for a dev environment anyway.

If it's not a pressing issue for you anymore, I'd say close it.

**Comment by BBaysinger** [comment]
(y)
