### ISSUE TITLE
Brew::installed() fails to correctly parse installed version of PHP if "php" is installed with no version constraint

### ISSUE THREAD

**Issue by mattstauffer** [laravel/valet#756]
See notes here:

https://github.com/laravel/valet/issues/728#issuecomment-479523782

To reproduce:

Install `php` instead of `php@7.3` with Homebrew, then run `valet use php73`. Valet will suggest it's not installed, even though it is, because it looks at `php` which doesn't have a version number and therefore doesn't match `php73`.

**Comment by mattstauffer** [comment]
Thanks to @lasseeee and @drbyte for finding, testing, and refining the issue.

**Comment by workzentre** [comment]
Same here, If I run valet use php@7.2 still stuck with 5.6.3 "alias" php (plain, no version). Thanks.
