### ISSUE TITLE
Can't change daemon launch permissions

### ISSUE THREAD

**Issue by edalzell** [laravel/valet#759]
I long time ago, in a galaxy far, far, away, I installed valet w/ sudo, so the services are all run w/ `root`: https://cl.ly/c4ac9173c6ac.

How can I change those to run under my user?

I have tried moving the relevant plists to my dir but valet just recreates them when updated.

**Comment by edalzell** [comment]
Turns out it should be root.

**Comment by drbyte** [comment]
Yes, some of them need to run as root. Valet starts them as such accordingly.
