### ISSUE TITLE
Installing a fresh valet version caused to get a wrong version

### ISSUE THREAD

**Issue by ModestasV** [laravel/valet#762]
# Issue
Ran a fresh install of Laravel valet in order to get the latest issues with following commands:
`composer global require laravel/valet`
Php version is:
`PHP 7.3.4 (cli) (built: Apr  8 2019 10:21:33) ( NTS )`

# Problem
The version of valet that was installed is: `Laravel Valet 2.2.1`
Composer.lock has a 2.2.2 version 
Running `valet on-latest-version` returns `NO`

# Additional information:
http://prntscr.com/n9mjdr
Upgrade was made fresh, after all of the caches were cleared on composer

**Comment by drbyte** [comment]
Ya, you've got 2.2.2, as `composer global show` and your composer.lock indicate.

The PHP file just wasn't stamped with the new version number prior to being tagged.

**Comment by ModestasV** [comment]
Yeah, just wanted to share that as I don't know if there are latest changes accessed or not :)

**Comment by mattstauffer** [comment]
I cannot even begin to tell you how many times I've forgotten that. 🤦‍♂️
