### ISSUE TITLE
CORS policy + 'Access-Control-Allow-Origin'

### ISSUE THREAD

**Issue by Livijn** [laravel/valet#768]
When making a request from a subdomain to the domain I get a CORS error. I looked at #377 and saw [this gist](https://gist.github.com/poul-kg/b669a76fc27afcc31012aa0b0e34f738) but that didn't help. It is working on the staging server set up by Forge, but not locally.

How can I make valet allow cross-subdomain requests?

Here is the full error:

> Access to XMLHttpRequest at 'https://***.test/api-path-bla' from origin 'https://subdomain.***.test' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by Livijn** [comment]
I am also trying to change the `client_max_body_size` to imitate my staging server. However, it still accepts requests that are above this limit. Running `locate valet.conf` only gives me 1 config, meaning I am updating the correct file: `/usr/local/etc/nginx/valet/valet.conf`.

I also tried restarting nginx using `brew services restar nginx` but doesn't affect the max request limit.

**Comment by alexkerber** [comment]
I got exactly the same issue here with a project. Tried to install ngnix-full and the more-headers-module so I can use `more_set_headers "Access-Control-Allow-Origin: *";`. This works perfect before I did an upgrade of Laravel Valet :| Anyone with the same issue?

**Comment by alexkerber** [comment]
Ok so for me there were other stuff that did create this error. So mine is now working perfect again.

**Comment by drbyte** [comment]
@Livijn In Valet 2 the file to put your changes in is `~/.config/valet/Nginx/your_domain.test` and then run `valet restart`
