### ISSUE TITLE
Stripe API + Valet

### ISSUE THREAD

**Issue by upwebdesign** [laravel/valet#773]
There is some extreme slowness with the Stripe API using Laravel Cashier on Laravel Valet. When switching to Laravel Homestead, the issue is remedied. However, I would prefer to use Valet. There are 20+ second response times from Stripe and I don't think Im the only one experiencing this... right?

There has been chatter about secure URLs and dnsmasq being possible issues, but I have installed and reinstalled and restarted and stoped and started all the services Valet uses including Valet, multiple times. Spin up the Virtual Machine (Homestead) and all is fine as long as the connections to Stripe are made using Homestead.

Anyone have a clue what might be going on?

**Comment by upwebdesign** [comment]
So, to add to the conversation... we have a Cisco switch using IP block of 10.0.1.x. Would this cause issues with Valet DNS lookups? Really stumped. When connecting to my iPhone as a hotspot, the problem goes away, so it has to be a networking issue, but I cannot nail it down as to why.

**Comment by matt-allan** [comment]
Maybe try writing a simple PHP script that passes the [`CURLOPT_VERBOSE`  option](https://www.php.net/manual/en/function.curl-setopt.php) to [the Stripe curl Client](https://github.com/stripe/stripe-php#custom-curl-options-eg-proxies).

If you run the script from the CLI `i.e. php my-script.php` you should get a bunch of output from curl.

There is also some helpful info in [this comment](https://github.com/laravel/valet/issues/736#issuecomment-468723342) explaining how to enable dnsmasq logging, which may be helpful.

**Comment by upwebdesign** [comment]
@matt-allan Thanks for the response. I should have came back here and posted what I found. In my Network Preferences I needed to make sure 127.0.0.1 was first as a DNS server. Im not exactly sure why, but that made the problem go away.

**Comment by drbyte** [comment]
> Thanks for the response. I should have came back here and posted what I found. In my Network Preferences I needed to make sure 127.0.0.1 was first as a DNS server. Im not exactly sure why, but that made the problem go away.

@upwebdesign Yes, that would definitely explain a few things:
- dnsmasq, which is the DNS service that serves all your valet domains, runs on 127.0.0.1/localhost. It's actually important that it be first in the list of dns servers (or the list be blank).
- the delay was likely caused by waiting for a timeout from the first DNS server listed, before it could fallback to the 127/localhost one.

Glad you got it sorted out!
