### ISSUE TITLE
sites.test/wp-admin/install.php ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by abkrim** [laravel/valet#774]
Hi.

I see other post, [but it was older](https://github.com/laravel/valet/issues/406) and also I use normal folder.

I use:

`Sites/mysite/public` for install wordpress (root of installation)

When I try access to site or directly site/wp-admin/install.php get error `ERR_TOO_MANY_REDIRECTS`

Also I've tried

```
define('WP_HOME', 'https://mysite.test');
define('WP_SITE_URL', 'https://mysite.test');

define('WP_DEBUG', true);
define('WP_DEBUG_LOG', true);
define('WP_DEBUG_DISPLAY', true);
```

If backup original site, install on my developer `Sites` and modify wp-config.php for develop DB and Debug, a blank page on index. Not log, not debug. Only blank page.

**Comment by rgjchandler** [comment]
Hi @abkrim, have you tried installing WordPress inside of the `Sites/mysite/` directory instead? It's very rare that WordPress would need to be installed inside of a `public/` subdirectory.

Your problem might be caused by a specific Valet driver not choosing the correct front controller.

**Comment by abkrim** [comment]
Hi @rgjchandler 
If use ~/Sites/mysite get a `404 - Not Found`

I don't use a  additional Valet driver Only a Valet fresh installation.

**Comment by drbyte** [comment]
@abkrim is this resolved?

**Comment by abkrim** [comment]
Oops.. Sory for delay. I don't not. Know use docker for my develop computer. A lot of thanks
