### ISSUE TITLE
Files uploaded to S3 not showing up with Drupal 8 

### ISSUE THREAD

**Issue by marcbelletre** [laravel/valet#776]
I have a Drupal 8 website installed in my `~/Sites` directory which is parked with Valet. The website is running correctly.
We are using the module `drupal/flysystem_s3` to connect the website to our Amazon S3 bucket. Everything is working fine in both our Heroku preproduction environment and a teammate's Apache environment, but not in my Valet environment.
The files I upload from my Valet installation are successfully stored in S3, but they don't show up. I get a white square instead.  

So when I upload an image from my local Drupal back-end I get an URL like this:
`http://mylocaldrupal.test/_flysystem/s3/styles/large_rect/s3/2019-05/myfile.jpg`  

The file exists in S3 and shows up in our Heroku environment. However I get a broken link on my Valet environment (but no 404).  

Does anyone ever experienced this? It looks like this is related to Valet as I can't reproduce this on any other environment with the same configuration.

**Comment by drbyte** [comment]
@marcbelletre Is this still a Valet issue?

**Comment by marcbelletre** [comment]
@drbyte I have no idea honestly. I ended up setting up an Apache server on my iMac to make things work. What's weird is that I have the exact same Valet configuration on my Macbook and everything's working fine. The Drupal configuration was the same on both machines.  
Anyway I guess we can close this issue as nobody seems to have the same issue.
