### ISSUE TITLE
Create a Proxy driver/config possible?

### ISSUE THREAD

**Issue by FrodeMMeling** [laravel/valet#777]
I am running a development environment in valet and also in Docker. Is it possible to to add custom nginx config for sites?

Example:
I would like to create a folder called myProxiedSite in Sites, then this conf should be used when http://myProxiedSite.test is loaded:
```
server {
  server_name myProxiedSite.test;

  location / {
    proxy_pass http://myOtherWebserver.local:8080;
    proxy_set_header Host            $host;
    proxy_set_header X-Forwarded-For $remote_addr;
  }
}

```

**Comment by FrodeMMeling** [comment]
Fixed it myself.. Sorry to bother.. I found server/* include can be used.. added it there.

**Comment by elephantux** [comment]
> Fixed it myself.. Sorry to bother.. I found server/* include can be used.. added it there.

Can you please explain this?

If I understand correctly, did you manage to upload the custom Nginx config for one particular site?

**Comment by drbyte** [comment]
You can indeed add your own custom nginx configs.

Two places where you could optionally put them:
1. `~/.config/valet/Nginx/abc.test`
or
2. `/usr/local/etc/nginx/server/abc.conf`

Pick whichever suits you. The subdirectory under home is easier to "get to" or edit quickly, but the nginx server directory is created when installing nginx via homebrew. (I've seen some systems where that `server` directory doesn't exist. You can easily create it by hand.

**Comment by elephantux** [comment]
@drbyte thanks!

For my custom config to work, must the domain already exist in the valet parked directory? Or can I direct nginx to completely arbitrary domain name (but in *.test zone)?

**Comment by drbyte** [comment]
Depends. 
If you're expecting Valet to serve it like any other PHP-based valet-kinda project, then your site's files must be in a dir that Valet will recognize.

If you're wanting Nginx to serve it with some other directives, then you'll need to specify "how" that's to work. eg: proxying to some other address (such as was posted earlier above), or some custom fastcgi configuration.

**Comment by elephantux** [comment]
Let me explain my problem.
For an old project (Laravel 5.2) I need php v7.1 but Valet 2.7.0 is part of Laravel 6.x which requires PHP v7.2 or above. So for a separate local domain, I need a separate nginx config where I could specify to use php 7.1.

**Comment by drbyte** [comment]
> For an old project (Laravel 5.2) I need php v7.1 but Valet 2.7.0 is part of Laravel 6.x which requires PHP v7.2 or above. So for a separate local domain, I need a separate nginx config where I could specify to use php 7.1.

Oh. Well, that's more complicated. 
Valet doesn't currently support "running" multiple PHP instances (of different versions).
So, you'd need to set up the configs that instantiate the version of PHP that you've NOT got Valet set up to use, and start those processes on boot. And then set up your nginx to call that.

Things involved in that include:
- the php-fpm pool for that custom php version
- the php config needs to point to either a custom socket (Valet uses `~/.config/valet/valet.sock`, so you can't use that)
- nginx for that domain needs to have the fastcgi stuff set up to reference the right socket

**Comment by drbyte** [comment]
> Valet 2.7.0 is part of Laravel 6.x which requires PHP v7.2 or above

Only partly true. Valet is not limited to Laravel 6, nor to PHP 7.2.
But it does only support one running instance of PHP, out of the box.

Technically Valet 2.7.0 can still run on PHP 5.6 ... but you'll have to sort out a bunch of composer package dependencies and tap old homebrew resources to do it.
