### ISSUE TITLE
Valet won't load changes Gulp makes to an HTML file 

### ISSUE THREAD

**Issue by jalendport** [laravel/valet#782]
I've got a static site (using the `BasicValetDriver`) running locally. I'm using Gulp to compile Twig templates to an HTML file. I can verify that Gulp is indeed firing and that HTML file is updating any time I update a Twig file.

The problem I'm running into is that when I go to reload my browser, it doesn't pull in the new file; I'm still getting the old HTML file in the browser. I've tried reloading, shift-reloading, clearing the browser cache, running with and without BrowserSync, everything. The only way to make the browser recognize the HTML file updated is to manually go in and re-save the HTML file in my code editor. However, if I load the HTML file in the browser manually (via the absolute path), it updates every single time.

My conclusion is that Valet is somehow caching the html value and that cache breaks any time the html file changes, and for some reason Gulp isn't triggering that while my manual edits do. This is super weird and it's holding me up from working on this project right now... 😬

**Comment by jalendport** [comment]
@drbyte any thoughts?

**Comment by drbyte** [comment]
I'm not aware of any intentional caching that Valet would be doing.

And in a traditional install it seems to work fine with recognizing local updates.
For example, when I use "watch" mode with Laravel Mix it properly recognizes my content changes in the browser.

Sounds like you've tried all the usual suspects that I'd be checking.
Maybe you've added some sort of cache headers in your browser or your PHP code? Does Twig have settings for that? Page-Cache systems typically look for a content-changed indicator from the filesystem to know whether they should reload the content.

**Comment by drbyte** [comment]
@jalendport Does this issue still need to be kept open? If so, please provide additional context.

**Comment by jalendport** [comment]
Hey @drbyte; I never did solve the issue but ended up using another solution because I had a deadline fast approaching. I'm going to close it for now as I don't have the need anymore to debug it and it seems like I'm the only one who's run into it so far... Thanks for your help!

**Comment by RyanRoberts** [comment]
hey @jalendport I know you said above you didn't solve the problem but I'm having the exact same issue, did you ever get to the bottom of it? Or what was your other solution? Thanks.

**Comment by jalendport** [comment]
@RyanRoberts are you using Twig.js as well? I never did get to the bottom of it, but I ended up just switching to plain PHP because all I was using Twig for was to have partials that I could include in multiple places.

**Comment by RyanRoberts** [comment]
@jalendport OK so this issue in the Sass repo explains what I think is the problem: https://github.com/dlmanning/gulp-sass/issues/706 - it appears to have been a change with Gulp 4 which packages had to account for. Gulp-Sass got updated but I don't think Gulp-Twig has been updated in a few years.

Scroll to the bottom and you'll find a solution using _through2_ that's working for me 👍

**Comment by jalendport** [comment]
Awesome; good to know in case I ever run into it again 👏  Thanks for reporting back!
