### ISSUE TITLE
laravel Valet create database issue

### ISSUE THREAD

**Issue by at-quangtran** [laravel/valet#784]
Hello everyone,
I have setup Valet according to this `https://laravel.com/docs/5.8/valet` , it's success. But when i connect to DB `mysql -uroot` and then `create database  testdb` i got error
![Screen Shot 2019-05-31 at 16 40 56](https://user-images.githubusercontent.com/15379864/58696970-e88d9e00-83c2-11e9-9df2-7ecafe854b6e.png)
What's missing here? 
![Screen Shot 2019-05-31 at 16 48 32](https://user-images.githubusercontent.com/15379864/58697642-0c9daf00-83c4-11e9-8459-b380e8ded22e.png)
![Screen Shot 2019-05-31 at 16 48 06](https://user-images.githubusercontent.com/15379864/58697658-145d5380-83c4-11e9-97c2-78e9732900c6.png)

**Comment by jrbarnard** [comment]
The install of mysql via brew might need more configuring, have a look at this guide here: https://gist.github.com/operatino/392614486ce4421063b9dece4dfe6c21

Ensure that the mysql command is the brew installed one (which mysql) should give you the path of the binary.

Alternatively you could do this via a GUI like sequel pro by connecting to 127.0.0.1 (info in laravel docs).

Hope that helps!

**Comment by at-quangtran** [comment]
@jrbarnard  i already use mysql workbench to connect. But it's not successful when i create new DB 
![Screen Shot 2019-05-31 at 17 04 11](https://user-images.githubusercontent.com/15379864/58698927-7ae37100-83c6-11e9-82eb-ba3eab735c2e.png)

**Comment by jrbarnard** [comment]
Ah ok, what is the output of 'which mysql'? And 'mysql -v'?

Did you have mysql 8 installed via brew before installing 5.7?

It also could be a mysql directory permissions issue.

**Comment by at-quangtran** [comment]
@jrbarnard  
![Screen Shot 2019-06-03 at 09 43 41](https://user-images.githubusercontent.com/15379864/58772711-5533b300-85e4-11e9-8142-c6e110480844.png)

**Comment by jrbarnard** [comment]
It looks like you previously had mysql 8 installed and it's using that
instead of the brew installed 5.7 I think.

Check out:
https://discourse.brew.sh/t/how-to-revert-from-mysql-8-0-11-to-a-specific-older-version-such-as-5-7-21/2431/3

**Comment by drbyte** [comment]
IMO this can be closed, because Valet doesn't have anything to do with databases.
