### ISSUE TITLE
Valet just stopped working

### ISSUE THREAD

**Issue by josefarrugia** [laravel/valet#786]
Hi all,

Valet just suddenly stopped working today. I might have installed another package which is interfering with it. I have uninstalled it and removed it via composer too. Additionally, I have changed the domain from `.test` to `.host` and yet still the same issue.

Any ideas how to get this sorted?

**Comment by drbyte** [comment]
Have you rebooted first before answering the following questions and trying again?
What's the output of `brew services list`?

MORE IMPORTANTLY: What does "suddenly stopped working" look like? It's hard to support without details of the symptoms you're encountering.
What did you try to do? What did you expect to happen? What actually happened instead?

**Comment by Treggats** [comment]
I've run across this too, just had an OSX update maybe related.

Versions:
- OSX High Sierra 10.13.6 (iMac mid 2011)
- PHP 7.2.14
- Laravel Valet 2.3.3

Started with a clean slate; stopped, uninstalled valet and removed configs from $HOME/.valet and $HOME/.config/valet
Rebooted, removed valet (composer) and installed it again.
Ran valet install and linked a Statamic site.
Restarting valet doesn't help.

Pinging works, I get a response. But when I try the same link in the browser I get an ERR_CONNECTION_REFUSED message.

Valet is mentioned in my `scutil --dns`
```
resolver #8
  domain   : valet
  nameserver[0] : 127.0.0.1
  flags    : Request A records, Request AAAA records
  reach    : 0x00030002 (Reachable,Local Address,Directly Reachable Address)
```
Output of `brew services list`
```
Name            Status  User        Plist
blackfire-agent started tonkomulder /Users/tonkomulder/Library/LaunchAgents/homebrew.mxcl.blackfire-agent.plist
dnsmasq         started root        /Library/LaunchDaemons/homebrew.mxcl.dnsmasq.plist
mailhog         stopped
mysql           started tonkomulder /Users/tonkomulder/Library/LaunchAgents/homebrew.mxcl.mysql.plist
nginx           started root        /Library/LaunchDaemons/homebrew.mxcl.nginx.plist
php             stopped
php@7.2         started root        /Library/LaunchDaemons/homebrew.mxcl.php@7.2.plist
postgresql      stopped
redis           started tonkomulder /Users/tonkomulder/Library/LaunchAgents/homebrew.mxcl.redis.plist
```

Telnetting to localhost on port 80 and 443 fails with `Connection refused`

Suggestions welcome on how to debug this

**Comment by josefarrugia** [comment]
Figured out the issue folks! There was a conflict with a brew installed php and valet. So I ended up completely uninstalling brew-php and Valet. Works like a charm now!
