### ISSUE TITLE
Valet sites can´t connect to external websites

### ISSUE THREAD

**Issue by marflow** [laravel/valet#788]
I tried several fresh installs of Homebrew, Composer & Valet but my sites can´t connect to external servers. In .composer>valet>log nginx-error.log I have messages like this
`2019/06/14 16:52:07 [error] 16025#0: *1 upstream prematurely closed connection while reading response header from upstream, client: 127.0.0.1, server: mysite.test, request: "POST /index.php?p=admin/actions/app/check-for-updates HTTP/2.0", upstream: "fastcgi://unix:/Users/wg/.config/valet/valet.sock:", host: "mysite.test", referrer: "https://mysite.test/admin/plugin-store"`
Also it seems the valet.lock file is not existing. Thanks for a suggestion how to fix the problem. 

Homebrew 2.1.5
PHP 7.3.6
Valet 2.3.3

**Comment by marflow** [comment]
So after going back to PHP 7.2 as described in here (https://github.com/laravel/valet/issues/717) everything is working as expected. Seems PHP 7.3.6 is not working (at least on MacOS Mojave).

**Comment by drbyte** [comment]
Clarification: PHP 7.3.6 does work fine on MacOS Mojave. At least, it's working fine for me.
If it's not working for you (as evidenced by the missing valet.sock file), then something's wrong with your configs such that PHP-FPM isn't starting properly.

I've posted many times in this repo about troubleshooting PHP-FPM. I don't have all those links handy, but here's one:
https://github.com/laravel/valet/issues/717#issuecomment-502488646
