### ISSUE TITLE
FR: Improve .valet-env.php to be able to set GLOBAL ENV vars for all projects

### ISSUE THREAD

**Issue by madsem** [laravel/valet#789]
So I'm just done installing and using valet for the first time (Good job & thanks for that btw).
I thought I would be able to drop the `.valet-env.php` in my `~/Sites` directory for example, to have ENV vars set globally for all my projects.

But this doesn't seem to be the case. So I would like to suggest this as a new feature, as I'm sure it could be helpful and that my scenario isn't super-unique.

If this is already possible and I'm just too blind to see it in the documentation, apologies :) (And a plea for someone to explain to me how to set it up globally)

**Comment by drbyte** [comment]
The current implementation doesn't offer that.

Can you give some examples of the sort of vars that you need to set globally? Trying to understand the use-case.

**Comment by madsem** [comment]
Sure thing!

In my case, many of my projects use the Maxmind PHP extension. So I'd like to just have them available where ever I need them.

Examples of Maxmind variables:
```php
<?php

return [

  // global ENV vars
	'*' => [
		'ISP' => 'Telekom',
		'COUNTRY_CODE' => 'US',
		...
		...
	],

];
```

It can be useful for many other use-cases as well though, think API keys for sandbox environments and so forth.

I would even go as far as saying, the `.valet-env.php` should be placed in the `~/Sites` root in general and only optionally on a per-project basis. To override, extend or share ENV var files when working in a team.

I'd imagine it to work like this, when placed in `~/Sites`:
```php
<?php

return [

  // global ENV vars
	'*' => [
		'API_1' => 'some key',
		'API_2' => 'another key',
		...
		...
	],

	// project A
	'somefolder' => [
		'key' => 'value',
		...
		...
	],

	// project B
	'anotherfolder' => [
		'key' => 'value',
		...
		...
	],

];

```

At the very least it would be possible to have global / shared vars that way.

**Comment by drbyte** [comment]
It's a little unlikely that such a feature would be added. Keep in mind that Valet supports multiple parked parent directories, not just ~/Sites, and in such a case it gets muddy trying to figure out where the global file would be, or whether multiple global files would be relevant but even that isn't pretty either.

However, there's an easy solution for you, and your team if you're collaborating with others who are sharing similar configs: A custom valet driver.

Since the Valet drivers are extended from the master abstract driver, you can extend that to make your own, and override the method which does the custom var loading.

You can find more about drivers in the docs, but here's the basic idea:

1. Copy the `.composer/vendor/laravel/valet/cli/drivers/LaravelValetDriver.php` to your `~/.config/valet/Drivers` directory, as `MyLaravelValetDriver.php`.

2. Copy the `loadServerEnvironmentVariables()` method from the `.composer/vendor/laravel/valet/cli/drivers/ValetDriver.php` file into your (from step 1) `~/.config/valet/Drivers/MyLaravelValetDriver.php`

3. Edit the function to look one directory higher for the .valet-env.php file. Maybe something like the following:
```diff
- $varFilePath = $sitePath . '/.valet-env.php';
+ $varFilePath = realpath($sitePath . '/../.valet-env.php');
```

This custom driver is now yours, and is untouched by upgrades, although you may need to update it if significant changes are made to the original driver files, just like any other code you extend in other projects.

**Comment by madsem** [comment]
@drbyte that looks amazing, thanks a lot for pointing me in the right direction here :)

What you say about multiple parent directories makes sense of course. Although, in the case of global env vars, I would say it wouldn't matter where the file is located as long as there is one with a global wildcard it would be loaded into the environment. if it is now located in dir A or dir B.

When it comes to site-specific config though, you're absolutely right, that would indeed be messy.

**Comment by madsem** [comment]
I've extended it, but it seems I have to call the overridden method from the serve method to get the env vars set, does that look right to you? :)

```php
/**
     * Loads .valet-env.php from registered paths, for global availability.
     *
     * Load server environment variables if available.
     * Processes any '*' entries first, and then adds site-specific entries
     *
     * @param  string  $sitePath
     * @param  string  $siteName
     * @return void
     */
    public function loadServerEnvironmentVariables($sitePath, $siteName)
    {

        $varFilePath = realpath($sitePath . '/../.valet-env.php');
        if (! file_exists($varFilePath)) {
            return;
        }
        $variables = include $varFilePath;
        $variablesToSet = isset($variables['*']) ? $variables['*'] : [];
        if (isset($variables[$siteName])) {
            $variablesToSet = array_merge($variablesToSet, $variables[$siteName]);
        }
        foreach ($variablesToSet as $key => $value) {
            if (! is_string($key)) continue;
            $_SERVER[$key] = $value;
            $_ENV[$key] = $value;
            putenv($key . '=' . $value);
        }
    }

    /**
     * Determine if the driver serves the request.
     *
     * @param  string  $sitePath
     * @param  string  $siteName
     * @param  string  $uri
     * @return false
     */
    public function serves($sitePath, $siteName, $uri)
    {
        $this->loadServerEnvironmentVariables($sitePath, $siteName);

        return false;
    }
```

**Comment by madsem** [comment]
PS:

I made that a repository for anyone who needs the same: https://github.com/madsem/global-env-valet-driver

**Comment by drbyte** [comment]
I hadn't dug into it far enough to see it needing to be fired from the `serves` method, but if what you've got is working for you, then that's probably enough. 

One thing to note is that now you're only looking for a .valet-env file "above" your projects, and no longer "in" your projects. You could expand the logic to check both places, if that were relevant to your needs.

Nicely done with the Repository. Another handy thing with the repository is you (or anyone) can literally check out the repo into the Drivers directory and Valet will still find it automagically, and still keep it as a git repo, and pull/push updates for it, with no need to manually copy just the .php file.

**Comment by madsem** [comment]
Ahh yeah I didn't even think that far, great idea :) 

And the way the driver works now is that it looks in both locations... The original valetDriver still looks for the env file inside a projects directory, and the GlobalEnvValetDriver adds the global env vars on top.

**Comment by drbyte** [comment]
> And the way the driver works now is that it looks in both locations... The original valetDriver still looks for the env file inside a projects directory, and the GlobalEnvValetDriver adds the global env vars on top.
> 
Nice. I guess that's the consequence of the original code loading the original function, and then your custom driver calling the localized one via `serves`. Interesting, but no harm in that. :+1:

**Comment by adriaanzon** [comment]
@drbyte Is there any chance this issue could be revisited?

I'd love to be able to set `IGNITION_EDITOR=vscode` globally.

Maybe by reading a `~/.config/valet/env.php`, because Valet supports multiple parked directories.

**Comment by drbyte** [comment]
Ya, I can see the value of this for that context.

How does the following suit?

`~/.config/valet/.valet-env.php` (uses same filename as individual projects, for consistency, to minimize confusion)
```php
<?php
/**
 * Return an array of [site_folder => ['VARIABLE' => 'value']], indicating which environment variables to be set. 
 * ... where site_folder is foo for a site served as foo.test
 * Using '*' for site_folder will apply those variables to all sites.
 * This file is ignored completely if a .valet-env.php file exists in the actual site directory, in which case that file is used instead of this one.
 */
return [
    '*' => [
        'IGNITION_EDITOR' => 'vscode',
    ],
];
```

And to enable it, edit `~/.composer/vendor/laravel/valet/cli/drivers/ValetDriver.php` like this:
```diff
    public function loadServerEnvironmentVariables($sitePath, $siteName)
    {
        $varFilePath = $sitePath . '/.valet-env.php';
+        if (! file_exists($varFilePath)) {
+            $varFilePath = VALET_HOME_PATH . '/.valet-env.php';
+        }
        if (! file_exists($varFilePath)) {
            return;
        }
```
