### ISSUE TITLE
POST requests fail [404 (Not Found)] on Ajax form submission

### ISSUE THREAD

**Issue by andrewjireland** [laravel/valet#795]
Hi there, I've generally been using valet with great success (wonderful work 👍), but have run into a small issue I'm looking to resolve.

When trying to post a form using Ajax, I'm receiving a 404 (Not Found) error on the mailer.php file (using the swift mailer library). Can anyone advise if there's anything I can do to debug this issues/resolve it in valet?

The post request works without a hitch in Mamp, and on my web server.

Thanks for your help!
Andrew

**Comment by drbyte** [comment]
Valet returns a basic text response of `404 (Not Found)` when:
- the URL you give it can't be resolved to a domain name it can find a directory to serve it from
- the URL you give it points to a directory for which it can't find a suitable Valet Driver which understands that directory
- the URL you give it results in selecting a Valet Driver that can't find a $frontController path to the PHP file that drives the directory it thinks it's supposed to be serving from

https://github.com/laravel/valet/blob/master/server.php

**Comment by drbyte** [comment]
I'm guessing this can be closed.

**Comment by andrewjireland** [comment]
Still now closer to working this out, but thanks for your help. Consider it closed.
