### ISSUE TITLE
feature request: Arrange sites into groups for links display.

### ISSUE THREAD

**Issue by AlexanderWright** [laravel/valet#798]
I have a variety of projects for different customers and test projects for myself where I'm testing new features or techniques.

Thus, running ```valet links``` ends up with a large disorganised list of URLs.

It would be helpful to be able to add a 'Group' property to each site, and then group the sites by this property.

**Comment by AlexanderWright** [comment]
I'm looking to implement this feature.

Is it desired? Where is the best place to store the extra information?

**Comment by drbyte** [comment]
The best way to do it is as a new command, written as an Extension.
1. put your code in your `~/.config/valet/Extensions` directory
2. if you need to persist some custom data of your own, perhaps the `~/.config/valet/` directory is the place to add your own additional data file (not re-using existing ones).

Here's an example Extension as a starting point:
```php
<?php
namespace Valet;

use Illuminate\Container\Container;
use function Valet\info;
use function Valet\output;
use function Valet\table;
use function Valet\warning;

 /**
  * Create a new database on your local machine.
  */
 $app->command('make:db [name]', function ($name) {
     if(!$name) {
         warning('Please specify a database name');
         return;
     }
     if($error = CommandLine::run('mysql -uroot -e "create database '.$name.'"')) {
         warning($error);
     } else {
         info('The database '.$name.' has been created');
     }
 })->descriptions('Create a new database');
```

**Comment by drbyte** [comment]
@mattstauffer I believe this can be closed
