### ISSUE TITLE
feature request: Add sites available via 'Park' be visible in links

### ISSUE THREAD

**Issue by AlexanderWright** [laravel/valet#799]
Where ```valet park``` is used, sites should be listed when using the ```valet links``` command.

**Comment by jrbarnard** [comment]
@AlexanderWright I just looked at this and reckon an issue may be if you've got lots of directories within a parked path this could get bloated quite quickly, especially if some of those directories aren't actual sites.
However this could be done relatively easily but could be better behind an option on the links command? E.g `valet links --with-parked` or something.

What do you reckon?

**Comment by jrbarnard** [comment]
@mattstauffer This can be closed
