### ISSUE TITLE
Ability to have multiple folders on 1 domain and share cookies?

### ISSUE THREAD

**Issue by marbuser** [laravel/valet#801]
I'm working on a project that requires me to run 2 different software suites at the same, as well as code an extension for them with Laravel. I need access to the cookies of these other software suites but I've been unable to find a way to accomplish this using valet.

E.G (these would all share the same cookies/domain)
laravel.test
laravel.test/example1
laravel.test/example2
example.laravel.test
etc...

I was wondering if this was possible? If not, then consider this a feature suggestion. :)

**Comment by drbyte** [comment]
Sharing cookies across domains is something you configure in your cookies themselves.

IMO this is not a Valet issue.
