### ISSUE TITLE
Pointing localhost to a folder

### ISSUE THREAD

**Issue by chrisGeonet** [laravel/valet#802]
I'm trying to set up Braintree payment on a Laravel install to use GooglePay.
The docs say "Your website and any assets must be served over HTTPS (or localhost if testing in sandbox) for the Google Pay option to appear".
As I'm using a sandbox account I need to be running the site on localhost.

Is there any way of pointing http://localhost to http://mylaravelsite.test?

Thanks

**Comment by drbyte** [comment]
You can add a `default` entry to your valet config.

`~/.config/valet/config.json`
```diff
{
    "paths": [
        "/Users/me/.config/valet/Sites",
        "/Users/me/Sites",
    ],
+    "default": "/Users/me/Sites/myfallbackproject",
    "tld": "test"
}
```

**Comment by chrisGeonet** [comment]
Thanks, that worked perfectly.
