### ISSUE TITLE
Safari on macOS 10.14.6 does not include cookies in POST request

### ISSUE THREAD

**Issue by marin246** [laravel/valet#803]
On a fresh installation of macOS 10.14.6 and laravel valet, Safari does not include cookies in POST requests such that a new session is generated with the POST request (and a status of 419 is returned; see below).
On Firefox and Chrome: no problem.

Has anyone had a similar behavior?

> Übersicht
URL: https://plus.test/login
Status: 200
Quelle: Netzwerk
Adresse: 127.0.0.1:443

> Anfrage
:method: GET
:scheme: https
:authority: plus.test
:path: /login
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Encoding: br, gzip, deflate
Host: plus.test
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.2 Safari/605.1.15
Accept-Language: de-ch
Referer: https://plus.test/login
Connection: keep-alive

> Antwort
:status: 200
Content-Type: text/html; charset=UTF-8
Set-Cookie: XSRF-TOKEN=eyJpdiI6IjZ6eFR6WFZrUWF2bUpBeDJwNUFQK3c9PSIsInZhbHVlIjoiR3pMcGJ6STUyeFE5d0xXZ3pieHdOSGxwMllDOEROcldIQ2JQcVFhK0hVQ2t4UllhSGgydFBmOE92c2kwSTF2WSIsIm1hYyI6Ijg1M2VjZWUzYjFjM2JmYTA4ZjdkZmU5NDU1NGNmM2UxMmU0OWNkNTQwYTc0MDhhNjY3YTBhMDU2ZTA5ODE5YjMifQ%3D%3D; expires=Mon, 29-Jul-2019 16:54:36 GMT; Max-Age=7199; path=/; domain=.plus.test; secure; samesite=lax
Set-Cookie: plus_session=eyJpdiI6IkV5eTVVcnFJYzZ3a01DOFljUUxuUVE9PSIsInZhbHVlIjoiMGtZbWg3Zm9NVVhSK1U0YXJ5elllVzg5Y05ESTlURG1ncFhYeE5ZcEg2d0JLMFVlUGRvdWxSR0hqU2REd2swcyIsIm1hYyI6IjE2YzlmZDYyNjhkMzc3OTUzYzUzYTMzMGVmZWJkNTE2YTZjMjc2ODUyMzgwYmZlZjgwYzY5YWYyN2UxNDk3MGUifQ%3D%3D; expires=Mon, 29-Jul-2019 16:54:36 GMT; Max-Age=7199; path=/; domain=.plus.test; secure; httponly; samesite=lax
Date: Mon, 29 Jul 2019 14:54:36 GMT
Content-Encoding: gzip
Cache-Control: no-cache, private
Vary: Accept-Encoding
Server: nginx/1.17.2
x-powered-by: PHP/7.3.7

> Übersicht
URL: https://plus.test/login
Status: 419
Quelle: Netzwerk
Adresse: 127.0.0.1:443

> Anfrage
:method: POST
:scheme: https
:authority: plus.test
:path: /login
Cookie: _ga=GA1.2.XXX; _gat_gtag_UA_XXX_2=1; _gid=GA1.2.XXXX
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Content-Type: application/x-www-form-urlencoded
Origin: https://plus.test
Content-Length: 64
Accept-Language: de-ch
Host: plus.test
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.2 Safari/605.1.15
Referer: https://plus.test/login
Accept-Encoding: br, gzip, deflate
Connection: keep-alive

> Antwort
:status: 419
Set-Cookie: plus_session=eyJpdiI6IkhDYnFKSXNQQ1dPbjU5RGNcLzUrOFBnPT0iLCJ2YWx1ZSI6IjJNYmtKN0lyZk1sWnRacDFZeGJVWWR6QU1TOXAzUjFxY1dLakl3YUVmUXcydEgzRENGWXRlaURqYktKRUtcL1d2IiwibWFjIjoiZjQ4NTE5OTYxNzFhN2FiYjQ1ZGExZDk0Mjc3NGNiMTc5MDI3NWNiYTczNGUzYjgxNDhlMDk1M2YxODA4M2VhNSJ9; expires=Mon, 29-Jul-2019 16:50:40 GMT; Max-Age=7200; path=/; domain=.plus.test; secure; httponly; samesite=lax
Date: Mon, 29 Jul 2019 14:50:40 GMT
Content-Type: text/html; charset=UTF-8
Cache-Control: no-cache, private
x-powered-by: PHP/7.3.7
Server: nginx/1.17.2

> Anfragedaten
MIME-Typ: application/x-www-form-urlencoded
_token: nmFcz3eyWlry8oytWeZYhPzM8NBhI6wNX9kmyJpD
email
password

**Comment by drbyte** [comment]
I haven't done that upgrade yet, so can't comment on that specific environment.

Is this happening with a fresh new Laravel app? Or if not, can you provide steps to recreate using a fresh new Laravel install?

**Comment by marin246** [comment]
yes, it is happening on a fresh install of laravel. I noticed that it works as long as `'same_site' => null,` is set in config/session.php. If you alter it to `'same_site' => 'lax,`, it stops working in Safari.

**Comment by drbyte** [comment]
> I noticed that it works as long as `'same_site' => null,` is set in config/session.php. If you alter it to `'same_site' => 'lax',`, it stops working in Safari.

After a big of browsing, it seems clear this is not a Valet issue. 

It's a known issue with Safari:
https://news.ycombinator.com/item?id=19855476
https://github.com/vintasoftware/safari-samesite-cookie-issue
https://github.com/httpwg/http-extensions/commit/49bcb4fddb8a8c294749ec9d81a236cde4df94b0

You'll need to code your app according to the limitations of the browsers you support. :(

**Comment by marin246** [comment]
I've come across some of those sites as well but I just find it very peculiar that everything worked fine up until macOS 10.14.6, which was released less than a month ago. (Those articles are considerably older)

**Comment by drbyte** [comment]
> everything worked fine up until macOS 10.14.6

> User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.2 Safari/605.1.15

FWIW: On my macOS 10.14.5 Safari reports 12.1.1

I agree: it does seem strange that a long-time-known-problematic feature like this would work fine but suddenly break by a 0.0.1 point release change.

**Comment by drbyte** [comment]
I think this issue can be closed, since it's not something Valet controls.

If you find a workaround which you wish to share for future reference, feel free to post it here if it can help others.
