### ISSUE TITLE
ERR_CONNECTION_REFUSED, nginx can't find .crt file

### ISSUE THREAD

**Issue by heggern** [laravel/valet#807]
Hi.

I've been fighting valet (or maybe nginx) the whole day. I upgraded Valet from 2.0 something to Valet 2.3.3, and from PHP 7.1 to 7.3.8, and suddenly every application stoped working. Got the ERR_CONNECTION_REFUSED in Chrome.

When running `nginx -t` dumps this error:
```
nginx: [emerg] cannot load certificate "/Users/heggern/.config/valet/Certificates/testapp.test.crt": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/Users/heggern/.config/valet/Certificates/testapp.test.crt','r') error:2006D080:BIO routines:BIO_new_file:no such file)
nginx: configuration file /usr/local/etc/nginx/nginx.conf test failed
```

Inside `/.config/valet/Certificates` there is no `.crt` file, just three other files: `.conf`, `.csr` and `.key`

I have tried to uninstall everything, and re-install, but no luck. No `.crt` file anywhere.

I also looked into an old valet folder (renamed my old valet folder to valet-backup before removing everything), but there wasn't any `.crt` file.

Anyone with any information who to get the `.crt` file to be created with the `valet secure` command?

**Comment by drbyte** [comment]
Sounds oddly familiar to https://github.com/laravel/valet/issues/654 for which v2.2.2 was released.

Maybe there's a permissions mask issue on your `~/.config` directory, preventing the files from being generated?

**Comment by drbyte** [comment]
Also, since you didn't mention it, and it solves a myriad of problems, I'll ask: have you rebooted since upgrading all those components?

**Comment by heggern** [comment]
Thanks for the reply @drbyte.

I have restarted after upgrading and re-installing. Several times, but no luck.

I also tested the change in `Site.php` on line 307, but still nothing.

Everything running as `root`: `brew services list`
```
dnsmasq    started root /Library/LaunchDaemons/homebrew.mxcl.dnsmasq.plist
mongodb    started root /Library/LaunchDaemons/homebrew.mxcl.mongodb.plist
mysql      started root /Library/LaunchDaemons/homebrew.mxcl.mysql.plist
mysql@5.7  started root /Library/LaunchDaemons/homebrew.mxcl.mysql@5.7.plist
nginx      started root /Library/LaunchDaemons/homebrew.mxcl.nginx.plist
php        started root /Library/LaunchDaemons/homebrew.mxcl.php.plist
php@7.2    stopped
postgresql started root /Library/LaunchDaemons/homebrew.mxcl.postgresql.plist
redis      started root /Library/LaunchDaemons/homebrew.mxcl.redis.plist
unbound    started root /Library/LaunchDaemons/homebrew.mxcl.unbound.plist
```

**Comment by heggern** [comment]
Update

Dumped the $result from Site.php line 307.

```
WARNING: can't open config file: /usr/local/php5/ssl/openssl.cnf
Signature ok
subject=/CN=spontio-front.test/emailAddress=spontio-front.test@laravel.valet
Error opening CA Certificate /Users/heggern/.config/valet/CA/LaravelValetCASelfSigned.pem
```

So, I guess an old `php5` is still bugging my system, and that the `.config/valet/CA`folder is empty.

**Comment by heggern** [comment]
Yes! Found the solution.

Copied the file `System/Library/OpelSSL/openssl.conf` to `usr/local/php5/ssl/openssl.conf`.

Then `brew reinstall openssl` and the `valet secure`works! Finally. After 13 hours without my localhost setup.
