### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by grantholle** [laravel/valet#815]
I had it installed successfully, but was having trouble using `valet share`. I found others who said to uninstall valet, update composer and reinstall valet. Which I did.

I've used homebrew to install composer:

```
➜ composer --version                   
Composer version 1.9.0 2019-08-02 20:55:32
➜ php -v             
PHP 7.3.9 (cli) (built: Aug 30 2019 01:42:25) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.9, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.9, Copyright (c) 1999-2018, by Zend Technologies
```

But when trying to `composer global require laravel/valet` I get the [following failure](https://gist.github.com/grantholle/bd6749b46aea859a12ced1c1cb45979e).

I've removed the global lock file and the global vendor directory, reran `composer global install`, and still receive the same installation error.

**Comment by drbyte** [comment]
Looks like you've got conflicts in your global composer config.
What's the content of your `~/.composer/composer.json` file?

**Comment by grantholle** [comment]
I've done some tinkering, but here's the last attempt:

```json
{
    "require": {
        "laravel/installer": "~1.1",
        "laravel/envoy": "dev-master",
        "laravel/lumen-installer": "dev-master",
        "bamarni/symfony-console-autocomplete": "dev-master",
        "hirak/prestissimo": "dev-master"
    }
}
```

Could it be the Laravel installer?

**Comment by drbyte** [comment]
What's `composer global why illuminate/contracts` report?

**Comment by grantholle** [comment]
```
➜ composer global why illuminate/contracts
Changed current directory to /Users/grant/.composer
illuminate/support  v6.0.0  requires  illuminate/contracts (^6.0) 
```

**Comment by drbyte** [comment]
now the same with illuminate/support

**Comment by grantholle** [comment]
```

**Comment by drbyte** [comment]
Looks like laravel/envoy is your issue.  Why dev-master ?

**Comment by grantholle** [comment]
Not sure? I'll remove it and see what changes. Thanks @drbyte

**Comment by drbyte** [comment]
Overall explanation: One of your global dependencies is accepting 6.0, but others are not yet.

The simplest way to downgrade is to either add a dependency on an older version of one of those dep's, or re-install all of them "at one time" so Composer calculates the best match.

Here's a quick way to do it (deletes all previous matchings, and then builds fresh with the new addition).
```sh
composer global remove laravel/envoy
rm -rf ~/.composer/vendor composer.lock
composer global require laravel/valet laravel/envoy
```

**Comment by drbyte** [comment]
(Or, if some of those packages are NOT actually used by you now/anymore, just composer global remove them. That'll make life simpler until you actually need them.)

**Comment by grantholle** [comment]
Yep that was it. Thanks so much! Lifesaver

**Comment by drbyte** [comment]
Cool! That `composer why` thing is very handy ;)
