### ISSUE TITLE
Nginx 400 Request Header Or Cookie Too Large

### ISSUE THREAD

**Issue by alekseyp** [laravel/valet#820]
After upgrading to Laravel Valet 2.4.1 and running `valet install` I've started getting 400 error on all laravel sites (need to login and do couple clicks).

Looks like https://github.com/laravel/valet/pull/813 has introduced bad nginx config.

I've reverted to default nginx values and everything is back to normal.

I won't do PR since the current one can be simply reverted, but will leave it here in case other people face the same issue.

**Comment by drbyte** [comment]
Argh. Sorry about that.

I agree: we'll probably just revert #813.   

In the meantime ... Question: for these same local apps, is your related production server running on Forge? ie: do Forge-related settings "matter" in your case?

**Comment by mattstauffer** [comment]
Reverted. https://github.com/laravel/valet/releases/tag/v2.4.2

(Feel free to keep the conversation open though!)
