### ISSUE TITLE
Certificate Location Empty?

### ISSUE THREAD

**Issue by latwelve** [laravel/valet#827]
If I go here:

~/.config/valet/Certificates 

Then it is empty. I am trying to add the master file to firefox so I can access local sites via https.

I have around 20 sites working on https with valet locally with chrome

Any pointers appreciated

**Comment by drbyte** [comment]
I'm puzzled that you'd find that directory empty, since that's the directory where Valet stores its certificates for those "20 sites working on https with valet".

Things in that directory are automatically generated when you run `valet secure` on any folder.

**Comment by drbyte** [comment]
@latwelve what's the output of `valet links` and `valet parked`?

**Comment by drbyte** [comment]
@latwelve if you upgrade to Valet 2.6 (`composer global update`) and run `valet install` it should re-secure those sites, which will regenerate the Certificates directory etc.

It also handles spaces in directory-names better, in case that's what's been causing the problem you're reporting.

Please report back whether that solves your issue. If there's no response, we'll probably just assume it's been fixed for you and close this Issue.

**Comment by drbyte** [comment]
@latwelve is this still an issue? If not, please click Close.

**Comment by drbyte** [comment]
@mattstauffer Seems like this can be closed.
