### ISSUE TITLE
Curl returning SSL_ERROR_SYSCALL

### ISSUE THREAD

**Issue by pauladams8** [laravel/valet#828]
I started using Laravel Valet a couple of days ago and set up a secure connection using `valet secure`. Ever since, requests made from my application have been returning the error `cURL error 35: OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to`. This is the same for all websites, so I didn't bother including the address.

Interestingly, I face no problems when visiting these websites in the browser or via the command line curl, so I concluded it had to be related to Valet.

Valet's certificates are working fine as I can find them in `~/.config/valet/Certificates` and they are trusted in my browser (Chrome).

**Comment by drbyte** [comment]
Sounds like an openssl problem on your Mac. or a libcurl conflict.

What's the output of the following?
```sh
sw_vers
valet --version
openssl version -a
openssl ciphers
php -v
which -a php
nginx -v
curl --version
php --ri curl
brew info openssl
brew info nginx
```

**Comment by pauladams8** [comment]
- ProductName:	Mac OS X
ProductVersion:	10.13.6
BuildVersion:	17G5019
- Laravel Valet 2.5.0
- LibreSSL 2.2.7
built on: date not available
platform: information not available
options:  bn(64,64) rc4(ptr,int) des(idx,cisc,16,int) blowfish(idx)
compiler: information not available
OPENSSLDIR: "/private/etc/ssl"
- ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-CHACHA20-POLY1305:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-DSS-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA256:DHE-RSA-AES256-SHA:DHE-DSS-AES256-SHA:GOST2012256-GOST89-GOST89:DHE-RSA-CAMELLIA256-SHA256:DHE-DSS-CAMELLIA256-SHA256:DHE-RSA-CAMELLIA256-SHA:DHE-DSS-CAMELLIA256-SHA:GOST2001-GOST89-GOST89:ECDH-RSA-AES256-GCM-SHA384:ECDH-ECDSA-AES256-GCM-SHA384:ECDH-RSA-AES256-SHA384:ECDH-ECDSA-AES256-SHA384:ECDH-RSA-AES256-SHA:ECDH-ECDSA-AES256-SHA:AES256-GCM-SHA384:AES256-SHA256:AES256-SHA:CAMELLIA256-SHA256:CAMELLIA256-SHA:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:DHE-DSS-AES128-GCM-SHA256:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES128-SHA256:DHE-DSS-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA:DHE-RSA-CAMELLIA128-SHA256:DHE-DSS-CAMELLIA128-SHA256:DHE-RSA-CAMELLIA128-SHA:DHE-DSS-CAMELLIA128-SHA:ECDH-RSA-AES128-GCM-SHA256:ECDH-ECDSA-AES128-GCM-SHA256:ECDH-RSA-AES128-SHA256:ECDH-ECDSA-AES128-SHA256:ECDH-RSA-AES128-SHA:ECDH-ECDSA-AES128-SHA:AES128-GCM-SHA256:AES128-SHA256:AES128-SHA:CAMELLIA128-SHA256:CAMELLIA128-SHA:ECDHE-RSA-RC4-SHA:ECDHE-ECDSA-RC4-SHA:ECDH-RSA-RC4-SHA:ECDH-ECDSA-RC4-SHA:RC4-SHA:RC4-MD5:ECDHE-RSA-DES-CBC3-SHA:ECDHE-ECDSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:EDH-DSS-DES-CBC3-SHA:ECDH-RSA-DES-CBC3-SHA:ECDH-ECDSA-DES-CBC3-SHA:DES-CBC3-SHA:EDH-RSA-DES-CBC-SHA:EDH-DSS-DES-CBC-SHA:DES-CBC-SHA
- PHP 7.3.10
- /usr/local/bin/php
/usr/bin/php
- nginx version: nginx/1.17.3
- curl 7.54.0 (x86_64-apple-darwin17.0) libcurl/7.54.0 LibreSSL/2.0.20 zlib/1.2.11 nghttp2/1.24.0
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz HTTP2 UnixSockets HTTPS-proxy
- curl

cURL support => enabled
cURL Information => 7.66.0
Age => 5
Features
AsynchDNS => Yes
CharConv => No
Debug => No
GSS-Negotiate => No
IDN => No
IPv6 => Yes
krb4 => No
Largefile => Yes
libz => Yes
NTLM => Yes
NTLMWB => Yes
SPNEGO => Yes
SSL => Yes
SSPI => No
TLS-SRP => Yes
HTTP2 => Yes
GSSAPI => Yes
KERBEROS5 => Yes
UNIX_SOCKETS => Yes
PSL => No
HTTPS_PROXY => Yes
MULTI_SSL => No
BROTLI => Yes
Protocols => dict, file, ftp, ftps, gopher, http, https, imap, imaps, ldap, ldaps, pop3, pop3s, rtmp, rtsp, scp, sftp, smb, smbs, smtp, smtps, telnet, tftp
Host => x86_64-apple-darwin17.7.0
SSL Version => OpenSSL/1.1.1d
ZLib Version => 1.2.11
libSSH Version => libssh2/1.9.0

Directive => Local Value => Master Value
curl.cainfo => no value => no value
ADAMS-MBP:~ paul.adams$ php --ri curl

curl

cURL support => enabled
cURL Information => 7.66.0
Age => 5
Features
AsynchDNS => Yes
CharConv => No
Debug => No
GSS-Negotiate => No
IDN => No
IPv6 => Yes
krb4 => No
Largefile => Yes
libz => Yes
NTLM => Yes
NTLMWB => Yes
SPNEGO => Yes
SSL => Yes
SSPI => No
TLS-SRP => Yes
HTTP2 => Yes
GSSAPI => Yes
KERBEROS5 => Yes
UNIX_SOCKETS => Yes
PSL => No
HTTPS_PROXY => Yes
MULTI_SSL => No
BROTLI => Yes
Protocols => dict, file, ftp, ftps, gopher, http, https, imap, imaps, ldap, ldaps, pop3, pop3s, rtmp, rtsp, scp, sftp, smb, smbs, smtp, smtps, telnet, tftp
Host => x86_64-apple-darwin17.7.0
SSL Version => OpenSSL/1.1.1d
ZLib Version => 1.2.11
libSSH Version => libssh2/1.9.0

Directive => Local Value => Master Value
curl.cainfo => no value => no value
- openssl: stable 1.0.2t (bottled) [keg-only]
SSL/TLS cryptography library
https://openssl.org/
/usr/local/Cellar/openssl/1.0.2r (1,795 files, 12.1MB)
  Poured from bottle on 2019-04-04 at 17:11:25
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/openssl.rb
- nginx: stable 1.17.3 (bottled), HEAD
HTTP(S) server and reverse proxy, and IMAP/POP3 proxy server
https://nginx.org/
/usr/local/Cellar/nginx/1.17.3_1 (25 files, 2MB) *
  Poured from bottle on 2019-10-06 at 20:53:51
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/nginx.rb
==> Dependencies
Required: openssl@1.1 ✔, pcre ✔

**Comment by drbyte** [comment]
Most of that looks fine.
I'd recommend `brew update && brew upgrade && brew cleanup` if only to update your openssl from 1.0.2r to 1.0.2t but I'm not convinced that'd resolve the issue you've mentioned.

When you say `requests made from my application have been returning the error cURL error 35` how exactly is the application making those requests? Any packages involved? What framework is the app using? 
Before Valet, what were you using?

**Comment by pauladams8** [comment]
I have a variety of different API clients that make outbound requests from my application (some I've made, some are 3rd party). I personally use Guzzle (6.0), but I'm getting the same error everywhere and it comes from PHP curl. Presumably Guzzle eventually uses this to make the requests.

I'm currently trying to reinstall Valet from scratch to see if this will solve the problem, and will try your steps if this doesn't work. I've deleted the entire config directory at `~/.config/valet` in case there's something there that's corrupted.

**Comment by drbyte** [comment]
The underlying CURL issue doesn't sound like a Valet problem. (Valet is just a wrapper around Nginx/PHP/Dnsmasq).
Perhaps your MacOS version requires some special handling of CURL in PHP's configs. 
I didn't have those issues on 10.13 but I know some others do have CURL issues with Wordpress. Still haven't found a common denominator for those cases.

**Comment by drbyte** [comment]
The CURL error #35 simply means it couldn't negotiate TLS/SSL securely. And that usually comes down to bad certificates in the location set in the curl config in use during that call.

**Comment by pauladams8** [comment]
I wasn't sure where the problem lay, so I just went ahead and reinstalled Homebrew, PHP, Nginx and Valet from scratch. It seems to have fixed the curl error.

**Comment by pauladams8** [comment]
I reinstalled homebrew because `brew doctor` seemed to list a lot of missing symlinks and other problems.

**Comment by drbyte** [comment]
Fantastic! 
It's very possible that the update of Homebrew's packages (including that openssl version) is all that was needed.
Thanks for posting back.

If this is resolved, please click Close below.

**Comment by pauladams8** [comment]
Sorry, I spoke too soon. I'm getting this. error still, though not on all requests.
`cURL error 35: OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to acme-v02.api.letsencrypt.org:443  (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)`.

**Comment by pauladams8** [comment]
I guess it's probably not related to Valet though, so I'll keep digging.
