### ISSUE TITLE
How to make valet allow CORS requests to public folder?

### ISSUE THREAD

**Issue by marbuser** [laravel/valet#836]
I'm writing a project that consists of a REST API in Laravel, and then a VueJS SPA frontend.
E.G https://github.com/yyx990803/laravel-vue-cli-3

However, there are certain instances in my app where I need to make requests from the frontend to the backend to get an image from the public folder. But it's constantly blocked by CORS and I feel like I've tried everything.

- I've tried using the `laravel-cors` package, which apparently doesn't effect the public folder.
- I've tried modifying the .htaccess inside the public folder.

So how can I go about allowing it so that requests can be made directly to "project.test/my-image.jpg" and be allowed via CORS?

**Comment by itguy614** [comment]
The simplest configuration to allow CORS requests in valet is to add the following file and restart nginx.  This will enable the request for all projects.

~/.config/valet/Nginx/cors.conf
```
# CORS Rules
add_header Access-Control-Allow-Origin *;
# END of CORS Rules #
```

And then restart valet.

```
valet restart
```

**Comment by drbyte** [comment]
Agreed.

@marbuser does this work for your needs?

**Comment by drbyte** [comment]
@mattstauffer I believe this can be closed.

**Comment by pieter-janDB** [comment]
This fix is not working for me. I keep getting CORS errors between my valet domains when I call an api from another project

**Comment by djmtype** [comment]
Same here. It works for the page itself, but not the assets like js, css and images.

**Comment by AlexBa** [comment]
Does not work for me. Searching hours for a solution now.
