### ISSUE TITLE
Invalid Cert Authority

### ISSUE THREAD

**Issue by atymic** [laravel/valet#838]
Hey.

I had some issues with my valet so I did a fresh install. Everything appears to be back working again, however I've got an issue with secured sites.

It seems that the cert authority is not trusted or the config is broken.
Another interesting thing is I see that nginx is loading the wrong cert?

<img width="722" alt="Screen Shot 2019-11-04 at 8 44 44 pm" src="https://user-images.githubusercontent.com/50683531/68111736-fa600800-ff43-11e9-8d99-47796a0fc5a6.png">

<img width="700" alt="Screen Shot 2019-11-04 at 8 46 52 pm" src="https://user-images.githubusercontent.com/50683531/68111887-43b05780-ff44-11e9-9df9-eee12e011c24.png">

I'll try and get some more information as I continue to debug.

**Comment by atymic** [comment]
So after some more debugging it seems that for some strange reason, nignx is loading the wrong config. 
The `SERVER_NAME` variable shows that of a different valet domain 🤔

<img width="776" alt="Screen Shot 2019-11-04 at 8 53 08 pm" src="https://user-images.githubusercontent.com/50683531/68112728-1fee1100-ff46-11e9-8ed5-d3390646b6b0.png">

**Comment by drbyte** [comment]
> So after some more debugging it seems that for some strange reason, nignx is loading the wrong config.
> The `SERVER_NAME` variable shows that of a different valet domain 🤔
That's normal, although confusing when it happens the first time. 
https://www.itworld.com/article/2987967/why-your-nginx-server-is-responding-with-content-from-the-wrong-site.html

When it happens I find it's usually because I've reset my valet setup (insomuch as breaking that vhost or removing it but still trying to visit that site with https) and simply need to re-run valet secure for that specific domain so that it's rebuilt and nginx restarted. And then all is good again.

**Comment by atymic** [comment]
> When it happens I find it's usually because I've reset my valet setup (insomuch as breaking that vhost or removing it but still trying to visit that site with https) and simply need to re-run valet secure for that specific domain so that it's rebuilt and nginx restarted. And then all is good again.

I tried re-securing the sites a bunch on time but that didn't fix it.

It did randomly fix itself about 3 days later so i'm going to close this. No idea why 🤷‍♂

**Comment by djnorrisdev** [comment]
Might as well delete this entire issue if no solution has been proposed.
