### ISSUE TITLE
Proxy to different Port

### ISSUE THREAD

**Issue by KaiReichart** [laravel/valet#839]
Hey,
is it possible to have valet act as a proxy to a running server on localhost? 
e.g. http://mailhog.test => http://127.0.0.1:8025

**Comment by drbyte** [comment]
1. Create a new file: `~/.config/valet/Nginx/mailhog.test`
```
server {
    server_name mailhog.test;
    listen 127.0.0.1:80;
    location / {
            proxy_pass      http://localhost:8025;
            proxy_set_header    Host             $host;
            proxy_set_header    X-Real-IP        $remote_addr;
            proxy_set_header    X-Forwarded-For  $proxy_add_x_forwarded_for;
            proxy_set_header    X-Client-Verify  SUCCESS;
            proxy_set_header    X-Client-DN      $ssl_client_s_dn;
            proxy_set_header    X-SSL-Subject    $ssl_client_s_dn;
            proxy_set_header    X-SSL-Issuer     $ssl_client_i_dn;
            proxy_read_timeout 1800;
            proxy_connect_timeout 1800;
            chunked_transfer_encoding on;
            proxy_set_header X-NginX-Proxy true;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_http_version 1.1;
            proxy_redirect off;
            proxy_buffering off;
    }
}
```

2. Run `sudo nginx -t` to be sure you haven't made any errors.
3. Run `valet restart`
4. Visit http://mailhog.test

Be aware that if you run the `valet tld` command to change your `.test` tld to something else, it will rewrite this file from default stubs. So keep a backup.

Inspired from: https://gist.github.com/blakethepatton/7928abb131593fd192606b681ee47b2b

**Comment by drbyte** [comment]
@KaiReichart This seemed to work fine for me. 

Did it work for you? Is this Issue still needed, or can it be closed?

**Comment by KaiReichart** [comment]
Yes, it worked perfectly, thanks
