### ISSUE TITLE
.app tld and tinkerwell.app domain

### ISSUE THREAD

**Issue by subdesign** [laravel/valet#840]
hey,
a new Mac app released, on the domain tinkerwell.app, but my system thinks it is a Valet domain, and stops loading it (Your connection is not private.., etc.)
I tried `valet unlink tinkerwell`, but no change even I get the message
`The [tinkerwell] symbolic link has been removed. `

best **clean** way to make this domain work?
- I don't want to change my Valet tld, it's hardcoded in lot of projects..
- I don't want stop Valet every time when I visit this site (or other .app sites)

thanks

**Comment by mattstauffer** [comment]
Unfortunately, unless someone else comes along and tells me I'm wrong on this, you're stuck. `.dev` and `.app` TLDs have been announced for a while and the moment they were we did some research and started moving to `.test` for *exactly this reason.* 

If you choose any TLD other than `.test` (or, technically, `.localhost`, but it has its issues) you will run into this problem some day.

https://github.com/laravel/valet/pull/436

**Comment by subdesign** [comment]
Thanks, I'm an old Valet user that times the default tld was .app :) Didn't realize the changes..
Going to use .test 
Thx

**Comment by mattstauffer** [comment]
@subdesign Totally understood! I fought it hard for a long time!!
