### ISSUE TITLE
PHP 7.4 Support 

### ISSUE THREAD

**Issue by ravenberg** [laravel/valet#846]
Hiya,

With the https://github.com/Homebrew/homebrew-core/pull/47289 PR merged `brew install php` installs version `7.4`. However the installer is still set on the supported and latest version `7.3`. 

By adding `7.4` to the `SUPPORTED_PHP_VERSIONS` array I got the installer working and have my dev environment running on `7.4` just fine. Would it be desirable to make a PR? Or is someone working on it already?

**Comment by drbyte** [comment]
Yes, updating both the SUPPORTED constant to include @7.4 works for me. (I also updated the LATEST constant to 7.4). I also ran `valet install` so that it updated the php 7.4 configs to work with valet.

Feel free to submit a PR.

**Comment by ravenberg** [comment]
Thanks for your assistance @drbyte. I'll close this issue now since the PR has been merged.
