### ISSUE TITLE
Valet install failed after upgrading to PHP 7.4

### ISSUE THREAD

**Issue by sadhakbj** [laravel/valet#848]
I upgraded my php to latest version (7.4) and while trying to install valet i got the following error:

```
valet install 

Stopping nginx...
Installing nginx configuration...
Installing nginx directory...
Updating PHP configuration...

In Brew.php line 251:

  Unable to determine linked PHP when parsing '7.4'


install
```

**Comment by LeRoyJulian** [comment]
Same here. Did you find a solution ?

**Comment by LeRoyJulian** [comment]
1. `nano ~/.composer/vendor/laravel/valet/cli/Valet/Brew.php`
2. Add 'php@7.4' into SUPPORTED_PHP_VERSIONS.
3. Try again `valet install`

**Comment by sadhakbj** [comment]
@LeRoyJulian thanks. It did work. Someone needs to send PR updating the file Brew.php

**Comment by evinkuraga** [comment]
Can this be reopened. I'm getting this error even though the line was already added in the Brew.php file.
