### ISSUE TITLE
Certificate not generating when spaces in filepath

### ISSUE THREAD

**Issue by cdavid138** [laravel/valet#862]
Hi there,

I've been battling with this for a couple of days and looking for some assistance.

It seems to be since moving my user folder onto a different internal HD, i'm unable to generate SSLs for sites getting the error:

```
nginx: [emerg] cannot load certificate "/Volumes/Storage HD/Users/david/.config/valet/Certificates/healthkit.test.crt": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/Volumes/Storage HD/Users/david/.config/valet/Certificates/healthkit.test.crt','r') error:2006D080:BIO routines:BIO_new_file:no such file)
nginx: configuration file /usr/local/etc/nginx/nginx.conf test failed
```

I've read through
#807 
#329 

Unfortunatley those errors have not helped.

Running 
Mac OS: 10.15.1
Valet: 2.5.4

```
~ brew services list
Name      Status  User  Plist
dnsmasq   started root  /Library/LaunchDaemons/homebrew.mxcl.dnsmasq.plist
mysql@5.7 started david /Volumes/Storage HD/Users/david/Library/LaunchAgents/homebrew.mxcl.mysql@5.7.plist
nginx     started root  /Library/LaunchDaemons/homebrew.mxcl.nginx.plist
php@7.3   started root  /Library/LaunchDaemons/homebrew.mxcl.php@7.3.plist
```

Certificates not successfully being generated but no errors when using valet secure
```
~ ls -ltr ~/.config/valet/Certificates
total 24
-rwxrwxrwx  1 david  staff  1675  3 Dec 09:45 healthkit.test.key
-rwxrwxrwx  1 david  staff  1074  3 Dec 09:45 healthkit.test.csr
-rwxrwxrwx  1 david  staff   744  3 Dec 09:45 healthkit.test.conf
```
Completely fresh install as of yesterday evening, all help appreciated thanks!

**Comment by drbyte** [comment]
> seems to be since moving my user folder onto a different internal HD

> No such file... fopen(
'/Volumes/Storage HD/Users/david/.config/valet/Certificates/healthkit.test.crt'

First guess: I'm wondering if maybe it's not liking the space in your volume name `Storage HD` when trying to write the `.crt` file. It looks like the other 3 related files are created fine though.

**Comment by drbyte** [comment]
As such, I'm curious whether if you wrap the single remaining `%s` in double-quotes like `"%s"` in these 3 lines 
of your `~/.composer/vendor/laravel/valet/cli/Valet/Site.php file` maybe that'll fix it for you?

https://github.com/laravel/valet/blob/3d877ef803732f8e7388cea4beeb525703ce16cc/cli/Valet/Site.php#L374

https://github.com/laravel/valet/blob/3d877ef803732f8e7388cea4beeb525703ce16cc/cli/Valet/Site.php#L381

https://github.com/laravel/valet/blob/3d877ef803732f8e7388cea4beeb525703ce16cc/cli/Valet/Site.php#L436

**Comment by cdavid138** [comment]
Thanks for the help!

No such luck with that solution im afraid. Same result, three files generated, no .crt.

Also note that the output of valet links doesn't show the SSL enabled for that site, but I assume that's because its checking for the existance of a .crt file.

```
Password:
+-----------+-----+-----------------------+----------------------------------------------------------+
| Site      | SSL | URL                   | Path                                                     |
+-----------+-----+-----------------------+----------------------------------------------------------+
| healthkit |     | http://healthkit.test | /Volumes/Storage HD/Users/david/Documents/Work/healthkit |
+-----------+-----+-----------------------+----------------------------------------------------------+
```

**Comment by drbyte** [comment]
> Also note that the output of valet links doesn't show the SSL enabled for that site, but I assume that's because its checking for the existance of a .crt file.

Yes, that's exactly right.

**Comment by drbyte** [comment]
It's probably too drastic to explore renaming that `Storage HD` volume to have no space, right?

**Comment by drbyte** [comment]
Next best step would be manually running the various `openssl` commands that Valet performs, to see whether any errors are coming up, and dealing with whatever they mean.

In that same `Site.php` file around line 373 you have this section of code. Try changing it as follows, and the attempt `valet secure` again:
```diff

        $result = $this->cli->runAsUser(sprintf(
            'openssl x509 -req -sha256 -days 730 -CA "%s" -CAkey "%s" %s -in "%s" -out "%s" -extensions v3_req -extfile "%s"',
            $caPemPath, $caKeyPath, $caSrlParam, $csrPath, $crtPath, $confPath
-        ));
+        ),
+            function ($exitCode, $outputMessage) {
+                throw new DomainException("errors: [$exitCode: $outputMessage].");
+            }
+        );
```

**Comment by cdavid138** [comment]
Perfect thanks, will give that a go now.

I did try a rename of the HD, to just Storage, but same result.

Will proceed with testing these commands now.

**Comment by cdavid138** [comment]
Getting somewhere...

```
  errors: [1: unknown option -CAserial /Volumes/Storage HD/Users/david/.config/valet/CA/LaravelValetCASelfSigned.srl -CAcreateserial
  usage: x509 args
```
Possible this is an openssl error?

**Comment by drbyte** [comment]
That feels like space issue causing parameters to be misinterpreted

**Comment by cdavid138** [comment]
So i think that was caused by adding the quotes around the remaining %s values, as it resulted in the added params for $caSrlParam being contained within the quotes, ie:

```
" -CAserial ..."
```

So i've now modified it to add the quotes around the filepath a few lines above as follows:

```
$caSrlParam = '-CAserial "' . $caSrlPath . '"';
```

That results in the command the code is running as follows

```
openssl x509 -req -sha256 -days 730 -CA "/Volumes/Storage HD/Users/david/.config/valet/CA/LaravelValetCASelfSigned.pem" -CAkey "/Volumes/Storage HD/Users/david/.config/valet/CA/LaravelValetCASelfSigned.key" -CAserial "/Volumes/Storage HD/Users/david/.config/valet/CA/LaravelValetCASelfSigned.srl" -CAcreateserial -in "/Volumes/Storage HD/Users/david/.config/valet/Certificates/healthkit.test.csr" -out "/Volumes/Storage HD/Users/david/.config/valet/Certificates/healthkit.test.crt" -extensions v3_req -extfile "/Volumes/Storage HD/Users/david/.config/valet/Certificates/healthkit.test.conf"
```

Which does execute correctly, but still getting the error when its run as part of the valet secure script.

**Comment by drbyte** [comment]
Good work.

So, if it works fine on its own, are we sure Valet is correctly generating the same command?

**Comment by cdavid138** [comment]
Okay changing the following line actually sorted it once I removed the quotes around the %s that we added.

```
$caSrlParam = '-CAserial "' . $caSrlPath . '"';
```

However now getting NET::ERR_CERT_INVALID, so i'm assuming we're now failing to add this to the keychain somewhere?

**Comment by drbyte** [comment]
> However now getting NET::ERR_CERT_INVALID, so i'm assuming we're now failing to add this to the keychain somewhere?

Ya, probably in `trustCertificate()` line 437-ish

**Comment by drbyte** [comment]
... called from 387

**Comment by drbyte** [comment]
I imagine 437 and 424 probably both need the added quotation-marks.

**Comment by cdavid138** [comment]
Yup!

Perfect we're all sorted, thanks for the help!

I'll tidy this up and submit as a PR later in the week, I don't imagine it would have a detrimental effect on anyone that doesn't have this issue, and would certainly help anyone that does have a space in their path somewhere!

Thanks again for the help, really appreciate it!

**Comment by drbyte** [comment]
Cool. Glad it was relatively painless in the end!

Yes, a PR would be welcome. 

You may already know this, but I'll say it for completeness: Be sure to mention "Closes #862" in the Commit Message or the PR text, so it properly refers to and closes this issue.

**Comment by drbyte** [comment]
Maybe also mention in the PR title something about spaces in volume name. Actually, might be good to also update the title(subject) of this Issue mentioning that too.

**Comment by cdavid138** [comment]
Done thanks! I'll be sure to mention the issue in the PR!
