### ISSUE TITLE
After running valet share the share url is not automatically copied to the clipboard.

### ISSUE THREAD

**Issue by NM338** [laravel/valet#868]
**Valet**: 2.5.4 **Ngrok**: 2.3.3 5 **PHP**: 7.4 **Mac OS**: 10.15.1

Now share works fine, but the share url is not automatically copied to the clipboard. Something is being copied, but it appears as blank on the clipboard. After a while I am able to use **valet fetch-share-url | pbcopy** to copy the url, but I would like if it is copied to the clipboard automatically.

**Comment by drbyte** [comment]
I've seen intermittent situations where the share command wouldn't fetch a URL, and even caused the display output to shift slightly while it invisibly posted an error message.

The only explanation I have is that it seems ngrok is taking too long to fire up and the fetch script doesn't actually receive a URL.  I'm not sure if that delay is an ngrok thing or a PHP thing, or what.

But the following appears to solve it for me, back as far as Valet 2.1 all the way to 2.6 released today:

`~/.composer/vendor/laravel/valet/cli/Valet/Ngrok.php` around line 19:
```diff
    function currentTunnelUrl($domain = null)
    {
+        // wait a second for ngrok to start before attempting to find available tunnels
+        sleep(1);
+
        return retry(20, function () use ($domain) {
```
