### ISSUE TITLE
what is the correct path for custom drivers ~/.config/valet/Drivers or ~/.valet/Drivers ??

### ISSUE THREAD

**Issue by vesper8** [laravel/valet#873]
So everything was working perfectly before I upgraded to php 7.4, since I upgraded and had to uninstall and reinstall all brew services and valet, my custom drivers stopped working

Everything had been in `~/.config/valet` until now, and https://laravel.com/docs/5.8/valet#custom-valet-drivers also mentions that the correct expected folder is `~/.config/valet`

But I read in another issue that the drivers are supposed to be found in `~/.valet` ??

So for the heck of it I symlinked it like this `ln -nfs ./.config/valet .valet`

And now my custom drivers are working again.. but why? Why is there this confusion between `~/.config/valet` and `~/.valet`

Why is Valet looking for the drivers in a different folder than what the official docs point to?

**Comment by drbyte** [comment]
Back in [Sept 2018, with the release of Valet 2.1.0](https://github.com/laravel/valet/releases/tag/v2.1.0) the Valet config directory was moved from the old `~/.valet` to `~/.config/valet`

**Comment by vesper8** [comment]
ok.. so any idea why my newly updated Valet fails to find my custom drivers in that folder and started to work after I symlinked it like I show above.. I'm on `Laravel Valet 2.5.4`

**Comment by vesper8** [comment]
it's very weird.. I swear 30 minutes ago doing `valet which` in a folder where I need a custom driver was saying that it was returning the wrong driver, and after using the symlink it started working. But now I have removed the symlink and somehow it still works.. anyway will close this issue as an unexplained solved mystery

**Comment by drbyte** [comment]
Glad it's sorted, and glad you don't need the symlink!

**Comment by drbyte** [comment]
I dunno if it's of any value or interest to you, but you can git-checkout a Driver into the Drivers folder, and Valet will pick it up. Just follow the naming convention and approach as described in https://github.com/laravel/valet/pull/591 (with the config directory change)
