### ISSUE TITLE
Brew requirement faulty

### ISSUE THREAD

**Issue by nickolasnikolic** [laravel/valet#875]
There is an issue with cli/includes/compatibility.php my system has brew installed however it says that it does not.. exec('which brew') returns /usr/local/bin/brew

**Comment by drbyte** [comment]
If you alter the code to capture what `exec` receives back, what do you get?
If you escalate PHP error logging, does it report any errors?
I'm wondering if something in your PHP environment is imposing some restrictions on the response.
Also, what's your PATH contain?

**Comment by nickolasnikolic** [comment]
hmm you are probably right

PHP message: PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 86016 bytes) in Unknown on line 0" while reading response header from upstream, client: 127.0.0.1, server: word-dance.test, request: "GET /home HTTP/2.0", upstream: "fastcgi://unix:/Users/nn/.config/valet/valet.sock:", host: "word-dance.test"

**Comment by nickolasnikolic** [comment]
$PATH is as follows:

/usr/local/opt/php@7.2/sbin:/usr/local/opt/php@7.2/bin:/usr/local/opt/php@7.2/bin:/usr/local/opt/php@7.2/sbin:/usr/local/opt/php@7.2/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:~/.composer/vendor/bin

**Comment by drbyte** [comment]
Do you have other PHP versions installed besides 7.2 ? Perhaps switching to a different PHP (one way is to use `brew unlink php@7.2` and `brew link php`) may be enough to activate a different set of PHP configs, which would then let you use Valet's built-in functionality to do some cleanups (including possibly a complete uninstall and re-install).
Or you could tinker with your PHP configs manually in `/usr/local/etc/php/`

Aside: looks like you've got duplicates of the 7.2 stuff in your PATH. While that's unlikely to be your current problem, it's worth finding out "why" and fixing it.

**Comment by drbyte** [comment]
Is this your first time using Valet today? Or when did these symptoms start? (Specifically, how does that "when" relate to any other "events"/changes/installed apps/etc you've done with your Mac recently?)

What's the output of the following?

```sh
sw_vers
valet --version
cat ~/.config/valet/config.json
cat ~/.composer/composer.json
ls -al /etc/sudoers.d/
brew config
brew services list
brew list --versions | grep -E 'php(@\d\.\d)?\s|nginx|dnsmasq|mariadb|mysql|mailhog|openssl(@\d\..*)?\s'
php -v
which -a php
nginx -v
curl --version
php --ri curl
~/.composer/vendor/laravel/valet/bin/ngrok version
ls -al ~/.ngrok2
brew info nginx
brew info php
brew info openssl
openssl version -a
openssl ciphers
sudo nginx -t
```

Also, try the following:
```sh
brew services cleanup
brew cleanup
brew doctor
composer global update
```

**Comment by drbyte** [comment]
@nickolasnikolic Is this still an issue?

**Comment by drbyte** [comment]
@mattstauffer I think this can be closed.
