### ISSUE TITLE
Upgraded PHP 7.4 - Error (The process has been signaled with signal 6 / 9.

### ISSUE THREAD

**Issue by bmadigan** [laravel/valet#876]
It doesn't appear that Valet is running at all for me any longer I get:
_**Unable to Connect**_ on Firefox and
**_This site can't be reached_** on Chrome

I upgraded PHP via `brew update` and then ran `brew upgrade php`

Valet on-lastest version: `Yes`
PHP -v: `7.4.0`
Which PHP: `/usr/local/bin/php`

I also ran `composer global upgrade` and `valet install`.

Trying to run Brew Services List and Valet use PHP gives the following:

![image](https://user-images.githubusercontent.com/13608/70669623-e72c1080-1c44-11ea-83db-a2535ffd9e5b.png)

NOTE: I also tried `valet uninstall --force` but I get the error (Screenshot)

![image](https://user-images.githubusercontent.com/13608/70669857-8c46e900-1c45-11ea-98e5-6eda1d9b1384.png)

**Comment by drbyte** [comment]
It's probably good to leave this issue titled with the `The process has been signaled with signal "6"` text, since that appears to be the primary issue. (well, 6 or 9 anyway)

What's the output of:
```sh
composer global outdated
cat ~/.composer/composer.json
echo $PATH
```

I'm wondering specifically here what other dependencies are installed, which could be causing Process to behave unexpectedly (and what older version might be installed, etc).

Also, maybe run the following just to be sure the old PHP is shut down and not restarting on boot:
`brew services php@7.2 stop`

**Comment by drbyte** [comment]
According to various sources (one of which is https://en.wikipedia.org/wiki/Signal_(IPC) )
Signal 6 is Abort, and Signal 9 is Kill

`Symfony/Process` is being used to run commands. 
In your case it seems to be failing when running commands related to installing/removing/configuring PHP.
I wonder what Homebrew is saying behind-the-scenes.

What's the output of the following? I'm curious whether any errors occur, especially with verbose output. 
`brew services stop php -vvv`
and 
`brew services start php -vvv`

Also, for diagnostics, let's also try uninstalling all your PHP versions, since the `valet uninstall --force` will loop through all and attempt to uninstall them, and you're getting the error in that case as well as just with a restart.
```sh
brew uninstall --force php@7.2 -vvv
brew uninstall --force php@7.1 -vvv
brew uninstall --force php -vvv
brew install php -vvv
```

**Comment by bmadigan** [comment]
@drbyte - Great ideas. I'll go through the last comment and I'll update

**Comment by bmadigan** [comment]
I have it working now. There was so much output that it would really be too much to add here. I pretty much did what you suggested ie:

```
brew uninstall --force php@7.2 -vvv
brew uninstall --force php@7.1 -vvv
brew uninstall --force php -vvv
brew install php -vvv
```

But I was still getting the same issue, and by accident actually I typed:
`brew upgrade` (I mean update) and it upgraded a bunch of services. 

I then reran `valet install` for sh*ts and giggles and it is now working 🤷‍♂  

Thank you for your comments. It was a big help.

**Comment by drbyte** [comment]
Woot! Glad it's working.

> I upgraded PHP via `brew update` and then ran `brew upgrade php`

Perhaps in hindsight simply running `brew update` and `brew upgrade` (not limiting it to just `php`) might have been enough.

I usually run `brew update && brew upgrade` on a weekly basis.

**Comment by JackEllis** [comment]
I also ran into this with Laravel Valet where I hit The process has been signaled with signal "6". As per the rules, if it takes you longer than 20 minutes to solve, post about it. I did the following to get it working.

This is a dump of my terminal history. I fixed this yesterday and have no idea what did it, but throw everything at it and you'll get things working.

1. valet uninstall
2. composer global remove laravel/valet
3. brew uninstall --force php nginx dnsmasq
4. composer global require laravel/valet
5. valet install
6. composer global update
7. brew upgrade php
8. brew switch icu4c 64.2
9. valet reinstall
10. brew services php start
11. brew services restart nginx
12. brew unlink php
13. brew cleanup
14. brew link php

**Comment by mbroadley** [comment]
> I have it working now. There was so much output that it would really be too much to add here. I pretty much did what you suggested ie:
> 
> ```
> brew uninstall --force php@7.2 -vvv
> brew uninstall --force php@7.1 -vvv
> brew uninstall --force php -vvv
> brew install php -vvv
> ```
> 
> But I was still getting the same issue, and by accident actually I typed:
> `brew upgrade` (I mean update) and it upgraded a bunch of services.
> 
> I then reran `valet install` for sh*ts and giggles and it is now working 🤷‍♂
> 
> Thank you for your comments. It was a big help.

Was experiencing the same issue and read this thread, tried a few things that didn't work.

The "brew upgrade" and "valet install" fixed it all for me too  :)

**Comment by acirinelli** [comment]
> The "brew upgrade" and "valet install" fixed it all for me too :)

Same. Nothing else worked.

**Comment by richartkeil** [comment]
For me the fix was the specific upgrade from nginx 1.15.9 to 1.17.8 by `brew upgrade nginx`. Works like a charm now.

**Comment by warksit** [comment]
> For me the fix was the specific upgrade from nginx 1.15.9 to 1.17.8 by `brew upgrade nginx`. Works like a charm now.

Brew listed nginx as version 1.17.8 but uninstalling it and reinstalling nginx is what fixed it for me. Thanks for the pointer @richartkeil

**Comment by foxnorth** [comment]
Got this error. 
I was trying to fetch data from DB before I applied migrations to create a table for that model.
I was trying to fetch it inside a route (it was a lesson).
```php
Route::get('/projects', function() {
    $projects = App\Project::all();
    return view('projects.index', compact('projects'));
});
```
And "Signal 9" was uninformative.

**Comment by seivad** [comment]
I ran the following to successfully resolve Signal 6 issue:

```
composer global update
brew update && brew upgrade 
valet restart
```

During that restart, I got the firewall allow prompt in OSX, hit allow and valet restarted successfully. Sites loading now. Weird bug.

**Comment by turanzamanli** [comment]
I tried all the comments. But it just fuckup.

Finally, I add comment to /Users/username/.composer/vendor/symfony/Process.php 428. line

**Comment by jesseleite** [comment]
`brew upgrade nginx` fixed it for me as well

**Comment by HPWebdeveloper** [comment]
This is my solution:

https://medium.com/@panjeh/valet-this-site-cant-be-reached-err-connection-refused-ad424ea1e343

In one line : brew upgrade nginx

**Comment by zamson** [comment]
`brew upgrade nginx` followed by `valet install` worked for me

**Comment by shayanazali** [comment]
I got signal 6 error when I upgraded to php 7.3 but when I tried to backup my database I get the following error:

`dyld: Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib`

so i switched the version of openssl by running:
`brew switch openssl 1.0.2q`

and then my mysql started to work correctly, then I try `valet install` again and things started to work again

**Comment by usamamuneerchaudhary** [comment]
> For me the fix was the specific upgrade from nginx 1.15.9 to 1.17.8 by `brew upgrade nginx`. Works like a charm now.

this worked for me !

**Comment by anasred** [comment]
I did 
```brew cleanup```

then I got this:
```
Error: Could not remove php@7.3 keg! Do so manually:
  sudo rm -rf /usr/local/Cellar/php@7.3/7.3.13
```

then I did:
```sudo rm -rf /usr/local/Cellar/php@7.3/7.3.13```

then I did:
```php -v```
So I got this:
```PHP 7.3.11 (cli) (built: Jul  5 2020 03:23:39) ( NTS )```

so finally I did:
```valet use php@7.3```

And voila! Valet back to business again 😎🙌
Thanks guys for sharing

**Comment by im-sunil** [comment]
> For me the fix was the specific upgrade from nginx 1.15.9 to 1.17.8 by `brew upgrade nginx`. Works like a charm now.

How you know? but its work awesome!

**Comment by sakinobashi** [comment]
I was having a similar issue; my project was being served correctly most of the time, but on certain requests I was getting a "The process has been signaled with signal 9" Symphony error rather than the regular Ignition error pages.

The following commands:

````
composer global update
brew update && brew upgrade 
valet install
````

… worked for me as well, so everyone's comments were much appreciated!

**Comment by im-sunil** [comment]
> I was having a similar issue; my project was being served correctly most of the time, but on certain requests I was getting a "The process has been signaled with signal 9" Symphony error rather than the regular Ignition error pages.
> 
> The following commands:
> 
> ```
> composer global update
> brew update && brew upgrade 
> valet install
> ```
> 
> … worked for me as well, so everyone's comments were much appreciated!

brew upgrade nginx 
Worked for me

**Comment by SidneyMachara** [comment]
```brew upgrade nginx```

it might tell you :
Error: Could not remove nginx keg! Do so manually:
  sudo rm -rf /usr/local/Cellar/nginx/1.15.8

so do --> ``` sudo rm -rf /usr/local/Cellar/nginx/1.15.8```

```brew update && brew upgrade ```

it might tell you :
Error: Could not remove dnsmasq keg! Do so manually:
  sudo rm -rf /usr/local/Cellar/dnsmasq/2.80

do go ahead and do --> ```sudo rm -rf /usr/local/Cellar/dnsmasq/2.80```

```valet restart```
