### ISSUE TITLE
Valet no longer accepting external connections

### ISSUE THREAD

**Issue by molovo** [laravel/valet#877]
In my office we currently use a development domain, which resolves a subdomain for each developer to their local IP address, so that we can access sites when on our office network. For years, I and others in the office have been using this subdomain as our valet TLD, and sites on my machine have been accessible by my team members from their machines.

Since upgrading valet to 2.7.0 from 2.5.4 and running `valet install`, sites still load correctly on the mac they are hosted on, but are no longer accessible externally. Downgrading valet to 2.5.4 or 2.5.3 does not restore things to the way they were - even with a full uninstall and reinstall of valet.

I've played around with various dnsmasq configurations, but found no luck getting sites to load.

Running `dig +short +time=2 @site.james.example.com TXT CHAOS version.bind` does correctly return `dnsmasq-2.80`, both from my machine and externally, so the DNS routing does seem to be correct, but it doesn't seem to be accepting connections. With dnsmasq logging turned on, internal connections are triggering queries within dnsmasq, but external connections are not.

I'll continue to debug, but any recommendations would be much appreciated. Please let me know if there are any particular log files which you'd like me to provide as well.

**Comment by molovo** [comment]
It looks as thought port 53 is no longer open for external connections.

```
❯ nmap -p 53 127.0.0.1 -Pn
Starting Nmap 7.80 ( https://nmap.org ) at 2019-12-13 10:18 GMT
Nmap scan report for localhost (127.0.0.1)
Host is up (0.00017s latency).

PORT   STATE SERVICE
53/tcp open  domain

Nmap done: 1 IP address (1 host up) scanned in 0.07 seconds

❯ nmap -p 53 192.168.1.52 -Pn
Starting Nmap 7.80 ( https://nmap.org ) at 2019-12-13 10:18 GMT
Nmap scan report for 192.168.1.52
Host is up (0.00013s latency).

PORT   STATE  SERVICE
53/tcp closed domain

Nmap done: 1 IP address (1 host up) scanned in 0.22 seconds
```

**Comment by molovo** [comment]
I've tracked it down - the issue seems to be caused by fcd73d73

**Comment by molovo** [comment]
I've got around this temporarily by using a composer patch to remove the IP address within the `listen` directive. Perhaps it would be better to put this behind a configuration setting, so the user can decide whether or not to allow external connections.

**Comment by drbyte** [comment]
Quick patches:
a - `/usr/local/etc/nginx/valet/valet.conf` - you can update the `listen` directive here for non-secured sites that Valet serves.
b - `~/.composer/vendor/laravel/valet/cli/stubs/secure.valet.conf` is used to generate the secured site configs. Update this and then run `valet tld test` to rebuild the secured sites with the update.

> Perhaps it would be better to put this behind a configuration setting, so the user can decide whether or not to allow external connections.

Maybe. Only 2 other people have reported it being a problem for them. 

But instead of adding new configuration settings, I've been considering what I think may be an even more effective improvement: to give more direct control over stubs so people can customize those stubs for their environment/needs. The problem is version-controlling them so people get important updates if the master stubs are ever updated.

**Comment by molovo** [comment]
@drbyte that's exactly what I've done. The full patching process

```
mkdir -p ~/.composer/patches
composer global require "cweagans/composer-patches:~1.0"
```

Save [this gist](https://gist.github.com/molovo/d7b7bcde96491ed6d46658fee7cbefbd) as `~/.composer/patches/valet-listen-address.patch`

Add the following to `~/.composer/composer.json`
```
"extra": {
  "patches": {
    "laravel/valet": {
      "Allow external connections": "patches/valet-listen-address.patch"
    }
  }
}
```

Then install
```
composer global install
valet install
```

This will also satisfy your second point - since patches are always applied by composer after the current version is installed, any updates to the repository will be present before the patch is applied.

I do a similiar thing with [this patch](https://gist.github.com/molovo/247be3c51deded747ac6017f999b8c0c) to update the default PHP memory limit for development

**Comment by drbyte** [comment]
Ya, this is an easy workaround for anyone who needs to expose their machine to the entire network.

**Comment by drbyte** [comment]
@mattstauffer Documentation has been added to explain how to open up ports for local network sharing needs:
https://laravel.com/docs/valet#sharing-sites

Thus I believe this issue can be closed.

**Comment by mattstauffer** [comment]
@drbyte Beautiful!
