### ISSUE TITLE
valet park stopped working

### ISSUE THREAD

**Issue by rebecatl** [laravel/valet#886]
I created a new laravel project on my code folder in the terminal and I used the valet park on that folder. 
The '.test' website was loading perfectly but after changing a little bit the views, I went back and it stopped loading any of the projects I have on that folder. It only opens if I create a new one but not the ones that were already there.
On the terminal, I don't get any errors running the command but on the website, I get a 404 not found error

**Comment by drbyte** [comment]
Valet throws a 404 Not Found if the domain name cannot be found in a parked or linked folder. 

`valet links` will show a list of linked sites
`valet parked` will show a list of sites that "could" be served by Valet based on the folders you've marked as parked.

A reboot solves a myriad of strange problems.

What's the output of the following?
```sh
sw_vers
valet --version
cat ~/.config/valet/config.json
cat ~/.composer/composer.json
ls -al /etc/sudoers.d/
brew config
brew services list
brew list --versions | grep -E 'php(@\d\.\d)?\s|nginx|dnsmasq|mariadb|mysql|mailhog|openssl(@\d\..*)?\s'
php -v
which -a php
nginx -v
~/.composer/vendor/laravel/valet/bin/ngrok version
sudo nginx -t
```

Also, try the following:
```sh
composer global diagnose
composer global update
brew doctor
```

**Comment by rebecatl** [comment]
<img width="1073" alt="Screenshot 2019-12-27 at 12 59 04" src="https://user-images.githubusercontent.com/58027048/71516780-24caa380-28ab-11ea-8f7b-507fbbde44ae.png">

**Comment by rebecatl** [comment]
When I run valet links it doesn't show any sites, but if I run the command valet park it tells me the folder has been added to Valet's paths.

This is the output of what you provided.
1. sw_vers 
```ProductName: Mac OS X
ProductVersion: 10.14.6
BuildVersion: 18G2022
```
2. valet --version
`Laravel Valet 2.7.1`
3. cat ~/.config/valet/config.json
```{
    "tld": "test",
    "paths": [
        "/Users/rebetejedor/code",
        "/Users/rebetejedor",
        "/Users/rebetejedor/code/laravel6",
        "/Users/rebetejedor/code/laravel7"
    ]
}
```
4. cat ~/.composer/composer.json
```{
    "tld": "test",
    "paths": [
        "/Users/rebetejedor/code",
        "/Users/rebetejedor",
        "/Users/rebetejedor/code/laravel6",
        "/Users/rebetejedor/code/laravel7"
    ]
}
(base) MacBook-Pro-de-Eva:code rebetejedor$ cat ~/.composer/composer.json
{
    "require": {
        "laravel/installer": "^2.3",
        "laravel/valet": "^2.7"
    }
}
```
5. ls -al /etc/sudoers.d/
```total 0
drwxr-xr-x    2 root  wheel    64 Aug 18  2018 .
drwxr-xr-x  141 root  wheel  4512 Dec 25 12:46 ..
```
6.brew config
```HOMEBREW_VERSION: 2.2.2
ORIGIN: https://github.com/Homebrew/brew
HEAD: 13f508d0dc8ada1726ee09a750285d7447ac3df4
Last commit: 4 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 32d7795859f1c34cfd096fced651b55a5fda5e72
Core tap last commit: 20 hours ago
HOMEBREW_PREFIX: /usr/local
CPU: octa-core 64-bit skylake
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/bin/ruby
Clang: 10.0 build 1001
Git: 2.23.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 11.0.1, 1.8.0_191, 1.8.0_181, 1.6.0_65-b14-468
macOS: 10.14.6-x86_64
CLT: 10.3.0.0.1.1562985497
Xcode: 10.2.1
XQuartz: 2.7.11 => /opt/X11
```
7. brew services list
```dnsmasq started root        /Library/LaunchDaemons/homebrew.mxcl.dnsmasq.plist
mysql   started rebetejedor /Users/rebetejedor/Library/LaunchAgents/homebrew.mxcl.mysql.plist
nginx   started root        /Library/LaunchDaemons/homebrew.mxcl.nginx.plist
php     started root        /Library/LaunchDaemons/homebrew.mxcl.php.plist
```
8. brew list --versions | grep -E 'php(@\d\.\d)\s|nginx|dnsmasq|mariadb|mysql|mailhog|openssl(@\d\..*)?\s'
```curl-openssl 7.67.0
dnsmasq 2.80
mysql 8.0.18_1
nginx 1.17.3_1
openssl@1.1 1.1.1d
php 7.3.12
```
9. php -v
``Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.12, Copyright (c) 1998-2018 Zend Technologies
with Zend OPcache v7.3.12, Copyright (c) 1999-2018, by Zend `Technologies``

10. which -a php
``/usr/local/bin/php``
   ``/usr/bin/php
``

11.nginx -v
`nginx version: nginx/1.17.3`
12. ~/.composer/vendor/laravel/valet/bin/ngrok version
`ngrok version 2.3.35`

13. sudo nginx -t
``nginx: the configuration file /usr/local/etc/nginx/nginx.conf syntax is ok``
``nginx: configuration file /usr/local/etc/nginx/nginx.conf test is successful``

**Comment by drbyte** [comment]
> cat ~/.config/valet/config.json
> ```
>     "tld": "test",
>     "paths": [
>         "/Users/rebetejedor/code",
>         "/Users/rebetejedor",
>         "/Users/rebetejedor/code/laravel6",
>         "/Users/rebetejedor/code/laravel7"
>     ]
> }
> ```

I'd recommend shortening the `paths` there by removing the last 3 and just keeping the first (the one ending in `/code`). You could do that by editing the json file directly (remember to set commas and quotes correctly), or cd into each of those last 3 folders and run `valet unpark`.

TIP: You don't need to `park` every directory you create a new site in. The `valet park` command specifies a "root" location for finding your projects.  When you run `valet park` inside your `~/code` folder, that tells Valet to serve EVERY project located inside the `~/code` folder. eg: `http://foo.test` would look in `~/code/foo` and serve that domain from there. You would NOT need to `park` the `foo` folder, because it is an immediate child of the `~/code` folder.

**Comment by drbyte** [comment]
@rebecatl Is this still an issue?

**Comment by drbyte** [comment]
@mattstauffer Given no response, this can probably be closed.
