### ISSUE TITLE
Create and Expose a Site Specific Nginx conf.

### ISSUE THREAD

**Issue by kerns** [laravel/valet#897]
Less of an issue and more of a feature request – it would be very nice if every new Valet site had the option for a <site name>.nginx.conf file, for testing a quick tweak or customization. It could be made available with something like a link-conf command.

I know Valet is not designed for server tuning or hardcore customization, but sometimes a project (e.g. testing out a new CMS) can call for a simple rewrite or error handling directive, ...and it would be so useful to be able to quickly edit a file like this, restart the service and keep moving.

I feel like I've seen others request this feature in the past.

**Comment by drbyte** [comment]
Yes - You can do this immediately already:

The Nginx configs for individual Valet sites are found in:  `~/.config/valet/Nginx`
You can simply edit the config for the site in question, and then run `valet restart nginx` to have it take effect.

One thing to note: Valet doesn't generate a site-specific config unless you first run `valet secure` for that site. So do that first, and everything else is then straightforward.

Simple workflow:
```sh
# Make a Sites directory and tell Valet to use it
mkdir ~/Sites
cd ~/Sites
valet park

# Make a new Laravel app (or some other project)
laravel new foo

# enable HTTPS on the project folder, so that Nginx configs are created for it
cd foo
valet secure

# now you can see the site configs, for editing:
ls ~/.config/valet/Nginx/foo.*
# edit as required
```

**Comment by kerns** [comment]
@drbyte Perfect. Thank you!
