### ISSUE TITLE
[Proposition] Use Docker instead of Homebrew

### ISSUE THREAD

**Issue by cwilby** [laravel/valet#900]
[Laradock](https://github.com/laradock/laradock) provides a solution for running a Laravel application and services in Docker that has been iterating for a few years, but recently I feel has become overloaded with packages that just aren't needed for the beginnings of a project.

Docker is great for local development as it can be "reset to neutral", which is exactly what Valet seeks to provide.  

I propose either refactoring Valet to use Docker, creating a new solution seperate from Valet, or ignoring the whole thing and continue trimming down Laradock for new projects.

An immediate benefit of using Docker would be support for almost any OS that can run Docker.

Some thoughts:

* Should run dnsmasq in a Docker container to avoid `/etc/hosts`. Valet manages a singleton service among multiple projects.
* Should use [`mkcert`](https://github.com/FiloSottile/mkcert) to create locally trusted development certificates.
* Should replace Caddy with Traefik for proxying traffic to individual Laravel projects.
* Should create an nginx container to pass requests to Laravel.
* Should proxy valet commands to docker containers (e.g. `valet link` creates traefik config)
* Should include a workspace container for artisan commands.  Developers run `valet exec` to run `php artisan` commands, similar to `homestead ssh`.
* Should start Docker containers for MariaDB and other containers.
* Should still support public sharing - not sure how to do this, would imagine a container with ngrok or similar proxying traffic to Laravel nginx container.
* Should support viewing logs - `valet logs` can run `docker logs`.

Where this all starts to fall down though is custom Valet drivers.

**Comment by njbair** [comment]
This seems more like an issue for Laradock to address. We all love Docker but this proposal seems to directly contradict Valet's whole selling point. From the Valet docs:

> ...a blazing fast Laravel development environment that uses roughly 7 MB of RAM.

> ...provides a great alternative [to Vagrant or Homestead] if you want flexible basics, prefer extreme speed, or are working on a machine with a limited amount of RAM.

As someone who lives in Docker dev environments on my desktop PC, the idea of trying to do all that on my MacBook Air just sounds like a nightmare.

**Comment by mattstauffer** [comment]
I agree with @njbair -- it's too distant from the original goals of Valet. However, I'd also encourage anyone interested in Docker to check out Vessel, which I believe is a lot lighter and simpler than Laradock:

https://vessel.shippingdocker.com/

I think Vessel and Laradock together are the reasons why no official Docker-based alternative to Valet has been proposed.

Thanks for the ideas and conversation y'all :)

**Comment by cwilby** [comment]
Additionally, after some research I realize it was a big presumption to [assume everybody on a team wants to use Docker](https://blog.testdouble.com/posts/2020-02-11-the-slippery-slope-of-docker-dev-environments/).

Thanks for the insight!
