### ISSUE TITLE
valet install success ,link success,but open url error

### ISSUE THREAD

**Issue by bestvayne** [laravel/valet#905]
- Laravel Valet 2.8.1 
- php 7.2
- Laravel 6.2
- Nginx 1.17.8

valet install -> ok
valet link project  -> ok
but when I valet link project, open URL in the browser, it shows 
"Unable to access this site"
"Server IP address for courseware-store-back-end.test not found“
” DNS_PROBE_FINISHED_NXDOMAIN“

all over it ok, but can't open URL

**Comment by drbyte** [comment]
According to google search the `DNS_PROBE_FINISHED_NXDOMAIN` message indicates that the DNS service is reporting a non-existent domain.

I guess I would investigate further by checking:
- is dnsmasq running?
- is 127.0.0.1 in your Mac's Network DNS settings as the first DNS provider?
- does a shorter domain name like `foo.test` work correctly, vs the very long on you posted?
- is the problem limited to just "linked" sites?
- does the problem resolve itself after a reboot?

There are many more questions, but answers to those would help give greater context.

**Comment by bestvayne** [comment]
@drbyte thx your answer.
I try to change used" valet tld test ", then valet can be run. but when I used " valet tld vance/vayne/ any name ", the valet can't access URL.

before, I will use vayne or any name as the domain name that is ok, but yesterday it does not work.

**Comment by Summonshr** [comment]
run valet secure

**Comment by adarmawan117** [comment]
I Tried "valet restart".
It's work, like a charm
