### ISSUE TITLE
Cannot run valet after switching to use 7.0 (tightenco/collect reqs 7.1+)

### ISSUE THREAD

**Issue by chasegiunta** [laravel/valet#907]
After switching down to use 7.0 for a project, I'm no longer able to run `valet`.

Trying `composer global upgrade` didn't do anything unfortunately.

I know Collect is 7.1+ only, so maybe this is a `won't fix`, but just incase it's not... Did I miss a vital step here upon downgrading to 7.0? I, of course, couldn't run `valet install` right after downgrading.

```
PHP Warning:  Class 'Tightenco\Collect\Support\LazyCollection' not found in /Users/chasegiunta/.composer/vendor/tightenco/collect/src/Collect/Support/alias.php on line 19

Warning: Class 'Tightenco\Collect\Support\LazyCollection' not found in /Users/chasegiunta/.composer/vendor/tightenco/collect/src/Collect/Support/alias.php on line 19
PHP Parse error:  syntax error, unexpected '=' in /Users/chasegiunta/.composer/vendor/tightenco/collect/src/Collect/Support/LazyCollection.php on line 611

Parse error: syntax error, unexpected '=' in /Users/chasegiunta/.composer/vendor/tightenco/collect/src/Collect/Support/LazyCollection.php on line 611
```

**Comment by chasegiunta** [comment]
Sorry, this may be a CLI issue. I forget that the CLI could be running a different PHP version than what your projects are serving.

If that sounds like the case, someone smarter than I, please close the issue 😅

**Comment by drbyte** [comment]
Correct: the PHP CLI (configured by filesystem paths) can operate differently from PHP-FPM (configured by config files).

Aside: I've found that any app that can run on PHP 7.0 runs fine on 7.1, so I never worry about using 7.0 anymore. Or, at least as far as my projects have required anyway.

As the author of the issue, you can click the Close button below to close this.

**Comment by chasegiunta** [comment]
@drbyte Thanks for the clarification!
