### ISSUE TITLE
Valet secure not working

### ISSUE THREAD

**Issue by ngstwr** [laravel/valet#909]
> valet restart
Restarting dnsmasq...
Restarting php...

In Nginx.php line 121:

  Nginx cannot start; please check your nginx.conf [1: nginx: [emerg] cannot load certificate "/Users/nagesh/.config/valet/Certificates/store.as.crt": BIO_new_file() failed (S
  SL: error:02001002:system library:fopen:No such file or directory:fopen('/Users/nagesh/.config/valet/Certificates/store.as.crt','r') error:2006D080:BIO routines:BIO_new_file
  :no such file)
  nginx: configuration file /usr/local/etc/nginx/nginx.conf test failed
  ].

FYI - .as is my valet tld!

Running -

macOS Mojave
PHP 7.4.1
OpenSSL 1.1.0c
Dnsmasq version 2.80
nginx/1.17.8

Already tried uninstalling everything and installing again.

There are only two files inside /Users/nagesh/.config/valet/Certificates -
store.as.conf and store.as.key.

**Comment by drbyte** [comment]
> There are only two files inside /Users/nagesh/.config/valet/Certificates -
> store.as.conf and store.as.key.

Evidently it's not able to create the necessary CSR, and therefore not the CRT.
I suspect it's a permissions issue or an openssl incompatibility on your computer.

I'm guessing at this, but perhaps making the following change may expose some details:

Edit `~/.composer/laravel/valet/Valet/Sites.php` and make the following changes, around line 373:

```diff
        $result = $this->cli->runAsUser(sprintf(
            'openssl x509 -req -sha256 -days 730 -CA "%s" -CAkey "%s" %s -in "%s" -out "%s" -extensions v3_req -extfile "%s"',
            $caPemPath, $caKeyPath, $caSrlParam, $csrPath, $crtPath, $confPath
        ));
+  echo $result;

        // If cert could not be created using runAsUser(), use run().
        if (strpos($result, 'Permission denied')) {
-            $this->cli->run(sprintf(
+            $result = $this->cli->run(sprintf(
                'openssl x509 -req -sha256 -days 730 -CA "%s" -CAkey "%s" %s -in "%s" -out "%s" -extensions v3_req -extfile "%s"',
                $caPemPath, $caKeyPath, $caSrlParam, $csrPath, $crtPath, $confPath
            ));
+        echo '(2)-'.$result;
        }

        $this->trustCertificate($crtPath);
```

and also around line 407:
```diff
    function createSigningRequest($url, $keyPath, $csrPath, $confPath)
    {
-        $this->cli->runAsUser(sprintf(
+        $result = $this->cli->runAsUser(sprintf(
            'openssl req -new -key "%s" -out "%s" -subj "/C=/ST=/O=/localityName=/commonName=%s/organizationalUnitName=/emailAddress=%s%s/" -config "%s"',
            $keyPath, $csrPath, $url, $url, '@laravel.valet', $confPath
        ));
+        echo $result;
    }
```

And then re-run `valet secure` on your `store` project directory. 

If it runs properly it will output something like:
```text
No value provided for Subject Attribute C, skipped
No value provided for Subject Attribute ST, skipped
No value provided for Subject Attribute O, skipped
No value provided for Subject Attribute localityName, skipped
No value provided for Subject Attribute organizationalUnitName, skipped
Signature ok
subject=/CN=store.as/emailAddress=store.as@laravel.valet
Getting CA Private Key
Restarting nginx...
The [store.as] site has been secured with a fresh TLS certificate.
```

**Comment by ngstwr** [comment]
After doing what you suggested, I got this:

```
(3)-problems making Certificate Request
4534797760:error:0D07A098:asn1 encoding routines:ASN1_mbstring_ncopy:string too short:crypto/asn1/a_mbstr.c:102:minsize=2
(1)-x509: Cannot open input file /Users/nagesh/.config/valet/CA/LaravelValetCASelfSigned.pem, No such file or directory
x509: Use -help for summary.

In Nginx.php line 121:

  Nginx cannot start; please check your nginx.conf [1: nginx: [emerg] cannot load certificate "/Users/nagesh/.config/valet/Certificates/familiar.as.crt": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or d
  irectory:fopen('/Users/nagesh/.config/valet/Certificates/familiar.as.crt','r') error:2006D080:BIO routines:BIO_new_file:no such file)
  nginx: configuration file /usr/local/etc/nginx/nginx.conf test failed
  ].


secure [<domain>]
```

**Comment by drbyte** [comment]
> (3)-problems making Certificate Request
4534797760:error:0D07A098:asn1 encoding routines:ASN1_mbstring_ncopy:string too short:crypto/asn1/a_mbstr.c:102:minsize=2

I suspect the problem has something to do with your default locale, or with copying the stubs that Valet depends on.

I recommend that you trace through each of the results of the function calls in this section of the code (364, 365, 366, 374, etc):
https://github.com/laravel/valet/blob/d6558b90a5529f03752627798047f3a9e0543ab8/cli/Valet/Site.php#L364-L384

And also dump out the openssl command it generates, and run it manually, seeking which parameter is the one that's deemed as "too short". It could be that something in your system is requiring different default lengths instead of the values that Valet is using that works for everyone else.

**Comment by drbyte** [comment]
@ngstwr if this is resolved for you, can you please click Close below?

**Comment by ngstwr** [comment]
No it isn't resolved yet, but that's because I haven't had the time to do what you asked. I will surely do it later, I will reopen this issue then! Thanks for your help!

**Comment by ngstwr** [comment]
I need secure to work now, so I reopened this and did what you asked! I echoed everything since secure command is called. But haven't been able to figure out the issue or the solution.

`Nageshs-MacBookPro:hrm nagesh$ valet secure

 Log - Secure Called
 Log - Unsecure calling
 Log - Unsecure done

 Log - caPath
 /Users/nagesh/.config/valet/CA
 Log - user
 nagesh
 Log - ensureDirExists calling for caPath
 Log - ensureDirExists done

 Log - certificatesPath
 /Users/nagesh/.config/valet/Certificates
 Log - ensureDirExists calling for certificatesPath

 Log - ensureDirExists done

 Log - createCa calling

 Log - createCa done

 Log - createCertificate calling

 Log - createCertificate called
 Log - inside createCertificate method
 Log - caPemPath
 /Users/nagesh/.config/valet/CA/LaravelValetCASelfSigned.pem
 Log - caKeyPath
 /Users/nagesh/.config/valet/CA/LaravelValetCASelfSigned.key
 Log - caSrlPath
 /Users/nagesh/.config/valet/CA/LaravelValetCASelfSigned.srl
 Log - keyPath
 /Users/nagesh/.config/valet/Certificates/hrm.as.key
 Log - csrPath
 /Users/nagesh/.config/valet/Certificates/hrm.as.csr
 Log - crtPath
 /Users/nagesh/.config/valet/Certificates/hrm.as.crt
 Log - confPath
 /Users/nagesh/.config/valet/Certificates/hrm.as.conf

 Log - buildCertificateConf calling

 Log - buildCertificateConf done

 Log - createPrivateKey calling

 Log - createPrivateKey done

 Log - createSigningRequest calling

 createSigningRequest called

 inside createSigningRequest method

 Log - command
 openssl req -new -key "/Users/nagesh/.config/valet/Certificates/hrm.as.key" -out "/Users/nagesh/.config/valet/Certificates/hrm.as.csr" -subj "/C=/ST=/O=/localityName=/commonName=hrm.as/organizationalUnitName=/emailAddress=hrm.as@laravel.valet/" -config "/Users/nagesh/.config/valet/Certificates/hrm.as.conf"
 
Log - command result
 problems making Certificate Request
4722185664:error:0D07A098:asn1 encoding routines:ASN1_mbstring_ncopy:string too short:crypto/asn1/a_mbstr.c:102:minsize=2

 Log - createSigningRequest done

 Log - caSrlParam
 -CAserial "/Users/nagesh/.config/valet/CA/LaravelValetCASelfSigned.srl"
 Log - caSrlParam file exists
 -CAserial "/Users/nagesh/.config/valet/CA/LaravelValetCASelfSigned.srl" -CAcreateserial
 Log - command
 openssl x509 -req -sha256 -days 730 -CA "/Users/nagesh/.config/valet/CA/LaravelValetCASelfSigned.pem" -CAkey "/Users/nagesh/.config/valet/CA/LaravelValetCASelfSigned.key" -CAserial "/Users/nagesh/.config/valet/CA/LaravelValetCASelfSigned.srl" -CAcreateserial -in "/Users/nagesh/.config/valet/Certificates/hrm.as.csr" -out "/Users/nagesh/.config/valet/Certificates/hrm.as.crt" -extensions v3_req -extfile "/Users/nagesh/.config/valet/Certificates/hrm.as.conf"
 Log - command result
 x509: Cannot open input file /Users/nagesh/.config/valet/CA/LaravelValetCASelfSigned.pem, No such file or directory
x509: Use -help for summary.

 Log - createCertificate done

In Nginx.php line 121:

  Nginx cannot start; please check your nginx.conf [1: nginx: [emerg] cannot load certificate "/Users/nagesh/.config/valet/Certificates/hrm.as.crt": BIO_new_file() failed (SSL
  : error:02001002:system library:fopen:No such file or directory:fopen('/Users/nagesh/.config/valet/Certificates/hrm.as.crt','r') error:2006D080:BIO routines:BIO_new_file:no
  such file)
  nginx: configuration file /usr/local/etc/nginx/nginx.conf test failed
  ].


secure [<domain>]
`

**Comment by ngstwr** [comment]
Got it working by adding country, state, organization and org unit name flat in subject digest in both openssl command on site.php. Thanks for your help!

**Comment by wdavis** [comment]
I recently encountered this issue of not being able to secure any of my valet sites and it was due to the wrong `openssl` version being found in my path.

This command can help reveal that:

```
which -a openssl
```

Mine returned:
```
~ ❱ which -a openssl
/Users/Shared/DBngin/postgresql/13.3/bin/openssl
/usr/bin/openssl
```

I was using DBngin's postgres binaries for the cli -- side affect was that it also had openssl installed.

For some reason, I had prepended (instead of appending) `/Users/Shared/DBngin/postgresql/13.3/bin/openssl` to my path, so it was searching there first and causing it to use the wrong `openssl` version.

To fix, just reprioritize the paths in your `PATH`. Then you should get something like this:

```
~ ❱ which -a openssl
/usr/bin/openssl
/Users/Shared/DBngin/postgresql/13.3/bin/openssl
```
