### ISSUE TITLE
certain domain name exceptions

### ISSUE THREAD

**Issue by VinceG** [laravel/valet#910]
I am using Valet with .app as the TLD, is there a way to ignore certain domains so they'll resolve to the appropriate outside DNS?

For example mailcoach.app does not work since Valet takes over.

Thank You.

**Comment by drbyte** [comment]
If you're using latest Valet, you can add a special dnsmasq config file that will give you this sort of control.

From your post it looks like you've already run `valet tld app` to serve *.app locally.

Next, create the following file, and then run `valet restart dnsmasq`:
`~/.config/valet/dnsmasq.d/passthru-domains.conf`
```text
# This configuration can be used to allow fallback DNS lookups to public servers
# This is particularly useful if you don't specify fallback servers in MacOS config

# Uncomment to set the public fallback servers to Cloudflare:
#server=1.1.1.1
#server=1.0.0.1


#### Special overrides per-domain which should fallback to public if not found locally
## syntax:  server=/domain.tld/#  (where the /# is what means to use public fallback)
server=/mailcoach.app/#
```

**Comment by VinceG** [comment]
@drbyte Thank You. That worked perfectly.

**Comment by maximepvrt** [comment]
I had to create the file here : `/usr/local/etc/dnsmasq.d/passthru-domains.conf`
