### ISSUE TITLE
Valet share with configuration per site

### ISSUE THREAD

**Issue by stephan-v** [laravel/valet#912]
Hello,

Is there a way to simple run `valet share` with preconfigured arguments?

I am using a project with a reserved domain and a default region.

Preferably I would just run `valet share` instead of always using `valet share --region=eu -subdomain=myproject`

The ideal scenario would be to have like a `.valet` config file where all arguments could simply be passed into.

**Comment by drbyte** [comment]
@stephan-v this appears to be similar to #557 
... in which case, no it's not a feature yet
... but is welcome
