### ISSUE TITLE
/usr/local/etc/nginx/nginx.conf:9

### ISSUE THREAD

**Issue by idmahbub** [laravel/valet#921]
i have reinstall valet, but stuck on this step, any one help me?
i just trty for, reinstall ngix but still my error 
`Nginx cannot start; please check your nginx.conf [1: nginx: [emerg] open() "/usr/local/etc/nginx/mime.types" failed (2  
  : No such file or directory) in /usr/local/etc/nginx/nginx.conf:9                                                       
  nginx: configuration file /usr/local/etc/nginx/nginx.conf test failed                                                   
  ]. `

`nginx version: nginx/1.17.9
built by clang 11.0.0 (clang-1100.0.33.17)
built with OpenSSL 1.1.1d  10 Sep 2019
TLS SNI support enabled
configure arguments: --prefix=/usr/local/Cellar/nginx/1.17.9 --sbin-path=/usr/local/Cellar/nginx/1.17.9/bin/nginx --with-cc-opt='-I/usr/local/opt/pcre/include -I/usr/local/opt/openssl@1.1/include' --with-ld-opt='-L/usr/local/opt/pcre/lib -L/usr/local/opt/openssl@1.1/lib' --conf-path=/usr/local/etc/nginx/nginx.conf --pid-path=/usr/local/var/run/nginx.pid --lock-path=/usr/local/var/run/nginx.lock --http-client-body-temp-path=/usr/local/var/run/nginx/client_body_temp --http-proxy-temp-path=/usr/local/var/run/nginx/proxy_temp --http-fastcgi-temp-path=/usr/local/var/run/nginx/fastcgi_temp --http-uwsgi-temp-path=/usr/local/var/run/nginx/uwsgi_temp --http-scgi-temp-path=/usr/local/var/run/nginx/scgi_temp --http-log-path=/usr/local/var/log/nginx/access.log --error-log-path=/usr/local/var/log/nginx/error.log --with-compat --with-debug --with-http_addition_module --with-http_auth_request_module --with-http_dav_module --with-http_degradation_module --with-http_flv_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_mp4_module --with-http_random_index_module --with-http_realip_module --with-http_secure_link_module --with-http_slice_module --with-http_ssl_module --with-http_stub_status_module --with-http_sub_module --with-http_v2_module --with-ipv6 --with-mail --with-mail_ssl_module --with-pcre --with-pcre-jit --with-stream --with-stream_realip_module --with-stream_ssl_module --with-stream_ssl_preread_module`

`valet -V
Laravel Valet 2.8.1`

`nginx -s reload 
nginx: [alert] could not open error log file: open() "/usr/local/var/log/nginx/error.log" failed (13: Permission denied)
2020/03/11 11:39:31 [warn] 76687#0: the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /usr/local/etc/nginx/nginx.conf:1
2020/03/11 11:39:31 [emerg] 76687#0: open() "/usr/local/etc/nginx/mime.types" failed (2: No such file or directory) in /usr/local/etc/nginx/nginx.conf:9`

`brew install nginx          
==> Downloading https://homebrew.bintray.com/bottles/nginx-1.17.9.catalina.bottle.tar.gz
Already downloaded: /Users/a/Library/Caches/Homebrew/downloads/31fec6e83b749c53c91d0796d695ae4717f21616ecca4510802b4eba864acca2--nginx-1.17.9.catalina.bottle.tar.gz
==> Pouring nginx-1.17.9.catalina.bottle.tar.gz
Warning: The post-install step did not complete successfully
You can try again using `brew postinstall nginx`
==> Caveats
Docroot is: /usr/local/var/www

The default port has been set in /usr/local/etc/nginx/nginx.conf to 8080 so that
nginx can run without sudo.

nginx will load all files in /usr/local/etc/nginx/servers/.

To have launchd start nginx now and restart at login:
  brew services start nginx
Or, if you don't want/need a background service you can just run:
  nginx
==> Summary
🍺  /usr/local/Cellar/nginx/1.17.9: 27 files, 2.1MB`

`brew postinstall nginx --debug
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/nginx.rb
==> Postinstalling nginx
Warning: The post-install step did not complete successfully
You can try again using `brew postinstall nginx`
==> An exception occurred within a child process:
  Errno::EACCES: Permission denied @ rb_sysopen - /usr/local/etc/nginx/fa
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:1386:in `initialize'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:1386:in `open'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:1386:in `block in copy_file'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:1385:in `open'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:1385:in `copy_file'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:492:in `copy_file'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:419:in `block in cp'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:1557:in `block in fu_each_src_dest'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:1573:in `fu_each_src_dest0'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:1555:in `fu_each_src_dest'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:418:in `cp'
/usr/local/Homebrew/Library/Homebrew/extend/pathname.rb:209:in `cp_path_sub'
/usr/local/Homebrew/Library/Homebrew/install_renamed.rb:16:in `cp_path_sub'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1006:in `block (2 levels) in run_post_install'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/find.rb:49:in `block (2 levels) in find'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/find.rb:48:in `catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/find.rb:48:in `block in find'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/find.rb:43:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/find.rb:43:in `find'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1003:in `block in run_post_install'
/usr/local/Homebrew/Library/Homebrew/utils.rb:478:in `with_env'
/usr/local/Homebrew/Library/Homebrew/formula.rb:999:in `run_post_install'
/usr/local/Homebrew/Library/Homebrew/postinstall.rb:21:in `<main>'`

Thanks In Advance

**Comment by drbyte** [comment]
Line 9 of your nginx.conf is doing its normal task of trying to load the mime.types file, but the file does not exist.
The post-install process shows that it ran into a permissions error while trying to copy files.

This suggests that you have some ownership/permission differences in the homebrew "stuff".

I recommend the following, which will destructively remove several things in the process:
`brew remove nginx`
`sudo rm -rf /usr/local/Cellar/nginx /usr/local/var/log/nginx /usr/local/etc/nginx`
`sudo chown -R $(whoami):admin $(brew --prefix)/*`
`brew services cleanup`
`brew doctor`

And then ask valet to install nginx again as part of its usual install process:
`valet install`

**Comment by EmperorKonstantin** [comment]
drbyte! You saved me! After updating my Apple Developer Transition Kit's Big Sur to OS 11 Beta 6, Nginx started failing to start with an errorless exception. dnsmasq as well needed to be fully removed and reinstalled. 

**Valet works again! WOOP WOOP!**

**Comment by EmperorKonstantin** [comment]
OS 11 Beta 7 update broke Nginx again. We should probably figure out what about the updates is causing Homebrew installed Nginx to break. I'm assuming dnsmasq broke too, haven't tried to repair it yet. I don't even know who to report this to yet.

**Comment by abhishek-pokhriyal** [comment]
After updating Big Sur, nginx php dnsmasq cannot be started. Can I use the same steps for all of these?
![image](https://user-images.githubusercontent.com/11808845/107569624-8ca68f80-6c0e-11eb-803b-92410833f226.png)

**Comment by drbyte** [comment]
> After updating Big Sur, nginx php dnsmasq cannot be started. Can I use the same steps for all of these?
> ![image](https://user-images.githubusercontent.com/11808845/107569624-8ca68f80-6c0e-11eb-803b-92410833f226.png)

It's not clear whether you're having the same error as this thread started with.

Based only on your screenshot, I suggest:
```
brew services stop php@7.3
brew cleanup
brew services cleanup
sudo brew services cleanup
brew upgrade
composer global update
valet install
```

If you still have problems after that, open a new issue including the output of `valet diagnose` and more background info.

**Comment by drbyte** [comment]
@idmahbub Is this issue resolved for you? If so, please click Close below.

**Comment by abhishek-pokhriyal** [comment]
thanks drbyte. now getting this ![image](https://user-images.githubusercontent.com/11808845/107573223-3f78ec80-6c13-11eb-8bf8-b1f14356fdc5.png)

**Comment by drbyte** [comment]
> thanks drbyte. now getting this ![image](https://user-images.githubusercontent.com/11808845/107573223-3f78ec80-6c13-11eb-8bf8-b1f14356fdc5.png)

Looks like your composer update didn't build its classes properly.
Try an aggressive reset:
```sh
rm -rf ~/.composer/vendor ~/.composer/composer.lock
composer global update
php -v
valet install
```
