### ISSUE TITLE
Bedrock driver does not allow pretty permalink rewrites under /wp/ directory

### ISSUE THREAD

**Issue by zamson** [laravel/valet#927]
I'm using WordPress and Bedrock together with a plugin (wp-graphql) that needs to create the following rewrite **example.test/wp/graphql**. However rewrites under /wp/ does not work and renders the following error:

```
Warning: require(/Users/x/code/example.com/web/wp/graphql): failed to open stream: No such file or directory in /Users/x/.composer/vendor/laravel/valet/server.php on line 191

Fatal error: require(): Failed opening required '/Users/x/code/example.com/web/wp/graphql' (include_path='.:/usr/local/Cellar/php/7.3.5/share/php/pear') in /Users/x/.composer/vendor/laravel/valet/server.php on line 191
```

Normal rewrites under example.test works (with pretty permalinks enabled). The rewrite under /wp/graphql works when running the same install / setup on my VPS droplet with nginx so I'm suspecting it's the Valet / Bedrock driver that needs some tweaking.

**Comment by stevebauman** [comment]
I was able to get this working by creating a local valet driver in the **_root_** of my Bedrock application:

```php
<?php

// LocalValetDriver.php

<?php

class LocalValetDriver extends LaravelValetDriver
{
    public function serves($sitePath, $siteName, $uri)
    {
        return $uri === "/wp/graphql";
    }

    public function frontControllerPath($sitePath, $siteName, $uri)
    {
        return $sitePath.'/web/index.php';
    }
}
```

You should no longer receive errors from visiting the GraphQL endpoint of your Bedrock application with Valet. 👍
