### ISSUE TITLE
[Question] Use Apache2 instead of Nginx.

### ISSUE THREAD

**Issue by crydotsnake** [laravel/valet#932]
Hello, is there an option to use Laravel Valet with Apache2 instead of nginx?. Would be cool, to switch between those webserver options, (if thats possible).

**Comment by drbyte** [comment]
No, there is no Apache support in Valet. That would require significant changes.

**Comment by ihorvorotnov** [comment]
@crydotsnake Do you have any particular reason why you'd need Apache2?

**Comment by crydotsnake** [comment]
@drbyte I have more experience with Apache2.

@ihorvorotnov Hm no.. not really.

**Comment by drbyte** [comment]
As far as I know there are no plans for this.

**Comment by crydotsnake** [comment]
Okay.

This another issue has nothing todo with Laravel Valet, i cant install PHP Extensions using PECL i always get this error message: 
![pecl_error](https://user-images.githubusercontent.com/39345336/79341162-a82c0580-7f2b-11ea-88df-10b385161f3a.png)

**Comment by mattstauffer** [comment]
Please feel free to open a separate issue if it's Valet-related, but for non-Valet stuff this isn't the right space. Good luck!

**Comment by crydotsnake** [comment]
Thank you dear @mattstauffer !, and sorry!. Just didnt find any solutions yet 😅.

**Comment by mattstauffer** [comment]
@crydotsnake Don't be sorry! Good luck!!!
