### ISSUE TITLE
`valet share` breaks `dyld`

### ISSUE THREAD

**Issue by charpun** [laravel/valet#946]
Running `valet share` resulted in the following error:
```
dyld: Library not loaded: /usr/local/opt/icu4c/lib/libicuio.64.dylib
  Referenced from: /usr/local/bin/php
  Reason: image not found
Abort trap: 6
```
There were no errors prior to this.

Reinstalling _each_ version of PHP through `brew reinstall php@{version}` seems to have resolved this, however this probably should not have caused a problem in the first place.

**Comment by drbyte** [comment]
This is not a Valet issue.
This is a Homebrew issue, where the PHP version that you had linked at the time of invoking PHP is incompatible with the `icu4c` package that Homebrew has installed. 
(The `icu4c` package was updated this week in Homebrew's taps, and is incompatible with older PHP versions, especially PHP versions from unofficial taps.)

**Comment by charpun** [comment]
Understanding that this is not inherently a Valet issue, everything worked prior to running this command. Does that mean that under-the-hood Valet is upgrading Homebrew packages?

**Comment by drbyte** [comment]
> Does that mean that under-the-hood Valet is upgrading Homebrew packages?

Valet only manages Homebrew packages insomuch as when you run `valet install` it installs php, dnsmasq, and nginx. And, when you run `valet use php@X.Y` it installs that PHP version and does some switching of configs accordingly. 
But if you use PHP 5.6 you're using unofficial obsolete PHP which is highly incompatible with newer stuff, and you'll run into this `icu4c` and other dylib issues more and more while trying to use older packages.

**Comment by charpun** [comment]
Running PHP 7.4

**Comment by drbyte** [comment]
Interpreting the error message:

> Library not loaded: /usr/local/opt/icu4c/lib/libicuio.64.dylib
  Referenced from: /usr/local/bin/php
  Reason: image not found

You (or the script you called) ran `/usr/local/bin/php` (which is the symlink to whatever PHP version was linked at the time you ran it).
That PHP version has a dependency (from when it was compiled and/or installed) on `/usr/local/opt/icu4c/lib/libicuio.64.dylib` which was not present ("image not found") on your filesystem at the time you ran the command.

**Comment by drbyte** [comment]
You might try upgrading to Valet 2.10.0 and running `valet diagnose` and pasting the output in a reply here. The output may expose other issues you have on your computer.

Granted, you posted that you've already manually run a bunch of installations that have allegedly fixed the issue, so it's quite probable that there's nothing much left to reverse-engineer things in order to find the exact cause.

**Comment by nateritter** [comment]
I know this is an older post but [this article](https://medium.com/code-kings/brew-php-yarn-node-laravel-error-libicuio-64-dylib-not-found-try-this-5d98e7877335) helped me fix this.

To reiterate what's said in the article for posterity....

> Upon doing some research I found this has something to do with brew not using the proper dependencies for the icuio64 library. Here is a quick script to reinstall the apps that use icuio64 as a dependencies

`brew uses --installed icu4c | xargs brew reinstall`

> Once that script is completed, you might have to manual remove the reinstall package from the “Cellar” of the Brew installation. It will give you instructions on how to do that in the terminal.
>
> After that try running your Laravel Valet again:

`valet list //Lists Commands for Valet. A good test command.`

**Comment by drbyte** [comment]
That's certainly an option. Thanks for posting it!. 

Note: Sometimes calling `reinstall` may require a `--force` tag, but then that installs it as `packagename-reinstall` and that version-name/number has sometimes caused Valet to not recognize it. 

If keeping a mix of very old and much newer homebrew-installed apps on the machine (ie: not keeping everything up to date in tandem) then sometimes it's necessary to tell homebrew to install-from-source for various packages. 

Usually upgrading everything (regularly) is simplest: `brew upgrade`
(Or you can run `brew update && brew outdated` to show what "needs" upgrading, before doing the actual upgrade.)

Often uninstalling (all) the Homebrew packages and installing them clean works too. Valet has a `valet uninstall --force` to clean up all Valet stuff. After that you can clean up any remaining Homebrew issues, and re-install Valet.

**Comment by tonsoflaz2** [comment]
> I know this is an older post but [this article](https://medium.com/code-kings/brew-php-yarn-node-laravel-error-libicuio-64-dylib-not-found-try-this-5d98e7877335) helped me fix this.
> 
> To reiterate what's said in the article for posterity....
> 
> > Upon doing some research I found this has something to do with brew not using the proper dependencies for the icuio64 library. Here is a quick script to reinstall the apps that use icuio64 as a dependencies
> 
> `brew uses --installed icu4c | xargs brew reinstall`
> 
> > Once that script is completed, you might have to manual remove the reinstall package from the “Cellar” of the Brew installation. It will give you instructions on how to do that in the terminal.
> > After that try running your Laravel Valet again:
> 
> `valet list //Lists Commands for Valet. A good test command.`

this just saved my *ss today, thank you!
