### ISSUE TITLE
 Preventing missing assets from reaching PHP

### ISSUE THREAD

**Issue by ArondeParon** [laravel/valet#953]
## Clear description of your problem
I am currently working on a WordPress installation which has a pretty big pile of assets running in production that I do not have on my local environment.

These missing files result in `$this->isStaticFile()` from evaluating to `false`, where each missing JPG/PNG/whatever results in yet _another_ call to my WordPress instance, which then handles the 404 appropriately. 

## Expected behavior
Because of the high number of 404's that I cannot easily fix, I am looking for a solution to have Nginx handle these missing static files instead of proxy'ing them to WordPress.

**Comment by ihorvorotnov** [comment]
As a workaround you can serve static files from production (or staging, doesn't matter - basically, from **remote** host). This will help you avoid that 404 errors: https://gist.github.com/mishterk/a8f19eeb514cf77ad333fb67b3c7aeb9

**Comment by techieshark** [comment]
@ArondeParon did you happen to find an nginx solution? I was thinking just edit the valet nginx config (~/.config/valet/Nginx) and use a reverse proxy -

```
    # Magic: make it so we don't need a copy of all the uploads, we actually just rely on the production server
    location /wp-content/wp/wp-content/uploads/ {
        log_not_found on;
        log_subrequest on;
        proxy_ssl_server_name on;
        proxy_pass https://example.com/;
    }
```

It's not quite working for me yet tho. I tried the local driver from @ihorvorotnov (thanks!) but for some reason that's not doing anything for me either.

**Comment by ArondeParon** [comment]
@techieshark if I remember correctly, my original issue was WordPress/Themosis related. I solved the issue by creating a custom driver and adding it to `~/.config/valet/Drivers`: https://gist.github.com/ArondeParon/b815c92e3f7a3124f3bb619ec8014230

Maybe it can be of help to you!

**Comment by techieshark** [comment]
Thanks @ArondeParon. It's been a while since I've done tons of WP/php work, so I wasn't able to get the custom driver work. But I now have this working with just an nginx config. I'll share it here in case useful to others. 

```
# in ~/.config/valet/Nginx/your-site.test
server { 
...
# The only change to the Valet nginx file:
include "/Users/your-user/.config/valet/Nginx-includes/your-site.test--tweaks"; 
# note we put these in a new "Nginx-includes" directory; if we put them in the Nginx directory, 
#   Nginx would try to run our include file as its own server
...
}
```

and in the new file, `/Users/your-user/.config/valet/Nginx-includes/your-site.test--tweaks`:
```
# Define some DNS resolvers needed for us to
# proxy_pass (reverse proxy) requests on to the production site.
resolver               1.1.1.1 1.0.0.1 valid=300s;
resolver_timeout       2s;

location ~ ^/wp-content/uploads/(.*) {
    add_header Via "1.0 valet-proxy";
    proxy_ssl_server_name on;
    # Note the "/wp" here - remove if not needed in your setup
    proxy_pass https://www.your-production-server.com/wp/wp-content/uploads/$1;
    # Note  also the proxy_pass requires the "resolver" setting, which we've set above.
}
# This location is only for Roots Bedrock sites (which rename "/wp-content" as "/app"):
location ~ ^/app/uploads/(.*) {
    add_header Via "1.0 valet-proxy";
    proxy_ssl_server_name on;
    proxy_pass https://www.your-production-server.com/wp/wp-content/uploads/$1;
}

# Add these to log additional things for debugging proxy_pass above.
rewrite_log on;
log_not_found on;
log_subrequest on;
access_log "/Users/your-user/.config/valet/Log/nginx-access.log";
error_log "/Users/your-user/.config/valet/Log/nginx-error.log" info;
```

**With this config, we can rely entirely on the production server for the uploads files rather than copying them locally.**
