### ISSUE TITLE
Could not resolve: example.de.test (Domain name not found) 

### ISSUE THREAD

**Issue by jprangenbergde** [laravel/valet#960]
If i call the `example.de.test` domain with the **Laravel Http client**, the error occurres:

`Could not resolve: example.de.test (Domain name not found)`

Browsing with a browser to `example.de.test` will work as expected.
Pinging to `example.de.test` will work as expected.
curl with the terminal to `example.de.test` will work as expected.

Any suggestions?

PHP Version: 7.4.6

**Comment by tooshay** [comment]
Did you resolve this? I've run into the same issue exactly.

**Comment by jprangenbergde** [comment]
> Did you resolve this? I've run into the same issue exactly.

No, currently im using homestead.
