### ISSUE TITLE
[Feature Request] Add support for sharing for Expose (alternative to ngrok)

### ISSUE THREAD

**Issue by vesper8** [laravel/valet#962]
Now that https://github.com/beyondcode/expose has been released, I think many Valet users would appreciate the option to use it as an alternative to ngork when using `valet share`

**Comment by drbyte** [comment]
I'm having trouble understanding what you mean.

How do you envision this operating? You must have something in mind that I'm not seeing.

Currently typing `valet share` fires ngrok, and typing `expose` fires expose. Both painless. One is shorter (faster to type) than the other.

One notable difference: `valet share` copies the generated URL to the clipboard but `expose` does not. I imagine they'd be open to a PR that adds that to expose.

**Comment by mattstauffer** [comment]
@drbyte I think a lot of folks are excited about the idea and see "valet share" still existing in Valet meaning we don't connect with Expose.

Maybe it's worth a tweet--you want to put it out and I'll RT it? 

I assume we just want to say: "Valet works great with Expose!" or something like that, basically making it clear that nothing needs to change.

**Comment by edalzell** [comment]
It could be a config option as well? `valet set share expose`, then `valet share` would fire Expose?

**Comment by drbyte** [comment]
@mattstauffer https://twitter.com/DrByteZC/status/1274015447688626177
