### ISSUE TITLE
More slow response times in Valet + tons of 504 gateway timeouts

### ISSUE THREAD

**Issue by havardlj** [laravel/valet#965]
## Clear description of your problem

Same as in issue #744, slow response time including 504-timeouts. Tried the suggested solutions in mentioned thread without any change in behavior.
## Expected behavior
Normal load times, no time outs.
## Current behavior
10 second+ load times on most request, 504-timeouts on larger requests (like new matrix blocks in Craft CMS), my mac seems to have been operating slower in general since the problem occured, but no other applications behave as slow as valet

PHP memory limit is at 256M, max load time 120

## Steps to Reproduce
Worked fine until recently, upgraded to Mac OS 10.14.6 (18G5033), but the problem occurred the next day.
I have Nord VPN installed, but this did not cause any issues during the months before the issue occurred.

Using the latest MBP

## Diagnosis
<details>
<summary>sw_vers</summary>
<pre>ProductName:	Mac OS X
ProductVersion:	10.14.6
BuildVersion:	18G5033</pre>
</details>
<details>
<summary>valet --version</summary>
<pre>Laravel Valet 2.11.0</pre>
</details>
<details>
<summary>cat ~/.config/valet/config.json</summary>
<pre>{
    "tld": "test",
    "paths": [
        "/Users/havardlj/.config/valet/Sites"
    ]
}</pre>
</details>
<details>
<summary>cat ~/.composer/composer.json</summary>
<pre>{
    "require": {
        "laravel/valet": "^2.8"
    }
}</pre>
</details>
<details>
<summary>composer global diagnose</summary>
<pre>Changed current directory to /Users/havardlj/.composer
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: ...
Dev Public Key Fingerprint: ...
OK
Checking composer version: OK
Composer version: 1.10.8
PHP version: 7.4.2
PHP binary path: /usr/local/Cellar/php/7.4.2/bin/php
OpenSSL version: OpenSSL 1.1.1d  10 Sep 2019</pre>
</details>
<details>
<summary>composer global outdated</summary>
<pre>Changed current directory to /Users/havardlj/.composer</pre>
</details>
<details>
<summary>ls -al /etc/sudoers.d/</summary>
<pre>total 0
drwxr-xr-x   2 root  wheel    64 Feb 23  2019 .
drwxr-xr-x  89 root  wheel  2848 Jun 26 11:44 ..</pre>
</details>
<details>
<summary>brew config</summary>
<pre>HOMEBREW_VERSION: 2.4.2
ORIGIN: https://github.com/Homebrew/brew
HEAD: ...
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: ...
Core tap last commit: 69 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_MAKE_JOBS: 4
CPU: quad-core 64-bit kabylake
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
Clang: 10.0 build 1001
Git: 2.20.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
macOS: 10.14.6-x86_64
CLT: 10.3.0.0.1.1562985497
Xcode: N/A</pre>
</details>
<details>
<summary>brew services list</summary>
<pre>Name      Status  User     Plist
dnsmasq   started root     /Library/LaunchDaemons/homebrew.mxcl.dnsmasq.plist
mysql     started havardlj /Users/havardlj/Library/LaunchAgents/homebrew.mxcl.mysql.plist
mysql@5.7 started havardlj /Users/havardlj/Library/LaunchAgents/homebrew.mxcl.mysql@5.7.plist
nginx     started root     /Library/LaunchDaemons/homebrew.mxcl.nginx.plist
php       started root     /Library/LaunchDaemons/homebrew.mxcl.php.plist</pre>
</details>
<details>
<summary>brew list --versions | grep -E "(php|nginx|dnsmasq|mariadb|mysql|mailhog|openssl)(@\d\..*)?\s"</summary>
<pre>curl-openssl 7.68.0
dnsmasq 2.80
mysql 8.0.19
mysql@5.7 5.7.29
nginx 1.17.8
openssl@1.1 1.1.1d
php 7.4.2</pre>
</details>
<details>
<summary>brew outdated</summary>
<pre>c-ares
curl-openssl
dnsmasq
freetds
freetype
gettext
glib
gmp
icu4c
jansson
jemalloc
libev
libffi
libpq
libtool
libzip
mysql
nghttp2
nginx
oniguruma
openldap
openssl@1.1
pcre
php
protobuf
python
readline
sqlite
xz</pre>
</details>
<details>
<summary>php -v</summary>
<pre>PHP 7.4.2 (cli) (built: Jan 22 2020 06:34:34) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.2, Copyright (c), by Zend Technologies</pre>
</details>
<details>
<summary>which -a php</summary>
<pre>/usr/local/bin/php
/usr/bin/php</pre>
</details>
<details>
<summary>php --ini</summary>
<pre>Configuration File (php.ini) Path: /usr/local/etc/php/7.4
Loaded Configuration File:         /usr/local/etc/php/7.4/php.ini
Scan for additional .ini files in: /usr/local/etc/php/7.4/conf.d
Additional .ini files parsed:      /usr/local/etc/php/7.4/conf.d/ext-opcache.ini,
/usr/local/etc/php/7.4/conf.d/php-memory-limits.ini</pre>
</details>
<details>
<summary>nginx -v</summary>
<pre>nginx version: nginx/1.17.8</pre>
</details>
<details>
<summary>curl --version</summary>
<pre>curl 7.54.0 (x86_64-apple-darwin18.0) libcurl/7.54.0 LibreSSL/2.6.5 zlib/1.2.11 nghttp2/1.24.1
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz HTTP2 UnixSockets HTTPS-proxy</pre>
</details>
<details>
<summary>php --ri curl</summary>
<pre>curl

cURL support => enabled
cURL Information => 7.68.0
Age => 5
Features
AsynchDNS => Yes
CharConv => No
Debug => No
GSS-Negotiate => No
IDN => No
IPv6 => Yes
krb4 => No
Largefile => Yes
libz => Yes
NTLM => Yes
NTLMWB => Yes
SPNEGO => Yes
SSL => Yes
SSPI => No
TLS-SRP => Yes
HTTP2 => Yes
GSSAPI => Yes
KERBEROS5 => Yes
UNIX_SOCKETS => Yes
PSL => No
HTTPS_PROXY => Yes
MULTI_SSL => No
BROTLI => Yes
Protocols => dict, file, ftp, ftps, gopher, http, https, imap, imaps, ldap, ldaps, pop3, pop3s, rtmp, rtsp, scp, sftp, smb, smbs, smtp, smtps, telnet, tftp
Host => x86_64-apple-darwin18.7.0
SSL Version => OpenSSL/1.1.1d
ZLib Version => 1.2.11
libSSH Version => libssh2/1.9.0

Directive => Local Value => Master Value
curl.cainfo => no value => no value</pre>
</details>
<details>
<summary>~/.composer/vendor/laravel/valet/bin/ngrok version</summary>
<pre>ngrok version 2.3.35</pre>
</details>
<details>
<summary>ls -al ~/.ngrok2</summary>
<pre>total 8
drwx------   3 havardlj  staff    96 Feb 20 15:41 .
drwxr-xr-x+ 35 havardlj  staff  1120 Jun 25 15:21 ..
-rw-------   1 havardlj  staff    55 Feb 20 15:41 ngrok.yml</pre>
</details>
<details>
<summary>brew info nginx</summary>
<pre>nginx: stable 1.19.0 (bottled), HEAD
HTTP(S) server and reverse proxy, and IMAP/POP3 proxy server
https://nginx.org/
/usr/local/Cellar/nginx/1.17.8 (25 files, 2MB) *
  Poured from bottle on 2020-02-07 at 12:32:18
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/nginx.rb
==> Dependencies
Required: openssl@1.1, pcre
==> Options
--HEAD
	Install HEAD version
==> Caveats
Docroot is: /usr/local/var/www

The default port has been set in /usr/local/etc/nginx/nginx.conf to 8080 so that
nginx can run without sudo.

nginx will load all files in /usr/local/etc/nginx/servers/.

To have launchd start nginx now and restart at login:
  brew services start nginx
Or, if you don't want/need a background service you can just run:
  nginx
==> Analytics
install: 35,778 (30 days), 102,288 (90 days), 408,940 (365 days)
install-on-request: 34,718 (30 days), 99,253 (90 days), 394,082 (365 days)
build-error: 0 (30 days)</pre>
</details>
<details>
<summary>brew info php</summary>
<pre>php: stable 7.4.7 (bottled), HEAD
General-purpose scripting language
https://www.php.net/
/usr/local/Cellar/php/7.4.2 (518 files, 76.0MB) *
  Poured from bottle on 2020-02-07 at 11:47:03
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/php.rb
==> Dependencies
Build: httpd, pkg-config
Required: apr, apr-util, argon2, aspell, autoconf, curl-openssl, freetds, freetype, gettext, glib, gmp, icu4c, jpeg, libffi, libpng, libpq, libsodium, libzip, oniguruma, openldap, openssl@1.1, sqlite, tidy-html5, unixodbc, webp
==> Options
--HEAD
	Install HEAD version
==> Caveats
To enable PHP in Apache add the following to httpd.conf and restart Apache:
    LoadModule php7_module /usr/local/opt/php/lib/httpd/modules/libphp7.so

    <FilesMatch \.php$>
        SetHandler application/x-httpd-php
    </FilesMatch>

Finally, check DirectoryIndex includes index.php
    DirectoryIndex index.php index.html

The php.ini and php-fpm.ini file can be found in:
    /usr/local/etc/php/7.4/

To have launchd start php now and restart at login:
  brew services start php
Or, if you don't want/need a background service you can just run:
  php-fpm
==> Analytics
install: 51,565 (30 days), 148,670 (90 days), 515,302 (365 days)
install-on-request: 49,333 (30 days), 140,182 (90 days), 479,299 (365 days)
build-error: 0 (30 days)</pre>
</details>
<details>
<summary>brew info openssl</summary>
<pre>openssl@1.1: stable 1.1.1g (bottled) [keg-only]
Cryptography and SSL/TLS Toolkit
https://openssl.org/
/usr/local/Cellar/openssl@1.1/1.1.1d (7,983 files, 17.9MB)
  Poured from bottle on 2020-02-07 at 11:37:04
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/openssl@1.1.rb
==> Caveats
A CA file has been bootstrapped using certificates from the system
keychain. To add additional certificates, place .pem files in
  /usr/local/etc/openssl@1.1/certs

and run
  /usr/local/opt/openssl@1.1/bin/c_rehash

openssl@1.1 is keg-only, which means it was not symlinked into /usr/local,
because macOS provides LibreSSL.

==> Analytics
install: 651,967 (30 days), 2,430,078 (90 days), 6,071,847 (365 days)
install-on-request: 86,406 (30 days), 367,186 (90 days), 812,393 (365 days)
build-error: 0 (30 days)</pre>
</details>
<details>
<summary>openssl version -a</summary>
<pre>LibreSSL 2.6.5
built on: date not available
platform: information not available
options:  bn(64,64) rc4(16x,int) des(idx,cisc,16,int) blowfish(idx) 
compiler: information not available
OPENSSLDIR: "/private/etc/ssl"</pre>
</details>
<details>
<summary>openssl ciphers</summary>
<pre>...</pre>
</details>
<details>
<summary>sudo nginx -t</summary>
<pre>nginx: the configuration file /usr/local/etc/nginx/nginx.conf syntax is ok
nginx: configuration file /usr/local/etc/nginx/nginx.conf test is successful</pre>
</details>
<details>
<summary>which -a php-fpm</summary>
<pre>/usr/local/sbin/php-fpm
/usr/sbin/php-fpm</pre>
</details>
<details>
<summary>/usr/local/opt/php/sbin/php-fpm -v</summary>
<pre>PHP 7.4.2 (fpm-fcgi) (built: Jan 22 2020 06:34:43)
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.2, Copyright (c), by Zend Technologies</pre>
</details>
<details>
<summary>sudo /usr/local/opt/php/sbin/php-fpm -y /usr/local/etc/php/7.4/php-fpm.conf --test</summary>
<pre>[26-Jun-2020 13:03:18] NOTICE: configuration file /usr/local/etc/php/7.4/php-fpm.conf test is successful</pre>
</details>
<details>
<summary>ls -al ~/Library/LaunchAgents | grep homebrew</summary>
<pre>-rw-r--r--   1 havardlj  staff   543 Jun 25 17:01 homebrew.mxcl.mysql.plist
-rw-r--r--   1 havardlj  staff   551 Feb  7 13:50 homebrew.mxcl.mysql@5.7.plist
-rw-r--r--   1 havardlj  staff   628 Jun 25 16:01 homebrew.mxcl.php.plist</pre>
</details>
<details>
<summary>ls -al /Library/LaunchAgents | grep homebrew</summary>
<pre></pre>
</details>
<details>
<summary>ls -al /Library/LaunchDaemons | grep homebrew</summary>
<pre>-rw-r--r--   1 root  admin   657 Jun 25 16:54 homebrew.mxcl.dnsmasq.plist
-rw-r--r--   1 root  admin   571 Jun 25 16:54 homebrew.mxcl.nginx.plist
-rw-r--r--   1 root  admin   628 Jun 25 16:54 homebrew.mxcl.php.plist</pre>
</details>

**Comment by drbyte** [comment]
Possible causes:

1 The 10s+ load times feel like either a DNS resolution issue (delayed lookups due to internal timeouts). 
Setting your Mac's primary DNS to 127.0.0.1 can help with that, since that's where dnsmasq listens, and that's what Valet uses to serve local sites.
If the slowness is for external sites, then also configuring dnsmasq with a specific public DNS server can help too. I've discussed that in a dozen other issues:
Create `~/.config/valet/dnsmasq.d/dns-cloudflare1111-normal.conf` containing these lines:
```text
# Fallback servers to use if we can't resolve locally
# These are Cloudflare's public DNS:
# https://developers.cloudflare.com/1.1.1.1/
server=1.1.1.1
server=1.0.0.1
#server=2606:4700:4700::1111
#server=2606:4700:4700::1001
```

2 Outdated software. 
Your brew outdated command reveals lots of outdated packages. Run `brew upgrade` to bring them up to date. In your case `nginx` and `dnsmasq` and `php` are in that list, along with lots of their dependencies.
Perhaps the refresh that happens by updating those apps may bring things in line with your OS upgrade you did recently.

3 Multiple MySQL versions running simultaneously
I see you've got both 5.7 and 8.0 running simultaneously. Are they on different ports? Are they competing for resources or cpu cycles? Could they be causing timeouts on sites that are expecting a db response?

4 Something with Craft? 
(since most people reporting any of this slowness (such as in the issue you referenced) happen to also be reporting it in conjunction with Craft)

**Comment by havardlj** [comment]
I just went through the steps, and now valet is actually slower than before. The requirement overview in Craft has no warnings. Looks like I'll have to go back to Apache for a while to get some work done.

**Comment by drbyte** [comment]
Spending some time profiling where the slowness is coming from would be useful. Probably tailing nginx and php and dnsmasq logs, as well as looking at the browser's dev tools to identify which networking requests are happening (what kinds of requests, which ones are timing out, etc) are good starting points.

**Comment by handhikadj** [comment]
+1 on this. What is the current alternative in favor of this?

**Comment by mattstauffer** [comment]
@handhikadj what does this question mean?

**Comment by handhikadj** [comment]
got problem back then. never mind now
