### ISSUE TITLE
Consider making it easier for users to modify their Nginx config

### ISSUE THREAD

**Issue by mattstauffer** [laravel/valet#969]
Use case:
If you're debugging with Xdebug, you'll get a 504 Gateway Time-out if you spend more than 30 seconds (or whatever our current setting is) debugging.

Potential solution:
First, this *may* already be easy based on changes someone not-me wrote. If so, my bad!
If not, let's see what it looks like to make this super easily customizable. <3

**Comment by nedmas** [comment]
So [`fastcgi_read_timeout`](http://nginx.org/en/docs/http/ngx_http_fastcgi_module.html#fastcgi_read_timeout) is the config we need to change. I think the best place to put it is in the Nginx site config. Currently Valet has stubs for those (one each for secure/unsecure). So we could just add a sensible default (`60s`? or `120s`?) into the stubs. That might be a good first step? Then we could add a config value to Valet to customise the timeout and a command to update it?

I'd be happy to put a couple of PR's together for this if no one else is working on it?

**Comment by drbyte** [comment]
Valet currently works with Nginx's default config-file paths as well as a few that Valet has added for its own use:

`~/.config/valet/Nginx/*`
`/usr/local/etc/nginx/servers/*`

For example I control CORS using:
`~/.config/valet/Nginx/cors.conf`

I usually put custom fastcgi stuff at:
`~/.config/valet/Nginx/valet_fastcgi_settings.conf`
with contents of:
```
# If no responses are read for this length of time, connection is closed
fastcgi_read_timeout 360;
```

(and at one time I was toying with having it at the following path but it's slightly harder to "get to" for quick editing)
`/usr/local/etc/nginx/servers/valet_fastcgi_settings.conf`

**Comment by nedmas** [comment]
Hey @drbyte, that's a really cool and much more elegant solution! Is it worth a specific mention in the docs regarding it's use with Xdebug? Happy to put a PR together if so.

**Comment by drbyte** [comment]
I attempted something slightly related but it was rejected: https://github.com/laravel/docs/pull/6202/files

That said, Xdebug is much more specific than what I was targeting, so feel free to submit something!
