### ISSUE TITLE
502 Error in browser : When sending more than 5 requests from the frontend to Laravel Valet.

### ISSUE THREAD

**Issue by chris-barklem** [laravel/valet#971]
This issue relates to the failure to document with transparency the pm.max_children setting in: valet-fpm.conf which leads to frontend restrictions and failures in Laravel Queue.

## Clear description of your problem
When the application is using any form of asynchronous request structures on the frontend. E.g:

`array.foreach(postSomethingToLaravel)`

Or asynchronously

`async processItems(array) {
                var vm = this.$data;
                for (const item of array) {
                    await this.processItem(item);
                }
                console.log('Upload completed!');
                this.updateTable();
}`

Laravel Valet will by default limit the maximum number of open requests to 5 (pm.max_children). Furthermore when using Laravel Queue to manage large request processing. Valet will restrict the afterResponse method from releasing the request and passing the job to the queue. Eg.

`dispatch(function (Request $request) {
            ProcessReferenceImages::dispatch($request)->onQueue($que_name);
})->afterResponse($request);` 

In this instance, the afterResponse expectations of releasing the request (with a response) are held (at 5) until the first job is completed. 

## Expected behavior
It is expected that a development environment would adhere to the limitations of settings found in configurations within Nginx and in this instance the limitations of Laravel throttling. 

## Current behavior
Limitations have been set, which are difficult to locate (time-consuming) due to limited documentation (Google has no results on this development roadblock).

## Steps to Reproduce
To reproduce, simply send a request to a controller that is configured to dispatch->afterResponse with more than 5 requests sent (see asynchronous frontend request structure above).

## Possible solution
I believe that this is purely a documentation issue and that structuring documentation in a way that can be found (in Google) will resolve this issue. The pm.max_children setting is clearly a requirement for many development environments, therefore transparency on this limit should resolve this issue.

## Diagnosis
If any additional information is required I am happy to respond promptly.

**Comment by drbyte** [comment]
You're correct: Valet's default for `pm.max_children` is 5. This is also PHP's default (which, admittedly, they say is "based on a server with limited resources").

Keeping it at 5 is a happy balance between what's needed for regular local use vs RAM/resource requirements,
given that the vast majority of dev environments are not load-testing large instantly-simultaneous traffic bursts back to oneself.

That said, if your project regularly requires massive bursts of simultaneous traffic, there's nothing wrong with updating your local config accordingly: as you say, just edit the `valet-fpm.conf` file and restart php.

I'll work on a PR to add a brief note about this setting to the docs. Taylor can decide whether to include it.

**Comment by yob-yob** [comment]
what would be the reason.. if I only get this error if I'm dispatching a Job?

Environment Setup
- Macbook Apple M1 Chip
- Php 8.0.3
