### ISSUE TITLE
ContaoValetDriver not working for contao-manager.phar.php?

### ISSUE THREAD

**Issue by pgerundt** [laravel/valet#980]
## Clear description of your problem
The `ContaoValetDriver` does not seem to work for the `contao-manager.phar.php`.
Background: For installing the managed edition of Contao, the official manual suggests to create a subdirectory `/web` and place the `contao-manager.phar` file in there (see [installation instructions](https://contao.org/en/download.html)).
After renaming to `contao-manager.phar.php` the file should be accessible via the browser.

## Expected behavior
Calling `http://<domainname>.test/contao-manager.phar.php` should open the Contao Manager.

## Current behavior
Calling `http://<domainname>.test/contao-manager.phar.php` results in a Valet 404.

## Steps to Reproduce
1. Create a new Valet directory `<domainname>`
2. Create a subdirectory `/web`
3. Download `contao-manager.phar` from https://contao.org/en/download.html and place it into /web
4. Rename the file to `contao-manager.phar.php`
5. Open `http://<domainname>.test/contao-manager.phar.php` in browser

### Output of these steps
`404 - Not Found`

## Possible solution
When installing Contao, the directory `/vendor/contao` is not present yet (and the installation does not run if there are any files or directory present beside the `contao-manager.phar.php`
So `ContaoValetDriver::serves()` has to be modified to check whether there we are in "installation mode" (only `/web/contao-manager.phar.php` present) or Contao is already installed (/vendor/contao and `/web/app.php` present).
`ContaoValetDriver::frontControllerPath()` also has to be modified to resolve the requests to the `contao-manager.phar.php` file.
```
if (0 === strncmp($uri, '/contao-manager.phar.php', 24)) {
  return $sitePath.'/web/contao-manager.phar.php';
}
```
After modifying the `ContaoValetDriver` the Contao Manager opens up, but all `/api` requests (e.g. `http://<domainname>.test/contao-manager.phar.php/api/session`) to the phar file return a 404 error (not generated by Valet).
There is a discussion going on [here](https://github.com/contao/contao-manager/issues/587) that the 404's occur due to nginx misconfiguration.

## Diagnosis
not needed here

**Comment by aschempp** [comment]
`ContaoValetDriver` was created by @Toflar and maintained by @leofeyer maybe someone has an input. But apparently the driver wasn't updated for a while, most switched to the [Symfony Web Server](https://symfony.com/doc/current/setup/symfony_server.html) I guess.

**Comment by Toflar** [comment]
Yeah, I haven't used Valet for a long time. Not going to bother here, sorry.

**Comment by pgerundt** [comment]
3 years later - for everyone else struggling - here is a working `ContaoManagerValetDriver` to put into the custom Valet drivers directory:

```
<?php
class ContaoManagerValetDriver extends ValetDriver
{

    /**
     * Contao's document root (public/web)
     *
     * @var string
     */
    public $docRootPath = '';

    /**
     * Determine if the driver serves the request.
     *
     * @param  string  $sitePath
     * @param  string  $siteName
     * @param  string  $uri
     * @return bool
     */
    public function serves($sitePath, $siteName, $uri)
    {
        if (file_exists($sitePath.'/public/contao-manager.phar.php')) {
            $this->docRootPath = '/public';
        }
        if (file_exists($sitePath.'/web/contao-manager.phar.php')) {
            $this->docRootPath = '/web';
        }
        return $this->docRootPath != '';
    }

    /**
     * Determine if the incoming request is for a static file.
     *
     * @param  string  $sitePath
     * @param  string  $siteName
     * @param  string  $uri
     * @return string|false
     */
    public function isStaticFile($sitePath, $siteName, $uri)
    {
        if ($this->isActualFile($staticFilePath = $sitePath.'/web/'.$uri)) {
            return $staticFilePath;
        } elseif ($this->isActualFile($staticFilePath = $sitePath.'/public/'.$uri)) {
            return $staticFilePath;
        }

        return false;
    }

    /**
     * Get the fully resolved path to the application's front controller.
     *
     * @param  string  $sitePath
     * @param  string  $siteName
     * @param  string  $uri
     * @return string
     */
    public function frontControllerPath($sitePath, $siteName, $uri)
    {
        if(preg_match('/(^\/(contao-manager\.phar|preview)\.php)(.*)/', $uri, $match) === 1) {
            $frontControllerPath = $sitePath.$this->docRootPath.$match[1];
        }
        else {
            $frontControllerPath = $sitePath.$this->docRootPath.'/index.php';
        }

        $_SERVER['SCRIPT_FILENAME'] = $frontControllerPath;

        return $frontControllerPath;
    }
}
```

Works with `public` or `web` document root and fixes the Contao preview as a bonus.

**Comment by drbyte** [comment]
@pgerundt If you're willing to maintain the proposed Valet Driver, here's an option:

1. Create a github repo for it, with naming convention of `FooValetDriver` (eg: ends in '`ValetDriver`')
2. See example: https://github.com/DCzajkowski/DistValetDriver
3. In the README provide installation instructions (replacing `YOU` and `Foo` for yours of course):
`git clone https://github.com/YOU/FooValetDriver.git ~/.config/valet/Drivers`
4. Anytime someone wants to update their local driver from your git, they can run `git pull` from within that cloned directory. (You could explain that in your README as well)

Valet will look for all `XYZValetDriver` directories under `~/.config/valet/Drivers/`, and will make it available.

**Comment by pgerundt** [comment]
@drbyte done:
https://github.com/pgerundt/ContaoManagerValetDriver
