### ISSUE TITLE
Wordpress under Valet returns 301 error on URLs that should return 404 error

### ISSUE THREAD

**Issue by nickbasham** [laravel/valet#981]
I very well could have misconfigured something or have some other issue with my development setup, but I haven't been able to find a solution for this, so hopefully someone can help me figure this out. Thanks for any help you can provide!

## Clear description of your problem
Wordpress running with Valet is not returning a 404 error or the 404 template on URLs that don't exist. Instead it's sending a 301 permanent redirect to the home page.

## Expected behavior
URLs for pages that don't exist should return a 404 error and cause Wordpress to display the 404.php template.

## Current behavior
Browser receives a 301 redirect to the root URL.

## Steps to Reproduce
1. Set up a new Wordpress site under Valet
2. Go to a URL that does not exist on that site

## Diagnosis
<details>
<summary>sw_vers</summary>
<pre>ProductName:	Mac OS X
ProductVersion:	10.15.6
BuildVersion:	19G2021</pre>
</details>
<details>
<summary>valet --version</summary>
<pre>Laravel Valet 2.11.0</pre>
</details>
<details>
<summary>cat ~/.config/valet/config.json</summary>
<pre>{
    "tld": "test",
    "paths": [
        "/Users/nick/.config/valet/Sites",
        "/Users/nick/Sites"
    ]
}</pre>
</details>
<details>
<summary>cat ~/.composer/composer.json</summary>
<pre>{
    "require": {
        "laravel/valet": "^2.5",
        "laravel/installer": "^3.0"
    }
}</pre>
</details>
<details>
<summary>composer global diagnose</summary>
<pre>Changed current directory to /Users/nick/.composer
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: You are not running the latest stable version, run `composer self-update` to update (1.9.1 => 1.10.13)
Composer version: 1.9.1
PHP version: 7.4.6
PHP binary path: /usr/local/Cellar/php/7.4.6/bin/php</pre>
</details>
<details>
<summary>composer global outdated</summary>
<pre>Changed current directory to /Users/nick/.composer
illuminate/container v7.28.1 ~ v8.1.0 The Illuminate Container package.
illuminate/contracts v7.28.1 ~ v8.1.0 The Illuminate Contracts package.
laravel/installer    v3.2.0  ~ v4.0.3 Laravel application installer.
tightenco/collect    v7.26.1 ~ v8.0.0 Collect - Illuminate Collections as a separate package.</pre>
</details>
<details>
<summary>ls -al /etc/sudoers.d/</summary>
<pre>total 16
drwxr-xr-x   4 root  wheel   128 Sep  1 00:56 .
drwxr-xr-x  85 root  wheel  2720 Sep 11 17:41 ..
-rw-r--r--   1 root  wheel    80 Dec 12  2019 brew
-rw-r--r--   1 root  wheel    83 Dec 12  2019 valet</pre>
</details>
<details>
<summary>brew config</summary>
<pre>HOMEBREW_VERSION: 2.5.0
ORIGIN: https://github.com/Homebrew/brew
HEAD: 2ec8266697b2c9838cef86f8f97b5f392d0f926d
Last commit: 5 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: a19c0820d9e949e9aca700b1f45ab391d39d203f
Core tap last commit: 16 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 16
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 16-core 64-bit kabylake
Clang: 11.0 build 1103
Git: 2.24.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.6-x86_64
CLT: 11.0.33.12
Xcode: 11.7</pre>
</details>
<details>
<summary>brew services list</summary>
<pre>Name      Status  User Plist
dnsmasq   started root /Library/LaunchDaemons/homebrew.mxcl.dnsmasq.plist
mailhog   stopped      
mysql@5.7 started nick /Users/nick/Library/LaunchAgents/homebrew.mxcl.mysql@5.7.plist
nginx     started root /Library/LaunchDaemons/homebrew.mxcl.nginx.plist
php       started root /Library/LaunchDaemons/homebrew.mxcl.php.plist</pre>
</details>
<details>
<summary>brew list --versions | grep -E "(php|nginx|dnsmasq|mariadb|mysql|mailhog|openssl)(@\d\..*)?\s"</summary>
<pre>curl-openssl 7.70.0
dnsmasq 2.81
mailhog 1.0.0
mysql@5.7 5.7.29
nginx 1.17.10
openssl@1.1 1.1.1g
php 7.4.6</pre>
</details>
<details>
<summary>brew outdated</summary>
<pre>brotli
curl-openssl
dnsmasq
freetds
freetype
gdbm
gettext
glib
icu4c
krb5
libevent
libidn
libpq
libtool
libyaml
libzip
mysql@5.7
nghttp2
nginx
node
openldap
php
python@3.8
sqlite
stripe/stripe-cli/stripe
unixodbc
yarn</pre>
</details>
<details>
<summary>php -v</summary>
<pre>PHP 7.4.6 (cli) (built: May 14 2020 10:38:36) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Xdebug v2.9.6, Copyright (c) 2002-2020, by Derick Rethans
    with Zend OPcache v7.4.6, Copyright (c), by Zend Technologies</pre>
</details>
<details>
<summary>which -a php</summary>
<pre>/usr/local/bin/php
/usr/local/bin/php
/usr/bin/php</pre>
</details>
<details>
<summary>php --ini</summary>
<pre>Configuration File (php.ini) Path: /usr/local/etc/php/7.4
Loaded Configuration File:         /usr/local/etc/php/7.4/php.ini
Scan for additional .ini files in: /usr/local/etc/php/7.4/conf.d
Additional .ini files parsed:      /usr/local/etc/php/7.4/conf.d/ext-opcache.ini,
/usr/local/etc/php/7.4/conf.d/php-memory-limits.ini</pre>
</details>
<details>
<summary>nginx -v</summary>
<pre>nginx version: nginx/1.17.10</pre>
</details>
<details>
<summary>curl --version</summary>
<pre>curl 7.64.1 (x86_64-apple-darwin19.0) libcurl/7.64.1 (SecureTransport) LibreSSL/2.8.3 zlib/1.2.11 nghttp2/1.39.2
Release-Date: 2019-03-27
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS GSS-API HTTP2 HTTPS-proxy IPv6 Kerberos Largefile libz MultiSSL NTLM NTLM_WB SPNEGO SSL UnixSockets</pre>
</details>
<details>
<summary>php --ri curl</summary>
<pre>curl

cURL support => enabled
cURL Information => 7.70.0
Age => 6
Features
AsynchDNS => Yes
CharConv => No
Debug => No
GSS-Negotiate => No
IDN => No
IPv6 => Yes
krb4 => No
Largefile => Yes
libz => Yes
NTLM => Yes
NTLMWB => Yes
SPNEGO => Yes
SSL => Yes
SSPI => No
TLS-SRP => Yes
HTTP2 => Yes
GSSAPI => Yes
KERBEROS5 => Yes
UNIX_SOCKETS => Yes
PSL => No
HTTPS_PROXY => Yes
MULTI_SSL => No
BROTLI => Yes
Protocols => dict, file, ftp, ftps, gopher, http, https, imap, imaps, ldap, ldaps, pop3, pop3s, rtmp, rtsp, scp, sftp, smb, smbs, smtp, smtps, telnet, tftp
Host => x86_64-apple-darwin19.4.0
SSL Version => OpenSSL/1.1.1g
ZLib Version => 1.2.11
libSSH Version => libssh2/1.9.0

Directive => Local Value => Master Value
curl.cainfo => no value => no value</pre>
</details>
<details>
<summary>~/.composer/vendor/laravel/valet/bin/ngrok version</summary>
<pre>ngrok version 2.3.35</pre>
</details>
<details>
<summary>ls -al ~/.ngrok2</summary>
<pre>ls: /Users/nick/.ngrok2: No such file or directory</pre>
</details>
<details>
<summary>brew info nginx</summary>
<pre>nginx: stable 1.19.2 (bottled), HEAD
HTTP(S) server and reverse proxy, and IMAP/POP3 proxy server
https://nginx.org/
/usr/local/Cellar/nginx/1.17.10 (25 files, 2.1MB) *
  Poured from bottle on 2020-05-21 at 13:19:26
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/nginx.rb
License: BSD-2-Clause
==> Dependencies
Required: openssl@1.1, pcre
==> Options
--HEAD
	Install HEAD version
==> Caveats
Docroot is: /usr/local/var/www

The default port has been set in /usr/local/etc/nginx/nginx.conf to 8080 so that
nginx can run without sudo.

nginx will load all files in /usr/local/etc/nginx/servers/.

To have launchd start nginx now and restart at login:
  brew services start nginx
Or, if you don't want/need a background service you can just run:
  nginx
==> Analytics
install: 33,635 (30 days), 102,439 (90 days), 404,254 (365 days)
install-on-request: 32,982 (30 days), 100,363 (90 days), 392,195 (365 days)
build-error: 0 (30 days)</pre>
</details>
<details>
<summary>brew info php</summary>
<pre>php: stable 7.4.10 (bottled), HEAD
General-purpose scripting language
https://www.php.net/
/usr/local/Cellar/php/7.4.6 (519 files, 76.1MB) *
  Poured from bottle on 2020-05-21 at 13:31:10
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/php.rb
License: PHP-3.01
==> Dependencies
Build: httpd, pkg-config
Required: apr, apr-util, argon2, aspell, autoconf, curl-openssl, freetds, gd, gettext, glib, gmp, icu4c, krb5, libffi, libpq, libsodium, libzip, oniguruma, openldap, openssl@1.1, pcre2, sqlite, tidy-html5, unixodbc
==> Options
--HEAD
	Install HEAD version
==> Caveats
To enable PHP in Apache add the following to httpd.conf and restart Apache:
    LoadModule php7_module /usr/local/opt/php/lib/httpd/modules/libphp7.so

    <FilesMatch \.php$>
        SetHandler application/x-httpd-php
    </FilesMatch>

Finally, check DirectoryIndex includes index.php
    DirectoryIndex index.php index.html

The php.ini and php-fpm.ini file can be found in:
    /usr/local/etc/php/7.4/

To have launchd start php now and restart at login:
  brew services start php
Or, if you don't want/need a background service you can just run:
  php-fpm
==> Analytics
install: 50,645 (30 days), 156,898 (90 days), 559,924 (365 days)
install-on-request: 49,482 (30 days), 152,600 (90 days), 528,271 (365 days)
build-error: 0 (30 days)</pre>
</details>
<details>
<summary>brew info openssl</summary>
<pre>openssl@1.1: stable 1.1.1g (bottled) [keg-only]
Cryptography and SSL/TLS Toolkit
https://openssl.org/
/usr/local/Cellar/openssl@1.1/1.1.1g (8,059 files, 18MB)
  Poured from bottle on 2020-05-21 at 13:17:52
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/openssl@1.1.rb
License: OpenSSL
==> Caveats
A CA file has been bootstrapped using certificates from the system
keychain. To add additional certificates, place .pem files in
  /usr/local/etc/openssl@1.1/certs

and run
  /usr/local/opt/openssl@1.1/bin/c_rehash

openssl@1.1 is keg-only, which means it was not symlinked into /usr/local,
because macOS provides LibreSSL.

If you need to have openssl@1.1 first in your PATH run:
  echo 'export PATH="/usr/local/opt/openssl@1.1/bin:$PATH"' >> ~/.zshrc

For compilers to find openssl@1.1 you may need to set:
  export LDFLAGS="-L/usr/local/opt/openssl@1.1/lib"
  export CPPFLAGS="-I/usr/local/opt/openssl@1.1/include"

==> Analytics
install: 567,701 (30 days), 1,743,070 (90 days), 7,184,526 (365 days)
install-on-request: 62,658 (30 days), 205,696 (90 days), 913,283 (365 days)
build-error: 0 (30 days)</pre>
</details>
<details>
<summary>openssl version -a</summary>
<pre>LibreSSL 2.8.3
built on: date not available
platform: information not available
options:  bn(64,64) rc4(16x,int) des(idx,cisc,16,int) blowfish(idx) 
compiler: information not available
OPENSSLDIR: "/private/etc/ssl"</pre>
</details>
<details>
<summary>openssl ciphers</summary>
<pre>ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-CHACHA20-POLY1305:GOST2012256-GOST89-GOST89:DHE-RSA-CAMELLIA256-SHA256:DHE-RSA-CAMELLIA256-SHA:GOST2001-GOST89-GOST89:AES256-GCM-SHA384:AES256-SHA256:AES256-SHA:CAMELLIA256-SHA256:CAMELLIA256-SHA:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-CAMELLIA128-SHA256:DHE-RSA-CAMELLIA128-SHA:AES128-GCM-SHA256:AES128-SHA256:AES128-SHA:CAMELLIA128-SHA256:CAMELLIA128-SHA:ECDHE-RSA-RC4-SHA:ECDHE-ECDSA-RC4-SHA:RC4-SHA:RC4-MD5:ECDHE-RSA-DES-CBC3-SHA:ECDHE-ECDSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:DES-CBC3-SHA</pre>
</details>
<details>
<summary>sudo nginx -t</summary>
<pre>nginx: the configuration file /usr/local/etc/nginx/nginx.conf syntax is ok
nginx: configuration file /usr/local/etc/nginx/nginx.conf test is successful</pre>
</details>
<details>
<summary>which -a php-fpm</summary>
<pre>/usr/sbin/php-fpm</pre>
</details>
<details>
<summary>/usr/local/opt/php/sbin/php-fpm -v</summary>
<pre>PHP 7.4.6 (fpm-fcgi) (built: May 14 2020 10:38:46)
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Xdebug v2.9.6, Copyright (c) 2002-2020, by Derick Rethans
    with Zend OPcache v7.4.6, Copyright (c), by Zend Technologies</pre>
</details>
<details>
<summary>sudo /usr/local/opt/php/sbin/php-fpm -y /usr/local/etc/php/7.4/php-fpm.conf --test</summary>
<pre>[13-Sep-2020 09:32:29] NOTICE: configuration file /usr/local/etc/php/7.4/php-fpm.conf test is successful</pre>
</details>
<details>
<summary>ls -al ~/Library/LaunchAgents | grep homebrew</summary>
<pre>-rwxr-xr-x   1 nick  staff   551 Nov 25  2019 homebrew.mxcl.mysql@5.7.plist
-rw-r--r--   1 nick  staff   628 May 21 22:40 homebrew.mxcl.php.plist</pre>
</details>
<details>
<summary>ls -al /Library/LaunchAgents | grep homebrew</summary>
<pre></pre>
</details>
<details>
<summary>ls -al /Library/LaunchDaemons | grep homebrew</summary>
<pre>-rw-r--r--   1 root  admin   657 Jul 20 13:41 homebrew.mxcl.dnsmasq.plist
-rw-r--r--   1 root  admin   571 Jul 20 13:42 homebrew.mxcl.nginx.plist
-rw-r--r--   1 root  admin   628 Jul 20 13:42 homebrew.mxcl.php.plist</pre>
</details>

**Comment by isaaclubow** [comment]
I have the same problem. Watching here for any ideas.

**Comment by isaaclubow** [comment]
@nickbasham After noticing that WP attempts to redirect in the case of a mismatch between PHP_SELF and the request, I solved this by adding the following to my `LocalValetDriver.php`:
```
/**
 * Get the fully resolved path to the application's front controller.
 *
 * @param  string $sitePath
 * @param  string $siteName
 * @param  string $uri
 * @return string
 */
public function frontControllerPath( $sitePath, $siteName, $uri ) {
	$_SERVER['PHP_SELF']    = '/index.php';
	$_SERVER['SERVER_ADDR'] = '127.0.0.1';
	$_SERVER['SERVER_NAME'] = $_SERVER['HTTP_HOST'];
	return parent::frontControllerPath(
		$sitePath,
		$siteName,
		$_SERVER['PHP_SELF']
	);
}
```
This sets `PHP_SELF` to `/index.php` which matches what I was finding on my (correctly working, with regard to 404s) production installs.

**Comment by nickbasham-grayloon** [comment]
@isaaclubow This is great, thanks! Just tested this out and it's working perfectly. It would be great if you could submit this as a PR and see if you can get `WordpressValetDriver.php` updated. I'm sure there are other Wordpress devs who have run into this, and are either banging their head against a wall, just dealing with it, or jumping to another tool like Local.

Thanks, again!

**Comment by nickbasham** [comment]
@isaaclubow This is great, thanks! Just tested this out and it's working perfectly. It would be great if you could submit this as a PR and see if you can get WordpressValetDriver.php updated. I'm sure there are other Wordpress devs who have run into this, and are either banging their head against a wall, just dealing with it, or jumping to another tool like Local.

Thanks, again!

**Comment by isaaclubow** [comment]
@nickbasham Thanks, but I'm just discovering that now admin Ajax requests are 404ing too - so, there are caveats to hard-coding `index.php`. If I can find the method WP uses to fetch the values it's comparing, I can duplicate/adapt them to this class.

**Comment by isaaclubow** [comment]
@nickbasham OK, this version is working perfectly for me so far (with minimal testing, but no hard-coding, shows 404s correctly, and doesn't break Ajax calls):
```
/**
 * Get the fully resolved path to the application's front controller.
 *
 * @param  string $sitePath
 * @param  string $siteName
 * @param  string $uri
 * @return string
 */
public function frontControllerPath( $sitePath, $siteName, $uri ) {
	$_SERVER['PHP_SELF'] = $_SERVER['SCRIPT_NAME'];
	return parent::frontControllerPath(
		$sitePath,
		$siteName,
		$_SERVER['PHP_SELF']
	);
}
```

**Comment by nickbasham** [comment]
Ah, shoot, yeah, you're right, I'm seeing that, too.

**Comment by adamtomat** [comment]
Also running into this issue. For me, it mainly happens when there's a missing asset.

Because the asset was missing, the `isStaticFile` method was returning `false` because it physically didn't exist on disk. It _is_ a static file, it's just missing.

In the short-term I've updated the `isStaticFile` so it doesn't check the disk for any requests with an extension (e.g. `.png`) and therefore will 404.

```php
/**
     * Determine if the incoming request is for a static file.
     *
     * @param  string       $sitePath
     * @param  string       $siteName
     * @param  string       $uri
     * @return string|false
     */
    public function isStaticFile($sitePath, $siteName, $uri)
    {
        $staticFilePath = $sitePath . '/site/web' . $uri;

        $extension = pathinfo($staticFilePath, PATHINFO_EXTENSION);

        if ($this->isActualFile($staticFilePath) || $extension !== '') {
            return $staticFilePath;
        }

        return false;
    }
```
