### ISSUE TITLE
Changing TLD's trigger warnings each time

### ISSUE THREAD

**Issue by kupoback** [laravel/valet#984]
## Clear description of your problem
Every time I switch my tld, for each site I have registered with Valet, I receive this warning:

```
Warning: file_get_contents(/Users/mak/.config/valet/Nginx/wp-boilerplate.test.app): failed to open stream: No such file or directory in /Users/mak/.composer/vendor/laravel/valet/cli/Valet/Filesystem.php on line 112

Call Stack:
    0.0026     505704   1. {main}() /Users/mak/.composer/vendor/laravel/valet/cli/valet.php:0
    0.0818    2962344   2. Silly\Application->run(???, ???) /Users/mak/.composer/vendor/laravel/valet/cli/valet.php:591
    0.0998    3206008   3. Silly\Application->doRun(???, ???) /Users/mak/.composer/vendor/symfony/console/Application.php:147
    0.1024    3282920   4. Silly\Application->doRunCommand(???, ???, ???) /Users/mak/.composer/vendor/symfony/console/Application.php:271
    0.1025    3282920   5. Silly\Command\Command->run(???, ???) /Users/mak/.composer/vendor/symfony/console/Application.php:1000
    0.1032    3284752   6. Silly\Application->Silly\{closure:/Users/mak/.composer/vendor/mnapoli/silly/src/Application.php:72-103}(???, ???) /Users/mak/.composer/vendor/symfony/console/Command/Command.php:253
    0.1056    3380512   7. Invoker\Invoker->call(???, ???) /Users/mak/.composer/vendor/mnapoli/silly/src/Application.php:95
    0.1056    3381072   8. call_user_func_array:{/Users/mak/.composer/vendor/php-di/invoker/src/Invoker.php:83}(???, ???) /Users/mak/.composer/vendor/php-di/invoker/src/Invoker.php:83
    0.1056    3381088   9. Silly\Application->{closure:/Users/mak/.composer/vendor/laravel/valet/cli/valet.php:78-94}(???) /Users/mak/.composer/vendor/php-di/invoker/src/Invoker.php:83
    9.8970    3924760  10. Facade::resecureForNewTld(???, ???) /Users/mak/.composer/vendor/laravel/valet/cli/valet.php:89
    9.8970    3925136  11. Facade::__callStatic(???, ???) /Users/mak/.composer/vendor/laravel/valet/cli/valet.php:89
    9.8979    3925408  12. Valet\Site->resecureForNewTld(???, ???) /Users/mak/.composer/vendor/laravel/valet/cli/includes/facades.php:28
   14.1866    3926200  13. Valet\Site->getSiteConfigFileContents(???) /Users/mak/.composer/vendor/laravel/valet/cli/Valet/Site.php:342
   14.1867    3927312  14. Valet\Filesystem->get(???) /Users/mak/.composer/vendor/laravel/valet/cli/Valet/Site.php:212
   14.1867    3927312  15. file_get_contents(???) /Users/mak/.composer/vendor/laravel/valet/cli/Valet/Filesystem.php:112
```

## Expected behavior
I prolly shouldn't be getting these warnings?

## Current behavior
See description of problem

## Steps to Reproduce
 On Valet version `2.11.0`, macOS `10.15.7`, Composer `1.10.13`, php `7.4.11`
1. Park in a sites folder
2. Setup `valet secure` for some sites within the folder
3. Use `valet tld app` from `valet tld test` Starts happening
4. Use `valet tld test` from `valet tld app` Happens again

## Diagnosis

<details>
<summary>sw_vers</summary>
<pre>ProductName:	Mac OS X
ProductVersion:	10.15.7
BuildVersion:	19H2</pre>
</details>
<details>
<summary>valet --version</summary>
<pre>Laravel Valet 2.11.0</pre>
</details>
<details>
<summary>cat ~/.config/valet/config.json</summary>
<pre>{
    "tld": "app",
    "paths": [
        "/Users/mak/.config/valet/Sites",
        "/Users/mak/Sites"
    ]
}</pre>
</details>
<details>
<summary>cat ~/.composer/composer.json</summary>
<pre>{
    "require": {
        "laravel/valet": "^2.3",
        "laravel/installer": "^2.1"
    }
}</pre>
</details>
<details>
<summary>composer global diagnose</summary>
<pre>Changed current directory to /Users/mak/.composer
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys: FAIL
Missing pubkey for tags verification
Missing pubkey for dev verification
Run composer self-update --update-keys to set them up
Checking composer version: OK
Composer version: 1.10.13
PHP version: 7.4.11
PHP binary path: /usr/local/Cellar/php/7.4.11/bin/php
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020</pre>
</details>
<details>
<summary>composer global outdated</summary>
<pre>Changed current directory to /Users/mak/.composer
guzzlehttp/guzzle         6.5.5   ~ 7.1.1  Guzzle is a PHP HTTP client library
guzzlehttp/promises       v1.3.1  ! 1.4.0  Guzzle promises library
guzzlehttp/psr7           1.6.1   ! 1.7.0  PSR-7 message implementation that also provides common utility methods
illuminate/container      v7.26.0 ~ v8.9.0 The Illuminate Container package.
illuminate/contracts      v7.26.0 ~ v8.9.0 The Illuminate Contracts package.
laravel/installer         v2.3.0  ~ v4.0.5 Laravel application installer.
symfony/console           v4.4.11 ~ v5.1.7 Symfony Console Component
symfony/filesystem        v4.4.11 ~ v5.1.7 Symfony Filesystem Component
symfony/process           v4.4.11 ~ v5.1.7 Symfony Process Component
symfony/service-contracts v2.1.3  ! v2.2.0 Generic abstractions related to writing services
symfony/var-dumper        v5.1.3  ! v5.1.7 Symfony mechanism for exploring and dumping PHP variables
tightenco/collect         v7.25.0 ~ v8.0.4 Collect - Illuminate Collections as a separate package.</pre>
</details>
<details>
<summary>ls -al /etc/sudoers.d/</summary>
<pre>total 16
drwxr-xr-x   4 root  wheel   128 Sep 28 18:15 .
drwxr-xr-x  85 root  wheel  2720 Oct  2 10:58 ..
-rw-r--r--   1 root  wheel    80 May 23  2019 brew
-rw-r--r--   1 root  wheel    83 May 23  2019 valet</pre>
</details>
<details>
<summary>brew config</summary>
<pre>HOMEBREW_VERSION: 2.5.5
ORIGIN: https://github.com/Homebrew/brew
HEAD: 0c7a7188c15901cbe724861df0724cab08c8176d
Last commit: 20 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: a705f680fe65a76a305cadcb4a15d078b0bb94d6
Core tap last commit: 7 days ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit kabylake
Clang: 12.0 build 1200
Git: 2.28.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 1.8.0_265
macOS: 10.15.7-x86_64
CLT: 12.0.0.0.1.1599194153
Xcode: N/A</pre>
</details>
<details>
<summary>brew services list</summary>
<pre>Name          Status  User Plist
dnsmasq       started root /Library/LaunchDaemons/homebrew.mxcl.dnsmasq.plist
httpd         stopped      
mailhog       started mak  /Users/mak/Library/LaunchAgents/homebrew.mxcl.mailhog.plist
mariadb       started mak  /Users/mak/Library/LaunchAgents/homebrew.mxcl.mariadb.plist
nginx         started root /Library/LaunchDaemons/homebrew.mxcl.nginx.plist
php           started root /Library/LaunchDaemons/homebrew.mxcl.php.plist
php@7.3       stopped      
postgresql    started mak  /Users/mak/Library/LaunchAgents/homebrew.mxcl.postgresql.plist
postgresql@11 stopped      
unbound       stopped</pre>
</details>
<details>
<summary>brew list --versions | grep -E "(php|nginx|dnsmasq|mariadb|mysql|mailhog|openssl)(@\d\..*)?\s"</summary>
<pre>curl-openssl 7.72.0_1
dnsmasq 2.82
mailhog 1.0.0
mariadb 10.5.5
nginx 1.19.3
openssl@1.1 1.1.1g
php 7.4.11
php@7.3 7.3.22</pre>
</details>
<details>
<summary>brew outdated</summary>
<pre>dart-lang/dart/dart
sass/sass/sass</pre>
</details>
<details>
<summary>php -v</summary>
<pre>PHP 7.4.11 (cli) (built: Oct  1 2020 23:30:54) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Xdebug v2.9.0, Copyright (c) 2002-2019, by Derick Rethans
    with Zend OPcache v7.4.11, Copyright (c), by Zend Technologies</pre>
</details>
<details>
<summary>which -a php</summary>
<pre>/usr/local/bin/php
/usr/local/bin/php
/usr/bin/php</pre>
</details>
<details>
<summary>php --ini</summary>
<pre>Configuration File (php.ini) Path: /usr/local/etc/php/7.4
Loaded Configuration File:         /usr/local/etc/php/7.4/php.ini
Scan for additional .ini files in: /usr/local/etc/php/7.4/conf.d
Additional .ini files parsed:      /usr/local/etc/php/7.4/conf.d/ext-debug.ini,
/usr/local/etc/php/7.4/conf.d/ext-opcache.ini,
/usr/local/etc/php/7.4/conf.d/php-memory-limits.ini</pre>
</details>
<details>
<summary>nginx -v</summary>
<pre>nginx version: nginx/1.19.3</pre>
</details>
<details>
<summary>curl --version</summary>
<pre>curl 7.64.1 (x86_64-apple-darwin19.0) libcurl/7.64.1 (SecureTransport) LibreSSL/2.8.3 zlib/1.2.11 nghttp2/1.39.2
Release-Date: 2019-03-27
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS GSS-API HTTP2 HTTPS-proxy IPv6 Kerberos Largefile libz MultiSSL NTLM NTLM_WB SPNEGO SSL UnixSockets</pre>
</details>
<details>
<summary>php --ri curl</summary>
<pre>curl

cURL support => enabled
cURL Information => 7.72.0
Age => 7
Features
AsynchDNS => Yes
CharConv => No
Debug => No
GSS-Negotiate => No
IDN => No
IPv6 => Yes
krb4 => No
Largefile => Yes
libz => Yes
NTLM => Yes
NTLMWB => Yes
SPNEGO => Yes
SSL => Yes
SSPI => No
TLS-SRP => Yes
HTTP2 => Yes
GSSAPI => Yes
KERBEROS5 => Yes
UNIX_SOCKETS => Yes
PSL => No
HTTPS_PROXY => Yes
MULTI_SSL => No
BROTLI => Yes
Protocols => dict, file, ftp, ftps, gopher, http, https, imap, imaps, ldap, ldaps, pop3, pop3s, rtmp, rtsp, scp, sftp, smb, smbs, smtp, smtps, telnet, tftp
Host => x86_64-apple-darwin19.5.0
SSL Version => OpenSSL/1.1.1g
ZLib Version => 1.2.11
libSSH Version => libssh2/1.9.0

Directive => Local Value => Master Value
curl.cainfo => no value => no value</pre>
</details>
<details>
<summary>~/.composer/vendor/laravel/valet/bin/ngrok version</summary>
<pre>ngrok version 2.3.35</pre>
</details>
<details>
<summary>ls -al ~/.ngrok2</summary>
<pre>ls: /Users/mak/.ngrok2: No such file or directory</pre>
</details>
<details>
<summary>brew info nginx</summary>
<pre>nginx: stable 1.19.3 (bottled), HEAD
HTTP(S) server and reverse proxy, and IMAP/POP3 proxy server
https://nginx.org/
/usr/local/Cellar/nginx/1.19.3 (25 files, 2.2MB) *
  Poured from bottle on 2020-10-02 at 15:03:52
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/nginx.rb
License: BSD-2-Clause
==> Dependencies
Required: openssl@1.1, pcre
==> Options
--HEAD
	Install HEAD version
==> Caveats
Docroot is: /usr/local/var/www

The default port has been set in /usr/local/etc/nginx/nginx.conf to 8080 so that
nginx can run without sudo.

nginx will load all files in /usr/local/etc/nginx/servers/.

To have launchd start nginx now and restart at login:
  brew services start nginx
Or, if you don't want/need a background service you can just run:
  nginx
==> Analytics
install: 32,094 (30 days), 102,487 (90 days), 409,374 (365 days)
install-on-request: 31,526 (30 days), 100,534 (90 days), 397,530 (365 days)
build-error: 0 (30 days)</pre>
</details>
<details>
<summary>brew info php</summary>
<pre>php: stable 7.4.11 (bottled), HEAD
General-purpose scripting language
https://www.php.net/
/usr/local/Cellar/php/7.4.11 (497 files, 72.3MB) *
  Poured from bottle on 2020-10-02 at 15:03:12
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/php.rb
License: PHP-3.01
==> Dependencies
Build: httpd, pkg-config
Required: apr, apr-util, argon2, aspell, autoconf, curl-openssl, freetds, gd, gettext, glib, gmp, icu4c, krb5, libffi, libpq, libsodium, libzip, oniguruma, openldap, openssl@1.1, pcre2, sqlite, tidy-html5, unixodbc
==> Options
--HEAD
	Install HEAD version
==> Caveats
To enable PHP in Apache add the following to httpd.conf and restart Apache:
    LoadModule php7_module /usr/local/opt/php/lib/httpd/modules/libphp7.so

    <FilesMatch \.php$>
        SetHandler application/x-httpd-php
    </FilesMatch>

Finally, check DirectoryIndex includes index.php
    DirectoryIndex index.php index.html

The php.ini and php-fpm.ini file can be found in:
    /usr/local/etc/php/7.4/

To have launchd start php now and restart at login:
  brew services start php
Or, if you don't want/need a background service you can just run:
  php-fpm
==> Analytics
install: 50,574 (30 days), 161,328 (90 days), 568,834 (365 days)
install-on-request: 49,517 (30 days), 157,377 (90 days), 538,858 (365 days)
build-error: 0 (30 days)</pre>
</details>
<details>
<summary>brew info openssl</summary>
<pre>openssl@1.1: stable 1.1.1g (bottled) [keg-only]
Cryptography and SSL/TLS Toolkit
https://openssl.org/
/usr/local/Cellar/openssl@1.1/1.1.1g (8,059 files, 18MB)
  Poured from bottle on 2020-04-22 at 11:23:47
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/openssl@1.1.rb
License: OpenSSL
==> Caveats
A CA file has been bootstrapped using certificates from the system
keychain. To add additional certificates, place .pem files in
  /usr/local/etc/openssl@1.1/certs

and run
  /usr/local/opt/openssl@1.1/bin/c_rehash

openssl@1.1 is keg-only, which means it was not symlinked into /usr/local,
because macOS provides LibreSSL.

If you need to have openssl@1.1 first in your PATH run:
  echo 'export PATH="/usr/local/opt/openssl@1.1/bin:$PATH"' >> ~/.zshrc

For compilers to find openssl@1.1 you may need to set:
  export LDFLAGS="-L/usr/local/opt/openssl@1.1/lib"
  export CPPFLAGS="-I/usr/local/opt/openssl@1.1/include"

For pkg-config to find openssl@1.1 you may need to set:
  export PKG_CONFIG_PATH="/usr/local/opt/openssl@1.1/lib/pkgconfig"

==> Analytics
install: 484,931 (30 days), 1,655,921 (90 days), 6,967,703 (365 days)
install-on-request: 58,962 (30 days), 192,997 (90 days), 913,928 (365 days)
build-error: 0 (30 days)</pre>
</details>
<details>
<summary>openssl version -a</summary>
<pre>LibreSSL 2.8.3
built on: date not available
platform: information not available
options:  bn(64,64) rc4(16x,int) des(idx,cisc,16,int) blowfish(idx) 
compiler: information not available
OPENSSLDIR: "/private/etc/ssl"</pre>
</details>
<details>
<summary>openssl ciphers</summary>
<pre>ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-CHACHA20-POLY1305:GOST2012256-GOST89-GOST89:DHE-RSA-CAMELLIA256-SHA256:DHE-RSA-CAMELLIA256-SHA:GOST2001-GOST89-GOST89:AES256-GCM-SHA384:AES256-SHA256:AES256-SHA:CAMELLIA256-SHA256:CAMELLIA256-SHA:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-CAMELLIA128-SHA256:DHE-RSA-CAMELLIA128-SHA:AES128-GCM-SHA256:AES128-SHA256:AES128-SHA:CAMELLIA128-SHA256:CAMELLIA128-SHA:ECDHE-RSA-RC4-SHA:ECDHE-ECDSA-RC4-SHA:RC4-SHA:RC4-MD5:ECDHE-RSA-DES-CBC3-SHA:ECDHE-ECDSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:DES-CBC3-SHA</pre>
</details>
<details>
<summary>sudo nginx -t</summary>
<pre>nginx: the configuration file /usr/local/etc/nginx/nginx.conf syntax is ok
nginx: configuration file /usr/local/etc/nginx/nginx.conf test is successful</pre>
</details>
<details>
<summary>which -a php-fpm</summary>
<pre>/usr/local/sbin/php-fpm
/usr/sbin/php-fpm</pre>
</details>
<details>
<summary>/usr/local/opt/php/sbin/php-fpm -v</summary>
<pre>PHP 7.4.11 (fpm-fcgi) (built: Oct  1 2020 23:31:04)
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Xdebug v2.9.0, Copyright (c) 2002-2019, by Derick Rethans
    with Zend OPcache v7.4.11, Copyright (c), by Zend Technologies</pre>
</details>
<details>
<summary>sudo /usr/local/opt/php/sbin/php-fpm -y /usr/local/etc/php/7.4/php-fpm.conf --test</summary>
<pre>[09-Oct-2020 12:19:06] NOTICE: configuration file /usr/local/etc/php/7.4/php-fpm.conf test is successful</pre>
</details>
<details>
<summary>ls -al ~/Library/LaunchAgents | grep homebrew</summary>
<pre>-rw-r--r--   1 mak  staff   581 Jun  3  2019 homebrew.mxcl.mailhog.plist
-rw-r--r--   1 mak  staff   541 Aug 20 10:44 homebrew.mxcl.mariadb.plist
-rw-r--r--   1 mak  staff   571 Jan 13  2020 homebrew.mxcl.nginx.plist
-rw-r--r--   1 mak  staff   719 Jun  4 11:03 homebrew.mxcl.postgresql.plist</pre>
</details>
<details>
<summary>ls -al /Library/LaunchAgents | grep homebrew</summary>
<pre></pre>
</details>
<details>
<summary>ls -al /Library/LaunchDaemons | grep homebrew</summary>
<pre>-rw-r--r--   1 root  admin   657 Oct  9 12:05 homebrew.mxcl.dnsmasq.plist
-rw-r--r--   1 root  admin   571 Oct  9 12:06 homebrew.mxcl.nginx.plist
-rw-r--r--   1 root  admin   628 Oct  9 12:05 homebrew.mxcl.php.plist</pre>
</details>

**Comment by drbyte** [comment]
> Warning: file_get_contents(/Users/mak/.config/valet/Nginx/wp-boilerplate.test.app): failed to open stream

This might be a bug.

Looks like it's trying to read the combination of both TLDs in the config filename `.test.app`.
Fixing it involves also still making sure the various shared functions still interact correctly when passing information back and forth.

**Comment by kupoback** [comment]
@drbyte Any updates on this?
