### ISSUE TITLE
Installing Custom Certificate on Laravel Valet (For using an external service)

### ISSUE THREAD

**Issue by spooksie** [laravel/valet#985]
I need to install a trusted certificate for Laravel Valet (For working locally & it isnt for SSL), I've installed it on my live Ubuntu servers with no problems.

**Example on how I installed on Ubuntu:**

 1. Installed the certificate inside this location `/usr/local/share/ca-certificates/`
 2. Then ran `sudo update-ca-certificates`
 3. `sudo reboot`
 4. Then it works a charm

**Trying to do the same with Lavavel Valet on local**

 1.  Installed the certificate inside this location `Users/<user>/.config/valet/Certificates/`
 2. Restart valet
 3. Doesn't work

> Is there an equivalent of `update-ca-certificates` for MacOs or Valet?

I've also installed the certificate on the MacOs keychain with no luck. 

Any suggestions?

**Comment by drbyte** [comment]
If you run `brew info openssl` you will get a message with instructions like the following:

```
To add additional certificates, place .pem files in
  /usr/local/etc/openssl@1.1/certs

and run
  /usr/local/opt/openssl@1.1/bin/c_rehash
```

I'm pretty sure this is essentially the same as the `update-ca-certificates` on Ubuntu.

**Comment by spooksie** [comment]
> If you run `brew info openssl` you will get a message with instructions like the following:
> 
> ```
> To add additional certificates, place .pem files in
>   /usr/local/etc/openssl@1.1/certs
> 
> and run
>   /usr/local/opt/openssl@1.1/bin/c_rehash
> ```
> 
> I'm pretty sure this is essentially the same as the `update-ca-certificates` on Ubuntu.

Its not for a SSL and needed to use a service. Its only a .CERT file.

**Comment by spooksie** [comment]
> If you run `brew info openssl` you will get a message with instructions like the following:
> 
> ```
> To add additional certificates, place .pem files in
>   /usr/local/etc/openssl@1.1/certs
> 
> and run
>   /usr/local/opt/openssl@1.1/bin/c_rehash
> ```
> 
> I'm pretty sure this is essentially the same as the `update-ca-certificates` on Ubuntu.

Thanks for the reply, it worked a treat.

**Comment by drbyte** [comment]
> Thanks for the reply, it worked a treat.

Cool. Thanks for confirming.

You can click Close below if this topic is resolved.

**Comment by nhattay** [comment]
> If you run `brew info openssl` you will get a message with instructions like the following:
> 
> ```
> To add additional certificates, place .pem files in
>   /usr/local/etc/openssl@1.1/certs
> 
> and run
>   /usr/local/opt/openssl@1.1/bin/c_rehash
> ```
> 
> I'm pretty sure this is essentially the same as the `update-ca-certificates` on Ubuntu.

I've trie this but it it doesn't work. It works fine when running `curl hostname.com` but it doesn't work when connecting the host using Laravel. Is there any additional configuration for this?
