### ISSUE TITLE
502 Bad Gateway nginx/1.19.4  big sur update

### ISSUE THREAD

**Issue by sultansawalha** [laravel/valet#994]
tried to fresh install and to increase the buffers to no avail, any ideas are much appreciated

## Diagnosis
<details>
<summary>sw_vers</summary>
<pre>ProductName:	macOS
ProductVersion:	11.0.1
BuildVersion:	20B29</pre>
</details>
<details>
<summary>valet --version</summary>
<pre>Laravel Valet 2.13.1</pre>
</details>
<details>
<summary>cat ~/.config/valet/config.json</summary>
<pre>{
    "tld": "test",
    "paths": [
        "/Users/sultan/.config/valet/Sites",
        "/Users/sultan/Desktop/site",
        "/Users/sultan"
    ]
}</pre>
</details>
<details>
<summary>cat ~/.composer/composer.json</summary>
<pre>{
    "require": {
        "laravel/valet": "^2.13"
    }
}</pre>
</details>
<details>
<summary>composer global diagnose</summary>
<pre>Changed current directory to /Users/sultan/.composer
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 2.0.7
PHP version: 7.4.12
PHP binary path: /usr/local/Cellar/php/7.4.12/bin/php
OpenSSL version: OpenSSL 1.1.1h  22 Sep 2020
cURL version: 7.73.0 libz 1.2.11 ssl OpenSSL/1.1.1h
zip extension: OK</pre>
</details>
<details>
<summary>composer global outdated</summary>
<pre>Changed current directory to /Users/sultan/.composer</pre>
</details>
<details>
<summary>ls -al /etc/sudoers.d/</summary>
<pre>total 0
drwxr-xr-x   2 root  wheel    64  1 Jan  2020 .
drwxr-xr-x  86 root  wheel  2752 18 Nov 21:18 ..</pre>
</details>
<details>
<summary>brew config</summary>
<pre>HOMEBREW_VERSION: 2.5.11
ORIGIN: https://github.com/Homebrew/brew
HEAD: 07b3aa69f8dc5098437cf2562864558bae2d45aa
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: c67b17cb80b042825f00f1768c422a1df637ad4b
Core tap last commit: 16 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit kabylake
Clang: 12.0 build 1200
Git: 2.24.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.0.1-x86_64
CLT: N/A
Xcode: 12.2</pre>
</details>
<details>
<summary>brew services list</summary>
<pre>Name          Status  User Plist
dnsmasq       started root /Library/LaunchDaemons/homebrew.mxcl.dnsmasq.plist
mysql@5.7     stopped      
nginx         started root /Library/LaunchDaemons/homebrew.mxcl.nginx.plist
php           stopped      
php@7.2       started root /Library/LaunchDaemons/homebrew.mxcl.php@7.2.plist
php@7.3       stopped      
valet-php@7.1 stopped      
valet-php@7.2 stopped</pre>
</details>
<details>
<summary>brew list --versions | grep -E "(php|nginx|dnsmasq|mariadb|mysql|mailhog|openssl)(@\d\..*)?\s"</summary>
<pre>curl-openssl 7.73.0
dnsmasq 2.82
mysql@5.7 5.7.32
nginx 1.19.4
openssl@1.1 1.1.1h
php 7.4.12
php@7.2 7.2.33
php@7.3 7.3.24
valet-php@7.1 7.1.33_5
valet-php@7.2 7.2.34_1</pre>
</details>
<details>
<summary>brew outdated</summary>
<pre></pre>
</details>
<details>
<summary>php -v</summary>
<pre>PHP 7.4.12 (cli) (built: Nov 14 2020 22:23:58) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies</pre>
</details>
<details>
<summary>which -a php</summary>
<pre>/usr/local/opt/php@7.4/bin/php
/usr/local/opt/php@7.2/bin/php
/usr/local/bin/php
/usr/bin/php</pre>
</details>
<details>
<summary>php --ini</summary>
<pre>Configuration File (php.ini) Path: /usr/local/etc/php/7.4
Loaded Configuration File:         (none)
Scan for additional .ini files in: /usr/local/etc/php/7.4/conf.d
Additional .ini files parsed:      /usr/local/etc/php/7.4/conf.d/php-memory-limits.ini</pre>
</details>
<details>
<summary>nginx -v</summary>
<pre>nginx version: nginx/1.19.4</pre>
</details>
<details>
<summary>curl --version</summary>
<pre>curl 7.64.1 (x86_64-apple-darwin20.0) libcurl/7.64.1 (SecureTransport) LibreSSL/2.8.3 zlib/1.2.11 nghttp2/1.41.0
Release-Date: 2019-03-27
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS GSS-API HTTP2 HTTPS-proxy IPv6 Kerberos Largefile libz MultiSSL NTLM NTLM_WB SPNEGO SSL UnixSockets</pre>
</details>
<details>
<summary>php --ri curl</summary>
<pre>curl

cURL support => enabled
cURL Information => 7.73.0
Age => 7
Features
AsynchDNS => Yes
CharConv => No
Debug => No
GSS-Negotiate => No
IDN => No
IPv6 => Yes
krb4 => No
Largefile => Yes
libz => Yes
NTLM => Yes
NTLMWB => Yes
SPNEGO => Yes
SSL => Yes
SSPI => No
TLS-SRP => Yes
HTTP2 => Yes
GSSAPI => Yes
KERBEROS5 => Yes
UNIX_SOCKETS => Yes
PSL => No
HTTPS_PROXY => Yes
MULTI_SSL => No
BROTLI => Yes
Protocols => dict, file, ftp, ftps, gopher, http, https, imap, imaps, ldap, ldaps, mqtt, pop3, pop3s, rtmp, rtsp, scp, sftp, smb, smbs, smtp, smtps, telnet, tftp
Host => x86_64-apple-darwin19.6.0
SSL Version => OpenSSL/1.1.1h
ZLib Version => 1.2.11
libSSH Version => libssh2/1.9.0

Directive => Local Value => Master Value
curl.cainfo => no value => no value</pre>
</details>
<details>
<summary>~/.composer/vendor/laravel/valet/bin/ngrok version</summary>
<pre>ngrok version 2.3.35</pre>
</details>
<details>
<summary>ls -al ~/.ngrok2</summary>
<pre>ls: /Users/sultan/.ngrok2: No such file or directory</pre>
</details>
<details>
<summary>brew info nginx</summary>
<pre>nginx: stable 1.19.4 (bottled), HEAD
HTTP(S) server and reverse proxy, and IMAP/POP3 proxy server
https://nginx.org/
/usr/local/Cellar/nginx/1.19.4 (25 files, 2.2MB) *
  Poured from bottle on 2020-11-18 at 21:18:17
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/nginx.rb
License: BSD-2-Clause
==> Dependencies
Required: openssl@1.1, pcre
==> Options
--HEAD
	Install HEAD version
==> Caveats
Docroot is: /usr/local/var/www

The default port has been set in /usr/local/etc/nginx/nginx.conf to 8080 so that
nginx can run without sudo.

nginx will load all files in /usr/local/etc/nginx/servers/.

To have launchd start nginx now and restart at login:
  brew services start nginx
Or, if you don't want/need a background service you can just run:
  nginx
==> Analytics
install: 48,219 (30 days), 116,539 (90 days), 438,594 (365 days)
install-on-request: 47,455 (30 days), 114,612 (90 days), 426,609 (365 days)
build-error: 0 (30 days)</pre>
</details>
<details>
<summary>brew info php</summary>
<pre>php: stable 7.4.12 (bottled), HEAD
General-purpose scripting language
https://www.php.net/
/usr/local/Cellar/php/7.4.12 (497 files, 72.3MB)
  Poured from bottle on 2020-11-18 at 11:37:00
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/php.rb
License: PHP-3.01
==> Dependencies
Build: httpd, pkg-config
Required: apr, apr-util, argon2, aspell, autoconf, curl-openssl, freetds, gd, gettext, glib, gmp, icu4c, krb5, libffi, libpq, libsodium, libzip, oniguruma, openldap, openssl@1.1, pcre2, sqlite, tidy-html5, unixodbc
==> Options
--HEAD
	Install HEAD version
==> Caveats
To enable PHP in Apache add the following to httpd.conf and restart Apache:
    LoadModule php7_module /usr/local/opt/php/lib/httpd/modules/libphp7.so

    <FilesMatch \.php$>
        SetHandler application/x-httpd-php
    </FilesMatch>

Finally, check DirectoryIndex includes index.php
    DirectoryIndex index.php index.html

The php.ini and php-fpm.ini file can be found in:
    /usr/local/etc/php/7.4/

To have launchd start php now and restart at login:
  brew services start php
Or, if you don't want/need a background service you can just run:
  php-fpm
==> Analytics
install: 56,896 (30 days), 157,348 (90 days), 588,751 (365 days)
install-on-request: 55,892 (30 days), 154,298 (90 days), 561,091 (365 days)
build-error: 0 (30 days)</pre>
</details>
<details>
<summary>brew info openssl</summary>
<pre>openssl@1.1: stable 1.1.1h (bottled) [keg-only]
Cryptography and SSL/TLS Toolkit
https://openssl.org/
/usr/local/Cellar/openssl@1.1/1.1.1h (8,067 files, 18.5MB)
  Poured from bottle on 2020-10-19 at 19:51:20
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/openssl@1.1.rb
License: OpenSSL
==> Caveats
A CA file has been bootstrapped using certificates from the system
keychain. To add additional certificates, place .pem files in
  /usr/local/etc/openssl@1.1/certs

and run
  /usr/local/opt/openssl@1.1/bin/c_rehash

openssl@1.1 is keg-only, which means it was not symlinked into /usr/local,
because macOS provides LibreSSL.

If you need to have openssl@1.1 first in your PATH run:
  echo 'export PATH="/usr/local/opt/openssl@1.1/bin:$PATH"' >> /Users/sultan/.bash_profile

For compilers to find openssl@1.1 you may need to set:
  export LDFLAGS="-L/usr/local/opt/openssl@1.1/lib"
  export CPPFLAGS="-I/usr/local/opt/openssl@1.1/include"

For pkg-config to find openssl@1.1 you may need to set:
  export PKG_CONFIG_PATH="/usr/local/opt/openssl@1.1/lib/pkgconfig"

==> Analytics
install: 791,018 (30 days), 1,946,368 (90 days), 7,360,819 (365 days)
install-on-request: 125,871 (30 days), 283,577 (90 days), 1,048,953 (365 days)
build-error: 0 (30 days)</pre>
</details>
<details>
<summary>openssl version -a</summary>
<pre>LibreSSL 2.8.3
built on: date not available
platform: information not available
options:  bn(64,64) rc4(16x,int) des(idx,cisc,16,int) blowfish(idx) 
compiler: information not available
OPENSSLDIR: "/private/etc/ssl"</pre>
</details>
<details>
<summary>openssl ciphers</summary>
<pre>ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-CHACHA20-POLY1305:GOST2012256-GOST89-GOST89:DHE-RSA-CAMELLIA256-SHA256:DHE-RSA-CAMELLIA256-SHA:GOST2001-GOST89-GOST89:AES256-GCM-SHA384:AES256-SHA256:AES256-SHA:CAMELLIA256-SHA256:CAMELLIA256-SHA:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-CAMELLIA128-SHA256:DHE-RSA-CAMELLIA128-SHA:AES128-GCM-SHA256:AES128-SHA256:AES128-SHA:CAMELLIA128-SHA256:CAMELLIA128-SHA:ECDHE-RSA-RC4-SHA:ECDHE-ECDSA-RC4-SHA:RC4-SHA:RC4-MD5:ECDHE-RSA-DES-CBC3-SHA:ECDHE-ECDSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:DES-CBC3-SHA</pre>
</details>
<details>
<summary>sudo nginx -t</summary>
<pre>nginx: the configuration file /usr/local/etc/nginx/nginx.conf syntax is ok
nginx: configuration file /usr/local/etc/nginx/nginx.conf test is successful</pre>
</details>
<details>
<summary>which -a php-fpm</summary>
<pre>/usr/local/opt/php@7.4/sbin/php-fpm
/usr/local/opt/php@7.2/sbin/php-fpm
/usr/local/sbin/php-fpm
/usr/sbin/php-fpm</pre>
</details>
<details>
<summary>/usr/local/opt/php/sbin/php-fpm -v</summary>
<pre>PHP 7.4.12 (fpm-fcgi) (built: Nov 14 2020 22:24:12)
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies</pre>
</details>
<details>
<summary>sudo /usr/local/opt/php/sbin/php-fpm -y /usr/local/etc/php/7.4/php-fpm.conf --test</summary>
<pre>[18-Nov-2020 21:34:23] ERROR: failed to open configuration file '/usr/local/etc/php/7.4/php-fpm.conf': No such file or directory (2)
[18-Nov-2020 21:34:23] ERROR: failed to load configuration file '/usr/local/etc/php/7.4/php-fpm.conf'
[18-Nov-2020 21:34:23] ERROR: FPM initialization failed</pre>
</details>
<details>
<summary>ls -al ~/Library/LaunchAgents | grep homebrew</summary>
<pre></pre>
</details>
<details>
<summary>ls -al /Library/LaunchAgents | grep homebrew</summary>
<pre></pre>
</details>
<details>
<summary>ls -al /Library/LaunchDaemons | grep homebrew</summary>
<pre>-rw-r--r--   1 root  admin   657 18 Nov 21:33 homebrew.mxcl.dnsmasq.plist
-rw-r--r--   1 root  admin   571 18 Nov 21:33 homebrew.mxcl.nginx.plist
-rw-r--r--   1 root  admin   636 18 Nov 21:33 homebrew.mxcl.php@7.2.plist</pre>
</details>

**Comment by drbyte** [comment]
You have multiple PHP versions installed. While that's fine, you've got one linked as primary by homebrew, but a different/older one is the one actually running.

> brew list --versions | grep -E "(php|nginx|dnsmasq|mariadb|mysql|mailhog|openssl)(@\d\..*)?\s"
> curl-openssl 7.73.0
> dnsmasq 2.82
> mysql@5.7 5.7.32
> nginx 1.19.4
> openssl@1.1 1.1.1h
> php 7.4.12
> php@7.2 7.2.33
> php@7.3 7.3.24
> valet-php@7.1 7.1.33_5
> valet-php@7.2 7.2.34_1

Also, you've got "valet-plus" junk leftover in your homebrew taps. Best to remove those. (Or, if you want to use valet-plus, go whole hog to it, and work with them to help support your configuration issues)

> php -v
> PHP 7.4.12 (cli) (built: Nov 14 2020 22:23:58) ( NTS )

Note above how your CLI PHP says it's configured to use 7.4
That's because it's listed first in your environment PATH, as confirmed below:

> which -a php
> /usr/local/opt/php@7.4/bin/php
> /usr/local/opt/php@7.2/bin/php
> /usr/local/bin/php
> /usr/bin/php

(The above shows all "php" binaries accessible by how your PATH is configured to look in each of those directories.)

----

Now we move on to checking which PHP-FPM is linked, since that's what Nginx uses, and your `502 Bad Gateway` is likely related to PHP-FPM.

> which -a php-fpm
> /usr/local/opt/php@7.4/sbin/php-fpm
> /usr/local/opt/php@7.2/sbin/php-fpm
> /usr/local/sbin/php-fpm
> /usr/sbin/php-fpm

Again, 7.4 is listed first in your PATH

> /usr/local/opt/php/sbin/php-fpm -v
> PHP 7.4.12 (fpm-fcgi) (built: Nov 14 2020 22:24:12)

.. and asking for its version via Homebrew's symlink confirms that 7.4 is the one that will run by default.

> sudo /usr/local/opt/php/sbin/php-fpm -y /usr/local/etc/php/7.4/php-fpm.conf --test
> [18-Nov-2020 21:34:23] ERROR: failed to open configuration file '/usr/local/etc/php/7.4/php-fpm.conf': No such file or directory (2)
> [18-Nov-2020 21:34:23] ERROR: failed to load configuration file '/usr/local/etc/php/7.4/php-fpm.conf'
> [18-Nov-2020 21:34:23] ERROR: FPM initialization failed

Uh oh. This is bad. It means your 7.4 install wasn't clean ... or has been tampered with.

> ls -al /Library/LaunchDaemons | grep homebrew
> -rw-r--r--   1 root  admin   657 18 Nov 21:33 homebrew.mxcl.dnsmasq.plist
> -rw-r--r--   1 root  admin   571 18 Nov 21:33 homebrew.mxcl.nginx.plist
> -rw-r--r--   1 root  admin   636 18 Nov 21:33 homebrew.mxcl.php@7.2.plist

Note how Homebrew's Daemons are set to load PHP 7.2 instead of 7.4
This suggests commands have been run to activate PHP 7.2 even though 7.4 is installed. 
And,  `brew services list` confirms that you've got 7.2 running instead of 7.4:
> Name          Status  User Plist
> dnsmasq       started root /Library/LaunchDaemons/homebrew.mxcl.dnsmasq.plist
> mysql@5.7     stopped      
> nginx         started root /Library/LaunchDaemons/homebrew.mxcl.nginx.plist
> php           stopped      
> php@7.2       started root /Library/LaunchDaemons/homebrew.mxcl.php@7.2.plist
> php@7.3       stopped      
> valet-php@7.1 stopped      
> valet-php@7.2 stopped

----

I think your situation is fixable by running the following:

`brew unlink php && brew link php@7.2` (to reset brew to be in sync with what's actually running, and prepare to run `valet use` below after some cleanup)
`brew remove php`  (to get rid of the unversioned php 7.4; will reinstall below)
`rm -rf  /usr/local/etc/php/7.4` (to get rid of config fragments)
`sudo brew services stop php@7.2`  (to shut down the unused one)
`valet use php@7.4` (to install the versioned @7.4 and configure it afresh, and configure it as primary)

And probably clean out old valet-plus stuff:
`brew remove valet-php@7.1`
`brew remove valet-php@7.2`
`brew untap valet-php`

**Comment by sultansawalha** [comment]
👍 Great. Appreciate all the help
