### ISSUE TITLE
site path detection for subdomain changed in latest release (2.13.1)

### ISSUE THREAD

**Issue by gehrisandro** [laravel/valet#998]
## Clear description of your problem
Site path detection behaviour for subdomains has changed in an unexpected way with the latest release which allows for case sensitive file systems.
In version 2.13.0 and before paths matching the site name (api.myproject) were prefered over paths matching only the base domain name (myproject).
Bug was introduced in commit #952 

## Expected behavior
Given you have two linked projects: "myproject" and "api.myproject"
When opening http://api.myproject.test in the browser, valet serves the site of "api.myproject".

## Current behavior
When opening http://api.myproject.test in the browser, valet serves the site of "myproject" instead.

## Steps to Reproduce
1. Create two two Laravel project. (ex. "myproject" and "myproject-api")
2. Link the two project with valet (`valet link myproject` and `valet link api.myproject`)
3. Now you should have two links similar to:

```bash
sandro@Sandros-MacBook-Pro ~ % ls -l .config/valet/Sites
total 0
lrwxr-xr-x  1 sandro  staff  32 Nov 23 21:17 api.myproject -> /Users/sandro/Code/myproject-api
lrwxr-xr-x  1 sandro  staff  28 Nov 23 21:15 myproject -> /Users/sandro/Code/myproject
```

### Output of these steps
Open both links (http://api.myproject.test and http://myproject.test) in your browser.
Both are pointing to the same project (myproject).

Before release 2.13.1 http://api.myproject.test pointed correctly to the api project (myproject-api).

## Possible solution
Change the detection behaviour to prefer paths with a matching site name over paths with a matching domain name.
I suggest a solution here: https://github.com/laravel/valet/pull/997

**Comment by mattstauffer** [comment]
Fixed in #997, tagged in https://github.com/laravel/valet/releases/tag/v2.13.2
